### ISSUE TITLE
Hi all!

### ISSUE THREAD

**Issue by denisdemaisbr** [svaarala/duktape#1029]
I'm starting on JS/Duktape and this works fine! [to my surprise with very low memory hungry]

Using on;
a powermac g4 [32-bit powerpc big-endian] on osx tiger 10.4 running! [compiled with gcc 4.x / xcode 2.5]
a desktop win7/64-bit on cygwin
and was running perfect on a [32-bit arm big-endian] property/closed os [unix-like]

I can run tests on this plataforms! [on new versions or patched versions!]

**Comment by svaarala** [comment]
Good to hear - there's ongoing work for a 2.0.0 release so there'll surely be some testing ahead :)

**Comment by denisdemaisbr** [comment]
fine! 
the project have a google groups or an aproprieated channel ?

**Comment by svaarala** [comment]
@denisdemaisbr The support mechanisms are listed on http://duktape.org/. Currently there's github for development related stuff (features, bugs, etc). There's also a github project for the duktape-wiki which is a natural place to request howtos and such. There's an IRC channel too, but no mailing list or similar at present.
