### ISSUE TITLE
Variable name supports UTF-8

### ISSUE THREAD

**Issue by yushli** [svaarala/duktape#103]
I wonder whether duktape support utf8 variable names? e.g.,
var my_变量=1;
my_变量++;
and 
var obj ={};
obj.变量1="hello";

**Comment by svaarala** [comment]
That is the goal, and e.g. the following works:

https://github.com/svaarala/duktape/blob/master/ecmascript-testcases/test-lex-utf8.js

The source file is interpreted in UTF-8, and characters comprising the identifier must match the IdentifierPart (IdentifierStart for the first character) production:

http://www.ecma-international.org/ecma-262/5.1/#sec-7.6

Duktape does make the assumption that source code is in UTF-8.

**Comment by svaarala** [comment]
Regarding your examples, at the moment:

```
var my_变量=1;
my_变量++;
print('count:', my_变量);
```

results in:

```
SyntaxError: error parsing token (line 1)
	duk_lexer.c:1272
```

Rhino accepts this so there's probably a bug in IdentifierPart parsing.  I'll look into it.

**Comment by svaarala** [comment]
There's a bug in forming the Unicode tables.  The first character, U+53D8, is not considered an IdentifierPart.  When running the Unicode table generator manually, it emits the following ranges (truncated):

```
0x3105 ... 0x312d
0x3131 ... 0x318e
0x31a0 ... 0x31ba
0x31f0 ... 0x31ff
0x3400
0x4db5
0x4e00
[no ranges here]
0x9fcb
0xa000 ... 0xa014
0xa016 ... 0xa48c
0xa4d0 ... 0xa4f7
0xa500 ... 0xa60b
0xa610 ... 0xa61f
0xa62a ... 0xa62b
```

This is caused by `UnicodeData.txt` not containing the CJK range explicitly, but rather as a range rule:

```
4E00;<CJK Ideograph, First>;Lo;0;L;;;;;N;;;;;
9FCB;<CJK Ideograph, Last>;Lo;0;L;;;;;N;;;;;
```

There are other ranges like this; I'll fix the Unicode range generator to handle these.

**Comment by svaarala** [comment]
Here are all the affected Unicode ranges (first codepoints of them anyway):

```
3400;<CJK Ideograph Extension A, First>;Lo;0;L;;;;;N;;;;;
4E00;<CJK Ideograph, First>;Lo;0;L;;;;;N;;;;;
AC00;<Hangul Syllable, First>;Lo;0;L;;;;;N;;;;;
D800;<Non Private Use High Surrogate, First>;Cs;0;L;;;;;N;;;;;
DB80;<Private Use High Surrogate, First>;Cs;0;L;;;;;N;;;;;
DC00;<Low Surrogate, First>;Cs;0;L;;;;;N;;;;;
E000;<Private Use, First>;Co;0;L;;;;;N;;;;;
20000;<CJK Ideograph Extension B, First>;Lo;0;L;;;;;N;;;;;
2A700;<CJK Ideograph Extension C, First>;Lo;0;L;;;;;N;;;;;
2B740;<CJK Ideograph Extension D, First>;Lo;0;L;;;;;N;;;;;
F0000;<Plane 15 Private Use, First>;Co;0;L;;;;;N;;;;;
100000;<Plane 16 Private Use, First>;Co;0;L;;;;;N;;;;;
```

Only the BMP ones are a compliance issue.

**Comment by svaarala** [comment]
Added a fix to "unpack" UnicodeData.txt in a prestep so that all ranges are expanded into individual characters before using the other Unicode parsing scripts. As a result the original example now works as intended.

**Comment by svaarala** [comment]
@yushli Could you confirm master is now fixed for you too?

There's a snapshot with the fix here (in case you don't have the Github repo checked and all the required stuff installed): http://duktape.org//snapshots/duktape-1.1.99-20150113114100-v1.1.0-17-gd5af3b2.tar.xz

**Comment by yushli** [comment]
Thanks for your quick response and fix! I can confirm that it works now. Hope this project become better and better.
