### ISSUE TITLE
parseInt base 16

### ISSUE THREAD

**Issue by aerogelio** [svaarala/duktape#1052]
I am testing py_mini_racer(V8) and pyduktape(duktape).

When i parse string to number base 16 passes the following:
V8:
n = parsetInt( '09', 16 ); #output = 9
duktape:
n = parseInt('09', 16); #output = 0

I am decrypting and this changes the result.
I don't know it is part duktape or pyduktape, greetings.

I try with other extension for python I get the same result.

**Comment by denisdemaisbr** [comment]
@aerogelio whats version of duktape you are using?

**Comment by svaarala** [comment]
@aerogelio There are some differences between engines how they parse `09` which is an invalid octal sequence. Some parse it as decimal:

```
$ nodejs
> process.version
'v6.7.0'
> 09
9
```

Others like Duktape reject it as SyntaxError:

```
((o) Duktape [linenoise] 1.99.99 (v1.5.0-868-gd69f9da-dirty)
duk> x = 09
SyntaxError: invalid number literal (line 1)
    at [anon] (input:1) internal
    at [anon] (duk_lexer.c:1683) internal
```

`parseInt()` rejects any trailing garbage which would otherwise cause a SyntaxError. For example, `parseInt('123xyz')` parses as 123. So in the case of "09", Duktape treats the digit 9 as a syntax error and just parses the input as if it was "0".

This behavior has been revised a few times, I'll recheck it against ES6.
```

**Comment by fatcerberus** [comment]
@svaarala Should it not be parsed as 9 in this case, regardless of the leading zero, since the radix is explicitly specified as 16 in the `parseInt()` call?

**Comment by svaarala** [comment]
Oh, missed that part, that should be the case. Quickly testing, that should work at least in Duktape 1.5.0 and above:

```
((o) Duktape 1.5.0 (v1.4.0-421-g8e90d3d-dirty)
duk> parseInt('09', 16)
= 9
```

Master:
```
((o) Duktape [linenoise] 1.99.99 (v1.5.0-858-g490f634-dirty)
duk> parseInt('09', 16)
= 9
```

**Comment by svaarala** [comment]
Seems to be broken in Duktape 1.1.x but fixed in Duktape 1.2.x and above.

**Comment by svaarala** [comment]
@aerogelio Your pyduktape is probably using a very old Duktape version (1.1.x or 1.0.x) where this was indeed an issue. You can verify that by evaling `Duktape.version`. If you can update the Duktape version in the pyduktape binding that should fix the problem.

**Comment by fatcerberus** [comment]
Regarding invalid literals in particular, It's worth noting that SpiderMonkey parses a literal `09` as decimal 9:
```
C:\src\mozilla-central\js\src\build_OPT.OBJ\dist\bin>js --version
JavaScript-C52.0a1

C:\src\mozilla-central\js\src\build_OPT.OBJ\dist\bin>js
js> 09
9
js>
```

As does V8:
```
C:\src\chromium\v8\out.gn\x64.release>d8
V8 version 5.6.0 (candidate)
d8> 09
9
d8>
```

So Duktape's behavior is probably surprising from a real-world perspective.

**Comment by fatcerberus** [comment]
BTW, ES6 adds the notation `0oXXX` for octal literals.  In that case invalid sequences are rejected:

```
d8> 0o777
511
d8> 0o9
(d8):1: SyntaxError: Invalid or unexpected token
0o9
^^
SyntaxError: Invalid or unexpected token
```

**Comment by svaarala** [comment]
@fatcerberus That lenient octal parsing behavior varied across engines IIRC, and I chose the stricter route because the behavior is very confusing with respect to typos. But if it is now the dominant behavior then it may be worth changing Duktape to match that.

Adding an explicit octal literal would make sense - I'll open a pull for that, or perhaps a pull with both changes at the same time.

**Comment by svaarala** [comment]
Ok, #1057 will make both changes.

**Comment by fatcerberus** [comment]
> That lenient octal parsing behavior varied across engines IIRC, and I chose the stricter route because the behavior is very confusing with respect to typos.

Agreed, as I noted above it's very confusing that e.g. `09` is parsed as decimal but e.g. `010` is parsed as octal.  But yeah, that seems to be the dominant behavior for better or worse.

**Comment by svaarala** [comment]
Btw, older V8 used to handle `parseInt('078')` as 7 (treating 8 as garbage to be ignored) and `parseInt('088')` as 0 (treating both 8s as garbage).

Newer V8 `parseInt()` handles everything in decimal, so `parseInt('077')` is 77 (and not 63 like the literal `077`), `parseInt('078')` is 78, etc:

```
> 077
63
> parseInt('077')
77
```

Duktape already has this behavior too so only the literal needs changing.

**Comment by fatcerberus** [comment]
SpiderMonkey `parseInt()` behavior matches:
```js
js> parseInt("077")
77
js> parseInt("09")
9
js> parseInt("010")
10
```

However literals are interpreted in octal if possible (likely for compatibility reasons):
```js
js> 077
63
js> 09
9
js> 010
8
```

**Comment by svaarala** [comment]
This is fixed in master:
```
duk> n = parseInt( '09', 16 ); n
= 9
```
