### ISSUE TITLE
Does Duktape guarantee key enumeration order?

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1053]
I wrote the following code to write binary data to a file, but then I realized it might not work properly because Duktape is still an E5.1 engine at heart:
https://github.com/fatcerberus/minisphere/blob/master/assets/system/modules/struct.js#L226-L254

The order of properties in the descriptor object is supposed to determine the layout of the binary structure when written.  If this doesn't work, `writeStruct()` will need to be refactored to use an array to describe the structure.

I know that ES6 specifies the following enumeration order:
* Array indices in ascending order, followed by:
* String keys in insertion order, followed by:
* Symbols in insertion order

I believe E5.1 leaves the key order entirely up to the implementation.  So I'm wondering, does Duktape specificially have any guaranteed order, and if so, what is it?

**Comment by svaarala** [comment]
It does guarantee an enumeration order but it doesn't match the ES6 requirements for array indices when an array becomes sparse and the array part is abandoned. If an object never gets an array part (like an object), array indices are treated like any other keys and won't enumerate first.

**Comment by svaarala** [comment]
So, what matters to `.defineProperties()` and any other place where object literals are used and expected to keep their key order, that holds for everything except array index keys which will be treated just like any other key (insertion / literal appearance order) for non-array objects:

```
duk> obj = { foo: 123, 1: 234, bar: 345 };
= {foo:123,"1":234,bar:345}
duk> Object.keys(obj);
= ["foo","1","bar"]
```

ES5 doesn't require even this behavior but there's plenty of real world code that will fail if key order isn't preserved so it was made official in ES6. I find the array index requirement *for non-array objects* very weird; Node.js:

```
> obj = { foo: 123, 1: 234, bar: 345 };
{ '1': 234, foo: 123, bar: 345 }
> Object.keys(obj);
[ '1', 'foo', 'bar' ]
```

I find this automatic reordering for plain objects very odd but it's probably easier for engines doing hidden classes and such.

**Comment by fatcerberus** [comment]
It also makes sense from a duck typing perspective, in that array-*like* objects such as `arguments` can be counted on to enumerate like real arrays.

**Comment by svaarala** [comment]
Sure, it makes sense in some ways but not in others. I would expect an object literal to preserve order for example. But since it's part of ES6, it's not important for me to agree, I just need to comply ;)

**Comment by svaarala** [comment]
But in any case, as long as enumeration is based on creating the enumerated sequence in advance to an enumerator object, it's not difficult to sort the sequence according to some criteria after it's first created. That's already done in a few special cases.

Of course it'd be ideal to enumerate without creating the sequence in advance, but that's actually pretty difficult with mutation, etc.

**Comment by fatcerberus** [comment]
Anyway, it's good to know my binary file writer will work as designed in Duktape, thanks :)

**Comment by fatcerberus** [comment]
Does that "keys in order of appearance" also apply to `JSON.parse()`?

**Comment by svaarala** [comment]
I don't remember off-hand what the specification says about it - but it does apply to Duktape `JSON.parse()`.

I'll open a pull for ES6 enumeration order. It should be a pretty easy fix because it's a post-process sorting step. The sorting is optimized so that for nearly correct orders (which is already the case for dense arrays etc) the sorting operation is fast, so while it will have some impact, it should be quite limited. Symbol sorting will then be easy to handle too.

**Comment by svaarala** [comment]
#1054 is the pull, just a placeholder for now.

**Comment by mamod** [comment]
I wanted to ask the same question long time ago but after testing I found that duktape preserve keys order even though ES5 doesn't guarantee that, so thank you @svaarala for predicting that this behavior will have a real world  usage :+1:

**Comment by svaarala** [comment]
Contrary to what's said above, unfortunately ES6 guarantees are also not very strong, see https://github.com/svaarala/duktape/pull/1054#issuecomment-258649921. But #1054 provides the same ordering for `for-in`, `Object.keys()`, `Object.getOwnPropertyNames()`, etc, which is least surprising for users.
