### ISSUE TITLE
Add missing ES2015 Object built-ins

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1067]
- [x] Object.assign() - #1064
- [x] Object.getOwnPropertySymbols() - will come out of symbol support
- [x] Object.is() - #1068

**Comment by fatcerberus** [comment]
`Object.is()` looks very easy, Duktape already has an internal SameValue() helper.

**Comment by svaarala** [comment]
Yeah, I'm implementing it right now to get it out of the way.

**Comment by svaarala** [comment]
```
duk> Object.is(-0, +0)
= false
duk> Object.is(+0, +0)
= true
```

**Comment by fatcerberus** [comment]
Oh!  That's nice, previously a check for negative zero was rather dense: `n === 0 && (n / 0) < 0`
