### ISSUE TITLE
longjmp state attached to heap instead of hthread

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1081]
I'm currently attempting to use duktape in a project where we have our own coroutine support.  This means I have implemented the JavaScript methods "StartCoroutine" and "Yield" as C functions which trigger coroutine behaviors in our own C code.  By doing this we're able to achieve coroutine behavior without relying on the more limited form of coroutines available in duktape.

Unfortunately, our code interacts negatively with the duktape longjmp code, particularly when an error is thrown and the system has more than one active coroutine.  Because there is only one longjmp state (`duk_ljstate`) per heap (instead of per thread), its state becomes invalid (or corrupted?) as coroutines process.

I was able to solve this problem by moving the longjmp state structure (`duk_ljstate`) from `duk_heap` to `duk_hthread` and making the associated changes.  The modification was relatively painless.

Is this a change you'd be interested in looking at?

**Comment by svaarala** [comment]
@beevik Did you look into using the `duk_suspend()` and `duk_resume()` calls?

By default Duktape doesn't support the situation where there are multiple entries into the Duktape heap; with `duk_suspend()` and `duk_resume()` that is relaxed a bit. When calling `duk_suspend()` the longjmp state is saved and a corresponding call to `duk_resume()` then restores it.

I'm not sure if just making the ljstate thread specific is enough, there may be some other state that won't work correctly if you effectively switch the active thread without Duktape being aware of it.

But I'll be happy to try to figure out a solution if `duk_suspend()` and `duk_resume()` is not workable.

**Comment by beevik** [comment]
Oh, I'm using 1.5.1, so I didn't know about `duk_suspend` and `duk_resume`.  Is there anything I can do in 1.5.1?

**Comment by svaarala** [comment]
Not at present, but I'm making a 1.6.0 release with `duk_suspend()` and `duk_resume()` backported - would that work for you?

**Comment by beevik** [comment]
I can certainly try it out. My knowledge of the internal workings of duktape is still quite limited, so I'd be much more comfortable using your recommended approach than hacking my own.

**Comment by svaarala** [comment]
Ok, I'll put some effort into cherry-picking the 1.5.2 and 1.6.0 fixes into the relevant branches. Maybe you could then try it out from the branch before an actual release?

**Comment by beevik** [comment]
Would be happy to.

**Comment by beevik** [comment]
By the way, I just wanted to express my gratitude for your responsiveness.  It's refreshing to find an open-source project that is so actively maintained.

**Comment by fatcerberus** [comment]
@beevik Sami's responsiveness is a big part of why I haven't already switched to SpiderMonkey or V8 in my game engine, minisphere.  Now I'm a regular contributor :)

**Comment by svaarala** [comment]
Now the project just needs an active contributor from Asia and we could be responsive 24h ;-)

**Comment by svaarala** [comment]
@beevik Alright, `v1-maintenance` branch should now have all fixes for v1.5.2 included, and backported support for `duk_suspend()` and `duk_resume()`. It passes the basic API and Ecmascript tests but I haven't yet tested it thoroughly (asserts, valgrind, various shuffle/gc stress tests, etc).

**Comment by beevik** [comment]
Great, I'll try it out today and report back soon.  Thanks!

**Comment by beevik** [comment]
Just tried it.  It works!  I'll close this issue.

Thanks again.

**Comment by svaarala** [comment]
@beevik Great to hear :-)

If you encounter any other threading issues let me know -- multiple thread support (suspend/resume) is rather barebones but it's in use by at least two applications. But there's definitely room for improvement.

**Comment by beevik** [comment]
FYI, we're using the [**sc** coroutine library](https://github.com/rhoot/sc ) my colleague built.  This low-level, cross-platform coroutine library allows us to introduce full coroutine support with duktape, even when the call stack includes native C calls.  If you're interested in learning more, let me know.

**Comment by svaarala** [comment]
Sounds cool - that would make a nice Wiki Howto for other users :)

**Comment by svaarala** [comment]
Solving the general problem of yielding anywhere without relying on an actual thread switch (which has some portability issues I wouldn't want to tackle in Duktape core) is possible but it's rather awkward because the relevant C bindings need to be aware of the process.

So it'd be awesome if there was a "you can do this" recipe for generic coroutine support, and from the looks of it, `sc` is quite portable too.

If you have any example code demonstrating the technique (the `duk_suspend()` and `duk_resume()` sites for example) I can write a Wiki article based on that, and point to it from the coroutines/threading Guide sections.

**Comment by svaarala** [comment]
@andoma might be interested in this solution too, not sure if the limitations have been an issue in this case :)
