### ISSUE TITLE
Make finalizer guarantees exact

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#109]
Currently a finalizer may run twice in special cases even when the object is not rescued. Make the guarantees exact:

- If an object is not rescued, its finalizer is executed once.
- If an object is rescued, its finalizer is executed once per rescue cycle.

**Comment by darkuranium** [comment]
I do wonder --- in what cases *specifically* can the finalizer run twice even when the object is not rescued?

**Comment by svaarala** [comment]
@darkuranium see #108 for one case (probably fixed now though).

**Comment by svaarala** [comment]
Whatever remains is probably easy to fix, but this needs testcases to cover all the cases, and possibly some options to force all the cases to happen (similar to DUK_OPT_GC_TORTURE).

**Comment by svaarala** [comment]
I'm trying to fix this for 1.4.0 but it seems pretty hard to come up with a repro case. If anyone is encountering this in practice and has a way to reproduce a finalizer re-entry (other than when the object is actually rescued by the finalizer) it'd be very helpful.

In any case, it should be enough to make `duk_hobject_run_finalizer()` check for the `DUK_HOBJECT_FLAG_FINALIZED`:

- If `DUK_HOBJECT_FLAG_FINALIZED` is set, don't run the finalizer again.
- If `DUK_HOBJECT_FLAG_FINALIZED` is not set, set it, and run the finalizer.
- Remove `DUK_HOBJECT_FLAG_FINALIZED` writes elsewhere so that it's tied to that specific spot only.
