### ISSUE TITLE
ESP32 port: Some arithmetic and boolean bitwise operations not working

### ISSUE THREAD

**Issue by nkolban** [svaarala/duktape#1107]
In the port to ESP32, I seem to find that bitwise operations are not working.  For example, running:
`1 & 1` returns 0 and `8 >> 1` returns 0 and `10%3` returns 0.  I am currently compiling with the default `duktape_config.h` and have made no over-rides.  I am fully of the opinion that there is likely some configuration option in the build process that needs tweaked and am looking for guidance or tests to run to resolve the issue.

**Comment by svaarala** [comment]
Diagnosing on the IRC channel e.g. `10.7 | 0` returns 0, and `fmod()` seems a possible candidate.

**Comment by nkolban** [comment]
Aha ... it turned out to be an ESP32 bug ... see this related issue on the ESP32 driver libraries:

https://github.com/espressif/esp-idf/issues/83

I am reaching out to the ESP32 developers to see if I can get this resolved ...   am closing this issue as it is nothing to do with Duktape.  The pointer from svaarala that this might be fmod() related was the golden clue.
