### ISSUE TITLE
Add an internal duk_hproxy type

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1136]
This would improve Proxy performance and simplify handling a bit. Impact on footprint is uncertain: on the one hand simplified handling reduces code, but additional GC handling code is introduced.

**Comment by fatcerberus** [comment]
I think this change at least makes sense: Proxy objects are about as "exotic" as they come so it's rather awkward that it's internally just a normal `duk_hobject` now.  When I was implementing Reflect, I saw some of the internal proxy handling code and it seemed a bit messy.

**Comment by svaarala** [comment]
This change would only affect the way how e.g. the traps table (handlers) are accessed - they are currently internal properties which needs an explicit lookup etc. But as for the other semantics parts like where proxy checks are needed, how to handle traps, etc, there would be no real difference.

For example, traps cannot be cached and must always be looked up from the handlers object because it may be changed on-the-fly. A reference to the handlers table *can* be stored as a direct `duk_hobject` pointer though which removes one lookup. The trap lookup still remains.

**Comment by svaarala** [comment]
Implemented in #1500.
