### ISSUE TITLE
Add example for compiling with musl

### ISSUE THREAD

**Issue by highpost** [svaarala/duktape#116]
[musl](http://www.musl-libc.org/) is a new C Standard Library for embedded devices. For example, the [OpenWRT Linux distro](https://openwrt.org/) is beginning to support it. Here's a [feature comparison matrix](http://www.etalabs.net/compare_libcs.html).

**Comment by svaarala** [comment]
Did you have a problem in compiling with musl?

**Comment by highpost** [comment]
It seems to work fine. I should have added a note on how to use it. On
Ubuntu, just install musl-tools:

sudo apt-get install musl-tools

and then change the CC definition in Makefile.hello to use the musl-gcc
wrapper:

CC      = musl-gcc

There is a way to configure the wrapper to use clang, but I'm still trying
to figure that out.

**Comment by svaarala** [comment]
Do you have a concrete suggestion what should be changed in Duktape for musl usage?  Some possibilities I can think of:

- Provide a musl example Makefile (perhaps Makefile.hello-musl)

- Add a musl section to the website

Btw, note that the Makefiles in the dist package are just simple examples of what you would do yourself. They're not intended to be actually used for your own project as they really can't cover all the compilers and platforms people are working with.

**Comment by svaarala** [comment]
@highpost Any suggestions for a Duktape change (see above)? :)

**Comment by technosaurus** [comment]
Most musl users should already have CC set to musl-gcc.  The biggest hindrance to it building properly is if the makefile has CC = gcc instead of CC ?= gcc.  This also affects compiling with other compilers like clang or tcc, but is a common occurrence in many packages.

**Comment by svaarala** [comment]
Just to be clear - there's no "official" Makefile for Duktape - the intent is that you embed it into whatever build model you have for your application :-)

**Comment by svaarala** [comment]
Portability notes will be handled in Wiki so I'll close this.
