### ISSUE TITLE
Print undefined

### ISSUE THREAD

**Issue by AndreyArsov** [svaarala/duktape#1167]
Using the following build

 *  Git commit: 458018a88649ec249f47737aeb2807616167cfd9
 *  Git describe: v1.5.0-1123-g458018a
 *  Git branch: master

I get the error that print is undefined as follows:

Attached to duktape debugger.
Exception thrown @C:\code\duktape\dist-files\mandel.js:45: ReferenceError: identifier 'print' undefined
Exception thrown @C:\code\duktape\dist-files\mandel.js:52: ReferenceError: identifier 'print' undefined
Disconnected: Target detached: ( 0 )  

Is this a normal behavior? I see that the hello sample provides native_print api.
From the documentation it follows that print should be available, but probably I have messed up the compile options.

Can anyone clarify?

**Comment by svaarala** [comment]
`print()` is no longer automatically provided in master because it had portability issues (namely an assumption on I/O and printf()) and retargetability issues (redirecting it to a different place).

Duktape.org still documents Duktape 1.x which provides `print()`.

**Comment by svaarala** [comment]
Here are replacements for the bindings that you can include in your build:

- https://github.com/svaarala/duktape/tree/master/extras/print-alert

**Comment by AndreyArsov** [comment]
Thanks, Sami.
