### ISSUE TITLE
Compiler documentation is missing

### ISSUE THREAD

**Issue by rburchell** [svaarala/duktape#117]
duk_js_compiler.c:20 says: See doc/compiler.txt for discussion on the design.

but this file is absent. git history does not give any clues about if it ever did.

**Comment by svaarala** [comment]
I have a bunch of design documents that need a lot of cleanup and compiler documentation is one of them. Hopefully I'll have time to clean a few more for the next release :)

**Comment by svaarala** [comment]
I cleaned up a very old compiler document and merged it to master:

- https://github.com/svaarala/duktape/blob/master/doc/compiler.rst

It's not fully up-to-date but should provide a reasonable overview of what's going on.
