### ISSUE TITLE
String.fromCharCode not working for 32-bit code points

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#120]
To reproduce: just do
    String.fromCharCode(0x108001)
which erroneously produces the character 0x8001 "老".

Changing the "duk_to_uint16" in duk_bi_string_constructor_from_char_code to "duk_to_uint32" fixes it. I guess this is not worth a pull request...

**Comment by svaarala** [comment]
Sounds straightforward, I'll put in a fix. Thanks!

**Comment by svaarala** [comment]
Oh, now I remember why this happens:

- http://www.ecma-international.org/ecma-262/5.1/#sec-15.5.3.2

Ecmascript compliance requires a ToUint16() coercion:

    An argument is converted to a character by applying the operation ToUint16 (9.7) and regarding the resulting 16-bit integer as the code unit value of a character.

So fixing this breaks compliance a little bit.

**Comment by HouQiming** [comment]
Thanks for the quick response! 

I guess it would make more sense to add a "DUK_OPT_NO_..." option and mention the compliance issue in the documentation. Currently both the code and the Guide more or less implies that String.fromCharCode supports the full UTF-8 range or Unicode range.

Personally I'm fine either way since I need a 4-byte UTF-8 char in my application...

**Comment by svaarala** [comment]
Yeah, I'll make the change and add a compliance option.

**Comment by svaarala** [comment]
The fix is now in master, I'm closing this.  If the fix doesn't work for you, please reopen :)
