### ISSUE TITLE
Problems switching on 16-bit field header reductions

### ISSUE THREAD

**Issue by nkolban** [svaarala/duktape#1205]
Following the instructions here:

https://github.com/svaarala/duktape/blob/master/doc/low-memory.rst

I changed my duk_config to the following:
```
#define DUK_USE_REFCOUNT16
#define DUK_USE_STRHASH16
#define DUK_USE_STRLEN16
#define DUK_USE_BUFLEN16
#define DUK_USE_OBJSIZES16
#undef DUK_USE_HSTRING_CLEN
```

Now when I try and compile, I get lots of and lots of compilation errors ... here are some examples:

```
CC src/duktape.o
duk_unicode_support.c: In function 'duk_unicode_case_convert_string':
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_util.h:147:41: note: in definition of macro 'DUK_BW_INIT_PUSHBUF'
duk_unicode_support.c:1024:31: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_unicode_support.c:1029:20: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_api_bytecode.c: In function 'duk__dump_hstring_raw':
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_api_bytecode.c:54:8: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_api_bytecode.c: In function 'duk__dump_string_prop':
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_util.h:221:49: note: in definition of macro 'DUK_BW_ENSURE_RAW'
duk_api_bytecode.c:97:41: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_util.h:223:55: note: in definition of macro 'DUK_BW_ENSURE_RAW'
duk_api_bytecode.c:97:41: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_api_bytecode.c: In function 'duk__dump_varmap':
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_util.h:221:49: note: in definition of macro 'DUK_BW_ENSURE_RAW'
duk_api_bytecode.c:171:43: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_hstring.h:94:62: error: 'duk_heaphdr_string' has no member named 'h_strextra16'
duk_util.h:223:55: note: in definition of macro 'DUK_BW_ENSURE_RAW'
duk_api_bytecode.c:171:43: note: in expansion of macro 'DUK_HSTRING_GET_BYTELEN'
duk_api_bytecode.c: In function 'duk__dump_formals':
```

**Comment by svaarala** [comment]
Some of the lowmemory options depend on one another but that set seems correct at a glance.

Could you double check that there isn't e.g. a `#define` and an `#undef` for any of the options? The cleanest way to enable/disable options would be via `tools/configure.py` but editing `duk_config.h` manually is also workable.

**Comment by nkolban** [comment]
I double checked my configuration and believe that the settings are as stated ... just in case, I have attached the duk_config.h that I am using assuming (if you were like me), you'd want to see for yourself.   Screen sharing available on request.


[duk_config_h.txt](https://github.com/svaarala/duktape/files/659990/duk_config_h.txt)

**Comment by svaarala** [comment]
It seems there's a bug in master with the 16-bit fields when reference counting is disabled. That `h_strextra16` is assumed by `duk_hstring` but is incorrectly not present without reference counting.

For now, could you enable reference counting - I'll fix the incorrect assumption tomorrow.

**Comment by svaarala** [comment]
There's currently no commit regression coverage for 16-bit fields + no refcounting: ajduk covers 16-bit fields but has refcounting enabled, while stripsize has no refcounting but 32-bit fields. I'll add that commit test  coverage at the same time.

**Comment by nkolban** [comment]
Howdy ... thanks for the response.  Could you elaborate on "For now, could you enable reference counting" ... I don't know what that means.

**Comment by svaarala** [comment]
Enable `DUK_USE_REFERENCE_COUNTING` and `DUK_USE_DOUBLE_LINKED_HEAP`.
