### ISSUE TITLE
Regexp parse error - /[\0]/

### ISSUE THREAD

**Issue by josh** [svaarala/duktape#122]
Hey @svaarala,

Hit another weird regexp parsing case.

``` js
/[\0]/
```

throws "invalid decimal escape" syntax error.

``` js
"got \0".replace(/[\0]/, "null")
// "got null"
```

The https://github.com/mishoo/UglifyJS2 minifier project makes use of this Regexp. https://github.com/mishoo/UglifyJS2/blob/ae07714927f44790e40628cde4fa57bc2c4cb076/lib/output.js#L90

Related #74 and #86.

**Comment by svaarala** [comment]
This one isn't a "real world" issue but seems lika a straightforward bug in Duktape regexp parser.

Fix coming shortly :)

**Comment by svaarala** [comment]
Fix is now in master and the above testcase now passes.

**Comment by josh** [comment]
Thanks @svaarala
