### ISSUE TITLE
Possible mistake recognizing end of comment inside a string

### ISSUE THREAD

**Issue by nkolban** [svaarala/duktape#1224]
I had a piece of JS code that looked as follows:

```
	http.request({
		address : address,
		port : 80,
		path : "/api.php?city=Dallas",
		headers : {
		    "Accept": "*/*"
		}
	}, function(response) {
...
```

I wanted to comment out the headers object so changed my logic to:
```
	http.request({
		address : address,
		port : 80,
		path : "/api.php?city=Dallas"
/*
		headers : {
		    "Accept": "*/*"
		}
*/
	}, function(response) {
...
```

Now I get the report of a syntax error.  If I add space in the value of the "Accept" property to make its value: `"* /*" ... the syntax error goes away.

**Comment by svaarala** [comment]
Ecmascript doesn't recognize string literals inside comments. For example:

```js
/*
var test = '*/*';
*/
```

will cause a SyntaxError. Here's Node output for comparison:

```
$ nodejs /tmp/test.js
/tmp/test.js:2
var test = '*/*';
              ^
SyntaxError: Unexpected token *
    at Object.exports.runInThisContext (vm.js:76:16)
[...]
```

So this is unfortunately correct behavior.

**Comment by nkolban** [comment]
Ahh ... thank you sir.  How odd/interesting.
