### ISSUE TITLE
Add C API macros for creating internal keys and symbols

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1230]
Add something to hide the concrete prefixes (`\xFF` etc). At the very minimum a macro for `DUK_HIDDEN_SYMBOL()` a.k.a. an internal key would be useful.

**Comment by fatcerberus** [comment]
In the spirit of abstraction, should there also be an API for checking if a value is a symbol, e.g. `duk_is_symbol()`?

**Comment by svaarala** [comment]
That could be added too - but for symbols both `duk_is_string()` and `duk_is_symbol()` would be true for now.

**Comment by fatcerberus** [comment]
Yeah, that's okay; the idea was that one could go:

```c
str = duk_require_string(ctx, 0);
if (duk_is_symbol(ctx, 0)) {
    duk_error(...);
}
```

...without relying on a particular internal symbol representation.

**Comment by svaarala** [comment]
Maybe I'll add that to the 2.0.0 release, it seems relatively low risk for maintenance after all.

**Comment by svaarala** [comment]
Macros now exist (for 2.2.0 release) and duk_is_symbol() was added earlier, so closing.
