### ISSUE TITLE
Accept ArrayBuffer as duk_push_buffer_object() argument

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1236]
This would allow one to push an arbitrarily configured ArrayBuffer first, and then construct a view on top of it. When pushing a Uint8Array (for example) over a plain buffer, the ArrayBuffer .byteOffset and .byteLength are automatically computed based on the view's offset/length and can't be fully controlled now.

**Comment by fatcerberus** [comment]
Hm, going off on a tangent a bit, but with the current API this would require 3 steps:
* Push the backing plain buffer (usually fixed)
* Push the ArrayBuffer and configure it
* Push the TypedArray or DataView

It would be nice to be able to skip the first step.

**Comment by svaarala** [comment]
I agree - the intent longer term would be to make the C API look as closely like the Ecmascript environment as possible. So most likely there would be an API for `duk_push_arraybuffer()` for example.

**Comment by svaarala** [comment]
Unassigning from 2.2 because this needs more changes than anticipated to handle stacking of offsets correctly:
- Assume plain buffer base exists and has length 32.
- Create ArrayBuffer on top of plain buffer with offset=10, length=14. Byte offsets [10,24[ relative to plain buffer.
- Create Uint32Array on top of ArrayBuffer with offset=4, length=2. Byte offsets [4,12[ relative to ArrayBuffer, and [14,22[ relative to plain buffer. 

This is conceptually workable, but for the Uint32Array:
- External `.byteOffset` should be relative to the ArrayBuffer -> 4.
- Internal `->offset` should be relative to the plain buffer, and have a different value -> 14.

However, current internal representation doesn't support different internal and apparent offset.

It would be OK to accept ArrayBuffers as base values provided that their byteOffset was zero. In general it would be ultimately simpler if ArrayBuffers never had a non-zero offset as the Ecmascript APIs don't support it.

**Comment by svaarala** [comment]
On the other hand new Uint32Array(ab) where 'ab' is manually constructed with a non-zero offset is already accepted, the C API should just behave the same way. Documentation should mention that non-zero ArrayBuffer offsets are not recommended.

**Comment by svaarala** [comment]
The C API now matches new TypedArray() for ArrayBuffer arguments with one exception: the C API explicitly allows creation of an "unbacked" typed array just like it is allowed for plain buffers.
