### ISSUE TITLE
Does duk_destroy_heap() need to call free(ctx)?

### ISSUE THREAD

**Issue by gubaojian** [svaarala/duktape#1239]
duk_destroy_heap  only free,  ctx.heap;  ctx pointer is not free.   is need call free(ctx) after duk_destroy_heap(ctx) ?

duk_destroy_heap(ctx)
free(ctx)

**Comment by svaarala** [comment]
You don't need to free `ctx` explicitly. The `ctx` argument to duk_destroy_heap() identifies the Duktape heap and everything attached to it. This includes all Duktape threads (contexts), including the one you call duk_destroy_heap() with.

Once you've called duk_destroy_heap() it's important *not* to use the `ctx` for anything. It has already been freed and using it will cause memory unsafe behavior.

**Comment by svaarala** [comment]
@gubaojian I'll close this now, please reopen if something was left unanswered.
