### ISSUE TITLE
[Question] Call JavaScript function from C

### ISSUE THREAD

**Issue by Memorix101** [svaarala/duktape#1243]
Hey,

It's not pretty clear to me how I can call functions from JavaScript code within my C code.

For example I run this code 

````
int main(int argc, char *argv[]) {
  duk_context *ctx = duk_create_heap_default();
  duk_eval_file(ctx, "test.js");
  duk_destroy_heap(ctx);
  return 0;
}
````

and inside my test.js is a function like

`````
function GotCalledFromC()
{
   // stuff 
} 
`````

How would it work to call this function in C code ?

Thank you :)

**Comment by fatcerberus** [comment]
```c
duk_get_global_string(ctx, "GotCalledFromC");
/* push arguments here */
duk_call(ctx, num_args_pushed);
```

**Comment by svaarala** [comment]
Calling Ecmascript code from C and vice versa is covered in Getting started with concrete examples: http://duktape.org/guide.html#gettingstarted.

**Comment by fatcerberus** [comment]
Note that if the script is declared strict (`"use strict"` on first line of file) then the above won't work because the function declaration will be local to the file.  In that case you would need to find an alternate method to export it.

**Comment by fatcerberus** [comment]
One important consideration is that, with the example above, if the JavaScript function throws an error your process will crash.  To avoid that, you should look into `duk_pcall()` (protected call).

**Comment by svaarala** [comment]
@Memorix101 The getting started `processLines()` case should be similar, the pieces in the example are:

```
duk_push_global_object(ctx);
duk_get_prop_string(ctx, -1 /*index*/, "processLine");

duk_push_string(ctx, line);

if (duk_pcall(ctx, 1 /*nargs*/) != 0) {
    printf("Error: %s\n", duk_safe_to_string(ctx, -1));
} else {
    printf("%s\n", duk_safe_to_string(ctx, -1));
}
duk_pop(ctx);  /* pop result/error */
```

The example uses `duk_pcall()` to avoid the uncaught error issue mentioned by @fatcerberus above.

**Comment by svaarala** [comment]
Hmm, I'm moving the getting started examples into the Wiki for a 2.0.0 release. The examples are now in a story form involving several steps. Maybe specific questions like this could go into some "mini howtos" so that they'd be more easily readable?

**Comment by svaarala** [comment]
@Memorix101 Added https://github.com/svaarala/duktape-wiki/issues/158 to consider adding specific Howtos for the wiki.

I'm closing this now - please reopen if there's still something unanswered.
