### ISSUE TITLE
How to run Duktape on STM32?

### ISSUE THREAD

**Issue by fkeujjpdc** [svaarala/duktape#1244]
this project is a greate,if there are some demo on different device is better

**Comment by svaarala** [comment]
@fkeujjpdc The Duktape repo doesn't provide direct support for specific targets other than the necessary configuration support to compile Duktape on the target. The remaining stuff like adding a main program, setting up a memory allocator, adding native bindings etc are handled separately elsewhere. For example, @nkolban is using Duktape on ESP32 and that project has its own repo: https://github.com/nkolban/duktape-esp32.

There's no current duktape-stm32 repo though. If you start one, I'd be happy to help with that. Also adding a Wiki article for "Duktape on STM32" would be fine.

**Comment by svaarala** [comment]
Google search found this, which may be useful: https://github.com/Catethysis/stm32js.

**Comment by nkolban** [comment]
I for one will be delighted to share experiences on getting Duktape running on the ESP32 ... which may be useful for other platforms.

**Comment by fkeujjpdc** [comment]
Thank you for your reply。I will learn more about these two links. @svaarala @nkolban
