### ISSUE TITLE
Unexpected buffer value when assigning a negative number

### ISSUE THREAD

**Issue by mamod** [svaarala/duktape#125]
After upgrading Duktape to version ``1.1.1`` I got [one failure test](https://github.com/mamod/Comojs/blob/master/tests/buffer/buffer.js#L38)  with buffers

Duktape ``v1.0``
````js
var b = Duktape.Buffer(10);
b[0] = -1;
print(b[0]); //--> 255
````

Duktape ``v 1.1.1``
````js
var b = Duktape.Buffer(10);
b[0] = -1;
print(b[0]); //--> 0
```
I've implemented a wrapper around duktape Buffer to make it compatible with node's buffers so I'm running node's buffer tests.

**Comment by svaarala** [comment]
This has been fixed in master:

```
((o) Duktape 1.1.99 (v1.1.0-134-g5c74ffe)
duk> var b = Duktape.Buffer(10); b[0] = -1; print(b[0]);
255
```

If this is breaks something concretely I can add the fix to the 1.1.2 fix list too.

**Comment by mamod** [comment]
For me its not of that importance and only breaks one test :) so fixing in 1.2.0 is good enough.

Sorry, I had to indicate that this might be a ``Two's complement`` buffer issue, so I'm not sure if changing the title to ``when assigning -1`` is clear as the bug is the same with all negative values, I guess it's better to say ``when assigning a negative number``  which will make more sense for future reference :)

**Comment by svaarala** [comment]
Added a note for 1.1.2 fix list, closing this.
