### ISSUE TITLE
Add a `global` binding, like Node.js

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1259]
Node.js has a `global` binding which by default refers to the global object.  This is quite useful as it is otherwise awkward (in the general case) to get at the global object in Ecmascript.  Consider adding such a binding (maybe optional) in Duktape.

Note that there is an active proposal to implement a Node.js-style `global` binding in Ecmascript proper, presently in Stage 3:
https://github.com/tc39/proposal-global

**Comment by svaarala** [comment]
Sounds good to me - I would prefer not to add the binding if it was only implemented as an engine specific thing (it would then make user code less portable) but if it's likely to become a standard it makes sense to add it early.
