### ISSUE TITLE
Cannot determine intptr type on Android NDK r8e

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#126]
When building my duktape-enabled program using my ancient version of Android NDK, it stopped at:

#error cannot determine intptr type

in duktape.h. I was building for armeabi-v7a with "LOCAL_CFLAGS += -O0 -fno-var-tracking-assignments"

Since duktape has been tested for android, I strongly suspect it's my NDK being too old. Is there a minimum NDK version requirement for building duktape?

BTW: the error was triggered by my own C file including duktape.h, not duktape.c itself.

Thanks

**Comment by svaarala** [comment]
Do you have `-std=c99`?

**Comment by HouQiming** [comment]
No. Is it required?

**Comment by svaarala** [comment]
Without C99 Duktape ends up guessing for types using "legacy means" which is not ideal and can sometimes fail. If you can add `-std=c99` Duktape can just use C99 types without doing type detection which is preferred.

**Comment by HouQiming** [comment]
Thanks!

After fixing my own code for the non-C99-ness, it did work.

Qiming

**Comment by HouQiming** [comment]
I would appreciate "-std=c99 recommended" in http://duktape.org/guide.html
though. Since the problematic code is in duktape.h, going this way requires
the user's code to be compiled with c99 too.

Qiming

**Comment by HouQiming** [comment]
I mean in the "Android" line of the Portability table.

**Comment by svaarala** [comment]
Yeah, `-std=c99` is recommended in the compiling section but since there's a concrete problem on Android without it, I'll add it to the Android line too.

**Comment by svaarala** [comment]
The change is now in master and will be deployed on 1.2.0 release at the latest.
