### ISSUE TITLE
how do I use require in the sample duk?

### ISSUE THREAD

**Issue by diacha** [svaarala/duktape#1262]
followed instructions http://duktape.org/guide.html#gettingstarted and tried to use require.  No matter what module I use I get the same type error:

```
$ ./duk
((o) Duktape 1.6.0 (v1.6.0)
duk> require('./fib')
TypeError: undefined not callable
    at [anon] (duk_js_call.c:770) internal
    at require () native strict preventsyield
    at global (input:1) preventsyield
duk> = undefined
Cleaning up...
```

**Comment by svaarala** [comment]
First, the website has now been updated for the 2.0.0 release which doesn't include a module loader by default. For 2.x can include one from `extras/module-duktape` (compatible with the 1.x loader) or `extras/module-node` (Node.js-like).

But since you appear to be using 1.6.0, you need to define a module search function as `Duktape.modSearch()`. See http://wiki.duktape.org/HowtoModules.html.

**Comment by diacha** [comment]
@svaarala thanks for a quick reply! When I checked the page last night the latest version was 1.6.0.

Do you have a JS example implementation of the node require?  The docs say you can make a module search function using the C API or with JS, and the example is currently in C

**Comment by svaarala** [comment]
Yeah, 2.0.0 was released today :)

There's no documentation beyond https://github.com/svaarala/duktape/tree/master/extras/module-node at present for the Node.js module loader. Ecmascript load/resolve functions would be directly analogous. For example:

```c
duk_eval_string(ctx,
    "({\n"
    "    resolve: function (requestedId, parentId) {\n"
    "        var resolvedId = ...;\n"
    "        return resolvedId;\n"
    "    },\n"
    "    load: function (resolvedId, exports, module) {\n"
    "        var source = ...;  // load source using resolvedId\n"
    "        return source;\n"
    "    }\n"
    "})\n");
duk_module_node_init(ctx);
```

There are obviously many ways to come up with the argument table that `duk_module_node_init()` expects; the functions don't have to be inline like that.

**Comment by svaarala** [comment]
I'll close this now - reopen if there's still something open.
