### ISSUE TITLE
Proxy == Proxy scenario

### ISSUE THREAD

**Issue by dug9** [svaarala/duktape#1278]
Q. is it true that there's no proxy trap I can override for
if(proxy1 == proxy2) //always false for me
so as to get my underlying native types (and their native pointers) for comparison?
And no way to override binary operator ==?
Thanks,
-Doug
more...
Sami thanks again for duktape - still using in freewrl.sf.net, and becoming more dependent on it.
...
I want to keep my objects wrapped in proxies, because after a test, someone wants to do something with it:
if( a == b){
a.field = something;
}
and I need the proxy for the field access.
...
If I over-ride valueOf, to return a naked pointer with duk_push_pointer, then I can do
if(proxy1.valueOf() == proxy2.valueOf()) // and get true
- but its a bit unconventional syntax, and not like if there was no proxy.
- and its the one of only 2 syntax glitches in otherwise great lazyproxy approach to wrapping native types.
more..
- right now I have only one proxy type, and do all my native specific types by attaching attributes 
- any tips / suggestions, or confirmation

**Comment by fatcerberus** [comment]
This is more a general JavaScript issue, not something Duktape specific.  For example, Node.js:

```
> var obj = {}
undefined
> var p1 = new Proxy(obj,{})
undefined
> var p2 = new Proxy(obj,{})
undefined
> p1 == p2
false
> p1 == obj
false
> p2 == obj
false
```

JavaScript doesn't have operator overloading, so unfortunately, I don't think there's a way to do what you want other than the `valueOf()` comparison you came up with.

**Comment by dug9** [comment]
Thank you fatcerberus for confirming.
-D
...
what about (p1 == p1)?
var obj = {};
var p1 = new Proxy(obj,{});
print('p1 == p1:'+(p1 == p1));  //true
//more complex proxies wrapping native types:
print('ground == ground:'+(ground == ground)); //false for me
Hypotheses: 
H0: I'm already over-riding a trap that gets called, and returns a different wrapper
H1: ????

**Comment by svaarala** [comment]
@dug9 If you're creating Proxy objects on-the-fly for property accesses, you may be able to provide equality if you cache the created Proxies. Ideally that would need weak references however which are not yet supported.

**Comment by dug9** [comment]
Sami - thanks yes I'm not caching the proxies, and for (ground == ground) I generate 2 separate wrappers on the fly - and get false as a result. I'll try caching.
-Doug
If the proxies have the same address (due to caching) then a == b will be true at the right time with clean syntax.
Not sure what weak references are. In my native type struct, I (think I) can put a field initialized to NULL, and generate a proxy once. I'll try it.

**Comment by svaarala** [comment]
Weak references can be used for several things, but one pattern is to use a weak reference for caching objects or other values. Weak references can be used in the cache without preventing collection of the values in question. Normal (strong) references in the cache would prevent garbage collection. Sometimes that's not an issue; at other times it may be.

ES6 provides a few weak reference structures, see e.g. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap. These are not yet supported but will eventually be added to Duktape.

**Comment by dug9** [comment]
Have some caching coded and working a bit
- per-context lookup table
- add,remove,search
print('ground == ground: '+ (ground == ground)); //true now
PROBLEM: it looks like the proxy gets finalized at end of scope ie when exiting the () around ground==ground, 
that's the end-of-scope for the proxy that's generated on-the-fly first time inside (), and I'm relying on finalizer to tell me when the proxy reaches end-of-scope life.
These ?micro-scopes? aren't quite what I imagined and I'm not sure this is going to be muscular enough for all == comparison scenarios.
...
One idea is to trigger proxy generation for likely candidates at the global level, before entering any functional scopes. But that still won't cover everything.
...
algo:
proxyptr = search_cache(...)
if(proxyptr)
duk_push_heaptr(ctx,proxyptr);
else{
... create proxy as usual with finalizer and duk_new(ctx,2) 
.. proxyptr = duk_get_heapptr(ctx,-1);
.. add to cache(ctx,proxyptr,...)
}

**Comment by fatcerberus** [comment]
The quick finalization you're seeing is because Duktape is reference counted by default, so when there are no remaining references to the object it gets freed immediately.  If that's too much for you, you can disable refcounting and only use mark-and-sweep.

**Comment by dug9** [comment]
refcounting - gotcha. That explains it. mark-and-sweep. Thanks very much for the tips fatcerberus. 
-Doug
more..
The proxies I need cached for the binary == tests are all what could be global / root objects in the script ctx context ie they are nodes in a scenegraph in a rendering engine, and the nodes typically survive 1000s of frames, the scripts are called once per frame.
in js
aa.bb.cc[3].dd.ff = gg.hh.ii.kk[4].ll.mm;
most of the aa bb .. are nodes. There can be 1000s of nodes in a scenegraph, and we don't know in advance which nodes will be needed/accessed in the script, and it would be inefficient to prepare all their proxies at the ctx global level in advance. So a lazy-proxy approach helps do just what's needed.
Beside switching to mark-and-sweep, I'm wondering if there's a way to lazily add references to the global level on-the-fly:
duk_increment_refcount(ctx,-1); //I didn't see an API function for this
or the duk api equivalent of something like this:
//global level
var _cache = {};
_cache.add(proxy);
so that one way or another, on the first lazy instancing, I increment the refcount so its not gcd until _cache flushed intentionally.
That would allow everything else to continue with refcounting as normal. 
,.,
I didn't see mark_and_sweep function in api - I gather its a build configuration.

**Comment by dug9** [comment]
simple^ proxy caching is working for the binary == tests - all the permutations I can think of, and a big improvement over not caching. Even if proxies are sometimes regenerated redundantly, within the scope of the == test its getting the same proxy (object address), and saving to intermediate var a = proxy1; if(a == proxy2) that works too I guess because proxy1 isn't finalzied early because var a has a ref.
Thanks Sami and B.
-Doug
^simple proxy caching: add on create, remove on finalize, list is per-context. tinkering with refcounting/not adding to global context. Still using default refcounting.

**Comment by svaarala** [comment]
@dug9 Good to hear! As soon as weak references are implemented you may be able to improve on that solution.
