### ISSUE TITLE
Debugger improvements for 1.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#128]
Debugger cleanups and improvements for 1.2 release:

- [x] Add a duk_debugger_cooperate() call to allow debug commands to be executed outside of any Duktape calls (e.g. from an eventloop).
- [x] GetBytecode debugger command to get bytecode for active function, web UI support for viewing human readable bytecode (perhaps an overlay that can be opened and closed at first). Bytecode view helps diagnosing compiler errors and opportunities for optimization.
- [x] Debugger transport torture feature option (for development of debug transport / debug client)
- [x] JSON mapping for debug protocol
- [x] JSON debug proxy which allows user code to talk to the debug target using JSON messages rather than implementing the binary protocol
- [x] Current JSON debug protocol framing is newline-terminated one-line JSON objects; use a more explicit framing, or perhaps adopt JSONRPC? => good enough for now.

**Comment by svaarala** [comment]
Draft of debugger bytecode view in:

- https://github.com/svaarala/duktape/tree/debugger-bytecode-view

The web UI has a button for showing bytecode for current function in a somewhat pretty printed form. Dumping bytecode is also possible for eval() functions and others where source code is not available.

No support for stepping in bytecode view or showing bytecode next to the source file yet.

**Comment by uxnow** [comment]
:+1:

**Comment by svaarala** [comment]
Added flags decoding and merged to master as a very first step in debugger bytecode support.

**Comment by svaarala** [comment]
The Duktape debug protocol is binary and optimized for low memory and slow links. Integrating directly to the binary protocol needs a lot of level binary manipulation. To make integration easier, a JSON mapping will be added with Duktape also providing a JSON proxy so that you can more easily integrate clients with a debug target.

Here's a prototype branch for that:

- https://github.com/svaarala/duktape/tree/debugger-json-proxy-prototype

The JSON mapping has various reasonable design alternatives. The branch current uses one with minimal framing (single-line JSON documents with newline termination) and a custom JSON object format. Another option would be to adopt e.g. JSONRPC 2.0, but it doesn't map 1:1 to the debug transport (which lacks, for instance, message reordering).

The goal of a JSON mapping is to make deeper integration (other than just providing a dumb transport and using an existing debugger UI) easier, so feedback is welcome especially if you plan on implementing debugger integration.

Here's an example session with the current framing (arrows added to indicate message direction, `<--` is received from JSON proxy/target, `-->` is written to JSON proxy/target):
```
$ telnet localhost 9093
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
<-- {"notify":"_Connected","args":[{"protocolVersion":1,"versionIdentification":"1 10199 v1.1.0-173-gecd806e-dirty duk command built from Duktape repo"}]}
<-- {"notify":"Status","command":1,"args":[1,"test-dev-mandel2-func.js","global",58,0]}
--> {"request":"Resume"}
<-- {"reply":true,"args":[]}
<-- {"notify":"Status","command":1,"args":[0,"test-dev-mandel2-func.js","global",58,0]}
<-- {"notify":"Status","command":1,"args":[0,"test-dev-mandel2-func.js","global",58,0]}
<-- {"notify":"Print","command":2,"args":["................................................................................\n"]}
[omitted]
<-- {"notify":"Print","command":2,"args":["................................................................................\n"]}
<-- {"notify":"_Disconnecting"}
Connection closed by foreign host.
```
