### ISSUE TITLE
jscl.js failed to execute(RangeError: register limit)

### ISSUE THREAD

**Issue by syoyo** [svaarala/duktape#1292]
I tried to play with jscl https://github.com/jscl-project/jscl with duktape 2.0.0, but unfortunately got the following runtime error.

```
$ cd /path/to/jscl
$ ./make.sh

$ cd /path/to/duktape-2.0.0
$ ./duk /path/to/jscl/jscl.js
RangeError: register limit (line 3654)
    at [anon] (/path/to/jscl/jscl.js:3654) internal
    at [anon] (duk_js_compiler.c:1544) internal
error in executing file /path/to/jscl/jscl.js
```

In jscl.js:3654, it defines an object with large number of function arguments
```
var l262=internals.QIList(internals.QIList(65,90),internals.QIList(97,122),internals.QIList(170,170),internals.QIList(181,181),internals.QIList(186,186),internals.QIList(192,214),internals.QIList(216,246),internals.QIList(248,705),internals.QIList(710,721),internals.QIList(736,740),internals.QIList(748,748),internals.QIList(750,750),internals.QIList(880,884),internals.QIList(886,887),internals.QIList(890,893),internals.QIList(902,902),internals.QIList(904,906),internals.QIList(908,908),internals.QIList(910,929),internals.QIList(931,1013),internals.QIList(1015,1153),internals.QIList(1162,1317),internals.QIList(1329,1366),internals.QIList(1369,1369),internals.QIList(1377,1415),internals.QIList(1488,1514),internals.QIList(1520,1522),internals.QIList(1569,1610),internals.QIList(1646,1647),internals.QIList(1649,1747),internals.QIList(1749,1749),internals.QIList(1765,1766),internals.QIList(1774,1775),internals.QIList(1786,1788),internals.QIList(1791,1791),internals.QIList(1808,1808),internals.QIList(1810,1839),internals.QIList(1869,1957),internals.QIList(1969,1969),internals.QIList(1994,2026),internals.QIList(2036,2037),internals.QIList(2042,2042),internals.QIList(2048,2069),internals.QIList(207 ...
```

I guess it looks the issue is related to #955, right?

**Comment by svaarala** [comment]
This is a different case, it's related to some opcode trying to use a register beyond a 16-bit register limit which may happen in very large functions with a lot of variables or very large expressions.

I'll test to see which opcode causes the issue here specifically (thanks for repro instructions :-).

**Comment by svaarala** [comment]
The register limit is also encountered with Duktape 1.5.0 so it's related to the bytecode format changes in 2.0.0.

The instruction causing the issue is (in duk__emit_a_bc):
- op_flags: 0x1b0 -> DUK__EMIT_FLAG_NO_SHUFFLE_A, opcode DUK_OP_CALL
- a: 0x1a7 -> call argument count (larger than A range, 0-255)
- bc: 1 -> start register for call arguments

So the limit being hit here is the call argument count. An easy fix for that would be to make the count indirect but since that's slower and larger for the common case, there would need to be an indirect variant. I'll need to think a bit about what's the most sustainable and consistent way to handle very large argument counts.

**Comment by svaarala** [comment]
Disabling that limit with a test hack the compilation finishes and execution then fails with:

```
ReferenceError: identifier 'window' undefined
    at [anon] (duk_js_var.c:1269) internal
    at [anon] (/tmp/jscl/jscl.js:39) strict
    at global (/tmp/jscl/jscl.js:27176) preventsyield
error in executing file /tmp/jscl/jscl.js
```

So maybe this is the only limit preventing execution.

**Comment by syoyo** [comment]
Thank you for the investigation!

> So maybe this is the only limit preventing execution.

Yes, we can ignore `window` undefined error.

**Comment by kakaraky** [comment]
I ran into the same issue:
a=String.fromCharCode(65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65)

It sounds like the best approach is a new opcode with larger than 8 bit argument

**Comment by svaarala** [comment]
For dispatch speed it's better for the indirect call to have its own opcode. I've completed a few call handling rework steps so this change should now be a bit easier.

**Comment by svaarala** [comment]
The argument limit is now roughly ~64k. This now works:

```
duktape@keppihevonen:~/duktape$ cat /tmp/foo.js
a=String.fromCharCode(65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65)
print(a.length, a);
duktape@keppihevonen:~/duktape$ ./duk /tmp/foo.js
258 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by kakaraky** [comment]
Thanks.

**Comment by syoyo** [comment]
Thank you!
