### ISSUE TITLE
Bug in TextEncoder: use of uninitialized variable

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1293]
Kept getting "invalid args" when calling TextEncoder#encode() with valid input (i.e. a string), so I decided to investigate.  Got this back from MSVC:
```
Run-Time Check Failure #3 - The variable 'final_len' is being used without being initialized.
```

Offending line of code is here:
https://github.com/svaarala/duktape/blob/v2.0.0/src-input/duk_bi_encoding.c#L430

Not sure what would cause this, but the variable must indeed be uninitialized, since MSVC reports its value as 14757395258967641292, or in hex `0xcccccccccccccccc`, which is the sentinel for an uninitialized stack variable.

`len` is zero, so the input seems to be an empty string.

**Comment by svaarala** [comment]
Yep, looks like there's a bug for zero sized string input. I'll open a fix pull.

**Comment by svaarala** [comment]
This is unfortunately not triggered by any of the regression tests, and manually testing it on Linux the empty string input works fine -- which is ultimately due to luck.

**Comment by fatcerberus** [comment]
I'm actually quite surprised *I* didn't catch this during implementation.  I know I tried a bunch of different input... guess I never tried to pass it an empty string.

**Comment by svaarala** [comment]
Not sure but I probably reworked those bits a little after merge and maybe broke it then.

**Comment by fatcerberus** [comment]
As a side note: That sentinel thing MSVC does for uninitialized variables (0xcccccccc) is the reason I started treating `null` and `undefined` differently in JS.  It's really quite useful for debugging :-)

**Comment by svaarala** [comment]
Tagged 'security' because may cause memory unsafe behavior.

**Comment by svaarala** [comment]
Ah, actually, this can't cause memory unsafe behavior: the invalid final_len will go into the buffer object virtual `.length` field. The resulting buffer object is not covered by the backing buffer, but that's allowed and doesn't cause memory unsafe behavior.
