### ISSUE TITLE
Misc issues for 2.1.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1298]
- [x] Include `duk-pgo.O2` in the performance summary wiki page - https://github.com/svaarala/duktape-wiki/pull/171
- [x] Include Octane score going back a few versions - https://github.com/svaarala/duktape-wiki/pull/171

**Comment by svaarala** [comment]
Performance page in Wiki https://github.com/svaarala/duktape-wiki/pull/171.

**Comment by svaarala** [comment]
Octane score is around 25% higher than Duktape 2.0.0 which is nice :-)

**Comment by fatcerberus** [comment]
> Octane score is around 25% higher than Duktape 2.0.0

I knew the recent master builds seemed a lot faster :)
