### ISSUE TITLE
duk_dump_context_stderr  print problem

### ISSUE THREAD

**Issue by sukenzhu** [svaarala/duktape#133]
why duk_dump_context_stderr print always  like “ctx: top=2, stack=[{”, It is an Incomplete  log.
My IDE is Eclipse for C/C++;
how to solve the problem ，thanks！

**Comment by svaarala** [comment]
Hmm, no idea why that would happen. Does this also happen when you run the executable from command line (in case you ran it from the IDE)?

**Comment by sukenzhu** [comment]
@svaarala I tried command line in ubuntu   ,  the log is OK !
