### ISSUE TITLE
What happened to #line x  "duk_***.h" in duktape.c?

### ISSUE THREAD

**Issue by harold-b** [svaarala/duktape#1332]
When generating duktape.c via `tools/configure.py` for duktape.c with 2.0.* (right now using master), now #line directives are generated anymore as in previous versions. This was useful when debugging, as Visual Studio would redirect to the original source file instead of duktape.c. I checked if there was any option for configure.py for them but, didn't seem to find any. Is there a way to enable them again?

**Comment by svaarala** [comment]
You can use `--line-directives` as a configure.py option to get them to be emitted.

**Comment by svaarala** [comment]
```
duktape@keppihevonen:~/duktape$ python tools/configure.py --help
Usage: configure.py [options]
[...]
  --line-directives     Output #line directives in combined source (default is
                        false)
[...]
```

**Comment by harold-b** [comment]
> You can use --line-directives as a configure.py option to get them to be emitted.
Perfect, thanks!

I checked only on `duk-config.rst`, so I didn't find anything there. Perhaps mention of the `--help` command should be made there, to let the user know of further options?

Thanks again, closing as this solves it :yum:

**Comment by svaarala** [comment]
@harold-b Good idea, I'll add a note about --help into duk-config.rst. The tool documentation isn't intended to cover all options as keeping them fully in sync is a bit of work :-)

The Wiki documentation does mention --help: http://wiki.duktape.org/Configuring2x.html. There's some unfortunate overlap between the Wiki documentation and duk-config.rst now (the duk-config.rst documentation came first).
