### ISSUE TITLE
TypeError: cannot string coerce Symbol

### ISSUE THREAD

**Issue by arcticfoxs** [svaarala/duktape#1333]
There is an error in version 2.0 of compiled code.
I run an example

```
    examples\cmdline\cmdline.exe -c mandel.bin  mandel.js
    examples\cmdline\cmdline.exe  mandel.bin    
```

And there is an error:

```
TypeError: cannot string coerce Symbol
    at [anon] (duk_api_stack.c:2588) internal
error in executing file mandel.bin
```

In version 1.6 all worked without errors.

**Comment by svaarala** [comment]
Good catch, that's a bug in the command line example code; it pushes a binary file as a string and tries to buffer convert it. I'll open a fix pull shortly.

**Comment by svaarala** [comment]
@arcticfoxs The fix is now merged to master, here's a dist snapshot if you want to check out the fix: http://duktape.org/snapshots/duktape-2.0.99-20170127201519-v2.0.0-154-gf943435.tar.xz.

Thanks for reporting the issue :)
