### ISSUE TITLE
Check if Duktape could be added to kangax/compat-table

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1338]
https://github.com/kangax/compat-table

**Comment by svaarala** [comment]
This seems to be doable, though the results need to be updated manually (I'm not sure if that's the right way). I'll open a few pulls to the compat-table repo.

**Comment by svaarala** [comment]
https://github.com/kangax/compat-table/pull/1069

**Comment by fatcerberus** [comment]
I find it rather amusing that Duktape passes the "proper tailcall" tests when almost no other major engine/browser does. :)

Tailcalls seem to be a major sticking point for ES6 support in most engines, for whatever reason.
