### ISSUE TITLE
Linker issues with Ubuntu Eclipse C/C++ IDE (__fpclassify)

### ISSUE THREAD

**Issue by sukenzhu** [svaarala/duktape#134]
use ubuntu  Eclipse C/C++   compile duktape  , always  build  error :  "more undefined references to `__fpclassify' follow"!
thanks!

**Comment by svaarala** [comment]
Do you have math library linked, i.e. `-lm`?

**Comment by sukenzhu** [comment]
@svaarala  i did't link math library  ,just compile duktape,c file。
all the log is below
duktape.o:/home/suken/workspace/test/Debug/duk_js_ops.c:855: more undefined references to `__fpclassify' follow

**Comment by svaarala** [comment]
I think you may be accidentally linking instead of just compiling, could you paste the compiler command you used?

**Comment by svaarala** [comment]
@sukenzhu Ping? :)
