### ISSUE TITLE
Add support for shebang lines

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1346]
A shebang in the beginning of a script currently causes a syntax error.  It is possible (of course) to preprocess the script and remove the shebang, but it would be nice if Duktape could do it automatically in service to applications like minisphere and Cell that use it as a frontend.

**Comment by svaarala** [comment]
I've been considering this too earlier on - it's technically non-compliant behavior but since ES allows "additional syntax" pretty broadly, it should be OK to just treat shebang lines as an extended comment syntax.

**Comment by svaarala** [comment]
One thing I'm not sure about is whether they should be only allowed for certain kinds of code. For example, would one expect that the Ecmascript code:

```js
eval('#!foo\n1+2+3')
```

would return 6 or SyntaxError? For the C API this probably should be accepted because many users bring in "modules" by eval'ing a bunch of files from C code. Maybe the same should apply to Ecmascript code.

**Comment by fatcerberus** [comment]
In Node, that eval is a SyntaxError:
```
> eval('#!foo\n1+2+3')
SyntaxError: Invalid or unexpected token
```

However a shebang as the first line of a file is accepted (i.e. Node ignores it, but retains the line numbers):
```
#!/usr/bin/pig
throw new Error("the pig ate everything");
```

```
C:\Users\fatce_rtr2nxl>node pig.js
C:\Users\fatce_rtr2nxl\pig.js:2
throw new Error("the pig ate everything");
^

Error: the pig ate everything
    at Object.<anonymous> (C:\Users\fatce_rtr2nxl\pig.js:2:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

**Comment by svaarala** [comment]
Right, but with no understanding of "files", I wonder what the best semantics would be.

One simple approach would be to add a `DUK_COMPILE_ALLOW_SHEBANG` to `duk_compile()` flags. It would then only be available from C code and when you explicitly request for it.

**Comment by denisdemaisbr** [comment]
this is implemented in lua core (lauxlib.c) very simple "just skip the first line" on loader

**Comment by svaarala** [comment]
@denisdemaisbr Right, as long as it's clear what contexts should allow the syntax the parsing itself is very simple.

**Comment by fatcerberus** [comment]
I vote for a flag for `duk_[p]compile()`.  IMO It doesn't make much sense to allow shebangs for `eval()` etc. and Node.js indeed doesn't in those contexts.
