### ISSUE TITLE
Native finalizer receives only one argument instead of two

### ISSUE THREAD

**Issue by mamontov-cpp** [svaarala/duktape#1348]
According to http://wiki.duktape.org/HowtoFinalization.html ("Heap destruction" section), a finalizer function now should receive two arguments. However, if a native function is set as a finalizer, it seems to receive only one argument.

```
duk_ret_t finalize(duk_context *ctx)
{
	printf("Count of arguments: %d\n", duk_get_top(ctx));
}

int main(int argc, char** argv)
{
	duk_context* ctx = duk_create_heap(NULL,NULL, NULL, NULL, NULL);
	
	duk_idx_t obj = duk_push_object(ctx);
	duk_push_c_function(ctx,  finalize, 1);
	duk_set_finalizer(ctx, obj);
	
	duk_destroy_heap(ctx);
	return 0;
}
```

On v.2.0.1, this program prints "1". So, how many arguments does finalizer function receive: 2 or 1? Is it an issue with my code or some mistake in the wiki?

**Comment by fatcerberus** [comment]
Your `duk_push_c_function()` explicitly specifies one argument, so Duktape coerces the valstack to match that when the function is called.  You can either change it to 2 or define it as `DUK_VARARG`.

**Comment by mamontov-cpp** [comment]
Thank you! This was really an issue in my code.
