### ISSUE TITLE
Update hoisting behavior for function statements, var to align with modern engines

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1350]
The following code, when executed in V8 (either Chrome or Node.js):
```js
var global = new Function('return this;')();
global.fn = function fn() { console.log("outside if"); };
(0, eval)('if (false) { function fn() { console.log("inside if"); } }');
fn();
```

Outputs:
```
outside if
```

Duktape instead logs:
```
inside if
```

So the function is being hoisted outside of the `if` by Duktape, but not in V8.  However, that's not the end of it.  For some reason, Babel transforms the code inside the eval to:
```js
if (false) { var fn = function fn() { console.log("inside if"); } }
```

Which leads to `TypeError: undefined not callable` in Duktape, but the same output in Node/Chrome (`outside if`).  So my question is: Is Duktape doing hoisting wrong?

**Comment by svaarala** [comment]
The semantics of function declarations outside of the top level used to be engine specific. ES2015 Annex B gives some guidance: http://www.ecma-international.org/ecma-262/6.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics.

Duktape follows earlier V8 semantics of hoisting the declarations:

```
sva-p@keppihevonen:~$ node
> process.version
'v0.12.1'
> var global = new Function('return this;')();
undefined
> global.fn = function fn() { console.log("outside if"); };
[Function: fn]
> (0, eval)('if (false) { function fn() { console.log("inside if"); } }');
undefined
> fn();
inside if
undefined
```

And this has indeed changed:

```
sva-p@keppihevonen:~$ nodejs
> process.version
'v6.7.0'
> var global = new Function('return this;')();
undefined
> global.fn = function fn() { console.log("outside if"); };
[Function: fn]
> (0, eval)('if (false) { function fn() { console.log("inside if"); } }');
undefined
> fn();
outside if
undefined
```

**Comment by fatcerberus** [comment]
Side note: You don't need to do the `new Function(...)` dance in Node, because it provides `global` by default :-)

**Comment by fatcerberus** [comment]
This isn't just academic by the way - I actually have a real-world case that is broken (indirectly) by this:

```js
if (GetVersion() < 1.6) {
	function DoesPersonExist(name) {
		return Link(GetPersonList()).contains(name); 
	}
}
```

That's a polyfill for older Sphere versions.  It happens to work fine by accident in Duktape, with the caveat that the polyfill is provided unconditionally.  However, Babel is part of the minisphere toolchain and transforms the function declaration to an expression:

```js
if (GetVersion() < 1.6) {
	var DoesPersonExist = function DoesPersonExist(name) {
		return Link(GetPersonList()).contains(name); 
	};
}
```

Which leads to "undefined not callable" in Duktape, but (strangely) works as expected in Node (the hoisted `var` apparently doesn't overwrite the global function, while it does in duktape).

Note that for Node, everything is a CommonJS module (i.e. function body) so you need to use an indirect eval to run top-level code.

**Comment by svaarala** [comment]
> Side note: You don't need to do the new Function(...) dance in Node, because it provides global by default :-)

Right, I just pasted the example in the issue description.

**Comment by svaarala** [comment]
> This isn't just academic by the way [...]

I know, I chose the original behavior based on V8 at the time. While the semantics of function statements are not exactly required, Duktape should IMO just follow the principle of least surprise there, and hoisting used to be that behavior. If that's no longer the case across major engines, Duktape should adapt to the prevailing behavior.

**Comment by svaarala** [comment]
The issue title should probably be changed to something else - the current behavior is not incorrect as far as I know, but it's worth discussing if and how to change it to better match major engines at this point in time.

**Comment by fatcerberus** [comment]
Actually Duktape's hoisting of function statements isn't the problem directly in my case at least - it just means I get an overly broad polyfill.  The issue I'm having is that a hoisted `var` in global scope overwrites a global binding, which doesn't happen in V8.

**Comment by fatcerberus** [comment]
To illustrate the above:
```js
global.fn = function() { console.log("the pig ate it"); };
(0, eval)('var fn;');
fn();
```

Node prints `the pig ate it`.  Duktape throws `TypeError: undefined not callable`.

**Comment by svaarala** [comment]
In functions a `var` declaration is hoisted even if it is inside an if block that doesn't get executed. The variable thus exists at function entry, but will have an `undefined` value. Duktape does the same for program code too, so that DECLVAR opcodes are emitted for them.

So maybe that behavior is incorrect for code running outside of functions? It's specified (for ES5.1) in http://www.ecma-international.org/ecma-262/5.1/#sec-10.5. The algorithm runs "On entering an execution context" and step 8 handles variable declarations anywhere in the function. This all happens before any code is executed.

But I'd need to read the algorithm through to be sure if it's correct. Just quickly testing Rhino agrees with Duktape behavior while both newer and older V8 doesn't -- but I'm not sure if they execute code as "global" code or as module code which would be important here.

**Comment by svaarala** [comment]
This is the global code case:

```
console.log('foo' in global);

if (false) {
    var foo = 123;
}

console.log('foo' in global);
```

Duktape prints true -- V8 prints false for both cases because the code most likely executes as a module (= function) rather than a global program.

**Comment by fatcerberus** [comment]
Note the indirect eval in my testcase above - I specifically did that to force Node to run it as top-level code.  Otherwise everything is a CommonJS module (which are function-wrapped by definition).

**Comment by svaarala** [comment]
> Node prints the pig ate it. Duktape throws TypeError: undefined not callable.

Ok, this seems like a clear bug in that if the variable is already defined, it shouldn't get initialized to undefined.

**Comment by svaarala** [comment]
> Note the indirect eval in my testcase above - I specifically did that to force Node to run it as top-level code. Otherwise everything is a CommonJS module (which are function-wrapped by definition).

Eval and global code are still distinct execution contexts and have slightly different declaration semantics -- maybe not an issue here but worth noting that there's no single "topl level code" concept.

**Comment by fatcerberus** [comment]
I figured that, but in any case the issue manifests with both an indirect eval and actual global code.

**Comment by svaarala** [comment]
How do you run global code in Node.js?

**Comment by fatcerberus** [comment]
I don't think you can - the closest I could get was the indirect eval idiom `(0,eval)()`, but as you note, that's not always the same.

**Comment by svaarala** [comment]
Ok, so there's no comparison for global code. But the eval case seems like a clear bug (and I think the global case matches it), opened a specific issue for this: #1351.

**Comment by fatcerberus** [comment]
> and I think the global case matches it

It does - I spent about 20 minutes trying to figure out why a certain legacy game was throwing errors after transpiling it with Babel.  Turns out that Babel was transforming a function statement to a function expression:
```js
if (GetVersion() < 1.6) {
	var DoesPersonExist = function DoesPersonExist(name) {
		return Link(GetPersonList()).contains(name); 
	};
}
```

Which triggered the hoisting bug.

**Comment by svaarala** [comment]
Right, but I meant if the global case matches V8 behavior.

**Comment by fatcerberus** [comment]
Hm, V8 doesn't actually seem to make the function block-scoped but rather treats it as a statement: if you change `if (false)` to `if (true)` then it will print "inside if".  Curious.

**Comment by svaarala** [comment]
There are a few variants what engines do (or have done) with function statements. Older V8 hoists the declaration completely as if the function was declared at the top level of the enclosing function. This is what Duktape does too: http://duktape.org/guide.html#custombehavior.6. The downside is that if a function statement occurs e.g. in a catch-clause, the function won't see the catch variable.

Newer V8 seems to treat the function statement as a `var` declaration: the identifier gets bound on the function entry but is `undefined` until the assignment happens (if it happens). This has the advantage that the assigned function has block scope visibility (e.g. it can see a catch variable).

**Comment by svaarala** [comment]
Concrete example:

```js
var e = 123;
var bar = 'parent';

console.log(process.version);

function foo() {
    console.log(typeof e, e);
    console.log(typeof bar, bar);
    try {
        throw 'aiee';
    } catch (e) {
        function bar() { console.log(typeof e, e); }
    }
    console.log(typeof bar, bar);
    bar();
}
foo();
```

Older V8, bar() never sees 'e' (it sees the global one instead because catch variables are block scoped), 'bar' is declared (and callable) immediately at entry to the function, just like any other function declaration. This is also the current Duktape behavior:

```
v0.12.1
number 123
function function bar() { console.log(typeof e, e); }
function function bar() { console.log(typeof e, e); }
number 123
```

Newer V8, bar() sees 'e', bar exists at top of function as undefined (and shadows the global):

```
v6.7.0
number 123
undefined undefined
function function bar() { console.log(typeof e, e); }
string aiee
```

**Comment by svaarala** [comment]
Opened #1353 for the specific change to update that behavior (which is unrelated to any var redeclaration changes this issue also addresses). I think this issue can now be closed because the "var" part is handled by #1351 and a clearer description of the function statement change is in #1353.

**Comment by svaarala** [comment]
If it wasn't apparent from above, I prefer the new V8 behavior over the older one, both to match newer V8 and because the behavior is actually more useful.

I chose the older V8 behavior for Duktape originally because function statements don't have a single required behavior and matching V8 behavior had the benefit of being the least surprising approach.

**Comment by fatcerberus** [comment]
You mention function statement behavior in functions (hoisting, shadowing globals, etc.)--but what about in global code/indirect eval?  Is it the same there?

**Comment by svaarala** [comment]
Yes, it's the same. For example:

```js
console.log(typeof foo);

if (false) {
    function foo() {};
}

console.log(typeof foo);
```

Older V8 (and Duktape now):

```
function
function
```

Recent V8:

```
undefined
undefined
```

**Comment by fatcerberus** [comment]
I assume you mean the reverse (V8 prints function, Duktape prints undefined)?

**Comment by fatcerberus** [comment]
Anyway, since there are separate issues for the `var` and function statement changes now, this can indeed be closed.

**Comment by svaarala** [comment]
No, Duktape prints function because the function statement is interpreted as a function declaration and is visible right on function entry.

**Comment by fatcerberus** [comment]
Oh, I see it now.  I must not be fully awake yet - I seem to be dyslexic this morning :)

**Comment by svaarala** [comment]
Concretely that declaration compiles to a CLOSURE + DECLVAR which is emitted into the function prologue.
