### ISSUE TITLE
Redeclaring a global variable in eval code resets variable to undefined

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1351]
https://github.com/svaarala/duktape/issues/1350#issuecomment-277453162

Repro:

```js
global.fn = function() { console.log("the pig ate it"); };
(0, eval)('var fn;');
fn();
```

Node prints the pig ate it. Duktape throws TypeError: undefined not callable.

**Comment by svaarala** [comment]
The issue doesn't occur when global code or eval code redeclares the variable in the same compilation unit, e.g.:

```
var foo = 123;
var foo;
console.log(foo);  // -> 123
```

This is the case because the compiler "squashes" the duplicate declaration as part of tracking identifiers, so only one DECLVAR gets emitted, and the issue isn't triggered. In the problematic eval case the eval code is a separate compilation unit which allows the case to happen.

**Comment by svaarala** [comment]
Related issue, useful in repro test cases:

```js
print(Math);
var Math;
print(Math);
```

This should print:

```
[object Math]
[object Math]
```

but prints

```
undefined
undefined
```

because of the same root cause.

**Comment by fatcerberus** [comment]
> In the problematic eval case the eval code is a separate compilation unit which allows the case to happen.

That explains the real-world issue too: In my case a native C-provided binding was being overwritten.

**Comment by fatcerberus** [comment]
I assume the fix is to change DECLVAR to not set the variable to undefined if a binding by that name already exists.

**Comment by svaarala** [comment]
Essentially yes, with careful reading of all the related semantics in each execution mode.

**Comment by fatcerberus** [comment]
I assume this is the relevant bit:
> b. Let varAlreadyDeclared be the result of calling env’s HasBinding concrete method passing dn as the argument.
> c. If varAlreadyDeclared is false, [...]

HasBinding:
> 1. Let envRec be the declarative environment record for which the method was invoked.
> 2. If envRec has a binding for the name that is the value of N, return true.
> 3. If it does not have such a binding, return false.

But global code doesn't have a declarative environment IIRC--it has an object environment.  So I'm not sure whether varAlreadyDeclared should be true or false in that case (assuming a global binding by the same name already exists).

**Comment by fatcerberus** [comment]
I'll look at ES2016 to see if anything has changed.

**Comment by fatcerberus** [comment]
It's quite difficult to follow the variable declaration semantics in the specification as they're all over the place, but considering that `var x;` is evaluated as follows:

> 1. Return NormalCompletion(empty).

That seems to indicate that the current behavior of overwriting existing global bindings is indeed a bug.  A `var` statement without an initializer has no observable effects at runtime.

**Comment by svaarala** [comment]
It is clearly a bug, yes.

**Comment by svaarala** [comment]
I also found following the specification semantics for declarations rather complicated btw... :)

**Comment by mpietras** [comment]
I ran into something similar (or the same?) on 1.5.1:
`
duk_peval_string( ctx, "var a=5; print(a);if(typeof a=='undefined'){var a=6; print(a);} print(a);" );
duk_pop( ctx );
duk_peval_string( ctx, "print(a);if(typeof a=='undefined'){var a=6; print(a);} print(a);" );
duk_pop( ctx );
`
prints 5,5,6,6... somehow just evaluating the string causes a re-definition.  Is this is same as the issue described here?

**Comment by mpietras** [comment]
So I recently ran into something in 1.5.1 that can be demonstrated like this:

`duk_peval_string( ctx, "a=5; print(a);" );`
`duk_pop( ctx );`
`duk_peval_string( ctx, "print(a); a=6; print(a);" );`
`duk_pop( ctx );`
`duk_peval_string( ctx, "print(a); var a=7; print(a);" );`
`duk_pop( ctx );`

Which outputs 5,5,6,undefined,7.  Is this the same issue addressed here or am I misunderstanding?

**Comment by svaarala** [comment]
@mpietras It is very likely the same issue. It occurs on the third eval. The `var a=7` is executed in two parts:
- First is a DECLVAR opcode on entry to the third eval (before anything else runs). Because `a` is already declared this should be a no-op, but the bug caused the variable to overwritten with `undefined` at that point.
- Second is the assignment itself, here `a=7`. This works correctly in your case.

The key thing is that a redeclaration in the same compilation unit (eval code, global code) won't trigger the issue. The binding must already exist or must be declared and redeclared in separate compilation units.

If you wanted to verify this, you could try the `v1-maintenance` branch which has a backported fix.

**Comment by svaarala** [comment]
The 1.x fix will be in the 1.7.0 release, 1.6.x doesn't have the fix.

**Comment by mpietras** [comment]
I tried out just commit 48f7ad5c06331fac88d1e9aa5a767030a143ba88 on 1.5.1 and it did resolve my specific version of the issue, thanks.

**Comment by svaarala** [comment]
@mpietras Good to hear - you can use that cherry-pick or v1-maintenance (to become 1.7.0 in a week or two). Upgrading from 1.5.1 to 1.7.0 should be straightforward: the changes are quite minor, and the minor version has just been bumped because of a few small API additions.
