### ISSUE TITLE
estrange bug - concat string

### ISSUE THREAD

**Issue by denisdemaisbr** [svaarala/duktape#1359]
env: duktape-1.6.1 + win7 64-bit + cygwin 64-bit
this behavior is expected or not ?

file.js
> try {
>     require('js/console.js');
>     require('js/object-assign.js');
>     require('js/object-prototype-definesetter.js');
>     require('js/object-prototype-definegetter.js');
> } catch (e) {
>     print("CATCH: " + (e.printstack || e));
> }
> 
> //
> // https://msdn.microsoft.com/pt-br/library/dd548687(v=vs.94).aspx
> //
> var obj = {};
> Object.defineProperty(obj, "newDataProperty",
>     {value: 101, writable: true, enumerable: true, configurable: true}
> );
> 
> obj.newDataProperty = 102;
> 
> **// crash (when concat with undefined variable**
> // print("Property value: " + obj.newDataProperty + **newLine**);
> 
> // OK!
> print("Property value: " + obj.newDataProperty);
> 
>

**Comment by svaarala** [comment]
When you say crash, do you mean a segmentation fault or similar? If so, that's definitely not expected.

If you mean an error is caught, could you provide the traceback?

**Comment by svaarala** [comment]
For example this is normal:

```
duk> x = 'foo' + newLine
ReferenceError: identifier 'newLine' undefined
    at [anon] (duk_js_var.c:1197) internal
    at global (input:1) preventsyield
```

**Comment by denisdemaisbr** [comment]
$ ./test2.exe c.js
FATAL 56: uncaught error
PANIC 56: uncaught error (calling abort)

--- c.js

> try {
>         require('js/console.js');
>         require('js/object-assign.js');
>         require('js/object-prototype-definesetter.js');
>         require('js/object-prototype-definegetter.js');
> } catch (e) {
>         print("CATCH: " + (e.printstack || e));
> }
> 
> //
> // https://msdn.microsoft.com/pt-br/library/dd548687(v=vs.94).aspx
> //
> var obj = {};
> Object.defineProperty(obj, "newDataProperty",
>         {value: 101, writable: false, enumerable: true, configurable: false}
> );
> 
> obj.newDataProperty = 102;
> obj.n = 1001;
> obj.x = 'abc';
> obj.o = { a: 123, b: 321, c: 12.22 };
> 
> // crash
> print("Property value: " + obj.newDataProperty + newLine);
> 
> // OK!
> print( Duktape.enc('jx', obj, null, 4) );
> // EOF

teste2.c

> #include <stdio.h>
> #include <stdlib.h>
> 
> #include "duktape.h"
> 
> duk_context *CTX = NULL;
> extern void duk_register_fileio(duk_context *ctx);
> extern void duk_register_modSearch(duk_context *ctx);
> 
> 
> 
> int main(int argc, char *argv[]) {
> 
>     if (argc < 2) {
>         printf("usage: %s filename.js\n", argv[0]);
>         exit(1);
>     }
> 
>         if ((CTX = duk_create_heap_default()) == NULL) {
>         printf("duk_create_heap_default\n");
>         exit(1);
>     }
> 
>         duk_register_fileio(CTX);
>         duk_register_modSearch(CTX);
> 
>     if (duk_peval_file_noresult(CTX, argv[1]) != 0) {
>         printf("[runtime error]: \n%s\n <<EOF>>", duk_safe_to_string(CTX, -1));
>         goto finished;
>     }
> 
> finished:
>     duk_destroy_heap(CTX);
>     CTX = NULL;
> 
>     return 0;
> }
> 
>

**Comment by svaarala** [comment]
Does the uncaught error happen inside duk_peval_file_noresult()? (Could you ensure that by printing something just prior to the duk_peval_file_noresult() call?)

**Comment by svaarala** [comment]
Oh - I think I may know the reason. You're calling `duk_peval_file_noresult()` which provides no result value, and then trying to string coerce the result with `duk_safe_to_string(CTX, -1)`. However, because there's no result, that -1 points to a non-existent value stack index which causes an (uncaught) error.

If you changed `duk_peval_file_noresult()` to `duk_peval_file()` it might fix the uncaught error and allow the actual error to be printed.

**Comment by denisdemaisbr** [comment]
nice!

> $ ./test2.exe c.js
> [runtime error]:
> ReferenceError: identifier 'newLine' undefined
>  <<EOF>>
>
