### ISSUE TITLE
Regression coverage for refcount handling

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1360]
There's currently no regression coverage for refcount handling beyond what testcases and assertions cover. It would be nice to have more automatic regression coverage for refcount handling.

If refcount is artificially high, this usually goes unnoticed because mark-and-sweep ignores refcounts and will collect garbage even when their refcount is > 0. This is also memory safe, so the only functional issue is late memory freeing and potentially late finalizer execution. If refcount is artificially low, memory unsafe behavior may happen; this is obviously usually noticed quite quickly.

A mark-and-sweep like process could be used to calculate the correct refcounts for all heap objects and the refcounts could then be compared. However, refcounts are artificially bumped e.g. during refzero finalizer execution which would need to be fixed first (e.g. by pushing the value being finalized instead, so that the refcount bump is also associated a reference). As a practical matter replicating mark-and-sweep code for assertions only would be quite awkward. On the other hand running a mark-and-sweep essentially for doing assertions would also be awkward because mark-and-sweep has side effects.

A compromise approach would be to recompute refcounts during mark-and-sweep when assertions are enabled, and then compared them at the end of mark-and-sweep. Each `duk_heaphdr` would get an extra field with assertions enabled to allow the comparison. Refcounts would thus be checked on every mark-and-sweep pass -- too late to easily identify the cause, but still better than nothing.

A black box approach would be to start measuring testcase memory usage patterns and make commit tests point out any significant deviations from previous. For example, when refcounts work correctly many testcases have a relatively smooth memory usage profile. When a refcount is too high, and a lot of such objects are created, memory usage becomes more of a sawtooth because mark-and-sweep releases the garbage as a backstop. Just comparing maximum memory usage to previous master would identify such a sawtooth as well as other bugs.

**Comment by fatcerberus** [comment]
> However, refcounts are artificially bumped e.g. during refzero finalizer execution

I've never understood why this was necessary.  The finalizer is passed the object being finalized as a parameter, so that should be enough to ensure the object remains reachable during finalizer execution, right?

**Comment by svaarala** [comment]
What if the finalizer says `argumentObject = null`? Similarly, when the finalizer call returns and the value stack is unwound, the argument would have its refcount drop to zero before the call site for the finalizer would be able to do anything about it.

The main point is to avoid a refzero event for the object because we're already in refzero handling. This is now achieved by a refcount bump. It could equally be pushed on the value stack though.

**Comment by svaarala** [comment]
So to clarify, it's not enough for the value to get into the finalizer safely - it must also come out without being refzero processed so that we can decide whether to rescue or free the object without the object being re-queued into the refzero list (which would cause an infinite loop because we're already processing that list).

**Comment by fatcerberus** [comment]
Hm, would it be possible just to add a check to refzero processing to ensure it can't be invoked recursively, like mark-and-sweep does now?

**Comment by svaarala** [comment]
Refzero processing (refzero free pending) is not entered recursively and there's a flag against that (which has a checking cost unfortunately). That's not the issue here; instead, the refzero code would queue the object back into the refzero_list (at the tail) so it would get processed again (and again) but the current "refzero free pending" call which works the list until it becomes empty.

The cheapest way to prevent that is to ensure the refcount doesn't drop to zero during finalization - otherwise some extra flags and flag checks would be needed for every refzero event anywhere.

**Comment by fatcerberus** [comment]
Ah, I see.  That makes sense: Mark-and-sweep deals with the entire heap as a unit, while refzero logic is more localized and concerned with individual objects.  So what works for one mechanism doesn't necessarily work for the other one.

**Comment by svaarala** [comment]
Yep, the sequence of events is roughly:
- A DECREF operation drops some refcount to zero.
- The object in question is queued to refzero_list.
- The `duk_refzero_free_pending()` function is called to process the refzero_list, which at this point only has one object.
- The function processes the head of `refzero_list` until it becomes NULL. Each object freed may call further DECREF operations for whatever references it points to (just before being freed).
- Each such DECREF may have another refcount to drop to zero. These are handled by queueing them to the tail of `refzero_list` so that the initial `duk_refzero_free_pending()` will process them, in order.
- The `duk_refzero_free_pending()` function is called but it returns as a no-op because the list is already being processed.
- As a result, an entire object tree (without cycles) is potentially freed, inline in the initial DECREF operation.

In general there are one or two flags that could be eliminated from the current solution. It may seem unimportant but since the checks affect potentially every refcount or at least every refzero situation, it adds up easily. Also the current refcount code is not very efficient considered as a whole, and there's much room for improvement.

For example, the refzero-within-refzero case could be handled a bit more efficiently by making the "process refzero list" a function pointer and make the first call replace it with a nop function so that no explicit flag check would be needed in the common case.

**Comment by svaarala** [comment]
Another simple improvement is to combine the refzero_list queueing and "free pending" checks so that:
- If refzero_list is NULL before queueing, no "free pending" is running and we should start one.
- If refzero_list is not NULL before queueing, a "free pending" is already running and we don't need to start one.

This would be nice because the queueing code needs to check for `refzero_list == NULL` anyway in the queueing code.

I'll try this out in a pull ;)

**Comment by svaarala** [comment]
Hmm, that won't strictly work as described above because in some cases objects are refzero queued without a "free pending" check (e.g. the NORZ macros).

**Comment by svaarala** [comment]
#1406 adds refcount asserts.
