### ISSUE TITLE
Module loader gives a warning on Windows (Visual Studio 2013)

### ISSUE THREAD

**Issue by armornick** [svaarala/duktape#1369]
To be precise, compiling duk_module_duktape.c gives the following warning:

`warning C4013: 'snprintf' undefined; assuming extern returning int`

The problem occurs because Microsoft prepends the names of certain functions with an underscore. My current fix is adding the following to duk_module_duktape.h:

```
#ifdef _WIN32
	#define snprintf _snprintf
#endif
```

**Comment by svaarala** [comment]
@armornick Thanks, I'll look into it.

**Comment by fatcerberus** [comment]
Note that the define is only needed on MSVC2013 and earlier.  Later versions include the standard `snprintf()` and using the define can produce compile errors.

(The reason for the artificial compile errors is because `_snprintf()` differs from the standard function in NUL-termination behavior.)

**Comment by svaarala** [comment]
Yes, I'm aware of that - the same issue exists for Duktape itself.

**Comment by svaarala** [comment]
This is the related Duktape config snippet: https://github.com/svaarala/duktape/blob/master/config/compilers/compiler_msvc.h.in#L62-L72.
