### ISSUE TITLE
Debugger Throw notify tries sending even when debug client not connected

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1378]
`duk_debug_send_throw()` tries to write a Throw notify to the debug connection even when a debug client is not connected. This should be harmless because the writes are ignored - however, the process involves value stack operations to figure out a filename and a line, so it'd be better if nothing was done when a client isn't connected.

**Comment by fatcerberus** [comment]
I think the reason I wrote it like this originally was because I based the implementation on `duk_debug_send_status()`, which also doesn't check for an active connection before writing stuff.  That case is probably already accounted for by the debugger architecture, though - if the debugger is not connected, the code that sends status notifies simply won't run.

For throw notifies it's indeed different because the notify is handled inline with the normal throw logic.

**Comment by svaarala** [comment]
I'll check that path too but I think Status is only sent from debugger message loop handling.

Re: Throw notify, all the debug writes should ultimately come down to `duk_debug_write_bytes()` and be summarily ignored with:

```c
        if (heap->dbg_write_cb == NULL) {
                DUK_D(DUK_DPRINT("attempt to write %ld bytes in detached state, ignore", (long) length));
                return;
        }
```

So, not very clean, but as far as I can tell there's no functional issue besides doing unnecessary operations when debug client is not connected.

**Comment by svaarala** [comment]
Another issue in the Throw implementation which I think we left over on purpose is that e.g. the error `.fileName` property read can have arbitrary side effects as it may invoke a Proxy or a getter. In fact, the `.fileName` of an error is usually a getter so this is more or less necessary to get useful behavior.

Those side effects are potentially harmful though. For example, a getter may throw, causing another debug notify to be sent while the previous one is still just half-way written; this ultimately causes a debugger connection to be lost. Also error state may become clobbered.

So for the Throw notify to really work reliably, it would need to avoid code execution side effects: Proxy invocation, getter invocation, and finalizer execution (which may happen on any allocation). To achieve that the code would need:
- To enable GC flags to prevent finalizer execution (with a 100% reliable cleanup if an error is thrown e.g. due to out-of-memory).
- To use side effect free property accesses. For errors, the code could e.g. look up the file/line properties and if they are getters, try to use `_Tracedata` directly.

All in all rather tricky.

**Comment by svaarala** [comment]
In rewriting parts of the side effect protections I reread the code in question and there's a guard before duk_debug_send_throw() call after all. No idea how I missed it earlier, it's not exactly hidden.

So, I think this issue is invalid -- I'm not very happy about the debugger side effect handling and the guards in place (the Throw re-entry case is, for example, a realistic one as far as I can tell). But this particular issue is invalid at present IMO, so closing.
