### ISSUE TITLE
Direct handling of func.call() and func.apply()

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1388]
Currently `.call()` and `.apply()` cause a natively handled function call rather than an Ecmascript-to-Ecmascript call like ordinary function calls. This affects coroutine yield/resume behavior but also grows the native call stack for a case where that's unnecessary. Handling `.call()` and `.apply()` better is useful: while they're not very common in normal application code, they are frequently used in Promise implementations, transpiler generated code, etc.

**Comment by fatcerberus** [comment]
ES2015 requires both `.call()` and `.apply()` to tailcall the target function (and therefore any solution here is likely to dovetail nicely with #1026):
http://www.ecma-international.org/ecma-262/6.0/#sec-function.prototype.call

So this issue could probably be tagged `compliance`.

**Comment by svaarala** [comment]
Agree, also matches V8 behavior (as visible via `err.stack`).

**Comment by svaarala** [comment]
Avoiding the .call() or .apply() (or Reflect.construct()) on the call stack is relatively straightforward; did a quick prototype of that and it should only require a few lines of changes to call handling. That won't yet handle the direct ES-to-ES call part which needs a bit more changes, so maybe these two will be in separate pulls.

**Comment by fatcerberus** [comment]
I definitely welcome this change, it means less call() and apply() noise in my debugger callstack listings :)

**Comment by fatcerberus** [comment]
Another nice benefit if this is implemented is that these become tailcalls:
```js
return fn.call(...);
return fn.apply(...);
```

whereas right now, `.call()` itself is tailcalled, but then leaves itself on the stack while the target function runs.

**Comment by svaarala** [comment]
Conceptualyl yes, but tailcalls are implemented only for Ecmascript-to-Ecmascript calls at present., however. So depending a bit on how this is ultimately implemented, .call() and .apply() may be called as native functions, and even though they unwind themselves before making the actual call, the Ecmascript-to-Ecmascript call handling won't apply because the function itself is native.

**Comment by svaarala** [comment]
This is now implemented and in master. The `return fn.call()` etc tailcalls also work now.
