### ISSUE TITLE
Syntax error if last line in a module is a // comment with no line ending

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1394]
This affects both the Duktape 1.x and Node module loaders (and also miniSphere's loader, which is how I discovered it).  The module wrapper doesn't include a newline before the closing brace, so if the last line is a line comment (`//`) and the file ends without a newline, a syntax error will result.

This is a practical issue for at least TypeScript-transpiled code, which includes a reference to the source map as a line comment at the end of the file, without a final newline.

The fix would be to insert a newline before the closing brace of the wrapper function.

**Comment by svaarala** [comment]
Good catch, hadn't thought of that :-)

**Comment by svaarala** [comment]
I'll work up a pull in a second.
