### ISSUE TITLE
Using a 32-bit refcount for duk_heaphdr h_refcount field

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1399]
I noticed the following comment in `duk_heaphdr.h`, explaining why `h_refcount` is declared as a `duk_size_t` instead of `duk_uint32_t`:

> Technically, 'h_refcount' must be wide enough to guarantee that it cannot wrap (otherwise objects might be freed incorrectly after wrapping).  This means essentially that the refcount field must be as wide as data pointers.  On 64-bit platforms this means that the refcount needs to be 64 bits even if an 'int' is 32 bits.  This is a bit unfortunate, and compromising on this might be reasonable in the future.

Would you consider a duk_config option to use `duk_uint32_t` for `h_refcount`?  The default behavior could be to use `duk_size_t`, but if the client knows they'll never have that many references to an object, they could opt into saving 8 bytes per `duk_heaphdr`.

**Comment by svaarala** [comment]
Sure, that'd be OK.

**Comment by svaarala** [comment]
Two main approaches would be: (a) a config option for a 32-bit refcount or (b) adding a `duk_refcount_t` typedef. The downside of (b) is that overriding it means manual duk_config.h editing rather than just saying for example `python2 tools/configure.py -DDUK_USE_32BIT_REFCOUNT`.

**Comment by fatcerberus** [comment]
Hm, I'm actually not sure I follow the logic there.  I'm assuming the rationale is: there could theoretically be as many references to an object as addressable bytes available.  However in practice that's not really true: Anything holding a reference would itself be using some of the address space such that the maximum practical refcount is far below the size of the address space.

**Comment by beevik** [comment]
I like the `DUK_USE_REFCOUNT32` idea because it echoes the `DUK_USE_REFCOUNT16` implementation you already have.

**Comment by svaarala** [comment]
@fatcerberus Quite so - but assume you have a 64-bit `size_t` and the smallest heap allocated object containing a reference is 64 bytes. That means you can have 2^58 objects containing a reference to one specific target object.

The full 64 bits are of course not needed, but there aren't any obvious types smaller than `size_t` that would be correct either.

**Comment by beevik** [comment]
@fatcerberus I thought the same thing, but I guess it's technically possible on a 64-bit system to have enough addressable memory to exceed 4billion+ references to an object.  (On ARM64 systems, I believe you can address up to 256TB of memory, which is the largest I think I've seen.)

**Comment by svaarala** [comment]
As a slightly more realistic case:

Assume that there are several Array objects containing references to the same object. Each such reference takes 16 bytes with unpacked `duk_tval`. Given that, you can overrun 32 bits with a ~64GB heap.

Quite unlikely for most applications, but certainly possible to arrange if you really want to do so.

**Comment by svaarala** [comment]
@beevik Given that actually reaching `size_t` is quite unlikely for most applications, maybe `DUK_USE_REFCOUNT32` could be the default, and if you wanted to support huge memory spaces (and cared about the overruns) you could disable it.

**Comment by svaarala** [comment]
Opened #1400 to add INCREF wrap assertions. They're good to have in case refcount field is technically smaller than necessary.

**Comment by svaarala** [comment]
@beevik I'll work up that 32-bit refcount pull shortly, once #1400 is merged.

**Comment by fatcerberus** [comment]
FWIW, COM objects use 32-bit refcounts--and in fact they have to, because it's part of the API contract:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms691379(v=vs.85).aspx
> The internal reference counter that AddRef maintains should be a 32-bit unsigned integer.

I can't remember ever hearing about a bug in a COM component related to refcount overflow, so that seems to indicate that 32 bits is sufficient for most real-world use cases.

**Comment by svaarala** [comment]
@fatcerberus It is sufficient for almost all real world use cases - like I said above, one needs a >64GB heap to cause wrapping.

**Comment by svaarala** [comment]
@fatcerberus And even if a system had a very large memory like 256GB (and ignoring the fact that a stop-the-world mark-and-sweep would work very badly in such an environment), one would only really overflow 32 bits by trying to do so on purpose -- for example, malicious crafted code might want to try to do that.

But it's a very remote issue because Duktape on a 64+GB heap is not very feasible at present at least with voluntary GC enabled (one would need incremental mark-and-sweep for such cases to work smoothly).

**Comment by svaarala** [comment]
Ok, #1401 makes the refcount change.

**Comment by svaarala** [comment]
@beevik The change is now in master, thanks for bringing this up!
