### ISSUE TITLE
New warnings when compiling 1.1.2

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#141]
Compiling Duktape 1.1.2 in Visual Studio 2013 now yields the following warnings:

1>duk_js_executor.c(3118): warning C4244: 'initializing' : conversion from 'unsigned long' to 'duk_small_uint_fast_t', possible loss of data
1>duk_js_executor.c(3549): warning C4244: 'initializing' : conversion from 'unsigned long' to 'duk_small_uint_fast_t', possible loss of data

Prior to this release, Duktape compiled cleanly, and I'm not familiar enough with the codebase to know whether this is an issue or not.  Figured I'd mention it just in case.

**Comment by svaarala** [comment]
Thanks for pointing this out - I'll give it a look and apply a fix.

I'm trying to keep a clean compile for "main line" builds, i.e. a modern compiler and usual options. For more rare options there may be warnings, and it's difficult to get a clean build for all compilers.

**Comment by svaarala** [comment]
@fatcerberus This should now be fixed in master - could you check if the fix works for you?

Here's a prebuilt distributable from master:

- http://duktape.org/snapshots/duktape-1.1.99-20150325222308-v1.1.0-260-gfe1372b.tar.xz

**Comment by fatcerberus** [comment]
No more warnings, it compiles cleanly. :-)
