### ISSUE TITLE
How to implement getter/setter in CAPI

### ISSUE THREAD

**Issue by zero-ui** [svaarala/duktape#1413]
I have a c++ class  as follows:

> class AA
> {
> public:
>     AA();
>     ~AA();
>     call();
>     key_setter(int k);
>     int key_getter();
> private:
>     int key;
> };

Implemented code:

> if (!duk_is_constructor_call(ctx)) {
>         return DUK_RET_TYPE_ERROR;
>     }
>     duk_push_this(ctx);
>     duk_push_pointer(ctx, new AA);
>     duk_put_prop_string(ctx, -2, "_ptr");
>     duk_push_c_function(ctx, AA_Call, DUK_VARARGS /*nargs*/);
>     duk_put_prop_string(ctx, -2, "call");
>     ......
>     Here how to achieve getter/setter for AA.key
>    ........
>     return 1;

**Comment by harold-b** [comment]
What you are looking for is [duk_def_prop](http://duktape.org/api.html#duk_def_prop).

**Comment by zero-ui** [comment]
I've seen this,This is code:

>         duk_push_string(ctx, "key");
>         duk_push_c_function(ctx, AA_Get, 0 /*nargs*/);
>         duk_push_c_function(ctx, AA_Set, 1 /*nargs*/);
>         duk_def_prop(ctx,
>             -2,
>             DUK_DEFPROP_HAVE_GETTER |
>             DUK_DEFPROP_HAVE_SETTER |
>             DUK_DEFPROP_HAVE_CONFIGURABLE |  /* clear */
>             DUK_DEFPROP_HAVE_ENUMERABLE | DUK_DEFPROP_ENUMERABLE);

However, the callback function did not respond,If in the end with duk_put_prop_string(ctx, -2, "key");  Get an error ERROR: TypeError: cannot write property 'key' of (0C9D5738)
My JS code:

> var a=new AA();
> a.call();
> a.key=1;
> var b=a.key;;

**Comment by harold-b** [comment]
It looks like you bound the property to the 'getter' function object. ` duk_def_prop(ctx, -2, ...*`. The object index at **-2** is the getter function.

I find it good practice to comment the stack on every line that modifies it:

``` C
duk_push_string(ctx, "key");  // [... key]
duk_push_c_function(ctx, AA_Get, 0 /*nargs*/); // [... key get]
duk_push_c_function(ctx, AA_Set, 1 /*nargs*/); // [... key get set]
duk_def_prop(ctx, ... ); // [...]
```

**Comment by zero-ui** [comment]
Use of constructor function

> duk_push_this(ctx);// [... this]
> duk_push_string(ctx, "key");  // [... this key]
> duk_push_c_function(ctx, AA_Get, 0 /*nargs*/); // [... this key get]
> duk_push_c_function(ctx, AA_Set, 1 /*nargs*/); // [... this key get set]
> duk_def_prop(ctx, ... ); // idx should be?????????

**Comment by harold-b** [comment]
Since you want to bind it to 'this', with your current stack state being `// [... this key get set]`, -1 being `set`, keep decreasing it until you get to `this`, which means it's *-4*.

**Comment by zero-ui** [comment]
Thank you very much. You've been a great help
