### ISSUE TITLE
How to bind a user data

### ISSUE THREAD

**Issue by zero-ui** [svaarala/duktape#1414]
How to bind a user data to a context

**Comment by svaarala** [comment]
A context is a Duktape.Thread instance in Ecmascript terms, and it's an object which can store properties normally. You can store a userdata pointer (I'm assuming you mean a C `void *` with userdata) as a normal or as a "hidden symbol", see http://duktape.org/guide.html#symbols.

**Comment by zero-ui** [comment]
I refer to the dukluv,UserData as the fourth parameter of duk_create_heap

**Comment by svaarala** [comment]
The heap userdata is available to e.g. allocation functions and some of the configuration macros (such as pointer compression).

**Comment by zero-ui** [comment]
Thank you,Is there a similar mujs inside the has callback.    js_newuserdatax

**Comment by zero-ui** [comment]
Because many of my objects are dynamic,

**Comment by svaarala** [comment]
@zero-ui I'm not sure, I haven't used mujs so I'm not sure about that mechanism.

**Comment by zero-ui** [comment]
duk_push_string(ctx, "aa");
        duk_push_c_function(ctx, Getter, 0);
        duk_push_c_function(ctx, Setter, 1);
        duk_def_prop(ctx,...);

        duk_push_string(ctx, "bb");
        duk_push_c_function(ctx, Getter, 0);
        duk_push_c_function(ctx, Setter, 1);
        duk_def_prop(ctx,...);

        duk_push_string(ctx, "cc");
        duk_push_c_function(ctx, Getter, 0);
        duk_push_c_function(ctx, Setter, 1);
        duk_def_prop(ctx,...);

        duk_push_string(ctx, "dd");
        duk_push_c_function(ctx, Getter, 0);
        duk_push_c_function(ctx, Setter, 1);
        duk_def_prop(ctx,...);

............................

**Comment by zero-ui** [comment]
In this case, there are uncertain members,Can handle all requests through a callback.

**Comment by zero-ui** [comment]
for example:

static duk_ret_t Setter(duk_context *ctx) {
    if(memcmp("aa",duk_to_string(ctx,0))){
    .......   
    }else if(memcmp("bb",duk_to_string(ctx,0))){
    .......   
    }else if(memcmp("cc",duk_to_string(ctx,0))){
    .......   
    }else if(memcmp("dd",duk_to_string(ctx,0))){
    .......   
    }else if(memcmp("ee",duk_to_string(ctx,0))){
    .......   
    }
    ......................................
}

**Comment by zero-ui** [comment]
for example:

static duk_ret_t Setter(duk_context *ctx) {
if(memcmp("aa",duk_to_string(ctx,0))==0){
.......
}else if(memcmp("bb",duk_to_string(ctx,0))==0){
.......
}else if(memcmp("cc",duk_to_string(ctx,0))==0){
.......
}else if(memcmp("dd",duk_to_string(ctx,0))==0){
.......
}else if(memcmp("ee",duk_to_string(ctx,0))==0){
.......
}
......................................
}

**Comment by svaarala** [comment]
You could use the "magic" value of a function for that, see:
- http://duktape.org/api.html#duk_set_magic
- http://duktape.org/api.html#duk_get_current_magic

Each C function (getter) you push can have a different magic value. When called, you can access the "magic" value with duk_get_current_magic() in the setter function.

**Comment by zero-ui** [comment]
Although magic can solve the problem of a function call, it is necessary to bind the object in advance

**Comment by svaarala** [comment]
I'm not sure what you are trying to do -- do you want to capture all property accesses regardless of the property names?

**Comment by zero-ui** [comment]
Yes, it is through a callback to handle all property access.For example, in the example of example.aa example.bb example.cc...........,Specific objects may not be clear in advance.I need to judge whether the native attribute exists in this callback

**Comment by svaarala** [comment]
Getters/setters can't do that, but you can use Proxy, see Proxy discussion and examples in http://wiki.duktape.org/HowtoVirtualProperties.html.

**Comment by zero-ui** [comment]
This document does not seem to mention how to achieve CAPI through Proxy

**Comment by svaarala** [comment]
Proxy traps can be Duktape/C functions just like getters/setters. There's no C API to create a proxy so you need to do something like:

```c
duk_get_global_string(ctx, "Proxy");
duk_push_xxx();  /* push target object */
duk_push_object();  /* traps table */
/* set trap functions ('get', 'set', etc) to traps table */
duk_new(ctx, 2 /*nargs*/);
```

**Comment by zero-ui** [comment]
Mujs provides a very convenient function.
void js_newuserdatax(js_State *J, const char *tag, void *data, js_HasProperty has, js_Put put, js_Delete delete1, js_Finalize finalize);,You can refer to the ability to achieve, which is a very convenient feature.

**Comment by svaarala** [comment]
Duktape doesn't have an equivalent to that right now - Proxy with native traps is closest to that I think.

**Comment by zero-ui** [comment]
I'll deal with it first

**Comment by zero-ui** [comment]
Mujs seems to be in the process of dealing with the OP_GETPROP VM callback query attributes exist in HasProperty,Consider adding similar API?

**Comment by svaarala** [comment]
I don't know about the internals of Mujs so I don't know what that means in practice. With Duktape the basic approach right now is to use the standard Proxy construct. There are some backlog items for making more C native object virtualization APIs but no immediate plans now.

**Comment by zero-ui** [comment]
This is not an urgent need to increase the support in the future on the line,Thank you very much for your answer
