### ISSUE TITLE
Duktape.act() reports wrong line number for callstack entries

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#143]
Paste the following code into Dukweb to test.  It should print 4 and 5, but instead prints 5 and 8.

```
(function() {
function cows_eat_kitties() { print(Duktape.act(-3).lineNumber); }
function pigs_eat_cows() { return cows_eat_kitties(); }
pigs_eat_cows();
pigs_eat_cows();


})();
```

This is an issue as I'm calling `Duktape.act()` from C to report the filename and line number of a function call with invalid arguments, so I don't want it blaming the wrong call for the error.

Note that when the requested stack entry is the top level of a script (i.e. remove the wrapper function from the above script), line numbers are reported correctly.

**Comment by svaarala** [comment]
Augmenting the test a bit:

```
(function() {
function cows_eat_kitties() { for (var i = -1; i >= -4; i--) { print(i, JSON.stringify(Duktape.act(i))); }; print(Duktape.act(-3).lineNumber); }
function pigs_eat_cows() { return cows_eat_kitties(); }
pigs_eat_cows();
pigs_eat_cows();


})();
```

Prints:

```
-1 {"lineNumber":0,"pc":0}
-2 {"lineNumber":2,"pc":24}
-3 {"lineNumber":5,"pc":4}
-4 {"lineNumber":8,"pc":5}
5
-1 {"lineNumber":0,"pc":0}
-2 {"lineNumber":2,"pc":24}
-3 {"lineNumber":8,"pc":6}
-4 {"lineNumber":8,"pc":5}
8
```

One issue you see here is that a tailcall will affect the call stack so that indices may not line up as expected. You can prevent a function from being tailcalled by using the following directive:

- http://duktape.org/guide.html#use-duk-notail

**Comment by svaarala** [comment]
Quite likely the line number issue is related to how the compiler assigns line numbers with bytecode instructions emitted. It's got a few known issues (which also affect debugging) where the line of an instruction emitted is actually that of the next token.

For instance, if in the example code you add anything that emits bytecode following the problematic calls, the line numbers come out right:

```
[...]
pigs_eat_cows(); print('dummy');
pigs_eat_cows(); print('dummy');
```

It's a known issue but fixing it requires some compiler rework: the way line numbers are associated with emitted code needs a bit more plumbing.

**Comment by fatcerberus** [comment]
Well, it's good to know it's a known issue at least.  I can deal with it for now--it's not a showstopper.  But a fix would be nice if possible, of course. :smiley:

Out of curiosity, is there a way to set the notail flag on C functions, or is it set by default, or...?

**Comment by svaarala** [comment]
Yeah, I'll try to fix that - it also affects debugging (breakpoints).

C functions are never tail called: tail calls currently only happen when an Ecmascript function calls another Ecmascript function.

**Comment by svaarala** [comment]
After looking at the compiler PC/line information it seems this not a compiler issue but rather there's a bug in `Duktape.act()`. It uses the current PC to come up with the lineNumber but because the PC points to the next instruction to execute (i.e. instruction after a CALL) it needs to be decremented by 1 before the lineNumber lookup. Error augmentation already does the same thing for errors (which come out right).

This diff fixes the issue for the original example:

```
--- a/src/duk_bi_duktape.c
+++ b/src/duk_bi_duktape.c
@@ -146,6 +146,13 @@ DUK_INTERNAL duk_ret_t duk_bi_duktape_object_act(duk_context *ctx) {
        duk_push_tval(ctx, &act->tv_func);

        pc = (duk_uint_fast32_t) act->pc;
+       if (pc > 0) {
+               /* Relevant PC is just before current one because PC is
+                * post-decremented.  This should match what error augment
+                * code does.
+                */
+               pc--;
+       }
        duk_push_uint(ctx, (duk_uint_t) pc);
```

I'll add a testcase and merge a fix next week.

(Even with this fix, there *are* some compiler corner cases where line number assignment may be off by one. This just isn't one of them :-)

**Comment by svaarala** [comment]
(The "post-decremented" in the code comment should of course be "post-incremented".)

**Comment by fatcerberus** [comment]
Awesome, I'll try this out a bit later and see if it fixes the line numbers reported by my engine for script errors.

**Comment by fatcerberus** [comment]
This works perfectly!  Thanks for the quick response! :smile:

**Comment by svaarala** [comment]
Fix now in master.
