### ISSUE TITLE
Decision to keep/remove global binding

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1440]
See https://github.com/tc39/proposal-global/issues/20. Global binding is in master but not yet released, so it can be removed without versioning issues. It could also be made optional and disabled by default.

**Comment by svaarala** [comment]
'global' is now marked experimental and disabled by default in master (enable with DUK_USE_GLOBAL_BINDING), so the situation is now a bit better. Being experimental it can be removed after release too.

Open question remaining: should the binding be removed altogether at this point, before 2.1.0 release.

**Comment by fatcerberus** [comment]
There seems to have been a compatibility issue with a couple (unfortunately high-profile) websites, so the feature was pulled from browsers.  However the conversation appears to have stalled since then, so I can't figure out what the current state of things is.  Best I can tell they're trying to come up with a new name for the binding.

**Comment by fatcerberus** [comment]
In any case, assuming the binding doesn't make it into an ES spec, I'm leaning towards keeping it in as an opt-in, since it *is* provided by Node.js, so it helps with compatibility with existing Node modules.

Alternatively, module-node could provide the binding itself.

**Comment by svaarala** [comment]
Right - though it's maybe possible Node will remove it if it gets rejected in browsers too?

The situation in master should be good with this in mind: it's an opt-in feature and marked experimental if it gets removed. (And if that happens, it's a one-liner for an application to add the binding by itself.)

**Comment by fatcerberus** [comment]
I can't imagine Node removing it as it would break compatibility with existing modules - something they are trying very hard not to do.  See how much consternation there is in the community in trying to come up with a way to implement ES6 modules without breaking CommonJS ones :)

If it ends up getting dropped from ECMAScript completely, I would definitely vote for removing it from the core.  It would help to know what the state of things is, but it just seems like total radio silence right now. :-(

**Comment by svaarala** [comment]
Removed this from 2.1.0 because it's unlikely to get resolved before the release -- and with the option experimental and not enabled by default, it's not a big deal if it gets removed later.

**Comment by svaarala** [comment]
Current status in https://github.com/tc39/proposal-global is that the binding would have the name `globalThis` which would not conflict with existing websites.
