### ISSUE TITLE
Rework TRYCATCH opcode to remove current reg/const limits

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#145]
Current TRYCATCH opcode has a low register limit for both catch register and catch variable name constant. There's no indirect variant or shuffling support.

Related to #144.

**Comment by sva-p** [comment]
The issue preventing a trivial fix is that the `TRYCATCH` opcode is emitted before knowing what the catch variable name constant will be, so the code emitter doesn't know whether shuffling would be needed or not.

This could be fixed by reserving an explicit load slot for the trycatch variable name / with target object (slot C of TRYCATCH) but that would also impact code that doesn't run into shuffle limits.

Another option would be to rework the catch binding handling so that the binding would be set up explicitly in catch code which could then use ordinary shuffling.

**Comment by fatcerberus** [comment]
I must say all this register shuffling talk confuses me.  Doesn't Duktape just interpret bytecode?  There is a stack obviously, but where do the registers come in?

**Comment by svaarala** [comment]
Ecmascript functions allocate a certain number of value stack entries and then refer to these entries as "registers". This is to avoid resizing the value stack for every operation as one would normally do for a stack based interpreter.

But regardless of the type of the interpreter, if the bytecode format uses fixed size instructions (32 bits per instruction for Duktape), the bytecode won't be able to refer to an arbitrary number of indices on the value stack. This is where shuffling comes into play.

For example, for three-argument arithmetic operations of the form "DEST = SRC1 <op> SRC2" the 32-bit opcode format uses 6 bits for the opcodes, 8 bits for the destination register, and 9 bits each for src1/src2 (1 bit indicates either register or constant, and 8 bits are for the index). These operations quite often need shuffling when functions become larger.

**Comment by fatcerberus** [comment]
That's a pretty neat trick, but it must be hell to maintain. :p

**Comment by svaarala** [comment]
Well, there are not that many options: if you have a fixed size opcode format, you'll need to do some shuffling at some point (regardless of whether you're using a register or a stack based VM), at least to access constant tables or function arguments/bound variables.

Another alternative would be to use a variable size opcode format, so that opcode arguments would be represented e.g. as varints. This would be much simpler, but quite slow to decode. I wouldn't actually mind that personally but other people are more performance sensitive than me ;)

But yeah, it's pretty awkward to maintain. That's why it helps to have a regular opcode layout whenever that is possible so that the shuffle code is shared. There's also a "shuffle torture" option which helps in catching shuffling related bugs, which are only triggered otherwise by large functions.

**Comment by svaarala** [comment]
Draft solution here:

- https://github.com/svaarala/duktape/compare/reduce-trycatch-opcode-limits-gh145

Reworks TRYCATCH so that the BC slot (18 bits) is used both for (1) "with" target and catch variable name, and (2) base register for writing thrown value and throw type for catch/finally. The register limit bottleneck is raised from 511 to 262143 as for most other shuffle code.

The cost of this change is that an `LDCONST` is needed for every try-catch. Not sure if this should be merged as there might be a better solution.

**Comment by fatcerberus** [comment]
It just occurred to me: you only encode opcodes using 6 bits?  That seems like you don't have much headroom: you can have no more than 64 different instructions.  Seems like you'd bump into the ceiling pretty quickly...

I guess that's why the bytecode format is specified as strictly internal, so you can change it without violating any versioning guarantees. :P

**Comment by svaarala** [comment]
You're right, 6 bits is already not enough and some opcodes are encoded by setting the opcode field to an "EXTRA" opcode value, and then encoding the extra opcode in field A.

It might be reasonable to use 7 bits for the opcode, probably by stealing one bit from the other fields, but that would increase the need for shuffling so it's not necessarily a good change.

But yes, the format is internal and has actually changed several times already.

**Comment by svaarala** [comment]
There's now a change in master which increases the try-catch register limit from 511 to 262143 (combined BC slot) which should be large enough for most practical code. While there's no indirect opcode or shuffling support, there are similar 262143 register limits for some other opcodes too.
