### ISSUE TITLE
Decode failure error.

### ISSUE THREAD

**Issue by AskingQuestions** [svaarala/duktape#1468]
I am getting an odd error `Decode failure (line x)`

My code reads an entire file into a `const char*` and passes it into `duk_peval(ctx, entireFile)`

If the file has a newline with tabs/spaces in it duk tape gives me the `Decode failure`
Sample:
```
function start() {
print("Test");
}

start();
```
This throws the error `Decode failure (line 5)`

But if run this code
```
function start() {
print("Test");
}
start();
```

It outputs "Test", no errors.

The js file is `utf8` and if you need the code I can post it in a bit.

**Comment by svaarala** [comment]
Having the exact file would help in figuring out the issue, thanks!

**Comment by svaarala** [comment]
Just to be sure, when you read the file and give it to Duktape, is it NUL terminated by the file reading code?

**Comment by AskingQuestions** [comment]
Ok I think I was reading extra characters from other files into the string. I will try to do a line by line eval.
