### ISSUE TITLE
Function to set source of next internal error

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#147]
Yes, another filename/line number-related issue from me. :sweat_smile: 

Don't know if this is possible, but this would be invaluable if it could be implemented.  Currently, I have to have a complicated set of macros for argument type checking because the duk_require-generated errors don't include any fileName or lineNumber info. The macros are quite ugly and look something like this:

```
#define js_begin_api_func(name, min_args) const char* _api_name = name; int _n_args = duk_get_top(ctx); \
	if (_n_args < min_args) js_error(JS_ERROR, -1, "%s(): Wrong number of arguments (%i or more required)", _api_name, min_args)

#define js_bool_arg(argnum, varname) bool varname; \
	else if (!duk_is_boolean(ctx, (argnum) - 1)) js_error(JS_TYPE_ERROR, -1, "%s(): Parameter %i must be boolean (true/false)\n\Value: %s", _api_name, argnum, duk_to_string(ctx, (argnum) - 1)); \
	else varname = duk_require_boolean(ctx, (argnum) - 1)
#define js_maybe_bool_arg(argnum, varname, defval) bool varname; \
	if (_n_args < argnum) varname = defval; \
	else if (!duk_is_boolean(ctx, (argnum) - 1)) js_error(JS_TYPE_ERROR, -1, "%s(): Optional parameter %i must be boolean (true/false)\n\nValue: %s", _api_name, argnum, duk_to_string(ctx, (argnum) - 1)); \
	else varname = duk_require_boolean(ctx, (argnum) - 1)
```

Instead of this mess, it would be nice if I could just set a fileName and lineNumber (something like duk_set_next_error_file_and_line, although perhaps with a less verbose name :) ).  I can call Duktape.act() to retrieve the relevant info from the call stack, so that's not an issue.  I just need a way to get duk_require to include that info in the thrown error.

**Comment by svaarala** [comment]
Adding __FILE__ and __LINE__ to the duk_require_xxx() API calls transparently through macros would be possible. It's already done for duk_error() for instance. I suppose that's the fileName/lineNumber you'd like to see in the error objects?

Not sure about adding a duk_set_next_error_file_and_line(), as there might be some unintended consequences there :)

**Comment by fatcerberus** [comment]
The c file is useless for my intended use case.  I'm using duk_require_xxx to check JS argument types for Duktape/C calls, so I want the error to be reported as coming from the script.  This requires me to pull that info from the call stack, which isn't an issue, but I have no way of telling duktape to use that info for the next duk_require_xx error.

**Comment by svaarala** [comment]
Ok, I see what you mean.  So I guess what you'd need is either "set next error file/line" or perhaps duk_require_xxx() variants that accepted an explicit "blame this file/line" argument pair.

In general, the problem you're dealing with cannot be solved by Duktape itself - the proper file/line to "blame" depends on the application. Sometimes there are wrapper calls that need to be ignored etc, exactly as in your case.

One thing you might be able to do right now is to use an `errCreate` handler:

- http://duktape.org/guide.html#error-handlers

Your handler could use Duktape.act() to find the best file/line to blame and write explicit fileName/lineNumber properties to the error being created. You'll need to use Object.defineProperty or duk_def_prop() to define the properties: plain writes are caught by the getter/setter property in Error.prototype.

Something along these lines:

```
Duktape.errCreate = function (e) {
    var blameFile, blameLine;

    // Only augment Error instances
    if (!(e instanceof Error)) { return e; }

    // Figure out file/line to blame here

    try {
        Object.defineProperties(e, {
            fileName: { value: blameFile, writable: true, enumerable: false, configurable: true },
            lineNumber: { value: blameLine, writable: true, enumerable: false, configurable: true }
        });
    } catch (err) {
        // Ignore error, we don't want errCreate to throw
    }

    return e;
}
```

**Comment by fatcerberus** [comment]
Good to know, I wasn't aware of errCreate.  Does it only apply to errors thrown by Duktape itself (I hope)?  I don't want it to get called when a JS script throws an error, that would be bad.

**Comment by svaarala** [comment]
It applies to all errors being thrown, so you'd need to have some way of deciding when to augment an error or not.

**Comment by fatcerberus** [comment]
Okay, why is this failing?

```
	const char* filename;
	int         line;
	const char* message;
	
	if (!duk_is_error(ctx, 0)) return 1;
	duk_get_prop_string(ctx, 0, "message"); message = duk_get_string(ctx, -1); duk_pop(ctx);
	if (strstr(message, "not ") != message)
		return 1;
	duk_push_global_object(ctx);
	duk_get_prop_string(ctx, -1, "Duktape");
	duk_get_prop_string(ctx, -1, "act"); duk_push_int(ctx, -4);
	duk_call(ctx, 1);
	duk_get_prop_string(ctx, -1, "lineNumber"); line = duk_get_int(ctx, -1); duk_pop(ctx);
	duk_get_prop_string(ctx, -1, "function");
	duk_get_prop_string(ctx, -1, "fileName"); filename = duk_get_string(ctx, -1); duk_pop(ctx);
	duk_push_string(ctx, "fileName"); duk_push_string(ctx, filename);
	duk_def_prop(ctx, 0, DUK_DEFPROP_HAVE_VALUE
		|| DUK_DEFPROP_HAVE_WRITABLE | DUK_DEFPROP_WRITABLE
		|| DUK_DEFPROP_HAVE_CONFIGURABLE | DUK_DEFPROP_CONFIGURABLE
		|| DUK_DEFPROP_HAVE_ENUMERABLE | 0);
	duk_push_string(ctx, "lineNumber"); duk_push_int(ctx, line);
	duk_def_prop(ctx, 0, DUK_DEFPROP_HAVE_VALUE
		|| DUK_DEFPROP_HAVE_WRITABLE | DUK_DEFPROP_WRITABLE
		|| DUK_DEFPROP_HAVE_CONFIGURABLE | DUK_DEFPROP_CONFIGURABLE
		|| DUK_DEFPROP_HAVE_ENUMERABLE | 0);
	return 1;
```
I'm getting a double error.  When running it in the debugger, I found out that the second duk_def_prop() is throwing (not the first).  Did I screw up somewhere?

**Comment by svaarala** [comment]
Maybe it's a copy-paste bug but you have `||` instead of `|` in parts of the expression.

**Comment by fatcerberus** [comment]
Haha, oops.  The funny part is I've made that same mistake before and it took me just as long to figure out the issue that time.

Im embarrassed now...

**Comment by svaarala** [comment]
Been there, done that :)

**Comment by fatcerberus** [comment]
The || typo was indeed the cause of the double fault--well, that and mismanagement of the stack (I was returning the global object instead of the original error due to a missed pop).  It works now.

The errCreate handler is a workable fix for now, but a built-in facility would be preferable, of course. :-)  We have duk_error_raw() after all, so there should be an equivalent for require calls--and anything that can throw, really.

**Comment by svaarala** [comment]
Good to hear you have a workable solution!

Just to make sure, duk_error_raw() is not a public API call and is subject to change arbitrarily: only API calls listed on duktape.org/api.html are guaranteed, public API calls.

Adding an API variant where you could supply the file/line to "blame" for error and require calls would be possible. But, having such a variant for every call that may potentially throw seems unworkable - almost anything can throw an error after all in some exotic scenario (e.g. property reads can invoke a getter that throws, almost anything can fail due to out-of-memory, etc).

So, it's possible to review the existing API calls and add an explicit file/line variant for some of them; and there's an existing issue tracking this (#95). But as a generic solution that doesn't seem workable to me, and something like errCreate/errThrow callbacks are needed to handle it in general (and they have other purposes than file/line assignment too).

Btw, you mentioned that Duktape could provide an API call which would allow to specify the file/line to "blame" for the next error throw. You can simulate that with errCreate yourself: just set the file/line to a global variable and make errCreate copy it to the error being thrown. You can also null out the file/line stored in case an error is not thrown and "blaming" the file/line pair is no longer appropriate.

**Comment by fatcerberus** [comment]
Damn, I would hate to lose duk_error_raw().  I currently use it for this nifty "blame" function:

```
void
duk_error_ni(duk_context* ctx, int blame_offset, duk_errcode_t err_code, const char* fmt, ...)
{
	va_list ap;
	
	const char*   filename = NULL;
	int           line_number;
	const char*   full_path;

	// get filename and line number from Duktape call stack
	duk_push_global_object(g_duktape);
	duk_get_prop_string(g_duktape, -1, "Duktape");
	duk_get_prop_string(g_duktape, -1, "act"); duk_push_int(g_duktape, -2 + blame_offset); duk_call(g_duktape, 1);
	if (!duk_is_object(g_duktape, -1)) {
		duk_pop(g_duktape);
		duk_get_prop_string(g_duktape, -1, "act"); duk_push_int(g_duktape, -2); duk_call(g_duktape, 1);
	}
	duk_remove(g_duktape, -2);
	duk_get_prop_string(g_duktape, -1, "lineNumber"); line_number = duk_to_int(g_duktape, -1); duk_pop(g_duktape);
	duk_get_prop_string(g_duktape, -1, "function");
	duk_get_prop_string(g_duktape, -1, "fileName"); full_path = duk_safe_to_string(g_duktape, -1); duk_pop(g_duktape);
	duk_pop_2(g_duktape);

	// strip directory path from filename
	filename = strrchr(full_path, ALLEGRO_NATIVE_PATH_SEP);
	filename = filename != NULL ? filename + 1 : full_path;

	// throw the exception
	va_start(ap, fmt);
	duk_error_va_raw(g_duktape, err_code, filename, line_number, fmt, ap);
	va_end(ap);
}
```

**Comment by svaarala** [comment]
Added #149 to track the request of adding duk_error_*_raw() to the public API.

The reason the internal API calls are not part of the public API is to avoid creating baggage and to allow easier refactoring and experimentation. Adding the equivalent of duk_error_*_raw() to the public API is possible, but:

- We need to ensure the API calls are in good shape to become part of the versioning guarantees.

- The API calls probably need to be renamed for the public API because _raw is preferably only used for internal calls.

Thanks for bringing this up, API convenience is important :)

**Comment by svaarala** [comment]
Concrete change tracked by #149.
