### ISSUE TITLE
how to read vars in javascript

### ISSUE THREAD

**Issue by MarilynDafa** [svaarala/duktape#1476]
//js file
const var APPNAME = "dukdemo";
const var SCREEN_WIDTH = 300;
const var SCREEN_HEIHGT = 300;
const var CONFIG = {
      fullscreen:false
      profiler:false
};

**i want to read these const vars back to c++, 
how to do,need help**

**Comment by svaarala** [comment]
If the script is eval'ed these would become global variables and you could access them e.g. as:

```c
duk_get_global_string(ctx, "SCREEN_WIDTH");
int width = duk_to_int(ctx, -1);
duk_pop(ctx);
```

**Comment by MarilynDafa** [comment]
can not read const var ,duktape is not support es6 now？

**Comment by svaarala** [comment]
Right now `const` is just an alias for `var` with the additional requirement that an initializer is required, so `var SCREEN_WIDTH=128` and `const SCREEN_WIDTH=128` should work the same.

How are you evaluating/running the script? `duk_peval_string()` or something else?

**Comment by denisdemaisbr** [comment]
@MarilynDafa 
recommended book -> http://speakingjs.com/es5/index.html
duktape guide -> http://duktape.org/guide.html
3rd party projects using duktape -> http://wiki.duktape.org/ProjectsUsingDuktape.html

**Comment by fatcerberus** [comment]
There's no such thing as `const var` even in ES6.  The correct syntax is

```js
const whatever = 812;
```

**Comment by MarilynDafa** [comment]
duk_peval_string_noresult
I use this func

**Comment by svaarala** [comment]
Could you provide a bit more of the source code you're using? With duk_peval_string_noresult a `const FOO = 'bar'` should make "FOO" a globally visible property.

-Sami

**Comment by svaarala** [comment]
@MarilynDafa Was this resolved?

**Comment by svaarala** [comment]
@MarilynDafa I'll close this now, please reopen if the issue wasn't resolved.
