### ISSUE TITLE
Wrong minimum alignment on MIPS o32

### ISSUE THREAD

**Issue by jcowgill** [svaarala/duktape#1478]
I was just browsing the source (as you do) when I notice that `config/architectures/architecture_mips32.h.in` contains this:

```c
/* Based on 'make checkalign' there are no alignment requirements on
 * Linux MIPS except for doubles, which need align by 4.  Alignment
 * requirements vary based on target though.
 */
#if !defined(DUK_USE_ALIGN_BY)
#define DUK_USE_ALIGN_BY 4
#endif
```

The comment here is incorrect. MIPS generally requires alignment equal to the size of the type, and doubles require 8 byte alignment. The ELF ABI suppliment for MIPS (o32) has a table with the alignments for all the C types on page `3-4` here: https://www.linux-mips.org/pub/linux/mips/doc/ABI/psABI_mips3.0.pdf

Having said that, nothing will break completely on Linux because the kernel will attempt to fix any unaligned accesses done by user code - at a huge (probably > 1000x) performance cost.

So please can you change the define to `8` instead of `4`.

**Comment by svaarala** [comment]
Sure, will do.

**Comment by svaarala** [comment]
Ok, #1479 will change the alignment and will be part of 2.1.0 release (which is very close now).

Thanks for bringing this up!
