### ISSUE TITLE
DUK_USE_CPP_EXCEPTIONS: internal duktape exceptions do not trigger destructors

### ISSUE THREAD

**Issue by armornick** [svaarala/duktape#1495]
I've recently tried the `DUK_USE_CPP_EXCEPTIONS` option for Duktape but it doesn't seem to work as intended. Duktape functions which throw an internal error (like the require functions and evaluating source with a syntax error) do not appear to trigger destructors.

I can reproduce the issue by compiling the cpp_exceptions example that comes with Duktape. The example gives the following output (I've removed the rest of the tests because they work as intended):

```
*** test1 - duk_pcall()
my_class instance created
--> rc=1 (SyntaxError: parse error (line 1))

*** test1 - duk_safe_call()
my_class instance created
--> rc=1 (SyntaxError: parse error (line 1))

*** test1 - ecmascript try-catch
my_class instance created
SyntaxError: parse error (line 1)
    at [anon] (eval:1) internal
    at [anon] (duktape.cpp:65998) internal
    at [anon] () native strict preventsyield
    at eval (eval:2) preventsyield
```

As you can see, the destructor is not run when an internal error is thrown. I am using Visual C++ 2013 to compile the code.

**Comment by svaarala** [comment]
Could you describe a bit more how you configure your build? e.g. the tools/configure.py command you're running.

**Comment by svaarala** [comment]
Another useful check is to search for DUK_USE_CPP_EXCEPTIONS in duk_config.h, and ensure it gets #define'd, not #undef'ined.

**Comment by armornick** [comment]
Well, I just used the configure command that's listed on top of the example source:

`python2 tools\configure.py --source-directory src-input --output-directory ..\cpp --config-metadata config -DDUK_USE_CPP_EXCEPTIONS`

I've put all of the files in the same directory and I've also renamed the duktape.c file to duktape.cpp to make sure it gets compiled as C++.

There is a line `#define DUK_USE_CPP_EXCEPTIONS ` in the duk_config.h under the "forced options" section.

The command I've used to compile everything is just `cl /EHsc duktape.cpp cpp_exceptions.cpp`.

Feel free to ask anything else, but that's about everything I've done.

Also, this is unrelated to the bug but I've had to add `return 0` to the function test2_safecall in the example file because it's missing a return statement and wouldn't compile.

**Comment by svaarala** [comment]
Hmm, I'm not familiar with MSVC very much, but maybe this is related:

> c: If used with s (/EHsc), catches C++ exceptions only and tells the compiler to assume that functions declared as extern "C" never throw a C++ exception.

So maybe try `/EHs`?

**Comment by svaarala** [comment]
> Also, this is unrelated to the bug but I've had to add return 0 to the function test2_safecall in the example file because it's missing a return statement and wouldn't compile.

Thanks, it's missing a return, fixed in #1497.

**Comment by armornick** [comment]
Yes, the `/EHs` flag seems to fix the problem.

Thanks for the help.

**Comment by svaarala** [comment]
Good to hear, this is probably worth mentioning in the documentationif `/EHsc` is in common use. I'll figure out a place to add that note.

**Comment by armornick** [comment]
At the very least, it's one of the default compiler flags in CMake so it's probably in common use. I've been able to solve it using this snippet in my CMakeLists.txt:

```
if (MSVC)
	string( REPLACE "/EHsc" "/EHs" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" )
endif()
```

**Comment by svaarala** [comment]
Ok, I'll improve the documentation for MSVC. It's a bit difficult to do more because Duktape doesn't provide ready-to-use build files for platforms in general (just a few examples for Unix-like targets).

I can check if it's possible to detect whether `/EHsc` or `/EHs` is active during compilation. It would be nice to `#error` out if the option is not as expected. A runtime self check might also be possible, but would need to be enabled manually for troubleshooting.

**Comment by svaarala** [comment]
Finally, there's the option of implementing a third compilation mode, "native C++" which would not use `extern "C"` at all. That won't work for a generic library build but would work for embedding. This was on the table back when C++ exception support was added, but didn't seem critical at that point.

**Comment by svaarala** [comment]
The following is set based on documentation:

> _CPPUNWIND Defined as 1 if one or more of the /GX (Enable Exception Handling), /clr (Common Language Runtime Compilation), or /EH (Exception Handling Model) compiler options are set. Otherwise, undefined.

But it doesn't differentiate between different /EH options so it wouldn't help here.
