### ISSUE TITLE
Resource-constrained hardware compatibility list

### ISSUE THREAD

**Issue by mrquincle** [svaarala/duktape#150]
Hi there,

Currently we are working on microcontrollers (the nRF51822) with 256k FLASH and 32k RAM. You are slowly reaching this market segment with your engine with your requirements of 256k FLASH and 96k RAM.

Have you thought about make a list of compatible resource-constrained hardware? I think a list of microcontrollers that can run your code would give a powerful message.

Thanks!

**Comment by svaarala** [comment]
I'll be happy to list "known to work" hardware on duktape.org, so please drop a line if you're working with low memory targets :)

**Comment by mrquincle** [comment]
I am. But not yet with duktape. :-) 

There is an Arduino board that meets your specs, the http://arduino.cc/en/Main/arduinoBoardDue. It has two banks adding up to 96kB. But I don't know of course if hardware has been one of the driving factors for duktape.

**Comment by svaarala** [comment]
Portability and support for relatively low memory targets are an important goal, but it's not targeted at specific hardware.

**Comment by svaarala** [comment]
The best place for this kind of information would now be https://github.com/svaarala/duktape-wiki, and since there's no concrete change for this repo, closing.
