### ISSUE TITLE
Add support for TypedArray values

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#151]
Add support for TypedArray values as specified in:

- https://www.khronos.org/registry/typedarray/specs/latest/

ES6 typed arrays are more detailed (not needed initially):

- http://people.mozilla.org/~jorendorff/es6-draft.html#sec-arraybuffer-constructor
- http://people.mozilla.org/~jorendorff/es6-draft.html#sec-typedarray-constructors
- http://people.mozilla.org/~jorendorff/es6-draft.html#sec-arraybuffer-objects
- http://people.mozilla.org/~jorendorff/es6-draft.html#sec-dataview-objects

**Comment by svaarala** [comment]
Mozilla lists the Khronos specification as obsoleted by ES6. There are some behavior difference details between the specifications and Duktape needs to choose one or the other. For example, constructor behavior when called as a normal function (e.g. `ArrayBuffer(16)` instead of `new ArrayBuffer(16)`):

- Khronos spec doesn't apparently explicitly state what to do.
- V8 allows the call, treating it the same as `new ArrayBuffer(16)`.
- ES6 specification  requires the call to be rejected: "ArrayBuffer is not intended to be called as a function and will throw an exception when called in that manner." (http://people.mozilla.org/~jorendorff/es6-draft.html#sec-arraybuffer-constructor)

The same issue applies to view constructors.

**Comment by fatcerberus** [comment]
I would argue for preferring the ES6 behavior, unless it would conflict with real-world use.  If Khronos is considered to be obsoleted by ES6, there's no reason to consider it as anything other than a second opinion.

**Comment by svaarala** [comment]
I agree - I've implemented most stuff that way. So essentially the functional scope is the Khronos specification but with ambiguities resolved from ES6 and other engines.

There's a lot of detailed coercion etc rules (some of which matter while others don't) so the first commit will probably not match ES6 exactly. It's going to take a few iterations, both for the buffer functionality and the C APIs which are obviously not covered by the specifications.

**Comment by fatcerberus** [comment]
Just posting to ask what the progress on this is, if any?  TypedArrays would be a very useful thing to have indeed. :)

**Comment by svaarala** [comment]
First draft here:

- https://github.com/svaarala/duktape/tree/typedarray-nodejs-buffer-support

The draft contains Ecmascript parts of TypedArray support. It doesn't contain:

- C API changes needed to work with buffer objects (instead of plain buffer values)
- Website changes, especially guide section on working with buffer objects
- Changes for better interoperability between different buffer types

**Comment by svaarala** [comment]
Now merged to master.

**Comment by fatcerberus** [comment]
This is awesome, I'm going to have to try this out some time soon. :)

**Comment by svaarala** [comment]
Just note that the merge only covers the Ecmascript parts :) There's work to do in making buffer objects (as opposed to just plain buffers) conveniently usable from the C API, and there are separate issues for tracking those changes. There's also a separate issue to support "external" buffers, i.e. buffers whose data area is not allocated or managed by Duktape.

**Comment by JoshEngebretson** [comment]
Thanks!  Looking forward to having a look :+1:
