### ISSUE TITLE
 Is duktape thread safe?

### ISSUE THREAD

**Issue by yemingyu** [svaarala/duktape#1519]

**Comment by debdattabasu** [comment]
A duktape heap is thread safe in the same way as std::vector is thread safe. You need to make sure 2 threads do not make calls on a single heap simultaneously. You can have multiple threads simultaneously calling different heaps with no issues. :)

**Comment by yemingyu** [comment]
@debdattabasu Thank you very much!

**Comment by denisdemaisbr** [comment]
@debdattabasu using "mutex locking system" 1+ native threads can be change the same heap safety ?

**Comment by debdattabasu** [comment]
AFAIK a mutex should allow you to call a single heap from multiple threads. However, it is unclear to me why you would want to do such a thing. You will get better performance by just pinning a heap to a particular thread.
