### ISSUE TITLE
Add support for Node.js compatible Buffer object

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#152]
Add support for a Node.js compatible Buffer object, see:

- http://nodejs.org/api/buffer.html

**Comment by svaarala** [comment]
First draft here:

- https://github.com/svaarala/duktape/tree/typedarray-nodejs-buffer-support

The draft contains Ecmascript parts of Node.js Buffer support. It doesn't contain:

- C API changes needed to work with buffer objects (instead of plain buffer values)
- Website changes, especially guide section on working with buffer objects
- Changes for better interoperability between different buffer types

**Comment by svaarala** [comment]
Now merged to master.

**Comment by fatcerberus** [comment]
Does this include ES6 ArrayBuffers/TypedArrays?  I'm not familiar with Node.js so...

**Comment by svaarala** [comment]
@fatcerberus That's covered by #151.
