### ISSUE TITLE
A way to delete a global object property?

### ISSUE THREAD

**Issue by beevik** [svaarala/duktape#1528]
Is there currently a way to delete a property from the global object?

Using the interactive duktape command-line repl, it doesn't seem to be possible.  If I do the following:

```
duk> function Test() {}
= undefined

duk> Test
= {_func:true}

duk> delete Test
= false

duk> Test
= {_func:true}
```

Related: can `duk_del_prop` be used to delete global object properties?

**Comment by svaarala** [comment]
When you declare a global function it's not configurable:

```
duk> function test() {}
duk> Object.getOwnPropertyDescriptor(this, 'test')
= {value:{_func:true},writable:true,enumerable:true,configurable:false}
```

This comes from Ecmascript declaration semantics. You can delete the binding from C code using duk_def_prop() to first make it configurable, and then duk_del_prop().

However, if you just set a property as follows, you can delete it:

```
duk> this.foo = 'bar'
= "bar"
duk> delete this.foo
= true
duk> 'foo' in this
= false
```

So the answer is "yes" for properties - but "only from C" for global function and variable declarations.

**Comment by svaarala** [comment]
`duk_del_prop()` can be used to delete global properties, but only if they're configurable (i.e. not declarations).

**Comment by beevik** [comment]
thanks.

**Comment by svaarala** [comment]
Btw, the property attributes related to global declarations expose one difference between program code and eval code running in the global context:

```
duk> eval('function test() {}');
= undefined
duk> Object.getOwnPropertyDescriptor(this, 'test')
= {value:{_func:true},writable:true,enumerable:true,configurable:true}
```

Declarations established via 'eval' *are* configurable (= deletable).

**Comment by beevik** [comment]
Am I correct in thinking I need to use the flags `DUK_DEFPROP_FORCE | DUK_DEFPROP_SET_CONFIGURABLE` when I try to use C to convert a function property to a configurable one?

**Comment by svaarala** [comment]
That's correct, the "force" is needed because Ecmascript semantics would otherwise prevent a non-configurable property from being changed into a configurable one.
