### ISSUE TITLE
Object.prototype.__define{Getter,Setter}__ native support

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1529]
These are included in Annex B of Ecmascript 2017:
https://raw.githubusercontent.com/tc39/ecma262/es2017/spec.html#sec-additional-properties-of-the-object.prototype-object

These two functions are used by a LOT of legacy code (predating `Object.defineProperty()` by quite some time), enough so that it's almost *always* necessary to polyfill them.  It'd be better just to provide them natively.

**Comment by svaarala** [comment]
Agreed, I've also encountered them a lot.

**Comment by fatcerberus** [comment]
I notice tag is es2018 - are they skipping out on a spec release for 2017?

**Comment by svaarala** [comment]
I don't think so - but the link you provided is for ES2018 draft.

**Comment by svaarala** [comment]
Seems that the feature is already in ES2017 (ES8): https://raw.githubusercontent.com/tc39/ecma262/es2017/spec.html.

**Comment by svaarala** [comment]
@fatcerberus Could you update the description to point to ES2017 (rather than ES2018) draft? Doesn't feel right to edit someone else's description :)

**Comment by fatcerberus** [comment]
Sure.

It's weird, when I originally googled "Ecmascript 2017" I didn't get anything back, the only thing I was able to find was that ES2018 draft.  I just figured maybe they skipped a 2017 revision.

**Comment by svaarala** [comment]
There's a es2017 branch in the TC39 repo, so I guess it's still under editing or something?

**Comment by svaarala** [comment]
I wasn't able to find a formatted ES2017 link so maybe the one I posted above (raw HTML content) is OK.
