### ISSUE TITLE
Add support for external buffer values

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#153]
Add support for plain buffer values which point to an external (user allocated) memory area, such as a frame buffer allocated by a graphics library.

The same capability of pointing to an external buffer should also be present for TypedArray and Buffer.

**Comment by megous** [comment]
Hi, it would be nice if the API would allow for passing a callback that the creator of the buffer object could use to get notified when duktape releases the Buffer (when it's garbage collected).

Or if it will be possible to use Duktape.fin, it may be enough, though a little awkward to use.

**Comment by svaarala** [comment]
There's also a C API for setting a finalizer, `duk_set_finalizer()`. A finalizer can currently only be set on a Buffer object (not a plain buffer value) though.

**Comment by svaarala** [comment]
The new API calls coming in this merge are:

- `duk_push_external_buffer(ctx)`: push an external buffer, initial pointer is NULL, size zero
- `duk_config_buffer(ctx, obj_idx, new_ptr, new_size)`: configure an external buffer with a specified pointer and size
- `duk_is_external_buffer(ctx, obj_idx)`: 1 if buffer is external, 0 if not

Naming for `duk_config_buffer()` is chosen to match `duk_resize_buffer()` and `duk_steal_buffer()`: both of those work only on dynamic buffers but that is not mentioned in the API call name (i.e. they are not `duk_resize_dynamic_buffer()` or `duk_steal_dynamic_buffer()`). Another alternative I considered was `duk_set_external_buffer()` but consistency with previous calls seems useful.

**Comment by svaarala** [comment]
Merged to master. Impact on x64 code footprint (gcc -Os) is about +200 bytes.
