### ISSUE TITLE
Projects using duktape

### ISSUE THREAD

**Issue by zero-rp** [svaarala/duktape#1532]
https://github.com/zero-rp/ZUI,Hope included in the ProjectsUsingDuktape

**Comment by svaarala** [comment]
Thanks, I'll add them to the list. Could you provide exact link(s) and descriptions?

**Comment by zero-rp** [comment]
https://github.com/zero-rp/ZUI,A cross platform UI development library that uses duktape as a scripting framework and introduces the libuv async framework

**Comment by svaarala** [comment]
Thanks! Added in https://github.com/svaarala/duktape-wiki/pull/175. Shortened the description a bit for layout.
