### ISSUE TITLE
Makefile.dukdebug missing functionality like `print()`

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1535]
I'm not sure if that is the result of moving out some functionality into the extras folder, but currently when you build the `duk` demo it cannot even run `mandel.js` because of the missing `print()` support.

Steps to reproduce:
1. Build the `duk` app (here with debugger support): `make -f Makefile.dukdebug`
2. Run the app: `./duk mandel.js`

Output is:
```
ReferenceError: identifier 'print' undefined
    at [anon] (prep/duktape.c:78106) internal
    at global (mandel.js:52) preventsyield
error in executing file mandel.js
```

I'm on latest macOS.

**Comment by svaarala** [comment]
Thanks, Makefile.dukdebug is missing the print() and console bindings that Makefile.cmdline has. I'll fix that.
