### ISSUE TITLE
[Q] duktape and test frameworks

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1549]
Has anyone ever used one of the well known test frameworks (Mocha, Jasmine, QUnit) with duktape? I can't get any of them to work here. At least I can successfully import Jasmine, but using it fails with undefined identifier errors I can't explain.

Is there perhaps a different test framework that works with duktape?

**Comment by svaarala** [comment]
I don't have first hand experience - probably those undefined identifier errors are just plain missing bindings such as expecting `setTimeout`, `window`, etc.

**Comment by mike-lischke** [comment]
OK, just was wondering if anyone ever made it to use a test framework with duktape. I came quite far with Jasmine, but the Jasmine npm requires quite some NodeJS machinery to work (and the browser version relies too much on things only available in a browser). Thanks.

**Comment by svaarala** [comment]
Maybe someone else has done that, I've only needed to run some test sets like test262, underscore tests, bluebird tests etc, and most of those need a small shim to provide missing bindings. But if the test suite expects a lot of helper modules, it's probably not going to be a trivial task.

**Comment by svaarala** [comment]
@mike-lischke Just as a concrete example, here's an example of what Bluebird test set needed: https://github.com/svaarala/duktape/blob/master/util/bluebird-test-shim.js. Fully fledged test frameworks will probably require many more bindings, but just to give an idea what kind of stuff is usually needed.

**Comment by mike-lischke** [comment]
The thing is I have to implement quite a number of NodeJS modules anyway (file system, process, path, util etc.) so it's not so much extra work for Jasmine (or other test frameworks). Problems arise when such a library makes use of the more complex stuff like events (EventEmitter etc.).
