### ISSUE TITLE
Latest master can't evaluate core-js

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1554]
Using this copy of core-js (ES6+ polyfill):
https://github.com/fatcerberus/minisphere/blob/master/assets/system/shim.js

And this command-line:
```
./duk shim.js
```

Duktape 2.1.0 successfully runs the file, producing no output.  master (695b187eee4b7c22dffb2b02166c21a9a484e83f) produces:
```
fatcerberus@pigcult-vm:~/src/duktape$ ./duk shim.js
TypeError: cannot read property 'set' of undefined
    at [anon] (duk_hobject_props.c:2299) internal
    at [anon] (shim.js:4775) strict
    at __webpack_require__ (shim.js:28) strict
    at [anon] (shim.js:160) strict
    at __webpack_require__ (shim.js:28) strict tailcall
    at [anon] (shim.js:7431) strict
    at global (shim.js:7438) preventsyield
error in executing file shim.js
```

In my case, core-js failing to execute causes segfaults later in miniSphere, which I don't fully understand why (something to figure out later), but the TypeError itself is clearly a Duktape regression.

**Comment by svaarala** [comment]
Thanks, I'll look into it.

**Comment by svaarala** [comment]
Seems to be related somehow to constructor replacement value handling. Worked before #1545 and broke after; this is enough information to pin it down.

**Comment by svaarala** [comment]
@fatcerberus Autoclosed by pull request, but it'd be great to know if this fixed all the issues in your case. The shim.js now compiles cleanly but there might be some other files that Minisphere depends on.

**Comment by fatcerberus** [comment]
I'll check it out tonight, after I get off work, and let you know then.  Thanks for the quick response as always!

**Comment by svaarala** [comment]
Sounds good, sorry for the breakage, it was a bit surprising none of the existing tests covered this scenario. But now there's more coverage for various tailcall combinations :)

**Comment by fatcerberus** [comment]
Just tested Duktape master with miniSphere - the engine starts up and Spectacles builds and runs without issue at least.  I consider that a pretty thorough test since miniSphere loads core-js on startup and Cell loads both that AND the TypeScript compiler.  So plenty of opportunities there for things to go wrong, and nothing did :)

**Comment by svaarala** [comment]
@fatcerberus Thanks, good to hear :)
