### ISSUE TITLE
[Q] How to handle JS (callback) functions in C code?

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1555]
Since there is no `duk_get_function()` API I wonder how to store JS functions in my C++ implementation. For sending events I need to store listeners which are passed to me (similar to NodeJS' `EventEmitter.addListener()`). What else can I used to store and later call such functions/listeners?

**Comment by svaarala** [comment]
Does this match your scenario: http://wiki.duktape.org/HowtoNativePersistentReferences.html?

**Comment by mike-lischke** [comment]
Excellent and superfast answer! Yes, that looks as if it would work and answers also my next question (how to ensure the callback is not GC'ed). Just need to figure out how keep lists of callbacks for multiple EventEmitter instances. Thanks again!
