### ISSUE TITLE
How to access an object property inside its methods through 'this' keyword?

### ISSUE THREAD

**Issue by edoardomazzella** [svaarala/duktape#1556]
How the 'this' keyword can be associated to the object? thank you.

static duk_ret_t native_print(duk_context *ctx) {
	printf("%s\n", duk_to_string(ctx, -1));		
	return 0;
}

static duk_ret_t print_name(duk_context *ctx) {
	duk_eval_string_noresult(ctx, "print(this.Name);");  //how to do it????
       	return 0;
}

const duk_function_list_entry person_funcs[] = {
    { "printName", print_name, 1 /* no args */ },
    { NULL, NULL, 0 }
};

int main(int argc, char *argv[]) {
	duk_context *ctx = duk_create_heap_default();	/* initialize the context */

	if(ctx){
		duk_push_c_function(ctx, native_print, 1);
		duk_put_global_string(ctx, "print");
		
		duk_idx_t person_idx = duk_push_object(ctx);	
		duk_push_string(ctx, "Edoardo");
		duk_put_prop_string(ctx, person_idx, "Nome");	
		duk_put_function_list(ctx, person_idx, person_funcs);	
		duk_put_global_string(ctx, "Person");
		
		duk_eval_string_noresult(ctx, "Person.printName();" );

		duk_destroy_heap(ctx);
	}
	return 0;
}

**Comment by svaarala** [comment]
In person.printName() you'd do something like:

```js
duk_push_this(ctx);
duk_get_prop_string(ctx, -1, "name");
/* then print top of stack */
```

**Comment by edoardomazzella** [comment]
thank you, it works!

**Comment by svaarala** [comment]
:+1:
