### ISSUE TITLE
Enumeration of virtual properties of a proxy object 

### ISSUE THREAD

**Issue by kurash** [svaarala/duktape#1563]
My (admittedly squirrelly) implementation of a C-based proxy object was working fine with 1.5, but now after moving to 2.1, the properties can't be enumerated.  I get get and set props by name, but things like for-in and JSON.stringify find no properties.

duktape does call my ownKeys method, which is retuning the array of property names,  After duktape gets the array, it does some checks to make sure that names are valid strings/numbers.  It is in this check where it is testing various (internal?) conditions on the object, but those conditions don't hold.  Maybe I am not setting up the proxy object the right way for 2.1?

I can get this to work by changing the duktape code, though this is not the best thing since I do not know the code well enough.  But anyway, the change, in case it points out my mistake or reveals a bug, is to pass the DUK_ENUM_INCLUDE_NONENUMERABLE flag into the call to duk_proxy_ownkeys_postprocess made by duk_hobject_enumerator_create:

	duk_proxy_ownkeys_postprocess(ctx, h_proxy_target, enum_flags | DUK_ENUM_INCLUDE_NONENUMERABLE);

With that change, my virtual properties can be enumerated once again, but I wonder what other effects this change would have.

Any clues about what I might be doing wrong in my own code, or new ways I should be creating proxy objects in 2.1?

**Comment by svaarala** [comment]
It might be the same issue as in #1543?

**Comment by kurash** [comment]
Yes, that is exactly the issue.  I should have included closed issues when I did my search ;-)  So count my vote for getOwnPropertyDescriptor support.

Thanks for the fast response!
