### ISSUE TITLE
How to call the method of a JS object from duktape/C?

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1564]
I thought this should be a simple one but to my surprise I cannot figure out the proper way. Calling a function/method with duktape/C is easy via duk_pcall/duk_pcall_method. The tricky part is how to get to the function to call?

I have a global var `process` and want to call it's `emit()` method. I can simply evaluate the string:

```JS
process.emit("exit", code)
```
and that works nicely. But how to do that in duktape/C? This is what I tried:

```C++
  duk_get_global_string(ctx, "process");
  duk_get_prop_string(ctx, -1, "emit");
  duk_push_string(ctx, "exit");
  duk_push_int(ctx, exitCode);
  duk_int_t r = duk_pcall(ctx, 2);
  duk_pop_2(ctx);
```
but that doesn't trigger the event and the return value is 1. What's the correct way?

**Comment by fatcerberus** [comment]
```js
duk_int_t r = duk_pcall_method(ctx, 2);
```

That should do what you want.

**Comment by mike-lischke** [comment]
Nope, unfortunately this doesn't work either.

**Comment by fatcerberus** [comment]
Hm, well if `duk_pcall[_method]()` is returning nonzero, that means an error was thrown.  You'd have to look at the error value on top of the value stack (before popping it) to get an idea of what went wrong.  Otherwise I have no idea.

**Comment by mike-lischke** [comment]
Got it working:

```C++
  duk_get_global_string(ctx, "process");
  duk_push_string(ctx, "emit");
  duk_push_string(ctx, "exit");
  duk_push_int(ctx, exitCode);
  duk_pcall_prop(ctx, -4, 2);
  duk_pop_2(ctx);
```

**Comment by fatcerberus** [comment]
Huh, kind of weird.  `duk_get_prop_string(ctx, -1, "emit");` should have worked.  `duk_pcall_prop()` does exactly that internally.

**Comment by mike-lischke** [comment]
:-) I was surprised myself, but nothing worked until I detected the `duk_pcall_prop` function .

**Comment by svaarala** [comment]
If you do a duk_get_prop() followed by duk_pcall(), the `this` binding won't be the object where the property was read. `duk_(p)call_prop()` just basically does a `duk_(p)call_method()` where the `this` binding is the object, and the function is `obj.propname`.

**Comment by svaarala** [comment]
I'm not sure if the above was the issue (error or traceback would have been useful :) but there's really no difference between property calls and method calls, it's all about the `this` binding given to the method called. If `this` is incorrect, typically something like `this.callAnotherMethod()` in the target function then fails because `this` is e.g. the global object.

**Comment by mike-lischke** [comment]
Hmm, a traceback? Since there was no exception how can I get a traceback? The call simply did nothing.

**Comment by svaarala** [comment]
If duk_pcall() returns 1, it means an error occurred and an error object is on the top of the value stack.

**Comment by fatcerberus** [comment]
> If you do a duk_get_prop() followed by duk_pcall(), the this binding won't be the object where the property was read.

Right, but apparently `duk_pcall_method()` didn't work in this case either--yet `duk_pcall_prop()` does.  I'm baffled :)

**Comment by svaarala** [comment]
`duk_pcall_method()` with the object set explicitly as the `this` binding should definitely work, as it's literally the same thing as the internal implementation for `duk_pcall_prop()` :-)

So something like:

```
duk_get_prop_string(ctx, obj_idx, "method");
duk_dup(ctx, obj_idx);  /* this binding */
duk_push_string(ctx, "foo");  /* arg 1 */
duk_push_string(ctx, "bar");  /* arg 2 */
ret = duk_pcall_method(ctx, 2 /*nargs*/);
```

**Comment by svaarala** [comment]
@mike-lischke Just to clarify, in Ecmascript a function reference doesn't carry an implicit associated with the object whose method the function is. So if you look up, say, "process.emit", the result of that lookup doesn't remember that it came from "process". The only reason `process.emit(123)` works as a method is that property-based calls automatically copy the base value ("process") to the "this" binding of the call that is ultimately made.

But if you were to do:
```js
var fn = process.emit();
fn(1,2,3);
```

The emit() function would have a `this` binding of undefined (which is coerced to the global object of the function is not strict) and you'd probably see the same failure.

**Comment by fatcerberus** [comment]
The example code (that didn't work) was this:
```js
  duk_get_global_string(ctx, "process");
  duk_get_prop_string(ctx, -1, "emit");
  duk_push_string(ctx, "exit");
  duk_push_int(ctx, exitCode);
  duk_int_t r = duk_pcall(ctx, 2);
```

Equivalent to:
```js
process.emit("exit", code);
```

**Comment by svaarala** [comment]
It's not equivalent because the `this` binding will be undefined (or global object if the target is non-strict). That code would be equivalent to:

```js
var temp = process.emit;
temp("exit", exitCode);
```

**Comment by fatcerberus** [comment]
Sorry, I meant pcall_method :)

**Comment by svaarala** [comment]
If you just changed duk_pcall() to duk_pcall_method() like this:

```c
  duk_get_global_string(ctx, "process");
  duk_get_prop_string(ctx, -1, "emit");
  duk_push_string(ctx, "exit");
  duk_push_int(ctx, exitCode);
  duk_int_t r = duk_pcall_method(ctx, 2);
```

The code wouldn't make sense because duk_pcall_method() consumes 4 parameters here (function, this binding, 2 args) and not 3 like duk_pcall().

So the critical thing would be, what's pushed for the this binding.

**Comment by fatcerberus** [comment]
Ah, I see, the function and this binding are reversed, so you'd have to swap them first.  I think I opened an issue requesting a change to that... :)

**Comment by svaarala** [comment]
The fixed call sequence would be something like:

```c
  duk_get_global_string(ctx, "process");
  duk_get_prop_string(ctx, -1, "emit");
  duk_dup(ctx, -2);  /* this binding = process */
  duk_push_string(ctx, "exit");
  duk_push_int(ctx, exitCode);
  duk_int_t r = duk_pcall_method(ctx, 2);
```

The value stack would be:

```
process emit process "exit" exitCode
```

And you'd call emit(), with "process" as the this binding, with "exit" and exitCode arguments. Value stack after would be:

```
process result
```

**Comment by svaarala** [comment]
> Ah, I see, the function and this binding are reversed, so you'd have to swap them first. I think I opened an issue requesting a change to that... :)

That would be useful here but not in other situations necessarily. Typically property based calls are made with duk_pcall_prop() because it most closely evaluates the same as `obj.method(...)`.

One merit of the current value stack order (besides being in use already :) is that it matches func.call(). Value stack:

```
func myThis arg1 arg2
```

plus duk_pcall_method() evaluates like:

```
func.apply(myThis, arg1, arg2);
```

and the value are logically in the same order.

**Comment by mike-lischke** [comment]
I see, for the duk_pcall_method attempt I made earlier I should have added a proper this binding. Now that this is fixed it also works as expected. What would be a good use case to use duk_pcall_prop if you consider there is duk_pcall_method?

**Comment by svaarala** [comment]
Using duk_(p)call_prop() is usually more convenient if you want to make a property-based call, and it's also self evident from the call site that a `foo.bar()` style call is being made. `duk_(p)call_method()` is the most generic (non-constructor) call at present because you control the "this" binding exactly. The other calls are just convenience wrappers for it:
- `duk_(p)call_prop()` for property-based calls, i.e. `foo.bar()`
- `duk_(p)call()` when you want something similar to a plain `foo()` call and the default `this` binding is fine.

Both can be done using `duk_(p)call_method()` with a bit more inconvenience.

**Comment by mike-lischke** [comment]
Great, thanks for the explanation!

**Comment by svaarala** [comment]
Maybe it'd be helpful to have a wiki page with a table containing the Duktape API calls and the Ecmascript equivalents. Behavior of the "this" binding is not always well understood because you don't deal with it as directly in Ecmascript code as you do in the C API.

**Comment by svaarala** [comment]
@mike-lischke Here's an initial rough version I'll merge in so that the topic is at least minimally covered: https://github.com/svaarala/duktape-wiki/blob/29b14033d028b8b120aee0d0ff619cc77f39b52b/HowtoFunctionCalls.md. Feedback welcome :)

**Comment by mike-lischke** [comment]
@svaarala That looks very concise and yet covers all relevant cases. That's how it should be :-) The only improvement I'd like to see is code formatting in the table. And maybe a word or 2 about `duk_call_method` vs. `duk_call_prop`.
