### ISSUE TITLE
How to make a function global?

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1568]
The question title is a bit weird, but I'm going to explain it anyway :-)

Normally, in NodeJS or in a browser, when you store a variable or function on the `global` or `window` object it will be globally available in all scripts (without using `window.` or `global.` qualifiers), right? How can this be done in duktape? I already created a `global` object, but don't know how to continue.

Maybe I'm misunderstanding something here, so let me quickly explain what I'm actually trying to do: my app can now load the Jasmine test framework node module, which defines some functions like `describe()` or `it()`, just like Mocha does. You can usually just call them without a need to "require" something or have an object to call things on. However, in my test spec files I get an error that `describe` is unknown. So I wonder what could be wrong here? The frameworks seems to load fine (no errors and I get output from it).

The call stack is:
```bash
Could not load main script: main.js
ReferenceError: identifier 'describe' undefined
    at main (<path>/tests/self-tests/path-test.js:4)
    at require () native 
    at forEach () native 
    at runtTests (main.js:26)
    at global (main.js:35)
    at [anon] (node_modules/jasmine/lib/jasmine.js:198)
    at [anon] (eval:1)
```

and path-test.js contains:

```js

"use strict"

describe("Blah", function() {
  it("Do it", function() {
    print("testing");
  });
});
```

**Comment by svaarala** [comment]
I'm assuming you want to do this from Ecmascript (not C) code.

If a script just writes:

```js
foo = 123;
```

it will establish a global "foo" property (assuming no shadowing variable exists) from either program code, eval code, or even function code (which includes modules).  If you say:

```js
var foo = 123;
```

a global variable is established if the statement is executed as program code or eval code in the global context. In a function it establishes a local variable.

You can gain access to the global object from any scope as follows:

```js
var global = new Function('return this;')();
global.myProperty = 123;
```

That looks a bit weird, but what it does is: (1) create a non-strict function that returns its "this" binding, and (2) call the function. The call uses "undefined" for the "this" binding, but because the function is not strict, it gets coerced to the global object (which is standard ES "this" binding handling) for the call. The return value is thus always the global object, regardless of where the idiom occurs.

**Comment by svaarala** [comment]
Besides that low level answer it's a bit difficult to be sure what needs fixing in the setup.

Maybe something needs to do:

```js
(function () {
    var global = new Function('return this;')();
    global.describe = require('something)'.describe;
    global.it = require('something)'.it;
    // ... more?
})();
```

in order to provide the global bindings?

Or, if all the symbols need copying, something like:

```js
(function () {
    var global = new Function('return this;')();
    var mod = require('something');
    for (var k in mod) {
        global[k] = mod[k];  // copy symbols to global object
    }
})();
```

**Comment by mike-lischke** [comment]
Hmm, since the node module is used as is in my app and works in NodeJS I assume its code is already correct. I guess it's something I must yet do to make it work, e.g. provide something that NodeJS does too. Look [here](https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L964). This is where `described` is defined. How can this go to the public scope so that I can use the function without any `require` and variable/module qualifier?

I'm sorry if that is mostly not related to duktape, but I believe it must have to do with something my app has to provide via duktape.

**Comment by mike-lischke** [comment]
I just found [this](http://www.w3resource.com/node.js/nodejs-global-object.php), which confirms my assumption that any assignment to the `global` module/namespace automatically makes that available globally. At the moment I have this:

```C++
  duk_push_object(ctx);
  Utils::registerFunctions(ctx, functionList);
  duk_put_global_string(ctx, "global");
```
in order to create such a global namespace. Now, what must be done so that every assignment to this global object is automatically visible in duktape`s global object?

**Comment by mike-lischke** [comment]
I got it to work. A proxy is indeed the right approach. It simply forwards all calls to "get", "set", "ownKeys", "has" and "deleteProperty" to the global duktape object and voila, Jasmine runs nicely. Talking about a problem sometimes helps to solve it :-) Thanks.

**Comment by svaarala** [comment]
Hmm, I'm not sure why a Proxy is needed though - couldn't the global object reference just point to the global object directly? :)

**Comment by fatcerberus** [comment]
It seems like he was trying to get a module designed to be `require()`d to instead put its exports into the global scope, which is just not how CommonJS is designed to work.  The module code would have to be modified.

**Comment by svaarala** [comment]
Right, but if one does that by writing to a Proxy object backed by the global object, why not write to the global object directly? This part I didn't understand.

**Comment by fatcerberus** [comment]
No idea.  I suppose one could proxy `module.exports` to the global object if they didn't want to modify the module itself.

**Comment by svaarala** [comment]
But why Proxy it? Why not just set module.exports = global?

**Comment by svaarala** [comment]
@mike-lischke Great to hear you got it working :) If the solution is generally useful it'd be nice to document the setup for others.

Re: that Proxy/global thing, I'm not sure why a Proxy is required; would this work instead?

```c
duk_push_global_object(ctx);
duk_put_global_string(ctx, "global");
```

This just registers a global symbol "global", pointing to the global object.

**Comment by mike-lischke** [comment]
Well, I thought about simply replacing the global object (and actually even tried it), but then I have to mirror somehow everything that the global object does. I don't see how my replacement object could call the original global object. Hmm, maybe it could store a reference to it in a property? But then it's also kinda proxy, so it doesn't make a difference if I create an explicit proxy or just create an object that acts like one. Hence I decided for the explicit solution. The implementation is super simple anyway.

**Comment by mike-lischke** [comment]
>Re: that Proxy/global thing, I'm not sure why a Proxy is required; would this work instead?
>
>    duk_push_global_object(ctx);
>    duk_put_global_string(ctx, "global");
>
>This just registers a global symbol "global", pointing to the global object.

This is what I used before (in one of my comments I posted that code). But this doesn't replace the global duktape object, but adds an object named `global` to th global duktape object. The thing here is that some libraries (like Jasmine) do this:

```js
var realGlobal = <if browser> window else <if nodejs> global else {}
realGlobal.myFunction = function () { ... }
```

and later in a different file:

```js
myFunction(...)
```

This only works when `myFunction` is available on both the global duktape object and the object property`global` of the global duktape object.

**Comment by fatcerberus** [comment]
Not sure I understand - that code doesn't create a new object, it just adds a global variable `global` referencing the selfsame global object.  Objects in JS have reference semantics, assigning them doesn't create a copy.

**Comment by fatcerberus** [comment]
In other words, if one does this:
```js
var a = {};
var b = a;
b.foo = 812;
console.log(a.foo);
```

That should print 812.  The `global` reference is no different.
