### ISSUE TITLE
Unexpected regex behavior, dash in character class

### ISSUE THREAD

**Issue by mamod** [svaarala/duktape#1569]
```js
var token = /^[a-zA-Z0-9_!#$%&'*+.^`|~-]+$/;
console.log( token.test('Content-Type') );
```

The above prints `false` while it should be `true`

tested with `duktape v 1.4` & `nodejs v6.9.5`  and `latest chrome / firefox` all give true

it seems that removing end regex match will fix this

```js
var token = /^[a-zA-Z0-9_!#$%&'*+.^`|~-]+/;
```

**Comment by svaarala** [comment]
The root cause is related to parsing a literal minus vs. a codepoint range, a simplified repro case is:

```
duk> /[x-]/.test('-')
= false
```

The simplest fix for now is to escape the slash:

```
duk> /[x\-]/.test('-')
= true
```

I'll look into the root cause a bit deeper later.

**Comment by mamod** [comment]
yes I also just found that moving dash any where but the end will fix this too

```js
var token =  /^[a-zA-Z0-9-_]+$/;
console.log( token.test('Content-type') ); // true
```

**Comment by svaarala** [comment]
I think I found the cause: regexp class range '-' parsing checks whether the dash is followed by a ']', but that lookup was wrong in Duktape 2.0 and later.

**Comment by svaarala** [comment]
Ok, #1570 has a bug test case and a fix. I'll merge it once the tests pass.

**Comment by mamod** [comment]
I'm not sure how you can be this fast in fixing issues, but you're awesome :+1:

**Comment by svaarala** [comment]
Hehe, thanks :) This one was luckily a small bug probably introduced when reworking some lexer stuff for 2.0 release.

Thanks for reporting it, now it's covered by testcases too :)
