### ISSUE TITLE
Configuring Regexp stack limits

### ISSUE THREAD

**Issue by josh** [svaarala/duktape#157]
Hey @svaarala,

Hit an issue trying to get some code to compile within the CoffeeScript compiler within duktape (again, :wink:).

I narrowed it down pretty far this time. And of course was Regexp related.

``` js
/^(?:[^\\"#]|\\[\s\S]|"(?!"")|\#(?!\{))*/.exec("form[data-remote] input[type=submit],\nform[data-remote] button[type=submit],\nform[data-remote] button:not([type]),\nform[data-remote-submit] input[type=submit],\nform[data-remote-submit] button[type=submit],\nform[data-remote-submit] button:not([type])\n\"\"\"")
```

```
duk> /^(?:[^\\"#]|\\[\s\S]|"(?!"")|\#(?!\{))*/.exec("form[data-remote] input[type=submit],\nform[data-remote] button[type=submit],\nform[data-remote] button:not([type]),\nform[data-remote-submit] input[type=submit],\nform[data-remote-submit] button[type=submit],\nform[data-remote-submit] button:not([type])\n\"\"\"")
RangeError: regexp executor recursion limit
	duk_regexp_executor.c:145
	exec  native strict preventsyield
	global input:1 preventsyield
```

It seemed like this specific example was just a few iterations over the `1000` deep stack limit for `DUK_RE_EXECUTE_RECURSION_LIMIT`. I only had to bump it up to `1006` and it started working.

Do you think this default limit is to small for the deep stack mode? Or is this something we can make easier to configure via a compile time flag?

Thanks!

**Comment by svaarala** [comment]
It should be easy to make configurable - I can address it as part of #64 for example.

Probably the better fix would be to make the Regexp engine pluggable (#74). The built-in engine is a pretty minimal implementation because of footprint restrictions, and does backtracking through the C stack which is a limiting factor for large inputs.

**Comment by svaarala** [comment]
Bumped regexp stack depth from 1000 to 10000 for the 1.2.0 release.

In 1.3.0 this should be addressed by adding a DUK_USE_xxx option for the stack limits so that they're configurable from `duk_config.h` (one can then e.g. use sed/awk/patch to replace values).

**Comment by josh** [comment]
Works for me, thanks again @svaarala!

**Comment by svaarala** [comment]
The 1.3.0 DUK_USE_xxx issue is tracked as #165.
