### ISSUE TITLE
Unable to generate unicode table files in windows (duk_unicode_ids_noa.h)

### ISSUE THREAD

**Issue by Sarodh** [svaarala/duktape#1573]
Hi I'm trying to configure v2.0.0 on MSVS 2015. However I'm unable to generate the following files: 

- duk_unicode_ids_noa.h
- duk_unicode_ids_m_let_noa.h
- duk_unicode_idp_m_ids_noa.h
- duk_unicode_caseconv.h

I can't find any advice on how these files are generated either. I'd imagine I should use the tools/extract_caseconv.py to generate the duk_unicode_caseconv.h?

**Comment by svaarala** [comment]
They should be generated automatically by `tools/configure.py`. The other tools (like extract_caseconv.py) are for internal use and you shouldn't need to run them manually.

**Comment by Sarodh** [comment]
Thanks, it's working now
