### ISSUE TITLE
How to modify a javascript variable inside duktape/c function?

### ISSUE THREAD

**Issue by edoardomazzella** [svaarala/duktape#1576]
Suppose i have a pseudo code like this:

duk_eval_string("var a=0; write_two_inside(a); print(a);");

where write_two_inside(a) corresponds to:

static duk_ret_t duk_write_two(duk_context *ctx){
/* code to modify a and obtain a=2 */
  return 0;
}

it would be very helpful if someone can explain me how to do it so that "print(a);" prints 2 instead of 0.
Thank you.

**Comment by svaarala** [comment]
@edoardomazzella Your pseudocode is passing in the value of "a" -- not a reference to "a". So `duk_write_two()` cannot directly write to the variable based on the argument value alone. If you think about it in Ecmascript terms, you can't write a function that gets a reference to variable (other than the variable name).

You could pass in a variable name, e.g. as:

```js
var a = 0; write_two_inside("a"); print(a);
```

and then:

```c
static duk_ret_t duk_write_two(duk_context *ctx) {
    /* Value stack index 0: key. */
    duk_push_global_object(ctx);
    duk_dup(ctx, 0);  /* key */
    duk_push_uint(ctx, 2);  /* value */
    duk_put_prop(ctx, -3);  /* global[key] = value */
    return 0;
}
```

**Comment by edoardomazzella** [comment]
Thank you for the answer. More precisely, I have to wrap a c function with the following prototype "size_t iqReadTimeout(input_queue_t *iqp, uint8_t *bp, size_t n, systime_t timeout);" where bp is an output parameter buffer and the return value is an unsigned integer. My question was about how to write into the buffer without loosing the return value, is the solution you proposed me above the best one in this case or is there a better one? Thank you.

**Comment by mike-lischke** [comment]
I recently answered a [similar question in SO](https://stackoverflow.com/questions/44347242/duktape-modify-variable-argument-in-native-c-code/44352352#44352352).

**Comment by svaarala** [comment]
@edoardomazzella If you're writing bytes into the buffer itself, you'd just pass in a buffer or buffer object by reference, as a normal argument and then operate on it. In Ecmascript terms:

```
function foo(buf) {
    buf[0] = 123;
}
```

That's completely different from writing out a *buffer reference*, i.e. a situation where your function creates a buffer and wants to write that buffer reference to some variable that exists outside the function (which I think was the original question).

To do that, one would need to pass a variable name. Or, you could pass in an object reference where the buffer is written, in Ecmascript terms:

```js
var OUT = {};
function foo(outref) {
    outref.buffer = new Uint8Array(16);
}
foo(OUT);
console.log(OUT.buffer);
```

It should help thinking about the problem first in pure Ecmascript terms, and then translate that to Duktape/C code.

**Comment by edoardomazzella** [comment]
thank you both, very helpful answers! I'm sorry for my lack of experience.

**Comment by svaarala** [comment]
@edoardomazzella You're welcome! Learn by doing :)

**Comment by edoardomazzella** [comment]
hi,
i would like also to do it:
function foo(buf) {
    buf[0] = 123;
}
but inside a duk/c function, so something like:
-on ecmascript side:
"var ciao = new ArrayBuffer(10);  prova(ciao);"

-on C side: 
static duk_ret_t prova(duk_context *ctx){
  size_t sz;

/* and here i want to modify the values of ciao[0], ciao[1], ... , ciao[10] 
* using the duk API
*/ 

  return 0;
}
Can you help me? Thank you!

**Comment by svaarala** [comment]
The basic approach for that would be:

```c
static duk_ret_t prova(duk_context *ctx) {
    unsigned char *buf;
    size_t sz;

    buf = (unsigned char *) duk_require_buffer_data(ctx, 0, &sz);
    /* Then you can modify buf[0] ... buf[sz-1]. */
}
```

**Comment by edoardomazzella** [comment]
i'm sorry , i was not clear enaugh. My problem was not to call duk_require_buffer_data but to modify buf[0]... buf[n].
In C code i have:
static duk_ret_t prova(duk_context *ctx){
  size_t sz;
  uint8_t *ptr = (uint8_t *) duk_get_buffer_data(ctx,-1,&sz);
  unsigned int i;
  for(i=0; i<sz; i++){
    ptr[i] = i;
  }
  return 0;
}
and in Ecmascript:
"var ciao = new ArrayBuffer(10); SD1.prova(ciao);"
"for (i = 0; i < 10; i++) { print(ciao[i]); };"

but result of print is: undefined, undefined, ... undefined... i'm wrong with something?

**Comment by svaarala** [comment]
ArrayBuffer doesn't have virtual index properties so I think the C code is OK but `print(ciao[i])` won't work. In pure Ecmascript:

```
duk> b = new ArrayBuffer(10)
= |00000000000000000000|
duk> b[4]
= undefined
```

If you use Uint8Array instead (same C code is OK) it should work:

```
duk> b = new Uint8Array(10)
= |00000000000000000000|
duk> b[3]
= 0
```

**Comment by edoardomazzella** [comment]
Thank you!
