### ISSUE TITLE
MSVC2015 ARM compile failed

### ISSUE THREAD

**Issue by MarilynDafa** [svaarala/duktape#1577]
duk_config.h
#error cannot determine intptr type

**Comment by svaarala** [comment]
Thanks, I'll try to figure out how the type detection could work on ARM MSVC2015. I don't have that environment myself though, so hopefully you can try out a possible solution :)

**Comment by svaarala** [comment]
Was this from master or some other version BTW?

**Comment by MarilynDafa** [comment]
from master

**Comment by svaarala** [comment]
Ok, thanks, I asked because there were some recent 64-bit type changes in master, though those should only matter for old MSVC versions.

**Comment by svaarala** [comment]
There are very few intptr_t dependencies in the codebase and I've actually been considering removing the type wrapper entirely.

@MarilynDafa Could you try editing `duk_config.h` manually to provide an appropriate duk_(u)intptr_t type so we could see if it's the only problem?

**Comment by nesbox** [comment]
I added `defined(DUK_F_ARM32)` and `defined(DUK_F_ARM)` to the _Pointer size determination_ section to fix the compilation problem

``` C
#if defined(DUK_F_X86) || defined(DUK_F_X32) || \
    defined(DUK_F_M68K) || defined(DUK_F_PPC32) || \
    defined(DUK_F_BCC) || \
    (defined(__WORDSIZE) && (__WORDSIZE == 32)) || \
    ((defined(DUK_F_OLD_SOLARIS) || defined(DUK_F_AIX) || \
      defined(DUK_F_HPUX)) && defined(_ILP32)) || \
	defined(DUK_F_ARM32)
#define DUK_F_32BIT_PTRS
#elif defined(DUK_F_X64) || \
      (defined(__WORDSIZE) && (__WORDSIZE == 64)) || \
   ((defined(DUK_F_OLD_SOLARIS) || defined(DUK_F_AIX) || \
     defined(DUK_F_HPUX)) && defined(_LP64)) || \
	defined(DUK_F_ARM)
#define DUK_F_64BIT_PTRS
#else
/* not sure, not needed with C99 anyway */
#endif
```

**Comment by svaarala** [comment]
@nesbox Thanks, that sounds like a good fix. I can work that into master later on.

Those conditions are getting quite big so maybe the 32-bit/64-bit pointer definition could come from the helper define files, e.g. the file defining `DUK_F_ARM` could also define the pointer size if it's known for the platform, but that's a separate issue.

**Comment by MarilynDafa** [comment]
this bug still exist in version v2.1.1

**Comment by svaarala** [comment]
@MarilynDafa there's no fix in master either yet.

**Comment by svaarala** [comment]
@MarilynDafa could you check if #1675 fixes the issue for you?

**Comment by svaarala** [comment]
@MarilynDafa I merged the pull - let me know if it doesn't work after all. The fix was based on nesbox's fix above.
