### ISSUE TITLE
Debugger improvements for 1.4 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#158]
- [x] Support for showing bytecode while stepping (or at least show current position in bytecode dialog)
- [x] Halt on throw #286

**Comment by svaarala** [comment]
Have to postpone this to 1.4 to make 1.3 release.

**Comment by fatcerberus** [comment]
For the regression testing, I'm not convinced using the JSON proxy for it is a good solution as it adds an additional layer of abstraction between the testcasees and Duktape.  It might be better to use the raw binary protocol for testing.

**Comment by svaarala** [comment]
I agree it'd be better to use the binary protocol directly.

The advantage of using JSON would be that it'd be much easier to write test cases because expect strings and such would be more human readable. The test driver could also in some cases just be an expect script. So while JSON might be technically a bit less direct, it might provide more test coverage for a given effort.

But for the longer term, a debug client test driver will be needed and it should talk binary directly, I agree.

**Comment by fatcerberus** [comment]
I would actually really enjoy the ability to step through bytecode, it would be useful for lower-level debugging or cases where the client can't locate the original source.

**Comment by svaarala** [comment]
I agree, it'd be nice to do that. Also the web UI should show bytecode and ordinary code side by side (it doesn't need to align perfectly but roughly at least).

Opcode stepping shouldn't be too hard to implement, but there are some small details to iron out there. For example, should there be both PC and line oriented breakpoints? Should the stepping mode (PC vs. line) be an actual stateful mode, or should there be separate commands to StepIntoOpcode, StepOverOpcode, etc?

**Comment by fatcerberus** [comment]
I like separate commands a bit more, I think it would allow the client side to more easily switch modes, for example you could start out stepping by line, and then "drill down" and step right into the bytecode without breaking stride.

Plus the current protocol is mostly stateless right now, so adding different states to it might be confusing.

Not sure what to do about breakpoints though.

**Comment by svaarala** [comment]
Closing this as the identified issues have been implemented along with additional features in pulls not referenced here. Moving the debugger regression test into a separate issue.
