### ISSUE TITLE
Redundant info in error print for duktape/C generated errors

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1591]
When you throw an error in JS the resulting error printout only contains the call stack (with the top line containing the thrown error + message):

```
TypeError: Test
    at global (main.js:10)
    at [anon] (eval:1)
```

However, when you throw an error using `duk_error()` things look different. Now the resulting printout has 2 sections: `Message` and `Stack` where the stack repeats (part of) the message. Here's an example:

```
  Message:
    Error: Error while creating folder '': No such file or directory in tests/self-tests/fs-specs.js (line 16)
  Stack:
    Error: Error while creating folder '': No such file or directory
        at emptyDirSync () native 
        at [anon] (tests/self-tests/fs-specs.js:16)
        at call () native 
        at attemptSync (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3898)
        at [anon] (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3887)
        at [anon] (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3872)
        at [anon] (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:816)
        at [anon] (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:478)
        at [anon] (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4975)
        at call () native 
        [...]
```

(the call stack shown here is already cleaned-up, i.e. no C/C++ stuff).  I would like to get rid of the duplicate message. In such a situation I could remove the top entry of the stack, but that removes an important part for JS errors (as there is no dedicated message printout for them). What else could I do?

**Comment by fatcerberus** [comment]
Jasmine is on the stack.  Are you sure it’s not catching the error and rethrowing it?  I haven’t seen an error message that looks like that before.

**Comment by mike-lischke** [comment]
Seems you hit an important point. I didn't expect Jasmine to play a role here, since the difference I saw first was between a top level `throw` in a .js file vs `duk_error()`. However when I throw that error in any of the test functions from Jasmine the message shows up with the duplicate error string. So it looks as if Jasmine is doing the "wrong" thing here. Thanks for getting my head to think in the right direction.

**Comment by fatcerberus** [comment]
An important thing to keep in mind is that in Duktape, like with Lua, once you call into Duktape to execute a script, your C and JS code are fully integrated - Duktape/C functions essentially act as plugins and still run in the same context as any other ecmascript function.  They can throw errors, exceptions will propagate through them while unwinding, etc.  that’s why the “safe call” (error catching) APIs exist, because otherwise you’d throw the error right out of your reach.

This is a bit hard to wrap your head around at first (at least it was for me), but once you understand the implications it becomes very powerful.

**Comment by svaarala** [comment]
Something is catching, modifying, and rethrowing errors - that Message/Stack output definitely doesn't come from Duktape. Some frameworks do catch and rethrow, and may even augment the stack trace before rethrowing. For example, frameworks which translate code may try to modify or add original source file/line information into errors for convenience.

Unfortunately `.stack` is a non-standard property and as such there's no "standard behavior". Duktape's `.stack` is quite close (but not identical) to V8's equivalent so usually things work out fine. In particular, you can (1) assign to `.stack` (replacing the automatic getter-based value), and (2) Object.defineProperty() `.stack`. Usually this is enough for catch/rethrow framework code.
