### ISSUE TITLE
Inconsistent RegExp test results

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#1598]
Hi Svaarala,

I have this code to validate a guid enclosed with braces:

```
var reGuid = /^\{[0-9A-F]{8}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{12}\}$/g;

var m1 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
var m2 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
var m3 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
var m4 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
```

The expected result is true for all four variables but the output is:

```
m1=true
m2=false
m3=true
m4=false
```

Seems the regex state after a test is wrong and cannot restart but a test that fails, resets the internal state correctly.

Regards,
Mauro.

**Comment by svaarala** [comment]
The same happens with Node.js:

```
> var reGuid = /^\{[0-9A-F]{8}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{4}\-[0-9A-F]{12}\}$/g;
undefined
> 
> var m1 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
undefined
> var m2 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
undefined
> var m3 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
undefined
> var m4 = reGuid.test("{A6BFBB23-4426-4CFB-8D2F-5A642566BF94}");
undefined
> m1
true
> m2
false
> m3
true
> m4
false
```

The cause is the global flag (`/g`) of the RegExp. It causes the RegExp to match once, then attempt the second match from end of input (which fails) at which point the RegExp resets back to start of input. For example:

```js
var re = /./g;
var input = 'abc';

for (var i = 0; i < 8; i++) {
    console.log(i, re.lastIndex, re.test(input));
}
```

This will print the following with both Duktape and Node.js:

```
0 0 true
1 1 true
2 2 true
3 3 false
4 0 true
5 1 true
6 2 true
7 3 false
```

**Comment by mxmauro** [comment]
Hi,

Didn't know it was an expected behavior and good hint about Node.js. Next time I found something suspicious, I'll double check it.

Kind regards,
Mauro.

**Comment by svaarala** [comment]
I find the RegExp API a bit weird to work with, but I think the idea with the global match is that you can do e.g.:

```js
var re = /./g;

function dump(input) {
    var m;
    while (m = re.exec(input)) {
        console.log('match:', m[0]);
    }
    console.log('done');
}

dump('abc');
dump('foo');
```

This prints:

```
match: a
match: b
match: c
done
match: f
match: o
match: o
done
```

Without the final non-matching outcome it would be difficult to know when all the matches for a certain input had been matched.

**Comment by fatcerberus** [comment]
I didn't realize that's what the global flag was for.  I thought it just meant to match all occurrences (rather than stopping after the first), didn't know it was also "resumable".

**Comment by mxmauro** [comment]
Just removed the global flag because not needed and works fine.

**Comment by svaarala** [comment]
@fatcerberus Related, the `.lastIndex` property of the RegExp instance tracks the offset where to resume from. It has pretty weird semantics if you resume matching a different string though; you can also set it manually if you don't want to resume matching a string to completion.
