### ISSUE TITLE
Print SyntaxError: unterminated string. why?

### ISSUE THREAD

**Issue by edoardomazzella** [svaarala/duktape#1600]
Hi everybody,
using this example function:
static duk_ret_t native_print(duk_context *ctx) {
  printf("%s\n", duk_to_string(ctx, 0));
  return 0;  /* no return value (= undefined) */
}
when i do " print('ciao \n') " or in general when i use the escape character i get this error: SyntaxError: unterminated string. What's wrong?

**Comment by svaarala** [comment]
If you mean you're doing:

```c
duk_eval_string(ctx, " print('ciao \n') ");
```

then this would fail because Duktape will see the string:

```
 print('ciao 
') 
```

You'd need to escape the newline:

```c
duk_eval_string(ctx, " print('ciao \\n') ");
```

so that Duktape will see:

```
 print('ciao \n') 
```

**Comment by edoardomazzella** [comment]
thanks
