### ISSUE TITLE
Duktape 2.1.0 throws Syntax error for single line comments (//)

### ISSUE THREAD

**Issue by sriniedara** [svaarala/duktape#1609]
I am using Duktape 2.1.0 version with default configuration. It throws Syntax error for single line comments(//) and works fine for multiline comments (/* */). Is this known issue or unsupported in Duktape?

**Comment by fatcerberus** [comment]
I use single-line comments almost exclusively in my JS code and I've never had a problem.  Unless you're using one of the module loaders, in which case this could be #1394?

**Comment by sva-p** [comment]
@sriniedara Could you provide a simple example where this happens?

**Comment by sriniedara** [comment]
Sample code causing the Syntax error
====
function add(a, b){
// var result = a+b;
// return result;
}
========
Error Message :
 Error Name - SyntaxError
 Error Message - parse error (line 1)

**Comment by fatcerberus** [comment]
I can’t reproduce it in dukweb:
http://duktape.org/dukweb.html#function%20add(a%2C%20b)%7B%0A%2F%2F%20var%20result%20%3D%20a%2Bb%3B%0A%2F%2F%20return%20result%3B%0A%7D

> ==> undefined

No syntax error.

**Comment by sriniedara** [comment]
I am using **duk_peval_string(context,script)** API for executing my script. It throws Syntax error especially if single line comment is inside a function definition. if the comment is outside(global code), execution stops there. The Same script works fine with the above given dukweb.html link.
I feel something is missing from my side. I just downloaded the Duktape 2.1.0 version and picked the below files and included in my build system (without running any configuration scripts).
1. duktape.h
2. duktape.c
3. duktape_config.h
4. duktape_custom.h

is there something else to be done?

**Comment by svaarala** [comment]
Could you provide the exact duk_peval_string() call, including the arguments given? (Please use the Markdown block quote syntax so it won't get garbled.)

A typical problem could be:

```c
duk_peval_string(ctx, "(function foo() {"
    "// comment"
    "})()");
```

This will fail because there are no newlines in the C string, in effect the string is:

```
(function foo() {//comment})()
```

So the comment eats the remaining syntax, resulting in a SyntaxError. The correct form is:

```c
duk_peval_string(ctx, "(function foo() {\n"
    "// comment\n"
    "})()\n");
```

No idea if this is the case for you, but this particular issue I've seen a few times.

**Comment by sriniedara** [comment]
Your guess is perfectly right. It's working now.
Thanks for the help.

**Comment by svaarala** [comment]
Good to hear!
