### ISSUE TITLE
Pointer as object property

### ISSUE THREAD

**Issue by edoardomazzella** [svaarala/duktape#1617]
I need to associate a pointer to some Ecmascript object and I've done like this:

void scriptly_create_SD1_object(duk_context *ctx){

  /* push object into the stack */
  duk_idx_t SD1obj_idx = duk_push_object(ctx);

  /* properties */
  duk_push_pointer(ctx, (void *) &SD1);
  duk_put_prop_string(ctx, SD1obj_idx, "driver_pointer");

  duk_push_pointer(ctx, (void *) &SD1el);
  duk_put_prop_string(ctx, SD1obj_idx, "listener_pointer");

  duk_put_function_list(ctx, SD1obj_idx, serial_funcs);

  /* global string */
  duk_put_global_string(ctx, "SD1");
}

I've to use these pointers in some "serial_funcs", but I'm pretty sure that it has no sense to be able to access that properties from Ecmascript code. How can avoid that someone try to access SD1.driver_pointer from Ecmascript? Thank you!

**Comment by svaarala** [comment]
A plain pointer is not very dangerous in Ecmascript code because it can't be dereferenced. But if you still want to hide the properties, you can use hidden symbols (= internal properties in Duktape 1.x terms):

- http://duktape.org/guide.html#symbols

**Comment by svaarala** [comment]
@edoardomazzella Is this resolved?

**Comment by edoardomazzella** [comment]
yes, thank you. Sorry for the delay.
