### ISSUE TITLE
momentJs weird behavior when using duktape

### ISSUE THREAD

**Issue by rbloch** [svaarala/duktape#1623]
Hello,

I included momentJs in duktape and it seemed to work at first. 

First i just tried : 

```javascript
function someTest() {
	var someDate = moment();
	console.debug('someDate : ' + someDate.toString());
}
```
I get the proper result (i have a native console in my app that displays what i want using console.debug in duktape js)

![selection_222](https://user-images.githubusercontent.com/11425264/28408220-1552fd62-6d37-11e7-905b-cd99f8791411.png)

So i tried some other functions

```javascript
function someTest() {
	var start = moment();
	start.startOf('day');
	console.debug('result : ' + start.toString());
}
```
![selection_220](https://user-images.githubusercontent.com/11425264/28408270-34210996-6d37-11e7-9f8c-eb84430c3ba0.png)

Still working. However as i never trust anything :wink: i tried a huge number of it. And suddently :boom: 

```javascript
var end = moment();
end.endOf('day');
console.debug('result : ' + end.toString());
```
![selection_219](https://user-images.githubusercontent.com/11425264/28409481-151501c0-6d3b-11e7-8baf-9775325851b4.png)

Hey! this is not correct :thinking: Let's try in a fiddle

![selection_223](https://user-images.githubusercontent.com/11425264/28408448-c390b3ce-6d37-11e7-9ba0-3084caa7436d.png)

It seems that we've a problem here.

Here is the momentjs doc on the function https://momentjs.com/docs/#/manipulating/end-of

Did someone experience the same problem?

Thanks

**Comment by rbloch** [comment]
I forgot to add it : here is the script i use https://raw.githubusercontent.com/moment/moment/develop/moment.js

**Comment by svaarala** [comment]
Thanks, I'll look into it!

**Comment by svaarala** [comment]
Looks like a bug in bytecode executor unary arithmetic introduced in Duktape 2.0.0. I'll submit a fix pull later today.

**Comment by svaarala** [comment]
#1624 fixes the issue:

```
((o) Duktape [linenoise] 2.1.99 (v2.1.0-307-ga88dcf37-dirty)
duk> end = moment();
= "2017-07-20T09:51:51.468Z"
duk> print(end.endOf('day'))
Thu Jul 20 2017 23:59:59 GMT+0300
= undefined
```

Thanks for pointing this out, it wasn't caught by existing tests, test262, or anything else in the test set :-/

**Comment by rbloch** [comment]
Great thanks for the fast fix!

I found a lot of other functions that were not working. I'll give them a try after the merge

**Comment by svaarala** [comment]
It's quite likely they're from the same cause, because the problematic unary plus occurred quite deep in moment.js.

**Comment by svaarala** [comment]
I'll be out for a couple of hours, if you're anxious you could try #1624 directly :)

**Comment by rbloch** [comment]
:laughing: My anxiety vanished after seeing how fast you fixed this. Thanks a lot.

**Comment by svaarala** [comment]
Merged to master, let's hope that was it.

**Comment by svaarala** [comment]
@rbloch Did you have time to test the fix? Just wanted to be sure this issue is actually closed.

**Comment by rbloch** [comment]
I'm testing right now 😄 , i'll come back with the answer soon

**Comment by rbloch** [comment]
Good news everyone!

I just tested some pieces of code like : 
```javascript
function someTest() {
	var test = moment();
	console.warn('current : ' + test.toString());
	test.endOf('day');
	console.warn('tonight : ' + test.toString());
	test.add(1, 'days');
	console.warn('tomorrow : ' + test.toString());
}
```
Here's what i get : 

![momentjs](https://user-images.githubusercontent.com/11425264/28502400-0274d982-6ff2-11e7-92b4-59b5ab9a8381.png)

It seems to work :+1:

**Comment by fatcerberus** [comment]
Are the functions supposed to mutate the moment object?  Assuming that's normal, looks good :)

**Comment by rbloch** [comment]
The documentation https://momentjs.com/docs/#/manipulating/add/ says : 

```javascript
  moment().add(Number, String);
  moment().add(Duration);
  moment().add(Object);
```

Mutates the original moment by adding time.

So it's fine :)
