### ISSUE TITLE
Calling back into Duktape from debugger callback causes lockout

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1628]
I found something that I'm not sure whether it's a bug or if I just invoked "undefined behavior" due to doing something stupid...  but I found out that if I do in miniSphere:

```js
Dispatch.now(function() {
    // Sphere equivalent of setImmediate()
    ...
});
```

and then issue a Step Over on that call, the debugger will stop responding to commands.  The cause seems to be that the read callback does event loop processing--which is responsible for, among other things, async execution.  What I'm guessing happens is that Duktape does the StepOver, pauses again, then my event loop calls *back* into Duktape (to process the `Dispatch.now()`), and as a result the debugger gets confused about what state it's in.

Like I said, not sure whether it's really a bug or if I just shouldn't be doing that.  Please advise :)

**Comment by svaarala** [comment]
The debugger transport callbacks are explicitly not allowed to ever call back into Duktape, otherwise there are no guarantees as to what happens.

**Comment by svaarala** [comment]
Assuming this is what's happening here, that limitation is mentioned in http://duktape.org/api.html#duk_debugger_attach and https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#duk_debugger_attach so it should be well documented.

I'm not sure if this use case could be easily made to work or not. The main difficulty is that while we read stuff via the read callback, a debugger command may be operating on the value stack and e.g. reading input values or pushing output values. A call into Duktape API may arbitrarily operate on the stack which leads to problems. Also, the debugger code is not ready for most side effects happening while a command is being parsed; a call into any Duktape API can potentially have arbitrary side effects which may be hard to control. Apart from safety issues, there's a current control that prevents recursive debugger code entry, so all debugging features will be disabled for the duration of such recursive calls.

So while it might be possible to make this work, I'm not really sure it would be worth the effort.

**Comment by fatcerberus** [comment]
Yes, I do remember reading that that wasn't allowed now.  The Dispatch calls are a fairly new addition, so I didn't think anything of it when I added it to the event loop.  I can easily modify the engine to avoid calling into Duktape during a debugger callback, so no harm done. :)

**Comment by svaarala** [comment]
Out of curiosity, if there was some assert tests for this, would it have caught the issue earlier, IOW do you diagnose stuff with assertions enabled?

There's an internal assert helper, `DUK_ASSERT_CTX_VALID()` which is already used for API calls. Renaming those to e.g. `DUK_ASSERT_API_ENTRY()` and then tacking on additional validation beyond just checking the context itself would be straightforward. One could e.g. ensure that no API calls are made when transport calls are in progress.

**Comment by fatcerberus** [comment]
There's a decent chance that would have caught it eventually.  Assertions aren't part of my usual workflow even in debug builds (they slow everything down too much to properly test other things), but it's usually the first thing I'll try if I suspect a Duktape bug.

**Comment by svaarala** [comment]
I'll do that assert macro change soon, it'll at least provide a place to tack on future API entry asserts that will then apply automatically.

**Comment by fatcerberus** [comment]
I will close this since the cause of the issue was me violating well-documented restrictions.  There is no issue here other than me being stupid. :)

**Comment by svaarala** [comment]
I left this open to track that "assert if calling into Duktape from debugger callback" issue, but I'll open a separate one for that :)
