### ISSUE TITLE
duk_suspend clears out protected call info but duk_resume doesn't restore it

### ISSUE THREAD

**Issue by mpietras** [svaarala/duktape#1651]
I'm not certain I'm describing the problem exactly but debugging what I'm finding is this: I do a duk_pcompile_lstring which succeeds, followed by a duk_pcall.  In the script that's being executed is a native C function of mine which has some file I/O in it, so it calls duk_suspend/duk_resume during the time of the I/O.  Upon return from the I/O I sometimes (based on the results) want the script to stop executing, so I return DUK_RET_ERROR in that case.  Upon return to the code in duk__handle_call_inner, the negative return code results in a call to duk_error_throw_from_negative_rc which results in a fatal error instead of a protected return because the jmpbuf_ptr is NULL.  Looking back I discovered that it is NULLed out in the duk_suspend but never restored in the duk_resume.  I'm not sure if that was intended or even possible??

**Comment by svaarala** [comment]
I'll need to look into it a bit more, but I think the intent is to store and restore the pointer:
- duk_suspend() takes a copy of the entire duk_ljstate: https://github.com/svaarala/duktape/blob/master/src-input/duk_api_heap.c#L108
- duk_resume() restores the entire duk_ljstate here: https://github.com/svaarala/duktape/blob/master/src-input/duk_api_heap.c#L138

The jmpbuf_ptr is NULLed in duk_suspend(), but only after the state has already been copied for a later resume.

**Comment by svaarala** [comment]
Does this match what your native function is doing:
- Call duk_suspend()
- Do some blocking I/O
- Call duk_resume()
- Then return DUK_ERR_ERROR, depending on the results

Could it be you're returning DUK_ERR_ERROR before the duk_resume() call?

**Comment by svaarala** [comment]
Also something that might matter is what Duktape-related activity happens between the duk_suspend() and duk_resume() - i.e. is another native thread calling into Duktape. If so, what kind of locks are used to ensure only one thread ever calls into Duktape at a time? (If there's no Duktape activity during the blocking I/O, there's no need to suspend/resume.)

**Comment by mpietras** [comment]
Thanks... I saw the fatal happen with a NULL jmpbuf_ptr and I wrongly assumed the resume didn't restore the jmpbuf_ptr because I saw it directly set to NULL in the suspend and not restored in the resume.  Let me debug more and see where else it might be happening...

**Comment by svaarala** [comment]
Ok, let me know what you find out.

I added the most pruned down form of the scenario (as far as I understand it) in #1655, and at least that scenario works in master.

**Comment by mpietras** [comment]
Sorry about the run-around... duk_resume is working correctly when I call it correctly!  I verified that it works correctly with DUK_ERR_ERROR as well.  I had a pause/resume wrapper class that lost the resume part in a bad RVO cast.  Also, thanks for the comment on Duktape activity during I/O... I may re-evaluate my use of suspend/resume because the overall context remains locked to other thread access anyway...

**Comment by svaarala** [comment]
No worries, good that you found the issue :)

I wonder if some assertion could have caught this issue... For example, when the function which called duk_suspend() returned without a corresponding duk_resume(), it might be possible to notice this and assert for it.
