### ISSUE TITLE
Implement ES6 destructuring assignment

### ISSUE THREAD

**Issue by AnastasiaDunbar** [svaarala/duktape#1665]
To swap variables:
```javascript
var a=6,b=3;
[a,b]=[b,a];
console.log(a); //3
console.log(b); //6
```
Array destructuring:
```javascript
var array=[5,3,9,8,3,2];
var [a,b,c,...d]=array;
console.log(a); //5
console.log(b); //3
console.log(c); //9
console.log(d); //[8,3,2]
```
Create variables with values from an object:
```javascript
var object={a:5,b:"+",c:false};
var {c:bool,a}=object; //Creates the variables `bool` and `a` with values from `object`.
console.log(bool); //false
console.log(a); //5
```
More information here:
[Mozilla's documentation](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
[Exploring ES6](http://exploringjs.com/es6/ch_destructuring.html)

**Comment by svaarala** [comment]
Duplicate to #366, closing.

**Comment by AnastasiaDunbar** [comment]
Hmm, didn't see it when I searched it yesterday.
