### ISSUE TITLE
Object.keys support

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1701]
From the docs (e.g. [here](http://wiki.duktape.org/HowtoVirtualProperties.html)) I can't really tell if `Object.keys` is actually supported in duktape. When I try to get all keys from an object it returns an empty array, so it seems there **is** some support, but maybe it's broken.

![object keys](https://user-images.githubusercontent.com/2398704/29810646-e7e708c6-8ca0-11e7-91e1-54db73b7cfd8.png)

However, it seems as if that has to do with how the object has been created. The result from `os.networkInterfaces()` is constructed by duktape/C code. Pure JS code like `var t = Object.keys({ a: 1, b: 2 });` however works as expected.

**Comment by svaarala** [comment]
Object.keys() is supported so I'm not sure what could go wrong here. Object.keys() only returns own properties but that doesn't seem to be an issue. Currently Object.keys() doesn't support a Proxy object, not sure if that could be related?

**Comment by svaarala** [comment]
Could you paste how the C code creates the interface object?

**Comment by mike-lischke** [comment]
Pretty simple code:

```cpp
duk_ret_t OS::networkInterfaces(duk_context* ctx) {
  duk_push_object(ctx);

  for (auto &entry : Platform::get().networkInterfaces()) {
    duk_push_string(ctx, entry.first.c_str());
    duk_idx_t arrayIndex = duk_push_array(ctx);

    duk_uarridx_t index = 0;
    for (auto &interface : entry.second) {
      duk_push_object(ctx);

      duk_push_string(ctx, "address");
      duk_push_string(ctx, interface.address.c_str());
      duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);

      duk_push_string(ctx, "netmask");
      duk_push_string(ctx, interface.netmask.c_str());
      duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);

      duk_push_string(ctx, "family");
      duk_push_string(ctx, interface.family.c_str());
      duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);

      duk_push_string(ctx, "mac");
      duk_push_string(ctx, interface.mac.c_str());
      duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);

      duk_push_string(ctx, "internal");
      duk_push_boolean(ctx, interface.internal);
      duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);

      duk_push_string(ctx, "scopeid");
      duk_push_uint(ctx, static_cast<duk_uint_t>(interface.scopeid));
      duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);

      duk_put_prop_index(ctx, arrayIndex, index++);
    }

    duk_def_prop(ctx, -3, DUK_READ_ONLY | DUK_DEFPROP_HAVE_VALUE);
  }

  return 1;
}
```

**Comment by svaarala** [comment]
Object.keys() doesn't include non-enumerable properties so you should include DUK_DEFPROP_SET_ENUMERABLE to DUK_READ_ONLY.

If you don't want to do that, Object.getOwnPropertyNames() also includes non-enumerable properties.

**Comment by mike-lischke** [comment]
Makes a lot of sense. Thanks for your quick help!
