### ISSUE TITLE
One more project using Duktape...

### ISSUE THREAD

**Issue by dertuxmalwieder** [svaarala/duktape#1715]
Your website states that I should open a GitHub issue when adding Duktape to a project. Well, I started just yesterday: Duktape (glued with Dukglue, I hope it still counts) is the default and only scripting engine of my static blog compiler. :-) Nothing big yet, though.

* [Repository](https://bitbucket.org/tux_/blogcpp/)
* [Website](http://blogcpp.org)

Thank you for Duktape, everyone.

**Comment by svaarala** [comment]
Implemented in https://github.com/svaarala/duktape-wiki/pull/187.
