### ISSUE TITLE
Can a context have both a "public" and a "private" heap?

### ISSUE THREAD

**Issue by edoardomazzella** [svaarala/duktape#1717]
Hi, the question is simple: can a thread have both a public heap, where the objects are shared with the other threads in the heap, and a private heap, where the declared objects can be accessed only by that thread? How to do it?
Thank you!

**Comment by svaarala** [comment]
You could create multiple Duktape heaps: they're isolated from each other, and sharing references (or anything else) won't even work.

Inside a single Duktape heap there's no such isolation. But that's generally not needed: if code A creates an object but doesn't provide any reference to code B, there's no way code C (assuming it is Ecmascript) could access the object. So just ensuring references are not available is enough.

For example, if you create two separate global spaces (duk_push_thread_new_globalenv()), they will have separate global objects and no shared references by default. An object created in one environment, even when registered as a global, won't be visible in the other.

**Comment by edoardomazzella** [comment]
i don't understand how to avoid providing references to other threads in the same heap. If in a thread i do something like this "duk_eval_string(ctx, "'var i = 0;)";  it would be visible to all the threads in the same heap, is it right? how to avoid it?

**Comment by svaarala** [comment]
Suppose you create two global objects using duk_push_thread_new_globalenv(). Call them A and B.

If script code in A does:

```js
var foo = { hello: 'there' };
```

that object will exist in the same Duktape heap as B. But no code in B has a way to read `foo` or reference the target object.

So yes, it would be visible to B if it had the reference, but without the reference it isn't.

**Comment by edoardomazzella** [comment]
ok, but if then i want to declare an object visible from both the threads? i'm trying to wrap semophores of an RTOS so they have to be shared among threads but i also want to have the possibility of declaring objects visible only by one thread. Is it possible?

**Comment by svaarala** [comment]
There's no way to "declare" an object as such, but you can just provide a reference from code A to code B (or vice versa) in some way. Note that you can't provide access to a variable (`foo`) but rather the value (the object).

One way to do that is via C code:
```c
duk_get_global_string(ctx_A, "foo");  /* read the object reference */
duk_xcopy_top(ctx_B /*to*/, ctx_A /*from*/, 1 /*count*/); /* move it to another stack */
duk_pop(ctx_A);  /* remove from A */
duk_put_global_string(ctx_B, "foo");  /* register as global in B */
```

Now code B will see a global variable 'foo' pointing to the same object. The variables are not "linked" in that writing a new value to 'foo' in A or B won't change the other. Only the referenced object is shared.

Note that you don't need to read the reference from a global object or store it to a global object. You can just as well read the property of some object in A and store the value in some object in B. All that matters is that the reference gets copied.

**Comment by edoardomazzella** [comment]
which is, in practice, the difference between threads in different heaps and threads with different global enviroments? why should i choose the first option or the second one?

**Comment by fatcerberus** [comment]
I'm confused what you mean by "thread" - are you talking about native threads?  If so a single Duktape heap is not threadsafe and you will need to create a separate one for each thread.

Note that different heaps can't share objects at all, at least not without serialization.

**Comment by svaarala** [comment]
@edoardomazzella I think most of these issues should be covered by http://duktape.org/guide.html#threading and the links there.

In short, one Duktape heap == one object pool for garbage collection, with only one native thread allowed at a time.

If you have two (or more) Duktape heaps, you can't mix them in API calls or move objects between heaps. Everything that happens between the heaps must be serialized.

**Comment by svaarala** [comment]
@edoardomazzella Closing this now, please reopen if something is unanswered.

**Comment by edoardomazzella** [comment]
ok thank you both, i understood some important things. There is just another question i have that is not very clear in the documentation: inside a certain heap can i suspend the Duktape execution and act on another heap before the duk_resume?

**Comment by fatcerberus** [comment]
That's safe, as long as the two threads don't try to use the heap simultaneously.

**Comment by edoardomazzella** [comment]
thank you!
