### ISSUE TITLE
Warnings (1.2.x) when compiling with fastint support

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#172]
I wanted to test out the new fastint support, but when defining DUK_OPT_FASTINT and compiling with /W3 in MSVC, I get the following warnings:

```
1>duk_api_stack.c(84): warning C4244: 'return' : conversion from 'duk_int64_t' to 'duk_int_t', possible loss of data
1>duk_api_stack.c(141): warning C4244: 'return' : conversion from 'duk_int64_t' to 'duk_uint_t', possible loss of data
1>duk_tval.c(78): warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

These look potentially disastrous.  Compiler is MSVC 2013 (x86 cl.exe 18.0).

**Comment by svaarala** [comment]
Hmm, these look harmless but should be fixed with casts:

- duk_api_stack.c:84: this is just missing a cast, the value is clamped just before return
- duk_api_stack.c:141: same here
- duk_tval.c:78: should also be harmless, just missing a cast

**Comment by svaarala** [comment]
Fixed in master, https://github.com/svaarala/duktape/commit/e13895592af780816d1ff901808b168e986a7237

**Comment by svaarala** [comment]
This snapshot should contain the fix: http://duktape.org/snapshots/duktape-1.2.99-20150408083333-v1.2.0-19-g8d134b4.tar.xz

**Comment by fatcerberus** [comment]
This indeed fixes the warnings.  Thanks!
