### ISSUE TITLE
Incorrect handling of debugger StepOver with tailcalls

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1726]
See issue described in https://github.com/svaarala/duktape/pull/1685#issuecomment-328242066.

**Comment by svaarala** [comment]
@fatcerberus The StepOver + tailcall behavior is broken as you anticipated: when stepping over the tailcall, execution halts in the tailcall target which is inconsistent with how a non-tailcall is handled. I'll figure out a fix.

**Comment by svaarala** [comment]
Also StepInto has a similar bug: it won't trigger correctly because the "function changed" check fails due to the shared activation. I'll fix that at the same time.

**Comment by fatcerberus** [comment]
I think I actually hit that StepInto bug once or twice, but didn’t make the connection to tailcall handling :)
