### ISSUE TITLE
Using stash with array index

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1729]
This is a simple question about usage and if you think this should rather be asked on Stackoverflow, let me know. On SO you get at least some reputation points for answering :-)

I'd like to store values I got on the value stack in the global stash for later availability. I have a C++ class wrapper for such values and am thinking about how to store the managed value. I could convert the wrapper address to a string and use this as property name. However, what if I'd use the address (or a hash made of that) like an array index? Would that internally create a huge array? Something like this:

```cpp
void ScriptingContext::stashValue(duk_idx_t index, void *reference) const {
  index = duk_normalize_index(_ctx, index);
  duk_push_global_stash(_ctx);
  duk_dup(_ctx, index);

  auto hash = std::hash<void *>{}(reference);
  duk_put_prop_index(_ctx, -2, static_cast<duk_uarridx_t>(hash));

  duk_pop(_ctx);
}
```

**Comment by svaarala** [comment]
The internal array implementation has two different storage approaches:
- A flat array of tagged values (`duk_tval`) with no explicit keys. This is for typical dense arrays.
- A plain key/value storage with explicit string keys. This is used for very sparse arrays.

If you use random indexes, the array will fall back to the second storage approach so it won't become huge. However, the per entry cost will be larger than for a normal dense array because the key is stored explicitly, and the key is coerced to a string.

**Comment by svaarala** [comment]
> This is a simple question about usage and if you think this should rather be asked on Stackoverflow, let me know. On SO you get at least some reputation points for answering :-)

In general my hope is that this repo would be for issues regarding changes to Duktape itself, and SO and other programming sites for "how to do X" questions. Of course, sometimes that line is not clear, e.g. when a question leads to some development ideas. So it's not a big deal either way.

**Comment by mike-lischke** [comment]
I see - in that case I can also just use a property and avoid the hash computation. Thanks.

Re: posting questions, I'll try to follow your advice!

**Comment by svaarala** [comment]
> I see - in that case I can also just use a property and avoid the hash computation. Thanks.

That's the situation right now.

The answer might be different if the Duktape internal code was able to store non-string keys without coercion. The main challenges with that are:
- Keys take more space than they do now (they are plain `duk_hstring` pointers at present). This might not be an issue if duk_tval was a tagged pointer as it would take the same space.
- All keys must behave "as if" they were strings, so property lookups need to be able to find the key in any format, from any input format. This is easiest if the partition is strictly defined, e.g. all keys looking like integer strings are always stored as integers, other keys as strings (or symbols).

There's also the question of the ES2015 Map datatypes. I've hoped to use the same data structure for them, so maybe if that succeeds, then sparse integer keyed objects would behave better too.

**Comment by fatcerberus** [comment]
@mike-lischke If I understand your use case right, you're trying to pin heap pointers, in which case you don't even have to hash, you can just use the pointer as a key directly.  The pointer is guaranteed not to change over the lifetime of the object.

Here are my refcounted functions to do what you want to do:
ref: https://github.com/fatcerberus/minisphere/blob/v4.8.6/src/minisphere/utility.c#L212-L255
unref: https://github.com/fatcerberus/minisphere/blob/v4.8.6/src/minisphere/utility.c#L301-L337

See also #176.

**Comment by mike-lischke** [comment]
Seems we all end at the same solution, some sooner, some later :-D. Yes, this is essentially what I'm doing here. Using the heap ptr is a good idea, if there were add_ref and dec_ref functions in duktape/C.
