### ISSUE TITLE
Decode error when encountering accents chars

### ISSUE THREAD

**Issue by rbloch** [svaarala/duktape#1736]
Good evening,

In some of the scripts i'm executing, people used accents chars in comments (not in vars at least! 😌 )

I created a small case that is easier to debug. The following code crashes : 

```c++
duk_peval_string(ctx, "/* àéè */");
```
The error is : `SyntaxError: decode failed (line 0)`

If i remove the accents, everything works fine

Thansk in advance
Best

R. Bloch

**Comment by fatcerberus** [comment]
Duktape expects input in UTF-8.  You can either re-save the scripts as utf8 or else transcode them at runtime if that's not possible.

**Comment by rbloch** [comment]
The scripts are initially in UTF8, but I extract some parts before calling `duk_peval_string` on it and the extracted parts are indeed in ISO-8859-1. Thanks for the answer

**Comment by svaarala** [comment]
It is unfortunately quite common for scripts to even be in some sort of mixed encoding: an UTF-8 file may be edited using a naive editor which doesn't really understand encodings, and the editor may insert ISO-8859-1 characters into the source. Nowadays this is much less of a problem but there may still be some older script files that do have this issue.

The simplest fix is to sanitize the input, e.g. by doing a lenient UTF-8 decode which replaces invalid sequences with U+FFFD. One can use the Ecmascript TextDecoder() binding for this purpose if necessary.

**Comment by svaarala** [comment]
One possible change to the Duktape lexer would be to tolerate invalid UTF-8 and do the equivalent of TextDecoder's U+FFFD replacement inline. I'm not sure if the specification prohibits this or not, but it would be an extension of the accepted input space, converting a SyntaxError into a success case, which are generally allowed.

**Comment by rbloch** [comment]
Yes usually it's way more developer friendly to tolerate invalid char values and replace them like you said.

I agree on the replacement char solution, that would trivially solve 99% of the problems as usually the non proper chars are set in the comments.

Maybe another simpler improvement would be to just slightly change the error message to
`SyntaxError: char decode failed`

Which makes you understand immediately that you've some weird **chars** -> encoding. It'll still be annoying as the dev will have to remove them somehow (src or on the fly) but at least he'll be 100% sure of what is the problem. I think that just a `decode failed` is not verbose enough.

Best :thumbsup:

**Comment by svaarala** [comment]
The other school of thought is that UTF-8 decoding should in general be strict and always reject invalid sequences so that they can be detected and fixed. Pros and cons in each I guess.

I'll improve the error message.
