### ISSUE TITLE
Assert triggered, possible bug, can't reproduce with bare Duktape

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#175]
I'm not entirely sure if this is a bug in my own engine or in Duktape, but since the assert is inside of Duktape itself, I'm assuming an internal error.  This is the assert triggered:

```
PANIC 54: assertion failed: thr->callstack_top == entry_callstack_top + 1 (duk_js_call.c:1348) (calling abort)
```

This is the JS code that triggered it, but it uses API functions specific to minisphere:
```javascript
var foodTalking = function() {
	name = GetCurrentPerson();
	new Scenario()
		.talk(name, 2.0, Infinity, "Please don't eat me, maggie!")
		.talk("maggie", 2.0, Infinity, "Too late!")
		.playSound('Munch.wav')
		.killPerson(name)
		.run(true)
}
SetPersonScript('Scott T', SCRIPT_ON_ACTIVATE_TALK, foodTalking);
SetPersonScript('Bruce', SCRIPT_ON_ACTIVATE_TALK, foodTalking);
SetPersonScript('Lauren', SCRIPT_ON_ACTIVATE_TALK, foodTalking);
SetPersonScript('Katelyn', SCRIPT_ON_ACTIVATE_TALK, foodTalking);
SetPersonScript('Amanda', SCRIPT_ON_ACTIVATE_TALK, foodTalking);
```

It segfaults at the point of calling SetPersonScript(), which shouldn't be an issue as all that does it store the function for later use.  If necessary, I might be able to put together a test case in my engine...

**Comment by svaarala** [comment]
What happens if you run without assertions, is there a crash?

**Comment by fatcerberus** [comment]
Yes, it segfaults.  I originally had assertions off, I turned them on to see if it was a Duktape bug or on my end.

**Comment by svaarala** [comment]
Any chance of running under valgrind? :)

**Comment by fatcerberus** [comment]
I haven't set up a Linux VM yet, but I did use the MSVC profiler and found that memory usage skyrocketed just before the crash, it topped out at about 60MB.

**Comment by svaarala** [comment]
What does SetPersonScript() look like?  What happens if you replace it with an empty function?

**Comment by fatcerberus** [comment]
The relevant code is in these two files:

person.c: https://github.com/fatcerberus/minisphere/blob/master/minisphere/persons.c

script.c: https://github.com/fatcerberus/minisphere/blob/master/minisphere/script.c

In person.c look for JS_SetPersonScript and follow the code path from there.  Sorry I can't simplify it further... :(

**Comment by svaarala** [comment]
What happens if you make SetPersonScript() return immediately? If that avoids the problem, one way to narrow the cause down would be to enable/disable sections of SetPersonScript().

Valgrind is much more cost effective though as a first step :)

**Comment by fatcerberus** [comment]
Yeah, I installed Hyper-V on my laptop but haven't set up a Linux VM yet.  I'll have to get on that! :-)

I'll do some experiments later, I'm away from the computer right now.

**Comment by fatcerberus** [comment]
Okay, interesting thing I found out.  First some background IRT the offending SetPersonScript(): It can be passed either a string or JS function.  If the former, the string is compiled into a function and stored in an array in the global stash to be called later.  If the latter, that function is /also/ stored in the same array, just without the extra compilation step.

If I pass a string to SetPersonScript(), it works fine.  The crash occurs when I pass a function, even an empty one.  What I found out is that, for whatever reason, my function `duk_require_sphere_script()` is erroneously overwriting existing entries in the stash-array.  It just so happens that, in this particular case, the function overwritten was the function that was *currently executing* (to clarify, the SetPersonScript() call happens inside one of these stashed scripts).  Duktape then GCs it since that was the only reference to the function, and... well...

So this is a bug on my end certainly, but I'm wondering if it's ALSO a Duktape bug.  I would think the GC shouldn't be collecting functions mid-execution...

**Comment by svaarala** [comment]
Hmm. Executing functions should be reachable and reference counted through the call stack - but perhaps there's a bug somewhere in there.

**Comment by svaarala** [comment]
More specifically there should be a function reference on the value stack; the activation then uses a borrowed reference to that.

Could the function being executed be a bound function (`xxx.bind()`)? (I'm asking because the bug might be related to bound chain resolution.)

**Comment by fatcerberus** [comment]
It shouldn't be a bound function, as it's taken directly from duk_compile() (specifically `duk_compile_lstring_filename`).

**Comment by svaarala** [comment]
Ok, in that case the value stack below the current function should definitely contain a reference, so either the refcount is mismanaged (leading to the function being freed) or something else goes wrong. The assert that triggered may provide a clue though, because the assert indicates call stack has been unwound incorrectly previously.

**Comment by fatcerberus** [comment]
Okay, you can call off the wild goose chase now.  I found this bit of idiocy in `js_SetPersonScript`:
```
set_person_script(ctx, type, script_id);
```

See the `ctx`?  That's supposed to be a `person_t*`, not a Duktape context.  So in the process of storing the script ID, I was instead overwriting internal Duktape state.  Lovely.

Now the only mystery is why the compiler didn't warn me about passing the wrong pointer type...

**Comment by svaarala** [comment]
Duktape `duk_context *` is currently a `void *` which makes warnings less informative.

I plan to change that as soon as I've worked through a few large upcoming merges.  Sorry :o

**Comment by fatcerberus** [comment]
No problem, I honestly have no clue what I was thinking when I passed a Duktape context to an internal minisphere function like that.  I must just be so used to typing `ctx` that I did it reflexively without even thinking about it.  Interestingly, this was also what caused my stashed scripts to start overwriting each other.  I must have been overwriting something pretty vital to the engine, as it caused everything to go to hell catastrophically. :o)

**Comment by svaarala** [comment]
It's an easy mistake to make; there are two improvements that might make it easier to catch:

- Change `duk_context *` to be a specific struct pointer rather than a `void *`.
- In all public API calls, assert both that `ctx` is non-NULL, and also assert for some known value in the structure to identify the structure (not 100% but would probably catch a useful number of cases).

**Comment by fatcerberus** [comment]
I would think changing this line:
`typedef void duk_context;`

To something like:
`typedef struct duk_hthread duk_context;`

Would be sufficient.  The comments in duktape.h say that `duk_context*` maps directly to `duk_hthread*` anyway, and since nobody's accessing members of a duk_hthread from outside anyway, you don't have to expose the actual struct definition.

**Comment by andoma** [comment]
> It's an easy mistake to make

Yeah, same thing's happened to me once or twice.

**Comment by svaarala** [comment]
@fatcerberus Yep, that would be enough for now. Not 100% sure if there are any legacy compilers that will complain about never seeing the actual definition. They shouldn't because they don't need e.g. the struct size etc.

Anyway, I'm changing the headers so that the internal structures are also visible in the public header so that some basic operations can be made faster (e.g. direct access to the value stack without making an explicit library call). The definition will be visible during compilation then.

**Comment by svaarala** [comment]
Concrete change tracked by #178.
