### ISSUE TITLE
Function constructor end of block issue with // comment

### ISSUE THREAD

**Issue by kakaraky** [svaarala/duktape#1754]
Not sure this has been addressed already, at least not in 2.1.1. Consider this code:

f = new Function("//");

Current Function constructor appends "}" to the code block, which then is ignored by the compiler, since the line is a comment.

Adding a '\n' to duk_bi_function_constructor() in duk_bi_function.c should fix this problem:
	duk_push_string(ctx, "\n}");
	duk_concat(ctx, 5);

**Comment by svaarala** [comment]
@kakaraky Good point, there was a similar issue in the module loaders which was fixed. I'll fix this soon.

**Comment by svaarala** [comment]
Fixed in master, backports to maintenance releases will be done later. Thanks @kakaraky !
