### ISSUE TITLE
`size_t` narrowing warnings under 64-bit MSVC

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#177]
I recently started compiling for x64, and Duktape 1.2.1+ throws the following warnings when compiled:

```
1>duk_bi_string.c(985): warning C4267: '=' : conversion from 'size_t' to 'duk_uint32_t', possible loss of data
1>duk_bi_string.c(986): warning C4267: '=' : conversion from 'size_t' to 'duk_uint32_t', possible loss of data
1>duk_heap_hashstring.c(37): warning C4267: 'initializing' : conversion from 'size_t' to 'duk_uint32_t', possible loss of data
1>duk_util_hashbytes.c(17): warning C4267: 'initializing' : conversion from 'size_t' to 'duk_uint32_t', possible loss of data
```

I don't blame you for these (`int` and `long` are both 32-bit in x64 MSVC, which catches me all the time too as they are 64-bit elsewhere).  They look harmless, but might want to check into them anyway.

**Comment by svaarala** [comment]
Thanks - those coercions should be checked (there's a maximum string length) so they should be harmless. I'll check them out and fix as appropriate.

**Comment by fatcerberus** [comment]
Kind of off topic, but interestingly, the "unary minus on unsigned" warning I reported a few days ago doesn't show up under x64...

**Comment by svaarala** [comment]
The fix is now in master and should be in this snapshot:

- http://duktape.org/snapshots/duktape-1.2.99-20150418184946-v1.2.0-24-gc3aed9c.tar.xz

@fatcerberus If you have time to test, that'd be helpful (I don't get the warnings on Linux x64) :)

**Comment by svaarala** [comment]
Oops, accidentally closed via commit message.

**Comment by fatcerberus** [comment]
Yeah, you wouldn't get the warnings on Linux because every OS other than Windows does the sensible thing and has `int` and `long` be 64-bit in x64 code.  I love Windows to death as an everyday OS, but as a development platform even I'll admit it's rather... suboptimal.

That said, the `size_t` conversion warnings are still present in the snapshot above.  It looks like you snapshotted the wrong commit--you gave me `c3aed9c...` which is a merge.  The casts are the next commit after the merge.

**Comment by svaarala** [comment]
@fatcerberus I know - just meant that as I don't routinely run Windows, I don't have an easy way to check (at least not yet; I'm planning to get an automatic Windows compile test going on soonish).

Sorry about the snapshot, hopefully this is correct:

- http://duktape.org/snapshots/duktape-1.2.99-20150419053002-v1.2.0-27-g0f82a4f.tar.xz

**Comment by fatcerberus** [comment]
Yep, all the warnings are gone. :)
