### ISSUE TITLE
How to parse argument of type String Object (similarly Number object) in a Duktape/C function

### ISSUE THREAD

**Issue by rajubngr** [svaarala/duktape#1807]
How to type check the String object/Number object argument types in duktape c function and parse the value from String object/Number object. There is generic api like duk_is_object() but I need the correct object type to parse the value .

ex: 
ecmascript code
  var str1 = new String("duktape");
   var version = new Number(2.2);
 dukFunPrintArgs(str1,str2); 

dukFunPrintArgs(ctx) //duktape c function :
{
  // code to know whether the args is of type String Object / Number Object
}

**Comment by svaarala** [comment]
In Ecmascript you'd probably do something like `x instanceof String` and the C equivalent of that would be `duk_instanceof()`.

**Comment by svaarala** [comment]
Another approach you can use is `duk_to_primitive()` and then use `duk_is_string()` etc.

**Comment by rajubngr** [comment]
Actually I'm developing a project using Android where the main  business logic will be in Javascript, I will be mapping Ecmascript objects to Java classes  through JNI using duktape .  In this flow  I have a requirement to pass values from and to Ecmascript code to Android Java environment through JNI . 
Lets assume we have Ecmascript mapped duktape c function which takes one argument and the argument type can be  String/String object/Number/Number object/object with properties/Array/Function . So I need to parse the argument passed to duktape c function with correct type and need to pass that value to Java class through JNI .
```
Ex: 
    EcmaScript code calls function defined in duktape c with different types .
    dukFun("duktape");
    dukFun( new String("duktape"));
    dukFun(2.2);
    dukFun(new Number(2.2))
    dukFun({ name : "duktape:, version:2.2})
  ```
In duktape c function i.e dukFun , I was able to detect primitive string and number , object and array using api's `duk_is_string(),duk_is_number(),duk_is_object(),duk_is_array()` but not able to detect String object and Number object . If we pass String object from Ecmascript code, duk_is_object() detects that as object not able to find exact type whether it is String or Number Object .

If we use  `duk_instanceof()` ,how to push String object / Number object to value stack  for comparing like  `x instanceof String` or `x instanceof Number`

In V8 javascript engine , we can check like below . Need similar approach to distinguish between String/Number/Boolean and String/Number/Boolean objects 
 ```
    if(arg->IsBoolean())
	{
	   arg->BooleanValue());
	}
	else if(arg->IsBooleanObject())
	{
	    arg->ToBoolean()->BooleanValue());
	}
	else if( arg->IsNumber())
	{     
	   arg->NumberValue());
	}
	else if (arg->IsNumberObject())
	{
	   arg->ToNumber()->NumberValue());
	}
	else if(arg->IsString())
	{
	    v8::String::Value str(arg);
	}
	else if(arg->IsStringObject())
	{
	    v8::String::Utf8Value str(arg->ToString());
	}
	else if(arg->IsFunction())
	{
		....
	}
	else if(arg->IsArray())
	{
	   .....	
	}
	else if (arg->IsObject())
	{
	   ......
	}
   ```

**Comment by fatcerberus** [comment]
```
duk_get_global_string(ctx, "Number");  // or "String"
```

Then call `duk_instanceof()`.

**Comment by rajubngr** [comment]
The above works . Thanks .
