### ISSUE TITLE
Purpose of duk_safe_call()

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#181]
I'm having a hard time understanding the purpose of `duk_safe_call()`  From what I can gather from reading the documentation, `duk_safe_call` doesn't create a new stack frame, meaning the semantics of this:
```c
duk_safe_call(ctx, my_func, 0, 1);
```
are the same as:
```c
my_func(ctx);
```

Is there something I'm missing?

**Comment by svaarala** [comment]
The main difference is that it provides an error catcher (setjmp/longjmp) so that any error that is thrown inside `duk_safe_call()` is caught. In addition to that it manages the num_args/num_rets value stack shuffling so that you know the shape of the value stack on exit, regardless of where/how the call exits.

**Comment by fatcerberus** [comment]
Ah, so that's what is meant by a "protected C function call".  So it's like `duk_pcall()` except only for Duktape/C functions.  Why does it not create a stack frame though?  That makes it difficult to utilitize, as most Duktape/C funcs are written to use bottom-based indices.

**Comment by svaarala** [comment]
To create a stack frame would mean the usual call mechanics but also a Function object would need to be created. `duk_safe_call()` is intended for running a certain operation in a protected way - that operation might be just a part of what a function does, such as safely coercing a result into a string.

For a protected Duktape/C function call there's currently no syntax sugar, but `duk_push_c_function()` + `duk_pcall()` would do just that. A syntax sugared variant would also do the equivalent operations of creating a Function object and then calling it.

**Comment by fatcerberus** [comment]
This question was answered, so I'll close it.
