### ISSUE TITLE
How to set Object.defineProperty() on instance object(i.e this object)

### ISSUE THREAD

**Issue by rajubngr** [svaarala/duktape#1812]
How to achieve the below Ecmascript equivalent in duktape c .
```
    function ContentProperty() {
    var text = null;
  
    Object.defineProperty(this, 'content', {
      set: function(c) {
        
        text = c;
      },
      get: function() {
        return text;
      }
    });
  }
```

**Comment by fatcerberus** [comment]
Call `duk_push_this(ctx)` to get `this` on the stack, then use `duk_def_prop()`.

**Comment by rajubngr** [comment]
`duk_push_this(ctx)` should be called from duktape constructor function right ?

**Comment by svaarala** [comment]
Right, the expression `this` in an Ecmascript function maps to a `duk_push_this(ctx)` in a Duktape/C function.

**Comment by svaarala** [comment]
@rajubngr Please reopen if there was something not covered in the discussion.
