### ISSUE TITLE
Can I store/maintain duktape objects for adding properties directly on that object instead of getting from hierarchy of namespace 

### ISSUE THREAD

**Issue by rajubngr** [svaarala/duktape#1816]
Lets consider below example. 
```
  xyz  = {};
  uiObject = { } ;
 apiObject = {} ;
 widgetBox = function (){…};
 widgetButton = function () {…};
 networkApi = function(){ … } ;

xyz.ui = uiObject;
uiObject.Box = widgetBox;
xyz.api = apiObject;
apiObject.network = networkApi ;
uiObject. button  = widgetButton ;
```

When above objects are created using duktape c , can I store/maintain (may be heapptr..etc) of uiObject and add properties to that object directly instead of getting uiObject from xyz.ui for adding properties to uiObject in future . 

Actually I'm migrating Android project which uses Google chrome V8 to duktape ecmascript . V8 engine has provision to add properties directly on object directly .

**Comment by armornick** [comment]
If I understand the question correctly, you want to keep a reference to uiObject when you create it in C?

This can be done by registering the object with the [heap stash](http://duktape.org/api.html#duk_push_heap_stash). The heap stash is not accessible from ecmascript itself, so scripts can't reassign the object if that is your business case.

**Comment by svaarala** [comment]
You can use a borrowed heapptr (duk_get_heapptr()) to get access to the object - but you'd then be responsible for being 100% certain you never use the heapptr past a point where it has become unreachable.

**Comment by svaarala** [comment]
A safer approach is to store a reference e.g. to one of the stashes as pointed out by @armornick, but you need some handle (key) to look them up later. For example, if the object in question has a number or string ID (say, object creation count or something like that) that can usually serve as an easy handle.

**Comment by rajubngr** [comment]
@armornick , yes I'm trying to keep a reference to uiObject when I create it in C .
@svaarala , I will try and let u know the results . 

Thanks again .

**Comment by rajubngr** [comment]
Do I need to maintain heap stash reference ? as the uiObject is getting added to xyz object with key as "ui" and xyz is getting added to global object .

**Comment by armornick** [comment]
I guess you don't _have_ to, but you should be careful because someone could remove the reference to your object.

**Comment by svaarala** [comment]
If you were to do that, you should:
- Make the property non-configurable and non-writable (see duk_def_prop() or Object.defineProperty()) so no script code can affect the reference.
- Ensure that you don't ever free the UI object before ensuring that borrowed references have been removed.

**Comment by rajubngr** [comment]
Thanks a lot @armornick  and @svaarala
