### ISSUE TITLE
How to define common getter and setter methods for all dynamic properties?

### ISSUE THREAD

**Issue by rajubngr** [svaarala/duktape#1817]
Actually I'm migrating Google V8 based Android project to Duktape Android project . In Google V8 , there is an api (SetNamedPropertyHandler) for setting single getter and setter for all properties(including dynamic properties ) on the object, can we achieve same thing in Duktape c ? 

SetNamedPropertyHandle() V8 documentaion link :  https://v8docs.nodesource.com/node-0.8/db/d5f/classv8_1_1_object_template.html#a21edabb159db29683a37ea2eef37f20c

**Comment by svaarala** [comment]
There's no mechanism to capture all property operations to a getter/setter. You can share a setter/getter function by registering the same function multiple times; the getter/setter function gets a non-standard key name argument which allows the getter/setter to do different things for different property names.

The Ecmascript way of capturing all property writes is the Proxy object. See http://wiki.duktape.org/HowtoVirtualProperties.html.

**Comment by rajubngr** [comment]
Thing is that ,as I said properties are added/queried dynamically(not predefined properties) , so I can't register getter/setter functions, as I'm not aware of the properties . 
Proxy object will not fulfil my requirement .  As the properties should be queried and added on target object .  
I will provide library kind of namespace objects using duktape c and those objects are used by end developers to create instance objects and they will add/query dynamic properties on the instance object . So proxy object will not fulfill my requirement .

ex:  Through duktape c I will register below namespace object 
      ` duk_push_global_object(ctx); `   
` duk_push_c _function(ctx, constructor,DUK_VARARGS);`
`duk_put_prop_string(ctx,-2,"ui");
`
`duk_ret_t constructor(duk_context *ctx) {
    printf("constructor is called \n");
   return 0;
}    
`

I will expose above created "ui"  object as library function . 
From Ecmascript code : other developers will do like below 
   `var uiObject = new ui(...) ;
 uiObject.key1 = 20 ;  `// key1 is dynamic property , I expect common setter to be called .
` uiObject.key1 ;   `    // key1 is dynamic property , I expect common getter to be called .

**Comment by rajubngr** [comment]
I tried the below code w.r.t my example code but Proxy handler getter and setter are not getting called .
Duktape c code : 
`duk_push_global_object(ctx);`
`duk_push_c _function(ctx, constructor,DUK_VARARGS);`
`duk_put_prop_string(ctx,-2,"ui");`


 `duk_ret_t constructor(duk_context *ctx) { `
` duk_push_this(ctx);`
`  duk_push_object(ctx);  ` // handler 
    `duk_push_c_function(ctx, getter, 3); ` // 'get' trap 
  `  duk_put_prop_string(ctx, -2, "get");`
    `duk_push_c_function(ctx, setter, 4);  `// 'set' trap 
   ` duk_put_prop_string(ctx, -2, "set");`
  ` duk_push_proxy(ctx, 0); ` // [ target handler ] -> [ proxy ] 
    ` return 0;`
` }`
`
static duk_ret_t getter(duk_context *ctx)
{
    printf("getter is called \n") ;
     return 0;
}`

`static duk_ret_t setter(duk_context *ctx)
{
    printf("setter is called ");
     return 0;
}`
=======================================
Ecmascript code : 
 `var uiObject = new ui(...) ;`
 `uiObject.key1 = 20 ;  `
` uiObject.key1 ;   `   

When I evaluate above Ecmascript code , my getter and setter is not getting called  . Is that the right way yo access the object properties when wrapping in proxy object ?  . 
My requirement is executing above Ecmascript code , should call setter/getter method .

**Comment by fatcerberus** [comment]
You should return 1 from the Duktape/C constructor, not 0.  0 means you want the default return value (which for a constructor is the default instance Ecmascript creates for you).

**Comment by rajubngr** [comment]
When I return 1  it works but methods defined on target object prototype are not getting called . As returning 1 from the constructor method returns proxy object 
ex:
`var proxy = new Proxy(target, handler);`
`proxy.key1 = 321;`

if the target object has methods defined on its prototype , those methods are not getting called .
 (target.prototype.method1(flag) ;) 
`proxy.method1(flag)` // does not call the target object method ,which is expected since Proxy object does not have that method . 
My actual requirement is whenever methods are accessed on the target object , its corresponding method should be called and when dynamic/static properties are accessed common getter/setter should be called . I think, if the target object is wrapped inside Proxy object , we can't access target object method . Is there any other way to do that ?

**Comment by fatcerberus** [comment]
A method call is just a normal property read followed by calling the resulting value as a function (with `this` being whatever is on the left of the dot).  So if you want that method call to succeed, you need your getter (which has access to the target object) to return the correct function when `proxy.method` is accessed.

**Comment by rajubngr** [comment]
ok , thanks
