### ISSUE TITLE
How to achieve Inheritance using Duktape c 

### ISSUE THREAD

**Issue by rajubngr** [svaarala/duktape#1818]
How to achieve below ecmascript code equivalent using duktape c .

//SuperType constructor function
function SuperType(){
	this.name = "Virat"
}

//SuperType prototype
SuperType.prototype.getSuperName = function(){
	return this.name
}

//SubType prototype function
function SubType(){
	this.age = 26
}

//Inherit the properties from SuperType
SubType.prototype = new SuperType();  

//Add new property to SubType prototype
SubType.prototype.getSubAge = function(){
	return this.age;
}

I struck at implementing duktape code of statement `SubType.prototype = new SuperType(); `. 
How to assign the object returned from `new SuperType();` as prototype property to SubType. 

Tried below thing but getting empty return object when new SuperType() equivalent is applied using duktape c .    
     
 // SuperType duktape c function .
  `  duk_ret_t SuperTypeConstructor(duk_context *ctx) `
    {
      ` duk_push_this(ctx); `
      `duk_push_string(ctx,"Virat");`
     `duk_put_prop_string(ctx,-2,"name");`
     `  return 1 ;`
  }
  // SubType duktape c function .
  ` duk_ret_t SubTypeConstructor(duk_context *ctx) `
    {
       `duk_get_global_string(ctx, "SuperType");`
        `duk_push_this(ctx);`
        `duk_call_method(ctx, 0);`
       ` duk_pop(ctx);`
    ` duk_push_this(ctx); `
      `duk_push_number(ctx,26);`
     `duk_put_prop_string(ctx,-2,"age");`
      ` return 1 ;`
  }

 `duk_push_c_function(ctx, SuperTypeConstructor, DUK_VARARGS);`
  ` duk_push_object(ctx);` // prototype object
    `duk_push_c_function(ctx,method,1);`  // defined method as duktape c function .
    ` duk_put_prop_string(ctx,-2,"getSuperName");`
     `duk_put_prop_string(ctx,-2,"prototype");`
   `duk_put_global_string(ctx,-2,"SuperType");`
    
   `duk_push_c_function(ctx, SubTypeConstructor, DUK_VARARGS);`   // SubType object 
    `duk_get_global_string(ctx, "SuperType");`
    `duk_new(ctx,0);`
    ` duk_put_prop_string(ctx,-2,"prototype");`

**Comment by wenq1** [comment]
if you printf("result is object: %d\n", (int) duk_is_object(ctx, -1)); after duk_new ()
what's the result?

**Comment by wenq1** [comment]
Or, evil enough to use eval:

duk_eval_string(ctx, "Object.create");
duk_push_object(ctx);  /* build your prototype */
duk_call(ctx, 1 /*nargs*/);  /* = Object.create(proto) */
/* object is on stack top */

**Comment by svaarala** [comment]
>  How to assign the object returned from new SuperType(); as prototype property to SubType.

Something like:

```c
duk_get_global_string(ctx, "SubType");
duk_get_global_string(ctx, "SuperType");
duk_new(ctx, 0);  /* Stack here: [ SubType instance ] */
duk_put_prop_string(ctx, -2, "prototype");
duk_pop(ctx);  /* pop 'SubType' */
```

**Comment by svaarala** [comment]
@wenq1 Any updates or ready to close?
