### ISSUE TITLE
Not getting key argument in setter and getter functions which are implemented in duktape c . 

### ISSUE THREAD

**Issue by rajubngr** [svaarala/duktape#1819]
Trying to implement below Ecma script code (non standard )setter and getter but not getting key in setter function and getter function as arguments for duktape c function .

var obj = {};
function myGetter(key) {
    // 'this' binding is the target object, 'key' is a non-standard argument
}
function mySetter(val, key) {
    // 'this' binding is the target object, 'key' is a non-standard argument
}
Object.defineProperties(obj, {
    // Same getter/setter can be used here
    key1: { enumerable: true, configurable: true, get: myGetter, set: mySetter },
    key2: { enumerable: true, configurable: true, get: myGetter, set: mySetter },
    key3: { enumerable: true, configurable: true, get: myGetter, set: mySetter }
    // ...
});

Can we really get "key" in setter function and getter function when those functions are  implemented using duktape c functions ? 

Regards
Raju

**Comment by rajubngr** [comment]
Sorry I did mistake while declaring arguments for setter and getter c functions ,I corrected them  2 take 2 arguments for setter function and 1 argument for getter function after that I'm getting the key as argument in setter and getter function.  This ticket can be closed .

**Comment by svaarala** [comment]
@rajubngr That's the typical issue, nargs being wrong for the Duktape/C function and thus arguments seemingly being absent. Good that it worked out.
