### ISSUE TITLE
`instanceof` on Proxy object doesn't work

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#182]
My understanding of Proxy objects is that they're supposed to pass any operations without a trap through to the original object.  However, this doesn't work:

```javascript
var obj = new MyObject();
var proxy = new Proxy(obj, {});
print(proxy instanceof MyObject); // false
```

Is this a bug, or intended?  Background: minisphere has a ByteArray object as part of its API, used for reading raw data from files and sockets and such.  Since Duktape doesn't have TypedArrays or ArrayBuffers, I'm using a Proxy object to catch array accesses so that I can redirect the values into an underlying buffer.  However, because of the above behavior, this breaks `instanceof` for ByteArray objects.

Related issue: Applying `instanceof` against the Proxy constructor results in an `unexpected type` error being thrown.

**Comment by sva-p** [comment]
The current Proxy is a subset of ES6, here's the list of implemented traps:

- http://duktape.org/guide.html#es6-proxy

Prototype handling is not yet implemented.

**Comment by fatcerberus** [comment]
Ah, thanks.  I tried a workaround where I manually changed the prototype on the Proxy to the base object, but that caused a segfault.

For what it's worth I think Proxy is one of the best things about ES6, it's like Lua metatables but much cleaner.

**Comment by svaarala** [comment]
Could you paste the segfault-causing code - that's not supposed to happen :)

**Comment by fatcerberus** [comment]
Sure. :)  I investigated the issue some more and discovered the segfault in my case was due to a double free--the finalizer ran twice.  I was going to post a nice chunk of C-side stack juggling here, but luckily you can reproduce it in JS:

```javascript
(function() {
	var pig = {};
	Duktape.fin(pig, function() { print("The pig just got eaten by a cow!"); });
	var cow = new Proxy(pig, {});
	Object.setPrototypeOf(cow, pig);
})();
Duktape.gc();
```

It will print "The pig just got eaten by a cow!" twice, indicating double finalization.

**Comment by svaarala** [comment]
There is currently no guarantee that a finalizer won't run multiple times and there are indeed a few corner cases where that happen.

**Comment by fatcerberus** [comment]
I know that; I remember reading that in another issue.  The thing is, I'm wondering if it's an actual bug in this particular case, specifically related to prototype inheritance and finalizers.  Since I've set the prototype of `cow` (which has no finalizer) to `pig` (which does), is it possible that the finalizer is inherited through the prototype chain too?  Thus it runs once when `pig` is collected and again when `cow` is collected, which would be a legit bug.

**Comment by svaarala** [comment]
Finalizer is indeed inherited and on purpose so that the finalizer property doesn't need to be duplicate for every object instance. The downside of this is that it also runs for the prototype (as well as the instances).

**Comment by svaarala** [comment]
In this case the Duktape.fin() you initialize should be called for both cow and pig: the finalizer gets an argument (the object being finalized) that you can check to see if that's the case.

**Comment by fatcerberus** [comment]
```javascript
(function() {
	var cow = { name: "cow", food: "kitties" }, pig = { name: "pig", food: "cow" };
	Duktape.fin(pig, function(obj) { print("The " + obj.name + " just ate the " + obj.food + "!"); });
	Object.setPrototypeOf(cow, pig);
})();
Duktape.gc();
```

Output:
```
The cow just ate the kitties!
The pig just ate the cow!
```

Holy crap, that's awesome!  Don't change that; I had no clue finalizers could be inherited, that changes everything.  Currently I have a hack where I store the finalizer function in a hidden property of the prototype ("\xff" "dtor") to be set when each object is created, but now that I know this, I actually just have to set it once--on the prototype.  I take it back; it's not a bug, it's a feature! :smile:

**Comment by svaarala** [comment]
:smile: For most use cases inheriting the _Finalizer property is useful but there are some where it may be an issue. Perhaps there should be a non-inheritable _Finalizer variant; shrug. OTOH you can just define an empty _Finalizer (in fact any non-function value will be silently ignored and will prevent inheritance) if you don't want inheritance.

Anyway, the current behavior is part of the v1.x compatibility promise so it won't change in 1.x at least.

**Comment by svaarala** [comment]
Basic prototype which adds Proxy support to 'instanceof' without supporting `getPrototypeOf` trap:

- https://github.com/svaarala/duktape/compare/proxy-instanceof?expand=1

**Comment by fatcerberus** [comment]
So in other words, with this it will forward the instanceof test to the Proxy'd object?  That's useful, this way I won't have to evilly replace the prototype on the Proxy object anymore.

**Comment by svaarala** [comment]
Yes, that's the ES6 behavior. Or more precisely, the instanceof algorithm should use `[[GetPrototypeOf]]` which for a Proxy should check for `getPrototypeOf` trap and fall back to the target object if the trap is not implemented.

The diff in this branch falls back to the target object without checking for `getPrototypeOf` trap which is not yet supported. So it's a subset of the ES6 behavior.

**Comment by svaarala** [comment]
@fatcerberus The original code in the issue description now prints, so at least that case works :-)

```
((o) Duktape 1.2.99 (v1.2.0-178-ge463e23)
duk> function MyObject() {}
= undefined
duk> var obj = new MyObject(); var proxy = new Proxy(obj, {}); print(proxy instanceof MyObject);
true
```

**Comment by fatcerberus** [comment]
Nice, thanks. :smile:  I can't wait for 1.3!

**Comment by svaarala** [comment]
Merged the Proxy `instanceof` support to master.

The best change would actually be to replace every `DUK_HOBJECT_GET_PROTOTYPE()` with a call to a helper that either read the prototype pointer directly, or resolved a Proxy target before doing that, so that Proxy behavior w.r.t. prototypes would be fixed everywhere. This is not ideal though because the lookups will become slower.

Another approach would be to copy the target object's internal prototype to the Proxy internal prototype field, so that prototype traversal would automatically flow into the target. This would work correctly as long as internal prototypes are left unchanged. But, there's nothing stopping a user from modifying the Proxy target's internal prototype -- and this change would then need to be reflected in the Proxy object too. Since there's no "backpointer" from the target to the Proxy (or any number of Proxy objects), there's no realistic way of doing this.

**Comment by svaarala** [comment]
I'll close this now - the support is not complete as `getPrototypeOf` is not supported, but that will be covered by the ES6 Proxy gap analysis step anyway.

**Comment by fatcerberus** [comment]
I know this is closed already, but regarding slower lookups: If the performance hit is only for Proxy objects, I'd be okay with it.  You have to expect adding an extra level of indirection will slow things down.

**Comment by svaarala** [comment]
It affects all objects because the check is "Is this a Proxy object? If so, do X, else do Y".
