### ISSUE TITLE
Embedding utf-8 encoded JS code in the binary

### ISSUE THREAD

**Issue by saghul** [svaarala/duktape#1820]
Hey there!

In sjs I embed some ES6 polyfill, which contains some unicode (in a comment or something). The file is utf-8 encoded, and I'm currently using this script to generate a C header file I can add to the project: https://github.com/saghul/sjs/blob/master/tools/gencode.py

Then I evaluate it using duk_eval_string_noresult: https://github.com/saghul/sjs/blob/master/src/vm.c#L170

Now, given the source it not ascii, I'm using a uint8_t array to represent it, which I then need to cast to char*, which is what duk_eval_string_noresult takes. It's working, but, am I doing this right? Or should I do this differently?

Thanks!

**Comment by svaarala** [comment]
@saghul That should work fine, the pointer type doesn't really matter as long as the underlying data is in UTF-8 (or CESU-8).

**Comment by saghul** [comment]
Thanks for confirming @svaarala! I was concerned about the casting. Closing this then!
