### ISSUE TITLE
apply trap

### ISSUE THREAD

**Issue by dug9** [svaarala/duktape#1824]
I think I need the apply trap.
I have a get/set traps working on a global object. But users want to name a/some (global) functions the same as an/some global objects.
The get trap works when the function is called. But in the get trap I have no hint whether they are asking for the get/set object or the func object. So I have no idea what to return.
My understanding: the apply trap would help. Then  "oh - ok then you want to call it do you - in that case I'll call the function object for you"
But 2015 saavarla:
https://github.com/svaarala/duktape/issues/221
"Function calls are caught by the apply trap which Duktape doesn't yet implement."
(I think) I need it.

**Comment by svaarala** [comment]
Duktape 2.2.0 added support for 'call' and 'apply' traps.
