### ISSUE TITLE
Function declaration with prototype

### ISSUE THREAD

**Issue by zhangmw** [svaarala/duktape#1829]
Hi, I tried to allow duktape to parse function declaration likes below:

> var a = "456".abc();
>
> function String.prototype.abc()
> {
>     return '123';
> }

Currently, above code will cause an syntax error in duktape. I found the problem happens after this:
>		/* Function name is an Identifier (not IdentifierName), but we get
>		 * the raw name (not recognizing keywords) here and perform the name
>		 * checks only after pass 1.
>		 */
>		if (tok->t_nores == DUK_TOK_IDENTIFIER) {
>			duk_push_hstring(thr, tok->str1);       /* keep in valstack */
>			comp_ctx->curr_func.h_name = duk_known_hstring(thr, -1);
The symbol after the IDENTIFIER is a PERIOD instead of LPAREN, and then following code throw a syntax error.
>duk__advance_expect(comp_ctx, DUK_TOK_LPAREN);

So where shall I start to solve this issue?

**Comment by fatcerberus** [comment]
Your example is not legal Ecmascript syntax.  Duktape’s behavior here is correct.

Proper syntax would be:
```js
String.prototype.abc = function ()
{
    return ‘123’;
};
```

**Comment by zhangmw** [comment]
Thanks fatcerberus. What if I want to build a local version and support this syntax? Where shall I start the changes?

**Comment by svaarala** [comment]
The changes would need to go into duk_js_compiler.c. It would be relatively difficult work because the compiler has been hand crafted for the ES5.1 syntax and doesn't have an abstract syntax tree or other intermediate representation: tokens are parsed and bytecode is emitted on-the-fly.

May I ask why you would want to introduce non-standard syntax for this case?

**Comment by zhangmw** [comment]
OK. Got it. I was working on a project which trying to handling JS files from the wild as many as possible. I saw some collected scripts using this kind of syntax and I want to support them.

**Comment by svaarala** [comment]
Interesting, do you know which engines parsed these? I don't think at least modern engines support the syntax.

**Comment by fatcerberus** [comment]
I don't recall ever encountering an engine which supported that syntax.  It's something of a challenge semantically because normally function declarations are hoisted, but hoisting is completely nonsensical here.  It isn't clear to me what an engine could even do with such a definition.

**Comment by svaarala** [comment]
If it happens at the program level it would be a FunctionDeclaration and the semantics are more clear: it would register a global function name but support dotted syntax to locate the place to write the function reference.

**Comment by zhangmw** [comment]
Hi svaarala, this syntax is supported within ".hta" files.

**Comment by chinmaydd** [comment]
Hi @svaarala, even I am performing some experiments for supporting this syntax (seen in JScript for Windows). Could you give some more pointers as to how to implement it? Thanks.
