### ISSUE TITLE
global object

### ISSUE THREAD

**Issue by wenq1** [svaarala/duktape#1832]
When using global object in code, exception is thrown: identifier 'global' undefined. Is this normal?

Code sample:
````
    try {
        global.abc = 'test';
    }
    catch (err) {
        console.log (err.message);
    }

````

**Comment by fatcerberus** [comment]
`global` is not Ecmascript standard (yet, at least), so you'd have to define it yourself, either in the host (your application) or directly in JS as a global variable.

**Comment by svaarala** [comment]
Yes, there's no standard `global` binding in Ecmascript. There was a proposal to introduce but it got pulled back due to compatibility issues. Duktape supports that (now revoked) standard if you define `DUK_USE_GLOBAL_BINDING` for configure.py but it's not enabled by default (and may go away if the binding never gets standardized).

The easiest polyfill is:
```
if (typeof global !== 'object') {
    global = new Function('return this')();
}
```

This works by creating a function and calling it. The function is "non-strict" which means its `this` binding will be the global object regardless of the strictness of the surroundings.

**Comment by wenq1** [comment]
Wow! lightening speed! I'm fully impressed!

**Comment by wenq1** [comment]
Thanks anyway, I've found out about it also. I'm doing some experiments porting Weex (https://weex.apache.org/guide/) to duktape. Weex is similar to ReactNative in its architecture, where View logics are written in JS and then rendered using native (in Java terms, not in C terms) components.

Upon entry, there's a huge ES5 main.js to be evaluated. The beginning of this file looks like this, which clarifies this question.
````
    var global = this,
````

**Comment by wenq1** [comment]
Another question. I'm using  duk_eval_string () for the aforementioned script. Is there anyway I can tell whether the script has been evaluated without exception?

**Comment by fatcerberus** [comment]
The only JS environments I know of where `global` is provided as a standard binding are my own (miniSphere) and Node.js.  Anywhere else you definitely need to polyfill it.

**Comment by fatcerberus** [comment]
> Another question. I'm using duk_eval_string () for the aforementioned script. Is there anyway I can tell whether the script has been evaluated without exception?

For this, look into `duk_peval_string()`.  If an error is thrown, the function returns -1 and the error object is left on top of the value stack.

**Comment by wenq1** [comment]
Thx. I'll give it a go.

**Comment by fatcerberus** [comment]
@svaarala How heavily are the "protected" variant calls emphasized in the Guide?  It seems like people just getting started tend to overlook them.

**Comment by svaarala** [comment]
They are part of the Programming Model section which is "expected reading", http://duktape.org/guide.html#error-handling.

**Comment by wenq1** [comment]
It is just my laziness even though having been fiddling around duktape for half a year. We do not tend to peval () on our own scripts as they're usually linted and duktape-ed on host machine prior to deployment. Working with third-party scripts is quite different though ...

**Comment by fatcerberus** [comment]
@wenq1 Just so you're aware, if there is no protected catch point *at all*, any error thrown will be fatal and crash your process.  It's not a silent failure like what you'd usually expect in C.

**Comment by wenq1** [comment]
@fatcerberus Thanks for pointing that out

**Comment by wenq1** [comment]
Currently we use duk_call () and all entries into JS will have a try-catch block. Is this a more recommended apporach towards duk_pcall ()?

the catch () block will report error back to our server (logic also written in JS) in our use case.

**Comment by svaarala** [comment]
@wenq1 That will work fine for 99.99% cases - but if anything throws in the catch clause it may propagate outwards and cause an uncaught error, leading to the fatal error handler being called. The default handler will `abort()` but you can replace that behavior during heap creation.

Ultimately it's up to the application in my view. For some applications it's OK to simply provide a fatal error handler that will log the error (and perhaps send it to some server immediately or on the next startup). This is workable when the scripts are all controlled and part of the application build. When running more dynamically loaded scripts, this is usually much less workable as you noticed.
