### ISSUE TITLE
Revisiting promise API implementation options

### ISSUE THREAD

**Issue by wenq1** [svaarala/duktape#1833]
Usually eventloop-aware functions are not the responsibities of Javascript engines. This holds true for setTimeout () and friends, but  the new kid in town - Promise seems eager to push the boundaries.

I'm aware that @fatcerberus and @svaarala has already attempted (and aborted) to address the implementation, and I'm just write up some of my thoughts based on hands-on utility case. Since the two are far more intellectually capable and authrorative on this topic than myself, feel free to correct me if I'm wrong.

1. Implement this the JerryScript way.

JerryScript has got jerry_run_all_enqueued_jobs () function. This means Jerry has already got a jobqueue implememeted in the engine. This model works great with custom eventloop but presents difficulties to other event libraries.

For example, a custom eventloop would do as follows:

````
eventloop_run () {
    for (;;) {
        expire_timers ();
        jerry_run_all_enqueued_jobs ();
        
        timeout = next_deadline ? next_deadline - now : -1;
        xpoll (fds, nfds, timeout);
    }
}

// in Javascript,
// new Promise ().then () adds a job into the jerry_jobqueue
// setTimeout () adds a new timer into a timer objects (custom C linked-list implementation implementation for example)
````

However, a eventloop library (such as libev) works without the for (;;) loop will have some problems:

````
libev_eventloop_run () {
    ev_io_init (&lev_watcher, lev_socket_cb, socket_fd, EV_READ);
    ev_io_start (lev_loop, &lev_watcher);

    // where to 
    ev_run (lev_loop, 0);
}

// In Javascript,
// new Promise ().then () adds a job into the jerry_jobqueue
// setTimeout () adds a new timer into a timer objects implemented in libev by calling ev_timer_init () and ev_timer_start ()

````

In the production-quality libev setup, there will be nowhere to place jerry_run_all_enqueued_jobs () easily as it does not expose callbacks prior- and post- each iteration. Although one might argue and use ev_prepare () and ev_idle () to mitigate the issue, the former being dependent on a fd and the uncontrolled timing of the latter makes it difficult to standardise the behaviour.

2. Proposed implementation

The problem with the jerry_run_all_enqueued_jobs () API above is its assumption of a custom-eventloop. Jerry puts jobs into queue when the 'thennable' is called and leaves it to the eventloop to dequeue all jobs later. What about use callback setup and make duktape's Promise implementaiton eventloop-independent?

Example below with custom eventloop

````

void customqueue_runall (q) {
    while (jobid = customqueue_dequeue (q) {
            duk_run_promise_job (jobid)
    }
}

duk_ret_t duk_promise_cb (duk_context_t * ctx, int jobid)
{
    customqueue_add (q, jobid);
}


void libev_eventloop_run () {
    ctx = duk_create_heap_default (duk_promise_cb);

    duk_eval_string (ctx, "new Promise(function (resolve, reject) {resolve ('Hello, World!'); }).then (function (str) { console.log (str); });" );

    for (;;) {
        expire_timers ();
        
        customqueue_runall (q);
        
        timeout = next_deadline ? next_deadline - now : -1;
        xpoll (fds, nfds, timeout);
    }
}

// In Javascript,
// new Promise ().then () adds a job into the jerry_jobqueue
// setTimeout () adds a new timer into a timer objects implemented in libev by calling ev_timer_init () and ev_timer_start ()

````

With libev:
````

void lev_promise_cb (EV_P_ ev_timer * watcher, int revents)
{
    // opaque pointer
    duk_promise_jobid_t     jobid   = watcher->data;
    duk_run_promise_job (jobid);
}

duk_ret_t duk_promise_cb (duk_context_t * ctx, int jobid)
{
    lev_promise->data   = jobid;
    ev_timer_init (&lev_promise, lev_promise_cb, 0.0, 0.0);
    ev_timer_start (lev_loop, &lev_promise);
}


void libev_eventloop_run () {
    ctx = duk_create_heap_default (duk_promise_cb);

    duk_eval_string (ctx, "new Promise(function (resolve, reject) {resolve ('Hello, World!'); }).then (function (str) { console.log (str); });" );
	
    ev_run (lev_loop, 0);
}

// In Javascript,
// new Promise ().then () adds a job into the jerry_jobqueue
// setTimeout () adds a new timer into a timer objects implemented in libev by calling ev_timer_init () and ev_timer_start ()

````

With this approach, both custom eventloop and library ones will be able to use the native promise, which does not attempt to make any assumptions on where run_all_enqueued_jobs is called. The api proposed to add is duk_run_promise_job () which takes an opaque jobid as argument.

**Comment by fatcerberus** [comment]
Personally, I like the way the JsRT (MS Chakra) does it: When a promise settles, the JavaScript calls a user-provided callback function and provides you a function object that when called executes the corresponding `.then()`.  You then call that function at your leisure from your own event loop.

**Comment by svaarala** [comment]
@wenq1 Actually I haven't aborted the implementation, I just haven't had much time to work on it recently. I do have a work branch where I'll first implement the Promise mechanics themselves with a placeholder eventloop integration, and then add a public API for the eventloop integration separately. The eventloop integration is quite minor compared to the Promise implementation itself, though it has more version compatibility impact going forward.

**Comment by svaarala** [comment]
Re: the job queue, so far my favorite has been an API where one would be able to run one job from the (internal) queue. The caller could then choose whether to run all jobs (= until the queue is empty) or e.g. one job per a certain time slice (say a frame of a game). 

In ES2015 Promises are not the only job type, so the API should allow multiple job types to run. User code should also ideally be able to push jobs on the queue, e.g. for fired timers (the firing itself would be outside the scope of the mechanism).

**Comment by wenq1** [comment]
Sounds very cool. I'm looking forward to it. 

Currently I've integrated preact to our SDK, which uses Promises and fallbacks to setTimeout () when necessary. The result is a fully functional ReactNative-alike environment for drawing UI on Android in under 500kB of armeabi solib. (Prior experiments here https://github.com/wenq1/jsbridges)

**Comment by svaarala** [comment]
Sounds great :) In many cases an external Promises implementation is fine (I've been using Bluebird for now). But in some cases there are a lot of Promises so it becomes important to try to optimize their footprint and speed, and the native engine internals are in a good place to do that (e.g. optimizing their memory representation and such).

**Comment by fatcerberus** [comment]
Native Promises are also a prerequisite for ES2017 async/await.

**Comment by svaarala** [comment]
I guess technically it would suffice to have some integration API to an external Promises implementation in that case too. There might be some advantage in being able to switch the Promise provider easily (e.g. some providers have additional functionality). But even so there should be a native, in-engine implementation so that it can be optimized for footprint etc.

**Comment by fatcerberus** [comment]
Hmm, even with that integration layer in place, it seems like it might be difficult to make all the necessary guarantees such as:

```js
console.log(asyncFunction() instanceof Promise); // true
```

Being able to plug in other Promise implementations would be nice, I agree, but I’m not sure how it could cover all the corner cases.

**Comment by wenq1** [comment]
Note that bluebird promise shims, at its minimum, is ~56k. Other shims do exist, and most of them just call setTimeout () and friends to mock the behaviour.

**Comment by wenq1** [comment]
IMHO there's little need for an integration API for external Promises. Either people turn off duktape's native implementation and use pure JS shims or they turn the flag on.

**Comment by svaarala** [comment]
@wenq1 Right, but as @fatcerberus pointed out, some of the language features themselves are promise integrated so it isn't necessarily possible to implement everything via an external library.

But this is all pretty academic because there will be a built-in implementation. Whether there will be support for adding an external implementation is a separate, not as important issue IMO.

**Comment by wenq1** [comment]
@svaarala can you share the work branch and I might be able to find some time working on it further?

**Comment by wenq1** [comment]
Off-the-topic ... @fatcerberus is your minisphene ChakraCore engine ported to Android?

**Comment by fatcerberus** [comment]
@wenq1 It is not, but from what I understand someone is supposed to be working on that in their free time.  But yeah, that is very off-topic, if you want to talk more about miniSphere you can use the email address in my GitHub profile. :)
