### ISSUE TITLE
Buffer readInt32LE ()

### ISSUE THREAD

**Issue by wenq1** [svaarala/duktape#1834]
Is Node.js buffer prototype functions readInt32LE, readInt32BE implemented?

**Comment by svaarala** [comment]
Yes, they're implemented:

```
duk> b = new Buffer('foobar')
= {type:"Buffer",data:[102,111,111,98,97,114]}
duk> b.readInt32LE(0)
= 1651470182
duk> b.readInt32BE(0)
= 1718579042
```

**Comment by wenq1** [comment]
Thank you. We probably need a more unified place to provide docs:

http://wiki.duktape.org/HowtoBuffers2x.html
https://github.com/svaarala/duktape/blob/master/doc/buffers.rst
