### ISSUE TITLE
The members of duk_class_number_to_stridx[32] is undefined

### ISSUE THREAD

**Issue by jictannu** [svaarala/duktape#1837]
I run configure.py :
`$ python2 tools/configure.py \
      --output-directory /tmp/output \
      --dll \
      -DDUK_USE_FASTINT \
      -UDUK_USE_ES6_PROXY`
then I compile, but all the members of duk_class_number_to_stridx[32] is undefined. Why is this happening?

**Comment by svaarala** [comment]
Cannot reproduce the problem - could you paste your compilation command?

**Comment by svaarala** [comment]
Not sure if this is related, but you're configuring with `--dll` but Makefile.hello doesn't compile a DLL. What happens if you remove the `--dll` option?

**Comment by jictannu** [comment]
I remove the --dll option, but it  makes no difference.

**Comment by svaarala** [comment]
Hmm, I'm not sure what could go wrong - I can't replicate the problem so it's difficult to say. Does the src/ directory directly from the distributable work fine? Any chance generated sources and headers could be from different directories?

**Comment by jictannu** [comment]
in `duktape.c`:
`/* Note: assumes that these string indexes are 8-bit, genstrings.py must ensure that */
DUK_INTERNAL duk_uint8_t duk_class_number_to_stridx[32] = {`
but I can not find `genstrings.py`

**Comment by svaarala** [comment]
You don't need to run genstrings.py manually. It resides in tools/ and is automatically invoked by configure.py, which is the only configuration script you should need.

**Comment by jictannu** [comment]
The preconfigured sources work fine. I would like to how it configure.

**Comment by svaarala** [comment]
It's basically:
```
$ python tools/configure.py --output-directory src
```

In other words, no options changed from defaults.

**Comment by svaarala** [comment]
@jictannu Any updates on this issue?
