### ISSUE TITLE
Shouldn't `#include <exception>` when using duktape in C++ with exceptions disabled

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#1838]
As in the title, if `DUK_USE_CPP_EXCEPTIONS` weren't defined (which is the default), `duktape.c` doesn't use `std::exception` at all. However, `duk_config.h` includes `<exception>` regardless (as long as C++ is detected). When one uses C++ with exceptions disabled, this is bad practice in general and could produce a warning.

**Comment by svaarala** [comment]
Thanks, I'll fix the include to be conditional.
