### ISSUE TITLE
Duktape is slow when parsing/evaling large file(s)

### ISSUE THREAD

**Issue by stevefan1999** [svaarala/duktape#1842]
Try parsing a 400kb embedded file. It took me 30s to get the result. Do keep it in mind that it is a CommonJS module packed by Browserify and I also had duk_module to make it happen. I wonder what more optimizations can I do?

**Comment by svaarala** [comment]
Could you link to an example file (maybe there's something specific causing the slowdown)? Certainly 30 seconds is way more than expected. For comparison:
- moment.js is 126kB and parses in 0.06 seconds on this laptop.
- Emscripten-compiled Duktape is 1.6MB and parses in 0.7 seconds on this laptop.

**Comment by svaarala** [comment]
On this laptop the file is parsed and eval'ed in 0.14 seconds:

```
$ time duk problem.js 

real	0m0,137s
user	0m0,128s
sys	0m0,008s
```

So, I'm not sure why this would be different for you. Could you try eval'ing the file using the 'duk' command line utility in your setup?

Btw, note that Duktape, and any other interpreting engine, will typically be 30-100x slower than Node.js which uses a JIT.

**Comment by stevefan1999** [comment]
I did nothing and all of a sudden the runtime decreased to 4 seconds. WTF?! Closing this as a mystery.

**Comment by svaarala** [comment]
The difference between duk_compile_lstring_filename() and duk_peval_lstring() shouldn't affect the runtime in a measurable fashion. But good that this worked out somehow - though 4 seconds still sounds quite a lot compared to the ~0.14 seconds on this laptop.
