### ISSUE TITLE
assertion failed: DUK_HEAPHDR_GET_REFCOUNT(duk__h) > 0  in duk_hobject_refcount_finalize_norz

### ISSUE THREAD

**Issue by renatahodovan** [svaarala/duktape#1845]
###### Duk version:

```
Checked revision: 4ba1c99c
Build command: make dukd
```
###### OS:

```
Ubuntu 17.10, x86_64
```
###### Test case:

```javascript
Duktape.Thread.resume(Duktape.Thread(function() {}))
```

###### Backtrace:

```
*** FATAL ERROR: assertion failed: DUK_HEAPHDR_GET_REFCOUNT(duk__h) > 0 (duk_heap_refcount.c:85)
t
Program received signal SIGSEGV, Segmentation fault.
0x0000555555559025 in duk_default_fatal_handler (
    msg=msg@entry=0x55555593b140 "assertion failed: DUK_HEAPHDR_GET_REFCOUNT(duk__h) > 0 (duk_heap_refcount.c:85)", udata=0x0)
    at duk_error_macros.c:119
119	duk_error_macros.c: No such file or directory.
(gdb) bt
#0  0x0000555555559025 in duk_default_fatal_handler (
    msg=msg@entry=0x55555593b140 "assertion failed: DUK_HEAPHDR_GET_REFCOUNT(duk__h) > 0 (duk_heap_refcount.c:85)", udata=0x0)
    at duk_error_macros.c:119
#1  0x0000555555675e40 in duk_hobject_refcount_finalize_norz (heap=<optimized out>, h=0x555555c26a10) at duk_heap_refcount.c:85
#2  0x0000555555662daf in duk__refcount_free_pending (heap=<optimized out>) at duk_heap_refcount.c:316
#3  duk__refcount_refzero_hobject (heap=0x555555c03ed0, obj=<optimized out>, skip_free_pending=1) at duk_heap_refcount.c:416
#4  0x0000555555802f41 in duk_hthread_activation_unwind_norz (thr=0x555555c284e0) at duk_hthread_stacks.c:317
#5  0x0000555555843178 in duk_hthread_terminate (thr=0x555555c284e0) at duk_hthread_misc.c:11
#6  duk__handle_return (thr=thr@entry=0x555555c284e0, entry_act=entry_act@entry=0x555555c19870) at duk_js_executor.c:1652
#7  0x0000555555569dcd in duk__js_execute_bytecode_inner (entry_act=entry_act@entry=0x555555c19870, entry_thread=<optimized out>)
    at duk_js_executor.c:4500
#8  0x000055555563fd86 in duk_js_execute_bytecode (exec_thr=exec_thr@entry=0x555555c0a5b0) at duk_js_executor.c:2897
#9  0x0000555555648cd8 in duk__handle_call_raw (thr=0x555555c0a5b0, idx_func=<optimized out>, call_flags=0) at duk_js_call.c:2197
#10 0x00005555558d19e7 in wrapped_compile_execute (ctx=ctx@entry=0x555555c0a5b0, udata=udata@entry=0x0)
    at examples/cmdline/duk_cmdline.c:301
#11 0x000055555565dac6 in duk__handle_safe_call_inner (num_stack_rets=1, idx_retbase=0, entry_thread_state=1 '\001', 
    entry_curr_thread=0x0, entry_callstack_top=0, entry_valstack_bottom_byteoff=0, udata=0x0, 
    func=0x5555558d1620 <wrapped_compile_execute>, thr=0x555555c0a5b0) at duk_js_call.c:2432
#12 duk_handle_safe_call (thr=0x555555c0a5b0, func=0x5555558d1620 <wrapped_compile_execute>, udata=0x0, 
    num_stack_args=<optimized out>, num_stack_rets=1) at duk_js_call.c:2677
#13 0x00005555558d2b33 in handle_fh (ctx=0x555555c0a5b0, f=0x555555c28130, filename=0x7fffffffe15c "../test.js", 
    bytecode_filename=0x0) at examples/cmdline/duk_cmdline.c:632
#14 0x000055555555f36f in handle_file (bytecode_filename=<optimized out>, filename=0x7fffffffe15c "../test.js", ctx=0x555555c0a5b0)
    at examples/cmdline/duk_cmdline.c:691
#15 main (argc=2, argv=0x7fffffffdd78) at examples/cmdline/duk_cmdline.c:1465
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

**Comment by svaarala** [comment]
Confirmed, thanks (again!) @renatahodovan.

**Comment by svaarala** [comment]
Labeled 'security' because causes a segfault with assertions disabled.

**Comment by fatcerberus** [comment]
Curious why this segfaults, is it because the `Thread` object goes out of scope and gets GC’d?

**Comment by wenq1** [comment]
cool method. Is it like american loop test?

**Comment by renatahodovan** [comment]
@wenq1 if the question is targeted at me, then: the bug was found, minimized, and reported by a fuzzing framework called Fuzzinator, running one of my own fuzzers.

**Comment by wenq1** [comment]
@renatahodovan yes it is an interesting tool. I was referring to AFL (http://lcamtuf.coredump.cx/afl/) which I came across recently. Fuzzinator seems to be a similar tool?

**Comment by wenq1** [comment]
How did you (semi-)randomly choose what to test? I.e. why was "Duktape.Thread.resume(Duktape.Thread(function() {}))" chosen?

**Comment by renatahodovan** [comment]
@wenq1 Fuzzinator is a framework that can drive fuzzing sessions with arbitrary SUTs (like Duktape) and test generators (like [grammarinator](https://github.com/renatahodovan/grammarinator)). This means that Fuzzinator runs and monitors Duktape, asks new test cases from the choosen generator and saves/reports the found issues, but the test cases are produced by the external test generators.
The generator that created the test case above is called JSProFuzz which is basically a JavaScript API fuzzer. It's not open-source yet, but you can read about it [here](http://www.inf.u-szeged.hu/~akiss/pub/pdf/hodovan2016jsapi.pdf).

AFL is different from Fuzzinator since it's a framework & generator in a single tool. Which makes it easier to use out of the box but harder to customize the generator.

**Comment by wenq1** [comment]
@renatahodovan thanks for the answer.

**Comment by svaarala** [comment]
I think I've diagnosed the cause, in short:
- When the `function () {}` returns, the newly created thread terminates. This is handled using a longjmp to the bytecode executor.
- The bytecode executor unwinds the initial thread's activation for Duktape.Thread.resume(). This activation held the only reference to the resumed thread and it gets freed (in the frame for Duktape.Thread.resume()).
- The bytecode executor then tries to finalize the thread's book-keeping, using a stale reference.

There are several ways to fix this, e.g. by ensuring that the lifetime extends to the termination or by making `heap->curr_thread` a refcounted reference. I'll open up a pull for some fix later on.
