### ISSUE TITLE
New project using Duktape

### ISSUE THREAD

**Issue by yrashk** [svaarala/duktape#1848]
SIT (https://github.com/sit-it/sit), an offline-first/file-based/merge-friendly issue tracker is using Duktape to run user-defined event records reducers, producing meaningful projections of issues.

I would also like to use this as an opportunity to thank all developers for such a great piece of software. Not to mention it's documentation. It's absolutely brilliant. Inspirational. 

Great work.

**Comment by svaarala** [comment]
Thanks @yrashk! I'll add a link to the projects page (https://github.com/svaarala/duktape-wiki/pull/196).
