### ISSUE TITLE
How to clone a EcmaScript object(what the API duk_dup() does is duplicating a reference)?

### ISSUE THREAD

**Issue by faywong** [svaarala/duktape#185]
Is there a way to clone a EcmaScript object so that the changes to the property of cloned one don't affect the original one?

I have tried the API *duk_dup*(), it works as:
BEFORE dup:
```[{"thiz": "aaa"}]```
AFTER dup:
```[{"thiz": "aaa"}, {"thiz": "aaa"}]```
AFTER changing the property "thiz" of the duplicated one to "bbb":
```[{"thiz": "bbb"}, {"thiz": "bbb"}]```
This is not my want. I expect it to be:
```[{"thiz": "aaa"}, {"thiz": "bbb"}]```

Any help or advice is highly appreciated.

BR,
fay

**Comment by svaarala** [comment]
Cloning an object is a complex issue - should cloning be shallow (clone only one level of keys) or deep (clone all recursively); what to do with object reference loops, etc. Consequently there's no clone mechanism in the language itself or the Duktape API.

You can find various suggestions on the net for cloning objects, ranging from `JSON.parse(JSON.stringify(obj))` to manually copying keys in a certain way. The JSON approach has limitations, e.g. it doesn't handle reference loops or custom types (Proxy objects, objects with native state), and is limited to a subset of the whole set of inherited properties.

**Comment by faywong** [comment]
Many thanks to your quick and clear clarify. I got it.

The issue i run across now is i have instantiated many java objects, and i map their methods and properties to ECMAScript object(all the method in the ECMAScript object is bound to a single native c method, then invoke the implements in java-side through the native c method). As the java objects are of same *class*. So i want to only clone the corresponding ECMAScript object that has been bound and change its "thiz" property to the address of the java object so as to decrease the effort of *binding*.

Is there an easy way to achieve similar effect?

**Comment by faywong** [comment]
I found that maybe the API **duk_set_prototype** is the right way to achieve my goal.
