### ISSUE TITLE
List of functions

### ISSUE THREAD

**Issue by maxime-ohm-georges** [svaarala/duktape#1850]
Hello,
I would like to get "AST" of peace of javascript called by using duktape.

I tried "esprima" but the generated AST is not useful because I am developing in C and would like to call javascript functions using duktape API.

Is there a way to do that ?

Thank you in advance

**Comment by svaarala** [comment]
Could you clarify a bit what you want to do with the AST?

Regarding AST access, Duktape doesn't expose an AST for parsed code (and in fact doesn't build a full AST to minimize memory usage during compilation). So you would need to use an external C or Javascript library to parse the source code.

**Comment by maxime-ohm-georges** [comment]
Thank you for the quick reply.

In fact, I would like to extract all entries from a piece of javascript code and launch test on each entries by modifying parameters.

To do that, I use duktape to run js code.
But now, I have to extract functions and parameters to check/test script.

After reading a bit of docs, the best way is to use an AST and explore it but I don't know how to do that in C...

**Comment by mmorrison24** [comment]
I would still use esprima, you can then use a json loader to turn the output into something you can iterate over with c++. 

Here is a gist of a similar project I am working on - https://gist.github.com/mmorrison24/696676b89a707975b2f2afc292595e77

**Comment by svaarala** [comment]
I'll close this now - please reopen if something is still unanswered.
