### ISSUE TITLE
How to work with JavaScript Date in C++

### ISSUE THREAD

**Issue by jcmerlin** [svaarala/duktape#1852]
I am using duktape to implement some JavaScript calls in C++:

I have a script that is something like this:

`myFunction(new Date(););`

My question is, how do I declare `myFunction` so that I can access the time information in that date parameter (in `double` format, for example)?

All the JS/C examples I see are about strings and numbers, but I haven't seen anything dealing with dates.

Thanks,

**Comment by svaarala** [comment]
The simplest thing would probably be to do the equivalent of:

```javascript
function myFunction(x) {
    var t = x.valueOf();  // time in milliseconds
    // ...
}
```

In C one would do something like:

```c
duk_ret_t myFunction(duk_context *ctx) {
    /* Index 0: argument Date */
    duk_push_string(ctx, "valueOf");
    duk_call_prop(ctx, 0 /*Date instance*/, 0 /*nargs*/);
    /* Stack here: [ ... time ] */
    double t = (double) duk_get_number(ctx, -1);
    /* ... */
}
```

**Comment by svaarala** [comment]
@jcmerlin Was this question resolved from your point of view?
