### ISSUE TITLE
Duktape interruption and SIGPIPE

### ISSUE THREAD

**Issue by vikrem** [svaarala/duktape#1853]
Hello,

I'm trying to write Duktape bindings from a higher level language (Haskell).
I'm trying to add the ability to terminate long-running Duktape evaluations from Haskell.
Haskell cannot interrupt executing C. The best it can do is throw a SIGPIPE at the pthread running the C, and hope that causes the C functions to return control back to Haskell.

C syscalls have this behaviour (sleep(), read(), etc will return with EINTR if SIGPIPE is raised), but Duktape does not.

I've tried implementing a signal handler that will `setcontext`/`getcontext`-wrap Duktape calls.
It seems to work, but with some amount of non-determinism -- assuming I've implemented it correctly.

Is there a smarter way that I could implement this feature?

**Comment by svaarala** [comment]
If Duktape is executing calls into Duktape/C functions (the native bindings you provide), then the interruption mechanism would need to be able to interrupt each native operation in a case specific manner. Some cases cannot be handled, e.g. if a native call goes into an infinite loop.

For Ecmascript code, there's a very barebones macro-based execution timeout mechanism (DUK_USE_EXEC_TIMEOUT_CHECK), see https://github.com/svaarala/duktape/blob/master/doc/sandboxing.rst#bytecode-execution-timeout-details. There's a simple example in https://github.com/svaarala/duktape/blob/master/examples/cmdline/duk_cmdline_lowmem.c#L972-L1012.

**Comment by vikrem** [comment]
Thanks for your reply!

> If Duktape is executing calls into Duktape/C functions (the native bindings you provide), then the interruption mechanism would need to be able to interrupt each native operation in a case specific manner. Some cases cannot be handled, e.g. if a native call goes into an infinite loop.

So what you mean is: If Duktape makes a native call to a function provided by the bindings, that, say, loops forever or makes a blocking call or whatever it likes, forcefully terminating this function is beyond Duktape's runtime control.

This makes sense. I'll let that be my problem, not Duktape's.

Are there performance ramifications when using DUK_USE_EXEC_TIMEOUT_CHECK?

**Comment by fatcerberus** [comment]
> So what you mean is: If Duktape makes a native call to a function provided by the bindings, that, say, loops forever or makes a blocking call or whatever it likes, forcefully terminating this function is beyond Duktape's runtime control.

Yes.  Duktape assumes the native code it's calling into is "trusted" in this regard--and in fact *has* to assume such due to how close to the metal C is in general.

**Comment by svaarala** [comment]
> Are there performance ramifications when using DUK_USE_EXEC_TIMEOUT_CHECK?

It requires the DUK_USE_INTERRUPT_COUNTER option to allow bytecode execution to be interrupted from time to time. The main performance impact comes from the maintenance of the interrupt counter which adds a few cycles to every opcode dispatch. This amounts to around 5% for the worst case where simple opcodes are executed without calling native functions (say, an empty counter-based for-loop). If the bytecode operations being iterated are heavier (say property operations) the relative impact is smaller. Practical code is also a mix of bytecode and native functions so usually the impact is maybe around 1-3%.

**Comment by svaarala** [comment]
@vikrem I'll close this now - please reopen if something is still unanswered.
