### ISSUE TITLE
How to pass additional information to modSearch

### ISSUE THREAD

**Issue by jcmerlin** [svaarala/duktape#1854]
I'm trying to implement a C function for module searching: `modSearch`.

The documentation says that I have to implement the following signature:

```
duk_ret_t my_mod_search(duk_context *ctx) {
    /* Nargs was given as 4 and we get the following stack arguments:
     *   index 0: id
     *   index 1: require
     *   index 2: exports
     *   index 3: module
     */

    /* ... */
}
```

However, inside that function I would like to access a variable that contains the paths where module searching should look. Ideally, instead of a free function, this should be a method of a C++ instance, or at least I should be able to pass along with `duk_context *ctx` a list of paths so that `my_mod_search` can operate correctly when client code evaluates `require('module');`

How can I do this?

**Comment by svaarala** [comment]
Could you provide some conceptual code of what you're trying to do in the modSearch() function? Do you want to implement the search function in C or Ecmascript?

There are various places you could store the paths:
- You can store them in the function object (the modSearch function). In Ecmascript code you can access them via the function name, and in C code using `duk_push_current_function()` and then reading properties off the object.
- You can use an Ecmascript closure (example below). This only works for an Ecmascript implementation.
- You could use a global property (works for both Ecmascript and C code) or a "stash" (accessible from C code only).
- You could store it in a native C structure.

As an example of the closure technique:
```js
function makeModSearch(pathlist) {
    return function modSearch(...) {
        // access pathlist
    }
}

Duktape.modSearch = makeModSearch([ dir1, dir2, dir3 ]);
```

**Comment by jcmerlin** [comment]
Thanks, I've used a global property for now, but I'll explore the other options.

**Comment by svaarala** [comment]
I'll close this now - please reopen if something is still unanswered.
