### ISSUE TITLE
MSVC instrumented profiling triggers Duktape assert

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#187]
I get the following assert during `duk_create_heap()` when running my engine under the MSVC profiler using the "Instrumentation" setting.

```
PANIC 54: assertion failed: (duk_double_t) (duk_uint32_t) DUK_TVAL_GET_NUMBER(tv
) == DUK_TVAL_GET_NUMBER(tv) (duk_hobject_props.c:2688) (calling abort)
```

This makes it impossible to profile my app.  It doesn't happen in a normal debug build, only when attempting to use the profiler in Instrumentation mode.

**Comment by svaarala** [comment]
Do you have `DUK_OPT_SELF_TESTS` enabled? If not, could you try that to see if any self test fails also.

**Comment by fatcerberus** [comment]
```
PANIC 52: self test failed: casting 2147483648.0 to duk_int64_t failed (calling
abort)
```

**Comment by svaarala** [comment]
This fails for some reason - no idea why:

```
        /* Catch a double-to-int64 cast issue encountered in practice. */
        d = 2147483648.0;
        i = (duk_int64_t) d;
        if (i != 0x80000000LL) {
                DUK_PANIC(DUK_ERR_INTERNAL_ERROR, "self test failed: casting 2147483648.0 to duk_int64_t failed");
        }
```

**Comment by svaarala** [comment]
I encountered this same issue on a more exotic platform but interesting to see it also happens here.

**Comment by fatcerberus** [comment]
I think this is happening to me on Windows XP also; I can't run my engine on XP because it fails during Duktape initialization.

**Comment by svaarala** [comment]
The primary fix would be to figure out why the cast is broken - i.e. what value comes out of it?

On some platforms this cast is genuinely broken; here it might be that `duk_int64_t` has been incorrectly detected, but that is unlikely because type `sizeofs()` are also self tested.

A workaround might be to disable use of 64-bit types for MSVC altogether if this turns out to be a real cast issue. There's no feature flag for that, but internally Duktape can be compiled without 64-bit integers (it disables fastints though).

**Comment by fatcerberus** [comment]
Hm, interestingly, I can't reproduce this on my 5th gen Core i3.  It runs fine in the profiler.  Well, except for one small issue: Duktape throws an error of some sort (all I get out of it is `uncaught error` so no idea what it is--and assertions ARE enabled) during heap creation on an x64 instrumentation build.  The 32-bit build I can profile fine on this laptop.

The machine that exhibits the bug is running an AMD A10-6800K.

**Comment by svaarala** [comment]
That uncaught error probably means some fundamental thing is wrong which isn't caught by self tests, so it's quite likely not something trivial that fails.

Btw, it'd be interesting to know what the result of the double-to-int64 cast is in your case, using the AMD host :)

**Comment by fatcerberus** [comment]
Interesting.  I broke into the debugger following the assert and examined the variables:
d = 2147483648.0000000
i = 0

Wow.  Just... wow.  I could understand a small discrepancy due to floating point inaccuracy, but... 0?  From 2G?  What the hell? :confused:

**Comment by svaarala** [comment]
Does the debugger show what concrete type `duk_int64_t` maps to (I think it should be `long long`)?

There are a lot of union/cast issues even in some modern compiler (versions), standard libraries, etc, unfortunately. It's highly optimized so there are sometimes weird issues. For example this clang issue is very baffling: having a `double` in union breaks byte array accesses even when it is not accessed: https://github.com/svaarala/duktape/blob/master/misc/clang_aliasing.c (and this only happens with specific versions *and* `-m32`).

BTW, with IEEE there is no floating point inaccuracy as such - every result is specified to bit exact results (except for NaN values). In particular, all integers in [0,2^53] are represented exactly. Duktape relies on exact IEEE semantics both to provide correct Ecmascript results but also internally.

**Comment by fatcerberus** [comment]
IntelliSense has this to say re: `duk_int64_t`:
`typedef signed long long duk_int64_t`

But yeah, this only happens on an instrumented build under the profiler, release builds and normal debugging sessions are fine.  Weird.  The instrumentation must be doing something odd to the cast.

**Comment by fatcerberus** [comment]
So I guess there's not much that can be done about this, then... wait, would disabling fastints while profiling help?

**Comment by svaarala** [comment]
As long as the basic self tests are not passed anything can break in a very mysterious way. Duktape does rely on exact IEEE semantics, and working double/integer casts etc. This cast test is not related to fastints as such, it's just basic sanity.

If this is somehow related to 64-bit types, one thing to try is making Duktape avoid 64-bit types even when they're technically available. As I said above there's no feature option for that right now; you'd need to manually hack duktape.c to ensure `DUK_USE_64BIT_OPS` doesn't get set (just doing `#unset DUK_USE_64BIT_OPS` at the end of feature detection should work).

Without 64-bit operations fastint support doesn't currently work so you'd need to disable fastints. Other than that 64-bit operations are used by a few algorithms here and there which will then fall back to 32-bit integers or IEEE doubles.

**Comment by svaarala** [comment]
@fatcerberus This is pretty old, but did you ever get around to testing the above (disabling 64-bit ops manually)? If there's no concrete change to be made, this should be closed.

**Comment by fatcerberus** [comment]
Hehe, I forgot all about this issue.  My main box is an i7-6700K now, so without the AMD box I may not even be able to reproduce it.  You can close I guess.
