### ISSUE TITLE
"Project using Duktape"

### ISSUE THREAD

**Issue by benjymous** [svaarala/duktape#1870]
My little project has seen its first few pre-alpha releases, so I figured it'd be good to announce it here, too:

https://grapefruitopia.itch.io/prism-384

Prism is a "fantasy console" - an imaginary late 80s-esque virtual home computer, using Duktape for its code interpreter (bar the system routines, virtually everything running on it is implemented in JS)

Very early stages, but I hope for it to be usable as a "learn to code" type environment - something you can just sit down, turn on, and start programming, without the distractions of everything a modern computer offers.

On a related note, has anyone made a "Powered by Duktape" logo?

**Comment by svaarala** [comment]
Fun project! :) I'll add a link to the projects list.

AFAIK there's no "Powered by Duktape" logo at present, but that would be a nice thing to have. The only logos now are:
1. The text symbol `((o)`
2. Some graphical logos (which were needed in a hurry) in https://github.com/svaarala/duktape/tree/master/website/logo

**Comment by svaarala** [comment]
https://github.com/svaarala/duktape-wiki/pull/202

**Comment by benjymous** [comment]
Thanks :)
