### ISSUE TITLE
Contributing -- creating a branch

### ISSUE THREAD

**Issue by gonzus** [svaarala/duktape#1876]
This is probably a newbie question... sorry in advance.

I have a local branch in my laptop with some changes I want to contribute. I cannot push it upstream because I don't have the permissions.

How is this done? Should I create my own (living in github) clone of the duktape repo, create my branch in there, and then issue a pull request referencing the branch in my own clone?

**Comment by fatcerberus** [comment]
What you have to do is create a fork on GitHub (there’s a Fork button on the main repo page), then push your changes to the fork and make a pull request from that.
