### ISSUE TITLE
TypeScript 2.5 compatibility

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1878]
See https://github.com/svaarala/duktape/issues/523#issuecomment-382737135.

@thradams Opened a separate issue for this.

**Comment by thradams** [comment]
I am testing typescript with duktape using the following code:

````c

/* Push file as a buffer. */
void fileio_push_file_buffer(duk_context *ctx, const char *filename) {
  FILE *f = NULL;
  long len;
  void *buf;
  size_t got;

  if (!filename) {
    goto error;
  }

  f = fopen(filename, "rb");
  if (!f) {
    goto error;
  }

  if (fseek(f, 0, SEEK_END) != 0) {
    goto error;
  }

  len = ftell(f);

  if (fseek(f, 0, SEEK_SET) != 0) {
    goto error;
  }

  buf = duk_push_fixed_buffer(ctx, (size_t)len);

  got = fread(buf, 1, len, f);
  if (got != (size_t)len) {
    duk_pop(ctx);
    goto error;
  }

  fclose(f);
  return;

error:
  if (f) {
    fclose(f);
  }
  duk_push_undefined(ctx);
}

/* Push file as a string. */
void fileio_push_file_string(duk_context *ctx, const char *filename) {
  fileio_push_file_buffer(ctx, filename);
  if (duk_is_buffer(ctx, -1)) {
    duk_buffer_to_string(ctx, -1);
  }
}

int main()
{
  duk_context *ctx = duk_create_heap_default();
  
  fileio_push_file_string(ctx, "typescriptServices.js");
  if (duk_peval(ctx) != 0)
  {
    const char* pError = duk_safe_to_string(ctx, -1);
  }
  else
  {
    if (duk_peval_string(ctx, "ts.transpile('class X{}');") != 0) 
    {
      const char* pError = duk_safe_to_string(ctx, -1);
      pError = 0;
    }
  }  
  printf("return value is: %s\n", duk_get_string(ctx, -1)); 
  duk_destroy_heap(ctx);
  return 0;
}
```

It works for typescript release 2.4 

https://raw.githubusercontent.com/Microsoft/TypeScript/release-2.5/lib/typescriptServices.js

But it is not working for 2.5 and above

https://raw.githubusercontent.com/Microsoft/TypeScript/release-2.5/lib/typescriptServices.js

The error I got is at line:

  if (duk_peval_string(ctx, "ts.transpile('class X{}');") != 0) 

"ReferenceError: identifier 'ts' undefined"

**Comment by svaarala** [comment]
FWIW in master:
```
duktape@leijulauta:~/duktape$ ./duk /tmp/typescriptServices.js  -i
duk> ts.transpile('class X{}');
= "var X = /** @class */ (function () {\r\n    function X() {\r\n    }\r\n    return X;\r\n}());\r\n"
duk> 
Cleaning up...
```

**Comment by thradams** [comment]
Sorry, can you explain?
Is it working? Is the problem something else?

(
 I am using windows, visual studio 2017, saving typescriptServices.js with utf8 encoding.
 Duktape 2.2.0
 Original duk_config.h
)

**Comment by svaarala** [comment]
@thradams It might be related to the difference between evaluating the code as "program code" vs. "eval code":

```

**Comment by thradams** [comment]
I changed the code from

```c
if (duk_peval(ctx) != 0)
```
to

```c
  duk_push_string(ctx, "eval");
  duk_compile(ctx, DUK_COMPILE_STRICT);  /* [ ... source filename ] -> [ function ] */
  duk_call(ctx, 0);
```
and it worked with TS 2.5 and TS 2.8 (latest).

Something related with "program code" vs. "eval code" I guess, like you said.
(This concept is new for me)

Thanks.

**Comment by svaarala** [comment]
Ok, so it seems that the code is "strict mode" code, i.e. it has a 'use strict' declaration at the top. This means that if it is executed using eval(), any variable declarations made in the source code don't get added to the global object. As a toy example:

```
$ ./duk
((o) Duktape [linenoise] 2.2.99 (v2.2.0-264-g41760d52)
duk> eval('var foo = 123'); print(foo);
123
= undefined
duk> eval('"use strict"; var bar = 123'); print(bar);
ReferenceError: identifier 'bar' undefined
    at [anon] (duk_js_var.c:1204) internal
    at global (input:1) preventsyield
```

Just for comparison, Node.js behaves the same:

```
$ nodejs
> print=console.log;
[Function: bound ]
> eval('var foo = 123'); print(foo);
123
undefined
> eval('"use strict"; var bar = 123'); print(bar);
ReferenceError: bar is not defined
    at repl:1:44
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:539:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```

So I think the best fix is to switch to running the source as "program code", i.e. using duk_pcompile() with zero flags (defaults to "program code") and then executing the result with duk_pcall().

You could edit the TypeScript code to work around the issue in a few ways:

First, you could remove the 'use strict', but this may have side effects you don't want.

Second, if `ts` is the **only** thing missing from the global object (which I'm not sure of), you could append the following line at the end of the source:

```
new Function('return this')().ts = ts;  // <=> global.this = ts;
```

which should set the `ts` global binding at the end of the source. I'm not sure if this makes it work completely, but at least the failing example you gave works with this.

But I'd still recommend the duk_pcompile() + duk_peval() approach because it requires no changes to the source.

**Comment by svaarala** [comment]
Btw, the `DUK_COMPILE_STRICT` is not strictly necessary because the source code says `"use strict";`.

**Comment by fatcerberus** [comment]
It was my experience that `var` declarations at the top-level of a script don't become global if the script is strict mode, even when run as program code, so this issue seems odd...

**Comment by svaarala** [comment]
They do become globals in program code.

**Comment by svaarala** [comment]
So for example, this web page will alert "number":

```
<!DOCTYPE html>
<html>
<head></head>
<body>
<script>
"use strict";
var foo = 123;
var global = new Function('return this')();
alert(typeof global.foo);
</script>
</body>
</html>
```

**Comment by fatcerberus** [comment]
Interesting, as miniSphere 4.x and earlier (4.8.8 being the last version using Duktape) didn't behave that way.  So I just looked into that and as it turns out:
https://github.com/fatcerberus/minisphere/blob/v4.8.8/src/minisphere/script.c#L97

:)

**Comment by svaarala** [comment]
@fatcerberus Yep, most people want to evaluate code as "eval code" and are unaware of the small but significant differences. I'd really like to see this program/eval code distinction going away...

**Comment by svaarala** [comment]
@thradams Closing this now, please reopen if something wasn't resolved.
