### ISSUE TITLE
miniSphere is no longer a project using Duktape

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1883]
The last miniSphere version using Duktape for its frontend was 4.8.8.  miniSphere has been based on [ChakraCore](https://github.com/Microsoft/ChakraCore) since [version 5.0.0](https://github.com/fatcerberus/minisphere/releases/tag/v5.0.0).

The above being the case, it's probably misleading to have miniSphere listed on the "projects using Duktape" page.  On the other hand, it's historically significant that it *was* based on Duktape for a long time (and started its life as such), so I'm actually not sure what the best way to handle this is...

**Comment by svaarala** [comment]
I'm OK with either option - just tell me which you prefer :)

**Comment by svaarala** [comment]
Here's the pull to remove it from the list: https://github.com/svaarala/duktape-wiki/pull/203. To me that seems like the best change, but like I said it's up to you.
