### ISSUE TITLE
Remove Number.prototype internal number value slot

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1886]
Remove the internal Number value slot for Number.prototype, changed in ES2015: https://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-number-prototype-object.

**Comment by svaarala** [comment]
Current behavior:
```
duk> Number.prototype.valueOf.call(new Number(123))
= 123
duk> Number.prototype.valueOf.call(123)
= 123
duk> Number.prototype.valueOf.call(Number.prototype)
= 0
```

ES2015 behavior:
```
duk> Number.prototype.valueOf.call(new Number(123))
= 123
duk> Number.prototype.valueOf.call(123)
= 123
duk> Number.prototype.valueOf.call(Number.prototype)
=> TypeError
```

To be verified, because Node.js and Firefox still behave the same as current Duktape.

**Comment by svaarala** [comment]
It seems that the Number-nature of Number.prototype was restored in later versions. TC39 current snapshot says:
> The Number prototype object is the intrinsic object %NumberPrototype%. The Number prototype object is an ordinary object. The Number prototype object is itself a Number object; it has a [[NumberData]] internal slot with the value +0.

So, no change is likely to be needed after all.

**Comment by fatcerberus** [comment]
I’m guessing the ES6 change broke people’s code so they had to revert it.

**Comment by svaarala** [comment]
#1893 replaces.
