### ISSUE TITLE
C API changes for Node.js Buffer and TypedArray objects

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#190]
The current C API deals with plain buffer values, e.g. `duk_is_buffer()`, `duk_get_buffer()`, and `duk_require_buffer()` all expect plain buffer values and won't work with buffer objects (Duktape.Buffer, Node.js Buffer, ArrayBuffer, TypedArray values). The same situation exists for string values: e.g. `duk_get_string()` works for a plain string but not a String object.

Perhaps add a compatible extension to get the buffer data area of a plain buffer or a buffer object. There's one major difference between plain buffers and buffer objects: buffer objects support "views/slices" of an underlying buffer while plain buffers do not. The API call to get a buffer object's data area should take view offset/length into account so that C code would only interact with the slice active for that Buffer object.

- [x] Creating buffer objects from C (instead of just plain buffers)
- [x] Type checking for a buffer object - perhaps postpone to 1.4 because there's no such primitive for String objects either
- [x] Consider `byte_length` argument typing for `duk_push_buffer_object()`
- [x] Check .buffer of push result, at least for typed array views and DataView
- [x] Getting the data area (active slice) of a buffer object from C code
- [x] Note automatic ArrayBuffer creation in `duk_push_buffer_object()` API doc

**Comment by svaarala** [comment]
API calls for getting data area of a plain buffer or a buffer object:

- https://github.com/svaarala/duktape/compare/api-get-buffer-data

The other approach would be to change the semantics of current buffer calls. The upside would be a a smaller API footprint for buffer handling; the downside would be that buffer API changes would be postponed until 2.0.

I'll add these compatible API extensions (there are going to be around 4-5 functions total). The whole buffer handling API for both C and Ecmascript need a cleanup in a major version bump to remove redundancies now that TypedArray is supported. Unfortunately this means C code dealing with buffer values may need small changes afterwards.

**Comment by fatcerberus** [comment]
Just to clarify: 1.3 *will* support TypedArray, yes?

**Comment by svaarala** [comment]
@fatcerberus Yes, TypedArray support has already been merged to master.

**Comment by svaarala** [comment]
The `duk_get_buffer_data()` and `duk_require_buffer_data()` API calls are now in master.

**Comment by svaarala** [comment]
Draft implementation branch for pushing buffer objects:

- https://github.com/svaarala/duktape/compare/api-push-buffer-object

The basic idiom supports all buffer object and view types. It requires an underlying plain buffer, and supports creation of slices:

```c
/* Create an Uint16Array of 25 elements, backed by plain buffer at 'idx_plain_buffer',
 * starting from byte offset 100 and having byte length 50.
 */
duk_push_buffer_object(ctx,
                       -3 /*index of plain buffer*/,
                       100 /*byte offset*/,
                       50 /*byte length*/,
                       DUK_BUFOBJ_UINT16ARRAY /*flags and type*/);
```

**Comment by svaarala** [comment]
Unless there are any improvement suggestions, I'll merge the `duk_push_buffer_object()` tomorrow to round out the API changes for buffer support.

I postponed the type check API for boxed buffer objects: there's also no type check API call for boxed strings (`duk_is_string()` returns true for plain strings, and false for `String` objects) so it's probably best to address this for all boxed types at the same time. These types are: booleans, number, strings, and buffers. Tracked in #167.

**Comment by fatcerberus** [comment]
"Backed by plain buffer" - I thought TypedArray was always supposed to be backed by an ArrayBuffer?

**Comment by svaarala** [comment]
Yes, but the ArrayBuffer is backed by a plain buffer in Duktape.

**Comment by svaarala** [comment]
In Duktape's internal data model it would be possible to create a typed array (view) backed directly by only a `duk_hbuffer`, i.e. a plain buffer.

This is how it works anyway: when you create a typed array from an ArrayBuffer, the plain buffer reference underlying the ArrayBuffer gets copied into the typed array (sharing the same plain buffer). So each buffer object (internally `duk_hbufferobject`) ultimately points directly to a plain buffer. The plain buffer reference gets copied around when new "slices" (views) are created.

The `.buffer` reference in a typed array is not used by Duktape, it's only there for user code. It can also be deleted to save memory.

**Comment by fatcerberus** [comment]
That makes sense.  I figured the ArrayBuffer would itself be backed by a plain buffer internally, I just thought that the specification would have mandated an underlying ArrayBuffer object be visible to user code.  The ES specs tend to be strict like that :)

**Comment by fatcerberus** [comment]
But yes, this looks good.  This has always been one of Duktape's big strengths for me, anything that can be done by JS code can be also be done on the native side if you're willing to do some valstack juggling.  Many other engines, e.g. Jurassic, while powerful, don't allow this kind of fine-grained control.

**Comment by svaarala** [comment]
Yeah :) The current branch has a bug in that the C API calls don't create the ArrayBuffer and add the `.buffer` property to typed arrays. I'll fix that tomorrow before merging.

In Duktape 2.0 I'd like to simplify the buffer setup a bit. Not sure how yet, though.

Plain buffers are very useful in low memory environments because they're so memory efficient. For example a fixed plain buffer uses only a single allocation of 12 bytes + buffer data area (IIRC), and that includes heap header stuff (flags, type, refcount, heap pointers, pointer compression applied). A comparable ArrayBuffer with a Uint8Array view would involve two full objects with an actual property table allocated for at least the view (to hold `.buffer`). So removing plain buffers doesn't seem like a good change.

ArrayBuffers could own their data area directly without going through a plain buffer. But it'd be a shame to duplicate all the functionality of plain buffers there - e.g. dynamic buffers and external buffers. So it just seems simpler to back to a plain buffer *if* plain buffers are around anyway.

Getting rid of Duktape.Buffer would be possible - its only real function over ArrayBuffer is returning the plain underlying buffer for any buffer object (similarly to how `String(xyz)` returns a plain string for a boxed `String`). But that functionality could go elsewhere, e.g. as a custom method `ArrayBuffer.plain()`.

Removing Node.js Buffer binding would be possible, but there are users who are doing Node.js compatible stuff in Duktape and they do need it. Providing the ability to implement it from outside would probably remove that need, but that'd require some kind of efficient C callback mechanism for implementing virtual arrays or similar.

Stuff to think about another time :-)

**Comment by svaarala** [comment]
The only remaining issue is `byte_offset` and `byte_length` typing. They are both `duk_uint_t` now because that's what the view handling in `duk_hbufferobject` uses. The could also conceivably be:

- `duk_size_t`, to better match what other "C buffer length" fields use. However, `duk_size_t` may be a larger type than `duk_uint_t` so this would need range checks in the API call.
- `duk_uarridx_t`, to better match what arrays and virtual arrays use for length.

This has very little practical impact unless buffers are larger than 4G - which is not supported at the moment in practice anyway.

**Comment by fatcerberus** [comment]
`duk_uarridx_t` seems the better choice here, as it's indexed just like any other array in JS.  If you used, say, `duk_get_prop_index()` on it, that's all the range you'd get anyway.

**Comment by svaarala** [comment]
It's unfortunately not that simple :)

Suppose you have a 8G buffer, and map a Uint32Array over it. That Uint32Array would have 2G elements (mapping to 8G bytes) so that while the array indices are within 32 bits, the byte offsets and length are potentially not (though they'd be within `duk_size_t` range in that case).

But, this is pretty theoretical as very few users are running Duktape with >2G or >4G heaps.

**Comment by svaarala** [comment]
To clarify previous, `duk_uarridx_t` is now unsigned 32 bits because that's what array indices are in E5.1. But IIRC E6 relaxes that to allow larger arrays (I'd need to check but don't have time right now) so that type may be 64 bits later on.

**Comment by fatcerberus** [comment]
That would make sense if so, no reason to force an artificial 4G limitation when typical hardware supports far more.  Of course the ES spec itself undermines full 64-bit support--all numbers are IEEE double, whose integer range tops out at... what, 52 bits?

**Comment by svaarala** [comment]
IEEE double can represent integers [-2^53,2^53] accurately. I wouldn't worry about it being too limiting for array/buffer/string lengths: 2^53 is 8192 terabytes... :-)

**Comment by svaarala** [comment]
I'll reopen this - the API is lacking a wrap check (offset + length wraps `duk_uint_t`.

Mulling it over a bit I'm inclined towards the `duk_size_t` type for the byte offset and length:

- As a general rule the C API uses `duk_size_t` when a pointer/length pair are dealt with. For example `duk_push_lstring()`, `duk_config_buffer()`, etc.
- This choice is most future proof if buffer, array, typedarray etc length restrictions are lifted later.
- A runtime check is needed for length+offset wrapping anyway, so also checking for range should not matter very much.

**Comment by fatcerberus** [comment]
Maybe duk_uarridx_t should just be redefined to be the same range as size_t?  That will be needed later anyway if the array restrictions _are_ lifted...

**Comment by svaarala** [comment]
That would be incompatible right now because `duk_uarridx_t` must be exactly 32 bits for E5.1 compliance.

**Comment by fatcerberus** [comment]
Ah, didn't realize that.

**Comment by svaarala** [comment]
That was maybe too strong a statement: E5.1 provides special array index behavior only for the 32-bit range. Outside that range it's required that indexes have no special behavior. The C typing could be changed but this special behavior would still be restricted to 32 bits so extending the type wouldn't necessarily be very logical. For consistency some range checks might be required, e.g. attempt to set an array length to be over 4G should maybe fail (like it does if you set it to be over 4G from Ecmascript).

In any case the array indices are technically independent of *byte* indices. This is more of a technicality though: while a `Uint32Array` for example could have a logical length of less than 4G elements (and a byte length 4x4 = 16 GB), creating such a view object also requires creation of an `ArrayBuffer` which would then have 16GB bytes. Because of that `ArrayBuffer` the 4G *byte* limit restricts creation of `Uint32Array`s too.

But revisiting these types in Duktape 2.0 would be useful. I'm sure there is room for improvement and changes needed for ES6.

**Comment by fatcerberus** [comment]
I'm actually surprised the spec mandates specific behavior for indices at all, seeing as:

```javascript
arr[1]
```

Is semantically equivalent to:

```javascript
arr["1"]
```

The specification baffles me at times. :P

**Comment by svaarala** [comment]
Yes, the 32-bit limit is somewhat odd:

```
> a = []; a[0xfffffffe] = 1;
1
> a.length
4294967295
> a = []; a[0xffffffff] = 1;
1
> a.length
0
```

In other words, the index `2**32 - 2` is the last index to trigger an automatic length update. `2**32 - 1` does not, because that would push the length to be 0x100000000, i.e. over the 32-bit limit.

Also note that while `a[1] === a["1"]`, only strings which are canonical string representations of integers are array indices, e.g. `a["1.0"]` is not an array index (but `a[1.0] === a[1]`).

**Comment by svaarala** [comment]
All right, wrap and typecast check is in place, and typing changed to `duk_size_t`.

**Comment by Type1J** [comment]
@svaarala This might not be the right place to bring this up, but I noticed above that you said that ArrayBuffer.plain() might be added at some point. Is there a way to get the plain buffer backing an ArrayBuffer from the C API, or do you have to call "Duktape.Buffer()" to get it?

Right now, I have a project in which I have an ArrayBuffer, and I'd like to make a Uint8Array view from C. I can do that in script already with the normal Uint8Array constructor, but assuming that I have the ArrayBuffer on the stack, how would make a Uint8Array using the C API? I would think that I need to get the plain buffer on the stack first, then use duk_push_buffer_object(), but how does one get the plain buffer from an ArrayBuffer using just the C API? If ArrayBuffer had a plain() property, then would calling it from the C API be the best way to get the plain buffer on the stack, or is there already a better way?

I've read the docs about buffers a few times, but I can't figure this one out. The only way that I can see is to call Duktape.Buffer() from C.

**Comment by svaarala** [comment]
@Type1J Right, the buffer bindings are pretty well implemented in the Javascript side except for buffer type interoperability which is necessarily a bit non-standard. The C API is pretty bare bones now, and there are a few incompatible changes I'd like to make to make the C API simpler, such as removing Duktape.Buffer and then seeing where things naturally fall. I intentionally didn't want to write a bunch of API calls and create a backwards compatibility mess too early. Sorry :-)

You're right that `duk_push_buffer_object()` currently requires a plain buffer and getting the underlying plain buffer from an `ArrayBuffer` now involves `Duktape.Buffer()` which is awkward.

One approach is to extend `duk_push_buffer_object()` to accept a buffer object too (if the buffer object was a "view", it would then maybe respect an existing view offset/length and create a subview). This wouldn't need to wait for an incompatible buffer rework because it's a pretty natural extension.

Another approach would be to add an explicit API call to extract the plain buffer inside a buffer object. One would probably then also want to know the view offset/length, and the element type, to be able to recreate a new buffer object with similar backing values. This seems like an API that might encounter scope creep, especially if buffer objects gain new conceptual properties ... :)

A third approach would be to use some existing API call to get the plain buffer. For example `duk_to_primitive()` would seem natural, and it works for Duktape.Buffer because Duktape.Buffer.prototype.valueOf() returns the primitive value; it also works for String objects for the same reason. However, ArrayBuffer.prototype.valueOf() is required to return the buffer object because there's no standard type which is more primitive, so it doesn't do what one might expect here.

**Comment by svaarala** [comment]
In the meanwhile I'll add an issue to cover this topic in the wiki buffers article.

**Comment by fatcerberus** [comment]
You could maybe "cheat" by calling `duk_get_buffer_data()` followed by `duk_push_buffer()`.  Not sure if this would cause other issues, but it shouldn't since a plain buffer is just an address/size pair, a value type.

**Comment by svaarala** [comment]
That would duplicate the buffer contents though - an external buffer could be used for that but it'd be error prone because the resulting buffer would rely on the original ArrayBuffer being reachable for its lifetime. Not recommended :)

**Comment by Type1J** [comment]
@fatcerberus: Thanks. That would have been a quick solution if you could guarantee the lifetime of that memory allocation. I'm not sure if there's an internal pointer hash of active buffer pointers, but it sounds as if the new buffer could only be an external buffer in that case, and that new buffer would have a potentially different life time than the original buffer.

For the record, my solution was something like this (I knew that my buffer size was 8, but that could have easily been obtained by duk_get_buffer_data()):

    // We'll use the global object to store things.
    duk_push_global_object(ctx);

    // Make a Plain Buffer.
    duk_push_fixed_buffer(ctx, 8);

    // Make an ArrayBuffer backed by the plain buffer.
    duk_push_buffer_object(ctx, -1, 0, 8, DUK_BUFOBJ_ARRAYBUFFER);
    duk_replace(ctx, -2);

    duk_put_prop_string(ctx, -2, "buf");

    // Pop off the global object.
    duk_pop(ctx);

...some time later...

    // Get the global object.
    duk_push_global_object(ctx);

    // Make Uint8Array for the buffer called "buf" in the global object.
    // Get the Plain Buffer that backs "buf"
    duk_get_prop_string(ctx, -1, "Duktape");
    duk_get_prop_string(ctx, -1, "Buffer");
    duk_replace(ctx, -2);
    duk_get_prop_string(ctx, -2, "buf");
    duk_call(ctx, 1);
    // Create the Uint8Array backed by "buf" (actually, the same Plain Buffer that backs "buf").
    duk_push_buffer_object(ctx, -1, 0, 8, DUK_BUFOBJ_UINT8ARRAY);
    duk_replace(ctx, -2);

    // Store the new Uint8Array as "bufView" in the global object.
    duk_put_prop_string(ctx, -2, "bufView");

    // Pop off the global object.
    duk_pop(ctx);

**Comment by fatcerberus** [comment]
It's guaranteed not to move if it's a fixed buffer, which it should be (ArrayBuffers can't be resized).  Dynamic buffers would of course be trickier.

**Comment by svaarala** [comment]
Fixed and dynamic plain buffers "own" their allocation so the lifecycle of the buffer data lives with the plain buffer value. Plain buffer values are heap allocated and their heap header has a stable pointer; the data area pointer is only stable for fixed buffers because the data follows that heap header immediately.

As for ArrayBuffers and resize - the way Duktape handles this is that buffer objects have a virtual size, which backs into a plain buffer underneath. You *can* resize that underlying buffer, and even make it smaller than the apparent ArrayBuffer size (or any other buffer object); this is memory safe. So, the underlying plain buffer can be any type, even an external one.

**Comment by svaarala** [comment]
The point of this construction is that you can create an ArrayBuffer backed by an external plain buffer which is directly mapped to, say, a frame buffer allocated externally.

**Comment by fatcerberus** [comment]
What kind of plain buffer is created when you do, say, `new ArrayBuffer(812)`?

**Comment by fatcerberus** [comment]
Also, don't we have that function to "steal" buffers now, so that their lifetime is no longer managed by Duktape?  I don't know if that works with ArrayBuffers though...

**Comment by svaarala** [comment]
You could steal a dynamic buffer - but all of this is way too hacky IMO compared to calling Duktape.Buffer()... :)

**Comment by svaarala** [comment]
So just to be clear about the difference, if you get the plain buffer in a legitimate fashion and create a view based on that, there will be two buffer objects which will reference the same plain buffer. Both references will be properly reference counted, the plain buffer will be automatically freed when both references are gone, etc.

If you get a data area pointer and create a new buffer, you'll be copying the data into a newly allocated buffer (if you push a dynamic/fixed buffer) or referencing existing buffer data (if you push an external buffer). In the latter case the reference is not known to Duktape, so the outcome will be very fragile with respect to object lifecycles. I don't see why you'd want to do this in practice because just calling `Duktape.Buffer()` or using the workaround above is easier and less fragile.

**Comment by fatcerberus** [comment]
Yeah, I agree this is all a big hack, it's just I tend to be iffy about referencing JS-side objects by name from C because you don't know whether a script has replaced it with something else.  This is particularly important when you don't have direct control over the scripts you might end up running, as is the case in, for example, minisphere.

**Comment by svaarala** [comment]
That's true, but also Ecmascript code will have the same issue. If it's a real concern, the typical solution is to copy a reference during initialization and use that.

**Comment by svaarala** [comment]
Somewhat off topic but internal Ecmascript semantics typically refer to the "original XXX object/function" and Duktape uses in internal built-ins array to keep the "original" references. This is currently not handled well in sandboxing so there may be a need to expose that set of built-ins in the API for sandboxing. If so, one would then be able to e.g. push the "original XXX" (say, original RegExp constructor) using the API, and also replace that original object which may matter in sandboxing.

But committing to a set of objects/functions to expose is a bit painful - there are hundreds of built-in methods for instance, and a reference to the original value is needed for only a handful to implement Ecmascript semantics. If that set changes, it causes hassle in the API to keep compatibility. One reasonable sounding alternative so far would be to have an API call to "sync" current globals into the internal array so that you could edit the globals, replace them with your own implementations etc, and then tell Duktape to sync them into the built-in reference slots for implementing semantics.

Anyway, off topic ;)

**Comment by fatcerberus** [comment]
Is this issue solved?  It's marked for 1.3.0 and the whole checklist is checked off, so should this have been closed?

**Comment by svaarala** [comment]
I think it is closed (Sep 7)?

**Comment by fatcerberus** [comment]
Oh, I see, it was closed way above, then the discussion continued a while so I didn't see the "closed" notice.
