### ISSUE TITLE
Provide a stack trace for syntax errors and the like in eval(s).

### ISSUE THREAD

**Issue by cheako** [svaarala/duktape#1900]
https://pastebin.com/aJteC6cd

The pastebin has a comment at line one, but try inserting a line feed there and u get the same error.

The issue I'm reporting is that the line number from the error is wrong, thus preventing further debugging into why the code won't compile.  Bonus points for identifying why the error.

**Comment by cheako** [comment]
This was because of an eval.

**Comment by svaarala** [comment]
Did you figure out the problem?

**Comment by svaarala** [comment]
Evals are a bit interesting in tracebacks because sometimes it is important to have a line number for the eval source itself (e.g. if it is read from a file), and at other times the call site (the eval() call itself) is interesting. Sometimes it is both, so a traceback would ideally indicate both the call site file/line and the eval code line.

**Comment by svaarala** [comment]
In concrete terms, here's an example with an erroring eval:
```
$ cat /tmp/test.js 
print('line 1');
print('line 2');
eval('print("aiee');  // SyntaxError here
print('never here');
```

This now syntax errors out of the eval, producing the error:
```
SyntaxError: unterminated string (line 1)
```

The error string itself doesn't provide more context, but the stack trace does include the original call site (test.js:3):
```
line 1
line 2
SyntaxError: unterminated string (line 1)
    at [anon] (input:1) internal
    at [anon] (duk_lexer.c:944) internal
    at eval () native strict directeval preventsyield
    at global (/tmp/test.js:3) preventsyield
error in executing file /tmp/test.js
```

So one might improve this by:
- Including the call site file/line in the SyntaxError `.message` directly, though one could also argue it shouldn't be there in the first place (and should only be in the stack trace like all other line numbers).
- Including the call site file/line in the same line of the stack trace as the eval code call. Though I'm not sure if this is much better than having it later on in the stack trace (matching how the call stack works) as it is now.

**Comment by svaarala** [comment]
@cheako Could you check out the worked out example above, and comment on what improvement you would like to see?

**Comment by cheako** [comment]
I agree and even for recursive evals we need the line number information at a bare minimum.  I'm looking at duk internals and I think one would have to add a string match for "eval" function name somewhere in the lexer and emit some new op(s) to stash away the eval's backtrace information.

**Comment by cheako** [comment]
Ohh, so I just need to add the stack trace to my error handler, I think I can figure that out.

**Comment by fatcerberus** [comment]
I still don't understand - the backtrace is already in the error object `.stack`.  Duktape already tracks that information.

**Comment by cheako** [comment]
I'm hitting "fatal_handler", so to get a backtrace I'd need to handle the events thrown.  I can figure this out then.

**Comment by fatcerberus** [comment]
Note that you can hit the fatal error handler for reasons other than an uncaught exception (I think...) so ideally you should be using the protected calls such as `duk_pcall` and check the result rather than letting it become a fatal error.

**Comment by svaarala** [comment]
(Sorry for the long delay, apparently most, but not all, of my GIthub notifications started going to spam.)

@cheako The fatal error message is indeed quite sparse, the main reasons for that are that it is called when it's no longer safe to continue so the error message is created with minimal assumptions (but still somewhat informative):
- Use a small stack-only buffer with no memory allocations, heap changes, etc.
- Use only side effect free operations to e.g. print error information

Right now the stack trace is too long for the stack only buffer, but this could be changed. Also `.stack` is an accessor with side effects so it's not something the fatal error handling should access, but maybe there could be a safe parallel variant which would reconstruct the stack trace with zero side effects at least in the most common cases.
