### ISSUE TITLE
need get/put for `void *`

### ISSUE THREAD

**Issue by jockm** [svaarala/duktape#1905]
I am writing an app where I need to stash a pointer to an object in the context, so this can read back inside of a C Function.

On a 64 bit system the size of a pointer is lager than `duk_int_t` and and a pointer is going to be larger than the mantissa of a IEEE double.  In the end I had to cast my pointer to be a `duk_c_function` to save it, and re-cast it when retrieved.

While this works and should be safe regardless of 32/64 cpu size, it is a bit of a hack.  I would love to see get/put functions for a `duc_c_pointer` type

**Comment by fatcerberus** [comment]
`duk_push_pointer()` and related functions already exist for this purpose:
http://duktape.org/api.html#duk_push_pointer

**Comment by jockm** [comment]
Mea culpa.  I swear I searched before posting, but clearly not well enough ;)
