### ISSUE TITLE
Can duktape return lexical info for a JS text?

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1912]
In one of my projects I generate JS from certain DB data (Jasmine test cases). Now I'd like to know if I can replace/remove a test spec when it hasn't got any content yet but the DB entry for that changed.

Jasmine allows to mark a spec with a call to `pending(message)`. I could use that to mark empty specs and when I regenerate the specs file next time I can take out such specs if the have been removed from the DB.

For that I need to parse the JS text somehow and find the calls to `pending`. Can duktape give me the necessary details, e.g. return the internal parser data it has for an evaluated script?

**Comment by fatcerberus** [comment]
Duktape has a near-stateless recursive descent parser - it doesn’t maintain an AST, not even a partial one, and from what I understand its intermediate representation is limited to one or two expression terms at any given time.

You’ll need to use something like Esprima for this, I think.

**Comment by mike-lischke** [comment]
Many thanks for the pointer. I thought already about using some 3rd party lib, but wanted to ask first if my favorite JS backend can give me that info.

**Comment by svaarala** [comment]
Duktape doesn't currently maintain an AST even for a single expression, it only works on intermediate results and combining such results a single operator at a time. This will eventually change because ES2015 requires it.
