### ISSUE TITLE
Create Duktape as macOS Homebrew Formula

### ISSUE THREAD

**Issue by elmodaddyb** [svaarala/duktape#1913]
Hello,

This issue is to determine the interest level of the Duktape team to have a macOS Homebrew formula to install the duktape library into macOS.

### Background

I work on [Gerbera UPnP media server](https://github.com/gerbera) which uses the Duktape library for scripting support.  We would like to [create a Homebrew formula](https://github.com/gerbera/gerbera/issues/286) to make it easy for installation on macOS.  Since Duktape is a dependency, it seems reasonable to create a Homebrew formula for the library as well.

### Request

I created an [initial Duktape Homebrew formula](https://gist.github.com/elmodaddyb/a7947ee61d05a5bdd137ba564fcb1898), but would request your approval before pursuing such an addition to Homebrew project.

**Comment by svaarala** [comment]
Hi @elmodaddyb,

In general the duktape repo doesn't provide or maintain official build scripts for targets - there are way too many combinations of targets, preferred build tools etc for that purpose. But it's great if such scripts are provided separately, and I'd be happy to link to them too.

**Comment by elmodaddyb** [comment]
@svaarala - Thanks for the prompt reply.  The homebrew script will use the generally available download link provided by the `duktape` repository only.  Shall I comment that no support is provided by maintainers for homebrew build script?  Perhaps it will avoid any issues being opened here...

If you agree with the approach, we can close this issue.

Thanks again for your attention to this issue.

- Eamonn

**Comment by svaarala** [comment]
Sounds like a good approach to me. Re: the maintainer comment, I don't have a strong opinion, from the user perspective it'd be nice to point out where to raise issues (instead of saying where not to raise them :-)

**Comment by elmodaddyb** [comment]
Thanks much for your feedback.
