### ISSUE TITLE
Error: cannot push beyond allocated stack

### ISSUE THREAD

**Issue by gonzus** [svaarala/duktape#1916]
I am getting this error:
`duktape fatal error, aborting: uncaught: 'cannot push beyond allocated stack'`

But if I just add this line in the code before that error happens, everything works ok (yes, I am not using the return value at all)
`duk_to_string(ctx, -1);`

I guess the `duk_to_string` call is causing the stack to grow, so that the condition for the error does not happen. I tried replacing that call with one of these two lines:
`duk_require_stack(ctx, 1000);`
`duk_check_stack(ctx, 1000);`

but the error did not go away. Any hints? Thanks!

**Comment by svaarala** [comment]
@gonzus Could you provide something I could reproduce the error with?

duk_require_stack() should be enough to grow the stack.

**Comment by svaarala** [comment]
Also, which version of Duktape are you using?

**Comment by gonzus** [comment]
It seems the error was a bit of a red herring... It happens because of `extras/module-node/test.c:36`:
```duk_push_string(ctx, "module.exports = { module: module, __filename: __filename, wasLoaded: module.loaded };");```

My code was traversing that data structure, and because it is recursive, it ran out of stack space.

I am not sure if the recursive data is required for this test.

**Comment by svaarala** [comment]
I don't think the recursive reference itself is critical, but the `.module` is used by the minimal unit tests in the Makefile on purpose.
