### ISSUE TITLE
Accessing a heap's udata pointer

### ISSUE THREAD

**Issue by benjymous** [svaarala/duktape#1917]
Is there an official way for user code to get at the current context's heap udata pointer?  

I added my own function, but I wasn't sure if there's a proper way of doing this, since there isn't an obvious way of accessing the heap if you only have a context pointer.

```
DUK_EXTERNAL void* duk_get_heap_udata(duk_context *ctx) {
	return ctx->heap->heap_udata;
}
```

**Comment by svaarala** [comment]
This function currently provides the heap udata: http://duktape.org/api.html#duk_get_memory_functions.

**Comment by sseyod** [comment]
I agree with benjymous - this is a very useful thing to have.

**Comment by benjymous** [comment]
Closing this, as it's resolved by svaarla's comment
