### ISSUE TITLE
Map() reference error

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1918]
duktape supports the Javascript `Map` type, right? Why do I get a reference error when I use it:

```
Error encountered: sync/test-sync.js
ReferenceError: identifier 'Map' undefined
    at processTestCase (sync/test-sync.js:158)
    at processModule (sync/test-sync.js:136)
    at syncTestModules (sync/test-sync.js:109)
    at runSynchronization (sync/test-sync.js:88)
    at global (sync/test-sync.js:63)
    at [anon] (eval:1)
The terminal process terminated with exit code: 2
```

For the code line:

` var t = new Map();`

I recently upgraded to version 2.2.1.

**Update**

The same happens with `Set`, while `Array` works as expected.

**Comment by svaarala** [comment]
Map, Set, WeakMap, WeakSet are not yet implemented.

**Comment by mike-lischke** [comment]
That's a bummer and pretty serious limitation. I have to admit I didn't have this on my radar.

Guess it's meaningless to ask when these will be available, right? Could you perhaps create a wiki page listing all built-in types (as mentioned on MDN) and their implementation status? Thanks.

**Comment by fatcerberus** [comment]
By and large, Duktape currently only implements ES5.1 with a few select features from ES2015 (ES6) and later.  Map, Set, etc. are ES6 features.

**Comment by mike-lischke** [comment]
Yes, sure, but it wouldn't even come to my mind that such standard types wouldn't be available. I use them constantly and feel pretty limited without them :-)

**Comment by tsteinholz** [comment]
@mike-lischke I was able to work around this by using the 'es6-shim' package: `import { Map } from 'es6-shim';` prior to the import that called the `Map` constructor.
