### ISSUE TITLE
Can I use a buffer like handle like Node.js

### ISSUE THREAD

**Issue by aseaday** [svaarala/duktape#192]
```C
Buffer* buffer = Buffer::New(data, size, (void *) size);
return buffer->handle_;
```
And you could control it in javascript
```javascript
var buffer = function(..){}
buffer[i] = sth;
```

**Comment by svaarala** [comment]
Right now you can create plain buffer values (byte arrays) from C code and pass them to Ecmascript code. They'll have a virtual "length" property and you can assign values to index properties. The API call you can use is e.g.: http://duktape.org/api.html#duk_push_buffer

However, a buffer can't currently point to an already allocated external data area (which your example seems to be doing). There's an issue to add support for "external" buffers which would allow this, see #153.

**Comment by svaarala** [comment]
@aseaday Ping? :)
