### ISSUE TITLE
rst-conventions: "Nested lists and GitHub" obsolete?

### ISSUE THREAD

**Issue by apjanke** [svaarala/duktape#1920]
In the `doc/rst-conventions.rst` file, under ["Nested lists and GitHub"](https://github.com/svaarala/duktape/blob/dbd46747acc19b8f116b33ce3d58c431ae1270db/doc/rst-conventions.rst#nested-lists-and-github), it describes the need to keep a strict formatting of nested lists to render correctly in GitHub. It includes an example of an incorrectly formatted list.

However, when viewing this section now on GitHub, the example of the incorrectly formatted list renders nicely as a nested list still.

Maybe GitHub's RST renderer has become more lenient, and this section can be removed?

**Comment by svaarala** [comment]
Seems to be the case - though I think the recommendation should remain.

**Comment by apjanke** [comment]
Sounds good.

**Comment by svaarala** [comment]
So maybe the change would be to remove the GitHub reference but keep the recommendation with minor wording changes?

**Comment by svaarala** [comment]
Looks good.
