### ISSUE TITLE
Getting a "pointer" to a generic duktape value

### ISSUE THREAD

**Issue by gonzus** [svaarala/duktape#1927]
I need to find if a duktape object (containing arrays, containing more objects, etc.) has any circular references. The typical way to do this is to traverse the object, keep a list of all seen objects, and do something if you run into an object you have already seen. So this would require the ability to get a "pointer" / unique identifier for a duktape object, in order to store that and later compare. What is the recommended way to do this?

**Comment by fatcerberus** [comment]
`duk_get_heapptr()` should do the trick.  The heap pointer is guaranteed to be stable over the life of the object.

**Comment by gonzus** [comment]
Awesome, missed that one in the docs. Thanks.
