### ISSUE TITLE
Unable to evaluate object correctly

### ISSUE THREAD

**Issue by stevefan1999** [svaarala/duktape#1933]
See this for example:
```js
duk> {}
= undefined
duk> {test: "foo"}
= "foo"
duk> {"test": "foo"}
SyntaxError: unterminated statement (line 1)
    at [anon] (input:1) internal
    at [anon] (duk_js_compiler.c:6738) internal
```
However Node (10 FYI) correctly recognize those constructs:
```js
> {}
{}
> {test: "foo"}
{ test: 'foo' }
> {"test": "foo"}
{ test: 'foo' }
```

DT "incorrectly" saw object declaration as a statement, which is plausible: It can be [object literal](https://www.ecma-international.org/ecma-262/5.1/#sec-11.1.5)

https://github.com/antlr/grammars-v4/blob/master/javascript/JavaScriptParser.g4#L309 I think this is useful.

Workaround: wrap the object "expression" in quotes, which forces it to become a true (super) expression, but statements would fail. Or maybe is that the parser precedence for block statement a bit too high?

**Comment by stevefan1999** [comment]
Seems like it is not the issue of the parser but duk_peval🤔

**Comment by svaarala** [comment]
When you say `{ test: "foo" }` it doesn't parse as an object literal, but as a code block with a label:
```
{
    test: /* LABEL */
        "foo"  /* expression statement
}
```

This is the correct parsing with Ecmascript syntax for eval'd code. If you want to eval that, parentheses are needed: `({ test: "foo" })`.

**Comment by stevefan1999** [comment]
So you're basically saying what V8/Node/Chrome parsed was wrong...To an extreme, should I wrap the whole thing in `eval("%s")`?

**Comment by svaarala** [comment]
If you try this in Node.js you should get a SyntaxError:
```
> eval('{"foo":"bar"}')
SyntaxError: Unexpected token :
```

Exactly because it parses as a code block. This works:
```
> eval('({"foo":"bar"})')
{ foo: 'bar' }
```

It may be that the Node.js REPL is parsing object literals specially (maybe it tries to parse it first as an expression, and only then as a statement?).

**Comment by svaarala** [comment]
If you specifically want to parse an expression (not e.g. an "if" statement) you can just wrap the expression in parentheses. This should ensure the expression is never confused with a block statement.

**Comment by stevefan1999** [comment]
Well, I got this lexer hack:
```cpp
template <class T = void>
constexpr T Eval(const char *src) {
    auto ptr = src;
    while (*ptr != '\0' && isblank(*ptr)) ++ptr;
    if (*ptr == '{') return dukglue_peval<T>(m_ctx, ("(" + std::string(src) + ")").c_str());
    return dukglue_peval<T>(m_ctx, src);
}
```
...which checks if the first non-blank token is LCURLY, if yes wrap it with quotes, if not execute it rawly. The only problem left is to deal with unclosed curly braces. Well a stack count is surely ok but overkill in this situation.

**Comment by svaarala** [comment]
You could probably also use a trial method where you'd first try to parse as `'(' + expr + ')'` and if that fails, parse as `expr`.

**Comment by svaarala** [comment]
As an API improvement note, maybe duk_(p)compile() could provide a `DUK_COMPILE_EXPRESSION` mode which would parse the input as an expression (equivalent to parenthesis wrapping).

**Comment by svaarala** [comment]
And for a REPL one might want a "parse as expression OR statement" ability, so that expressions like object literals would take precedence and the retry would be in the parser itself.

**Comment by fatcerberus** [comment]
I’m kind of surprised the Node REPL parses that.  To my knowledge it’s always been required to parenthesize bare object literals in an eval context.  I’m guessing Node is special-casing it.

**Comment by fatcerberus** [comment]
To be fair, performance-sensitive code probably shouldn't be using eval in the first place as doing so invokes the parser and compiler.  The cost of a second eval is the least of your worries at that point, IMO.
