### ISSUE TITLE
How to implement a Duktape.modSearch function that supports several directories

### ISSUE THREAD

**Issue by markand** [svaarala/duktape#194]
Hello,

I'm trying to implement my own Duktape.modSearch function from C++ side. The key idea is the following:

1. The user calls `require("./foo")` then `foo` will be searched relatively to the current plugin
2. The user calls `require("/foo")` then `foo` will be searched in global directories (such as /usr/local/share/myapp)

The problem:

Let say I open a plugin named **/opt/plugin.js**. I say that its base directory path is **/opt**. It's easy to implement Duktape.modSearch function for it and to load modules that is into this directory.

However, when this plugin tries to load a global module (e.g `require("net")`), I will open **/usr/local/share/myapp/net.js** and then, if the **net.js** file is calling `require("./net-part-1")` I still have the base directory set to **/opt** which means I will not be able to determine that **net-part-1** should be in **/usr/local/share/myapp**.

How would you implement a modSearch function like this? It's like, when I load a global module, I should update the current base directory to the module being serched, however it's not possible to restore the old base path after.

**Comment by svaarala** [comment]
This is currently (probably) not possible because Duktape handles module ID resolution and modSearch() only gets the final, resolved module ID. A modSearch() function can then map that absolute module ID space to the file system in whatever way is appropriate.

You can of course implement a search path so that you try to look for a resolved module ID (such as `foo/bar/quux`) from multiple directories. But the modSearch() function won't know which syntax, absolute or relative, was used to resolve the module ID.

**Comment by markand** [comment]
So you're idea is to save the path in a small association table ? As modSearch receives `module.id` I can maybe store the path that was used to open that file.

**Comment by svaarala** [comment]
Maybe something like that would work? But you'd need to compare the prefix piece by piece to figure out which part "anchors" to a file system path.

Anyway, CommonJS has a certain module ID hierarchy and rules for resolution and it's easy to violate them if you rely on specific meanings to absolute/relative syntax.  For instance, if a module is loaded as `require('foo/bar')`, the following two should map to the same module:

- `require('foo/quux')`  (absolute)
- `require('../quux')`  (relative)

These are easy to break if the resolution process handles IDs differently depending on whether absolute or relative syntax is used.  Not saying it's not useful, though, just that it may be tricky to get seamless.

Anyway, the modSearch() mechanism will be reworked in the next major release to be more flexible and allow things like this.

**Comment by markand** [comment]
Mmmm, I think I may have a solution but it requires to implement my completely own `require` function that does not use modSearch.

The idea:

1. The module request for a global require: `require("net")`
2. This calls the require function, if we find the file, we push its base directory into a stack and call `duk_peval_file`
3. Now, the **net.js** file being processed, it knows where it is thanks to the path stack, if that file request relative modules, it will use the last pushed path from the stack. If it request a global module, we go to step 1 again
4. At the end of the require function, we pop the last pushed path only if we were searching a global module.

Obviously, the most important thing is to clear the path stack if any of the modules fails.

**Comment by markand** [comment]
At the moment, this draft seems to work, some changes may be improved for better paths (cosmetic). And the only one problem is that exports table is shared accross all modules.

````cpp
#include <iostream>
#include <stack>
#include <string>

#include "duktape.h"

using namespace std::string_literals;

std::stack<std::string> paths;

std::string dirName(std::string path)
{
	std::size_t pos;

	pos = path.find_last_of('\\');
	if (pos == std::string::npos) {
		pos = path.find_last_of('/');
	}

	if (pos == std::string::npos) {
		return path;
	}

	return path.substr(0, pos);
}

duk_ret_t require(duk_context *ctx)
{
	const char *id = duk_require_string(ctx, 0);

	/*
	 * 1. Determine if we are top-level require or not, in that case
	 * push "." as the current file path.
	 */
	duk_get_global_string(ctx, "\xff""\xff""require-is-top");
	bool top = duk_get_type(ctx, -1) == DUK_TYPE_UNDEFINED;
	duk_pop(ctx);

	if (top) {
		paths.push("");
	}

	/* Now set the require-top field to false */
	duk_push_boolean(ctx, false);
	duk_put_global_string(ctx, "\xff""\xff""require-is-top");

	/*
	 * 2. Search for the file relatively or absolutely to the global
	 * directories.
	 */
	std::string path;
	if (id[0] == '.') {
		path = paths.top() + id + ".js"s;
	} else {
		/* Normally, we will have several directories to test here */
		path = "C:/Modules/"s + id + ".js"s;
	}

	/*
	 * 3. Push the current path for next require invocation.
	 */
	paths.push(dirName(path) + "/");

	/*
	 * 4. Calls the file, this will recursively go into that function
	 * and use paths we have pushed before.
	 */
	bool failed = false;
	duk_push_object(ctx);
	duk_put_global_string(ctx, "exports");
	if (duk_peval_file(ctx, path.c_str()) != 0) {
		duk_push_error_object(ctx, DUK_ERR_TYPE_ERROR, "failed to open module: %s: %s", path.c_str(), duk_to_string(ctx, -1));
		failed = true;
	} else {
		/* Copy results of exports to an object that we will return and reset global exports (FIX THIS) */
		duk_pop(ctx);
		duk_get_global_string(ctx, "exports");
	}

	/* If top, we are at the absolute end of require() call, empty the paths */
	if (top || failed) {
		while (paths.size() > 0) {
			paths.pop();
		}

		/* Unset the require-is-top bit */
		duk_push_undefined(ctx);
		duk_put_global_string(ctx, "\xff""\xff""require-is-top");
	}

	/* If failed, stop immediately */
	if (failed) {
		duk_throw(ctx);
	}

	return 1;
}

int main(void)
{
	duk_context *ctx = duk_create_heap_default();

	duk_push_c_function(ctx, require, 1);
	duk_put_global_string(ctx, "require");

	if (duk_peval_file(ctx, "test.js") != 0) {
		std::cerr << "failed: " << duk_safe_to_string(ctx, -1) << std::endl;
		std::exit(1);
	}

	return 0;
}
````

**Comment by svaarala** [comment]
Since module loading is now external this is no longer really valid; I think the `extras/module-node` loader should be able to handle this scenario.
