### ISSUE TITLE
SIGSYS on Android using CrystaX NDK

### ISSUE THREAD

**Issue by TheBrokenRail** [svaarala/duktape#1940]
### Test Code
```1+1```

### Expected Result
It ether errors or outputs ```2```.

### Actual Result
```Fatal signal 31 (SIGSYS), code 1 in tid 19176 (enrail.letscode)```

### Test Device
Name: Android Emulator
OS: Android Oreo
Arch: x86_64

### Relevant Android.mk
```
include $(CLEAR_VARS)
LOCAL_MODULE := duktape
LOCAL_SRC_FILES := duktape/duktape.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/duktape
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := jsjni
LOCAL_SRC_FILES := jsjni.c
LOCAL_LDLIBS := -llog
LOCAL_SHARED_LIBRARIES := libduktape
include $(BUILD_SHARED_LIBRARY)
```

### C File
```c
#include "jsjni.h"
#include <android/log.h>
#include <string.h>
#include <pthread.h>
#include "duktape.h"

#define APPNAME "jsjni"
#define LOG(x) __android_log_write(ANDROID_LOG_INFO, APPNAME, (x))

jobject obj;
jclass clz;
JavaVM *vm = 0;

void logStr(char *value) {
    JNIEnv* env;
    (*vm)->AttachCurrentThread(vm, &env, 0);
    jmethodID log = (*env)->GetMethodID(env, clz,
        "log", "(Ljava/lang/String;)V");
    (*env)->CallVoidMethod(env, obj, log, (*env)->NewStringUTF(env, value));
}

void *runJS(void *voidString) {
    const char *nativeString = (char *)voidString;
    duk_context *ctx = duk_create_heap_default();
    if (duk_peval_string(ctx, "'testString'.toUpperCase()") != 0) {
        logStr(strcat("eval failed: ", strcat((char *)duk_safe_to_string(ctx, -1), "\n")));
    } else {
        logStr(strcat("result is: ", strcat((char *)duk_get_string(ctx, -1), "\n")));
    }
    duk_pop(ctx);
    duk_destroy_heap(ctx);
    return NULL;
}

JNIEXPORT jint JNICALL Java_com_thebrokenrail_letscode_javascript_JavascriptWrapper_run(JNIEnv *env, jclass jc, jstring value) {
    const char *nativeString = (*env)->GetStringUTFChars(env, value, JNI_FALSE);
    pthread_t thread;
    pthread_create(&thread, NULL, runJS, (void *)nativeString);
    return 0;
}

JNIEXPORT jint JNICALL Java_com_thebrokenrail_letscode_javascript_JavascriptWrapper_setLog(JNIEnv *env, jclass jc, jobject newObj) {
    clz = (*env)->NewGlobalRef(env, (*env)->GetObjectClass(env, newObj));
    obj = (*env)->NewGlobalRef(env, newObj);
    (*env)->GetJavaVM(env, &vm);
    return 0;
}
```

### Additional Info
CrystaX NDK Version 10.3.2
CrystaX is required for it's Python 3.5 distribution.
It is not an error from acessing the UI thread as the View.post method is used on the Java side.

If it is not possible to fix this can you recomend another open source JavaScript engine that works on Android and the CrystaX NDK, I cannot use V8 or SpiderMonkey as they are incompatible with the CrystaX NDK, and I cannot use JavaScriptCore as it does not have nearly enough documentation.

**Comment by fatcerberus** [comment]
Other people have successfully used Duktape on Android in the past, and anyway it’s made up almost entirely of hardware-agnostic C code (as in no inline asm, etc.) so it’s difficult to say what the problem is.  Perhaps the project maintainer @svaarala has more insight.

**Comment by fatcerberus** [comment]
Some quick Googling indicates that SIGSYS means “bad system call”; the manpage then points to http://man7.org/linux/man-pages/man2/seccomp.2.html; it might be that some syscall is being called which is not permitted by the Android security policy, but unfortunately I have no idea what that call might be.

**Comment by fatcerberus** [comment]
Potentially relevant reference for the above:
https://en.m.wikipedia.org/wiki/Seccomp

Might the CrystaX SDK be enabling this state behind your back...?

**Comment by TheBrokenRail** [comment]
I ended up switching to Mozilla's Rhino to fix the issue.

**Comment by fatcerberus** [comment]
It would be helpful to know the exact line of code this crash occurs on so that we have a better lead on what might be causing the issue.

**Comment by svaarala** [comment]
@TheBrokenRail I've been on vacation so it took me a while to reply -- if for some reason you revisit this issue, I'd suggest you:
- Enable assertions (-DDUK_USE_ASSERTIONS to tools/configure.py)
- Enable debug prints, see http://wiki.duktape.org/HowtoDebugPrints.html

Duktape calls very few platform APIs, and is mainly limited to things like sprintf(), memcpy(), and other string/memory operations, and setjmp/longjmp. One important dependency that might be related is the provider user for the Date built-in - on Android it should be gettimeofday(), gmtime() and similar. In any case all platform function dependencies are provided by `duk_config.h` and are tweakable from there if necessary.

Only one native thread may call into a certain Duktape heap instance at one time; I'm not sure if this could have been an issue in your case or not.

**Comment by fatcerberus** [comment]
From what I've read Oreo has a seccomp filter in place in the app trampoline ("zygote") which disallows certain syscalls (violation leads to SIGSYS).  It just would be helpful to know *which* syscall was the offender.

**Comment by svaarala** [comment]
Right, and that's why the Date provider is a potential culprit, it's one of the very few platform (libc or OS) calls that are likely to cause syscalls. Things like sprintf(), memcpy(), setjmp(), longjmp(), etc should for the most part not be visible to the OS.
