### ISSUE TITLE
Inconstancy in the documentation regarding bytecode obfuscation

### ISSUE THREAD

**Issue by livrish** [svaarala/duktape#1942]
in  https://github.com/svaarala/duktape/blob/master/doc/bytecode.rst
There are two main motivations for using bytecode dump/load:

Performance
Obfuscation
whereas in http://duktape.org/api.html#duk_load_function
"Duktape bytecode format is not intended for obfuscation"
given that obfuscation is the "the action of making something obscure, unclear, or unintelligible"  ??

**Comment by fatcerberus** [comment]
No inconsistency, the first part you quote is speaking generally, saying that *in general* bytecode is used for reasons of performance and obfuscation, while the second quote is saying that Duktape's bytecode dump format *specifically* is not suited for that purpose.

**Comment by svaarala** [comment]
The text is indeed intended as @fatcerberus pointed out - but I can clarify the first occurrence so that it's clear it refers to motivations in general, not motivations behind Duktape bytecode.

**Comment by livrish** [comment]
Sorry didn't mean to sound critical. Great to see the quick responses thanks for the clarification.

**Comment by svaarala** [comment]
@livrish Not at all, I think the critique was spot on. :+1:
