### ISSUE TITLE
RVL for pointer pushed with duk_push_string() ?

### ISSUE THREAD

**Issue by jbmonroe** [svaarala/duktape#1948]
For the sake of discussion, let's say I'm supporting findFiles() in a a tool that uses DukScript, and I'm going to push back the results as a '|' delimited string that's a std::string in the C++ implementation.  

```
.
.
.
duk_push_string(ctx,fileList.c_str());
return 1;
```
Do I need to persist that std::string so that the JavaScript caller gets the returned string, or does the API make a complete copy of the string internally so that I can allow the std::string to destruct at the end of the function?

**Comment by fatcerberus** [comment]
Duktape interns the string so you can do whatever you want with it afterwards.  A rule of thumb that I’ve found holds pretty consistently in C libraries is that if an API takes a `const char*` then you don’t have to keep the pointer around afterwards.

**Comment by svaarala** [comment]
All string push operations make a copy of the input string as part of interning the string. So when such an API call returns, the string is no longer referenced by Duktape. This is the case for both constant strings (const char *) and non-constant strings (char *).

**Comment by fatcerberus** [comment]
@svaarala Out of curiosity, which Duktape APIs accept non-const strings?  In most cases you would only take a `char*` if you wanted to mutate the original string, a la `strcat()`.  I didn’t think Duktape had any such functions.

**Comment by svaarala** [comment]
Suppose you build a string in C code by decoding ISO-8859-1 and then encoding into UTF-8. Then that string was pushed using `duk_push_string()`. The argument in this case couldn't be a constant string because it's formed on the fly.

The Duktape API prototype uses `const char *` to signify that *Duktape* won't mutate the input string. But the input can well be a non-constant string as well. This applies across the whole API, there's no practical difference from Duktape point of view between a constant and non-constant string because Duktape won't change the input string in any case.

**Comment by fatcerberus** [comment]
Yes, I understood that, it was just your wording above seemed to imply that there were some Duktape APIs declared to take a non-const string.

**Comment by svaarala** [comment]
Right, I meant that this is the case for both `const char *` and `char *` strings before they are given to Duktape (and thus effectively cast to `const char *`). So the input string doesn't have to be a constant string.

**Comment by svaarala** [comment]
So specifically:
> Out of curiosity, which Duktape APIs accept non-const strings?

All APIs accept non-const strings, but they are cast to `const char *` and not modified by Duktape.

**Comment by fatcerberus** [comment]
Sorry, confusion stemmed from exactly what you describe - there’s no difference from the callee’s point of view between a const and non-const string as the API is already declared to accept const.  So you making the point that it’s true for both types seemed to go without saying and I then figured maybe it to meant something else...

Dangers of being *too* familiar with the C language, I guess. :)

**Comment by fatcerberus** [comment]
Oops, sorry for derailing your thread @jbmonroe.

**Comment by svaarala** [comment]
Re: the API containing calls accepting a `char *`, I don't think there are any such calls. For buffers the data pointer is generally `void *`. The debugger read callback does seem to use a `char *buffer` for the read buffer argument though.

**Comment by jbmonroe** [comment]
@fatcerberus Not a problem.  What you brought up is good to know, too.

@svaarala Thanks--got it.  There are some values I'm caching internally so that repeat calls don't have to go through the grind to get the value--but a file find result wouldn't be one of those.
