### ISSUE TITLE
Array memory leak

### ISSUE THREAD

**Issue by sazlang** [svaarala/duktape#1957]
In the beginning, program only used 0.4Mb. I pushed 15 million string to empty array. Then memory go up to 700MB. I set array to null and memory fell to 60MB.

```
var a = []; // memory: 0.4MB
for(int i = 0; i < 15000000; i++)
  a.push("hello world " + i);

// memory: 700MB
a = null;
// memory: 60MB
```

What am I doing wrong? Why garbage collector doesn't deallocate my array?
_Note: I used cmdline example._

**Comment by svaarala** [comment]
How are you measuring memory usage? Note that when a libc implementation allocates memory and the memory is later freed, the allocated pages may not be unmapped by the libc implementation so the OS may report higher memory usage than prior to the test.

The above example with valgrind, smaller loop size to avoid valgrind memory issues:
```
$ cat /tmp/test.js
var a = [];
for(var i = 0; i < 150000; i++)
  a.push("hello world " + i);
a = null;

$ valgrind duktape/duk.230 /tmp/test.js
==4865== Memcheck, a memory error detector
==4865== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4865== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4865== Command: duktape/duk.230 /tmp/test.js
==4865== 
==4865== 
==4865== HEAP SUMMARY:
==4865==     in use at exit: 0 bytes in 0 blocks
==4865==   total heap usage: 452,958 allocs, 452,958 frees, 49,135,852 bytes allocated
==4865== 
==4865== All heap blocks were freed -- no leaks are possible
==4865== 
==4865== For counts of detected and suppressed errors, rerun with: -v
==4865== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by sazlang** [comment]
Oh. You are right. I measured memory with Task Manager. Sorry for that :)
