### ISSUE TITLE
Is it possible to create a heap/context snapshot?

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#1960]
Hi,

I usually execute repetitive tasks with DukTape: Create the heap object, add some global functions and variables, and run some code.

Because the code being executed varies I would like to "cache" or take a snapshot of a context with global functions and variables loaded expecting I can improve initialization speed.

Is it possible to dump the current state and load it in another heap?

Regards,
Mauro.

**Comment by svaarala** [comment]
Hi @mxmauro,

It's not possible at present: serializing an object graph with possibly related native resources is not a trivial problem because one needs the ability to serialize and deserialize some values in a special way (think of e.g. opened files). A limited solution where a subset of possible values could be serialized would be possible e.g. if limited in such a way that the serialization wouldn't need to work across a software restart.

**Comment by mxmauro** [comment]
Hi @svaarala , thanks for answering.

I'll check if I can redesign the code and use coroutines.

Regards.

**Comment by svaarala** [comment]
Just out of curiosity, could you list the value types your initialized heap would contain? E.g.
- Native functions (Duktape/C functions)?
- Custom Ecmascript functions?
- Native objects with allocated state (e.g. an initialized socket or database handle)?

**Comment by mxmauro** [comment]
For most of work I do this:

1. Define several global constants to match some C++ values like `S_OK`, `E_FAIL` to noun some.
2. Define some C functions like `connectToMySQL`, `outputDebugString()`, `exit()`... mostly helper functions. The former returns a JS object which has its implementation in C++.

     For e.g., I do `var mysql = connectToMySql()` and then `var data = mysql.queryAndFetchRow("SELECT ....");`. For `exit` basically I throw an exception with a specific content I handle after the call to `duk_safe_call`.
3. I also define a `MySqlError` which is derived from `WindowsError`, which in turn it is derived from `Error` object in both, C++ and Javascript side.

At this point, is when I would do the snapshot because next actions depends on the routine I must run.

My repository is private but if you need access on how I build the interaction between C++ and JS, feel free to ask.

Regards.
