### ISSUE TITLE
Exiting current pcall

### ISSUE THREAD

**Issue by arabine** [svaarala/duktape#1961]
Is it possible to exit a pcall from a C defined function. Eg, let's have the following Javascript:

```
function MyTest() {
      aJavascriptfFunction();
     
    cDefinedFunction();  // Inside this C defined function, I want to exit from MyTest if something goes wrong
   
      aNotherJavascriptfFunction(); // not want to execute this if the previous function has failed
}
```

On the C side, I called
```
int rc = duk_pcall(ctx, 0); // exit from that call if any sub functions has been problematic
```

Is there a duk_xxx function to do that? I tried several mechanisms including exceptions, without success.

**Comment by fatcerberus** [comment]
You can throw an error (see `duk_throw()`) but that’s about it.  The C call is just an extension of the normal flow of JS execution, so you’re basically asking “how do I return from multiple levels of function calls at once?” which is non-trivial.

**Comment by arabine** [comment]
Yes, I wanted this behavior; I will ask it for Christmass.

Meanwhile, I managed to get what I wanted:
1. _Without_ enable C++ exceptions, it generates a whole application crash that I am not able to catch.
2. return DUK_RET_ERROR; from my C Code, thank you wonderful documentation :)

In that way the pcall() returns without success, exactly what I want. I love Duktape.

**Comment by fatcerberus** [comment]
“Returning from multiple functions at once” is pretty much what exceptions are for.  By returning `DUK_RET_ERROR` this is essentially shorthand for throwing an equivalent exception using `duk_throw()` or `duk_error()`, so I don’t understand why the latter didn’t work for you.

**Comment by arabine** [comment]
Indeed I now understand that it is the same, duk_throw() didn't work because I enabled DUK_USE_CPP_EXCEPTIONS.

Unfortunately I was excepted to have something like this in the user code: 

```
try {
     pcal();
} catch( std::runtime_error &e) {
}
```

By reading the doc, it seems that the exception option is only to transform into JS an exception in a Duktape/C function, which is not exactly what I want.

**Comment by svaarala** [comment]
When you enable DUK_USE_CPP_EXCEPTIONS it doesn't change the way errors are handled in the Duktape API: you still use duk_pcall() (and its variants) and check the error code. C++ exceptions are used strictly internally to perform the long control transfer (from the throw site to the catch site) in a way that unwinds the C stack that supports automatic destructors etc. That internal exception, `duk_internal_exception` is not normally visible or caught by application code, and for that reason it also doesn't inherit from any standard exception class (to discourage trying to catch it).

**Comment by svaarala** [comment]
So as a concrete example, regardless of whether DUK_USE_CPP_EXCEPTIONS is enabled, one would:
```
if (duk_pcall(...) == DUK_EXEC_SUCCESS) {
    printf("success!\n);
} else {
    printf("failure: %s\n", duk_safe_to_string(ctx, -1));
}
duk_pop(ctx);
```

and in the throw site, one could e.g. use:
```
duk_type_error(ctx, "aiee");
```

The only concrete application-visible effect of DUK_USE_CPP_EXCEPTIONS is that when the C stack is unwound between the throw site and the catch site (duk_pcall), the stack unwinding is C++ aware and supports automatic destructors etc.

**Comment by arabine** [comment]
Ok that's clear, I had mis-understanding the documentation, but with this option turned on I always had exception raised and application crash (MinGW on Windows).

**Comment by svaarala** [comment]
Hmm, so with DUK_USE_CPP_EXCEPTIONS a duk_pcall() + duk_error() leads to a crash in your setup? What kind of crash, is there any useful information about the cause?

**Comment by svaarala** [comment]
@arabine Any updates?

**Comment by arabine** [comment]
No, I have to find time to give you a simple example of this use case, can you hold on this ticket a bit?

**Comment by svaarala** [comment]
Sure, no hurry, I was just trying to clean up some unnecessarily hanging issues.

**Comment by svaarala** [comment]
Good to hear that the cause was found :) Can you describe what fix you concretely applied; a gcc option?
