### ISSUE TITLE
Freeze in code

### ISSUE THREAD

**Issue by dejan994** [svaarala/duktape#1962]
Hello, i'm trying to blink a led on a microcontroller TI cc2538, but it just freezes. This is my code:

     duk_context *ctx = duk_create_heap_default();
    
     duk_push_c_function(ctx, js_HalLedSet, DUK_VARARGS);
     duk_put_global_string(ctx, "LedMode");
     duk_peval_string(ctx, "LedMode()");
     duk_call(ctx,1);
     duk_pop(ctx);  
     duk_destroy_heap(ctx);

I think the code freezes on second line, but i have no idea how to debug it.

**Comment by svaarala** [comment]
Could add debug prints between the Duktape calls, and any statements in js_HalLedSet() to see where the freeze occurs?

**Comment by dejan994** [comment]
I tried running through the first line only and it didn't freeze, however it froze when i added second line. In js_HalLedSet i did put a function for led blinking (it works normally without duktape).

**Comment by svaarala** [comment]
What do you mean by second line? The second line in your example is empty :)

**Comment by dejan994** [comment]
I meant  duk_push_c_function(ctx, js_HalLedSet, DUK_VARARGS); 

My bad :)

**Comment by svaarala** [comment]
One thing you could try is:
```
$ python tools/configure.py --output-directory /tmp/out -DDUK_USE_ASSERTIONS -DDUK_USE_SELF_TESTS
```

and then compiling your application with the headers and sources in /tmp/out.

Sometimes microcontroller platforms have broken implementations for some IEEE math like `fmod()`. The self tests should catch some of the common cases.

**Comment by dejan994** [comment]
I am on windows, is there any way to execute that code on windows? Like Cygwin64 or something?

**Comment by svaarala** [comment]
Any python2 command, with `python-yaml` package installed, should work.

**Comment by dejan994** [comment]
I'll try it, thank you for your time!

**Comment by svaarala** [comment]
@dejan994 Any updates?

**Comment by dejan994** [comment]
Hey, i forgot i made this thread. It's solved in another one, you can close this one. Thanks!
