### ISSUE TITLE
Large lookup tables in duktape.c

### ISSUE THREAD

**Issue by sazlang** [svaarala/duktape#1964]
I noticed that there are some very large lookup arrays in source. For example size of the `duk_unicode_re_canon_lookup` array is nearly 132Kilobyte. What is it for?

**Comment by sazlang** [comment]
Hmm, I think it is used for case-insensitive regex.

**Comment by fatcerberus** [comment]
For the most part those large arrays are autogenerated from a more human-readable source when a distribution is built.  They aren’t meant to be maintained in place (thankfully :P).

**Comment by svaarala** [comment]
There are automatically generated tables for e.g. Unicode operations (case conversion, various character class recognizers, etc) and for built-in objects and strings.

The Unicode tables are bit-packed to optimize footprint. That 128kB table is a Unicode case canonicalization table which is disabled by default. It can be enabled using DUK_USE_REGEXP_CANON_WORKAROUND to speed up case insensitive regexp operations for environments where their performance is very important and the large 128kB overhead is an OK trade-off. The other tables are quite a bit smaller because they're size, rather than performance, optimized.

**Comment by svaarala** [comment]
Some of the other (smaller) tables include:
```
/* Recognizing character classes like identifier start, identifier part */
extern const duk_uint8_t duk_unicode_ids_noa[1063];
extern const duk_uint8_t duk_unicode_ids_m_let_noa[42];
extern const duk_uint8_t duk_unicode_idp_m_ids_noa[549];

/* Unicode case conversion */
extern const duk_uint8_t duk_unicode_caseconv_uc[1386];
extern const duk_uint8_t duk_unicode_caseconv_lc[680];

/* Unicode case normalization helper, enabled by default */
extern const duk_uint8_t duk_unicode_re_canon_bitmap[256];

/* Some RegExp character class ranges */
DUK_INTERNAL_DECL const duk_uint16_t duk_unicode_re_ranges_digit[2];
DUK_INTERNAL_DECL const duk_uint16_t duk_unicode_re_ranges_white[22];
DUK_INTERNAL_DECL const duk_uint16_t duk_unicode_re_ranges_wordchar[8];
DUK_INTERNAL_DECL const duk_uint16_t duk_unicode_re_ranges_not_digit[4];
DUK_INTERNAL_DECL const duk_uint16_t duk_unicode_re_ranges_not_white[24];
DUK_INTERNAL_DECL const duk_uint16_t duk_unicode_re_ranges_not_wordchar[10];

/* Fast path table for identity character lookup in ASCII range */
DUK_INTERNAL_DECL const duk_int8_t duk_is_idchar_tab[128];

/* Built-in object and string initialization data. */
DUK_INTERNAL const duk_uint8_t duk_builtins_data[4116];
DUK_INTERNAL_DECL const duk_uint8_t duk_strings_data[967];
```

All in all, the other tables account for ~10kB of footprint.

**Comment by svaarala** [comment]
@sazlang If you're generally interested in footprint, you should check https://github.com/svaarala/duktape/blob/master/doc/low-memory.rst which covers a lot of low-memory related topics.

For these init tables specifically, you can reduce their size (from ~10kB) via:
- Removing built-in objects or methods you don't need, e.g. if you're content with ES5.1 the post-ES5.1 objects like typed arrays can be removed.
- Using a subset of the standard Unicode tables. This is often acceptable in embedded environments. The `tools/configure.py` utility accepts custom Unicode data which is then used to create the much smaller tables. Here are examples of Unicode tables pruned for 8-bit characters only:
https://github.com/svaarala/duktape/blob/master/src-input/UnicodeData-8bit.txt, https://github.com/svaarala/duktape/blob/master/src-input/SpecialCasing-8bit.txt.

Various other aspects are described in that low memory document.

**Comment by svaarala** [comment]
SpecialCasing lists Unicode codepoints which don't obey the regular casing rules (which are described in the main unicode data file).

For U+00DF (LATIN SMALL LETTER SHARP S), with more surrounding original comments:

```
# <code>; <lower>; <title>; <upper>; (<condition_list>;)? # <comment>
[ ...]

# The German es-zed is special--the normal mapping is to SS.
# Note: the titlecase should never occur in practice. It is equal to titlecase(uppercase(<es-zed>))

00DF; 00DF; 0053 0073; 0053 0053; # LATIN SMALL LETTER SHARP S
```

So for example:
```
duk> print('\u00df')
ß
duk> print('\u00df'.toUpperCase())
SS
```

Here the speciality is that a single codepoint upper cases to two codepoints.

Other Unicode code points within the 8-bit range are regular and thus not listed in SpecialCasing.
