### ISSUE TITLE
ClearBlade uses duktape

### ISSUE THREAD

**Issue by aallsbrook** [svaarala/duktape#1966]
Per the note at the bottom of https://wiki.duktape.org/ProjectsUsingDuktape.html

https://www.clearblade.com IoT Cloud and Edge Platform uses duktape for it's microservice runtime wrapped with cgo

**Comment by svaarala** [comment]
Thanks @aallsbrook, I'll update the Wiki :+1:

**Comment by svaarala** [comment]
https://github.com/svaarala/duktape-wiki/pull/208
