### ISSUE TITLE
Duktape working on bare metal, but not when integrated into OSAL system

### ISSUE THREAD

**Issue by dejan994** [svaarala/duktape#1971]
Hello, 

I'm using TI CC2538 with OSAL and Z-Stack in it. It has 512KB flash and 32KB RAM. I want to implement Duktape into Zigbee Z-Stack. When i try it on bare metal example (ADC temp reading through UART), it works flawlessly, but when i want to implement it into Z-Stack, i run into issues. My code looks like this:

duk_context *ctx = duk_create_heap_default();
      if (ctx) {
    / * success * /
        duk_push_c_lightfunc(ctx, js_HalLedSet, DUK_VARARGS,1,0/ *nargs* /);
        duk_put_global_string(ctx, "Led");
        duk_eval_string(ctx,"Led();");
    / * ... after heap is no longer needed: * /
        duk_destroy_heap(ctx);
    } else {
      / * not successful in creating heap * /
      HalLedSet( HAL_LED_ALL, HAL_LED_MODE_TOGGLE);
}

It always goes into else statement, and then goes back to duk_context *ctx = duk_create_heap_default();
It never manages to create_heap i guess.
I had other problems too, such as FaultISR infinite loop etc. Does anyone have an idea what might be wrong? Thanks in advance!

**Comment by svaarala** [comment]
If your footprint allows it, you could enable debug prints (https://wiki.duktape.org/HowtoDebugPrints.html) which may give a clue; running out of memory is a likely candidate.

For 32kB RAM you'll probably need to move built-in objects into ROM (see https://github.com/svaarala/duktape/blob/master/doc/low-memory.rst). You may need to implement a pooled allocator to minimize the effect of fragmentation (unless the platform allocator already does this). With built-ins moved into ROM Duktape starts up with a RAM footprint of a few kB.

**Comment by dejan994** [comment]
I already minimized configuration with everything there is to minimize. 

By pooled allocator , do you mean i should make duktape use same allocation memory as OSAL is using?

**Comment by svaarala** [comment]
To be sure, are you using the ROM built-in options?

By pooled allocator I mean that you can provide custom allocation functions for Duktape to use. For very low memory targets it's typical to use an allocator that handles small allocations (such as string objects, object headers, etc) efficiently without fragmenting a free list. I don't know the platform so I don't know what kind of allocator it uses.

One simple step would be to provide custom allocation functions which would just pass along the requests but console dump them. You'd then more easily see if some allocation failed.

**Comment by svaarala** [comment]
Sounds good, it'd be helpful to hear what allocations are made and whether they succeed or not.

Do you know how much stack is available? That might another potential issue.

**Comment by fatcerberus** [comment]
512 bytes is an extremely tiny amount of stack space.  If that’s accurate, I’m willing to hazard a guess that’s where your issue is - you’re smashing the stack.

**Comment by dejan994** [comment]
If i increase stack size, i have to reduce heap size unfortunately.

**Comment by dejan994** [comment]
Alright, good news. I create custom realloct function and changed default malloc to osal_mem_alloc. Code:

 duk_context *ctx = duk_create_heap_default();
      if (ctx) {
    /* success */
        duk_push_c_function(ctx, js_HalLedSet, DUK_VARARGS);
        duk_put_global_string(ctx, "Led");
        duk_peval_string_noresult(ctx,"Led();");
        
    /* ... after heap is no longer needed: */
        duk_destroy_heap(ctx);
    } else {
      /* not successful in creating heap */
      HalLedSet( HAL_LED_1, HAL_LED_MODE_TOGGLE);
}


It works now fully, but it won't go into js_HalLedSet when i call function  duk_peval_string_noresult(ctx,"Led();");

It just goes from there to destroy_heap after i set breakpoint. I don't know how to debug it, since there are not problems in stack trace.

**Comment by svaarala** [comment]
I'd suggest you try extending the native stack and see if that fixes the issue. The amount of native stack required by most operations is not large, but there are unfortunately some operations that require more than 512 bytes (e.g. float<->string conversions).

**Comment by dejan994** [comment]
I tried it, i put stack size on 1024 and 1500 bytes, and the same thing happens, it won't execute duk_ret_t function. The problem is, when i put stack on 1500, i have to reduce heap to under 2KB.

**Comment by svaarala** [comment]
If you have a total of 3.5kB free RAM for heap and stack, I'm afraid it'll be difficult to run anything useful :-/

**Comment by fatcerberus** [comment]
As an amusing aside, this project reminds me so much of the time I coaxed Windows 3.1 into running (and booting!) from a 3.5” floppy.  It was the most stripped-down Windows installation ever but it did work! :smile:

**Comment by dejan994** [comment]
Good news, i managed to expand stack and heap dramatically. 

Can you tell me how can i use DUK_DPRINT, DUK_DDPRINT, and DUK_DDDPRINT to print into debug log when debugging, it would be extremely helpful.

**Comment by svaarala** [comment]
Good to hear! For debug prints, see https://wiki.duktape.org/HowtoDebugPrints.html.

**Comment by dejan994** [comment]
I can't seem to make it work, when i try to put example:

#define DUK_USE_DEBUG_WRITE(level,file,line,func,msg) do { \
        fprintf(stderr, "D%ld %s:%d (%s): %s\n", \
                (long) (level), (file), (long) (line), (func), (msg));
    } while (0)

It says expected a declaration

**Comment by svaarala** [comment]
You would put that into your `duk_config.h` either manually (look for any existing definition and change it) or via tools/configure.py, see the `--fixup-file` option.

**Comment by dejan994** [comment]
Yeah i put it into duk_config.h and it throws expected a declaration on last line where while is.

**Comment by brodybits** [comment]
If a `#define` statement needs multiple line you have to put a backslash (`\`) at the end of each line, except for the last, as you can see in the sample. So I would suggest you rework `#define DUK_USE_DEBUG_WRITE` as follows:

```c
#define DUK_USE_DEBUG_WRITE(level,file,line,func,msg) do { \
    fprintf(stderr, "D%ld %s:%d (%s): %s\n", \
    (long) (level), (file), (long) (line), (func), (msg)); \
} while (0)
```

**Comment by dejan994** [comment]
Wow, i didn't know it, since i didn't type my code in multiple lines, thank you! Now it gives me another error...

`Error[Pe020]: identifier "msg" is undefined `

**Comment by dejan994** [comment]
Good news! My code is up and running now, however, it runs only in debug mode. I wonder why...

**Comment by dejan994** [comment]
Alright, so far so good. Is there a way to load .js files with newer versions of the duktape?

Cheers, and thank you for enormous help you gave me.

**Comment by svaarala** [comment]
@dejan994 You can just push a string using duk_push_(l)string() and then use duk_compile() + duk_pcall() for example (or duk_peval() if you just want to eval the files). You'll need to implement the file loading part because Duktape avoids dependencies on platform I/O.

**Comment by dejan994** [comment]
I see, i'll try to keep it portable and make local uart functions to write a script. I have another question tho.
If i want to pass an argument in a script, for example turning LED on or off. 
`led_function ("On")`

How do i make this in c function, i'm kinda confused.

**Comment by svaarala** [comment]
Let's suppose `led_function` is a property in the global object:
```c
duk_get_global_string(ctx, "led_function");  /* -> [ ... led_function ] */
duk_push_string(ctx, "On");  /* -> [ ... led_function "On" ] */
duk_call(ctx, 1);  /* -> [ ... return_value ] */
```

And if there's no safe call or pcall wrapper for this, use duk_pcall() instead.

**Comment by dejan994** [comment]
I'm trying to make it look like this:

`duk_ret_t led_function(ctx)
{
  // some code which can recognize an string argument for on and off

  if (string == "On") 
    LedOn();
  if (string == "Off")
    LedOff();
}`

I'm just trying to push that duk_ret_t and then eval it with a script which says `led_function ("On")` or `led_function ("Off")`

**Comment by svaarala** [comment]
You would then do something like:
```c
duk_ret_t led_function(duk_context *ctx)
{
    const char *arg = duk_require_string(ctx, 0);
    if (strcmp(arg, "On") == 0) {
        LedOn();
    } else if (strcmp(arg, "Off") == 0) {
        LedOff();
    }
}
```

**Comment by dejan994** [comment]
That's exactly what i needed, thank you so much!

**Comment by dejan994** [comment]
I'm sorry, but i have one more question. If i want to make c function which returns true or false, and represent it in script like this:

if (keyPressed == true) 
{
//do something
}
else if (keyPressed == false)
{
//do something
}

How should my c binding function look like?

**Comment by svaarala** [comment]
Assuming `keyPressed` is zero for false and non-zero for true:
```c
int keyPressed = <something>;
duk_push_boolean(ctx, keyPressed);
return 1;
```

In Ecmascript code this would then return `true` or `false`.

**Comment by dejan994** [comment]
I see, let me try writing this more understandably. I have 2 parameters: `key_pressed` and `key_released`
So i want to make a function which returns true in Ecmascript if `key_pressed `is true, and returns false if `key_released `is true.

**Comment by svaarala** [comment]
And what if neither is true, or both are true?

**Comment by dejan994** [comment]
Yeah that was the problem, so i did it with one keyPressed only. I made it, and it works with some hiccups, resolving it right now. Thank you again!

**Comment by dejan994** [comment]
I have another problem i cannot resolve. I have multiple function for multiple keys. My Ecmascript code looks like this:
```

if(Key1()) {
  TurnLed1('ON');
}
else  {
  TurnLed1('OFF');
}

if(Key2()) {
  TurnLed2('ON');
}
else  {
  TurnLed2('OFF');
}
```

The problem is, only first if works, for the first key. If i change places and put key 2 first, then only key 2 works. I cannot debug ecmascript, so i cant resolve it.
Edit: sometimes even key 2 works, but at random.

**Comment by svaarala** [comment]
@dejan994 Unfortunately it's very difficult to give any advise based on just that description.
