### ISSUE TITLE
share: build tiny exe for win32

### ISSUE THREAD

**Issue by wanjochan** [svaarala/duktape#1974]
Just want to share if any one want a tiny exe of duktape for win32 size around 400KB and less than 120KB after upx, here is a example for reference:

```
docker run -v `pwd`:/work/ -w /work/ -ti cmptech/docker_tinycc_dev i386-win32-tcc -DDUK_F_MINT -o eval.exe examples/eval/eval.c src/duktape.c -I src
```

**Comment by svaarala** [comment]
Why is DUK_F_MINT forced on the command line?

**Comment by wanjochan** [comment]
it will report the function not found for "cbrt" and "log2" on the tcc-win32, let's say it's a quick pass

**Comment by svaarala** [comment]
Does "tcc" refer to TinyCC here?

Regardless of that, if there is a good preprocessor condition for your environment, it could be added here:
- https://github.com/svaarala/duktape/blob/master/config/header-snippets/platform_fillins.h.in#L271-L290

**Comment by wanjochan** [comment]
you are right, but i just want to touch no codes to make the great baby run ;)

**Comment by svaarala** [comment]
@wanjochan Hehe :) If you can confirm your environment and the proper preprocessor detection check, I can add it to the exception :)

**Comment by svaarala** [comment]
@wanjochan Any update on this issue?
