### ISSUE TITLE
Append CargoWebServer to the list of your application user.

### ISSUE THREAD

**Issue by davecourtois** [svaarala/duktape#1975]
Hello Duktape,
I'm proud to tell you that I successfully integrate your engine in Golang in a different way than GoDuktape was doing it. My way is inspired by Otto a js engine written in Golang. Here is the test file as example of how user can use (duktape/chakracore/jerryscript) in go. I think my api is simple and really link Go and JS. You can access js object and function from go or access go function and object from js... Each interpreter run in it own process and communicate via tcp socket with the application that made use of it, it's isolate the client application from JS error and crash.

Get a look i think you will be proud of what duktape can do in Go...

**Comment by davecourtois** [comment]
This is the link to the go test unit
https://github.com/CargoWebServer/CargoWebServer/blob/master/Project/src/code.myceliUs.com/GoJavaScript/GoJavaScriptTest/GoJavaScript_test.go

**Comment by svaarala** [comment]
@davecourtois Hmm, so for the project list link:
- Should the project name be "CargoWebServer" and link to https://github.com/CargoWebServer/CargoWebServer (or maybe http://cargowebserver.com/ )?
- Could you provide a short description, i.e. what is Duktape used for in the project (see the other entries)?

**Comment by davecourtois** [comment]
Hi Sami,
thank first of all thank your for the answer and also for creating
Duktape!-) I really appreciated the quality of your JS engine, it's
compact, fast and easy to compile in all platform. I also appreciate your
devotion to other open source project even the one who compete with your
own project, that's the true spirit of open source movement and I wish the
best to you and Duktape. Because of it's quality I'm please to tell you
that it will be the engine by default in CargoWebServer, I also integrate
Chakra and JerryScript but I was unable to compile it in windows and they
also need external library compiling to make them work. Your engine compile
successfully by  cgo so no work is needed to make it work with go.
CargoWebSever is a complete web application framework with it own data
store (entity manager) and it own ide named Bridge there is some
screenshot.

[image: image.png]
This is the code editor, it support multi-user coding like google doc.

[image: image.png]
the entity editor

[image: image.png]
the search engine, i made use of xapian.

[image: image.png]
the query editor, (entity query) it also support SQL.

there is also LDAP, OAUTH2, SQL, Session and user management ...

All the server is written in go because of it high performance and it
concurrency model. Application and user sessions has their own JS engine
running in their own process, it possible to run JS engine in distant
computer...
The sub-project name GoJavaScript is an engine container. The engine is
running in it process and communicate via a TCP socket with the client side
who is see as a library in the client side, it's a kind of minimalist
node.js.
GoJavaScript can do what Otto, a native go js engine can do. So with
GoJavaScript Duktape became very useful and simple to use in go
application. CargoWebServer is a huge piece of code that made heavy use of
JS and
it work very well with Duktape so I think GoJavascript can be use
confidently by go project who need Javascript.

Now to ask about what to wrote in the description...
- The link must be  https://github.com/CargoWebServer/CargoWebServer
- Now the decription; A Javascript web application framework written in Go.

Again thank you for your interest!-)
best regard Dave Courtois

Le sam. 15 sept. 2018 à 16:53, Sami Vaarala <notifications@github.com> a
écrit :

**Comment by svaarala** [comment]
Thanks @davecourtois, you're quite welcome! Good to hear things worked out with the integration.

I'll add the project link and keep Cargo in mind for future use :-)

**Comment by svaarala** [comment]
https://github.com/svaarala/duktape-wiki/pull/210
