### ISSUE TITLE
What do I do with the push ECMAScript function?

### ISSUE THREAD

**Issue by ZhiYiDai** [svaarala/duktape#1977]
I received a ECMAScript function that I wanted to push into a new thread

**Comment by svaarala** [comment]
Do you mean that you have received a function object in the Duktape value stack, and want to move it to another thread?

If so, where in that thread -- in its value stack?

If these are the case, you can use https://duktape.org/api.html#duk_xcopy_top and https://duktape.org/api.html#duk_xmove_top to move data between value stacks.

**Comment by ZhiYiDai** [comment]
Thank you very much for helping me solve the problem.

**Comment by ZhiYiDai** [comment]
I use this method to implement multi-thread 
Example:
```
js code
Thread.start (function(){print('children Thread test')};
print (' hello ');

c code
void *script_children_thread(void *arg)
{
    duk_context *ctx = (duk_context *)arg;
    duk_idx_t nargs = duk_get_top(ctx);
    duk_call(ctx,nargs-1);
    duk_pop(ctx);
    return 0;
}

static duk_ret_t  threadStart(duk_context *ctx)
{
    duk_idx_t nargs = duk_get_top(ctx);
    duk_idx_t thr_idx;
    duk_context *new_ctx;
    thr_idx=duk_push_thread(ctx);
    new_ctx = duk_get_context(ctx, thr_idx);
    duk_pop(ctx);
    duk_require_stack(new_ctx, nargs);
    duk_xmove_top(new_ctx, ctx, nargs);
    pthread_t tid;
    pthread_create(&tid, NULL, script_children_thread, new_ctx);
    return 1;
}
```

Do you have any better Suggestions?

**Comment by svaarala** [comment]
As long as the native threads never call into Duktape at the same time (prevented e.g. via a global mutex), that should be feasible. A more fine grained solution which allows running other threads while on thread blocks is to use a mutex combined with duk_suspend/duk_resume.

**Comment by ZhiYiDai** [comment]
How do you enable Promise?, I did not find relevant instructions in API doc.

**Comment by ZhiYiDai** [comment]
I require bluebird. Js to display "Error: No async scheduler available".

**Comment by svaarala** [comment]
There's no built-in Promise support yet. You can use https://github.com/svaarala/duktape/blob/master/polyfills/promise.js or another polyfill like Bluebird.

For the Bluebird issue, you need some way of running the Promise jobs. For example Bluebird tests use this: https://github.com/svaarala/duktape/blob/master/util/bluebird-test-shim.js. Bluebird provides a direct API to provide a scheduler, see http://bluebirdjs.com/docs/api/promise.setscheduler.html.

**Comment by ZhiYiDai** [comment]
So what else do I need to set up? Why display "not configurable"

**Comment by svaarala** [comment]
I don't know - could you attach a traceback? The message alone doesn't really help that much.

**Comment by ZhiYiDai** [comment]
Sorry, my English is poor.
I use the following test example
https://github.com/svaarala/duktape/blob/26f00693780c976b4e490af68c022bccba9d80c0/tests/ecmascript/test-bi-promise-constructor-all-reject.js
The resolve function cannot be executed as a result.
There is no output of 'fulfill' or 'fulfill'.

**Comment by ZhiYiDai** [comment]
![sf](https://user-images.githubusercontent.com/17697008/45830424-a8ecbd80-bd2f-11e8-844f-7453a22d1168.png)

**Comment by svaarala** [comment]
Are you running Promise.runQueue() to trigger the promise jobs (see the polyfill)?

**Comment by svaarala** [comment]
@ZhiYiDai Any update on this issue?

**Comment by ZhiYiDai** [comment]
Thank you, my problem has been solved, I can close the issue.
