### ISSUE TITLE
Object.getOwnPropertySymbols([1, 2, 3]) returns ['0', '1', '2']

### ISSUE THREAD

**Issue by neoniousTR** [svaarala/duktape#1978]
Problem popped up in our project low.js:

Object.getOwnPropertySymbols([1, 2, 3]) returns ['0', '1', '2']

This does not seem to be the correct behaviour, it should return [], because the array items are not symbols. Both Firefox and Node return [].

**Comment by svaarala** [comment]
@neoniousTR Thanks, this is clearly a bug. I'll open a fix pull shortly.

**Comment by svaarala** [comment]
The issue also affected a plain String and a typed array argument.
