### ISSUE TITLE
Janus optionally uses Duktape since release 0.4.4

### ISSUE THREAD

**Issue by jonassmedegaard** [svaarala/duktape#1986]
Janus has grown a Duktape plugin since 0.4.4 just released:
https://github.com/meetecho/janus-gateway/commit/48a779da

**Comment by svaarala** [comment]
What would be a good oneliner "Using Duktape for..."?

**Comment by jonassmedegaard** [comment]
Quoting Sami Vaarala (2018-11-01 08:33:49)
> What would be a good oneliner "Using Duktape for..."?

Using Duktape for a scripting interface to the Janus WebRTC Server

Official webpage for the Janus Duktape plugin is 
https://janus.conf.meetecho.com/docs/duktape.html but arguably it is 
better introduced at https://github.com/meetecho/janus-gateway/pull/1264 
(and predecessor at https://github.com/meetecho/janus-gateway/pull/1033)

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by svaarala** [comment]
Sorry that it took a bit, but here it is:https://github.com/svaarala/duktape-wiki/pull/214. It should be live in ~24h. Thanks! :)
