### ISSUE TITLE
Documentation: Example Babel configuration that doesn't transpile things supported natively

### ISSUE THREAD

**Issue by lll000111** [svaarala/duktape#1988]
The subject says it. Since this runtime supports a few "post ES5" features natively a standard Babel configuration that transpiles everything would be wasteful. What would be the most optimal Babel (7) configuration? I think this should be part of the documentation.

Link to https://github.com/neonious/lowjs/issues/15

**Comment by fatcerberus** [comment]
I don’t think transpiling everything is as wasteful as you imagine.  As far as syntax, the only post-ES5 thing I believe is supported is the exponentiation operator `**`.  Otherwise it’s just some ES6+ builtins like typed arrays and such, which is the domain of a polyfill rather than a transpiler.

**Comment by fatcerberus** [comment]
Sorry, I just checked the list and it looks like we also support `const` and some additional regexp syntax.  However, that support is not complete; e.g., `const` is an alias for `var` with no block scoping and so it should still be transpiled to guarantee the correct semantics.
