### ISSUE TITLE
Printing stack trace on duk_pcall fail with Try/Catch

### ISSUE THREAD

**Issue by aquawicket** [svaarala/duktape#1989]
I'm attempting to print a stack trace when a function call fails with duk_pcall().

I can do this with duk_eval_string() pretty easy. Example
```
std::string str = "try{ MyFunc(); } catch(err){ print('+err.stack+'); }";
duk_eval_string(ctx, str.c_str());
```

_How to get the stack trace from duk_pcall()_
```
duk_push_global_object(ctx);
duk_get_prop_string(ctx, -1, func_name.c_str());
duk_push_string(ctx, param1_name.c_str()); //add parameter
if(duk_pcall(ctx, 1) != 0){
     //The function call failed, how do we get the context stack trace?
}
duk_pop(ctx);
```

**Comment by fatcerberus** [comment]
The error object (the very same kind you caught in the JS example!) is left on top of the stack when `duk_pcall` returns nonzero, so from there you just have to use `duk_get_prop_string()` to read its `.stack` property.

**Comment by aquawicket** [comment]
I'm still a bit confused about accessing the stack properly. From my js side, i call a C function that I registered. Then I look to see if that function comes with a callback, _probably doing it way wrong, but it's working_. And then, after I do some work, I call that callback with duk_pcall. 

Something like this
`MyFunc("test", function(){ alert("callback executed") });`
```
int MyFunc(duk_context* ctx)
{	
   std::string parameter1 = duk_require_string(ctx, 0);
	
   bool callback_found = false;
   if(duk_is_function(ctx, -1)){
      callback_found = true;
   }
	
   bool rval = DoWork(parameter1);

   //Call the callback
   if(callback_found){
      if(duk_pcall(ctx, 0) != 0 && duk_pcall(ctx, 1) != 0){
         //callback call failed, print stack trace
      }
      duk_pop(ctx);
   }

   duk_push_bool(ctx, rval);
   return 1;
}
```
I don't want to create the Error object in the js code. I'd like to wrap the callback from C side with a try/catch/throw unless it's already on the stack that is.

**Comment by fatcerberus** [comment]
`duk_pcall()` is effectively a native-side version of try-catch:
```c
// try {
if (duk_pcall(ctx, 0) != 0 && duk_pcall(ctx, 1) != 0) {
// } catch (err) {  // (`err` is on top of valstack)
    duk_get_prop_string(ctx, -1, "stack");  // push `err.stack`
    printf("%s\n", duk_get_string(ctx, -1));
    duk_pop(ctx);  // pop `err.stack`
}
duk_pop(ctx);  // pop return value (or `err`)
```

**Comment by fatcerberus** [comment]
As further clarification: When a `duk_pcall()` fails, it leaves whatever was thrown on top of the value stack *in place of the return value*.

**Comment by aquawicket** [comment]
I'm actually reading that section again, second time around. I got a better understanding and some working functions to play with now. Thanks a bunch.

**Comment by svaarala** [comment]
@aquawicket Was this issue resolved from your point of view?

**Comment by aquawicket** [comment]
Yes

**Comment by svaarala** [comment]
As a side note, it would be really nice for the getting started and programming model sections to be rewritten into more accessible form. The current ones do cover most of the important topics, but it would be nice if especially the value stack part provided more concrete examples with better visuals. While the stack model is a common concept not specific to Duktape, some users don't know it beforehand, and there are Duktape specific conventions too (like how index numbering works).

**Comment by fatcerberus** [comment]
Does stack indexing in Duktape work differently than Lua?  I was under the impression the APIs were very similar.

I will say that, while I was very familiar with the concept of a stack going in, it can still be difficult to follow complicated algorithms with a lot of pushes and pops.  I imagine it’s more intuitive to someone who working in assembly all the time but for someone spoiled by high-level languages like me it was a bit of a learning curve at first. :)

The above being said, I suspect part of the difficulty lies in keeeping a mental model of how the different API calls interact with the stack as you can’t always figure that out by the name of a function alone.  `duk_push_xxx` is intuitive, as is `duk_pop`.  But then you have `duk_get_prop_ string` which has an implicit push, `duk_set_prop_string` an implicit pop, etc.  Nevermind more complicated cases like `duk_get_prop` (pop key, push retrieved value).  Unfortunately I don’t know if there’s a good general solution for this other than encoding the stack signature into all function names (e.g. `duk_push_prop_string`, `duk_pop_and_set_prop_string`) which is obviously unwieldy and it’s not even obvious what to do in all cases (`duk_get_prop`?).  So documentation may indeed be our only practical weapon here.

Just my random thoughts first thing in the morning. Make of them what you will. :)

**Comment by svaarala** [comment]
I agree there's some learning curve (it is the same with Lua) and that's generally the case with stack virtual machines. But I haven't seen a practical solution to avoid that, other than documentation.
