### ISSUE TITLE
Qgoda is using Duktape

### ISSUE THREAD

**Issue by gflohr** [svaarala/duktape#1998]
Hi, do you mind listing [Qgoda](http://www.qgoda.net/) on https://wiki.duktape.org/ProjectsUsingDuktape.html? It's using Duktape via the Perl binding gonzus/JavaScript-Duktape-XS. Thanks!

**Comment by svaarala** [comment]
I'll be happy to list it - what would be a good oneliner telling how Duktape is used?

"Using Duktape to..."?

**Comment by gflohr** [comment]
It's currently using Duktape to parse its configuration file with js-yaml and ajv and merge it with lodash.merge(). It will soon use cheerio for DOM manipulations, and the list of applications will hopefully further grow in the future.

"Using Duktape for running auxiliary code written in JavaScript"?

A little bit off-topic: Qgoda also implements a working module resolver à la Node.js, see https://github.com/gflohr/qgoda/blob/master/lib/Qgoda/JavaScript/Environment.pm. The actual callbacks are `__moduleResolve` (currently line 166) and `__moduleLoad` (currently line 188). It's written in Perl but should still be pretty understandable, and it's at least smart enough to successfully load ajv, js-yaml and lodash and their dependencies. At first it wasn't clear to me how to implement such a resolver, and maybe other users are happy to find a working example. Despites it being written in Perl. ;)

**Comment by svaarala** [comment]
Sorry that it took so long, been really busy with other stuff, but here it finally is: https://github.com/svaarala/duktape-wiki/pull/213. The change will be live in ~24h. Thanks!
