### ISSUE TITLE
Don't undef DUK_F_DLL_BUILD

### ISSUE THREAD

**Issue by markand** [svaarala/duktape#2003]
Hello,

The actual duk_config.h explicitly un-define the `DUK_F_DLL_BUILD`. This prevents automatic switch between shared/static libraries when building the program.

For example, consider than incorporating duktape into a CMake project, one is able to select between building shared or static libraries. That is, when building shared libraries, user only has to pass `-DDUK_F_DLL_BUILD` unfortunately this is reset in the duk_config.h file.

I propose to completely remove that block:

```c
/* DLL build detection */
/* not configured for DLL build */
#undef DUK_F_DLL_BUILD
```

Instead, let user define either in source code DUK_F_DLL_BUILD or by using compiler option.

**Comment by fatcerberus** [comment]
The provided `duk_config.h` is only an example with common defaults - if your needs are different you’re meant to run the configuration script `genconfig.py` in your build process.

**Comment by svaarala** [comment]
@markand If you run `configure.py` with the `--dll` option, does that work?

**Comment by markand** [comment]
Oh okay, I didn't know configure.py was used to re-configure the duk_config.h. I'll use it next time. I have not tested it because I don't have python installed on Windows.

Sorry for the noise :)

**Comment by fatcerberus** [comment]
Yeah... that’s why `duk_config.h` exists separately from `duktape.h`. :smile:
