### ISSUE TITLE
Equality test from C code

### ISSUE THREAD

**Issue by jugglingcats** [svaarala/duktape#2004]
Hi, am new to Duktape but so far so good -- thanks for a great project.

I'm exploring event handling and want to be able to register a Javascript event handler that is invoked from a C event emitter, eg:

```
// Javascript
myfunc() {
  print("got event!");
}
myglobal.addEventListener("event", myfunc);
```

The C code stores the function in the global stash, and can invoke the callback no problem.

Am now looking at _unregistering_ the event handler... ie. `myglobal.removeEventListener("event", myfunc)`.

Am sure it's simple, but assuming I have a list of event handlers in the global stash, how can I work through them and test for equality in order to remove the correct listener?

**Comment by fatcerberus** [comment]
[`duk_strict_equals`](https://duktape.org/api.html#duk_strict_equals) is probably what you're looking for.

**Comment by jugglingcats** [comment]
Thanks, I missed that one!
