### ISSUE TITLE
How to add Node's VM like functionality using duktape

### ISSUE THREAD

**Issue by ganeshnikam18** [svaarala/duktape#2010]
Hello Team,
I have one node application which I need to port to ductape. This application has module which creates sand-boxing environment using Node's VM module. To communicate between main context and the VM sandbox, EventEmitter inherited (bridge) class has been used. The object of bride class has been created in main context and the reference is passed to VM sandbox context. When sandbox is done with its task, it is able to call the callback function which was registered from main context

I need to port this functionality using duktape engine. I checked the ducktape APIs to figure out how I can implement this. 
1.  Create the separate heap for sandbox and for communication do the serialization. But how the event registration and call backing functionality will work here ?
2. Create separate context with new global : duk_push_thread_new_globalenv(duk_context *ctx); 
Here also how do I refer bridge object created in main thread in VM sandbox ?

Can you please suggest better option to implement this requirement in duktape ?

**Comment by lll000111** [comment]
You can check how low.js does it &mdash; it is made on top of DukTape.

Files of interest:

- https://github.com/neonious/lowjs/blob/master/lib_js/vm.js
- https://github.com/neonious/lowjs/blob/master/src/low_native.cpp
- https://github.com/neonious/lowjs/blob/master/src/low_native_aux.cpp

**Comment by svaarala** [comment]
@ganeshnikam18 I'll close this now - please let me know if this wasn't resolved.
