### ISSUE TITLE
DUK_USE_DATE_GET_NOW Out of the box error

### ISSUE THREAD

**Issue by nick-thompson** [svaarala/duktape#2011]
Hi, I'm trying to compile Duktape in my existing cpp program. I've added the source headers/file from `src-noline` and by default the compilation fails due to a missing `DUK_USE_DATE_GET_NOW` macro. 

From what I've read in the docs, I would expect this to work by default for my OS? I'm on OS X 10.13.6 building in XCode 9.4.1.

I can get it to compile fine if I use the dummy date provider from the examples folder here, but the javascript that I want to run may rely on actual date information. So I'm asking here because I want to get this to compile the right way. Am I missing a `#define` or something? Or will I just actually have to provide my own date provider? Thanks!

**Comment by svaarala** [comment]
It should indeed work out of the box on OS X. I have a Mac Mini somewhere so I'll try to reproduce the issue later on.

**Comment by svaarala** [comment]
Just quickly testing with High Sierra, at least building Duktape checkout with `make duk` works out of the box, clang version is:
```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
```

**Comment by svaarala** [comment]
Reading through the config files, what should happen is that:
- `DUK_F_APPLE` detects the platform: https://github.com/svaarala/duktape/blob/master/config/helper-snippets/DUK_F_APPLE.h.in
- The platform file should define `DUK_USE_DATE_NOW_GETTIMEOFDAY`: https://github.com/svaarala/duktape/blob/master/config/platforms/platform_apple.h.in
- Finally, the Date provider snippet should detect that define and define `DUK_USE_DATE_GET_NOW()`: https://github.com/svaarala/duktape/blob/master/config/header-snippets/date_provider.h.in

I don't see how this process would fail except if `DUK_F_APPLE` failed to detect. That check is currently based on presence of `__APPLE__`. Could you check if this define is missing when you compile?

**Comment by nick-thompson** [comment]
Thanks @svaarala. So I dropped `#error` defines along the path that you described here. It looks like my compilation indeed hits the define for `DUK_USE_DATE_NOW_GETTIMEOFDAY` in step 2, but it doesn't make it to step 3 for defining `DUK_USE_DATE_GET_NOW`.

It looks like I never get past the `#if defined(DUK_COMPILING_DUKTAPE)` line, which is why the `DUK_USE_DATE_GETNOW` never gets set. Maybe a little more detail on how I'm compiling will help: I've downloaded the tar file and unpacked it into my repository, but instead of compiling with any of the provided Makefile's, I'm dropping `#include` definitions into my project:

```
#include "duktape/src-noline/duk_config.h"
#include "duktape/src-noline/duktape.h"
#include "duktape/extras/console/duk_console.h"
```
and
```
#include "duktape/src-noline/duktape.c"
#include "duktape/extras/console/duk_console.c"
```

Perhaps that wasn't the intended use, though it seems to work fine apart from the date provider. Maybe with a couple of additional `#define`s in my own project before those `#include` lines, I can resolve this?

**Comment by svaarala** [comment]
You should never include `duk_config.h` directly. Instead, just incldue `duktape.h`.

This may be breaking the build, because `duk_config.h` gets included before `DUK_COMPILING_DUKTAPE` gets set by `duktape.c`.

**Comment by svaarala** [comment]
Also, you shouldn't `#include` the C files (duktape.c etc). They should be compiled separately.

**Comment by nick-thompson** [comment]
Thanks @svaarala. Reordering my include order appropriately resolved the issue

**Comment by svaarala** [comment]
Good to hear!
