### ISSUE TITLE
"0=='+'" returns "true", +'+' incorrectly coerces to 0 instead of NaN

### ISSUE THREAD

**Issue by FlatAssembler** [svaarala/duktape#2019]
Why does "0=='+'" return "true" if Duktape is compiled with Clang (I haven't tested it on other compilers)? Is that intentional? In all the browsers I've tested that in it returns "false".
I've noticed that because my [project](http://flatassembler.000webhostapp.com/compiler.html) relies on "(0=='+')===false" to correctly display the casting-warnings when compiling from my own programming language to assembly.
Perhaps related to that, why doesn't the "Array.prototype.includes" appear to work?

Overall, I think Duktape is an excellent project. With it, I can target any platform I want with the tools I am familiar with. However, it has some annoying bugs, though most of them appear to be solvable simply by minifying the JavaScript. The JavaScript on that web-page (I was using it to make a scientific calculator for Android), for instance, takes around 15 seconds to load on Samsung Galaxy S3 Mini if it's not minified, yet it loads in around 2 seconds if it is minified. Similarly, if it's not minified, it doesn't load at all on Windows (results in "Out of Memory"), but it loads almost instantaneously if it is minified. Quite a big difference considering that the minified file is just 40% smaller.

**Comment by svaarala** [comment]
That `0 == '+'` seems like a bug in number coercion of `+`, namely:
```
print(+'+') // => 0
```

when it should be NaN.

Array.prototype.includes is ES2015+ and not yet implemented, so it's simply undefined at this point.

**Comment by svaarala** [comment]
Here's the apparently correct behavior from NodeJS:
```
> +'+'
NaN
> +'+0'
0
> +''
0
```

The bug is probably that Duktape interprets `+''` (empty string) coercion correctly as 0, and then incorrectly treats a leading plus sign as a no-op so that `+'+'` becomes +0 instead of NaN. Same goes for `+'-'`.

**Comment by svaarala** [comment]
Regarding the compiler, this happens on all compilers, not just clang. It can also be repeated at https://duktape.org/dukweb.html.
