### ISSUE TITLE
require() doesn't load the object correctly

### ISSUE THREAD

**Issue by mhshami01** [svaarala/duktape#202]
I am using duk_ API for embedding JavaScript in my application. I found that using 'require()' fails to load the object correctly.

The repro data is listed below:

```c
----------------------------------------- program.cpp -------------------------------
#include <stdio.h>

#include "duktape.h"


/**
 *
 */
duk_ret_t do_loadFile(duk_context *ctx)
{
    const char *moduleName = duk_require_string(ctx, 0);
    duk_pop(ctx);
    duk_push_string_file(ctx, moduleName);

    return 1;
}


/**
 *
 */
int main(int argc, _TCHAR* argv[])
{
    duk_context *ctx = duk_create_heap_default();

    if (!ctx)
    {
        printf("Failed to create a Duktape heap.\n");
        return -1;
    }

    duk_push_global_object(ctx);
    idx = duk_push_c_function(ctx, do_loadFile, 1);
    duk_put_prop_string(ctx, -2, "loadFile");

    duk_eval_string(ctx, "Duktape.modSearch = function (id) {\n"
        "  var res = loadFile('./Scripts/' + id + '.js'); \n"
        "  if (typeof res === 'string') {\n"
        "    return res;\n"
        "  };"
        "  throw new Error('module not found: ' + id);\n"
        "};"
    );

    duk_eval_string(ctx, "var MYObject = require('MYObject');\n"
        "print(typeof(MYObject));\n"
        "for (var k in MYObject) {\n"
        "    print(i + ': ' + k.toString());\n"
        "    i++;\n"
        "}\n"
        );

    duk_destroy_heap(ctx);
    return 0;
}

------------------------------  MyObject.js  --------------------------------
var MYObject;
(function (MYObject) {
    (function (Collections) {
    })(MYObject.Collections || (MYObject.Collections = {}));
    var Collections = MYObject.Collections;
})(MYObject || (MYObject = {}));


-------------------------------------------- compile line ---------------------------------
g++ -std=c++11 program.cpp duktape.c -o program -lm

----------------------  output:
expected:
   object
   0: Collections

actual:
  object

------------------------explanation:
```

Basically, I am unable to call any of the class's methods or access its properties...

**Comment by svaarala** [comment]
Unrelated, but you shouldn't `duk_pop()` the string argument given to `do_LoadFile`: once you do that, the `const char *` returned from `duk_require_string()` may no longer be valid if there's no other reference to it. In this case there are other references so it shouldn't cause an actual problem here.

**Comment by fatcerberus** [comment]
@svaarala:
Something I learned the hard way. :). When I first started using Duktape, my OCD compelled me to pop stuff off the stack as soon as possible and I kept getting segfaults because it was freeing the string.  Took me a bit to figure out what happened each time, now I know better.

**Comment by svaarala** [comment]
Hmm - your `MyObject.js` doesn't export any symbols? In a CommonJS module a module is expected to export symbols explicitly, e.g.:

```js
// adder.js
exports.add = function add(x,y) { return x + y; }
```

Which is then used like:

```js
var adder = require('adder');
print(adder.add(1, 2));
```

**Comment by svaarala** [comment]
@fatcerberus When I have time to rework the guide I'll try to clarify that with more explicit code examples - it really is a central point that the value stack is an easy guarantee of reachability and pointers can be considered live as long they are reachable. It's discussed e.g. here:

- http://duktape.org/guide.html#type-pointer-stability

**Comment by svaarala** [comment]
@mhshami01 Any updates on this?

**Comment by mhshami01** [comment]
I don't have to use 'exports' explicitly when running the code through NodeJS...

**Comment by svaarala** [comment]
CommonJS requires that symbols are exported explicitly through `exports`. You can write to globals directly as follows though, but it's not really good style in my view:

```js
// module.js
foo = 123;  // gets assigned to global object
var bar = 234;  // this doesn't
```

Could you paste an short Node.js example of what you mean?

**Comment by mhshami01** [comment]
Here is what I have:

------------------------------------- MyObject.js
var MyObject;
(function (MyObject) {
    (function (Collections) {
    })(MyObject.Collections || (MyObject.Collections = {}));
    var Collections = MyObject.Collections;
})(MyObject || (MyObject = {}));
var MyObject;
(function (MyObject) {
    function logName(name) {
        if (typeof console !== "undefined") {
            console.log('MyObject::logName(' + name +')');
        } else {
            print('MyObject::logName(' + name +')');
        }
    }
    MyObject.logName = logName;

    exports = module.exports = MyObject;
})(MyObject || (MyObject = {}));

---------------------------------------- app.js
var MyObject = require('MyObject');
print(typeof(MyObject));
var i = 0;
for (var k in MyObject) {
   print(i + ': ' + k.toString());
   ++i;
}
print('done');
MyObject.logName('Hello!');


----------------------------------- output
from node (node app.js):
object
0: Collections
1: logName
done
MyObject::logName(Hello!)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
from duktape (using duk_eval_file("app.js");):
object
done
FATAL 56: uncaught error
PANIC 56: uncaught error (calling abort)
Aborted (core dumped)

**Comment by svaarala** [comment]
You're using `module.exports` in that example.

Duktape 1.2.x doesn't support that but support for `module.exports` was merged to master just a few days ago #201.

**Comment by mhshami01** [comment]
the branch 'master' works. thank you!

**Comment by svaarala** [comment]
Good to hear :)
