### ISSUE TITLE
Incorrect docs on duk_set_finalizer?

### ISSUE THREAD

**Issue by koush** [svaarala/duktape#2037]
https://duktape.org/api.html#duk_set_finalizer
The sample code is as follows:
```c
duk_ret_t my_finalizer(duk_context *ctx) {
    /* Object being finalized is at stack index 0. */
    printf("object being finalized\n");
    return 0;
}

/* Create an object whose finalizer is my_finalizer(). */
duk_push_object(ctx);
duk_push_c_function(ctx, my_finalizer, 1 /*nargs*/);
duk_set_finalizer(ctx, -2);
```

Using this code, with a debugger attached, I see the following error when the finalizer is invoked:
```
RangeError: invalid count 
```

Changing the C code to fixes this error:
```c
duk_push_c_function(ctx, my_finalizer, 2 /*nargs*/);
```

It seems that there's a second argument being sent (I'm unsure what it is), and Duktape is throwing an error in the debugger (and pausing it) when it finds that the finalizer C func can't handle two arguments.

**Comment by koush** [comment]
Actually, this was a bug in my code. Was popping 1 too many items off the stack.

**Comment by svaarala** [comment]
@koush Good that it worked out - the finalizer is actually given two arguments (the object, and a boolean indicating whether rescue is possible). But it is up to the finalizer function how many arguments it actually wants to see (nargs).
