### ISSUE TITLE
How to share objects created in JS with C/C++

### ISSUE THREAD

**Issue by Geequlim** [svaarala/duktape#2038]
May related to #1997 

How can I return an object created in JavaScript from C/C++ ?

--------------
Here is an example for this question：
I export two C++ classes to JavaScript with duktape as below in the way similar to #1997 

```c++
class Button : public ReferenceCountedObject  {
public:
    void set_title(const char *) { ... }
    const char * get_title() const {  .... }
};

struct ButtonContainer : public ReferenceCountedObject {
public:
    void set_button(Button*) { ... }
    Button* get_button() const {....}
};

```

Then I get the problem in JavaScript

```javascript
var container = new ButtonContainer();
var button = new Button();
container.set_button(button);

// This should always be false as the returned object is not the one we created in js
var is_same_object = button == container.get_button();
```

**Comment by kungfooman** [comment]
What I like to do is using ID's for everything, e.g. in C/C++ you would make:

```C
Button *sharedButtons[1024] = {NULL};
```

And your JavaScript objects would just be simple classes with an ID:

```
function Button(id) {
    this.id = id;
}
Button.prototype.doSomething = function() {
    button_do_something(this.id); // exported C function
}
```

In Duktape C/C++ functions you can always check:

 `if (id >= 0 && id <= 1023 && sharedButtons[id] != NULL)` so it can't crash.

Testing if a button is the same: `button_a.id == button_b.id`

Too bad that JavaScript doesn't have anything like Lua meta tables to implement overloaded operators for `equal` e.g.

**Comment by Geequlim** [comment]
Solved with heap pointer https://duktape.org/api.html#duk_get_heapptr
