### ISSUE TITLE
JSON.stringify() performance optimization

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#204]
Some possibilities:

- Direct access to properties instead of using the stack API. However, must avoid side effects caused by `toJSON()` calls, value replacement, etc.
- Rewrite character output macros for direct buffer management instead of the shared dynamic buffer spare functions.
- Add option to use platform `sprintf()` for numbers, at least when number range guarantees compliant result.
- Add a separate fast path algorithm when no replacer is given (and perhaps no indent is used).
- Optimize loop detection to be faster in the common case.

**Comment by svaarala** [comment]
@JoshEngebretson Btw, does the input to JSON.serialize() contain a lot of numbers in your case? Non-integer numbers go through the built-in Dragon4-based number-to-string algorithm which is optimized for compactness and is quite slow.

If you do deal a lot with (non-integer) numbers, JSON.serialize() could most likely in your case just rely on the platform `sprintf()` being sufficient, at least when exponent notation is not needed. I could add an option for Duktape to rely on the platform number-to-string conversion in a few select places if that's the case.

The internal Dragon4-based algorithm is needed because sometimes `sprintf()` doesn't match the required formats. Ecmascript also mandates support for serializing fractional values in non-base-10, e.g.:

```
duk> Math.PI.toString(16)
= 3.243f6a8885a3
```

**Comment by fatcerberus** [comment]
Yet another example of JSON being way overspecified.  JSON was designed (or supposed to have been) so that you could parse it with a simple `eval`, but now that's actively discouraged.  For me at least, it's lost what little appeal it might have originally had.

Sorry, just venting. ;)

**Comment by svaarala** [comment]
@fatcerberus If you're referring to the non-base-10 number formatting, that's not part of JSON but part of Ecmascript. I was just saying that Duktape can't generally rely on `sprintf()` for this reason.

**Comment by JoshEngebretson** [comment]
@svaarala The JSON is Javascript AST from the Mozilla Parser API spec: 

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API

Here's some sample of what JSON.stringify is generating:

https://gist.github.com/JoshEngebretson/71722799f017c526df4a

**Comment by JoshEngebretson** [comment]
I should be able to get some profiler metrics today.  If I recall correctly from the last time, generating the AST object was pretty quick, but then converting the object to a JSON string took most of the time.

**Comment by svaarala** [comment]
The data you're serializing is object heavy so I'd guess the places to improve would be:

- Enumerating the keys: currently goes through the same enumeration mechanism as e.g. `for-in` which creates a temporary object (two actually) to deal with mutation-while-serializing. Unfortunately mutation cannot be ignored because any `toJSON()` call may have side effects. Without mutation there'd be no need for these temporary objects.

- Loop detection uses a tracking object whose keys are string-coerced object pointers. There's probably a faster way to do this at least for the first N levels. I also considered using `duk_hobject` flags for loop detection but that's unworkable because a `toJSON()` call (or a replacer call) may have a side effect which does another JSON.stringify() while the previous one is still running.

The numbers in your example are integers which should go through a fast path and won't invoke Dragon4.

**Comment by svaarala** [comment]
Serializing that AST a 100 times and using valgrind callgrind, some of the top entries:

```
774,829,174  duk_api_stack.c:duk_require_tval [/home/sva/duktape/duk.O2]
671,898,802  duk_hobject_props.c:duk__get_own_property_desc_raw [/home/sva/duktape/duk.O2]
640,311,587  duk_api_stack.c:duk_pop_n [/home/sva/duktape/duk.O2]
597,360,614  /build/buildd/eglibc-2.17/malloc/malloc.c:_int_malloc [/lib/x86_64-linux-gnu/libc-2.17.so]
596,729,714  /build/buildd/eglibc-2.17/malloc/malloc.c:_int_free [/lib/x86_64-linux-gnu/libc-2.17.so]
534,667,849  duk_hobject_props.c:duk_hobject_find_existing_entry.isra.74 [/home/sva/duktape/duk.O2]
469,622,347  duk_hobject_props.c:duk__realloc_props [/home/sva/duktape/duk.O2]
465,812,680  duk_hobject_props.c:duk_hobject_putprop [/home/sva/duktape/duk.O2]
415,758,945  duk_hbuffer_ops.c:duk_hbuffer_insert_bytes [/home/sva/duktape/duk.O2]
330,212,322  /build/buildd/eglibc-2.17/malloc/malloc.c:malloc [/lib/x86_64-linux-gnu/libc-2.17.so]
321,527,804  duk_api_stack.c:duk_get_tagged_heaphdr_raw [/home/sva/duktape/duk.O2]
319,052,400  /build/buildd/eglibc-2.17/stdio-common/vfprintf.c:vfprintf [/lib/x86_64-linux-gnu/libc-2.17.so]
277,452,495  duk_hobject_props.c:duk_hobject_getprop [/home/sva/duktape/duk.O2]
261,507,742  duk_heap_stringtable.c:duk_heap_string_intern [/home/sva/duktape/duk.O2]
247,501,130  duk_api_stack.c:duk_push_tval [/home/sva/duktape/duk.O2]
228,026,643  /build/buildd/eglibc-2.17/string/../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:__memcpy_ssse3_back [/lib/x86_64-linux-gnu/libc-2.17.so]
203,581,600  duk_bi_json.c:duk__enc_quote_string [/home/sva/duktape/duk.O2]
199,109,354  duk_api_stack.c:duk_to_string [/home/sva/duktape/duk.O2]
195,262,144  duk_api_stack.c:duk_remove [/home/sva/duktape/duk.O2]
187,187,814  duk_api_stack.c:duk_get_lstring [/home/sva/duktape/duk.O2]
181,655,715  duk_unicode_support.c:duk_heap_string_intern
[...]
```

**Comment by svaarala** [comment]
The annoying this about mutation-during-serialization is that it almost never happens in practical situations, but it still needs to be supported :)

One approach to that would be to write a fast path that didn't support mutation. It would be used when there was no "replacer" function and if it encountered an object with a `toJSON()` method (which might have side effects on any value being serialized), it could bail out and fall back to the slow path.

**Comment by svaarala** [comment]
@JoshEngebretson Did some very quick testing of the separate fast path approach. It doesn't handle all cases correctly yet, and doesn't yet have loop/recursion limits, but gives a ballpark for what's possible.

Serializing the test JSON you linked to 100 times with and without fast path:

```
sva@keppihevonen:~/duktape$ time sudo nice -20 ./duk.O2 _josh.js 
real  0m0.344s
user  0m0.326s
sys   0m0.012s

sva@keppihevonen:~/duktape$ time sudo nice -20 ./duk.master.O2 _josh.js 
real  0m2.053s
user  0m2.035s
sys   0m0.015s
```

It's going to become a bit slower because of the loop/recursion check, and the code will also need to check for an inherited `toJSON()` method (quite unfortunate but necessary for compliance). But it should be possible to get perhaps 3-4x current performance with this approach.

Improving the buffer appending process to be more direct should also help (also the current main path) as a separate step.

**Comment by JoshEngebretson** [comment]
Wow, very encouraging!  This is used by Atomic's integrated JS editor, basically parsing with acorn.js and then dump the AST object to JSON so can be consumed by native code.  These speedups combined with maybe doing the operation on a separate thread or maybe breaking it apart with some Duktape coroutines (yielding along the way so app remains responsive) should help, cool!

**Comment by svaarala** [comment]
Hmm, it appears the `toJSON` check doesn't really have a measurable impact, so perhaps the speedup would be closer to 4x than 3x. Anyway, I suspect the output buffer management would be a very useful optimization target, it really does a lot more than it needs to.

Here's some callgrind output:

```
432,492,668  duk_hbuffer_ops.c:duk_hbuffer_insert_bytes [/home/sva/duktape/duk.O2]
265,874,000  /build/buildd/eglibc-2.17/stdio-common/vfprintf.c:vfprintf [/lib/x86_64-linux-gnu/libc-2.17.so]
232,400,292  duk_lexer.c:duk__advance_chars [/home/sva/duktape/duk.O2]
213,005,166  /build/buildd/eglibc-2.17/string/../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:__memcpy_ssse3_back [/lib/x86_64-linux-gnu/libc-2.17.so]
203,581,600  duk_bi_json.c:duk__enc_quote_string [/home/sva/duktape/duk.O2]
120,828,615  duk_unicode_support.c:duk_heap_string_intern
103,219,500  duk_bi_json.c:duk__json_stringify_fast_value'2 [/home/sva/duktape/duk.O2]
 88,870,600  /build/buildd/eglibc-2.17/libio/genops.c:_IO_default_xsputn [/lib/x86_64-linux-gnu/libc-2.17.so]
 65,453,002  duk_hobject_props.c:duk__get_own_property_desc_raw [/home/sva/duktape/duk.O2]
 64,218,749  duk_hobject_props.c:duk_hobject_find_existing_entry.isra.74 [/home/sva/duktape/duk.O2]
 55,021,000  duk_hbuffer_ops.c:duk__enc_quote_string
```

As can be seen, `duk_hbuffer_insert_bytes()` is a major contributor to the instruction count (at least for Valgrind's intermediate assembly).

Oh, this fast path test relied on being able to `sprintf()` a `int64_t` and a `double`. I guess that'd be an acceptable limitation for enabling the fast path.

**Comment by svaarala** [comment]
Quite interesting, added everything needed in the fast path except for loop detection and the execution time is still around ~350ms. But when I add the slow path object detection mechanism (based on a tracking object whose keys are ToString(obj_ptr)) the execution time jumps to ~750ms!

So, I tried a more lightweight loop detection mechanism for the fast path, using a simple array of object pointers which are relatively fast to iterate over when serializing. This is much faster but has a depth limit (now 32) at which point the fast path will bail out and fall back to the main code path. With this check in place the total execution time for the test data is around ~350ms.

Since the loop check is so significant, I'll probably also make the main algorithm (slow path) loop check some kind of a hybrid with both a simple pointer array and a tracking object, so that reasonably shallow structures would avoid the slow object-based tracking.

**Comment by svaarala** [comment]
@JoshEngebretson Ok, here's a draft branch with the fast path approach:

- https://github.com/svaarala/duktape/compare/perf-json-serialize-fast-path

It's quite complete, but number serialization needs finishing: NaN, Infinity, and negative zero will at least serialize incorrectly. The branch uses `sprintf("%lg")` for doubles and `sprintf("%lld")` for fastints; these will need fixing before a merge.

If these are not an issue in your case, it'd be nice to hear if this kind of fast path would work for you! :)

**Comment by svaarala** [comment]
Number serialization is apparently relatively important for the fast path.

If I disable fastint support, integer values will get serialized using `sprintf("%lg")` instead of `sprintf("%lld")` and that bumps execution time from 350ms to 530ms.

When fastints are disabled and Duktape's built-in number-to-string conversion is used instead of `sprintf()`, execution time goes from 350ms to 440ms.

The built-in number coercion is faster than the native but only because it has a specific integer fast path and the inputs are integers. But it's still much slower than `sprintf("%lld")` for fastints, so the fast path performs best when fastints are enabled and there's a fastint-specific number serialization call in place - either relying on native `sprintf()` or perhaps adding fastint support for Duktape numconv.

**Comment by fatcerberus** [comment]
Integer is still by far the way to go for performance, even with floats being supported in hardware. :)

**Comment by JoshEngebretson** [comment]
Awesome work!  This is way faster and makes the editor feel far more responsive when loading Javascript :)   

I am not quite able to bring this into our master as it seems the module.exports may not be in this branch?  No worries, if you need to test it out a bit more... very impressive speed improvement!

**Comment by svaarala** [comment]
I'll rebase it and push the branch - it still needs some development before it can be merged to master. But after the rebase you should be able to use it with caution :)

**Comment by svaarala** [comment]
There was at least a few bugs:

- JSON.stringify() must auto-unbox Number, String, and Boolean objects and the fast path failed to do so.
- JSON.stringify() will only look at enumerable own properties of an object, but uses the `[[Get]]` operation for arrays that *does* inherit properties from `Array.prototype` (pretty weird). I avoided this gotcha for now by bailing out on gappy arrays. A better fix would to be to check the ancestor and bail out only if an inherited property showed through the gap (which is very, very unlikely for practical code).

Also improved the number serialization so that it now passes the testcases. There are still a few issues to resolve before a merge:

- What to do with the `sprintf()` call for fastints; perhaps use it only on C99 platforms (and MSVC).
- Feature option to disable the fast path (for low memory targets); also add it to the matrix test and include a small JSON test in the matrix test.
- Perhaps add support for gappy arrays so that when a gap is seen, ensure that there is no inherited property from `Array.prototype` (should be the case for all practical code). If there *is* a parent, bail out of the fast path; if not, serialize a `null`.
- Resolve FIXMEs (mostly downgrading at this point).

Anyway, rebased and force pushed the branch so it should now include `module.exports` changes too.

**Comment by fatcerberus** [comment]
That gap check on arrays concerns me... If an object with a lot of arrays is serialized, won't Duktape get bogged down walking all the arrays looking for gaps?

I suppose this kind of thing is the price to be paid for JS Arrays not really being what they claim to be.

**Comment by svaarala** [comment]
It's only a check that's needed for arrays that are walked (serialized) anyway: https://github.com/svaarala/duktape/blob/3e4ce49940306b0e84899d06dcb36c527430af11/src/duk_bi_json.c#L1977-L2005

**Comment by svaarala** [comment]
As a teaser for @JoshEngebretson, quickly tried what the rough speed improvement is with this fast path + the changes in #209 (removing buffer spare and reworking various buffer emission sites). Looping 1000 times (instead of 100 as above); relative speed to master is what matters:

```
sva@keppihevonen:~/duktape$ time sudo nice -20 ./duk.O2.master _josh.js 
real	0m22.999s
user	0m22.973s
sys	0m0.012s

sva@keppihevonen:~/duktape$ time sudo nice -20 ./duk.O2.rebased _josh.js 
real	0m1.715s
user	0m1.711s
sys	0m0.007s

sva@keppihevonen:~/duktape$ time sudo nice -20 rhino _josh.js 
real	0m11.105s
user	0m13.446s
sys	0m0.157s
```

**Comment by fatcerberus** [comment]
Holy crud, it's a 22x improvement!

**Comment by JoshEngebretson** [comment]
Whoa!!!!!  

... and my birthday isn't even for another 8 months! :cake: 

Those are some fantastic numbers, should make a huge difference when opening and typing in larger files. Thanks!

**Comment by svaarala** [comment]
V8 comparison for fun:

```
sva@keppihevonen:~/duktape$ time sudo nice -20 node _josh.js 
real	0m1.310s
user	0m1.301s
sys	0m0.011s
```

**Comment by fatcerberus** [comment]
So JSON performance with the new fast path is comparable to V8, very nice.

**Comment by JoshEngebretson** [comment]
Smokin' in your hot pants!

https://www.youtube.com/watch?v=G1_ctj5jx_s

Very nice!

**Comment by svaarala** [comment]
It'd be nice to get that close to V8 on a more regular basis ;-)

**Comment by svaarala** [comment]
Rebased and force pushed current draft. Just a couple of FIXMEs to go.

**Comment by svaarala** [comment]
The JSON.stringify() fast path is now merged to master.  It'll hopefully get a few small improvements (#255) before release but the bulk is now merged.  A few notes below.

First, the fast path is not fully portable so it's not enabled by default. To enable, ensure `DUK_USE_JSON_STRINGIFY_FASTPATH` is enabled in `duk_config.h` (there is no DUK_OPT_xxx feature option now).  You can do that by manually editing duk_config.h (or perhaps sed/awk), or by using genconfig e.g. as follows:

```
python config/genconfig.py \
    --metadata config/genconfig_metadata.tar.gz \
    --output duk_config.h \
    -DDUK_USE_JSON_STRINGIFY_FASTPATH \
    -DDUK_USE_FASTINT \
    autodetect-header
```

Second, the fastpath has optimized support for writing out fastints (integer values in the 48-bit signed range) and will be a lot slower without fastints.  So, fastints are recommended for now.  One of the pending
improvements is to optimize number serialization in general which at the moment always uses duk_numconv.c which is slow.

**Comment by svaarala** [comment]
@fatcerberus This snapshot includes the merged fastpath, see notes above: http://duktape.org/snapshots/duktape-1.2.99-20150805220002-v1.2.0-265-g8e948aa.tar.xz

**Comment by JoshEngebretson** [comment]
Ok, this is strange.  I've had a chance to try both master and the snapshot above.  I am not seeing the speed increase here, stringify is actually running a bit slower.

Snapshot above (also tested current master):

Acorn parse time: 463
JSON.stringify time: 492

Master before the stringify optimizations landed: https://github.com/svaarala/duktape/commit/0b005c676c66f76431f2af7d8eacd1f81fb238fb

Acorn parse time: 457
JSON.stringify time: 439

I've used:

#define DUK_USE_JSON_STRINGIFY_FASTPATH
#define DUK_OPT_FASTINT

I also tried DUK_USE_FASTINT as it is shown above, though in duk_config.h need to have the OPT set:

    #undef DUK_USE_FASTINT
    #if defined(DUK_OPT_FASTINT)
    #if !defined(DUK_F_HAVE_64BIT)
    #error DUK_OPT_FASTINT requires 64-bit integer type support at the moment
    #endif
    #define DUK_USE_FASTINT
    #endif

Any ideas on why your numbers would should 22x speed increase seeing a slight slow down here?

**Comment by svaarala** [comment]
The fast path is narrow so it's only used when certain conditions are met: there is no replacer nor indent arguments to `JSON.stringify()`. Could you paste an example of your JSON.stringify() call?

Regarding the options, did you define them on the compiler command line or did you edit duk_config.h? If you used the command line, defining DUK_USE_JSON_STRINGIFY_FASTPATH will get undefined by duk_config.h, so you should edit duk_config.h directly. (Duktape will transition away from compiler command line options to duk_config.h and this option is only configured from duk_config.h right now).

**Comment by JoshEngebretson** [comment]
Yeah, I caught the #undef at the bottom

    JSON.stringify(ast);

So, just the AST object, which is pretty much unchanged from what I pasted above:

https://gist.github.com/JoshEngebretson/71722799f017c526df4a

Ok, so the improvements might not affect an object like this?

**Comment by svaarala** [comment]
I don't see why it shouldn't take the fast path for that. The conditions are roughly:

- No replacer in the call (side effects)
- No indent in the call (fixable)
- No object with a .toJSON() method (side effects)
- No sparse arrays (fixable, but very rarely important)

I've been testing the speedup with the original AST you provided, and just retested with the above gist:

```
# Without fastpath
real	0m2.169s
user	0m2.163s
sys	0m0.004s

# With fastpath
real	0m0.218s
user	0m0.214s
sys	0m0.004s
```

**Comment by JoshEngebretson** [comment]
Here's the result of the stringify I have been testing here:

https://dl.dropboxusercontent.com/u/90864981/JSONStringify.json.zip

It is pretty big at like 3.6 megs, so might be other factors.  The primary use case is working well (smaller game component files), though I wanted to report the findings on the optimization.

**Comment by svaarala** [comment]
Are there any Date instances in the input to JSON.stringify()? They have a .toJSON() method.

**Comment by svaarala** [comment]
I get around ~2x speedup for that >3MB file, not sure what would be the causing the difference. One possibility is that the object structures fall out of some CPU cache level which affects the result (not sure how plausible that would be).

**Comment by svaarala** [comment]
Ok I think I figured it out - the AST is much deeper than the previous one and I set the fast path maximum object depth to 32.

Just to verify this theory, could you edit the following line in `duktape.c` manually:

```
#define DUK_JSON_ENC_LOOPARRAY                32
```

Replace with:

```
#define DUK_JSON_ENC_LOOPARRAY                64
```

**Comment by svaarala** [comment]
That recursion depth limit issue would also explain why JSON.stringify() would be slightly slower in your test: it tries to use the fast path, encounters the depth limit, and falls back to the slower algorithm which is generic. It'd be better if the fast path could fall back into the slow path preserving the output so far, but that's quite difficult because there's a native C stack also involved.

Removing the recursion limit entirely from the fast path would be a useful improvement. I could refactor the code so that loop detection is shared between the fast and slow paths, but ensure it's fast for typical shallow objects.

Another approach entirely would be to remove loop detection entirely from the fast path, and impose a maximum output size limit. If that limit is reached, we'd fall back to the slow path and detect the loop (to provide a good error message). This approach would be a bit faster than the current fast path which uses an array of object references to detect loops, but it needs to impose an artificial output size limit for the fallback.

**Comment by JoshEngebretson** [comment]
You sir are a rockstar:

JSON.stringify time: 105

This is well within requirements here, great work! :)

**Comment by svaarala** [comment]
@JoshEngebretson Awesome :) I pushed to 32->64 change to master as an intermediate measure. I'll have to figure out a cleaner solution for the eventual 1.3 release.

Right now I'm tempted to remove loop detection from the fast path and just detect loops based on the output becoming too large, and then falling back to the slow path to confirm the loop (or generate the required output). This would make the fast path a bit faster still, and loops are erroneous inputs which don't usually need to be detected quickly.
