### ISSUE TITLE
Compile error with DUK_USE_EXEC_TIMEOUT_CHECK

### ISSUE THREAD

**Issue by ksdd** [svaarala/duktape#2040]
When compiling duktape 2.3.0 with strict compiler error options on Ubuntu 14.04 (amd64) I get a compile error for the following configuration:

>python2 tools/configure.py --output-directory=mydir \
>-DDUK_USE_CPP_EXCEPTIONS \
>-DDUK_USE_INTERRUPT_COUNTER \
>-DDUK_USE_EXEC_TIMEOUT_CHECK=duk_cbf_exec_timeout \
>-DDUK_USE_BROWSER_LIKE

The compiler invocation and resulting error message are

>/usr/bin/g++-4.9 -fPIC -std=gnu++11 -g -O2  -MD -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic -Werror -c -o .build/duktape.o src-tsd/duktape.c
src-tsd/duktape.c: In function ‘duk_small_uint_t duk__executor_interrupt(duk_hthread*)’:
src-tsd/duktape.c:75000:54: error: ‘duk_cbf_exec_timeout’ was not declared in this scope
  if (DUK_USE_EXEC_TIMEOUT_CHECK(thr->heap->heap_udata)) {
 
I fixed this locally by applying the attached patch.

[duk_js_executor.c.diff.gz](https://github.com/svaarala/duktape/files/2839586/duk_js_executor.c.diff.gz)

**Comment by svaarala** [comment]
You should add a declaration of `duk_cbf_exec_timeout()` into `duk_config.h` using a config snippet. When the compiler is compiling duktape.c, it needs to see the declaration from the header.

**Comment by ksdd** [comment]
Okay, thanks. I added the declaration via additional option
>--fixup-line='extern duk_bool_t duk_cbf_exec_timeout(void*);'

**Comment by svaarala** [comment]
Good to hear it worked out :+1:
