### ISSUE TITLE
Error when encountering CJK  Ideographs

### ISSUE THREAD

**Issue by giserfly** [svaarala/duktape#2042]
Hi, I have a problem when I processing CJK ideographs.
The code as follow:
duk_eval_string(ctx, " '中'+'2' ");
the code is crash, and in Window 7(x64), VS2008,
the error: libpng warning: iCCP: known incorrect sRGB profile.
duk_eval_string(ctx, " '1'+'2' ");
is success, the result is 12.
Thansk in advance.

**Comment by svaarala** [comment]
Could you provide the source code as a .ZIP file? I want to make sure I have the exact bytes that are passed to Duktape. There may be some bug in Duktape here, but in many cases it happens that the source text is not UTF-8.

You could also try using `duk_peval_string()` to get the error. What happens now is that you don't have a protected call wrapper, and Duktape encounters an uncaught exception, which by default causes an `abort()`.

**Comment by giserfly** [comment]
I use  `duk_peval_string()` ，there is no error information, but the result is null. This is the demo which I test CJK, the link is [https://github.com/svaarala/duktape/issues/2042](url). 
Best wishes!
[DuktapeTest-master.zip](https://github.com/svaarala/duktape/files/2873946/DuktapeTest-master.zip)

**Comment by svaarala** [comment]
Looking at the .cpp file, the problem character seems to be encoded as D6 D0 which is not a valid UTF-8 byte sequence.

For printing out the error you're currently using:
```
        printf("result: %s\n", duk_get_string(ctx, -1));/* result:(null) */
```

This won't work because the value at -1 is not a string, but an Error object. You need to coerce it to a string, for example:
```
        printf("result: %s\n", duk_safe_to_string(ctx, -1));
```

**Comment by svaarala** [comment]
The correct encoding is probably:
```
>>> u'中'.encode('utf-8')
'\xe4\xb8\xad'
```

You can test this by either changing the encoding of the source file to UTF-8, or explicitly escaping the character in C source code, e.g.:
```
        duk_peval_string(ctx, "'\xe4\xb8\xad'+'2'");        
```

**Comment by svaarala** [comment]
Changing duk_get_string() to duk_safe_to_string() as described above I get the following printout:
```
result: SyntaxError: source decode failed (line 0)
```

So indeed it just seems that the source encoding is not UTF-8 and won't parse properly.

**Comment by svaarala** [comment]
@giserfly Let me know if this wasn't resolved, closing now.
