### ISSUE TITLE
Question: dynamic object resolver hook in C for COM object support 

### ISSUE THREAD

**Issue by dzzie** [svaarala/duktape#2044]
I would like to figure out a way to integrate duktape with arbitrary COM objects on Windows.

Currently i have a system working where I generate a javascript class stub for predefined com objects that all operate through a single C resolver function ex: https://github.com/dzzie/duk4vb/blob/master/vb_examples/with_COM/COM/ListBox.js

Not a great setup but was quick and easy to implement. 

What I would like to figure out is a way that I could add an object to duktape from C and implement a hook so that anytime duk tries to call a method or access a property on this object, it first hits the C hook which can then proxy the script call out to the COM object through IDispatch. 

This way the calls could be dynamic and COM object support universal without having to pregenerate js class stubs for each. 

Wondering if there an internal mechanism to do something similar to this already or where would be the place to look if I had to implement it myself. Thanks for any help.

example resolver: https://github.com/dzzie/duk4vb/blob/master/vb_examples/with_COM/mCOM.bas#L51

**Comment by svaarala** [comment]
I'm not sure about the details, but could you simply use a Proxy object with traps implemented as Duktape/C functions (= C code)? This would allow you to capture any property access on a certain frontend object.

**Comment by dzzie** [comment]
this sounds like it could work if one trap in C would trigger on any arbitrary method/property access of js object and I could determine from C what the method/property name was, arg count, and how accessed (ie method call, property get, property let).

**Comment by svaarala** [comment]
When a `var x = obj.foo` is done on a Proxy object it triggers a `get` trap which gets the object and the property name, and can return an arbitrary value. You could, for example, return a function which would then capture the arguments as needed.

I'd recommend you check out the Proxy parts of https://wiki.duktape.org/HowtoVirtualProperties.html, and maybe look into ES2015 Proxy objects a bit to see if this would work for you.

Here's a very quick example in pure JS:
```javascript
var P = new Proxy({}, {
    get: function (targ, key, recv) {
        return function () {
            print('function called, key was', key, 'arguments are:',
                  JSON.stringify(arguments));
            return key.toUpperCase();  // arbitrary return value
	}
    }
});

var res = P.fooBar(1, 2, 3);
print('==>', res);
```

This prints:
```
$ duk /tmp/test.js
function called, key was fooBar arguments are: {"0":1,"1":2,"2":3}
==> FOOBAR
```

This quick example creates and returns a fresh function for every property access, but the function returned could of course be cached (based on the key).

**Comment by dzzie** [comment]
ok this looks like it could simplify my work thank you. I will close the question for now. Thanks for the help.
