### ISSUE TITLE
Firefox locks up loading duktape.org API or Guide pages

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#205]
I've had this issue on a few machines.  At first I figured it was Adblock causing it, but disabling/removing Adblock doesn't improve the situation.  I've had to resort to using IE or Chrome to view the Duktape documentation as a result.

What's odd is that saving either page (API or Guide) locally and loading that is fine, Firefox just doesn't seem to like loading them from the internet.  No other site does this, but I can reproduce it consistently with duktape.org.  Firefox locks up and spins the CPU endlessly until I kill the process from Task Manager.  Weird.

**Comment by svaarala** [comment]
Very weird indeed, no issues with Firefox on Ubuntu.

It might be related to font loading, at least that would work differently offline.

**Comment by fatcerberus** [comment]
Note that even on machines where it _does_ load, there's a hefty delay before displaying the page where Firefox is completely unresponsive.  Maybe it only affects Windows Firefox...?

**Comment by fatcerberus** [comment]
Interestingly, this issue seems to have magically gone away of late, the page loads much faster and doesn't lock up anymore.  So either one of the recent Firefox updates, or me upgrading to Windows 10 must have fixed it.

**Comment by svaarala** [comment]
There isn't much to be done other than splitting the documentation into smaller pages so I'll close this one.
