### ISSUE TITLE
duk_push_lstring got and error

### ISSUE THREAD

**Issue by mccoysc** [svaarala/duktape#2050]
error: RangeError: cannot push beyond allocated stack
    at [anon] (c:/Users/mccoyzhou/Desktop/tmpCode/duktape/src-noline/duktape.c:21977) internal
    at [anon] () native strict preventsyield
    at require () native strict preventsyield
    at main (./mod.js:8) preventsyield
    at require () native strict preventsyield
    at global (./test.js:3) preventsyield

i use the "extra/module-node",require("test.js").
"test.js" size:180KB

**Comment by mccoysc** [comment]
i read "test.js" whose size is 180KB into memory and using duk_push_lstring to push the data from file to stack,and then get this error.

**Comment by mccoysc** [comment]
and by the way , i just read 4 bytes and call duk_push_lstring per loop

**Comment by svaarala** [comment]
When a Duktape/C function is entered (or when the call stack is empty) there is a limited number of value stack slots reserved for pushing values. Once that is exhausted, you get a RangeError.

You should extend your value stack using  e.g. https://duktape.org/api.html#duk_require_stack. See also https://duktape.org/guide.html#programming.5.

**Comment by svaarala** [comment]
@mccoysc Any update on this?

**Comment by svaarala** [comment]
@mccoysc Please let me know if this wasn't resolved. Closing now.
