### ISSUE TITLE
Lexer tokenization improvement

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#207]
The current lexer codepoint window is managed in a very inefficient way (copying for every advance). 

Also token value stack slots are cleared and reinitialized for every token which is not necessary: the slots can hold previous values with the only impact that the values will be reachable until another token overwrites the values or tokenization ends.

**Comment by svaarala** [comment]
Draft branch:

- https://github.com/svaarala/duktape/compare/perf-lexer-window

The branch:

- Uses a sliding lexer codepoint window for better performance
- Replaces the large lexer if-else ladder with (mostly) a switch

The mandelbrot compile test (perf-testcases/test-compile-mandel.js) is 10% faster with the changes: on x64 laptop drops from ~20 seconds to ~18 seconds.

Code footprint change (from master) for x64, gcc -Os:

- With sliding window: +336 bytes
- Without sliding window (but with the if-else change): +240 bytes

The differences are quite trivial; interestingly the switch-case structure compiles to more code even in a size-optimized build.

The memory usage difference with and without sliding window is around 0.6kB which is small but might matter for low memory devices. Not sure if it's large enough to warrant keeping two window algorithms in the lexer.

**Comment by fatcerberus** [comment]
Yeah, I was going to say, you should use a circular buffer for the CP window but I see you already did that ("sliding codepoint window") :)

**Comment by svaarala** [comment]
Technically a circular window would be a bit different, access to the window would use an offset and modulo arithmetic (masking in practice). It would never need to copy codepoints.

The sliding window has no offset masking for lookups but needs to "scroll" the window once in a while.

Not sure which would be better; I opted for the sliding one because the codepoint lookup code will be smaller (and there quite many forward lookups in the tokenizer).

**Comment by svaarala** [comment]
Merged to master.

**Comment by fatcerberus** [comment]
Geez, you're as productive as me!  I built minisphere, a fully functional 2D game engine, from the ground up to its current state in 5 months.  Looks like I have some competition for rapid development here. :)
