### ISSUE TITLE
Possible bug from docs? (Arbitrary "this" binding in method call)

### ISSUE THREAD

**Issue by tneward** [svaarala/duktape#2072]
Trying this code:

```
  duk_push_string(ctx, "function(x,y) { return x+y; }");
  duk_eval(ctx);

  duk_push_int(ctx, 123); 
  duk_push_int(ctx, 2);
  duk_push_int(ctx, 3);
  duk_call_method(ctx, 2);  // [ ... func Fred 2 3 ] -> [ 5 ]
```
from the documentation (Guide), I get a SIGABORT in the duk_call_method. Either I'm missing something fairly fundamental, or this sequence is a bug in the docs. I'm open to either possibility (preferably the first).

**Comment by svaarala** [comment]
Hmm, there is probably a bug in the example:
```
duk> eval('function (x,y) { return x+y; }')
SyntaxError: function name required (line 1)
```

There should be parentheses around the function so that it evaluates as a function expression (instead of a function declaration):
```
duk> eval('(function (x,y) { return x+y; })')
= {_func:true}
```

I'll open a pull to fix it - could you point to the location in the docs?

**Comment by tedneward** [comment]
I'll have to go back through the Guide and spot it again, but I'll try to do that ASAP

**Comment by tedneward** [comment]
Found it; it's not in the Guide, it's in the API example for duk_call_method().

**Comment by svaarala** [comment]
Thanks!
