### ISSUE TITLE
Building Duktape without Python

### ISSUE THREAD

**Issue by IngwiePhoenix** [svaarala/duktape#2076]
Hey :)

I am not a real python-guy and based on what I actually want to do with Duktape, Python may not be available at an end-user's system upon building. To make it short: I want to write a build system myself, utilizing Duktape as the underlying scripting language.

Now, I can build Duktape just fine on my Macbook, because I have all the bells and whistles installed over here. But what if someone does not have python installed? How can someone build Duktape without using Python? I see a _lot_ of `.yml` files, especially within the `config` folder. Is that even possible at all?

Kind regards,
Ingwie

**Comment by svaarala** [comment]
Duktape build has two steps:
- Running tools/configure.py to produce Duktape source and header files: `duktape.c`, `duktape.h`, and `duk_config.h`. This step involves Python (python2 to be exact).
- The source and header files are then compiled as part of some C/C++ application. This step doesn't need Python at all.

It is quite fine and even expected to run step 1 once and save the resulting source files. After this you won't need Python, and can build the C files in whatever way you wish.

In fact, the Duktape distributable contains pre-generated source files (see `src/` in the unpacked directory) with default configuration and portability to all supported targets. These can be used as-is in many cases.

**Comment by IngwiePhoenix** [comment]
This is very useful to know! However, this also means that using git modules is basically no option, since one is required to have python, when building the target files... Oh well!

Thank you for the information :)

**Comment by svaarala** [comment]
@IngwiePhoenix You can use a pre-built distributable from the https://github.com/svaarala/duktape-releases repo if you want to use submodules. That repo contains unpacked releases as tags, including the pre-generated `src/` directories. For example, release 2.3.0 is available here:
- https://github.com/svaarala/duktape-releases/tree/v2.3.0
