### ISSUE TITLE
Add API calls for bytecode dump/load

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#208]
Add API calls to dump a function into bytecode (a buffer value) and to load a function from bytecode. The bytecode format should be platform neutral (but can be version specific) so that cross compilation works as expected.

Tasks:

- [x] Implement API calls
- [x] Feature option for compilation (footprint)
- [x] API testcase
- [x] Internal documentation for bytecode format, including rationale
- [x] API documentation
- [x] Website changes, mention bytecode dump/load support and basic features/limitations
- [x] Bytecode dumper script for diagnosing bytecode issues
- [x] Command line tool to compile a `.js` file into bytecode, perhaps add to `duk`
- [x] Command line tool to execute a bytecode file, perhaps add to `duk`
- [x] Cleanup branch merge (resolve FIXMEs)
- [x] Resolve unused variable warnings
- [x] Resolve testcase FIXMEs
- [x] Fix DUK_ALWAYS_INLINE issues with pre-C99 compilers, maybe enable DUK_ALWAYS_INLINE only by default with C99/C++11 or above (this is now in duk_config.h so user can tweak it anyway)

Original issue #27.

**Comment by fatcerberus** [comment]
What are you doing about the problem mentioned in the original issue of verification?  A header specifying the Duktape version?

Actually a better solution might be to not use the Duktape version directly, but a bytecode revision number.  This way if the format doesn't change between releases existing bytecode files won't break.

**Comment by svaarala** [comment]
Current prototype is here:

- https://github.com/svaarala/duktape/compare/bytecode-dump-load

The testcase is functional but the bytecode format is missing function flags (e.g. "strict", "has name binding", "create Arguments object") and properties ("length", "name", "_Varmap", etc), so some development is still needed.

Code footprint impact is currently ~2kB over master so probably needs a feature option to disable support (for low footprint devices).

**Comment by svaarala** [comment]
Not sure what to do about verification. For now I'm using a `0xFF` leading byte followed by a one-byte version number. The 0xFF byte ensures that no ordinary string can be loaded as bytecode as 0xFF prefix never occurs for (extended) UTF-8.

Bytecode format byte could be bumped for every Duktape minor release and kept the same for a patch release.

But a signature is far from being able to validate bytecode - if the signature matches, the current implementation will do memory unsafe things if the data that follows is invalid. Fixing this is very difficult because one would need to validate also the bytecode by simulating all operations, their register indices etc (which is very complicated because there are also indirect operations etc).

So I'm not going to implement bytecode validation as such, i.e. it's not supported to load bytecode from an untrusted source.

**Comment by fatcerberus** [comment]
Yeah, I wouldn't expect it to have that level of verification, just to make sure the case is handled where trying to execute the wrong version of otherwise valid code fails fast.

**Comment by JoshEngebretson** [comment]
Wow, you are on fire.  This is a really important feature.  The main issue I ran into with Lua bytecode was undefined endian, it depended on where the bytecode was dumped.

**Comment by svaarala** [comment]
@JoshEngebretson I've run into that issue myself too. We solved it by using a separate compiler that was able to flip number endianness. But it's a bit annoying that the bytecode is *almost* portable but that one issue makes it awkward to work with. I want to avoid this issue (and alignment requirements) because the cost of doing so is in the end quite small.

**Comment by svaarala** [comment]
Since the serialized functions are going to need a bunch of properties to work correctly, I'll have to rewrite the dumping approach to use a dynamic buffer rather than to precompute the final size in advance (which becomes progressively more awkward the more properties with variable size there are).

The loading part can be stripped of out-of-bounds checks: that may seem dangerous, but on the other hand broken bytecode is memory unsafe anyway because bytecode instructions may index values outside the executor value stack. That should speed up and simplify loading a little bit.

**Comment by fatcerberus** [comment]
There are a few limitations I can see with bytecode dumping.  A big one is that modules can't be precompiled, since Duktape.modSearch is required to return source code.  This is a shame, as this would be one of the big use cases for it, I think.

And of course anything using eval() or the equivalent C API (e.g. the RequireScript function in my game engine) needs to stay in source code form as well.

**Comment by svaarala** [comment]
One problem for precompiling modules is that if you just compile the source file it won't work correctly: modules need a specific environment with certain bindings which is now provided using a function wrapper. If precompiled bytecode were used, it'd have to be for the module already wrapped inside the temporary function.

But if you were to do that, I don't wee why you shouldn't be able to load the module directly in modSearch() and then just return undefined (= no source code to load), similarly to how native modules are loaded. It's not intuitive though, so this is certainly something to keep in mind when the module mechanism is reworked.

**Comment by svaarala** [comment]
Force pushed updated branch which should be functionally close to complete. It'll need some cleanup work before it's merge ready though.  See the API testcase for details on what works and what doesn't:

- https://github.com/svaarala/duktape/blob/bytecode-dump-load/api-testcases/test-dump-load-basic.c

**Comment by svaarala** [comment]
Pushed an updated branch which is close to merge ready: the branch has documentation, API testcase covering also current limitations, website updates, etc. It's still missing a command line tool to offline compile bytecode, it'd be nice to include such a tool in the distributable.

**Comment by svaarala** [comment]
Implemented bytecode compilation and execution to "duk" command line for convenience (program code only, not eval/function), rebased to master.

**Comment by svaarala** [comment]
I'll be merging this later today - you've been warned :) There's still chance to fix issues and work on details until 1.3 release.

**Comment by fatcerberus** [comment]
There's still a few tasks unchecked... :wink:

**Comment by svaarala** [comment]
Yup, I'll do them before the merge.

**Comment by svaarala** [comment]
As a fun little test, tested bytecode dump/load with "emscripten inception test". This is the testcase where Duktape and a hello world program (both written in C) are Emscripten compiled, and the resulting Javascript is then executed using Duktape:

```
# Run the test
$ make emscripteninceptiontest
[...]
emscripten/emcc -O2 -std=c99 -Wall --memory-init-file 0 -Idist/src dist/src/duktape.c dist/examples/hello/hello.c -o /tmp/duk-emcc-test.js
[...]
./duk /tmp/duk-emcc-test-fixed.js
Hello world!
2+3=5

# Compile into bytecode
$ ./duk -c /tmp/duk-emcc-test-fixed.bin /tmp/duk-emcc-test-fixed.js
$ ls -l /tmp/duk-emcc-test-fixed.*
-rw-rw-r-- 1 sva sva 2852105 Jul 28 06:01 /tmp/duk-emcc-test-fixed.bin
-rw-rw-r-- 1 sva sva 1497643 Jul 28 06:01 /tmp/duk-emcc-test-fixed.js

# Execute from source
$ time ./duk /tmp/duk-emcc-test-fixed.js 
Hello world!
2+3=5

real  0m0.930s
user  0m0.907s
sys   0m0.016s

# Execute from bytecode
$ time ./duk /tmp/duk-emcc-test-fixed.bin
Hello world!
2+3=5

real  0m0.281s
user  0m0.268s
sys   0m0.012s
```

So: bytecode is larger than source (which is know, and also described in doc/bytecode.rst) but it loads a lot faster than compilation.

**Comment by svaarala** [comment]
Ok, this is now in master.

I noticed a small issue (which was already in master) for pre-C99 compilers: when GCC 3+ is used, DUK_ALWAYS_INLINE should not be defined (or rather should be defined as empty). Added a bullet to clean that up.

**Comment by haosu1987** [comment]
There is an error when it compile duk_api_bytecode.c, because the MACRO DUK_USE_BYTECODE_DUMP_SUPPORT used before the INCLUDE file.

**Comment by svaarala** [comment]
@haosu1987 I think I fixed that in the merge?

**Comment by svaarala** [comment]
https://github.com/svaarala/duktape/blob/8fbd81e597d31e5b0ec85ddf6dfe32322090dc6d/src/duk_api_bytecode.c#L13-L15

**Comment by svaarala** [comment]
Hmm, maybe there's another place than what I fixed.

**Comment by svaarala** [comment]
No, separate sources compile seems fine for me:

```
$ gcc -o /tmp/test -Isrc-separate src-separate/*.c examples/cmdline/duk_cmdline.c -lm
$ /tmp/test
((o) Duktape [no readline] 1.2.99 (v1.2.0-216-ga9423c5)
duk> 
```

**Comment by fatcerberus** [comment]
How is the bytecode larger than source?  Aren't all instructions 4 bytes?  I guess the average JS statement needs a lot of instructions...

**Comment by svaarala** [comment]
Bytecode consists of both code and constants. Consider for example:

```
a=0.1;
```

That's 6 bytes, but produces one 4-byte instruction and one 8-byte constant (12 bytes).

**Comment by svaarala** [comment]
In fact nearly all numeric and string constants will be larger in bytecode. Generic numbers are 8 bytes in IEEE format and mostly less than that as source code (e.g. "1.234"). Strings will also be larger in general, e.g. `"foo"` is 5 bytes but the corresponding serialized variant is 7 bytes (4-byte length + 3 bytes data).

**Comment by fatcerberus** [comment]
Huh, that makes sense.  It's intuitive to think of binary data as more compact than the equivalent text representation in general, but as proven in this case, it's often not true!

**Comment by bengarney** [comment]
Do you deduplicate strings/numeric constants in the bytecode format? ie a
string pool or something similar? Bytecode size isn't a huge deal but code
is often very repetitive in its use thereof... I see this feature very
commonly across bytecode formats so it's probably worth a brief
consideration.

**Comment by svaarala** [comment]
@bengarney The bytecode dump/load just dumps the in-memory representation without doing much - but the compiler dedplicates strings and number constants during compilation.

**Comment by svaarala** [comment]
@bengarney In a bit more detail, Duktape in-memory representation uses a constant table indexed by bytecode, and that constant table is used for number and string constants, except for trivial integers that can be loaded with a single opcode anyway.

**Comment by bengarney** [comment]
Ah OK - so for "real" programs the actual cost of a constant will be
amortized and likely work out fine. But if I have e.g. just a big table of
numbers  like [1.2, 3.4, 5.6, 1.2] it will be much larger.

**Comment by svaarala** [comment]
The bytecode will be larger even for stuff like `[x,x,x,x,x,x]` because there will be one or more opcodes (~4 bytes) for each member and each member is ~2 characters.

In general bytecode is about 2x larger than a minified source. That's fine because the bytecode format is not intended to be small - but fast to load into memory.

Here's a small example: https://github.com/svaarala/duktape/blob/master/doc/bytecode.rst#minimizing-code-size

**Comment by bengarney** [comment]
Cool. Great explanation, and I think it serves its goals very well. I
imagine it also compresses well with even basic zlib if you wanted to
strike a different balance between speed and size.

**Comment by fatcerberus** [comment]
What I find most interesting of all is that even with gzip compression, the source is still smaller.  I would have expected phenomenal compression due to all the redundancy in the bytecode, but minification still beats it out.

Getting back on topic, I don't understand the DUK_ALWAYS_INLINE issue.  What exactly is wrong?

**Comment by svaarala** [comment]
Didn't have time to look into it, but I'm guessing GCC doesn't like:

```
#define DUK_ALWAYS_INLINE inline __attribute__((always_inline))
```

with `-std=c89`.

**Comment by fatcerberus** [comment]
That makes some sense, I know MSVC (which has abysmal C99 support) chokes on the `inline` keyword in general and makes you replace it with `__inline`.

**Comment by svaarala** [comment]
Inlining is now restricted to gcc/clang and C99/C+11 only so there are no longer build failures with pre-C99 compilers related to this.
