### ISSUE TITLE
Remove buffer spare

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#209]
Dynamic buffers have an internal spare field which is not exposed to user code. It's used for automatic resizing when data is appended to a buffer. Current call sites include compiler bytecode emission, JSON serialization, and global object built-ins. Other than these, the spare area is not used and could be removed.

Another motivation to remove the spare and the shared buffer append/insert operations (duk_hbuffer_ops.c) is that the generated code is neither very small nor very fast. In bytecode dump/load prototype a simpler approach was used which yields better code.

- [x] Remove buffer spare from `duk_hbuffer` struct
- [x] Implement a shared alternative for appending/inserting bytes into a growing buffer
- [x] Rework call sites that depend on buffer spare - at least Ecmascript compiler, RegExp compiler, JSON, and global object
- [x] Debugger DumpHeap: remove buffer spare field (incompatible change but only impacts DumpHeap)
- [x] Internal docs etc

Call sites to fix:

- [x] duk_api_string.c: duk_map_string()
- [x] duk_bi_global.c: duk__transform_helper()
- [x] duk_bi_json.c: several calls related to serialization
- [x] duk_bi_string.c: duk_bi_string_constructor_from_char_code(), duk_bi_string_prototype_replace()
- [x] duk_lexer.c: duk__appendbuffer()
- [x] duk_js_compiler.c: duk__emit()
- [x] duk_regexp_compiler.c: duk__insert_u32(), duk__insert_i32(), duk__append_u32(), duk_append_16_list(), duk__insert_slice(), duk__append_slice(), duk__remove_slice(), duk__create_escaped_source()
- [x] duk_unicode_support.c: duk__slow_case_conversion(), duk__case_transform_helper()

Finalization:

- [x] Add comparison perf testcases in other languages for tests added in branch
- [x] Testcase coverage for affected loops / call sites
- [x] Test compile on MIPS
- [x] Test compile on Windows Cygwin
- [x] Test compile on Windows MSVC
- [x] Test262

Cleanups after merge: #250

**Comment by fatcerberus** [comment]
I'm not sure I understand the motivation for the spares in the first place.  Was it just to ensure a realloc wouldn't fail at a critical moment or...?

**Comment by svaarala** [comment]
Consider any serialization algorithm that produces an output string potentially one character at a time. No reasonable implementation would do a `realloc()` for one byte before every write. Instead, one would `realloc()` for more space once in a while, perhaps doing it 1kB or so at a time.

Dynamic buffer spare made that process part of the buffer itself so that growing the spare was entirely shared code. But because other parts of that approach don't generate very good code, it's probably better that the "spare" handling it outside the buffer object (it's still the same idiom but uses a "writer" object to manage it).

**Comment by svaarala** [comment]
The resulting code for the shared buffer writing code is not very good because every field write generates a function call, and that function call always independently checks for available buffer size, and resizes if necessary. This is somewhat reasonable for e.g. the compiler where the amount of processing per emitted bytecode instruction (for example) is rather large anyway. But for things like dumping bytecode the overhead is quite dominating.

I quickly tested an alternative to the built-in buffer spare in the bytecode dump/load branch: a buffer writer helper that provides spare management for a target buffer so that the buffer itself doesn't need to know about it. The writer is also geared more for emitting data quickly (bytecode dumping does very little processing for emitted values). Checking for available output space is also explicit and not necessary for every operation, e.g. one can:

- Ensure space for at least 8 bytes and get a pointer that'll be stable for writing at least those bytes.
- Write two 32-bit values without further checks.

The assembly generated from this looks pretty good, e.g. for writing those two values in network order:

```
# Field 1, copied as is
416557:       8b 45 60                mov    0x60(%rbp),%eax
41655a:       0f c8                   bswap  %eax
41655c:       89 41 f8                mov    %eax,-0x8(%rcx)

# Field 2: write input value & 0xfffffffcUL
41655f:       8b 45 00                mov    0x0(%rbp),%eax
416562:       83 e0 fc                and    $0xfffffffc,%eax
416565:       0f c8                   bswap  %eax
416567:       89 41 fc                mov    %eax,-0x4(%rcx)
```

The comparable code using `duk_hbuffer_ops.c` helpers would do a function call for each write and would be slower and have a larger footprint.

Anyway, if this model works well, I'll see if it also works well for JSON and the other call sites, and hopefully some of the buffer code could be stripped.

**Comment by fatcerberus** [comment]
So if I'm understanding it right, the spare is basically just what C++ `std::vector` does, where it reallocates the buffer to (as an example) twice the size when it runs out of space?  So it's not so much a "spare" as "slack space".  That makes more sense, I thought you were literally allocating two buffers for each buffer object and one was a "spare".  That's why I got confused.

**Comment by svaarala** [comment]
Yes, it's just unused space already allocated. Now that you mention it "spare" it not a very good term for it.

**Comment by svaarala** [comment]
Ok, I have a draft branch which removes the duk_hbuffer_dynamic spare and fixes all call sites to use bufwriter or some other solution. It needs some cleanup work so I'll push it after that, and merge to master after a lot more testing.

There's a slight code footprint increase at present (around +1.5 kB) but I can probably bring it down a bit. The call sites converted are a bit faster, e.g. some compilation tests are ~20% faster, also improvements to JSON parse/stringify, regexp compilation, etc.

I'll push the branch after a little bit of cleanup and also the results of a (rough) performance test run (takes several hours to run).

**Comment by svaarala** [comment]
Some intermediate perf results (absolute times don't matter, only relative):

```
test-array-read.js            : duk-O2-bufwriter  9.06 duk-O2-master  9.82 duk-O2-v122  8.60 duk-O2-v113 13.50 duk-O2-v102 14.13
test-array-write.js           : duk-O2-bufwriter  7.38 duk-O2-master  8.06 duk-O2-v122  9.85 duk-O2-v113 30.87 duk-O2-v102 30.72
test-bitwise-ops.js           : duk-O2-bufwriter  2.05 duk-O2-master  2.46 duk-O2-v122  2.63 duk-O2-v113  8.92 duk-O2-v102  8.12
test-buffer-nodejs-read.js    : duk-O2-bufwriter  9.75 duk-O2-master 10.76 duk-O2-v122  0.00 duk-O2-v113  0.00 duk-O2-v102  0.00
test-buffer-nodejs-write.js   : duk-O2-bufwriter  8.64 duk-O2-master  8.97 duk-O2-v122  0.00 duk-O2-v113  0.00 duk-O2-v102  0.00
test-buffer-object-read.js    : duk-O2-bufwriter 10.00 duk-O2-master 10.98 duk-O2-v122 32.57 duk-O2-v113 39.14 duk-O2-v102 38.46
test-buffer-object-write.js   : duk-O2-bufwriter  9.80 duk-O2-master  9.61 duk-O2-v122 38.72 duk-O2-v113 43.07 duk-O2-v102 39.50
test-buffer-plain-read.js     : duk-O2-bufwriter 10.38 duk-O2-master  9.91 duk-O2-v122  9.52 duk-O2-v113 13.95 duk-O2-v102 12.92
test-buffer-plain-write.js    : duk-O2-bufwriter  7.57 duk-O2-master  7.34 duk-O2-v122  8.96 duk-O2-v113 17.05 duk-O2-v102 14.66
test-call-basic.js            : duk-O2-bufwriter 24.50 duk-O2-master 24.17 duk-O2-v122 25.24 duk-O2-v113 33.28 duk-O2-v102 34.90
test-compile-mandel-nofrac.js : duk-O2-bufwriter 21.81 duk-O2-master 23.25 duk-O2-v122 24.71 duk-O2-v113 29.22 duk-O2-v102 29.75
test-compile-mandel.js        : duk-O2-bufwriter 26.50 duk-O2-master 26.96 duk-O2-v122 29.96 duk-O2-v113 33.81 duk-O2-v102 34.24
test-compile-short.js         : duk-O2-bufwriter 17.09 duk-O2-master 16.20 duk-O2-v122 16.56 duk-O2-v113 18.97 duk-O2-v102 20.05
test-empty-loop.js            : duk-O2-bufwriter  4.34 duk-O2-master  4.50 duk-O2-v122  6.29 duk-O2-v113  9.87 duk-O2-v102  9.94
test-fib.js                   : duk-O2-bufwriter 12.79 duk-O2-master 13.32 duk-O2-v122 13.93 duk-O2-v113 15.46 duk-O2-v102 16.27
test-hello-world.js           : duk-O2-bufwriter  0.00 duk-O2-master  0.00 duk-O2-v122  0.00 duk-O2-v113  0.00 duk-O2-v102  0.00
test-hex-decode.js            : duk-O2-bufwriter  7.96 duk-O2-master  7.76 duk-O2-v122  8.13 duk-O2-v113 13.45 duk-O2-v102 12.91
test-hex-encode.js            : duk-O2-bufwriter 59.74 duk-O2-master 59.59 duk-O2-v122 60.02 duk-O2-v113 68.55 duk-O2-v102 41.28
test-json-serialize.js        : duk-O2-bufwriter  4.42 duk-O2-master  4.63 duk-O2-v122  4.85 duk-O2-v113  4.85 duk-O2-v102  5.06
test-json-string-bench.js     : duk-O2-bufwriter  8.86 duk-O2-master  8.53 duk-O2-v122  8.16 duk-O2-v113 10.90 duk-O2-v102 10.84
test-json-string-parse.js     : duk-O2-bufwriter  1.12 duk-O2-master  5.38 duk-O2-v122  5.30 duk-O2-v113  5.66 duk-O2-v102  5.58
test-json-string-stringify.js : duk-O2-bufwriter  2.33 duk-O2-master  6.26 duk-O2-v122  6.52 duk-O2-v113  6.61 duk-O2-v102  5.91
test-prop-read.js             : duk-O2-bufwriter 15.62 duk-O2-master 16.90 duk-O2-v122 14.60 duk-O2-v113 22.74 duk-O2-v102 24.47
test-prop-write.js            : duk-O2-bufwriter 11.90 duk-O2-master 12.50 duk-O2-v122 13.08 duk-O2-v113 20.06 duk-O2-v102 18.34
test-reg-readwrite-object.js  : duk-O2-bufwriter  7.55 duk-O2-master  7.88 duk-O2-v122  7.78 duk-O2-v113 14.58 duk-O2-v102 15.86
test-reg-readwrite-plain.js   : duk-O2-bufwriter  5.85 duk-O2-master  5.84 duk-O2-v122  5.86 duk-O2-v113  7.82 duk-O2-v102  8.09
test-regexp-string-parse.js   : duk-O2-bufwriter 12.35 duk-O2-master 16.11 duk-O2-v122 20.65 duk-O2-v113 20.68 duk-O2-v102 19.96
test-string-array-concat.js   : duk-O2-bufwriter 12.01 duk-O2-master 11.34 duk-O2-v122 11.53 duk-O2-v113 36.07 duk-O2-v102 34.61
test-string-compare.js        : duk-O2-bufwriter  7.62 duk-O2-master  7.31 duk-O2-v122  7.47 duk-O2-v113 10.00 duk-O2-v102 10.70
test-string-decodeuri.js      : duk-O2-bufwriter  5.56 duk-O2-master  6.05 duk-O2-v122  6.28 duk-O2-v113  6.18 duk-O2-v102  6.30
test-string-encodeuri.js      : duk-O2-bufwriter  6.95 duk-O2-master 11.55 duk-O2-v122 10.96 duk-O2-v113 11.24 duk-O2-v102 10.24
test-string-intern-match.js   : duk-O2-bufwriter  5.42 duk-O2-master  5.54 duk-O2-v122  5.53 duk-O2-v113  5.59 duk-O2-v102  2.92
test-string-intern-miss.js    : duk-O2-bufwriter  5.72 duk-O2-master  5.70 duk-O2-v122  5.65 duk-O2-v113  6.14 duk-O2-v102  3.46
test-string-plain-concat.js   : duk-O2-bufwriter 11.08 duk-O2-master 10.99 duk-O2-v122 11.30 duk-O2-v113 11.14 duk-O2-v102  4.70
test-string-uppercase.js      : duk-O2-bufwriter  5.85 duk-O2-master  7.29 duk-O2-v122  7.32 duk-O2-v113  7.04 duk-O2-v102  7.06
```

The measurement is not very accurate so differences of <0.5sec or so may not be meaningful.

I'll work in a few JSON optimizations in the branch which should improve parsing just a little bit more.

**Comment by svaarala** [comment]
Here's the current work branch after most of the necessary cleanup: https://github.com/svaarala/duktape/compare/remove-dynbuf-spare-size

Still needs a bit of work before a merge, and better test coverage for all affected places.,

**Comment by svaarala** [comment]
Okay, this is now merged to master.  Because any bugs in the change may introduce very difficult-to-diagnose memory safety issues, I've tried to improve test coverage to cover all the affected code paths, and I've done quite a lot of testing with assertions and valgrind.  Also tested compilation on MIPS (big endian), and Windows Mingw, MSVC x86, and MSVC x64. But, if you encounter something weird, let me know.

Final change on code footprint compared to master (x64, gcc -Os):

- +552 bytes with fastpaths disabled

- +1472 bytes with fastpaths enabled (on x64 using gcc)

The new JSON fastpaths are enabled by default; for low memory environments, you may want to disable them to reduce code footprint slightly.

**Comment by fatcerberus** [comment]
1.4k additional footprint for x64 isn't bad at all for a 22x speedup. :)

**Comment by JoshEngebretson** [comment]
Looks like I will be updating today, thanks Sami!

**Comment by svaarala** [comment]
@JoshEngebretson Just to note, this branch doesn't yet include the specific JSON.stringify() fastpath @fatcerberus was referring to. I've rebased that branch and it's close to being merge-able, there's one portability issue to resolve.

**Comment by JoshEngebretson** [comment]
Oh ok, thanks for the clarification, I will hold off a little bit then, no problem.

**Comment by svaarala** [comment]
@JoshEngebretson There are some performance improvements in master already but not that specific fastpath. It'd be very useful if you could test master quickly to ensure nothing has broken for you :)

**Comment by JoshEngebretson** [comment]
I updated to master, the only different option I am using is DUK_OPT_NO_VOLUNTARY_GC

So far everything is working, I'll report if I run into any quirks!

**Comment by svaarala** [comment]
Thanks Josh, it's very good to get coverage for the new code quickly :)

**Comment by JoshEngebretson** [comment]
Atomic hits it pretty hard, no problem, I like being useful! :)

**Comment by fatcerberus** [comment]
I think I should get Cygwin set up to build the distributables so I can test out the WIP 1.3.0 in minisphere, I'm missing out on a lot of neat stuff. :)

**Comment by svaarala** [comment]
There's some progress in migrating to CMake so perhaps you can avoid Cygwin in the near future. But here's a snapshot with this change included: http://duktape.org/snapshots/duktape-1.2.99-20150805191826-v1.2.0-257-gb098f04.tar.xz

I'm pretty close to merging the JSON stringify fastpath branch so I'll post a snapshot link for that too.

**Comment by fatcerberus** [comment]
Thanks Sami, you didn't have to do that. :)

**Comment by svaarala** [comment]
I should probably change the cronjob to build when the master changes rather than nightly; there's no point building when master doesn't change and when it does, the snapshot should be online faster.

**Comment by svaarala** [comment]
Ok, now it checks for updated master hourly and builds as needed.

**Comment by fatcerberus** [comment]
All this time I never knew you had nightly builds available... That's nice, now I won't have to bug you for snapshots anymore. ;-)
