### ISSUE TITLE
Make "invalid base value" more informative

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#210]
Currently the `invalid base value` error is a bit too vague--it doesn't tell you the name of the variable that you're trying to access and is just in general very difficult to diagnose.  Would it be possible to reword this error message to make it clearer, something like what SpiderMonkey says in this case: `'varName' has no properties`

**Comment by svaarala** [comment]
Some discussion in #253.

**Comment by svaarala** [comment]
Possible concrete change:

- Add config option to include property key for "invalid base value" error, with default enabled.
- Note in sandboxing document that if keys can be sensitive, turn the option off.
- Reword the error message to indicate it's a property lookup error.

**Comment by fatcerberus** [comment]
Regarding the security discussion in the other thread: I think convenience should definitely be the default, with documentation on how to turn those features off.  I mainly worry that focusing too much on security may lull users into a *false* sense of security where they think that just because the engine is secure they don't have to follow best-practices.  I've seen that happen too often.
