### ISSUE TITLE
How is object env used?

### ISSUE THREAD

**Issue by wdoreen** [svaarala/duktape#2104]
I run Javascript code in my C++ project by calling Duktape API duk_peval_string.
In my Javascript code, I have this line:
Duktape.env();

However, this gives me error:
TypeError\: 'll u n p2 a4 x64 linux gcc' not callable (property 'env' of [object Object])

This error message looks confusing. What does this mean? How should env object be used?
I searched in the user's guide, but couldn't find much information on the env.
Thanks.

**Comment by svaarala** [comment]
It's covered here: https://duktape.org/guide.html#builtin-duktape-env.
