### ISSUE TITLE
Is there an configuration option to disable Duktape.env?

### ISSUE THREAD

**Issue by wdoreen** [svaarala/duktape#2105]
Similar to DUK_USE_DUKTAPE_BUILTIN which can disable Duktape.pointer() usage. Is there a way to disable Duktape.env so that Duktape.env won't output system/compiler information?
Thanks.

**Comment by svaarala** [comment]
Not at present; it wouldn't be difficult to add.

But, you can also just run the following after you have created the Duktape heap (and after creating a new global context if you do that):
```c
duk_eval_string(ctx, "delete Duktape.env");
```

**Comment by svaarala** [comment]
Also, it's quite likely `Duktape.env` will be removed at some point when the Duktape built-in is reorganized. For some of the bindings it might be better if they were by default only available to C code (not JS code).

**Comment by wdoreen** [comment]
Thanks for your reply!
