### ISSUE TITLE
Question: What's the command used for generating the duktape 2.3.0 release codes?

### ISSUE THREAD

**Issue by wdoreen** [svaarala/duktape#2109]
I downloaded Duktape 2.3.0 release and used the command "python tools/configure.py --output-directory /tmp/output --source-directory src-input --config-metadata config"(https://wiki.duktape.org/configuring2x) to try regenerating "src" folder. Compared to the original "src" folder from the release, in the newly generated "src" folder, the line 3066-3640(Checks for legacy feature options) in duk_config.h are gone. Also, in duktape.c, the lines such as "#line 1 "duk_exception.h"" are all gone. These lines are for indicating in which file under src-input directory the following codes are from. 
Could you please let me know what command(specifically the options used in the configure.py command) was used when generating the 2.3.0 release codes?
Thanks!

**Comment by svaarala** [comment]
Hi,

The default sources are generated by dist.py:
- https://github.com/svaarala/duktape/blob/master/util/dist.py#L802-L821
- Call site for src/ is https://github.com/svaarala/duktape/blob/master/util/dist.py#L823

**Comment by wdoreen** [comment]
Thanks!
