### ISSUE TITLE
Controlling execution (infinite loops)

### ISSUE THREAD

**Issue by Cubiverse** [svaarala/duktape#211]
Hi,

I've been investigating duktape for a replacement to V8, but I'm not able to understand the mechanism used to detect infinite loops.

In the cmdline utility I can see the ajsheap_start_exec_timeout and ajsheap_clear_exec_timeout calls being made, but I can't see where the ajsheap_exec_timeout_check() is fired from - it doesn't seem to be referenced.

Is there a more complete guide or resource on how to detect infinite loops?

James

**Comment by svaarala** [comment]
There's some documentation here:

- https://github.com/svaarala/duktape/blob/master/doc/feature-options.rst#duk_opt_exec_timeout_check
- https://github.com/svaarala/duktape/blob/master/doc/sandboxing.rst#bytecode-execution-timeout-details

**Comment by svaarala** [comment]
Closing as inactive.
