### ISSUE TITLE
Understanding prototypes and enumerations

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#2111]
I'm trying to enumerate properties of a "class" type I have defined in my app. However, I cannot get the right properties enumerated. The setup is this:

1. There's a base class `EventEmitter`.
2. This has a number of properties + methods, set on its prototype.
3. There's another class `Process` "derived" from `EventEmitter`.
3. This also has some properties defined on the `Process` prototype.
4. Finally there's an instance of that `Process` class.

Now trying to enumerat only the `Process` properties fails either with showing nothing (when using `DUK_ENUM_OWN_PROPERTIES_ONLY`) or all members of both `Process` and `EventEmitter` (when not using this flag). What would be the right way to only get the members defined on `Process`?

**Comment by svaarala** [comment]
The easiest first step is to express what you want in pure Ecmascript.

If I understand correctly you would want to enumerate the immediate parent prototype related to the instance? If so, you would do something like:
```javascript
// Or Object.keys() if you just want enumerable properties.
Object.getOwnPropertyNames(Object.getPrototypeOf(instance));
```

If you wanted to specifically enumerate `Process.prototype`, you would just use that in the expression.

**Comment by mike-lischke** [comment]
Actually, I expected that when I enumerate own keys of an object (a function) this would include those of the prototype as well. From an inheritance standpoint (if you can name it so) the direct prototype is essentially part of the instantiated object, no?

Meanwhile I worked around this problem by doing 2 enumeration steps: 1. the object itself, 2. it's direct prototype. That gives me all I want, but looks a bit hacky. Also because the prototype for instanatiated objects and constructor functions ("classes") is different:

```C++
  ...
  duk_enum(ctx, -1, enumFlags);
  while (duk_next(ctx, -1, 1)) {
    // stack [ ... enum key value ]
    std::string key = duk_get_string(ctx, -2);
    if (key == "prototype") {
      duk_pop_2(ctx);
      continue;
    }
  ... recursively dump the member
  }

  duk_pop(ctx); // Remove the enumerator.

  // Now enumerate the immediate prototype.
  duk_get_prop_string(ctx, -1, "prototype"); // For classes.
  if (duk_is_undefined(ctx, -1)) {
    duk_pop(ctx);
    duk_get_prop_string(ctx, -1, "__proto__"); // For objects.
  }

  if (!duk_is_undefined(ctx, -1)) {
    duk_enum(ctx, -1, enumFlags);
    while (duk_next(ctx, -1, 0)) {
  ...
```

Btw. I tried to find the equivalent of `getOwnPropertyNames` but couldn't find anything that comes close, name wise. I guess the `duk_enum()` is what's used on C side instead (which I did)?

**Comment by svaarala** [comment]
> From an inheritance standpoint (if you can name it so) the direct prototype is essentially part of the instantiated object, no?

Hmm, I'm not 100% sure what you mean here. At least in Ecmascript the instance is considered a separate object for property handling purposes which serves at least two important points: (1) it keeps the instance size small as most properties are inherited (and not "own" properties), (2) it ensures that it's difficult to write to the prototype, affecting all instances, by accident (which is why writes go the instance).

I guess it would be technically possible for e.g. enumeration to obey some other conceptual model, 
like recognizing instantiated objects and including their direct prototype in the enumeration result. This would be difficult without a lot of changes because in its core, Ecmascript doesn't really differentiate between instances and classes. It's all just objects with prototypes, despite the sugar.

> Btw. I tried to find the equivalent of getOwnPropertyNames but couldn't find anything that comes close, name wise. I guess the duk_enum() is what's used on C side instead (which I did)?

Object.keys(), Object.getOwnPropertyNames() etc are all covered by `duk_enum()`, that's correct.

**Comment by mike-lischke** [comment]
> > From an inheritance standpoint (if you can name it so) the direct prototype is essentially part of the instantiated object, no?
> 
> Hmm, I'm not 100% sure what you mean here. At least in Ecmascript the instance is considered a separate object for property handling purposes

Well, I'm too much into the C/C++ world here I guess, where the instance of a class (the object) of course also includes all the methods that are declared in the class. Not so in JS, but that's not true inheritance anyway. I just hoped there would be something that at least simulates this behavior in JS:

Thanks for your help Sami.

**Comment by svaarala** [comment]
You're welcome, I hope you found a satisfactory solution.
