### ISSUE TITLE
Repeated bytecode execution timeouts not working

### ISSUE THREAD

**Issue by sstruchtrup** [svaarala/duktape#212]
I observed that after bytecode execution was interrupted once due to a timeout, the timeout is not checked anymore.

As far as I can see, the problem seems to be that the code handling a timeout in `duk__executor_interrupt()` does not reset the "interrupt running" state for the given heap.

Further invocations of `duk__executor_interrupt()` will abort (DD message: "nested executor interrupt, ignoring").

See sstruchtrup/duktape@0a2149e164ad3f6fe58e0ad6046d6131c13fa6ce for a proposed fix - I can't judge if this is the correct approach, but I assume.

**Comment by sstruchtrup** [comment]
A simple test program to demonstrate the problem. It runs three endless loops `for (;;) ;`, which can be interrupted by SIGINT/Ctrl-C.

Compiled with `-DDUK_OPT_INTERRUPT_COUNTER` and `-DDUK_OPT_EXEC_TIMEOUT_CHECK=timeout_check `.


	#include <time.h>
	#include <stdio.h>
	#include <signal.h>
	#include <unistd.h>
	#include "duktape.h"

	volatile int interrupted = 0;

	void sigint(int n)
	{
		write(1, "SIGINT\n", 7);
		interrupted++;
		
		if (interrupted == 3)
		{
			write(1, "interrupted flag not honoured. Bailing out.\n", 44);
			_exit(1);
		}
	}

	duk_bool_t timeout_check(void *udata)
	{
		return interrupted;
	}

	void jsloop(duk_context *ctx, int i)
	{
		fprintf(stderr, "==> Loop %d\n", i);

		interrupted = 0;
		
		duk_peval_string(ctx, "for (;;) ;");
		fprintf(stderr, "%s\n\n", duk_safe_to_string(ctx, -1));
		duk_pop(ctx);
	}

	int main(int argc, char **arv)
	{
		int i;
		
		struct sigaction sa;
		sa.sa_handler = sigint;
		sa.sa_flags = SA_RESTART;
		sigaction(SIGINT, &sa, NULL);

		duk_context *ctx = duk_create_heap_default();
		
		for (i = 0; i < 3; i++)
			jsloop(ctx, i);
	}

**Comment by svaarala** [comment]
This regression seems to have snuck in when a debugger-related issue (debugger evals causing nested invocations) was fixed. The fix looks correct. Thanks!

**Comment by svaarala** [comment]
In addition to fixing this particular issue, it'd be nice to have a regression test for this mechanism (it's not currently covered).

**Comment by svaarala** [comment]
Fix now in master and cherry picked to v1.2-maintenance for an eventual 1.2.3 release.
