### ISSUE TITLE
Duktape doesn't compile with DUK_USE_CPP_EXCEPTIONS defined

### ISSUE THREAD

**Issue by wdoreen** [svaarala/duktape#2125]
Hi,

I have Duktape-2.3.0. I'm trying to make fatal error handler throw exceptions, so I set the default to true in DUK_USE_CPP_EXCEPTIONS.yaml. In the generated duk_config.h, DUK_USE_CPP_EXCEPTIONS is defined. 
However, building the src/ directory fails with Makefile.staticlibrary.
The errors are "unknown type name ‘class’", "unknown type name ‘throw'" etc. It seems that the C++ syntax is not supported. 
What could cause this? Is there additional configurations that also need to be changed to to support DUK_USE_CPP_EXCEPTIONS?

Thanks!

**Comment by svaarala** [comment]
You shouldn't modify the config option files, but instead run:
```
$ python tools/configure.py -DDUK_USE_CPP_EXCEPTIONS [...]
```

See comments in https://github.com/svaarala/duktape/blob/master/examples/cpp-exceptions/cpp_exceptions.cpp.

**Comment by wdoreen** [comment]
That works. Thanks!
