### ISSUE TITLE
What's the reason for having a double member in union of sandbox memory control example

### ISSUE THREAD

**Issue by wdoreen** [svaarala/duktape#2139]
In this example https://github.com/svaarala/duktape/blob/master/examples/sandbox/sandbox.c
typedef struct {
	/* The double value in the union is there to ensure alignment is
	 * good for IEEE doubles too.  In many 32-bit environments 4 bytes
	 * would be sufficiently aligned and the double value is unnecessary.
	 */
	union {
		size_t sz;
		double d;
	} u;
} alloc_hdr;

According to the comment, the "double" data type is added to union for alignment. I'm not quite understand what this means. Can you be more specific why we need "double" here?
If we don't have "double", size_t is 4 bytes in 32-bit system and 8 bytes in 64-bit system. What's the issue that will be caused because of this?

**Comment by svaarala** [comment]
If `size_t` is 32 bits, the union may only align to 4 which is not sufficient for natural alignment of a double.
