### ISSUE TITLE
Push Empty Function

### ISSUE THREAD

**Issue by koush** [svaarala/duktape#2148]
Is there a function equivalent for duk_push_object, that pushes a Function? Is it possible to do it with the other primitive type methods? I ran into some strange behavior pushing a C function as a proxy trap, and it was resolved by using an actual JS function:

```javascript
  // this fails
  // duk_push_c_function(m_context, some_noop_c_function, 0)

  // this works
  duk_eval_string(m_context, "(function(){});");
  // ...
  duk_push_proxy(...);
```

**Comment by svaarala** [comment]
There's no primitive like that at the moment, so duk_eval_string() (or duk_peval_string() if the call site itself is not protected) is probably your best bet at present.

Native (Duktape/C function) traps should work normally however.
