### ISSUE TITLE
Stack management question

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#215]
Is it necessary to clean up the valstack when returning from a Duktape/C function or throwing an error, or will Duktape do it automatically?  I ask because there are several locations where I added extra handling like this, to avoid leaks and also keep the stack state consistent:

```c
	else if (duk_is_null_or_undefined(ctx, index))
		return 0;
	else {
		duk_pop_2(ctx);  // <-- awkward
		duk_error_ni(ctx, -1, DUK_ERR_TYPE_ERROR, "Script must be string, function, or null/undefined");
	}
```

And it would of course greatly simplify things if I didn't have to do that.

**Comment by svaarala** [comment]
Whenever you return from a function Duktape will pick up the possible return value from the stack top and otherwise unwind the stack automatically. Same goes when throwing errors.

**Comment by fatcerberus** [comment]
Thanks, that'll save me a lot of tedious stack-juggling if I can count on Duktape unwinding the extra stuff for me automatically. :)
