### ISSUE TITLE
SyntaxError: parse error

### ISSUE THREAD

**Issue by moar82** [svaarala/duktape#2150]
I have a js script called [numeral](https://pastebin.com/R90FeyW2)
which works fine, If I execute it using:
`duk numeral.js`
However, If I embedded into a c program, using duktape.c , duktape.h from duktape/src, I got 

> SyntaxError: parse error (line 518)

` _currSymbol = localeData.currency.symbol;`

I do not see error in this line.  Additionally, this does not happens with the other js scripts that I have.  
Any idea?

Here is my C code for reference
[harness.c](https://pastebin.com/qBX34qHH)

Regards.

**Comment by svaarala** [comment]
Have you verified that the input string is not truncated when it is read from the file and pushed into the value stack?

**Comment by svaarala** [comment]
This is easy to verify if you:
```
printf("%s\n", duk_require_string(ctx, -1));
```
after you push the file contents.

**Comment by svaarala** [comment]
Quickly looking at harness.c, it may be that the input is truncated to 17384 bytes. The push_file_as_string() function should either use a larger buffer, or more preferably, deal with partial reads so that the entire file gets read.

**Comment by moar82** [comment]
Thanks @svaarala  for your quick answer.  Indeed this was the problem.  The original numeral.js file weights ~34 kb.  I run my test using the minificate version (which is only ~ 11 kb) and it worked fine.

Regards,
Rodrigo.

**Comment by svaarala** [comment]
There are several ways to deal with reading in arbitrary sized files, e.g.:
- First use fseek() to find out the file size, then malloc() a buffer (or use duk_push_fixed_buffer() to do that, getting free GC) and read the file into the buffer. Finally, push it as a string. This approach avoids the need to realloc or use a huge stack buffer, but there's an inherent race between reading the file size and its contents (which is often a non-issue).
- Read the file in parts to a buffer that is realloc()'d if it is exhausted. This has the upside of dealing with partial reads with the same code that is used when the buffer is exhausted. Finally, push the contents as a string.

**Comment by svaarala** [comment]
duk_cmdline.c incidentally has examples of both of these approaches; one in the readFile() binding, and another in handle_fh().

**Comment by svaarala** [comment]
This would have been easier to identify if there was a hint in the syntax error message, so opened #2151.
