### ISSUE TITLE
Extending Duktape.Pointer.prototype

### ISSUE THREAD

**Issue by Epiphane** [svaarala/duktape#217]
I'm trying to pass around a Duktape.Pointer object but add some functionality to it as well. I tried extending the Pointer prototype as follows:

```
duk_push_global_object(ctx);
duk_get_prop_string(ctx, -1, "Duktape");           // Get Duktape
duk_get_prop_string(ctx, -1, "Buffer");            // Get Duktape.Pointer
duk_get_prototype(ctx, -1);                        // Get Duktape.Pointer.prototype
duk_enum(ctx, -1, DUK_ENUM_INCLUDE_NONENUMERABLE); // Enumerate Duktape.Pointer.prototype
duk_push_global_object(ctx);                       // save global context for later

duk_idx_t new_proto = duk_push_object(ctx);
while (duk_next(ctx, -3, 1)) {                     // for (key in Duktape.Pointer)
   duk_put_prop(ctx, -3);                          //    new_proto[key] = Duktape.Pointer.prototype[key]
}

duk_put_prop_string(ctx, -2, "myPointer");         // Define it globally
duk_pop(ctx);                                      // Pop global context
```

and then in my script, I call:

```
print(myObject.valueOf());
```

If `myObject.__proto__ == Duktape.Pointer.prototype`, this works as intended, but if i call it when `myObject.__proto__ == myPointer`, then it throws a type error.

Presumably this is because, by changing the prototype `myObject` isn't recognized anymore as a pointer object. Is there any way to circumvent this besides adding functions to the Duktape.Pointer object?

**Comment by svaarala** [comment]
Probably a typo, but there's a Buffer in the example:

> duk_get_prop_string(ctx, -1, "Buffer");            // Get Duktape.Pointer

Could you paste a traceback of the TypeError? How do you create a myObject so that it would be a pointer instance?

The Duktape.Pointer.prototype functions except the "this" binding to be a pointer object. Concretely, they expect the object to have an internal `_Value` property which contains the primitive pointer value.

**Comment by Epiphane** [comment]
Oops, yes it's `Pointer` in my code.

Here's my program output:
```
myObject info:
typeof(myObject): object
myObject.toString: function toString() {/* native */}
myObject.valueOf: function valueOf() {/* native */}

/* Tried calling myObject.valueOf() */
type error (rc -105)                              
Traceback:
TypeError: type error (rc -105)
    toString  native strict preventsyield
    global world/tavern.js:8 preventsyield
```

And here's where I initialize `myObject`:
```
// Current stack: |...|global
duk_push_pointer(ctx, game->getPlayer());
duk_to_object(ctx, -1);

duk_get_prop_string(ctx, -2, "myPointer");  // Get myPointer prototype
duk_set_prototype(ctx, -2);                 // myObject.__proto__ = myPointer

duk_put_prop_string(ctx, -2, "myObject");   // Define myObject globally
duk_pop(ctx);                               // Pop global context 
```

If I comment out the two middle lines, then it does not throw any error and prints out the pointer value as expected

**Comment by svaarala** [comment]
Hmm, what does this print:

```
print(Object.prototype.toString.call(myObject));
```

**Comment by Epiphane** [comment]
`[object Pointer]` in both cases, actually.

**Comment by svaarala** [comment]
Hmm, could you try the following:

```
print(typeof myObject.valueOf());
```

It seems that perhaps valueOf() succeeds but trying to print the result fails (based on the traceback).

**Comment by Epiphane** [comment]
`typeof(myObject.valueOf())` returns `object` when I use my custom prototype, which I'm assuming should be `pointer` (based on the default constructor)

**Comment by svaarala** [comment]
Yeah, that's a problem, not sure why that would be.

**Comment by svaarala** [comment]
Ah, I think I know the reason. The internal prototype of `Duktape.Pointer` is not `Duktape.Pointer.prototype` but `Function.prototype` because `Duktape.Pointer` is a constructor function. Your code seems to copy the `Function.prototype` values because:

> duk_push_global_object(ctx);
> duk_get_prop_string(ctx, -1, "Duktape");           // Get Duktape
> duk_get_prop_string(ctx, -1, "Pointer");            // Get Duktape.Pointer
> duk_get_prototype(ctx, -1);                        // Get Duktape.Pointer.prototype   <== problem

So, you could try changing to:

```
duk_push_global_object(ctx);
duk_get_prop_string(ctx, -1, "Duktape");           // Get Duktape
duk_get_prop_string(ctx, -1, "Pointer");            // Get Duktape.Pointer
duk_get_prop_string(ctx, -1, "prototype");
```

If this only happens during setup, btw, you could just eval:

```
duk_eval_string(ctx, "Duktape.Pointer.prototype");
```

**Comment by Epiphane** [comment]
That worked, thanks!

**Comment by svaarala** [comment]
Good to hear, internal (effective) and external prototypes can be confusing :)
