### ISSUE TITLE
Feature request: Simplify object function access

### ISSUE THREAD

**Issue by kphillisjr** [svaarala/duktape#218]
Currently there is no good way to handle object access from the C Functions. This is an extremely useful feature to help with Implementing support for ECMAScript 6 ( aka ECMAScript 2015 ).  I have already put some thought into some of the public API that would help with the implementation of this function.

The first bit would be the addition of a new define. I believe it would be worth while to use duk_c_object_function as a good start on this feature...

``` C
typedef duk_ret_t (*duk_c_object_function)(duk_context *ctx, void* UserData);
duk_idx_t duk_push_c_object_function(duk_context *ctx, duk_c_object_function func, duk_idx_t nargs, void* UserData);
```

Also, since I am suggesting these new functions and typedefs, I believe it would not hurt to provide a short example...

``` C
typedef struct duk_example_c_object
{
    double example_value;
} duk_example_c_object;

duk_ret_t example_object_get_a(duk_context *ctx, void *UserData)
{
    duk_example_c_object *MyObjectData = (duk_example_c_object*)UserData;
    duk_push_number(ctx, MyObjectData->example_value);
    return 1;  /* one return value */
}

duk_ret_t example_object_set_a(duk_context *ctx, void *UserData)
{
    duk_example_c_object *MyObjectData = (duk_example_c_object*)UserData;
    double newValue = duk_get_number(ctx, 0);
    if(newValue < 0.0f) {
        duk_push_string(ctx, "Object Values Must be positive!");
        duk_throw(ctx);
        return 1;
    }
    //TODO: This needs an example.
    MyObjectData->example_value = duk_get_number(ctx, 0);
    return 1;  /* one return value */
}

duk_ret_t example_object_constructor(duk_context *ctx) {
    duk_idx_t obj_idx = /* ... */;
    /* TODO: This needs some Object Creation Code to be considered Complete */
    duk_example_c_object myObject;
    myObject.example_value = 0.0f;
    duk_push_string(ctx, "a");
    duk_push_c_object_function(ctx, example_object_get_a, 0 /*nargs*/, (void*)&myObject);
    duk_push_c_object_function(ctx, example_object_set_a, 1 /*nargs*/, (void*)&myObject);
    duk_def_prop(ctx,
                 obj_idx,
                 DUK_DEFPROP_HAVE_GETTER |
                 DUK_DEFPROP_HAVE_SETTER);
}
```

**Comment by fatcerberus** [comment]
You can already do this, just store the userdata pointer as an internal property of the object, like this:

```c
duk_push_object(ctx);
duk_push_pointer(ctx, userdata);
duk_put_prop_string(ctx, "\xff""udata");
// wire up methods and properties and stuff
```

Then in your C method:
```c
duk_ret_t myobj_get_a(duk_context* ctx) {
  duk_push_this(ctx);
  duk_get_prop_string(ctx, "\xff""udata");
  myobj_t* ptr = duk_get_pointer(ctx, -1);
  duk_pop(ctx);
  // do stuff with ptr
}
```

**Comment by kphillisjr** [comment]
Thanks for the heads up on how to access a user pointer. Also I was wondering, with the suggested method is there any chance that you could accidentally modify the user pointer from within the scripts themselves?

Also on a side note, there is a lot of changes for ECMAScript 2015 (aka ECMAScript 6 ) that need to be implemented and have examples added.

[Exploring ES6](http://exploringjs.com/) - A great book covering ECMAScript 2015
[2ality Javascript Bog](http://www.2ality.com/) - The Blog for the author that Created this book.

**Comment by fatcerberus** [comment]
You can get at the pointer using buffer-fu, but it's impossible to do so accidentally with pure JS.  That's the reason for the \xff byte before the "udata" string, it makes it invalid UTF-8 and thus inaccessible from script.

**Comment by svaarala** [comment]
Closing as there isn't a concrete change proposal.
