### ISSUE TITLE
Feature request: Example using Objects as native function paramaters

### ISSUE THREAD

**Issue by kphillisjr** [svaarala/duktape#219]
I was looking over the various examples and noticed that there is no good example of how to work with two objects as function parameters. To begin with Take the following javascript as an example:

``` JavaScript
var VectorOne = { x: 1, y: 2 };
var VectorTwo = { x: 1, y: 2 };


function printVector( inVec ) {
    print('X = ' + inVec.x + ' Y = ' + inVec.y)
}

function vectorAdd( inVecA, inVecB ) {
    var outVec = { x: 0, y: 0 };
    outVec.x = inVecA.x + invecB.x;
    outVec.y = inVecA.y + invecB.y;
    return OutVec;
}

// Print the Value of Vector 1:
print('Vector Addition Example:');
print( 'Vector 1:');
printVector( VectorOne );
print( 'Vector 2:');
printVector( VectorTwo );
print( 'Result of Vector 1 + Vector 2');
var resultVec = vectorAdd( VectorOne , VectorTwo  );
printVector( resultVec  );

var nativePrintVector = printVector; // TODO: Implement nativePrintVector in C.
var nativeVectorAdd  = vectorAdd; //TODO: Implement nativeVectorAdd in C.

print('Native Function Results for Vector Adition:');
print( 'Vector 1:');
nativePrintVector(VectorOne);// TODO: Implement this call using native functions.
print( 'Vector 2:');
nativePrintVector(VectorOne);
var nativeResultVec = nativeVectorAdd( VectorOne , VectorTwo );
print( 'Result of Vector 1 + Vector 2');
printVector( nativeResultVec  ); // Should be the same as the previous result.
```

**Comment by fatcerberus** [comment]
This kind of thing can be confusing because the entire Duktape C API is all stack-based: the value stack really is the most important primitive.  Admittedly it can get a bit hairy though.

Basically what you want to look into is the function `duk_get_prop_string()`.  For example:

```c
// get the value of the "x" property of the object at index 0
// and push it onto the valstack
duk_get_prop_string(ctx, 0, "x"); // first func. param
int x = duk_get_int(ctx, -1); // -1 = stack top
duk_pop_2(ctx);
```

Note that the value stack is completely different from the C and JS call stacks.

**Comment by kphillisjr** [comment]
I know that this is where the Duktape C API gets confusing, and this is why I am specifically requesting solutions to these type of problems. It is to greatly simplify the task of enabling developers to implement solutions using Duktape itself. 

Just to make sure, Based on what your saying, The native print function should be implemented using... 

```C
duk_ret_t nativePrintVector(duk_context *ctx) {
	int x = 0, y = 0;	
	// Get the First Object's Parameters:
	
	// get the value of the "x" property of the object at index 0
	// and push it onto the valstack
	duk_get_prop_string(ctx, 0, "x"); // first func. param
	x = duk_get_int(ctx, -1); // -1 = stack top
	duk_pop_2(ctx);
	// get the value of the "y" property of the object at index 0
	// and push it onto the valstack
	duk_get_prop_string(ctx, 0, "y"); // first func. param
	y = duk_get_int(ctx, -1); // -1 = stack top
	duk_pop_2(ctx);	
	
	// print the result to the console.
	printf("X: %D Y: %D", x, y);
	return 1;
}
````

And as far as the native vector addition function, this should be...

```C
// get the value of the "x" property of the object at index 0
// and push it onto the valstack
duk_ret_t nativeVectorADD(duk_context *ctx) {
	int x1 = 0, x2 = 0, y1 = 0, y2 = 0;	
	// Get the First Object's Parameters:
	duk_get_prop_string(ctx, 0, "x"); // first func. param
	x1 = duk_get_int(ctx, -1); // -1 = stack top
	duk_pop_2(ctx);
	duk_get_prop_string(ctx, 0, "y"); // first func. param
	y1 = duk_get_int(ctx, -1); // -1 = stack top
	duk_pop_2(ctx);	

	// Get the Second Vector's Values:
	duk_get_prop_string(ctx, 1, "x"); // first func. param
	x1 = duk_get_int(ctx, -1); // -1 = stack top
	duk_pop_2(ctx);
	duk_get_prop_string(ctx, 1, "y"); // first func. param
	y1 = duk_get_int(ctx, -1); // -1 = stack top
	duk_pop_2(ctx);	
	
	// Return the Object.
	duk_push_object(ctx);
	duk_push_int(ctx, x1 + x2);
	duk_put_prop_string(ctx, -2, "x"); 
	duk_push_int(ctx, y1 + y2);
	duk_put_prop_string(ctx, -2, "y");
	return 1;
}
```

And lastly, elsewhere in the code the functions need to be registered using...

```C
// Remember to Register these functions.
duk_push_global_object(ctx);
duk_push_c_function(ctx, nativePrintVector , 1); // TODO: Verify that the number of parameters is correct. This should be 1 object.
duk_put_prop_string(ctx, -2 /*idx:global*/, "nativePrintVector");
duk_push_c_function(ctx, nativeVectorADD, 2);  // TODO: Verify that the number of parameters is correct. This should be 2 objects.
duk_put_prop_string(ctx, -2 /*idx:global*/, "nativeVectorAdd"); //TODO: Is the ID of This string Correct?
duk_pop(ctx);  /* pop global */
```

**Comment by fatcerberus** [comment]
Your use case here is actually kind of odd, I think.  Generally speaking shuffling POJOs between C and JS like this is going to be inefficient and create
confusing code.

In most cases if you need to marshal a complex data structure between JS and C you would construct the object on the native side, attach its pointer to the JS object (as discussed in your other issue) and go from there.

A stack-based API like Duktape's isn't really suited for this kind of heavy-duty marshaling.  I think you'd find the same to be the case with, e.g. Lua.

Nonetheless, your function looks correct.

Two important things to keep in mind with the value stack:
* When a native function is called, the parameters passed from JS are pushed left to right and a new stack frame created, such that arg 1 is at index 0, arg 2 at index 1, etc.
* Negative valstack indices are relative to the top, positive from the bottom.

All that said, I do agree the value stack is one of those things in Duktape that could use better documentation.  For such a core part of the API, it gets surprisingly little attention.

**Comment by kphillisjr** [comment]
I know my use case is best described as odd, but I have found very specific cases where this is useful. A good example where this is most useful is in game engine development. In this case you could see following script register a new type of enemy...

```javascript
var myEnemy = {
	name: 'Red Slime',
	health: 500,
	state = 'alive';
	initialize: function() {
		this.name = 'Red Slime';
		this.health = 500;
		this.state = 'alive';
	}
	takeDamage: function(damage) {
		this.health -= damage;
	},
	updateState: function() {
		if(this.health < 1){
			this.state = 'alive';
		} else {
			this.state = 'dead';
		}
			
	},
	dealDamage: function(){
		if(this.state == 'alive')
			return 50;
		return 0;
	}
	getState: function() {
		return this.state;
	}
};

registerEnemy(myEnemy);
```

**Comment by fatcerberus** [comment]
Interesting you mention game engines.  I'm personally using Duktape myself in my own game engine, minisphere.  It started out as a clone of the old "Sphere" engine, but now has tons of new features.  The key thing about it though, is that all game logic is done purely in JS.  The facilities provided on the native side are all lower-level stuff, e.g. audio mixers, rendering functions, that kind of thing.  This avoids excessive marshaling of high-level game objects between C and JS because all the game programming is JS.

Of course this is out of the scope of this feature request, but you might want to consider looking into implementing a similar system.  It might save you a lot of headaches down the road.

**Comment by kphillisjr** [comment]
I agree, and honestly the main purpose of these various bug reports is to point out areas where example code can greatly reduce the learning curve needed to use Duktape. In most of these cases languages like lua already provide examples.

**Comment by svaarala** [comment]
The value stack concept comes from traditional stack machines: https://en.wikipedia.org/wiki/Stack-oriented_programming_language, so it's not really a Duktape (or Lua) specific concept.

Anyway, I agree there should be more and better examples of various common use cases that user code encounters. The plan is to put stuff like that in a Duktape Wiki and migrate existing examples in the guide over to the wiki to make the guide a smaller "umbrella" document.

**Comment by svaarala** [comment]
There's now a https://github.com/svaarala/duktape-wiki so writing a "how to" there is also an option.

**Comment by svaarala** [comment]
Moved to the wiki repo, because the relevant documentation would go there.
