### ISSUE TITLE
make test fail . make: https://github.com/mishoo/UglifyJS2/archive/v2.4.12.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by yuzhidi** [svaarala/duktape#2194]
macOS Mojave 10.14.5
 /usr/bin/make -f /Users/leocone/Study/duktape/Makefile test
 /# https://github.com/mishoo/UglifyJS2
 /# Use a specific release because UglifyJS2 is used in building Duktape
 /# (This is now a bit futile because UglifyJS2 requires an 'npm install',
 /# the NodeJS dependencies need to be controlled for this to really work.)
 /# Don't use this because it's a moving critical dependency
 /#/usr/bin/git clone --depth 1 https://github.com/mishoo/UglifyJS2.git
 https://github.com/mishoo/UglifyJS2/archive/v2.4.12.tar.gz -O v2.4.12.tar.gz
 make: https://github.com/mishoo/UglifyJS2/archive/v2.4.12.tar.gz: No such file or directory
 make: *** [UglifyJS2] Error 1
$ npm install uglify-js -g
also fail.

**Comment by svaarala** [comment]
First as background, the Makefile is intended for Linux only, and I don't intend for all Makefile targets to work on e.g. iOS. There are now Docker images that you can use for development however. They provide a Linux environment for building and testing, and they might work as is on iOS, e.g.:
```
$ make docker-images
$ make docker-shell-wdmount
```

This gives you a shell, which uses the same working directory, so you should be able to edit on iOS, but run tests etc. in the shell.

But regarding this specific problem, you are probably missing a `wget` command which causes the rather cryptic error.
