### ISSUE TITLE
How to read stack trace from fatal error handler?

### ISSUE THREAD

**Issue by nick-thompson** [svaarala/duktape#2196]
I've added my own fatal error handler following the guide here: https://wiki.duktape.org/howtofatalerrors

So far so good, I'm able to handle the error and the provided message as expected in my application, but how can I print the stack trace from the fatal error handler? Or would it be advised to just do everything inside `duk_pcal`/`duk_peval` and equivalent protected methods? What about for cases that don't have a protected API call?

**Comment by svaarala** [comment]
A fatal error handler only receives an error message string to be stored/printed in whatever way suits the application. You should not call any Duktape API calls from the fatal error handler: the handler may be called when it's unsafe to do so. There is also no access to the stack trace of the fatal error, only the string message.

In production applications where you generally may not want to `abort()` on a fatal error (there are exceptions to this of course), you should always begin an API call sequence with e.g. `duk_safe_call()` or other protected call. Unsafe API calls (calls that may throw) should then happen inside the protected call wrapper.

**Comment by nick-thompson** [comment]
Ok, got it! Thank you

**Comment by svaarala** [comment]
You're welcome!
