### ISSUE TITLE
debugger_attach() implementation

### ISSUE THREAD

**Issue by Freshdouble** [svaarala/duktape#2198]
I can't find the meaning of void* udata of the attach call in the documentation.
Is it ok to set this to NULL?
Also is there an example for the debugger with the tcp transport example? I can only find an example for the dvalue transport layer.

**Comment by svaarala** [comment]
The udata pointer in `duk_debugger_attach()` is passed around to e.g. the transport read/write callbacks. It can be NULL if you don't need it, Duktape doesn't interpret it in any way.

Regarding the debugger example, if you build with `make duk` in the repo, or `make -f Makefile.dukdebug` in the distributable, you get a Duktape command line tool with TCP based debugger transport. The transport implementation is here: https://github.com/svaarala/duktape/tree/master/examples/debug-trans-socket and the debugger initialization is here: https://github.com/svaarala/duktape/blob/master/examples/cmdline/duk_cmdline.c.

**Comment by Freshdouble** [comment]
Thank you very much, i think this answers all my questions.
I will close this issue for now.

Just a short request, if you have time, can you please update the doku for this debugger. In the readme at https://github.com/svaarala/duktape/tree/master/examples/debug-trans-socket there is no example for the usage of this implementation and it would be very helpfull if the readme has a reference to the implementation at https://github.com/svaarala/duktape/blob/master/examples/cmdline/duk_cmdline.c.
Especially because this debugger implementation
https://github.com/harold-b/vscode-duktape-debug
says that one should use the tcp debugger of duktape as a starting point.
