### ISSUE TITLE
Object instance identity

### ISSUE THREAD

**Issue by voinokin** [svaarala/duktape#2201]
Is it currently possible to somehow extract identity information from object instance present on values stack having that object changed over time in JS code ?

For example:
Duktape engine is embedded into application, and some API is provided for JS code. Two specific entry points are provided among others - StartSomething(obj) and EndSomething(obj). The application must have ability to match 'End' operation to 'Start' operation on the same object.

**Comment by svaarala** [comment]
The best first question is: how would you do that matching in pure ECMAScript code? Most likely you would add some sort of identifier / counter property on the object. The same approach can then be used in Duktape/C code.

But going beyond that, objects do have a heap pointer (readable using `duk_get_heapptr()` and its variants) which is stable for the lifetime of the object. However, if the object becomes unreachable, the same pointer may be reused for another object at a later time.

So, if you can guarantee that the object in question is always reachable between StartSomething() and EndSomething(), you could use the heap pointer to match the objects. But if you can't guarantee reachability, such matching would not be reliable.

**Comment by voinokin** [comment]
Did I get it right that duktape GC does not relocate objects during its passes? For compaction or other reasons.

**Comment by svaarala** [comment]
The object header structure is not relocated which is the pointer returned by `duk_get_heapptr()`. Property table is reallocated/relocated on resizes.
