### ISSUE TITLE
duk_push_array

### ISSUE THREAD

**Issue by NullFlex** [svaarala/duktape#2216]
Can someone post an example of returning an array to a js script? i read the docs and didnt understand it

**Comment by svaarala** [comment]
Here's an example returning `[ 'foo', 'bar' ]` (off the top of my head):
```c
duk_ret_t my_func(duk_context *ctx) {
    duk_push_array(ctx);
    duk_push_string(ctx, "foo");
    duk_put_prop_index(ctx, -2, 0);
    duk_push_string(ctx, "bar");
    duk_put_prop_index(ctx, -2, 1);
    return 1;
}
```

**Comment by NullFlex** [comment]
> Here's an example returning `[ 'foo', 'bar' ]` (off the top of my head):
> 
> ```c
> duk_ret_t my_func(duk_context *ctx) {
>     duk_push_array(ctx);
>     duk_push_string(ctx, "foo");
>     duk_put_prop_index(ctx, -2, 0);
>     duk_push_string(ctx, "bar");
>     duk_put_prop_index(ctx, -2, 1);
>     return 1;
> }
> ```

why is obj_idx -2?
shouldn't it be auto obj_idx = duk_push_array(ctx)
duk_put_prop_index(ctx, obj_idx, 0)?

**Comment by svaarala** [comment]
Both methods are correct. At the entry of the function the value stack contains arguments, marked `...` below. Stack contents (growing to the right) is shown between operations:
```c
    // Stack: [ ... ]
    duk_push_array(ctx);
    // Stack: [ ... arr ]
    duk_push_string(ctx, "foo");
    // Stack: [ ... arr "foo" ]
    // At this point 'arr' is at index -2 relative to the top (see https://duktape.org/guide.html#programming.4)
    duk_put_prop_index(ctx, -2, 0);
    // Stack: [ ... arr ]
    duk_push_string(ctx, "bar");
    // Stack: [ ... arr "bar" ]
    duk_put_prop_index(ctx, -2, 1);
    // Stack: [ ... arr ]
    return 1;  // returns 'arr'
```

Instead of relative indices, you can also use the absolute index returned by `duk_push_array()`. It will be >= 0 and relative to the stack bottom (and thus independent of what extra values are pushed on the stack). It's a matter of taste which approach to use, and both have merits in different situations.

**Comment by NullFlex** [comment]
> Both methods are correct. At the entry of the function the value stack contains arguments, marked `...` below. Stack contents (growing to the right) is shown between operations:
> 
> ```c
>     // Stack: [ ... ]
>     duk_push_array(ctx);
>     // Stack: [ ... arr ]
>     duk_push_string(ctx, "foo");
>     // Stack: [ ... arr "foo" ]
>     // At this point 'arr' is at index -2 relative to the top (see https://duktape.org/guide.html#programming.4)
>     duk_put_prop_index(ctx, -2, 0);
>     // Stack: [ ... arr ]
>     duk_push_string(ctx, "bar");
>     // Stack: [ ... arr "bar" ]
>     duk_put_prop_index(ctx, -2, 1);
>     // Stack: [ ... arr ]
>     return 1;  // returns 'arr'
> ```
> 
> Instead of relative indices, you can also use the absolute index returned by `duk_push_array()`. It will be >= 0 and relative to the stack bottom (and thus independent of what extra values are pushed on the stack). It's a matter of taste which approach to use, and both have merits in different situations.

very nice example, but here is the code I do:
```
auto arr_idx = duk_push_array(ctx);
duk_push_int(ctx, 1337);
duk_put_prop_index(ctx, arr_idx, 0);
duk_push_int(ctx, 999);
duk_put_prop_index(ctx, arr_idx, 1);
return 1;
```

and I register the stuff above as a function, then I call the function in my javascript like:
```
var resp = function_called();
//do stuff with resp...
```

but as soon as I try to interact with resp, it seems to be null or something (duktape calls abort()).
how can I debug this? I tried placing breakpoints in my cpp function, but they were never hit.

**Comment by svaarala** [comment]
All practical code should be inside a safe call wrapper to get reasonable error messages, see: https://duktape.org/guide.html#error-handling
