### ISSUE TITLE
why is failing to eval a script a fatal error 

### ISSUE THREAD

**Issue by conradjones** [svaarala/duktape#2217]
why is failing to eval a script a fatal error 
```    duk_push_string(ctx, R"RAW(
(function(block) {
   this_is_nonsense
})
)RAW");
duk_eval(ctx);
```

if this fails it triggers a fatal error using longjmp which means control can't pass back to program, I find it very strange decision that you feel the need make the decision to abort the consumers program for them .

**Comment by conradjones** [comment]
okay so duk_peval can be used. fair enough I don't understand why you have the other versions though,

**Comment by svaarala** [comment]
Protected calls involving a setjmp/longjmp are heavier than unprotected ones. The typical pattern is to have a wrapping protected call, and unprotected calls inside it. This is the same model as in Lua.

**Comment by svaarala** [comment]
The guide covers the issue in some more detail: https://duktape.org/guide.html#error-handling.
