### ISSUE TITLE
Is It Possible to Add Functions for Calling External Programs?

### ISSUE THREAD

**Issue by spaceman5** [svaarala/duktape#2221]
Hi

I am using Duktape on Linux (Command Line, not Browser),
and would like my code to execute an external program in Linux, for example "ls".

If I understand correctly, Duktape does not have such functionality right now.
My suggestion, is to consider adding such, so when using Duktape in a Local environment (not a Browser), then this functionality will be available..

What do you think?

**Comment by svaarala** [comment]
You can easily add a binding for `system()` if you wish, example:
```
static duk_ret_t sys_execute(duk_context *ctx) {
        const char *command = duk_require_string(ctx, 0);
        int rc;

        rc = system(command);
        if (rc != 0) {
                duk_push_error_object(ctx, DUK_ERR_TYPE_ERROR, "system() failed with code %d", rc);
                duk_push_int(ctx, rc);
                duk_put_prop_string(ctx, -2, "exitCode");
                return duk_throw(ctx);
        }

        return 0;
}
```

Then register it to the global object.

I'm probably adding something like this to master as part of rewriting the Py2 tooling to be JS-based and self-hosting.

**Comment by spaceman5** [comment]
Nice, thank you very much.
It will also be useful for other people.
Thank you for creating Duktape.
