### ISSUE TITLE
Unable to Create an Issue in Repository "embedded-scripting-languages"

### ISSUE THREAD

**Issue by spaceman5** [svaarala/duktape#2222]
Hi

In the embedded-scripting-languages repository you wrote 
"Please submit a pull request or create an issue to add a new language to the list"
yet for some reason the "Issues" tab does not exist there.

In any case, I wanted to offer to suggest adding QuickJS.
https://bellard.org/quickjs/

**Comment by svaarala** [comment]
I'm not the owner of that repo.

**Comment by spaceman5** [comment]
Oh right..
It's Forked from another one..
My apology..
That also explains why I can't open an issue
Sorry
