### ISSUE TITLE
debugger.rst documentation for GetLocals

### ISSUE THREAD

**Issue by dzzie** [svaarala/duktape#223]
https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#getlocals-request-0x1d

return type is specified as 
REP [ &lt;str: varName&gt; &lt;str: varValue&gt; ]* EOM

second argument is however a tval

https://github.com/svaarala/duktape/blob/master/src/duk_debugger.c#L1194

might also be worth a comment inclusion that _varmap only includes variables explicitly prefixed with var. After playing with this command, I probably wont be making use of it in my debugger UI and just letting users use the mouseover variable value lookup which works in all cases (including global vars)

**Comment by svaarala** [comment]
Fixed in master now.

The command intentionally only includes bindings in the current scope. The intent is to extend this command as future work so that you can enumerate through the outer scopes one by one (sometimes it's useful to know *where* variables come from).

Adding a command to list all reachable bindings (including global variables) might be useful separately.

**Comment by svaarala** [comment]
Oh, and thanks for reporting :)

**Comment by dzzie** [comment]
oops I didnt think about it, but the example also shows the old string return as well. Being able to walk scopes and figure out where variables reside sounds interesting. a global variable enum would be very nice.

**Comment by svaarala** [comment]
A string "tval" is actually represented as a plain string so the example should be correct.

The debugger command set is a bit limited now: it's a result of a first implementation pass which needed a command set that exercised relevant functionality but didn't go too far design-wise so that there'd be some time to gather feedback before adding/modifying commands.

**Comment by dzzie** [comment]
gotcha thanks. Only two things I had to implement outside of the protocol were 2 manual function calls

```C
case opd_dbgCurLine: return duk_debug_curr_line(ctx); 
case opd_dbgTriggerRead: duk__debug_process_message(ctx); return 0;
```
opd_dbgCurLine was for initial startup to highlight the first line of execution (couldnt seem to find that anywhere)

and as mentioned in irc the opd_dbgTriggerRead was to manually trigger a fresh read/write sequence from the current point in the call stack.

**Comment by dzzie** [comment]
I think this comment from the other thread was in reference to this

>I don't see how or why there should be any difference in line
>highlighting etc solely based on whether one uses, say, debug API 
>calls as opposed to a debug protocol. 

the case opd_dbgCurLine was for debugger startup. I did not see a current line included in the BasicInfo or a notification message sent before a single step was issued. trigger_status also did not include a line number so just went with direct api access to get the very initial line number for debugger events took place.

**Comment by svaarala** [comment]
@dzzie Btw, `duk_debug_curr_line()` and `duk__debug_process_message()` are not part of the Duktape public API, so there are no guarantees that they'll be available in newer versions. There's actually no relevant line number before any steps have been executed (as no code is running); `duk_debug_curr_line()` will return 0 when the callstack is empty.

Could you describe why you need to trigger a debugger read explicitly?

- When Duktape is running, it'll periodically poll for incoming messages (a few times per second usually). And when execution is paused, i.e. you're stepping, Duktape will be blocked in processing debug messages until the debug client steps (after which the message loop is resumed immediately) or execution is resumed.

- When no call is active, you can use http://duktape.org/api.html#duk_debugger_cooperate to get Duktape to respond to debugger commands. It's basically intended for your "idle loop" and will just peek (not block) for incoming messages.

There are probably use cases not covered by these two though :)

**Comment by dzzie** [comment]
I know I am out of spec I accept the burden/risk if the trick is unsupported latter lol. The line number is showing the correct line before I step actually. I added a blank lines to start of document and it still highlighted the first source line. 

I was using it in my event loop, but had not looked into the guts of duk_debugger_cooperate yet. Below is an example of how I am using my opd_dbgTriggerRead which basically the same intent but without checks for already processing and is blocking

```vb
Function SyncGetCallStack() As Collection 'of cCallStack
    Set tmpCol = New Collection 'module level var to work across call backs
    LastCommand = dc_GetCallStack
    replyReceived = False
    RespBuffer.ConstructMessage dc_GetCallStack
    DukOp opd_dbgTriggerRead, ActiveDebuggerClass.Context 'triggers full synchronous read/write cycle
    Set SyncGetCallStack = tmpCol 'this data is immediately available when DukOp returns
End Function
```
Since I am working in process, it is extremely convenient to be able to make a data request and receive the data immediately when my function call returns. The ones where this is really handy is when running eval, and Get_Var requests. 

Below is a call stack for my mouse dwell event. 

![call_stack](https://cloud.githubusercontent.com/assets/576721/8823823/0ac6e940-303e-11e5-97aa-c243c0af9274.png)

the cb_GetDbgCmd is the read callback that is blocking (single thread UI) I tested out switching over to  duk_debugger_cooperate but it is not guaranteed to work and returns no value so I can not wrap it in a while(!) loop. 

Based on the call stack above, without a synchronous read/write mechanism, in my mouse dwell event, I would have to do something like build my request packet,  let my mouse dwell event exit and the whole call stack return until cb_GetDbgCmd returns my request, then on the data data receive I would have to have a special flag or a timer polling "did new data receive" to handle the data specially and then at that point respond to the user and display the value in a tool tip. 

This fragments the code to much so I looked for a way to user initiate a synchronous data retrieval similar to what  a traditional api call would do. Since my UI thread is single threaded, and duk engine is already frozen further down teh call stack, it seemed like it should be safe to re trigger the read/write routines. I have not had any crashs and it is working. Time will tell if there are any corner cases where it leads to unstability. For now I accept the risk. ( I do not make commercial software, just research tools so I do funny things all the time :)

**Comment by dzzie** [comment]
this really does seem like it should be quite safe though. Duk is already in a known state of expecting to read data and frozen. I am just re-triggering it from a different point in the call stack of the same thread.

**Comment by svaarala** [comment]
@dzzie You're welcome to hack with the internals of course - just wanted to make sure it wouldn't be a surprise if things changed unexpectedly. It's probably safe what you're doing. One downside of a debug protocol is that it is to some extent necessarily asynchronous so that an ideal debug client also deals with asynchronous calls etc, which is not always convenient.

**Comment by fatcerberus** [comment]
I see what he's getting at about highlighting the first line.  It's like starting MSVC in single-step mode, it highlights the first line of main() without executing any code.  Maybe it would be worth having Duktape send out a notification for the first line of code whenever a debugger is attached?  Then the client could respond to this notification by sending a request to either step or begin execution normally.

**Comment by svaarala** [comment]
We're probably talking about different things: I'm talking about the situation where a debugger has attached but nothing is yet executing. Duktape cannot know *what* you will be executing, so it cannot know what file or fileName will run (it may not have even been compiled).

But once you start executing code, Duktape should pause immediately (before executing any bytecode instructions) and send a Status with the current file and line.

**Comment by fatcerberus** [comment]
If that's the case, then surely the `duk_debug_curr_line()` call mentioned above is not needed?

**Comment by svaarala** [comment]
I think @dzzie has a different issue and I'm not sure I understood his use case.

**Comment by dzzie** [comment]
To execute script I am calling
```C
duk.DebugAttach
duk.AddFile(curFile)
```
I receive the BasicInfo as the first message, and then a read request where i start blocking. At this point I do not know the first line of code so had to implement the work around.

**Comment by svaarala** [comment]
@dzzie Been there, done that :)

**Comment by fatcerberus** [comment]
No EOM on the attachment response... is that a bug?

**Comment by svaarala** [comment]
@fatcerberus If you mean the version line, that doesn't yet follow the binary protocol: it's just a line of text followed by a newline.

The intent of this is to make it easy to detect a debug port using e.g. telnet, and also to allow the binary protocol to be versioned. The initial line can provide the necessary information to continue parsing.

**Comment by fatcerberus** [comment]
Okay, that makes sense.  Just wanted to be sure it wasn't an undiscovered bug.

**Comment by svaarala** [comment]
This issue has strayed way off topic and the original issue is resolved, so closing.
