### ISSUE TITLE
new Error().stack doesn't contain JS'callstack in Android

### ISSUE THREAD

**Issue by Shuijwan** [svaarala/duktape#2234]
I use duktape as JS environment in Android. and I want to capture current call stack.
below is my test code, it is executed dynamic.

`   duktape.evaluate("var testcode = new Function('module','return module.exports={onclick:function(){console.error(new Error().stack);}};');\n" +
                            "var module = {};\n" +
                            "var fun = testcode.call(this, module);\n" +
                            "fun['onclick'].call();\n");`

however it only prints

"Error
at [anon] (compile:1)
at eval (?:4) preventsyield"

the function "onclick" is missing.  It seems "onclick" is treated as anonymous function?

In browser it can print correct call stack. I run the same code in https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function

![image](https://user-images.githubusercontent.com/7829310/75517499-cef4b200-5a39-11ea-862c-a6d6b097ee1b.png)

**Comment by hifoxwei** [comment]
+1, I have the same problem

**Comment by Shuijwan** [comment]
please ignore this issue. I am using square's duktape-android  project, It prints correct stack when executed by raw duktape.  I think the reason is this test code is wrapped by a global JS object. 

the true code executed is : String.format("ac.dispatch('%s');", testcode)

I will dig deep  to find the root cause.

**Comment by svaarala** [comment]
The onclick function is an anonymous function expression in your example:
```js
onclick:function(){ /*...*/ }
```

You can give it a name explicitly:
```js
onclick:function onclick(){ /* ... */ }
```

In ES2015+ the former would also get an automatic `.name` based on the literal key (`"onclick"`), but Duktape doesn't implement that ES2015+ behavior yet.

**Comment by Shuijwan** [comment]
Thanks for clarify.  I use Object.defineProperty(func, "name", { value: name });  to assign a name  to function temporarily since the source code is generated by others.
