### ISSUE TITLE
What is duktape's policy when receiving signals?

### ISSUE THREAD

**Issue by chrisdone** [svaarala/duktape#2241]
I'm curious about correctly writing an FFI to duktape from GHC Haskell. There are other Haskell bindings, but I'm not sure whether they're correct or just coincidentally working OK. I don't have much experience with signal handling in C, so I'm going off what I've read.

The RTS [uses signals](https://gitlab.haskell.org/ghc/ghc/wikis/commentary/rts/signals) to trigger context switches and other threading features. In particular, using the system timers API, `SIGVTALRM` will be triggered on a regular basis. The C code being called [apparently needs to be aware of this](https://gitlab.haskell.org/ghc/ghc/wikis/commentary/rts/signals#rts-alarm-signals-and-foreign-libraries). 

I believe it's possible for me to write some small wrapper C code to register a signal mask to prevent these signals from bothering the duktape functions.

---

Secondly, when declaring a foreign function, I can choose whether it is interruptible or not. If I mark it interruptible, that means that if I terminate the Haskell (green) thread using regular Haskell code, [SIGPIPE will be signalled to the OS thread](https://stackoverflow.com/a/52194650/89574) ([see also](https://ghc.readthedocs.io/en/8.0.1/ffi-chap.html#interruptible-foreign-calls)). What does duktape do when it receives SIGPIPE, and SIGINT for that matter? Is it manifested as a JS exception? What's the relationship between "protected" functions and non-protected ones in this setting? I've read through the user guide a few times, but wasn't able to find clarity on this.

---

**Use-case**: I'd like to be able to execute PureScript from my Haskell code to have server-side rendering and validation as well as front-end. I want to do one-shot runs of code. Ideally I could execute the JS via duktape, which has fine-grained control over what functionality is available (e.g. I need timers API (`setTimeout`, used for asynchronous runs by a library I'm using, but not actual waiting), but not I/O). 

However, due to the messiness in dealing with GHC's RTS, I'm wondering whether correctness-wise it may be easier to launch a nodejs program as a pipe and parse JSON output? :thinking: But then you have a much heavier dependency that needs to be kept around somewhere to be launched, etc. Trade-offs.

**Comment by svaarala** [comment]
It's up to each Duktape/C native binding to handle signals internally as they see fit. Duktape itself doesn't care about signals, it doesn't register any signal handlers for example.

**Comment by chrisdone** [comment]
OK, that simplifies things a lot. Thank you!

**Comment by svaarala** [comment]
Forgot to mention one place where Duktape does interact with signal handling: setjmp/longjmp. Current defaults are:
- `_setjmp()`: macOs, iOS, cygwin
- `setjmp()`: other platforms

You can also select the provider by overriding `DUK_SETJMP()` and `DUK_LONGJMP()` in duk_config.h, e.g. sigsetjmp() may be useful if you want to explicitly control signal mask handling.

**Comment by chrisdone** [comment]
OK, so I could:

1. Set a mask on `SIGVTALARM` before calling any Duktape function (particularly the `eval`).
2. I make sure to override the setjmp/longjmp macros with `sigsetjmp`/`siglongjmp`.
2. I can use `DUK_USE_EXEC_TIMEOUT_CHECK` to implement "cancel"/interrupting an `eval` call. 

Instead of running Duktape on a thread that may be killed (which triggers `SIGPIPE`), I would instead run it in a "background" thread that's paying attention to a "timeout :: Bool" value. A strawman thread that serves as a stand-in for Duktape would receive the Haskell kill exception and set the "timeout=True" and wait for the background thread to terminate in due course.

After the timeout occurs and the RangeError exception has propagated back up to a `duk_peval`-or-equivalent call, I presume the heap can be used again? Or should I destroy the heap and start with a fresh one next time I want to evaluate something?

**Comment by svaarala** [comment]
Sounds good to me, once the RangeError propagates out to a protected call, you can keep on using the heap normally as long as you ensure the DUK_USE_EXEC_TIMEOUT_CHECK() behavior is reset for the next call (i.e. it won't timeout right away).

**Comment by chrisdone** [comment]
Thanks, that's very helpful. :+1:

**Comment by aksyom** [comment]
When the DUK_USE_EXEC_TIMEOUT_CHECK -macro is executed by the bytecode executor, is it safe to call a global function object within the duk_context being interrupted?

**Comment by svaarala** [comment]
The interrupt check is really quite simple at present and there has been no thought about executing Duktape calls within the interrupt check.

But, I think calling a function from the interrupt check should work fine because a function may be get called for various other reasons within the bytecode executor - e.g. a property read may invoke a Proxy trap, and the bytecode executor is generally unaware of the situation.

If this doesn't work, it should be relatively easy to fix because the executor must tolerate recursive calls elsewhere.
