### ISSUE TITLE
Question about the Debug API

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#225]
All the documentation for Duktape's debug API puts heavy, heavy emphasis on protocols and transports as part of a debugger implementation.  So I'm confused, is it even possible to write a true local debugger with this, or does it have to be implemented as a remote debugger, like how the MSVC 64-bit debugger works?

**Comment by svaarala** [comment]
You can only access the debugger functionality (breakpoints, stepping, etc) through the protocol. You can of course implement a debug client on the same target (even the same process) as where Duktape is running so it doesn't need to be physically remote (but it is conceptually a "remote peer").

What do you mean by a "true" local debugger?

**Comment by dzzie** [comment]
I am just finishing up a local same process debugger. The read/write routines are just callbacks into the UI portion. 

https://github.com/dzzie/duk4vb
https://www.youtube.com/watch?v=nSr1-OugQ1M

**Comment by fatcerberus** [comment]
Yeah, that's what I meant by truly local: in contrast to a remote model.  Basically the difference between 32- and 64-bit debugging in MSVC: the 32-bit one attaches to the process directly and controls its execution, whereas my understanding of how the 64-bit one works is that it opens a TCP connection connected to loopback to debug--because for some reason that's the only way the OS will allow to debug an x64 app.  This tends to cause oddities like highlighting the next line instead of the one causing a crash, etc.

Duktape appears to use the latter model.  Thanks, that clears things up a lot. :smile:

**Comment by svaarala** [comment]
I don't see how or why there should be any difference in line highlighting etc solely based on whether one uses, say, debug API calls as opposed to a debug protocol. At least for Duktape there wouldn't be: if there was a debug API to do all the things that debug protocol does, line number handling would still be identical.

Also note that you don't need to use TCP or anything network related so it's not remote in that sense.

**Comment by fatcerberus** [comment]
Yeah, I didn't mean to imply that Duktape would suffer from the line number issue, just pointing out the difference in the case of MSVC.  I don't know _why_ it's that way but for some reason MSVC likes to highlight one line ahead when stopping at an exception or viewing stack frames in an x64 process (breakpoints are handled correctly however... weird).  But yeah, that's basically what I meant: A direct debug API ("attaching" directly to the running code) vs. having a middleman (the protocol).

Honestly the protocol approach is superior, so I applaud you for that. :)  With just an API I'd be forced to write my own communication layer anyway to be able to write an out-of-process debugger, so this is a nice convenience.

**Comment by fatcerberus** [comment]
Another question: `debugger.rst` mentions forwarding print() and alert() to the debug client.  For an in-process debugger this is trivial, just assign a new C function to them.  But if the client is separate, how would this be done, since everything has to go through the protocol?

**Comment by svaarala** [comment]
The documentation actually refers to the default print() and alert() calls which integrate with the debug protocol if you enable that option. There's currently no way for user code to interact with the debug protocol - this is definite future work, e.g. to relay notifications related to user code to the debugger (statistics, debug messages, etc).

**Comment by fatcerberus** [comment]
Ah, I see, that's good then.  This is the passage which confused me:

"Also consider other debugging related feature options, like forwarding print()/alert() to the debug client."

"Consider other options" made me think it was something I had to implement myself.

**Comment by svaarala** [comment]
I can see why, I'll try to reword that a little bit.

**Comment by svaarala** [comment]
Ok, reworded a little bit: https://github.com/svaarala/duktape/commit/b3341cf970d563a8ff9721a54f61162f40da331f

**Comment by fatcerberus** [comment]
Ah, that's much clearer.  It shows the actual option defines now, so no room for ambiguity.  Without those in there it read like it was recommending you to implement such features yourself.

**Comment by fatcerberus** [comment]
So, I'm unclear on the proper usage of `duk_debugger_cooperate()`?  The documentation stresses only to call it when "no call into Duktape is active".  But this doesn't make sense to me--if you're in the midst of debugging, then by definition there's an active call, usually `duk_eval()` or `duk_call()`.  So it seems like it would actually never be safe to call the function, but that wouldn't make any sense. :)

With this in mind, I'm going to assume that it's perfectly safe to call `duk_debugger_cooperate()` while execution is paused.  Would that be an accurate assumption?

**Comment by svaarala** [comment]
It's perfectly normal to have a debugger attached and the call stack to be empty. For example, your program may be an event loop that calls into Duktape occasionally and you may do that with debugger constantly attached. When nothing is running, you're still debugging but no code is running.

`duk_debugger_cooperate()` exists so that you can call it from your eventloop. It allows your debug client to perform some operations like changing breakpoints, evaluating expressions etc, even when nothing runs and the debugger is not caught in a breakpoint or otherwise paused.

**Comment by svaarala** [comment]
It's perfectly normal to have a debugger attached and the call stack to be empty. For example, your program may be an event loop that calls into Duktape occasionally and you may do that with debugger constantly attached. When nothing is running, you're still debugging but no code is running.

`duk_debugger_cooperate()` exists so that you can call it from your eventloop. It allows your debug client to perform some operations like changing breakpoints, evaluating expressions etc, even when nothing runs and the debugger is not caught in a breakpoint or otherwise paused.

**Comment by fatcerberus** [comment]
So what do I do in the opposite scenario--when execution _is_ paused but I want to still run my event loop (so the OS doesn't think the target has stopped responding)?  Would I run the event pump in the peek callback, or...?  Because I assume Duktape itself enters a busy wait when execution is paused.  There doesn't appear to be a dedicated "tick" callback for this purpose.

**Comment by svaarala** [comment]
Execution will be paused in the debugger message loop which will call into the read() callback you provide. That callback is required to block when no data is available, so you'll have the control flow until there's data to be processed.

**Comment by fatcerberus** [comment]
Ah, the requirement that the read callback not return 0 makes a lot more sense now.  I suddenly understand jack everything. :)
