### ISSUE TITLE
Compiler recursion limit under OS X compiling CoffeeScript

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#226]
I recently found out from a tester that Duktape fails to evaluate `coffee-script.js` with the following error when my engine is run under OS X (Mavericks I believe):

```
RangeError: compiler recursion limit (line 8)
```

This is with version 1.9.3 of the CoffeeScript compiler, available here:
http://coffeescript.org/extras/coffee-script.js

I don't have access to a Mac to test this myself.  The same script compiles and runs fine on every Windows build I've done.

**Comment by svaarala** [comment]
Deep C stack seems not to be enabled for OSX; could you try with `-DDUK_OPT_DEEP_C_STACK`?

If that fixes it, I'll change the default behavior for OSX to use a deep stack.

**Comment by fatcerberus** [comment]
Still waiting on a response from my OS X tester, hang tight. :-)

**Comment by fatcerberus** [comment]
`DUK_OPT_DEEP_C_STACK` indeed fixed the error.

**Comment by svaarala** [comment]
Alright, I'll change OSX default to use deep stacks (like Windows and Linux). For now you can just keep that feature option in your build.

**Comment by fatcerberus** [comment]
Out of curiosity, how much difference between the limits is there?  Are we talking an order of magnitude, or...?

**Comment by svaarala** [comment]
More than an order of magnitude - the "shallow stack" mode is intended for targets which have really limited stacks (around 32-64kB). With #64 the default will be "deep stack" and you'll have to explicitly request a shallow stack because that's probably the better default.

I'm planning to remove the current C stack limits altogether (which are applied separately for compilation, regexps, etc), and instead allow the user to provide a stack check macro which can check for available stack space in a target specific manner. This check can then be added to a few critical places inside Duktape, so that the out-of-stack error happens only when needed and there'd be no need for guesstimating reasonable stack limits which is difficult to get right.

**Comment by fatcerberus** [comment]
How would the user know how much stack space is left though?  Duktape itself is in a better position to make that determination, I would think, as it can count activations and you'd know best how many bytes are needed for each call, etc.

I'm assuming this stack-check macro, if it's implemented, will be part of the new duk_config system, yes?

**Comment by svaarala** [comment]
The user would be able to write a function that could inspect a stack pointer and have the target specific information needed to figure out how much safe stack space still exists.

I don't see how Duktape could do that, considering that stack handling is entirely target specific.

Duktape currently tries to count recursion depth for the important places where arbitrary recusion may occur.  But trying to estimate the safe counts (which amounts to estimating stack frame sizes in these recursion paths) is really a crap shoot and very difficult to get even closely right.

Yeah, this stack check macro would be part of `duk_config.h` with a no-op default.

**Comment by svaarala** [comment]
Btw, note that even if stack frame size estimates in the recursion paths were close to correct, Duktape would have no idea what the safe stack size on a certain platform is. The current shallow/deep distinction is now roughly tuned for "unix-like" (deep) or ~64kB (shallow), but this is pretty coarse and perhaps even counterproductive.

**Comment by fatcerberus** [comment]
That makes sense.  Keep in mind though that, as far as I am aware, many platforms may dynamically grow the stack.  So what is the ceiling one time may in fact be higher next time.

I guess it's not ever an exact science.  Even so, more granularity is always good thing.

**Comment by svaarala** [comment]
Sure, if the stack is essentially "infinite", it would then be up to the user to decide what's the appropriate stack check limit (if any). Even if the platform grew the stack indefinitely, it may still be desirable to artificially limit stack to, say, 1 megabyte for containment reasons.

**Comment by svaarala** [comment]
The OSX related change is now merged to master - reopen if it doesn't work for some reason (it was merged after #64 so there's a lot of trivia that may be broken).
