### ISSUE TITLE
Feature request for ES6's Set and Map

### ISSUE THREAD

**Issue by littlesome** [svaarala/duktape#2261]
Is it possiable to have a builtin Set and Map implementation ? 
The transpiler way may be slow, because it uses `Array` as backend. 

I think the implementation may be something like the builtin `object`, and do not need any changes to the compiler or parser,  am I right or I just missed something ?

**Comment by svaarala** [comment]
ES2015+ will be eventually supported. Map and Set are not difficult as such, but one must also support WeakMap and WeakSet which have more interactions with internals.

**Comment by littlesome** [comment]
Any ETA on this? will strong version Set and Map comes before weak ones?

**Comment by svaarala** [comment]
This is an off-hours project so I cannot give firm time estimates. Right now I'm working on rewriting the build tooling to JS and also cleaning it up a bit in the process. Next up is rewriting property access code and some internal structure rewrites which will then enable adding Map, Set, and their weak variants.

**Comment by littlesome** [comment]
Cool! Thanks for sharing and your great job.
