### ISSUE TITLE
Ducktape loading modules - cannot make it work

### ISSUE THREAD

**Issue by mihaioltean** [svaarala/duktape#2264]
I have tried to use _require_ with _duktape_ 2.5.0, but I cannot make it work. I have implemented a _modSearch_ function as I found in the documentation.

My C++ program compiles fine (in VS2019 on Windows 10), but when I run it I get this error (from duktape):

**ReferenceError: identifier 'suma' undefined**

I debugged the program and the mod_search function is called and the file is loaded from disk.

Below are my program and the _modul.js_ file.

Please suggest what I did wrong. Thank you!

	#include <iostream>
	#include "duktape.h"
	#include "duk_module_duktape.h"
	//---------------------------------------------------
	duk_ret_t mod_search(duk_context* ctx)
	{
		 int  len;

		const char *filename = duk_require_string(ctx, 0);

		FILE* f = fopen(filename, "rb");
		if (!f)
			return -1;
		fseek(f, 0, SEEK_END);
		len = (int) ftell(f);

		// Rewind
		fseek(f, 0, SEEK_SET);

		char* src = (char*)malloc(len);
		fread(src, 1, len,f);
		fclose(f);
		duk_push_lstring(ctx, src, len);
		free(src);
		return 1;
	}
	//---------------------------------------------------
	static duk_ret_t console_log(duk_context* ctx)
	{
		duk_push_string(ctx, " ");
		duk_insert(ctx, 0);
		duk_join(ctx, duk_get_top(ctx) - 1);
		std::cout << duk_safe_to_string(ctx, -1);
		return 0;
	}
	//---------------------------------------------------
	int main()
	{
		duk_context* ctx = duk_create_heap_default();

		duk_idx_t console_obj_idx = duk_push_bare_object(ctx);
		duk_push_c_function(ctx, console_log, DUK_VARARGS);
		duk_put_prop_string(ctx, console_obj_idx, "log");

		duk_put_global_string(ctx, "console");

		duk_module_duktape_init(ctx);

		duk_get_global_string(ctx, "Duktape");
		duk_push_c_function(ctx, mod_search, 4 /*num_args*/);
		duk_put_prop_string(ctx, -2, "modSearch");
		duk_pop(ctx);

                // a test program which uses a module
		duk_push_string(ctx, "\n");
		duk_push_string(ctx, "require('modul.js');");
		duk_push_string(ctx, "var a = 3;");
		duk_push_string(ctx, "var b = 5;");
		duk_push_string(ctx, "var s = suma(a, b);");
		duk_push_string(ctx, "console.log(s);");
                // concat all strings
		duk_join(ctx, 5);

		if (duk_peval(ctx) != 0) {
			std::cout << duk_safe_to_string(ctx, -1);
		}

		duk_pop(ctx); /* pop eval result */

		duk_destroy_heap(ctx);

		getchar();
	}
	//---------------------------------------------------

The modul.js is:

	//Your code here...
	function suma(a, b)
	{
	return a + b;
	}

Thank you,
mihai

**Comment by svaarala** [comment]
The likely issue is that your module doesn't export any symbols. The function declaration (suma) in the module does *not* go into the global object, but is local to the module. You can export it like this:
```js
//Your code here...
function suma(a, b)
{
return a + b;
}
exports.suma = suma;
```

Then, in the calling code, you need to take that export into use:
```
[...]
duk_push_string(ctx, "var suma = require('modul.js').suma;");
duk_push_string(ctx, "var a = 3;");
duk_push_string(ctx, "var b = 5;");
duk_push_string(ctx, "var s = suma(a, b);");
duk_push_string(ctx, "console.log(s);");
[...]
```

**Comment by mihaioltean** [comment]
Problem solved. Thank you very much!
