### ISSUE TITLE
PowerPC architecture and byte order

### ISSUE THREAD

**Issue by andrisz** [svaarala/duktape#2265]
PowerPC appears to automatically use big endian byte order while POWER8 introduces ppc64le mode. Maybe it should use autodetect like it's done for arm?

**Comment by svaarala** [comment]
Thanks! Do you have hardware to test on if I make the changes?

**Comment by andrisz** [comment]
Not quite, I was using qemu to emulate ppc64le (investigating a crash reported by user).  I could reproduce the crash and could fix it by forcing CFLAGS=-DDUK_USE_BYTEORDER=1
However it seemed preferable to patch duk_config.h (removed the DUK_USE_BYTEORDER defines for ppc64, leaving it for autodetect like it's done for arm). This also worked nicely.

So yes, I kinda can test, but that will not be on native hardware. I'm using ppc64le Debian 10 image, original report was about Centos 7 on Power 9 (ppc64le).

**Comment by svaarala** [comment]
Hmm - could you link to where the hardcoded assumption is?

For PowerPC we just use https://github.com/svaarala/duktape/blob/master/config/helper-snippets/DUK_F_PPC.h.in and then rely on automatic byte order detection. For PPC Amigas there is a hardcoded big endian assumption.

I tried to verify this with https://hub.docker.com/r/ppc64le/ubuntu but the emulation segfaults before a build is completed.

**Comment by svaarala** [comment]
Just to be sure, what happens if you take a fresh clone and run `make duk` from master, and then try to run `./duk`?

**Comment by andrisz** [comment]
https://github.com/svaarala/duktape/blob/master/config/architectures/architecture_powerpc64.h.in
if I correctly understand the duk_config.h generation.

**Comment by svaarala** [comment]
Ah, I see. My bad! I'll open a fix pull, it should be trivial.

**Comment by svaarala** [comment]
Can you verify that #2267 works correctly?

**Comment by andrisz** [comment]
Thanks! Will do tomorrow, emulation is sloooow.

**Comment by svaarala** [comment]
Ok, sounds good :+1: Once the fix is in master, I'll push it to v2-maintenance too so it gets included in 2.6.0.

**Comment by andrisz** [comment]
Thanks, works. Only question - wouldn't be better to remove also ifdef, so it's consistent with other places (arm) ?

**Comment by svaarala** [comment]
I agree, I'll make that change.

**Comment by svaarala** [comment]
Thanks @andrisz !
