### ISSUE TITLE
Add new ES6 Math built-ins (like Math.log10)

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#227]
See:
- https://stackoverflow.com/questions/30561800/duktape-typeerror-not-callable
- http://www.ecma-international.org/ecma-262/6.0/#sec-math.log10

Duktape seems to be missing:
- [ ] acosh
- [ ] asinh
- [ ] atanh
- [x] cbrt
- [ ] clz32
- [ ] cosh
- [ ] expm1
- [ ] fround
- [x] hypot
- [ ] imul
- [ ] log1p
- [x] log10
- [x] log2
- [ ] sign
- [ ] sinh
- [ ] tanh
- [x] trunc

**Comment by svaarala** [comment]
This is a duplicate (though older) to #1070, so closing this one.

**Comment by fatcerberus** [comment]
Oops, I didn't realize this issue existed before I opened #1070...

**Comment by svaarala** [comment]
It would be awesome if Github could do some similarity analysis (based on finding enough similar words or few common rare words) and suggest "Hey you may be opening a duplicate to X, Y, or Z?" :-)
