### ISSUE TITLE
Object.values undefined

### ISSUE THREAD

**Issue by jkeller51** [svaarala/duktape#2272]
Duktape 2.5.0 

```javascript
var object1 = {
  a: 'somestring',
  b: 42,
  c: false
};

print(Object.values(object1));
```

This code produces the following error:
`TypeError: undefined not callable (property 'values' of [object Function])`

If we run the exact same code except replace "values" with "keys", so the line is:
`print(Object.keys(object1));`
It works perfectly well. Keys but no values? Am I doing something wrong?

**Comment by svaarala** [comment]
Object.values() is not implemented yet.
