### ISSUE TITLE
Heap pointer compression (DUK_USE_HEAPPTR16) compile errors on x64

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#228]
Compilation fails due to bugs in explicit NULL init code (which is conditional).

**Comment by svaarala** [comment]
Fixed in master.

**Comment by fatcerberus** [comment]
I'm a little confused--what was the issue exactly?  I've been compiling for x64 forever and never had Duktape fail to compile.

Unless you meant JS compilation?

**Comment by svaarala** [comment]
It was only triggered when heap pointer compression was enabled, i.e. low memory specific options.
