### ISSUE TITLE
Build Debug mode

### ISSUE THREAD

**Issue by nick-thompson** [svaarala/duktape#2283]
Hey @svaarala,

I'm trying to compile the command line debugging utility as documented here: https://github.com/svaarala/duktape/tree/master/debugger#using-the-debugger-web-ui

As soon as I run `make -f Makefile.dukdebug` I get this:

```
make: *** No rule to make target `examples/cmdline/duk_cmdline.c', needed by `duk'.  Stop.
```

This is both on the current `master` branch and on `v2.2-maintenance`. Is there some prerequisite step that I'm missing? Perhaps I don't understand from the docs how to execute the "compile Duktape command line tool with debugger support" step?

**Comment by svaarala** [comment]
Makefile.dukdebug is intended to be used in the end user distributable. You could start from a distributable (duktape.org/download.html) or create a dist directory yourself in the repo:
```
$ git clone https://github.com/svaarala/duktape && cd duktape
$ make dist
[...]
$ cd dist/
$ make -f Makefile.dukdebug
```

But if you're working from a repo checkout, you can just say `make duk`. The compiled `duk` command has debugger support enabled (i.e. it supports `--debugger` option).

**Comment by nick-thompson** [comment]
Ah, great! Thanks
