### ISSUE TITLE
New project using duktape: OpenRCT2

### ISSUE THREAD

**Issue by IntelOrca** [svaarala/duktape#2289]
![image](https://user-images.githubusercontent.com/1482259/80382660-6fc8e780-889a-11ea-99e3-22264b4ba757.png)

### OpenRCT2 joins the club!

**Pull request:** https://github.com/OpenRCT2/OpenRCT2/pull/11320
**Announcement:** https://www.reddit.com/r/rct/comments/g8nq60/openrct2_plugin_support_now_available/
**API:** https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/openrct2.d.ts
**Readme:** https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/scripting.md
**Samples:** https://github.com/OpenRCT2/plugin-samples

Thanks!

**Comment by svaarala** [comment]
Awesome project! I'll add it to the list :+1:

**Comment by svaarala** [comment]
https://github.com/svaarala/duktape-wiki/pull/230
