### ISSUE TITLE
Regarding promise impl 

### ISSUE THREAD

**Issue by wenq1** [svaarala/duktape#2292]
regarding #1833 can we resume the talk assuming it has not yet been aborted? Can we discuss how we could go forward with it?

**Comment by devsnek** [comment]
I really like how V8 does microtasks. It has an internal queue, which can hold promise jobs, native (c++) callbacks, or js functions. After a script runs, if the stack is empty, it will automatically run through the microtask queue. If the embedder wants more control, they can switch to "explicit" mode, where they must manually call RunMicrotasks at some point.

**Comment by wenq1** [comment]
I'm closing this issue now. quickjs seems to be offering a better alterantive.
