### ISSUE TITLE
return new Date in c

### ISSUE THREAD

**Issue by aflin** [svaarala/duktape#2293]
Apologies if I'm missing the answer to this.  I'm only 2 days into writing duktape/c functions.

Is there a better/faster way to return a new Date?

So far this is the only thing I've come up with that works:

`      duk_push_string(ctx, "(function(x){return new Date(x*1000);})");`
`      duk_eval(ctx);`
`      duk_push_int(ctx,0);`
`      duk_push_int(ctx,(duk_int_t)date_in_seconds);`
`      duk_call_method(ctx,1);`

I am returning rows from a database, so it is possible that I'll be eval()ing that code many times.

Thanks in advance.

**Comment by aflin** [comment]
I figured it out:
```
(void) duk_get_global_string(ctx, "Date");
duk_push_number(ctx,1000.0*(duk_double_t)date_in_seconds);  
duk_new(ctx,1);
```

**Comment by svaarala** [comment]
Hi @aflin, that's the best you can do at present. There's no direct C API to push a Date instance.
