### ISSUE TITLE
"TypeError undefined not callable (property 'TestMethod' of [object Object]"

### ISSUE THREAD

**Issue by kumaran-git** [svaarala/duktape#2296]
I have the following Error "TypeError undefined not callable (property 'TestMethod' of [object Object])" Any insight or suggestion on what am I missing.

TestMethod is a member function of a SimpleObject class. I am pushing the global object
SimpleObject *so = new Simpleobject() as external, register the method TestMethod and make a call from the script;

function test2(){ external.TestMethod(); } test2()

**Comment by svaarala** [comment]
What do these print out:
- print(external)
- print(external.TestMethod)

**Comment by kumaran-git** [comment]
print(exernal) ->  [object Object]
print(external.TestMethod) -> Failed to push Script due to error SyntaxError: source decode failed (line 0)

**Comment by svaarala** [comment]
Something is wrong in registering the TestMethod.

**Comment by kumaran-git** [comment]
closing the issue. The issue as related to mismatched context.
