### ISSUE TITLE
Uninitialised buffer when DUK_USE_ZERO_BUFFER_DATA is set

### ISSUE THREAD

**Issue by TomMettam** [svaarala/duktape#2302]
Passing `Uint8Array.allocPlain(10)` directly to a C function and then reading the data with duk_get_buffer results in uninitialised memory being exposed, even when DUK_USE_ZERO_BUFFER_DATA is set

This does not occur if the buffer is first assigned to a variable.

**Affected:**
`
c_func(Uint8Array.allocPlain(10));
`

**Not affected:**
`
var plainBuf = Uint8Array.allocPlain(10);
c_func(plainBuf);
`

**Comment by svaarala** [comment]
That sounds odd, the buffer creation code should not be aware of the calling context. I'll try to see if I can reproduce this.

What does your C function look like?

**Comment by TomMettam** [comment]
It's complicated, i'll try to get you a simple repro

**Comment by TomMettam** [comment]
Ok, i'm unable to reproduce this using a simple test app so my stack must be corrupt somewhere. Sorry!

**Comment by svaarala** [comment]
No problem, let me know if you find the root cause :)

**Comment by TomMettam** [comment]
I was missing a `duk_pop` after a `duk_enum`.  It's a little counterintuitive which functions require a "pop" - I wonder if in a future revision, function names could be standardised so everything which pushes to the stack begins with `duk_push`?

**Comment by TomMettam** [comment]
Actually, I'm still seeing this issue after debugging the stack as much as I can.

I've created a repository with the code so far (it's by no means complete) - perhaps you can see what I'm doing wrong? (I'm probably doing many things wrong..)

https://github.com/CasperTech/node-duktype

**Comment by TomMettam** [comment]
(all of the duktape-specific code is in https://github.com/CasperTech/node-duktype/tree/master/src/duktype )

**Comment by TomMettam** [comment]
Ah, i got it. Absolutely nothing to do with Duktape - I needed Nan::CopyBuffer instead of Nan::NewBuffer (I stupidly assumed NewBuffer would make a copy).

**Comment by svaarala** [comment]
Good thing you found the root cause :+1:

> I was missing a duk_pop after a duk_enum. It's a little counterintuitive which functions require a "pop" - I wonder if in a future revision, function names could be standardised so everything which pushes to the stack begins with duk_push?

Worth considering IMO, so duk_enum() would become duk_push_enum(), and duk_next() would become duk_push_next().
