### ISSUE TITLE
A couple of questions..

### ISSUE THREAD

**Issue by TomMettam** [svaarala/duktape#2303]
Apologies if this is the wrong place, but I had a few questions about the API.

1) How do I create a Date object from C code?
2) ~How do I create and fill a (Node.JS style) buffer from C code?~ Figured this one out
3) Is there a way to change scope (i.e change "this" to point to child object of the global object)
4) ~If i already have an object on the global object like [global].foo, how do i push a new nested object e.g [global].foo.bar?~ And this too
5) ~How do I push a TypedArray? When I use duk_push_buffer_object with DUK_BUFOBJ_UINT32ARRAY and then query with instanceof, it doesn't seem to be a Uint32Array~ Sorted this one out too :)

Many thanks!

**Comment by TomMettam** [comment]
Here's a test case for the last item:

`#include <duktape.h>
#include <iostream>

int main()
{
    duk_context *ctx = duk_create_heap_default();

    int length = 64;
    duk_push_fixed_buffer(ctx, 64);
    duk_push_buffer_object(ctx, -1, 0, length, DUK_BUFOBJ_UINT32ARRAY);
    duk_replace(ctx, -2);

    if (duk_get_type(ctx, -1) == DUK_TYPE_OBJECT)
    {
        std::cout << " Confirmed object is an object" << std::endl;

        int index = -1;
        if (duk_is_buffer_data(ctx, index))
        {
            duk_get_global_string(ctx, "Uint32Array");
            if (duk_instanceof(ctx, index, -1))
            {
                std::cout << "Object is a UInt32Array" << std::endl;
            }
            else
            {
                std::cout << "Object is not a UInt32Array" << std::endl;
            }
        }
    }
    duk_pop(ctx);
    duk_destroy_heap(ctx);
    return 0;
}

`

**Comment by TomMettam** [comment]
I've got a temporary solution for #1 but I hate it..

`duk_eval_string(ctx,std::string("new Date(" + str + ")").c_str());`

Is there any way of doing this without using eval?

**Comment by svaarala** [comment]
The Date issue was covered in #2293.

**Comment by svaarala** [comment]
Re: 'this', when you are calling a function you can provide an explicit this binding when using `duk_(p)call_method()`.

**Comment by TomMettam** [comment]
Thank you!
