### ISSUE TITLE
Duktape deref notification?

### ISSUE THREAD

**Issue by TomMettam** [svaarala/duktape#2304]
In my project at https://github.com/CasperTech/duktype

When the user adds a function property with duktape, I need to store a local identifier so that I can call the appropriate NodeJS function.

However, if the function (or the containing object) is then deleted / garbage collected via a user script running within Duktape, I have no way of cleaning up the local identifier.

This is a problem, because potentially it could cause uncontrolled heap growth. Is there any way of getting a notification when something is either garbage collected, or becomes eligible for garbage collection?

**Comment by svaarala** [comment]
You can use finalizers, see https://duktape.org/guide.html#finalization.

**Comment by svaarala** [comment]
Closing now, let me know if the issue wasn't resolved.
