### ISSUE TITLE
how to get stack object

### ISSUE THREAD

**Issue by kumaran-git** [svaarala/duktape#2307]
I have a class member function void testMethod() which takes in generic type. I need to be able to get the object from the stack and call the member function.  
Is there a sample code on how to get the object address and pass to member function. 

script:
function test(){external.testMethod(external.tmethod()); }

**Comment by svaarala** [comment]
I'm not sure I understand which methods are scripted and which are native. But if your question is how a native Duktape/C function would call a method for an argument object, it would be something like:
```
duk_get_prop_string(ctx, 0, "methodName");  /* push method */
duk_dup(ctx, 0);  /* push "this" value (= object) */
duk_push_int(ctx, 123);  /* argument for method call */
duk_call_method(ctx, 1 /*nargs*/);  /* Stack change: [ ... method object argument ] => [ ... result ] */
```

Because this is quite common, there's also a helper for making object based method calls in https://duktape.org/api.html#duk_call_prop:
```
duk_push_string(ctx, "methodName");
duk_push_int(ctx, 123);
duk_call_prop(ctx, 0 /*object index*/, 1 /*nargs*/);
```

**Comment by kumaran-git** [comment]
The function TestMethod is a Class memeber function which is access via JS. TestMethod parameter is an object, and I am using the call back function which allows me to get the parameters and call the actual member function.  In order to do this I am fetching the parameter from the stack and calling the actual member function. I am able to get other types, but I am not able to find the doc to get the object type, as we dont have an api duk_get_object. I am looking to achieve what duk_get_object would do. Hope this makes things clear.

**Comment by svaarala** [comment]
There's no way to get an object as a C type. An object simply resides on the value stack, and you can operate on it using e.g. duk_get_prop_string(), duk_call_prop(), etc.

**Comment by svaarala** [comment]
Closing this now, let me know if the issue wasn't resolved.
