### ISSUE TITLE
Accessing the output from the Duktape lexer

### ISSUE THREAD

**Issue by bjaastad** [svaarala/duktape#2308]
Hi!

Is there an official, or an unofficial, way for an end user to access the intermediate token values that are output from the Duktape lexer?

I have a case where I'm using Duktape to handle complex and non-trivial evaluations, but where I want to handle some simpler forms of evaluations myself, in my C++ code (for various reasons).

I want to be able to tell the difference between the two.

For instance, if the eval is "**if (someProperty > 5) {someOtherProperty + 3} else {yetAnotherProperty - 1}**", then I want to handle it in Duktape. 

But, if the eval is "**someProperty + 10**", I want to parse it in C++, and realize the meaning of the expression, without having to pass it on to Duktape, if that makes sense.

I could parse and tokenize the expression myself, but I'm thinking, since I'm already using Duktape, that maybe there's a way, in my C++ code, to get access to the results from the internal parsing and tokenization support that's already in Duktape. Is there such a way?

**Comment by svaarala** [comment]
The parser/compiler is unfortunately not pluggable in this way, so you'd need to use an external parser to do this.

**Comment by bjaastad** [comment]
Ok, thanks! :)

**Comment by svaarala** [comment]
For your use case I think the ideal format would be an intermediate representation (a tree model or similar), which would allow optimization and transformation passes before final compilation. At present there's no such intermediate representation, and there's a memory cost in adding one, but it would be nice in many ways.
