### ISSUE TITLE
shared_ptr retrieved seems to be corrupt. The ref count is all wrong

### ISSUE THREAD

**Issue by kumaran-git** [svaarala/duktape#2311]
Is there a specific way to work with shared pointers. I have a requirement where in my C++ member function returns a shared pointer and while I retrieve the pointer using  

duk_get_prop_string(ctx, stackLoc, "\xFF" "obj_ptr");
void* ptr = duk_require_pointer(ctx, -1);
The reinterpret of the pointer is failing. Am i missing something.

**Comment by svaarala** [comment]
What happens?

**Comment by kumaran-git** [comment]
SEH exception. Debugging the issue it fails while incrementing the reference count also the reference count when we reinterpret the pointer is very high in the range of MAX_INT, when it gets incremented it overflow and fails.

**Comment by svaarala** [comment]
Duktape does nothing with the pointer - it's just stored as a `void *` with no interpretation. So the first thing you should check is whether you get the exactly same `void *` back as you store. If so, the issue should not be caused by Duktape.

**Comment by kumaran-git** [comment]
The issue turned out to be in multiple inheritance and pointer was getting truncated. Closing the ticket, thanks for the comments.
