### ISSUE TITLE
Application using duktape

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#2312]
I'd like to mention an application which uses duktape, so that you can include that in your list of [projects using duktape](https://wiki.duktape.org/projectsusingduktape).

It's a terminal application, called [MySQL GUI Automator](https://github.com/mysql/mysql-workbench/tree/8.0/tools/mga) (short: MGA), which is part of the MySQL Workbench repository. My team and I developed it over 2 years and used duktape for scripting the tool on Windows, macOS and Linux. It uses the accessibility layer on each platform to control the behavior of a GUI application (even though itself is only a terminal app), mainly for testing purposes.

More interesting for you is probably that we implemented a backend in C++11 (which is **not** based on libuv) that is pretty close to Node.js. It's so close that we can use Node.js modules like [Jasmine](https://jasmine.github.io/), to run unit tests. It includes timers, a run loop and everything you would want from such a backend. The entire tool is released under GPL (like all open source from MySQL).

**Comment by webfolderio** [comment]
@mike-lischke As i understood your team wrote C++ binding for duktape. Is it possible to use [scripting-context.cpp](https://github.com/mysql/mysql-workbench/blob/8.0/tools/mga/src/library/scripting-context.cpp) as a standalone c++ library.

**Comment by mike-lischke** [comment]
Absolutely, yes. The entire tool MGA is a standalone tool and requires nothing from MySQL Workbench. The only extra dependency (beside libss, libcrypto and libduktape) is libmysqlcppconn, as we implemented a database module for MySQL connectivity (which is important to Workbench testing).

**Comment by svaarala** [comment]
@mike-lischke Sorry for the delay, added here: https://github.com/svaarala/duktape-wiki/pull/231 :+1:
