### ISSUE TITLE
Fuzzilli Integration

### ISSUE THREAD

**Issue by WilliamParks** [svaarala/duktape#2319]
This issue is to cover integration with [Fuzzilli](https://github.com/googleprojectzero/fuzzilli).

Design decisions:
- What duktape branch should be targeted? I'm currently running against v2-maintenance, but currently believe it's branch agnostic. This should be tested either way.
- What duktape builtins should be included? It's a tradeoff of efficiency of the fuzzer (`Duktape.version` is probably not going to produce a bug) vs coverage.

**Comment by WilliamParks** [comment]
Additional issue, that I'm not sure how to resolve. Since the default build process for duktape puts everything into duktape.c, the resulting coverage number is poor and not representative of the actual engine coverage. The number given by the fuzzer includes the C/C++ API (https://duktape.org/api.html), of which Fuzzilli only uses a small portion.

For reference, after ~21 core-days, coverage is at 34%

**Comment by svaarala** [comment]
It's probably easiest if the changes are made to master, and then cherry-picked to v2-maintenance if that's straightforward.

**Comment by svaarala** [comment]
Regarding that coverage issue, it's (still) possible to build Duktape from separate source files, and with or without `#line` directives in the combined source (if that helps).

I've also run some coverage analysis on how much of the code base is covered by current tests. Coverage from both ECMAScript and API tests is pretty good, but from ECMAScript tests alone API test coverage is low, just like with fuzzing.

**Comment by WilliamParks** [comment]
> It's probably easiest if the changes are made to master, and then cherry-picked to v2-maintenance if that's straightforward.

I have it based on master now, and generally cleaned up. Shouldn't be an issue!

I'm working on the fuzzilli side, and should have something together shortly (it fuzzes fine locally, just want to get it into their docker build process). 

From there, a round of iteration on which builtins are used/how its compiled/etc should help improve coverage.

**Comment by WilliamParks** [comment]
The outstanding items:
- Figure out the proper place for the assert (duk_fuzzillia.c needs to be able to intentionally fail an assert. as part of the startup checks
-  Consider how to improve coverage, both by removing dead code in the compilation target, and verifying which duktape unique builtins should be included (list [here](https://github.com/WilliamParks/fuzzilli-1/blob/duktape_integration/Sources/FuzzilliCli/Profiles/DuktapeProfile.swift#L32))
- Clean up the lint errors

**Comment by WilliamParks** [comment]
https://github.com/googleprojectzero/fuzzilli/pull/77 is the integration on the fuzzilli side. Only thing remaining is final make targets to easily run the fuzzer in this repo.
