### ISSUE TITLE
JSON debug proxy: Where is it?

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#232]
I remember reading in the documentation somewhere that Duktape includes an optional proxy server implementation for using JSON-mapped debug commands instead of the raw binary protocol.  I can't seem to find it anywhere in the repository though.  Where is it and how do I go about using it?

**Comment by svaarala** [comment]
It's part of the example debugger client: https://github.com/svaarala/duktape/tree/master/debugger/README.rst

**Comment by fatcerberus** [comment]
Thanks. :)  I feel really stupid asking these kinds of simple questions in the Issues, but it seems like the only way to get in contact with you, so...

**Comment by svaarala** [comment]
You can also email me - and there's an IRC channel too :-)

**Comment by svaarala** [comment]
But I don't really mind as long as issues don't hang in open state unnecessarily :)

**Comment by fatcerberus** [comment]
Ah, I can take a hint. I'll close it now!

**Comment by svaarala** [comment]
That wasn't really my intent above, though :) Just in general I don't mind "small issues" as long as they don't accumulate and are somehow actionable.
