### ISSUE TITLE
Advice:Can it support ES2015 Module?

### ISSUE THREAD

**Issue by ScSofts** [svaarala/duktape#2330]
The Module system like CJS isn't firendly to javascript editor.Can it support ES2015 Moudle so that I can improve my work efficiency by using VSCODE that is famous.

**Comment by sva-p** [comment]
ES2015 modules are not yet supported, except via transpiling.

**Comment by IngwiePhoenix** [comment]
Bumping this just to ask if this has been updated as I see quite a lot of "module" filenames, though most of them seem to refer to CJS style modules.

**Comment by svaarala** [comment]
No update at present, i.e. CommonJS style modules are used.
