### ISSUE TITLE
Compilation warnings with -Wfloat-equal

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#234]
There are currently several compilation warnings with `-Wfloat-equal`. It'd be best to avoid direct float comparison for portability reasons - but Duktape does need to some comparisons here and there. Figure out what the most portable approach is (casting doesn't seem to be enough). An example of a typical problem is x86/x87 where a comparison might use the extended 80-bit precision rather than working with 64-bit IEEE doubles.

Note that this issue is _not_ about floating point precision errors which happen during comparison. Equality comparison for IEEE doubles _is_ well defined (for the values Duktape compares) but the compiler is not guaranteed to use it, even when comparing IEEE double values.

**Comment by svaarala** [comment]
Quite annoyingly, it doesn't seem to be enough to cast arguments explicitly to `double` to silence the warning:

```
#include <stdio.h>

int main(int argc, char *argv[]) {
    double x = 1.0, y = 1.0;
    if ((double) x == (double) y) {
        printf("equal\n");
    }
    return 0;
}
```

Results in (using gcc 4.8.4 on x64):

```
misc/float_equals.c:5:17: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  if ((double) x == (double) y) { printf("equal\n"); }
```

**Comment by svaarala** [comment]
https://randomascii.wordpress.com/2012/03/21/intermediate-floating-point-precision/

**Comment by fatcerberus** [comment]
The warning is sound: depending on how a value is calculated, two values that /look/ equal (have the same string representation) may in fact have one or two bits of difference, in which case the comparison fails.

Everything I've read is always that you should use a small epsilon when checking for FP equality.

If the equality check is really what you want, couldn't you cast them to pointers and back, i.e:

`*(double*)&d1 == *(double*)&d2`

That might be enough to trick the compiler into shutting up. :o)

**Comment by svaarala** [comment]
@fatcerberus Like I said above, this is not about precision issues, but rather ensuring that IEEE doubles are indeed compared as IEEE doubles. Rounding errors are not the issue here ... :)

Casting to another type won't be correct: it won't work on a 32-bit target among other things and won't handle NaNs etc correctly.

**Comment by svaarala** [comment]
Ah, I misread your pointer trick.

I'm not sure why that should work portably, any more than explicitly casting the values to `double` which gcc still complains about. Some of the values being compares are also constants, but I could declare them as dummy locals if necessary.

**Comment by svaarala** [comment]
Nope, the trick doesn't work:

```
/tmp/foo.c:17:20: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  if (*(double *)&x == *(double *)&y) {
```

**Comment by svaarala** [comment]
To be clear, the generated assembly is correct for x64. It might not be correct for x86 when using x87 floating point arithmetic. But I suspect the gcc warning is unconditional and unrelated to actual generated code.

**Comment by svaarala** [comment]
@fatcerberus Here's an example of where Duktape needs to use IEEE double comparison:

- http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3

In step 1.c.iii:

> If x is the same Number value as y, return true.

The "same Number value" requires a comparison for non-NaN numbers (NaN values are excluded explicitly beforehand). The whole comparison is a bit messy to implement, but it is part of the required semantics.

**Comment by fatcerberus** [comment]
Yeah, the warning in question is there to warn coders that carelessly compare FP numbers and then wonder why things don't work properly.  Kind of dumb that the cast doesn't remove it, I agree there.

**Comment by fatcerberus** [comment]
Here's an evil trick you could try: `memcmp`.  No idea what the performance hit on that would be though, if any.

**Comment by svaarala** [comment]
That wouldn't be correct for comparing zeroes (which must compare equal regardless of their sign).

**Comment by svaarala** [comment]
The easiest way to guarantee correct comparison would probably be inline assembly, but it'd be nice to have a maximally portable default too.

**Comment by fatcerberus** [comment]
Signed zero has to be the dumbest thing anyone ever came up with. :P

**Comment by svaarala** [comment]
The C99 define `FLT_EVAL_METHOD` is relevant:

- 0: intermediate precision is dictated by the types used
- 1: intermediate precision is double precision (unless the types used are higher precision)
- 2: intermediate precision is long double

Values 0 and 1 should lead to correct code being emitted. Value 2 might potentially cause problems in the general case, but since the 64-bit to 80-bit conversion is lossless, this should not be the case in practice for Duktape.

**Comment by fatcerberus** [comment]
_Is_ 64- to 80-bit lossless?  I know it would be for twos-complement integers, but I don't know that much about floating-point representation to say in that case.  You would clearly know better there. :)

**Comment by svaarala** [comment]
The exponent range is larger and the mantissa is longer so the conversion is lossless. NaN representation is always interesting but the specific NaN values don't matter for the Duktape comparisons (as long as NaNs compare not equal to other values).

**Comment by svaarala** [comment]
Just checked that for gcc-4.8.4: FLT_EVAL_METHOD is 0 for x64 and 2 for x86 (-m32). There are no known issues on x86 so I don't think there's a concrete issue with extended precision.

**Comment by fatcerberus** [comment]
Good to know, so now you just have to figure out how to shut up the warning...

**Comment by randomascii** [comment]
I wrote the blog post cited above:

https://randomascii.wordpress.com/2012/03/21/intermediate-floating-point-precision/

I also wrote a blog post about testing floating-point routines, here:

https://randomascii.wordpress.com/2014/01/27/theres-only-four-billion-floatsso-test-them-all/

In there I said "Conventional wisdom says that you should never compare two floats for equality – you should always use an epsilon. Conventional wisdom is wrong."

It is *often* a bad idea to compare floating-point numbers for equality, but a warning that says that doing so is dangerous and gives no way to indicate that you know what you are doing is a *bad* *warning*, IMHO, because sometimes an exact comparison is exactly the right thing to do.

I think you should consider disabling the float-equal warning. It is quite possible that it is causing more harm than good, and if that is the case then disabling it is the righteous thing to do.

**Comment by svaarala** [comment]
@randomascii I agree that -Wfloat=equal is not really that useful when compiling Duktape, or any other code base where exact floating point comparisons are made on purpose (with Duktape under IEEE assumptions no less).

However, the problem is that because Duktape doesn't have any official build system, users build it as part of their application using whatever build system and options they're using. Sometimes they enable -Wfloat=equal and wish that Duktape was warning free under that option. I've enabled the warning in the repo Makefile so that I can keep track of what (some) users are seeing when they compile. It's not a recommendation to use -Wfloat=equal when compiling Duktape.
