### ISSUE TITLE
Turkish Locale Bug (locales not supported)

### ISSUE THREAD

**Issue by webfolderio** [svaarala/duktape#2343]
Hi,

I know that duktape doesn't support fully Turkish [1] characters, but is it possible to fix the below bug.

```js
console.info('öÖçÇşŞiİğĞüÜıI'.toLocaleLowerCase('tr-TR'));
console.info('öÖçÇşŞiİğĞüÜıI'.toLocaleUpperCase('tr-TR'));
```

duktape:

```js
ööççşşii̇ğğüüıi
ÖÖÇÇŞŞIİĞĞÜÜII
```

chrome:
```js
ööççşşiiğğüüıı
ÖÖÇÇŞŞİİĞĞÜÜII
```

Incorrect mapping 1:
```js
ı => İ (wrong, duktape), ı => I (correct, chrome)
```

Incorrect mapping 2:
```js
i => I (wrong, duktape) i => İ (correct, chrome)
```

Other mappings seems fine.

[1] [limitations.html](https://github.com/svaarala/duktape/blob/master/website/guide/limitations.html)

> Although Duktape supports the concept of a local time, it doesn't support
other locale related features such as

**Comment by svaarala** [comment]
To clarify, Duktape doesn't support setting locale or following the locale of the platform. So one is running the same "locale" regardless of the platform and there's no table of locales (such as `tr-TR`).

Any behavior that is the same regardless of locale can be changed or fixed. But fixing something locale specific runs the risk of incorrect behavior for other locales.

**Comment by svaarala** [comment]
This particular behavior unfortunately seems to be locale specific. For example, on Firefox:
```
console.info('öÖçÇşŞiİğĞüÜıI'.toLocaleLowerCase());
console.info('öÖçÇşŞiİğĞüÜıI'.toLocaleUpperCase());
```

Prints:
```
ööççşşii̇ğğüüıi
ÖÖÇÇŞŞIİĞĞÜÜII
```

In other words without the specific locale, the behavior matches Duktape behavior.

**Comment by svaarala** [comment]
A few things you could consider in the short term:
- You could try to work around this issue by forcing the tr-TR behavior in the UnicodeData tables when you prepare Duktape for configuration. This would only be correct if working with a tr-TR locale in general is desirable.
- You could override toLocaleUpperCase() and toLocaleLowerCase() to support tr-TR, falling back to the default implementation.

Longer term we could add some locale awareness to Duktape, i.e. both a concept of current locale and locale sensitive operations like .toLocaleUpperCase()/.toLocaleLowerCase().

**Comment by webfolderio** [comment]
Thanks for information.

> You could override toLocaleUpperCase() and toLocaleLowerCase() to support tr-TR, falling back to the default implementation.

This is the best and easiest solution for me.
