### ISSUE TITLE
Embed in kernel code

### ISSUE THREAD

**Issue by c3r34lk1ll3r** [svaarala/duktape#2348]
Hi,

I'm trying to embed ```duktape``` in kernel code as a module but I continuously have various errors. 

My biggest problem is to disable floating point numbers because of the error ```SSE register return with SSE disabled```. Is there a way to completely disable floating point? Has anyone tried this?

Thanks for any hints.

**Comment by svaarala** [comment]
Duktape can run on bare metal for instance, but it requires floating point arithmetic so you would need to work that out somehow (e.g. use soft floats).
