### ISSUE TITLE
duk_config.h cleanups for initial release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#235]
Resolve issues needed for initial release of `duk_config.h` and `genconfig` based configuration model:

- [x] Genconfig: add unhandled config option defaults to autodetect header (useful when config metadata has been added but there's no snippet to provide a value)
- [x] Genconfig: forced options for autodetect header
- [x] Genconfig: forced header lines on command line (useful for very small fixups)
- [x] Genconfig: support `-DDUK_USE_FOO` and `-UDUK_USE_FOO` for convenience
- [x] Genconfig: move Date provider handling to after duk_custom.h
- [x] Genconfig: modular, autogenerated autodetect header => prototype exists, finish in Duktape 1.4
- [x] Resolve genconfig FIXMEs => resolved necessary FIXMEs for autodetect header
- [x] Provide prebuilt headers for Windows/Linux/OSX for both GCC and clang, and x86/x64 architectures (somewhat experimental) => left out of dist intentionally to avoid confusion
- [x] Provide prebuilt header for Linux, gcc/clang, and ARM/MIPS architecture (somewhat experimental) => left out of dist for now, headers are not finished
- [x] Add example option overrides for "low memory", "timing sensitive", "no es6", etc.
- [x] Decide where option documentation should go: distributable, website, or both? => Option documentation is autogenerated into the Wiki
- [x] Finalize website and internal documentation

This is a follow-up for #64.

**Comment by fatcerberus** [comment]
Regarding option documentation, I think it should definitely go on the website.  The API and Guide already have pages there, so this would just be a natural extension of that, I think.

**Comment by svaarala** [comment]
I'll do improvements for 1.3 release using a timebox: the main supported thing is still `duk_config.h` autodetection, and directly editing `duk_config.h` manually for exotic platforms. Other genconfig features, prebuilt platform headers, etc are not yet ready, but these can be safely postponed to 1.4.

**Comment by svaarala** [comment]
Cleanups in master. Genconfig is far from complete but it's good enough for a 1.3 release. In practice it means `autodetect-header` command with optional overrides is functional, so that you can e.g.:

```
$ python config/genconfig.py \
      --metadata config/genconfig_metadata.tar.gz \
      --output duk_config.h \
      --option-file my_options.yaml \
      -DDUK_USE_FASTINT \
      autodetect-header
```

This allows construction of a custom autodetect `duk_config.h` with overrides specified from file(s) and/or command line options, so that you don't need to work with compiler command line `DUK_OPT_xxx` anymore if you don't want to.

The `barebones-header` command and its related metadata is unfinished, and for Duktape 1.4 the autodetect header will be constructed from modular snippets, simplifying the required metadata/snippets and their maintenance. I'll continue these in master after 1.3.
