### ISSUE TITLE
Can it be embedded in react native?

### ISSUE THREAD

**Issue by a4646054** [svaarala/duktape#2350]
Can it be embedded in react native? Implement multithreading in RN!

**Comment by dazhbog** [comment]
What would be the usecase? Any more info?

**Comment by semmypurewal** [comment]
I don't know if anyone else has gotten this working, but I've made some progress. I wrote [JSI bindings for Duktape](https://github.com/semmypurewal/duktape-jsi) which would be the first step in embedding this as the JS engine for React Native.

I'm planning to give this a try in the near future, but if anyone else has managed to make this happen please reach out!
