### ISSUE TITLE
Duktape memory use question

### ISSUE THREAD

**Issue by raist-** [svaarala/duktape#2353]
Hi,

I have a custom memory allocator implemented and have been running memory testing with Duktape. I log the amount of memory allocated after loading my JS into Duktape and get a value of xKB. However, if I measure the change in PSS after loading, I see an increase of almost 2xKB. I was wondering if this is expected and if you had any ideas why this might occur. I have been unable to account for this PSS growth with massif.

**Comment by svaarala** [comment]
It's unfortuntely difficult to answer without knowing how your custom allocator works. Have you checked out what happens to PSS if you allocate a set of regions with the custom memory allocator?

Typically an allocator manages memory in its own data structures, requesting more pages from the OS as needed. Pages are typically requested in "chunks" so the OS often sees a larger allocation than actually in use in the allocator.

**Comment by raist-** [comment]
It sounds like you’re saying the custom allocator should account for all of Duktape’s memory usage? I’m currently using a basic malloc wrapper. Do you mean trying a pooled allocator that manually uses mmap or something like that?

**Comment by svaarala** [comment]
Duktape shouldn't bypass the custom allocator, all allocs/reallocs/frees should go through it.
