### ISSUE TITLE
String.prototype.slice does not work on strings containing only numbers

### ISSUE THREAD

**Issue by zinke-ct-video** [svaarala/duktape#2363]
Hello,

when I interpret javascript code using duktape, I noticed that
`"ABCDE".slice(2)` returns "CDE" as result, but `"12345".slice(2)` gives an empty string as result. Is this a bug?

This seems to be a general problem:

`ABCDE".charCodeAt(0)` returns 65
`"12345".charCodeAt(1)` returns null

Can anyone confirm this behaviour?

Thank you very much!

**Comment by svaarala** [comment]
Can't reproduce with the duk command line:
```
((o) Duktape [linenoise] 2.99.99 (v2.5.0-187-gf013ce00)
duk> "12345".slice(2)
= "345"
duk> "12345".charCodeAt(1)
= 50
```

Can you show the calling code?

**Comment by svaarala** [comment]
@zinke-ct-video Any update on this?

**Comment by zinke-ct-video** [comment]
Sorry for not responding so long ...
After a month of development I have tested the same thing again on our system. The problem does not occur anymore. I assume that the bug was located in my code around the console, transferring the input and output from / to the user.

**Comment by svaarala** [comment]
Ok, good to know it worked out :+1:
