### ISSUE TITLE
"duk" example fails on long (> 64k) single line inputs

### ISSUE THREAD

**Issue by GravisZro** [svaarala/duktape#2367]
I pasted in some obfuscated code into duk (the utility) which starts by defining a string that is over 150KB long and it immediately failed and claiming it was an unterminated string.

**Comment by GravisZro** [comment]
`(function() { var z="";var b="150+ KB of hexadecimal string here";eval((function(){for (var i=0;i<b.length;i+=2){z+=String.fromCharCode(parseInt(b.substring(i,i+2),16));} return z;})());})();`

This is the specific code sans the actual string.

**Comment by svaarala** [comment]
This is a limitation of `duk`, the command line test utility, not the core lexer itself. It's caused by a fixed line buffer size assumption:
- https://github.com/svaarala/duktape/blob/master/examples/cmdline/duk_cmdline.c#L124

I'll look into a fix.

**Comment by svaarala** [comment]
#2368 removes the 64kb limit (present when linenoise was off). However, the symptom of the limit doesn't actually seem to match the issue description; instead of an unterminated string, 'duk' complains "line too long".

Could it be that the input you were giving 'duk' was a multiline expression (which are not handled)?

**Comment by GravisZro** [comment]
I built the latest version and tried it.  It's definitely all a single line and when pasting in the code it just halts at a certain point.  Here's a screenshot: https://i.imgur.com/IHJ1wFz.png

**Comment by GravisZro** [comment]
It seems there is a limitation on the number of characters that can be input for duk.  I have no problem pasting the string into nano.

**Comment by GravisZro** [comment]
I rebuilt with "DUK_CMDLINE_FANCY" disabled/undefined and it will paste the entire string.  However, the error persists as it claims the string is unterminated. https://i.imgur.com/L1vwOJp.png

**Comment by svaarala** [comment]
Are you 100% sure there are no newlines in the pasted input? For example in https://i.imgur.com/IHJ1wFz.png it seems quite clear that the input line terminates in the middle of the string.

If possible, could you try these:
1. `cat > /tmp/test`, paste the same input, and CTRL-D. Then `wc /tmp/test` to see how many lines there are.
2. `cat > /tmp/test`, and then run the file with `duk /tmp/test` (and just for comparison `nodejs /tmp/test`).

**Comment by GravisZro** [comment]
The first image shows the paste into duk when DUK_CMDLINE_FANCY was not disabled.  It seems to have a limit on the number of characters that can be input at once before preventing you from entering more characters.  The second image is with DUK_CMDLINE_FANCY disabled.  Neither seems to parse the full string.

I am 100% sure it's only one line and just to be super sure, I even pasted it into nano, checked the number of lines and that it's the correct length.

> $ nano duktest.txt
> $ wc -l duktest.txt 
> 1 duktest.txt
> $ ls -l duktest.txt
> -rw-r--r-- 1 gravis gravis 176444 Oct 19 10:09 duktest.txt

You don't have to take my word for it either, you can get the script here and paste it into duk yourself: https://www.ampedwireless.com/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3

**Comment by svaarala** [comment]
Thanks, I'll see if I can reproduce with that input.

**Comment by svaarala** [comment]
Seems I can reproduce the issue. It only appears when pasting interactively, when piping in via stdin things work as expected.

**Comment by svaarala** [comment]
The interactive loop reads input with fgetc() one character at a time. I added a debug print when it encounters a newline (0x0a) and for some reason the command line tool always sees a bogus newline at offset 4095:
```
GOT 55 '7'
GOT 56 '8'
GOT 51 '3'
GOT 52 '4'
GOT 54 '6'
GOT 54 '6'
GOT 53 '5'
GOT 99 'c'
GOT 55 '7'
GOT 10 '
'
NEWLINE AT INDEX 4095
```

This might be related: https://unix.stackexchange.com/questions/131105/how-to-read-over-4k-input-without-new-lines-on-a-terminal. For me running:
```
$ stty cbreak
```
before trying the copy-paste fixes the paste.
