### ISSUE TITLE
Make Proxy internal properties non-writable and non-configurable

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#237]
Currently Proxy internal properties (_Target and _Handler) are writable and configurable, and the internal code assumes their value is sane (value is asserted for but not checked without assertions). Being writable and configurable, malicious Ecmascript code can now cause memory unsafe behavior by modifying _Target and/or _Handler.

Change the properties to be non-writable and non-configurable so that Ecmascript code won't be able to change the properties even with access to an internal key. C code, both user and Duktape internals, can still forcibly change the property values but that's OK. There's a potential need to modify these values when Proxy revocation is implemented.

**Comment by fatcerberus** [comment]
Weren't you talking a while ago about making internal properties inaccessible from Ecma code even with buffer-fu?  That seems like it would solve this problem anyway.

**Comment by svaarala** [comment]
Yes, but since that's an incompatible change it's probably best to do that in Duktape 2.0. This is to improve sandboxing in 1.3.

**Comment by svaarala** [comment]
Changed in master.
