### ISSUE TITLE
 error: 'func' may be used uninitialized in this function

### ISSUE THREAD

**Issue by Mair** [svaarala/duktape#2370]
Hi,

I've been trying to implement a simple example of running ductape on the esp32.
When I compile I get the following error

../main/duktape.c:66961:18: error: 'func' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   use_tailcall = duk__call_setup_act_attempt_tailcall(thr,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       call_flags,
                                                       ~~~~~~~~~~~
                                                       idx_func,
                                                       ~~~~~~~~~
                                                       func,
                                                       ~~~~~
                                                       entry_valstack_bottom_byteoff,
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       entry_valstack_end_byteoff,
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       &nargs,
                                                       ~~~~~~~
                                                       &nregs,
                                                       ~~~~~~~
                                                       &vs_min_bytes,
                                                       ~~~~~~~~~~~~~~
                                                       &act);
                                                       ~~~~~

Not sure what I'm missing, Is there something I can do to fix this?

**Comment by svaarala** [comment]
If I recall correctly that warning is harmless as the situation should never occur (the compiler can't always figure this out).

You could just disable -Werror and see what happens?

**Comment by Mair** [comment]
@svaarala 
Thank you for the reply.
Unfortunately It's part of the bigger esp32-idf framework where it's defined outside my project. Looking the the documentation  https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#optional-project-variables 
it seems there might be a way to switch it off but I haven't gotten it to work
is there anything I can do code wise to work around this?

**Comment by Mair** [comment]
@svaarala 
I got the flag working correctly, Thank you for your support
for anyone who might be interested you need to add 
```
set_source_files_properties(duktape.c PROPERTIES COMPILE_FLAGS -Wno-maybe-uninitialized)
```
to the the cmakelists.txt
