### ISSUE TITLE
Rest global object to default state (persist debug connection under "hot-reload")

### ISSUE THREAD

**Issue by JoshMarler** [svaarala/duktape#2376]
Hi All, 

Apologies if this is the wrong location for such a question. Please let me know if that be the case and I will close this issue. 

I've been working with duktape over at https://github.com/nick-thompson/blueprint. 

We have some 'hot-reload' functionality where we would like to be able to persist debugger transport connections during a reload/bundle-eval. So, rather than tearing down and recreating our engine's `duk_context` when we detect a bundle change, we clear the stack and then re-evaluate the bundle. 

See: https://github.com/nick-thompson/blueprint/blob/master/blueprint/core/blueprint_EcmascriptEngine.cpp#L204

However, this has recently been causing some issues, presumably due to global state being polluted with references to old objects etc. 

See: https://github.com/nick-thompson/blueprint/issues/138

Is there any sensible way to reset the global environment/object state without the disposing of the `duk_context` which kills active debugger connections?

Thanks

**Comment by svaarala** [comment]
There is nothing that would allow you to do that at present. It would mean not only resetting the global object (and built-ins) but also all native state stored in stahes, etc (this is probably what you would want I think).

Is there any way you could hide the reconnect from relevant peers? Note that Duktape debug transport does not need to match e.g. a TCP transport 1:1 - you're free to carry multiple debug transports over TCP e.g. via some tagging.

**Comment by JoshMarler** [comment]
Thanks for taking the time @svaarala! 

Right understood. Thanks for confirming. In regards to hiding a reconnect, we can reasonably set duktape to awaiting debug connection from a client immediately on re-evaluation of the bundle. The tricky part is transparently reconnecting the debug client (in our case the VsCode extension) without the user having to reconnect manually. 

I suspect this will involve a change to the extension to attempt reconnects for a given period if the connection is terminated by duktape. 

You've answered my question though so I'll close this. Much appreciated.
