### ISSUE TITLE
How to run a whole js file multiple times using duk_pcall? (question)

### ISSUE THREAD

**Issue by ximiTech** [svaarala/duktape#2377]
I try to continuously call a js file, using `duk_pcall` to do it, here is what I tried:

Firstly, I load the script file into a char* string.
Secondly, use `duk_pcompile_string(ctx, 0, programBody)` to compile it.
Then, I can use `duk_pcall(ctx, 0)` to call it once, and call `duk_pop(ctx)`.
But when I try to use `duk_pcall` a second time, I failed.

Can you give me some advice about how to do it the right way?

**Comment by svaarala** [comment]
The stack behavior in your example is as follows. After compilation:

    [ func ]

Once you duk_pcall(ctx, 0), the stack will become

    [ result ]

Note that duk_pcall() pops the function and replaces it with the return value (see stack description in https://duktape.org/api.html#duk_pcall).

If you want to keep the compiled function and call it again without recompiling, you'd need to duk_dup() first to get:

    [ func func ]

Then duk_pcall(ctx, 0) to get:

    [ func result ]

And then duk_pop() to remove the result:

    [ func ]

Now you'd be ready to duk_dup() again.
