### ISSUE TITLE
Add links to similar engines on index page

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#240]
There are quite a few engines which target use cases similar to what Duktape targets. Add a link list to the index page.

Branch: https://github.com/svaarala/duktape/compare/website-other-engine-links?expand=1

**Comment by svaarala** [comment]
Any suggestions for more? Current list:

- JerryScript
- MuJS
- quad-wheel
- Espruino

**Comment by fatcerberus** [comment]
I was only aware of MuJS, personally.  This is the first I've heard of the others...

**Comment by creationix** [comment]
Do you want only JS implementations or all minimal scripting languages?  I'm working on [μScript](https://github.com/creationix/uscript) which is based on [Bitlash](http://bitlash.net/).  And of course there are the many eLua variants.

**Comment by svaarala** [comment]
I'd like to link to relevant alternatives to those considering Duktape - so at least (currently!) functional embeddable JS engines fit that goal. Listing non-JS engines would probably make the list too long.

**Comment by mamod** [comment]
What about [v7](https://github.com/cesanta/v7) Embedded JavaScript

**Comment by svaarala** [comment]
@mamod Have you tried it out? Release notes seem to indicate there's still some built-ins missing etc. But if it's basically functional I'll add it to the list.

**Comment by mamod** [comment]
I've tried it once when I was testing out available options, before getting my hands on duktape :) 
not exactly sure how things went out then, but I remember it was functional.
I thought it would be a good alternative because it's still active developed and used in [smart.js](https://github.com/cesanta/smart.js) project which also is actively developed

**Comment by svaarala** [comment]
Sounds good, I'll add it :)

**Comment by fatcerberus** [comment]
I did a quick Google search for more engines but couldn't find any; I think "JavaScript engine" and "small footprint" might just be conflicting goals. :wink:

The only other engine I can think off-hand is Jurassic, but that's C# so requires .NET.

**Comment by JoshEngebretson** [comment]
tiny-js: https://github.com/gfwilliams/tiny-js

**Comment by svaarala** [comment]
Added tiny-js, I remember I encountered that a while ago too.

@fatcerberus I wouldn't say that, but perhaps "fully featured JS engine" and "tiny footprint" are somewhat conflicting. Several small engines are in fact subsets and that makes sense if the other alternative is "no engine" :)

**Comment by fatcerberus** [comment]
tiny-js says it doesn't compile to bytecode but interprets the source directly... that must be really slow.

It's neat that there's so many tiny JS engines though, even if they're subsets. :)

**Comment by svaarala** [comment]
@fatcerberus IIRC Espruino does the same thing. If it saves memory it's probably quite appropriate to the target environment. There are a lot of applications where speed is a non-issue. I think it's great there are many engines with different focuses. :)

**Comment by svaarala** [comment]
Ok, the initial list is now in the repo (it's not pushed to duktape.org until 1.3 release though).
