### ISSUE TITLE
getting functions from scripts and calling them later

### ISSUE THREAD

**Issue by swoopae** [svaarala/duktape#2400]
hey, i'm currently trying to implement duktape as a scripting engine for a game engine project i'm working on and can't quite figure out how to do the following:
- i plan on having multiple scripts loaded from files
- i want to have a global addCallback function, which will work as following

```js
function runOnThink(a1, a2) {
//some code
}

function runOnDraw(a1, a2) {
//some more code
}

addCallback("think", runOnThink);
addCallback("draw", runOnDraw);
```

```cpp
static duk_ret_t add_callback ( duk_context * ctx ) {
	auto str = duk_to_string ( ctx , 0 );
	auto fn;// get function somehow
	
	functions_to_call.push_back(fn);
}

//on initialization
duk_push_c_function ( this->m_ctx , add_callback , 2 );
duk_put_global_string ( this->m_ctx , "addCallback" );

//in think/draw function
duk_call(...);
```

where in the c++ project i can call the runOnThink/runOnDraw functions.

the way i thought about doing this is getting the function by name and calling it manually using duk_call, but this would cause issues with multiple scripts. i also thought about evaluating one file, running the function by name with duk_call, clearing up, rince and repeat for each script, but i think that would be pretty slow, especially for a game in time-critical functions.

how would i go about this? sorry if this has been answered before, i've been scrolling through some issues but none of the ones i've found answer my problem exactly.

edit: using duktape 2.6.0

**Comment by markand** [comment]
Hi,

There are many ways to capture a function and call it later. Since your API wants a key as string what you can do is simply to store the function into a global hidden table and call it later.

For example, in your `add_callback` function you can so something like:

```c
static duk_ret_t add_callback ( duk_context * ctx ) {
    auto str = duk_to_string ( ctx , 0 );

    // Push the global stash to store the function object
    duk_push_global_stash(ctx);
    duk_dup(ctx, 1);                    // duplicate the function argument
    duk_put_prop_string(ctx, -2, str);  // store the function with given key.
    duk_pop(ctx);                       // remove the stash object

    // Use a local list of strings in your case to remember which callbacks are present.
    functions_to_call.push_back(str);
}
```

Then when you want to call them you can do the following:

```c
duk_push_global_stash(ctx);

for (const auto &key : functions_to_call)
    duk_get_prop_string(ctx, -1, key.c_str());  // retrieve the function stored
    duk_call(ctx, 0);                           // adapt with number of arguments
}

duk_pop(ctx);                                   // remove the stash object
```

You may want to use `duk_pcall` if you don't want the error to be propagated.
