### ISSUE TITLE
Python3's distinguishing between str and byte-like objects types.

### ISSUE THREAD

**Issue by NurTasin** [svaarala/duktape#2405]
When I tried to run `python tools/confugure.py` with the required options. An exception is thrown that says
```console
TypeError: cannot use a string pattern on a bytes-like object
```
All exceptions are thrown where a regular expression (regex) compiles or searches for something.
It seems that the strings are needed to be encoded accordingly. And that works for some scenarios. But there are so many cases where string needs to be encoded before they are used. I keep fixing one but another one appears. Please update your tools to work with modern python versions.

**Comment by svaarala** [comment]
All the Python tooling is now Python2 only, and it will be converted to JS (Node.js) rather than Python3.
