### ISSUE TITLE
How to trigger Garbage Collection?

### ISSUE THREAD

**Issue by ghost** [svaarala/duktape#2407]
How to trigger Garbage Collection in JavaScript?

**Comment by shdon** [comment]
Can't you just expose it via an extremely simple function?

`duk_ret_t GC(duk_context *ctx)
{
	duk_gc(ctx, 0);
	return 0;
}

duk_push_c_function(ctx, GC, 0);
duk_put_global_string(ctx, "GC");`

Then you can call `GC()` from inside the JavaScript context. That's how I did this.

**Comment by svaarala** [comment]
There's actually already a binding for this:
```
Duktape.gc();
```
