### ISSUE TITLE
Avoiding memory leaks when reusing global variables - advice please

### ISSUE THREAD

**Issue by antipole2** [svaarala/duktape#2413]
I have written a [plugin for the marine navigation program OpenCPN](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:beta_plugins:javascript) which uses Duktape to provide JavaScript programming of OpenCPN.
This is mostly working well but certain scripts cause OpenCPN to become sluggish with time, which I believe is due to memory leaks. I would appreciate confirmation or correction of my understanding of the issue.

Consider the following illustrative script:

```
var navData;

function update(){
	navData = OCPNgetNavData();
	print (navData.position, "\n");
	}
```
	
The function update is called every five seconds by the plugin and it calls native code which obtains navigational information from OpenCPN and returns it as an object.
Now this navData needs to be accessed elsewhere and so I have made it a global variable by declaring it outside the function.

As I understand it, variables that are objects are, internally, actually pointers to the object.  In the above case, when the function is called again, navData points to the new object while the previous object continues to exist, albeit unreachable.  

I seem to have fixed the problem in this case thus:

```
function update(){
	delete navData;
	navData = OCPNgetNavData();
	print (navData.position, "\n");
	}
```

I have another script that is causing the problem but the possible statements are many and I need to clarify which are the problem.
I believe this problem would not occur if navData were set to a number or boolean,
but does occur if it is set to any object, array or string.

Am I understanding this correctly, please?

**Comment by svaarala** [comment]
Duktape should handle garbage collection for all pure Ecmascript objects without any intervention. Circular structures collect with a delay as they need a mark-and-sweep pass.

How is OCPNgetNavData() return value created? Is it a native object? If so, does the native object free its resources on finalization?

**Comment by antipole2** [comment]
Herewith is the code that creates the structure. pJavaScript_pi points to where the data has been made available to the plugin.
Your further guidance will be very much appreciated.

```
static duk_ret_t getNavigation(duk_context *ctx) {  // gets latest navigation data and constructs navigation object
    extern JavaScript_pi *pJavaScript_pi;
    // ****  Indenting here shows stack depth - do not re-indent this section ****
    duk_push_object(ctx);
        duk_push_number(ctx, pJavaScript_pi->m_positionFix.FixTime);
            duk_put_prop_literal(ctx, -2, "fixTime");
        duk_push_object(ctx);                                  // start of position
            duk_push_number(ctx, pJavaScript_pi->m_positionFix.Lat);
                duk_put_prop_literal(ctx, -2, "latitude");
            duk_push_number(ctx, pJavaScript_pi->m_positionFix.Lon);
                duk_put_prop_literal(ctx, -2, "longitude");
            duk_put_prop_literal(ctx, -2, "position");             // end of position
        duk_push_number(ctx, pJavaScript_pi->m_positionFix.Sog);
            duk_put_prop_literal(ctx, -2, "SOG");
        duk_push_number(ctx, pJavaScript_pi->m_positionFix.Cog);
            duk_put_prop_literal(ctx, -2, "COG");
        duk_push_number(ctx, pJavaScript_pi->m_positionFix.Var);
            duk_put_prop_literal(ctx, -2, "variation");
        duk_push_number(ctx, pJavaScript_pi->m_positionFix.Hdm);
            duk_put_prop_literal(ctx, -2, "HDM");
        duk_push_number(ctx, pJavaScript_pi->m_positionFix.Hdt);
            duk_put_prop_literal(ctx, -2, "HDT");
        duk_push_int(ctx, pJavaScript_pi->m_positionFix.nSats);
            duk_put_prop_literal(ctx, -2, "nSats");
    return 1;  // returns one arg
}
```

**Comment by svaarala** [comment]
The object constructed by that function is a pure Ecmascript object so it should not cause a leak, regardless of the `delete` statement.

Do you have a way of measuring memory usage so you can confirm that memory actually leaks?

**Comment by antipole2** [comment]
I am actually at sea and have only a small screen at the moment.  When back on land I will set up a simulation and hopefully narrow down where the problem is.  I will also consult others on memory measurement.
Can we please leave this open or in abeyance for now?  I will get back to you - thank you.

**Comment by svaarala** [comment]
Sure, let's leave this open and let me know if some clue turns up. :+1:

**Comment by antipole2** [comment]
I have not seen this problem for a long while.

The plugin has been updated, including improvements in tidying up after a script terminates or the plugin is closed.  Maybe the issue got resolved somewhere along the line.

So let's close this.  Thanks for your input.
