### ISSUE TITLE
How to get "this" from within a c-method?

### ISSUE THREAD

**Issue by zzador** [svaarala/duktape#2415]
I have c code that constructs a javascript object that looks like this in javascript:

`obj : {
    someval : 123.456,
    myCFunc : function()
    {
          ...
    }
}`

Within "myCFunc" (which is written in C) I want to access "this.someval", however the stack is empty (duk_get_top(...) returns 0). How can I access "this" from a C-Object-Method?

**Comment by svaarala** [comment]
You can use https://duktape.org/api.html#duk_push_this to push the `this` reference to the value stack.

**Comment by zzador** [comment]
I have searched my eyes out for a function like that and it was in the API all the time. Now it works just fine. Thanks.
