### ISSUE TITLE
Duktape drops debug session

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#242]
So I don't know if I'm doing something wrong, but I set up this minimal test case for the debugger in C#:

```c#
    class DuktapeClient : IDisposable, IDebugger
    {
        TcpClient tcp = new TcpClient();

        public DuktapeClient()
        {
        }

        public void Dispose()
        {
            tcp.Close();
        }

        public void Connect(string hostname, int port, uint timeout = 10000)
        {
            long end = DateTime.Now.Ticks + timeout * 10000;
            while (DateTime.Now.Ticks < end)
            {
                try {
                    tcp.Connect(hostname, port);
                    return;
                }
                catch (SocketException) { }
            }
            throw new TimeoutException();
        }

        public void Run()
        {
            byte[] request = new byte[] { 0x01, 0x13, 0x0 };  // REQ 19 EOM

            tcp.Client.Send(request);
        }

        public void StepInto() { }
        public void StepOut() { }
        public void StepOver() { }
    }

// Somewhere outside, this happens:
// var client = new DuktapeClient();
// client.Connect("localhost", 812);
// client.Run();
```

My engine just reads the bytes from the socket and gives it to Duktape verbatim, but upon `Run()` above being called, Duktape immediately drops the session as though I sent invalid data.  What's wrong?

**Comment by fatcerberus** [comment]
Okay, I'm an idiot.  The request number is an integer dvalue, not a byte.  0x13 is the prefix for a buffer, so of course Duktape would drop the session as the request was nonsensical! I feel dumb now...

**Comment by svaarala** [comment]
Don't, it's an easy mistake to make :) It's all dvalues but it's easy to think in terms of bytes.

**Comment by fatcerberus** [comment]
By the way, is it normal for Duktape to only read one byte at a time?  I noticed that while I was trying to diagnose this issue, the read callback was being called with a 1-byte buffer each time.

**Comment by svaarala** [comment]
It's quite normal - there's no input buffering on the Duktape side so it pulls in bytes as needed. It will read larger amounts e.g. for string/buffer data. The intent is that the transport abstraction provides input buffering if that is relevant; e.g. if you use TCP directly, the OS will do it and there's little reason to have one.
