### ISSUE TITLE
utilizing DUK_USE_GET_RANDOM_DOUBLE results in compile error with DUK_UTIL_GET_RANDOM_DOUBLE

### ISSUE THREAD

**Issue by mpietras** [svaarala/duktape#2432]
The macro to utilize DUK_USE_GET_RANDOM_DOUBLE is defined as:

#define DUK_UTIL_GET_RANDOM_DOUBLE(thr) DUK_USE_GET_RANDOM_DOUBLE((thr)->heap_udata)

But thr is passed as a duk_hthread which doesn't contain heap_udata.
It seems that it should be this instead:

#define DUK_UTIL_GET_RANDOM_DOUBLE(thr) DUK_USE_GET_RANDOM_DOUBLE((thr)->heap->heap_udata)

**Comment by svaarala** [comment]
Looks like a bug, I'll check it out. Thanks for reporting!
