### ISSUE TITLE
Force linking against libm

### ISSUE THREAD

**Issue by tinywrkb** [svaarala/duktape#2464]
When the default `LDFLAGS` from the environment has `--as-needed`, then the generated shared libs would not be linked against `libm`.   
I suggest adding something like `-Wl,--no-as-needed,-lm` to the Makefile command.  
Example of an app that segfault when duktape is not linked against libm is polkit.  

I don't feel confident to send this as a PR, as I can't properly test this change, I'm not sure if this just need to be in `Makefile.sharedlibrary`, and how this affect other libc than glibc, so someone else will have to handle this issue.

**Comment by svaarala** [comment]
Please note that all Makefiles in the distributable are examples only. They are not intended to be functional on various porting targets. The intent is that everyone compiles Duktape with their own build systems, Makefiles, etc.

**Comment by tinywrkb** [comment]
What about just adding `LIBS=-lm` as a variable, and then add `$(LIBS)` to the Makefile command?  
It would at least document that the generated shared lib is expected to be linked against libm.

**Comment by svaarala** [comment]
If it makes the intent of the Makefile clearer then I'd be OK with that change. Also adding a comment re: --no-as-needed might be useful?

But ultimately without CI support with dozens of test targets it's difficult to get Makefiles that work for everyone, so IMO the best goal is to provide easy-to-read and illustrative Makefiles rather than trying to cover all targets.

**Comment by tinywrkb** [comment]
Actually, someone pointed out to me that by adding the lib linking after the source file also solves the issue, and without having to use `--no-as-needed`. It's pretty much like the Makefile command for `duk`.

**Comment by tinywrkb** [comment]
Closing, see #2480 for details.
