### ISSUE TITLE
Duktape.dec('jx', '1Infinity') parses as -Infinity

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#247]
In Duktape 1.2.2 and prior, `1Infinity` will incorrectly parse as `-Infinity`, which is caused by an error in the parsing condition which will parse anything beginning with a minus or a number followed by an `I` as -Infinity. The impact is that inputs that should cause SyntaxError are accepted, there should be no effect for valid inputs.

**Comment by svaarala** [comment]
Will be fixed by #209 merge.

**Comment by fatcerberus** [comment]
I get the `I` thing (opportunistically treating a number starting with I as infinity), but how does it end up treating a leading digit as a negation?  This seems like a weird bug. :)

**Comment by svaarala** [comment]
The bug is here: https://github.com/svaarala/duktape/blob/master/src/duk_bi_json.c#L655-L660

There's a shared parent if, and the child if checking for -Infinity ignores the leading character.

**Comment by svaarala** [comment]
Fixed in master.
