### ISSUE TITLE
Resume fails after setting an initial breakpoint using AddBreak

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#248]
This time I'm almost positive the issue isn't with the client.  I'm finding that issuing AddBreak requests causes the debugger to stop at the first executable statement in the script, and any further attempts to step or resume have no effect.

Here's my code to set up breakpoints:
```csharp
                            string relativePath = filename;
                            string rootPath = Path.Combine(_project.RootPath, @"scripts") + @"\";
                            if (filename.Substring(0, rootPath.Length) == rootPath)
                                relativePath = filename.Substring(rootPath.Length).Replace('\\', '/');
                            _tcp.Client.Send(new byte[] { 0x01, 0x98 });  // REQ 18h
                            _tcp.Client.SendDValue(relativePath);  // <str: filename>
                            _tcp.Client.SendDValue(lineNumber);  // <int: line>
                            _tcp.Client.Send(new byte[] { 0 });  // EOM
```

I've checked in the C# debugger, and the filename sent is `main.js` (matching the filename passed to Duktape in the target) with line number 33.  Duktape instead stops at line 6 (the first executable line in the script) and I am then unable to advance.

**Comment by svaarala** [comment]
Can you replicate this issue with the debugger web UI? There are no known (somewhat basic) known breakpoint issues, and it's difficult for me to do anything if I can't reproduce the issue.

Btw, when you attach the debugger execution will initially be paused automatically, so do you first send an AddBreak and then a Resume to (try to) get started? Can you provide a binary log of the debug messages sent in each direction?

**Comment by fatcerberus** [comment]
I'll have to get node.js set up properly to test out the web UI.  For now I could probably set up some logging of messages.

And yes, I'm aware that I have to issue an explicit Resume on attach.  What I'm currently doing is this: attach debugger, add breakpoints via REQ 18h, Resume.  If no AddBreaks are sent, execution starts normally.  If even one breakpoint is set, execution stops at the very first statement and advancing is impossible (step and resume do nothing).

**Comment by svaarala** [comment]
What you mean by "do nothing" in more detail? Does Duktape debug log that it has received the commands (or does it read them through the read callback)?

**Comment by fatcerberus** [comment]
I can only tell you that the messages are being sent out by the client, and the target hasn't frozen, as forcibly closing the transport causes execution to resume.  So Duktape just isn't responding to the requests for some reason, including the initial Resume.

I'll have to add some sort of logging mechanism to the target.  Most of my logging there is done to the console, so doing that for the transport would be too noisy for everyday use.

I suppose it's possible my AddBreak requests are malformed, but then wouldn't Duktape drop the session outright?

**Comment by fatcerberus** [comment]
How do I enable debug logging for Duktape?

**Comment by svaarala** [comment]
Here's a JSON debug proxy sequence with a similar test sequence. Arrows and comments added manually (to telnet output):

```
<-- {"notify":"_Connected","args":["1 10299 v1.2.0-234-gbdd02a0 duk command built from Duktape repo"]}
<-- {"notify":"Status","command":1,"args":[1,"test.js","global",1,0]}
--> {"request":"AddBreak","args":["test.js",3]}
<-- {"reply":true,"args":[0]}
--> {"request":"Resume"}
<-- {"reply":true,"args":[]}
# Here's the place you're having issues, but in this setup Resume works as expected.
<-- {"notify":"Status","command":1,"args":[0,"test.js","global",1,0]}
<-- {"notify":"Print","command":2,"args":["1\n"]}
<-- {"notify":"Print","command":2,"args":["2\n"]}
<-- {"notify":"Status","command":1,"args":[1,"test.js","global",3,9]}
# Here we've executed line 1 and 2, breakpoint on line 3 hit and Duktape is paused.
--> {"request":"Resume"}
<-- {"reply":true,"args":[]}
<-- {"notify":"Status","command":1,"args":[0,"test.js","global",3,9]}
<-- {"notify":"Print","command":2,"args":["3\n"]}
<-- {"notify":"Print","command":2,"args":["4\n"]}
<-- {"notify":"_Disconnecting"}
```

Input source is, breakpoint is for line 3:

```js
print(1);
print(2);
print(3);
print(4);
```

**Comment by svaarala** [comment]
To enable debug, just compile Duktape with `-DDUK_OPT_DEBUG -DDUK_OPT_DPRINT`.

**Comment by svaarala** [comment]
To be a bit pedantic, "client has sent a message" doesn't really compute - it's all pulled in by Duktape using the read callback, and what matters for diagnosing the issue is whether Duktape has read the bytes or not.

**Comment by fatcerberus** [comment]
Oh, I know that, I was just pointing out that I ran the client through the debugger and it got through the Send calls, so the client's responsibility of sending the bytes out was taken care of.  I'm reasonably certain the .NET sockets implementation isn't bugged. :)

Believe me, I'm doing everything in my power to make sure the client isn't at fault here.

I'll set up a test harness of some sort later and then report back.

**Comment by svaarala** [comment]
Hmm, so the debug client is talking to the target using plain old TCP? If so, can you Wireshark the traffic? :)

**Comment by svaarala** [comment]
Wireshark won't tell whether Duktape is getting the data in the read callback but it'd be an easy starting point. Also, debug prints from read/write callbacks on the target would be very useful (= for each call, bytes read/written).

**Comment by fatcerberus** [comment]
Yeah, it's just a plain TCP connection via loopback.  That seemed like the easiest way to go to get cross-process communication.

**Comment by svaarala** [comment]
That also means that if you have access to a Linux VM, you could run the debugger web UI there if that's any easier than the node setup on Windows.

**Comment by svaarala** [comment]
Or if your target has a public IP address, *I* could connect to the target remotely ;)

**Comment by fatcerberus** [comment]
The way my engine is set up right now, you'd only get one shot--I can't run it unattended because once the debugger is detached, that's it--the port is closed.  I should probably change that...

**Comment by svaarala** [comment]
I have to go to sleep anyway, let me know what you find out :)

**Comment by fatcerberus** [comment]
Wireshark can't capture loopback traffic on Windows, apparently.  So that's a no-go unless I modify minisphere to allow remote debugging (i.e. keep the port open at all times) and connect from another machine.

Looks like I'll have to implement logging.

**Comment by fatcerberus** [comment]
Transport log below, starting from initial attach up to the Resume attempt.  Right arrow is outbound (write callback), left arrow is inbound (read callback)
```
--> 26 bytes  31 20 31 30 32 30 32 20 76 31 2e 32 2e 32 20 6d 69 6e 69 73 70 68 65 72 65 0a
--> 1 bytes  04
--> 1 bytes  81
--> 1 bytes  81
--> 1 bytes  67
--> 7 bytes  6d 61 69 6e 2e 6a 73
--> 1 bytes  64
--> 4 bytes  65 76 61 6c
--> 1 bytes  86
--> 1 bytes  80
--> 1 bytes  00
<-- 1 bytes  01
<-- 1 bytes  98
<-- 1 bytes  11
<-- 4 bytes  10 00 00 00
<-- 17 bytes  07 6d 61 69 6e 2e 6a 73 10 00 00 00 21 00 01 93 00

# At this point Duktape is paused on line 6.  The breakpoint is set for line 33.

# After clicking Resume twice in the client:
<-- 3 bytes  01 93 00
<-- 3 bytes  01 93 00
```

Note the eerie silence from Duktape...

**Comment by svaarala** [comment]
Do you implement a peek callback, and do you have the transport callbacks somewhere online that I could check?

The next useful things would be:

- Running the test with `-DDUK_OPT_ASSERTIONS` enabled to see if that catches anything
- Running the test with `-DDUK_OPT_DEBUG` and `-DDUK_OPT_DPRINT` enabled and correlate debug prints with transport log

The debug log looks something like:

```
[D] <110016502931311> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110016510307997> duk_debugger.c:938 (duk__debug_handle_basic_info): debug command version
[D] <110016519557873> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110016570323754> duk_debugger.c:1013 (duk__debug_handle_list_break): debug command listbreak
[D] <110016573298846> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110016579312764> duk_debugger.c:1199 (duk__debug_handle_get_locals): varmap is not an object in GetLocals, ignore
[D] <110016581490908> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110016596081469> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110199687117690> duk_debugger.c:994 (duk__debug_handle_step): debug command stepinto/stepover/stepout: 21
[D] <110199696131460> duk_debugger.c:1654 (duk_debug_process_messages): processing debug message, peek indicated no data, stop processing
[D] <110199700858476> duk_js_executor.c:1674 (duk__interrupt_handle_debugger): processed debug messages, restart execution to recheck possibly changed breakpoints
[D] <110199735483423> duk_js_executor.c:1547 (duk__interrupt_handle_debugger): STEP STATE TRIGGERED PAUSE at line 105
[D] <110199738484063> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110199738785067> duk_debugger.c:1013 (duk__debug_handle_list_break): debug command listbreak
[D] <110199739207639> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110199739694315> duk_debugger.c:1199 (duk__debug_handle_get_locals): varmap is not an object in GetLocals, ignore
[D] <110199740050323> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110199741207759> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110204748278655> duk_debugger.c:994 (duk__debug_handle_step): debug command stepinto/stepover/stepout: 20
[D] <110204750101767> duk_debugger.c:1654 (duk_debug_process_messages): processing debug message, peek indicated no data, stop processing
[D] <110204750465517> duk_js_executor.c:1674 (duk__interrupt_handle_debugger): processed debug messages, restart execution to recheck possibly changed breakpoints
[D] <110204759537640> duk_js_executor.c:1547 (duk__interrupt_handle_debugger): STEP STATE TRIGGERED PAUSE at line 106
[D] <110204760863196> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110204762529429> duk_debugger.c:1013 (duk__debug_handle_list_break): debug command listbreak
[D] <110204762958717> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110204763397035> duk_debugger.c:1199 (duk__debug_handle_get_locals): varmap is not an object in GetLocals, ignore
[D] <110204763708453> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110204764822980> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110205228902841> duk_debugger.c:994 (duk__debug_handle_step): debug command stepinto/stepover/stepout: 20
[D] <110205230618817> duk_debugger.c:1654 (duk_debug_process_messages): processing debug message, peek indicated no data, stop processing
[D] <110205230848545> duk_js_executor.c:1674 (duk__interrupt_handle_debugger): processed debug messages, restart execution to recheck possibly changed breakpoints
[D] <110205235639551> duk_js_executor.c:1894 (duk__executor_handle_debugger): STEP INTO ACTIVE, FORCE PAUSED
[D] <110205237111498> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110205238724394> duk_debugger.c:1013 (duk__debug_handle_list_break): debug command listbreak
[D] <110205239160360> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110205290190891> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
[D] <110205291570515> duk_debugger.c:1659 (duk_debug_process_messages): paused, process debug message, blocking if necessary
```

It's not terribly useful but it shows what commands Duktape has successfully read.

**Comment by svaarala** [comment]
I think your problem might be here:

```
[...]
<-- 1 bytes  01
<-- 1 bytes  98
<-- 1 bytes  11
<-- 4 bytes  10 00 00 00   <=== PROBLEM
<-- 17 bytes  07 6d 61 69 6e 2e 6a 73 10 00 00 00 21 00 01 93 00
[...]
```

Because the debug protocol is network (big) endian, that string length is 0x10000000, not 0x00000010, and Duktape will be reading for a 256 megabyte string.

**Comment by svaarala** [comment]
Btw, when debugging read/write callbacks, it's useful to log how much Duktape requested and how much was provided -- here you'd probably have seen that Duktape requested for 256 megabytes in the read callback (in one go) which would have been unusual :-)

**Comment by fatcerberus** [comment]
https://github.com/fatcerberus/minisphere/blob/master/src/debugger.c#L65-L106

Note that the peek callback simply calls peek_socket(), which returns the number of bytes in the socket's receive buffer (socket reads are done in the background and buffered).

**Comment by svaarala** [comment]
Actually looking at the bytes, it almost seems the 0x10 might be an extra byte - if you remove that, the read calls indicate a string of length 0x00000007 and the rest of the message is fine:

```
01 98 11 10 00 00 00 07 6d 61 69 6e 2e 6a 73 10 00 00 00 21 00 01 93 00
      ============== problem

# Remove the 0x11 and we have

01 | 98 | 10 00 00 00 07 6d 61 69 6e 2e 6a 73 | 10 00 00 00 21 | 00 | 01 | 93 | 00 |
REQ  0x18 "main.js"                             33               EOM  REQ  0x13 EOM
```

**Comment by svaarala** [comment]
Based on this I'd guess that `_tcp.Client.SendDValue(relativePath);` will send an incorrectly formatted string dvalue, probably sending the length field as *dvalue uint32* (11 10 00 00 00 07 ...) inside the string dvalue, rather than sending the length as a plain 4-byte field (11 00 00 00 07 ...).

**Comment by fatcerberus** [comment]
Oh crap, you're right:
https://github.com/Radnen/spherestudio/blob/edd1e98074e1fb718edf2b5ae6eb3bcb2ce20a98/DuktapeDebugPlugin/DValue.cs#L125-L132

Wow, how did I screw that one up?

**Comment by svaarala** [comment]
Binary stuff is hard and tedious to work with :(

I dislike binary protocols quite a bit but for the debugger direct support for a JSON protocol was not an option for low memory clients. That's why there's a JSON proxy BTW, and I'd rather people integrate with that because it's much easier to work with.

One interesting option would be to include a transport example with Duktape which would parse binary debug messages from Duktape, encode them into the JSON mapping, and call out to a user callback which would get a full JSON debug message. Similarly it would parse incoming JSON mapped debug messages and write them out to Duktape in binary form. Because it would be optional it'd leave the low memory targets alone, and it would allow most people to work directly with something text based. (It'd have more memory churn than optimal but this doesn't matter for many targets.)

**Comment by svaarala** [comment]
Another useful generic transport example would be something that mapped debug messages into a stream of already parsed dvalues, and accepted inbound dvalues. The transport would do automatic buffering needed to parse those dvalues.

And yet another would work with full debug messages mapped into a C array of dvalues, so that user code could concentrate on working with the debug message contents. Surprisingly many people want to embed the protocol decoder on the target (which I find odd).

**Comment by fatcerberus** [comment]
Sorry to send you on a wild goose chase, this is quite embarassing for me because the DValue formats are the one part of the debugger documentation that I really made sure to study closely.

As for the JSON protocol, I initially wanted to use it (or something like it), but TCP being a dumb streaming protocol makes it very hard to write a proxy, and my preference is for a simple conversation of client-target with no middleman (the Node-based JSON proxy is a hefty dependency, especially since one of minisphere's design goals is compactness).

That said, I don't do any decoding on the C side, as you can see by my callbacks.  It was easier to write the DValue decoder in C# than C.

**Comment by svaarala** [comment]
Added #251.

**Comment by svaarala** [comment]
No worries, I'm glad the issue was found :)

The issues that crop up also reflect on how easy various things are to work with. The current debug binary protocol isn't easy to work with as small issues like these are usual when integrating with it, so even wild goose chases are useful input in that respect.

Not sure what to do about that while working well with low memory targets. One candidate is to keep a binary protocol but make it more regular (and less compact), including generic length framing. This would be worse for low memory targets which also had a slow serial link - but that's probably a reasonable tradeoff still; other clients with a slow link can just employ compression and take the memory hit.

**Comment by fatcerberus** [comment]
Difficult to work with or not, the Duktape protocol is exactly the type of thing I have the most fun working with, stupid issues and all. :)

**Comment by fatcerberus** [comment]
By the way, what is the limit for number of breakpoints?  I noticed Duktape had an error condition for when too many are set, but no mention of what the limit specifically is.

**Comment by svaarala** [comment]
It's just an arbitrary define here:

- https://github.com/svaarala/duktape/blob/master/src/duk_heap.h#L261

Breakpoints are implemented as a simple array of a fixed size which simplifies things. They're always processed only up to the last actually used one, so making that define much larger wouldn't slow down the debugger when the extra breakpoints were not in use. For this too, there's no DUK_USE_xxx flag now.
