### ISSUE TITLE
use eval_string("print"), got crash

### ISSUE THREAD

**Issue by hymn4u** [svaarala/duktape#2481]
I'm quite new to duktape. I just use the sample code:
duk_context *ctx = duk_create_heap_default();
    if (ctx) {
        if (duk_peval_string(ctx, "print('Hello world!');") != 0) {
            printf("eval failed: %s\n", duk_safe_to_string(ctx, -1));
        } else {
            printf("result is: %s\n", duk_get_string(ctx, -1));
        }
        duk_pop(ctx);
}

got message:
eval failed: ReferenceError: identifier 'print' undefined

javascript has print function already, right? Or, eval_string must accept an native function?

**Comment by hymn4u** [comment]
if I define a native func:
duk_ret_t nativePrint(duk_context* ctx)
{
    duk_push_string(ctx, " ");
    duk_insert(ctx, 0);
    duk_join(ctx, duk_get_top(ctx) - 1);
    printf("nativePrint: %s\n", duk_safe_to_string(ctx, -1));
    return 0;
}

and register that func:
duk_push_c_function(ctx, nativePrint, DUK_VARARGS);
duk_put_global_string(ctx, "print");
duk_eval_string(ctx, "print('Hello world!!!');");

This time everything works fine. So i just wanna know that, if eval support origin javascript func print, this native print works like hook? 
Any help is appreciate, thanks~~

**Comment by svaarala** [comment]
print() and console.log() are not defined by default in the Duktape runtime. You can implement print() yourself or use the bundled extra: https://github.com/svaarala/duktape/tree/master/extras/print-alert

**Comment by hymn4u** [comment]
ok, got it. And i guess some sample code in doc should refresh. Thanks a lot.
