### ISSUE TITLE
Using duk_require_string + duk_require_function only works one

### ISSUE THREAD

**Issue by Lyuu17** [svaarala/duktape#2495]
So for some reason, I can't get both of them working in the same function, is anything wrong with my code?

c++ code
![image](https://user-images.githubusercontent.com/14199521/182005637-a9d4194b-b32a-49e6-ae30-8491e0169848.png)

js code
![image](https://user-images.githubusercontent.com/14199521/182005648-4094da21-2881-4e56-a233-b421dffc3c2a.png)

error
![image](https://user-images.githubusercontent.com/14199521/182005689-abaac950-8ff6-455f-b051-5785229654cf.png)

**Comment by svaarala** [comment]
How is addCommand registered as a global?

**Comment by Lyuu17** [comment]
> How is addCommand registered as a global, could you show that call site? In particular what is the "num args" for it?

hell, sorry. I was passing 1 argcount when registering it. I though duktape would throw an error or something if more args were passed to the function or something

**Comment by svaarala** [comment]
Good that it was resolved :+1:
