### ISSUE TITLE
Add an example debug transport with dvalue encoding/decoding

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#251]
Add a debug transport which will parse individual dvalues coming from Duktape and provide them to a user callback in parsed form. Similarly, accept dvalues and write them to Duktape in binary form. Dvalues can be represented with a C struct containing a type tag and a union of values.

- [x] Cleanup example code (FIXMEs, endianness)
- [x] Test dvalue parsing for all dvalue types (and variants), perhaps add them to test.c => tests in test.c, DumpHeap
- [x] Test dvalue sending for all dvalue types (and variants) manually
- [x] Add a reference to debugger.rst and perhaps website

**Comment by fatcerberus** [comment]
Another 1.3.0 milestone... 1.3 is going to be a huge upgrade at this rate. :smile:

**Comment by svaarala** [comment]
I'm not 100% strict about milestone targeting though - I used 1.3.0 for this because I have a few (uncommitted) transport tests which I can probably use to write the first two examples quite quickly.

The JSON transport example won't make it to 1.3.0 probably unless it'd depend on an external library. Or perhaps it could use an entirely separate Duktape instance for JSON parsing and stringifying only.

**Comment by svaarala** [comment]
Here's an example transport with dvalue encoding and decoding (very early draft, missing stuff, hasn't been tested well):

- https://github.com/svaarala/duktape/compare/example-debug-dvalue-parser

With this the main program which would implement a local debugger, would look something like:

- https://github.com/svaarala/duktape/blob/cf0feb743fe45c3d3153a89a7fc4323cd073468e/examples/debug-trans-dvalue/test.c

which should be a little bit easier than dealing with dvalues.

**Comment by fatcerberus** [comment]
Hm, nice, the only thing I don't like is the need to allocate and free dvalues.  Each dvalue sent is 3 lines (create, send, free), which could get ugly.  Since you have separate `make_tag` functions anyway, why couldn't it be simplified to something like this below:

```
duk_trans_dvalue_send_tag(ctx, DUK_DVALUE_REQ);
duk_trans_dvalue_send_tag_int(ctx, DUK_DVALUE_INTEGER, 0x15);  /* StepOver */
duk_trans_dvalue_send_tag(ctx, DUK_DVALUE_EOM);
```

Chances are you're not going to do much else with the allocated dvalues after sending them, besides freeing them, so why not simplify the API?

**Comment by svaarala** [comment]
The dvalues need to be allocated for the receive direction (they may need to be kept until the entire message has been received so they need a copy of the input data) so I used them also for the send direction. I guess the dvalues could point to the temporary buffer and the "release" it when done. Not sure if that'd be easier to follow.

But adding those wrappers for sending dvalues more easily would be easy, I'll add them.

**Comment by svaarala** [comment]
Added a few wrappers: https://github.com/svaarala/duktape/commit/433fae49d2255232fe6a12abee75d5c4f352f7ac

The sending code now looks like:

```
duk_trans_dvalue_send_req(ctx);
duk_trans_dvalue_send_integer(ctx, 0x15);  /* StepOver */
duk_trans_dvalue_send_eom(ctx);
```

**Comment by fatcerberus** [comment]
Ah, very nice.  That's even better naming than mine. :)

**Comment by fatcerberus** [comment]
Hm, maybe send_req() could take a command ID and avoid the extra integer send?

**Comment by svaarala** [comment]
Perhaps add `duk_trans_dvalue_send_req_cmd()` so that it's somewhat visible that it's actually sending two dvalues? It'd be nice if there was a 1:1 mapping for individual dvalues so `duk_trans_dvalue_send_req()` should IMO just send the REQ.

(I'll try to reduce the long prefix of the example later on; `duk_trans_dvalue_xxx` to `duk_dtrans`?)

**Comment by fatcerberus** [comment]
Yeah, `duk_dtrans_xxx` Looks more concise for a public API.  Overlong function names make it seem like an internal API.

I'd be fine with a separate `send_req_cmd`.  I definitely understand the rationale for wanting a 1:1 mapping and I agree with it 100% (you want to have your foundation be as generic and stable as possible), but the public API should also represent everyday use. :)

**Comment by svaarala** [comment]
This is just example code and not part of the public API so it'd be good if it was clear it's not a "normal" API call though.

**Comment by svaarala** [comment]
Fixed endianness handling (dynamic detection for double endianness), improved coverage so that all except a few dvalue encode/decode code paths were tested (some bugs fixed). Renamed functions a bit, made consistency renames for the socket example transport. Added to dist and merged to master.
