### ISSUE TITLE
Is there a way to build this on systems without `npm`?

### ISSUE THREAD

**Issue by cnlohr** [svaarala/duktape#2517]
I am trying to build duktape on a minimal system, but it seems to want `npm` to be able to build.  Is there any way of just building the base set of binaries (not all the tests, etc.) without npm (or an other heavy-weight dependencies)?

**Comment by cnlohr** [comment]
Never mind.  Looks like you are using python in your build system.  RIP.

**Comment by cnlohr** [comment]
(Unless there's some trick to just do a simple build)

**Comment by cnlohr** [comment]
Herp derp.  Just needed to read the getting started page. https://duktape.org/guide.html#gettingstarted.1

**Comment by svaarala** [comment]
Just a few comments:
- In basic usage you'd use a prebuilt source package which contains prepared .c and .h files and requires no tooling to include in your project. This is probably what you ended up with, hopefully :-)
- If you edit Duktape internals and want to rebuild the distributable, Duktape 2.x uses Python2 for tooling and master (Duktape 3.x) uses Node.js tooling for rebuilding the distributable. So tooling will migrate to Node.js.
