### ISSUE TITLE
Reading JS variable within C.

### ISSUE THREAD

**Issue by uwejan** [svaarala/duktape#2518]
Say i already have an JSON object exported and included into duktap.
Used 'duk_peval_string_noresult(ctx, ...long string)' to include my object.
Question would be how to read a global JS variable within C?

Thanks in advance.

**Comment by svaarala** [comment]
If the value is already set to the global object, you can use:
- https://duktape.org/api.html#duk_get_global_string

**Comment by uwejan** [comment]
Bare with me please, still new to duktape and C.
I do not see that returning a result.
Say my json object called `my_obj` 
duk_bool_t duk_get_global_string(duk_context *ctx, "my_obj");

**Comment by uwejan** [comment]
@svaarala This sequance is not working.
```
	ctx = duk_create_heap_default();

	//duk_json_decode(ctx, "my_db");
	//duk_get_string(ctx, 1);

	duk_get_global_string(ctx, "my_obj");
	duk_dup(ctx, 0);

	duk_call_method(ctx, 0);

	printf("JSON  %s\n", duk_to_string(ctx, 0));
	duk_destroy_heap(ctx);
	
```

The globale object is stringified, and is nested as well.
