### ISSUE TITLE
Error.prototype.fileName and Error.prototype.lineNumber unnecessarily invoke ToString() coercion

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#254]
The `ToString()` coercion is unnecessary and causes an infinite loop when one replaces `Error.prototype.toString()` with a custom function which access e.g. `.lineNumber` of an error.

You can work around this by replacing the `.fileName` and `.lineNumber` accessors too, but the better fix would be to avoid the recursion.

**Comment by svaarala** [comment]
Example:

```js
Error.prototype.toString = function () {
    print('toString: ' + this.message);
    return 'Error at line ' + this.lineNumber;  // Here 'this.lineNumber' invokes toString() again
};
try {
    aiee;
} catch (e) {
    print(e);
}
```

Leads to:
```
toString: identifier 'aiee' undefined
toString: identifier 'aiee' undefined
toString: identifier 'aiee' undefined
toString: identifier 'aiee' undefined
toString: identifier 'aiee' undefined
[...]
toString: C call stack depth limit
toString: C call stack depth limit
toString: C call stack depth limit
[...]
```

which is quite unintuitive.

**Comment by fatcerberus** [comment]
Wait, so accessing `err.lineNumber` calls `err.toString()`?  That IS unintuitive.

**Comment by svaarala** [comment]
Yes, it's not intentional but a side effect of the shared helper. To be fixed, of course. :)

**Comment by svaarala** [comment]
Ok, this is now fixed and in master.
