### ISSUE TITLE
JSON.stringify() fast path cleanups

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#255]
- [x] Add a DUK_OPT_JSON_STRINGIFY_FASTPATH since genconfig is still a draft
- [x] Add DUK_OPT_JSON_STRINGIFY_FASTPATH to matrix test for coverage
- [x] Check fast path behavior for Proxy object, may need to fallback, tracked in #327

Remaining cleanups after 1.3 release are in #325.

**Comment by svaarala** [comment]
JSON fast path Proxy bug is tracked by #327.

**Comment by fatcerberus** [comment]
I'm debating whether I should enable the fast path for minisphere, as JSON will be used for serializing game save data.  Besides the now-fixed Proxy issue, are there any other caveats I should be aware of?

**Comment by svaarala** [comment]
It should be transparent (that's the intent anyway). The fast path bails out and uses the normal path if some side effect prevents the fast path (getter, toJSON() method, Proxy object). If many objects do that there's little benefit to the fast path.

Anyway, unless you're saving a lot of data, I don't think you'll see a major overall difference at your application level?

**Comment by fatcerberus** [comment]
I'm making an RPG, so there could be a few KB of save data at least.  Probably you're right and it won't make a difference though.  I was mainly curious if it would be completely transparent or not.

**Comment by fatcerberus** [comment]
Does JX encoding benefit as well?  If so enabling this would benefit debugging. :)

**Comment by svaarala** [comment]
The fast path is quite narrow now - it doesn't support indentation or JX/JC formats yet. It's mostly there to start experimenting on how to make the serialization fast and it's easiest to start with a narrow and optional fast path. But adding support for JX and indentation is not hard as such, it just requires careful test cases etc.
