### ISSUE TITLE
Warnings in latest master

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#256]
...or at least, I assume it's the latest master (I downloaded `duktape-master.tar.xz` from the snapshots folder).  Anyway, more conversion warnings when compiling in MSVC 2015 x64:

```
duk_api_stack.c(2433): warning C4267: '=': conversion from 'size_t' to 'duk_uint_t', possible loss of data (compiling source file ..\src\duktape.c)
duk_bi_buffer.c(175): warning C4267: '=': conversion from 'size_t' to 'duk_uint_t', possible loss of data (compiling source file ..\src\duktape.c)
duk_bi_buffer.c(1389): warning C4267: '=': conversion from 'size_t' to 'duk_uint_t', possible loss of data (compiling source file ..\src\duktape.c)
duk_hbufferobject_misc.c(10): warning C4267: '=': conversion from 'size_t' to 'duk_uint_t', possible loss of data (compiling source file ..\src\duktape.c)
```

**Comment by svaarala** [comment]
Thanks, I'll fix these shortly. For some reason I don't get these in my MSVC setup, but it's an older compiler.

**Comment by svaarala** [comment]
Could you check if you get more with DUK_OPT_ASSERTIONS?

**Comment by svaarala** [comment]
None of these are an actual issue BTW, buffer and string sizes are controlled to be less than 0x80000000 so they'll always fit into a duk_uint_t even though they sometimes have an apparent duk_size_t size.

**Comment by fatcerberus** [comment]
Yeah, I've seen enough of these now to know they're not an issue.  They may freak out others, though, so best to quash them.

I'm using /W3, for what it's worth.  I think older MSVC versions defaulted to /W1, so that's probably why you don't see them.  It's an easy thing to overlook because from what I understand most 64-bit platforms other than windows have 64-bit ints whereas both `int` and `long` are 32-bit on Windows.  Whoever at Microsoft had that bright idea needs to be drug out into the street and shot. :)

**Comment by svaarala** [comment]
Sometimes they may be a problem if e.g. a `duk_size_t` is cast to `duk_uint_t` and the `duk_size_t` is not known to fit. At least one or two warnings you've reported have been real issues (though very difficult to trigger in practice, requiring allocations over 2G). Anyway, best to report, check, and fix.

**Comment by svaarala** [comment]
Now fixed, also tested DUK_OPT_ASSERTIONS with /W3 and should be clean.
