### ISSUE TITLE
Allow removing breakpoint by location

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#267]
Currently, AddBreak takes a filename and line number and sets a breakpoint at that location; however, removing breakpoints is less straightforward: You must know the index assigned to it by Duktape and pass that index to DelBreak.  In some cases this is not feasible, for example in a plugin-based client, the script-editing component may be completely self-contained and know nothing of the debugger itself.  When a breakpoint is cleared during execution, the only thing known may be the filename and line number.

This can be worked around by tracking the assigned indices for each filename/line number pair in the client and mapping between the two, but in some scenarios this might not be feasible: A dictionary (seemingly the best candidate for the lookup operation) typically only takes one key, and using a hash as a key is non-obvious since there are two types involved (a string and an int).  And ignoring that, implementing a dictionary may itself be non-trivial depending on the programming language (C for example is not particularly conducive to this kind of thing).

Since Duktape must already have a mechanism for mapping file/line pairs to breakpoints (to be able to trigger them), implementing a targeted DelBreak wouldn't be too difficult, I'd imagine.

**Comment by svaarala** [comment]
Could the client just list the breakpoints and match the index (or indices, there may be multiple) and issue DelBreaks?

**Comment by fatcerberus** [comment]
in C#, which my client is written in, I could probably use LINQ for index matching, so this isn't a huge issue there.  In other languages like C the reverse lookup may not be trivial, hence the feature request.

Does Duktape have a command to list breakpoints?  I must have overlooked it...

**Comment by svaarala** [comment]
There's a ListBreak command yes: https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#listbreak-request-0x17

For now the design assumption has been that the debug protocol would be rather bare bones and let the debug client implement user operations in terms of smaller primitive operations. For example, ListBreak + DelBreak allows you to delete all breakpoints in a certain file, a line range, etc, without Duktape needing to support those operations explicitly.

**Comment by fatcerberus** [comment]
Ah, that's useful then.  And here I thought the best solution was going to be to clear all the breakpoints and resend them all.  This is much better, I can just list them out and then run a LINQ query against the list to get an index.

There are a few potential gotchas I can see here though:
* Does ListBreak list them in index order?
* If you have breakpoints indexed 0, 1, 2 and you delete #1, are the remaining ones shifted?  If not this may be an issue since ListBreak doesn't tell you the indices.

**Comment by svaarala** [comment]
ListBreak lists them in index order yes. If you want to delete multiple indices, you should delete them starting from the highest one to avoid reordering issues (the indices are indeed shifted).

Btw, I don't disagree with an explicit command for this being useful. I'm just trying to ensure there's no unintentional scope creep: if this command is added, there are also many other useful commands that could be added for consistency, like deleting all breakpoints in a certain file, a line range, etc, and I wouldn't want to add all of them :) And if the UI needs ListBreak+DelBreak for some operations, why not all?

**Comment by svaarala** [comment]
This is how the Node.js debugger handles deletion of either all or just matching breakpoint(s): https://github.com/svaarala/duktape/blob/master/debugger/duk_debug.js#L1463-L1476

**Comment by fatcerberus** [comment]
I think I agree with just mandating the use of ListBreak+DelBreak for most deletions, however one command I think *should* be added is one that clears ALL breakpoints (call it ClearBreak).  This seems like a common enough use case--for example, maybe the client doesn't want to track indices and simply clears everything and resends as a shortcut--that having a single command to do it would be ideal, making what is currently an O(n) operation into O(1).

**Comment by svaarala** [comment]
If the client supports breakpoints, it probably also visualizes them somehow - so why would it be difficult for the client to handle breakpoint indices? Also note that while there are N breakpoint deletion commands, the client doesn't need to wait for responses so it's just N queued commands (where N is at most 16), so there's no practical issue I can think of. (I do understand it's easier to send a single command rather than multiple.)

Adding a command to clear breakpoints would of course be trivial, but I'd still myself prefer keeping the debug target as dumb as possible, and avoiding redundant commands where possible. This probably comes from trying to work with targets having very little memory, which is a constant challenge of "staying vigilant" against redundancy. It's a balancing act of course and not always clear cut (for example the C API provides a lot of redundancy for convenience).

**Comment by svaarala** [comment]
This discussion brought back some earlier design alternatives which might have been better than the current command set:

One possible design for breakpoint handling (and other parts of the debugger too) would be to expose the debugger state to the debug client "as is", and the debug client would then directly operate with the state. For example, Duktape could provide the number of breakpoint slots available in GetBasicInfo and the debug client could then operate on the slots directly with a *single* SetBreak command which could effectively both set and clear breakpoints.

Another barebones solution simpler than the current one would be to have a single SetBreakpoints command which provided the full list of desired breakpoints which would replace whatever was previously active. The debug client would manage that list and resend the whole list whenever something changed. Sending an empty list would be equivalent to clearing all breakpoints.

**Comment by fatcerberus** [comment]
Yes, I understand the N breakpoint deletions can be pipelined--the issue is that the Duktape target is necessarily serial in command processing, so if there are, say, 100 breakpoints (default limit is 16, but this can be modified), a Resume command won't be responded to until the prior 100 commands have been received and processed first, which depending on the speed of the link may take a while.

As for visualizing, I can at least say that, for my own debugger, the design is modular and the IDE maintains the list of breakpoints independent from the Duktape specifics, so that breakpoints are remembered across sessions.  As a result tracking indices is difficult since the script editor component (which serves as the "visualizer") has no knowledge of the specific debugger implementation which is in a separate plugin.  So with this setup at least, being able to change breakpoints with a single command without sacrificing responsiveness would be ideal.

**Comment by fatcerberus** [comment]
As a response to your other idea, operating on the slots directly: I rather like Duktape's system of only looking at breakpoint slots which are set (to improve performance), whereas allowing slots to be filled directly would require Duktape to walk the entire list on every interrupt, since a braindead client could in theory decide to set a single breakpoint in the last slot and leave the rest empty.

With the current system you can set a high breakpoint limit of, say, 1000 without any performance degradation unless that many breakpoints are actually set.  If Duktape instead has to walk the entire list on every interrupt, this becomes unfeasible.

**Comment by fatcerberus** [comment]
Having thought about this a bit, I think I understand why the Duktape debug client is set up the way it is--it's set up for a debug workflow similar to most command line debuggers.  In that environment breakpoints are set and unset one at a time, and a running target is a prerequisite to do anything.  The client is the frontend.  So for this paradigm the Duktape protocol makes a lot of sense. :)

**Comment by svaarala** [comment]
There's no clear change proposed in the issue so I'll close this now. If this becomes relevant later on, we can reopen or open a new issue with a concrete change proposal.
