### ISSUE TITLE
Support AmigaOS 4 PowerPC

### ISSUE THREAD

**Issue by chris-y** [svaarala/duktape#269]
Please add support for AmigaOS 4 - PowerPC.

I've managed to support it by modifying duktape.h, but cannot fathom how to do this in the development repo.  A diff is below, hopefully this is enough for you to integrate into development:

--- a/javascript/duktape/duktape.h
+++ b/javascript/duktape/duktape.h
@@ -281,6 +281,11 @@ static __inline__ unsigned long long duk_rdtsc(void) {
 #define DUK_F_M68K
 #endif
 
+/* PowerPC */
+#if defined(__powerpc) || defined(__powerpc__) || defined(__PPC__)
+#define DUK_F_PPC
+#endif
+
 /* Linux */
 #if defined(__linux) || defined(__linux__) || defined(linux)
 #define DUK_F_LINUX
@@ -576,8 +581,19 @@ static __inline__ unsigned long long duk_rdtsc(void) {
 #define DUK_USE_DATE_FMT_STRFTIME
 #include <limits.h>
 #include <time.h>
+#elif defined(DUK_F_PPC)
+/* AmigaOS on PowerPC */
+#define DUK_USE_DATE_NOW_GETTIMEOFDAY
+#define DUK_USE_DATE_TZO_GMTIME_R
+#define DUK_USE_DATE_PRS_STRPTIME
+#define DUK_USE_DATE_FMT_STRFTIME
+#include <limits.h>
+#include <time.h>
+#ifndef UINTPTR_MAX
+#define UINTPTR_MAX UINT_MAX
+#endif
 #else
-#error AmigaOS but not M68K, not supported now
+#error AmigaOS but not M68K/PPC, not supported now
 #endif
 #elif defined(DUK_F_WINDOWS)
 /* Windows 32-bit and 64-bit are currently the same. */
@@ -1502,7 +1518,7 @@ typedef double duk_double_t;
 
 /* AmigaOS on M68k */
 #if !defined(DUK_F_BYTEORDER) && defined(DUK_F_AMIGAOS)
-#if defined(DUK_F_M68K)
+#if defined(DUK_F_M68K) || defined(DUK_F_PPC)
 #define DUK_F_BYTEORDER 3
 #endif
 #endif
@@ -1603,6 +1619,11 @@ typedef double duk_double_t;
 #define DUK_USE_PACKED_TVAL_POSSIBLE
 #endif
 
+/* PPC: packed always possible */
+#if !defined(DUK_USE_PACKED_TVAL_POSSIBLE) && defined(DUK_F_PPC)
+#define DUK_USE_PACKED_TVAL_POSSIBLE
+#endif
+
 /* With Emscripten, force unpacked duk_tval just to be safe, as it seems to
  * break at least on Firefox (probably IEEE double arithmetic is not 100%
  * supported, especially for NaNs).
@@ -2255,6 +2276,8 @@ typedef FILE duk_file;
 #define DUK_USE_ARCH_STRING "sh"
 #elif defined(DUK_F_M68K)
 #define DUK_USE_ARCH_STRING "m68k"
+#elif defined(DUK_F_PPC)
+#define DUK_USE_ARCH_STRING "ppc"
 #elif defined(DUK_F_FLASHPLAYER)
 #define DUK_USE_ARCH_STRING "flashplayer"
 #elif defined(DUK_F_EMSCRIPTEN)

**Comment by chris-y** [comment]
Sorry, the pasted text got slightly munged, you can see a better version here:
http://git.netsurf-browser.org/netsurf.git/patch/?id=8d4c4b91795a1788ddb8dea1e21bdbd2ada4e588

**Comment by svaarala** [comment]
Ok, will do. I have a soft spot for Amiga because it was the greatest machine of its time :-)

**Comment by svaarala** [comment]
The configuration headers are in a bit of a flux because Duktape is moving to an external `duk_config.h` header, and the intent is for only mainline platforms to be supported through "autodetection". Instead, there's a genconfig utility that one would use to create a custom duk_config.h for a specific platform, and configuration rules like alignments, duk_tval packing, etc would be handled there.

This change is mostly in master already, but for the 1.3 release it's still in the background (with everything still outwardly the same as before), so I'll add the AmigaOS/PPC stuff into the autodetect header for now.

**Comment by svaarala** [comment]
@chris-y Could you test if I got this right: https://github.com/svaarala/duktape/compare/add-amigaos-powerpc-support?expand=1

**Comment by svaarala** [comment]
Just as an example of how this will work once the transition is complete (perhaps by Duktape 1.4), on AmigaOS PPC you'd create a duk_config.h something like:

```
$ python config/genconfig.py \
    --metadata config \
    --output duk_config.h \
    --platform amigaos \
    --architecture powerpc \
    --compiler generic \
    --option-file disable_es6.yaml \
    -DDUK_USE_JSON_STRINGIFY_FASTPATH \
    barebones-header
```

So, you select a platform-architecture-compiler triple (which are essentially C header snippets), define any Duktape config overrides from the command line or config input files, and genconfig writes out a specialized header for your target. You can then edit it further manually or through scripting.

**Comment by chris-y** [comment]
That looks right, as far as I can tell, thanks!

**Comment by svaarala** [comment]
Can you confirm that the result compiles if you dist from the branch? (If you want I can provide a distributable tar package for.)

**Comment by chris-y** [comment]
Can you provide a tar please?  Make dist isn't working here, looks like it needs a Java compiler which I don't have installed.

**Comment by svaarala** [comment]
Here's a dist tar: http://duktape.org/snapshots/duktape-1.2.99-20150809205300-v1.2.0-300-geb1c125.tar.xz

**Comment by chris-y** [comment]
Working perfectly!

**Comment by svaarala** [comment]
Good to hear, now pushed to master :)
