### ISSUE TITLE
Ability to load bytecode

### ISSUE THREAD

**Issue by malord** [svaarala/duktape#27]
There's a mention of this in the documentation in the section on differences vs. Lua, but it doesn't say whether this capability is planned?

**Comment by toastfr35** [comment]
The ability to compile and then save the bytecode for later execution would be great for my application.
The idea is to compile once and then not have to recompile every time the script is started. In my case I have an application started many times that contains a JS script and duktape. The script can be large but does not execute for long and I think that I might be spending more time compiling it every time than actually running it. It would be nice to be able to store it as bytecode as in Lua.

**Comment by svaarala** [comment]
Now tracked by #208, closing this one.
