### ISSUE TITLE
Add duk_safe_call() variant with a void pointer userdata

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#277]
Add a duk_safe_call() variant with a void pointer userdata, say `duk_safe_call_udata()`. Such an API call would allow user code to avoid passing C values through the value stack (which is done even internally in a few places). Instead, the caller could just:

```
typedef struct {
    int a;
    int b;
} my_args;

duk_ret_t my_safe_call(duk_context *ctx, void *udata) {
    my_args *args = (my_args *) udata;
    printf("a=%d, b=%d\n", args->a, args->b);
}

/* ... */
struct my_args args;
args.a = 123;
args.b = 234;
rc = duk_safe_call_udata(ctx, (void *) &args);
/* ... */
```

Packing C values to a struct is also not the most convenient thing but it scales to arbitrary numbers and types of arguments.

Unfortunately this cannot be easily implemented so that the previous `duk_safe_call()` would just be a dummy wrapper for the udata variant - the target C function prototype is different (typedef `duk_safe_call_function`).

(This has been suggested before, but I couldn't find the issue, so opening this new one.)

If implemented, also rework `duk_pnew()` and other internal call sites to take advantage of the new call.

**Comment by svaarala** [comment]
Some internal code actually uses the C structure approach in the description: call site stuffs values into a temporary struct, and pushes a plain pointer to the value stack pointing to the struct. duk_safe_call() target then gets that pointer from the value stack and casts it to a struct pointer. This pattern in particular would be much nicer with a userdata.

**Comment by fatcerberus** [comment]
I agree with this change.  Value stack semantics make sense when you're calling back into JS, but for pure C the userdata approach seems cleaner.

**Comment by kphillisjr** [comment]
I agree that avoiding the passing of user pointers through the stack is the best approach. I also believe it should be possible to store user data pointers outside the stack and have them referenced in by the stack unsigned integers. 

# Outline of Changes
I will not cover engine level changes to implement this, but the user level code is fairly simple.

## New Data Types
Only user-side data types are required to implement this.
 ```C
typedef duk_ret_t (*duk_safe_c_function)(duk_context *ctx, void *udata);
struct duk_safe_function_list_entry {
	const char *key;
	duk_safe_c_function value;
	duk_int_t nargs;
};
```

## New Functions:

There is a few new functions required for this change.

#### duk_push_safe_c_function

This works a lot like duk_push_c_function, but the function expects a user pointer when being called.

 ```C
duk_idx_t duk_push_c_function(duk_context *ctx,
   duk_safe_c_function func, duk_idx_t nargs, void *udata);
```

**Example usage:**

 ```C
typedef struct {
    int a;
    int b;
} my_args;

duk_ret_t my_safe_call(duk_context *ctx, void *udata) {
    my_args *args = (my_args *) udata;
    printf("a=%d, b=%d\n", args->a, args->b);
}

/* ... */
struct my_args args;
args.a = 123;
args.b = 234;
duk_push_global_object(ctx);
duk_push_safe_c_function(ctx, my_safe_call, 0, (void *) &args);
duk_put_prop_string(ctx, -2 /*idx:global*/, "mySafeCall");
duk_pop(ctx);  /* pop global */
/* ... */
```
## duk_push_safe_c_lightfunc
works like duk_push_c_lightfunc, but has a user data pointer attached. This could be useful for object construction.

 ```C
duk_idx_t duk_push_safe_c_lightfunc(
   duk_context *ctx, duk_c_function func,  duk_idx_t nargs,
   duk_idx_t length, duk_int_t magic, void* userData);
```

**Example usage:**
I do not currently have an example of this, but it would safe to say the usage would look similar to this...
```C
duk_idx_t func_idx;

func_idx = duk_push_c_lightfunc(ctx, mySafeC_Function,
   2 /*nargs*/, 2 /*length*/, 0 /*magic*/, (void*)myArgs /*UserData*/);
```
### duk_put_safe_function_list
This works a lot like duk_put_function_list, but is geared for User Pointers.

 ```C
void duk_put_safe_function_list(duk_context *ctx, duk_idx_t obj_index,
   const duk_safe_function_list_entry *funcs, void *userData);
```
**Example usage:**

 ```C
const duk_safe_function_list_entry my_module_funcs[] = {
    { "tweak", do_tweak, 0 /* no args */ },
    { "adjust", do_adjust, 3 /* 3 args */ },
    { "frobnicate", do_frobnicate, DUK_VARAGS /* variable args */ },
    { NULL, NULL, 0 }
};

/* .. */
struct my_args args;
args.a = 123;
args.b = 234;
duk_push_global_object(ctx);
duk_push_object(ctx);  /* -> [ ... global obj ] */
duk_put_safe_function_list(ctx, -1, my_module_funcs, (void*) &args);
duk_put_prop_string(ctx, -2, "MyModule");  /* -> [ ... global ] */
duk_pop(ctx);
/* .. */
```

**Comment by fatcerberus** [comment]
I'm not sure I understand the use case here.  `duk_push_c_function` etc. are to expose native functions to script, what use would the userdata pointer be in that case?

**Comment by kphillisjr** [comment]
The point of these functions are to prevent users from attempting to access the "Internal properties" of the object [Duktape Programmer's Guide: Internal Properties]( http://duktape.org/guide.html#internalproperties ). Also, it is possible that a user may want to expose a set of functions in a C++ object to the script, and does not necessarily want duktape to take care of the garbage collection of the pointer.

**Comment by fatcerberus** [comment]
I think you misunderstand the purpose of the `duk_safe_call()` API.  It's not for sandboxing, it's to create a safe environment in which to execute C code that may call Duktape APIs, so that if an error is thrown by Duktape due to bad input, it doesn't propagate back into JS code.  It's equivalent to a `try`/`catch` in JS.

**Comment by svaarala** [comment]
@kphillisjr The planned change to prevent Ecmascript code from accessing internal properties is described in #44.

**Comment by svaarala** [comment]
This API change probably won't make 1.3.0 so I'm assigning it to 1.4.0 for now. Perhaps moving it to 2.0 as an incompatible change (add one argument to duk_safe_call() which is easy to spot and fix when upgrading) might be the best approach.
