### ISSUE TITLE
Add ability to read variables from call stack

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#280]
In native debuggers like MSVC, you can select a call stack entry and view variable values from that scope.  There doesn't appear to be anything like this in Duktape, and an Eval request isn't a solution since the locals of an activation further down the stack aren't in scope.

It would be great if the Duktape debugger had this ability too.

**Comment by svaarala** [comment]
Also mentioned in future work: https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#possible-new-commands-or-command-improvements

**Comment by fatcerberus** [comment]
Wow, it's even the first item on the list!  No idea how I missed that...

**Comment by svaarala** [comment]
It's fine to have overlap though. I've just tried to keep long laundry lists of known future work in the relevant docs because having all that as separate Github issues would be unwieldy. (On the other hand, having a tracking Github issue for 10-20 individual improvements would probably be OK, and Github has that convenient checkbox feature as well.)

**Comment by fatcerberus** [comment]
As far as concrete implementation, it would be enough to walk the callstack and do a direct eval in the context of the correct activation, yes?  After the 1.3 release I want to look into implementing this.

**Comment by fatcerberus** [comment]
Hm, it occurs to me that modifying the relevant debug commands to allow this will break protocol compatibility as it requires an additional argument (the callstack index).

**Comment by svaarala** [comment]
Eval wouldn't be correct but there's an internal call to "GETVAR" starting from a certain activation.

Adding a new argument would just cause an older version to ignore the argument and do whatever it did before: https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#extending-the-protocol-and-version-compatibility

This allows some graceful extensions, and works well in some cases (and not so well in others).

**Comment by fatcerberus** [comment]
I imagine doing a direct eval under a previous activation might cause some havoc if it has any side effects, given that objects in JS are passed by reference.  I wouldn't blame you at all if there's no built-in primitive to support such shenanigans. :)

**Comment by svaarala** [comment]
Well it's possible to do an Eval sure in a different callstack entry (in most cases) - but it's different from the topic of this issue (reading variable values).

The only problem with doing an arbitrary Eval might be that some functions are optimized with the assumption that there won't be a direct eval call in that function (the compiler can figure this out during compilation). Some assumptions might then be violated when Eval runs, not sure what would break in practice.

**Comment by fatcerberus** [comment]
Yeah, I was just musing mainly because I use Eval to get JX-encoded values of objects in my debugger's variable viewer.  Sorry for drifting off-topic. :)

**Comment by svaarala** [comment]
I just meant there are actually two separate debugger improvements: one to add a callstack level to variable reads and another for Eval. Both are possible and slightly different (Eval can establish new variables, for example :-).

**Comment by fatcerberus** [comment]
@svaarala
I'm investigating how to implement callstack level for GetLocals.  Keep an eye out for pull requests. :)

**Comment by fatcerberus** [comment]
Regarding this:

> The only problem with doing an arbitrary Eval might be that some functions are optimized with the assumption that there won't be a direct eval call in that function (the compiler can figure this out during compilation). Some assumptions might then be violated when Eval runs, not sure what would break in practice.

It occurred to me that this applies even in master, when paused in a function which was compiled with such an assumption.  So I don't see that as a blocker for implementing callstack level for Eval. :)

**Comment by svaarala** [comment]
@fatcerberus That's true. There shouldn't be too many issues like that in the current master because debugger support prevents ditching _Varmap for example.

**Comment by fatcerberus** [comment]
I'll close this now that #412 has been merged.
