### ISSUE TITLE
Supporting Carthage

### ISSUE THREAD

**Issue by jasonShen89** [svaarala/duktape#285]
will duktape support Carthage?

**Comment by kphillisjr** [comment]
No idea, but I think it would be best to let others know what Carthage is. I believe your talking about [Carthage - A simple, decentralized dependency manager for Cocoa](https://github.com/Carthage)

**Comment by svaarala** [comment]
@jasonShen89 As a general rule Duktape doesn't provide a standard build script / makefile / project file etc. Instead, you incorporate Duktape into your project by:

- Adding `duktape.c` to the list of files to compile (or compiling `duktape.c` as a library)
- Ensuring `duktape.h` and `duk_config.h` are in the include path

Could you be more specific what you mean by "support Carthage"?

**Comment by svaarala** [comment]
@jasonShen89 Ping? :)
