### ISSUE TITLE
What exactly is needed to build Duktape?

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#291]
I tried building a Duktape distribution with Cygwin, but got the following back:

```
fatce@DESKTOP-AR6TT0B /d/src/duktape
$ make dist-src
which: no nodejs in (/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/CMake/bin:/usr/lib/lapack)
which: no node in (/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/CMake/bin:/usr/lib/lapack)
which: no java in (/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/CMake/bin:/usr/lib/lapack)
which: no valgrind in (/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/CMake/bin:/usr/lib/lapack)
cd closure-compiler; ant
/bin/sh: ant: command not found
Makefile:800: recipe for target 'closure-compiler/build/compiler.jar' failed
make: *** [closure-compiler/build/compiler.jar] Error 127
```

I looked through the Cygwin packages list but couldn't find anything called "ant".  So I just want to know ahead of time exactly what I'd need to ensure a successful make.

**Comment by svaarala** [comment]
The README lists dependencies on Linux (well, some variants of it):

```
# Install required packages (exact packages depend on distribution)
$ sudo apt-get install nodejs nodejs-legacy npm perl ant openjdk-7-jdk \
      libreadline6-dev libncurses-dev python-rdflib python-bs4 python-yaml \
      clang llvm
```

I guess that list should be similar for Windows. You might need to install Ant outside of Cygwin, and maybe same for Java.

**Comment by fatcerberus** [comment]
I assume valgrind isn't strictly necessary, even though the make seems to call for it?  It's not available for Windows at all.

I see that I need Node.js too.  I thought I already had it installed on this machine, but apparently not.

**Comment by svaarala** [comment]
We're now getting into the discussions I'm trying to avoid and which is why I've been so far only supporting Linux for development (imagine going through this for 5 Linux variants, OSX, BSD, Windows, etc, every time something changed :-).

The README lists dependencies for using the development Makefile. You don't need valgrind or node.js for "make dist". The specific requirements for make dist are unfortunately not listed explicitly.

**Comment by JoshEngebretson** [comment]
I've had no problem building a dist on OSX and have never tried on Windows.  VirtualBox + Ubuntu probably easier than cygwin hoops on Windows atm.

**Comment by kphillisjr** [comment]
I got build from git working on windows using a combination of CMake, Microsoft Visual Studio 2013 Community Edition ( Desktop version), Python, and PyYAML. The only issue with it is that all of the tests are not in place. See Pull request 278 for more details.

**Comment by fatcerberus** [comment]
@svaarala
Sorry, I'll do some googling to find out what else I need to do to get it working.  If I'm writing code for Duktape, I wanted to try to get a proper build environment going.  My current method is to make the changes in the combined source and then copy them out into the individual files manually, which is obviously error-prone.

Just to play devil's advocate though re: not needing node: you have it listed in the "required packages" in the readme. ;)

**Comment by svaarala** [comment]
Node is needed for using all the Makefile targets (e.g. "make qecmatest") but it's not needed for "make dist". The dependency list is for all targets, so that's why it is listed :)

Anyway, don't get me wrong - it'd be great if the main repo could support a number of platforms. It's just that there's effort involved which is always removed from something else. A few steps to improve the situation would be to pare down "make dist" a bit (it depends on cloc.pl for instance which is obviously not a critical dependency; minification is also not all that critical). Removing dependency on bash altogether and relying purely on Python would also be relatively easy (and useful) step.

**Comment by ReneHollander** [comment]
If you don't already found out about ant, it is a build tool mainly used by java projects. See http://ant.apache.org/ for more informations.

**Comment by fatcerberus** [comment]
Well, after installing Ant and the JDK, twiddling with environment variables for a while and running `dos2unix` on all the source files and shell scripts, I got Duktape `make dist` to work in Cygwin!  Now I can continue development. :smile:

The only thing that wouldn't run was genconfig.py, I got an error back about yaml being missing.  The build was otherwise successful.

**Comment by Legimet** [comment]
I don't think it's normal, but the source files should be fine.

**Comment by fatcerberus** [comment]
I'll close this as I have Duktape building successfully with no errors under Cygwin now.
