### ISSUE TITLE
Improve function .name handling

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#293]
See:
- #292
- https://github.com/svaarala/duktape/issues/292#issuecomment-134254359

**Comment by fatcerberus** [comment]
> an inherited non-writable property prevents property creation

Is this per spec?  Seems kind of dumb that just because the prototype's property is read-only the derived one is too...

**Comment by svaarala** [comment]
Yes, that's standard Ecmascript behavior:

```
> parent={}; Object.defineProperty(parent, 'foo', {writable:false, configurable:false, enumerable: false, value:'parent'})
{}
> child=Object.create(parent);
{}
> child.foo
'parent'
> child.foo = 123;
123
> child.foo
'parent'
```

**Comment by svaarala** [comment]
Function `.name` attributes are now specified by ES6: non-writable, non-enumerable, but configurable. So the portable way of setting a function `.name` is using `Object.defineProperty()` or `duk_def_prop()`.

Closing this as the behavior is ES6 specified and master now adheres to that.
