### ISSUE TITLE
Use a local 'consts' pointer in executor dispatch loop

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#295]
Currently consts base pointer is looked up on-the-fly using `fun`, which is indirect. Based on preliminary testing this change improves performance slightly (around 2%) but also decreases footprint by around 0.5kB (for -O2).

**Comment by svaarala** [comment]
The most significant effect is (not surprisingly) for LDCONST:

```
$ sudo nice -20 python util/time_multi.py --count 10 --sleep 10 --mode all --verbose ./duk.O2.consts tests/perf/test-const-load.js 
Running: 6.810000 6.840000 6.830000 6.870000 6.840000 6.820000 6.980000 6.880000 6.850000 6.940000
min=6.81, max=6.98, avg=6.87, count=10: [6.81, 6.84, 6.83, 6.87, 6.84, 6.82, 6.98, 6.88, 6.85, 6.94]

$ sudo nice -20 python util/time_multi.py --count 10 --sleep 10 --mode all --verbose ./duk.O2.master tests/perf/test-const-load.js 
Running: 7.120000 7.090000 7.330000 7.130000 7.110000 7.130000 7.110000 6.580000 6.560000 6.570000
min=6.56, max=7.33, avg=6.97, count=10: [7.12, 7.09, 7.33, 7.13, 7.11, 7.13, 7.11, 6.58, 6.56, 6.57]
```

Difference in other tests is pretty marginal - but since code footprint decreases without a performance penalty, I'll merge this.

**Comment by fatcerberus** [comment]
It's not often you get a chance to *lower* the footprint. :)

**Comment by svaarala** [comment]
Merged to master.
