### ISSUE TITLE
Breakpoint check incorrect when function call made by side effect

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#303]
When debugging a function call in Ecmascript code, the bytecode executor will automatically do a recheck of active breakpoints when the function call returns. This is needed because all Ecmascript calls share the same effective breakpoint list stored in `heap`. This works correctly for explicit function calls.

However, currently function calls caused by side effects such as a property getter being triggered by a property read are not handled correctly.  For example:

- The executor is executing function F1.
- A side effect in e.g. a property read causes the executor to call F2 (handled with `duk_handle_call()`, i.e. not sharing the executor C stack frame). If F2 is an Ecmascript function, a breakpoint check will be done for F2.
- When F2 returns, the executor is handling DUK_OP_GETPROP for F1 and will loop back without rechecking breakpoints. F1 resumes execution with the effective breakpoint list of F2 -- in practice breakpoints will be missed until a "normal" call happens in F1, an interrupt occurs, or F1 exits.

Example triggering this issue:

```js
var obj = {};
Object.defineProperty(obj, 'prop', {
    get: function () { print('get'); }
});

function test() {
    // Step into test(), then step into the getter.  Set a breakpoint on one
    // of the lines below and Resume.  The breakpoint will be skipped in
    // Duktape 1.2.  The same thing happens if you e.g. StepOut from the
    // getter.

    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
    obj.prop;
}

test();
```

**Comment by svaarala** [comment]
A simple fix would be to force an interrupt by manipulating the interrupt counter when (1) debugger session is active, and (2) we're returning to an Ecmascript activation. Often this will be unnecessary but that's OK.

**Comment by fatcerberus** [comment]
Surprisingly, this one never bit me.  That surprises me given all the issues I've had with hidden function calls ruining my day. ;-)

**Comment by svaarala** [comment]
It's actually quite difficult to trigger in practice, but worth fixing anyway.

**Comment by fatcerberus** [comment]
I think forcing an interrupt should be fine.  Unless literally every single instruction is a property read, it shouldn't be a performance issue in practice.

**Comment by svaarala** [comment]
Note that a breakpoint check is needed for every getter-based property read because a function call does happen. In current master that check is just not made. (Well to be exact if every bytecode executor instance had its own active breakpoint list instead of reusing the one in `duk_heap` there'd be no issue, but that'd be more wasteful.)

I have a tentative fix branch for this here:

- https://github.com/svaarala/duktape/compare/fix-debugger-sideeffect-recheck-gh303

I'm a bit on the fence if this is risky enough (likely to cause some other debugger issues) to postpone to Duktape 1.4.

**Comment by fatcerberus** [comment]
Technically breakpoints are global state (from the client's POV anyway) so yeah, copying it to each executor instance doesn't really make sense.

Curious on what the potential fallout is, though.  I do rely on the debugger now (having a JS debugger is so awesome), so I want to know what might break. :)

**Comment by svaarala** [comment]
However, the list of effective breakpoints for a certain function is logically related to the execution of that function only. That state, too, is in `duk_heap`, so it gets overwritten and reinitialized when calls are made and returned from.

**Comment by svaarala** [comment]
The minimum change is to force a breakpoint recheck every time we return. However, just that change causes the breakpoint check to run for normal calls executed through e.g. DUK_OP_CALL because that opcode will explicitly request for a breakpoint check anyway.

To avoid that double recheck I removed the explicit breakpoint checks from DUK_OP_CALL and DUK_OP_NEW, because we should be able to rely on the `heap->dbg_force_restart` flag for these cases too (as we do for calls triggered by side effects). However, there's some potential here for some unintended consequences here.

**Comment by fatcerberus** [comment]
The cleanest solution, I would think, would be to put the breakpoint check into `duk_handle_call()`, no?

**Comment by svaarala** [comment]
That would be possible but it would then preclude any breakpoint / restart check changes to executor local variables.

I actually have a fix branch for this already.

**Comment by svaarala** [comment]
The other reason for using just a force recheck flag was that there may be multiple native call returns because we are actually just about to return to the bytecode executor, and we don't want to recheck the breakpoints on every one of them. The call handling could look into the activation it's about to return to, but it's cheaper to just unconditionally set a "force recheck" flag; it gets set multiple times but that doesn't matter as it's only cleared by the executor.

**Comment by svaarala** [comment]
@fatcerberus Since you seem to have a pretty good and demanding debugger setup, would you be willing to test this branch a bit in your setup? Specifically, that the fix doesn't break other stuff related to breakpoints, stepping in and out of calls etc (I couldn't fix such issues myself but you have a more extensive setup I think). If so, we could merge it for Duktape 1.3 so it wouldn't hang around unnecessarily.

I force pushed the branch (rebased to master) and here's a snapshot if that helps: http://duktape.org/snapshots/duktape-1.2.99-20150830191847-v1.2.0-439-gd3005f4.tar.xz

**Comment by fatcerberus** [comment]
Sure, I'll test it out in a few hours.

**Comment by svaarala** [comment]
Thanks! There's no particular hurry, except I'm trying to figure out if this should make 1.3 or not :)

**Comment by fatcerberus** [comment]
Tried everything I could think of to break it: Step in, step out, step over, StepInto with a Duktape/C call in the middle (the way minisphere is designed, the fact that this works is awesome), adding and removing breakpoints at runtime... Looks like everything checks out!

**Comment by svaarala** [comment]
You have a good track record of finding bugs (and I mean that in a good way :) so maybe I'll merge this change for 1.3 :-)

**Comment by svaarala** [comment]
Now in master.
