### ISSUE TITLE
Missing 'act' relookup after creating arguments object

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#305]
Caught using refzero finalizer torture: 'act' was not property looked up after creation of an Arguments object. This might be quite difficult to trigger in practice though.

**Comment by svaarala** [comment]
Merged to master. The fix can be verified with the finalizer torture option, but I couldn't come up with an actual test case to trigger it (it might be possible though but not trivial).

**Comment by fatcerberus** [comment]
I don't understand this one, honestly.  Arguments object creation is part of call setup I thought, there should be `act` re-lookup needed?

**Comment by svaarala** [comment]
Every time there's a potential for side effects `thr->callstack` may be resized and reallocated which may change its pointer. So any previous `act` pointers computed based on `thr->callstack` are potentially invalid and must be computed again.

**Comment by fatcerberus** [comment]
Ah, I see.  For a testcase you might try synthesizing a very deep recursion (but not infinite!) with no tail calls to force Duktape to resize the callstack.

**Comment by svaarala** [comment]
But the problem for writing a testcase is how to trigger a finalizer (or any other call) during Arguments object creation: all the objects there are internal to Duktape and have no finalizers. Well, perhaps you could add a finalizer to `Object.prototype` or something weird like that. The torture test causes a concrete error though because it behaves as if every object always had a finalizer, so it catches this.

**Comment by fatcerberus** [comment]
Well, you have to give me points for tenacity anyway, I'm still trying to come up with a way to generate side effects during arguments object creation.  My latest attempt was to replace `Object.prototype` with a Proxy.  Needless to say, that didn't work as it's not writable. :)
