### ISSUE TITLE
Excessive recursion with debugger attached causes segfault

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#307]
The following testcase will cause a segfault with the debugger attached:

```javascript
Duktape.errCreate = function() {};
function EatyCounter() { this.n = 0; }
Duktape.fin(EatyCounter.prototype, function() { print("Stupid pig"); })
n = 1000 * 1000;
function pig(eatiness) {
	if (n-- > 0) {
		eatiness.n++;
		pig(eatiness);
	} else {
		throw new Error("There is nothing. Nothing left at all!");
	}
}
pig(new EatyCounter());
```

@svaarala For bonus points, see if you can guess what the testcase was originally _supposed_ to test for (it didn't work). :stuck_out_tongue:

**Comment by fatcerberus** [comment]
Additionally, this variation incorrectly prints "undefined":

```javascript
try {
	Duktape.errCreate = function() {};
	function EatyCounter() { this.n = 0; }
	Duktape.fin(EatyCounter.prototype, function() { print("Stupid pig"); })
	function pig(eatiness) {
		if (eatiness.n++ >= 5000) {
			pig(eatiness);
		} else {
			throw new Error("There is nothing. Nothing left at all!");
		}
	}
	pig(new EatyCounter());
} catch(e) {
	print(e);
}
```

**Comment by fatcerberus** [comment]
This is with latest master, by the way.

**Comment by svaarala** [comment]
Does this happen in v1.2.3? What about the fix branch for #287?

**Comment by fatcerberus** [comment]
Testing with 1.2.x is a pain now because I've moved my Duktape feature options into duk_config.h, but I'll do it for the sake of testing this bug. ;-)

I'll also test the try-finally fix, I didn't think this crash would be related but maybe?

**Comment by svaarala** [comment]
Ok, no worries. I should be able to reproduce this once I'm done with #287.

**Comment by fatcerberus** [comment]
I need to stop finding bugs, or I'll delay 1.3.0 indefinitely. :-)

#287 fixes the segfault in the first test, the second still incorrectly prints "undefined".  Will test with 1.2.3 shortly.

**Comment by svaarala** [comment]
Duktape v1.2.3 will issue a double error from this (without debugger):

```
$ ./duk.O2.123 _test.js 
Stupid pig
DoubleError: error in error handling
error in executing file _test.js
Stupid pig
```

**Comment by fatcerberus** [comment]
Double finalization as well, it seems.

**Comment by svaarala** [comment]
I guess there's a finalization for the object and one for the prototype?

**Comment by fatcerberus** [comment]
Ah, that makes sense.

The double error I know about, by the way: #191.  I've determined that it's caused by the recursion limit preventing errCreate from being called.

**Comment by svaarala** [comment]
Yeah, a better solution would be to reserve some callstack for errCreate but it doesn't work quite cleanly now.

**Comment by fatcerberus** [comment]
The first example doesn't crash v1.2.3, even with the debugger attached.  That's interesting, since that version _does_ exhibit the bug described in #287...

The second test prints "undefined" as well, though.  I'm thinking that second testcase is a different bug entirely.

**Comment by fatcerberus** [comment]
Hm, the first test doesn't crash earlier masters, either.  I'm starting to think it might not be your bug but an interaction with my error-intercepting code.

I think I'll open another issue for the other one.

**Comment by svaarala** [comment]
Your Duktape.errCreate() returns `undefined` which replaces the incoming error I think?

**Comment by svaarala** [comment]
If you replace it with:

```
Duktape.errCreate = function (e) { return e; };
```

seems to work correctly (?).

**Comment by fatcerberus** [comment]
Hm, you're right.  It's been a while since I've written an actual errCreate handler, I forgot it had to return the augmented error.  Silly me!

**Comment by fatcerberus** [comment]
Okay, confirmed not to segfault with unmodified master.  So the bug is mine.  Sorry!

**Comment by svaarala** [comment]
No problem :)

**Comment by svaarala** [comment]
Just to confirm, apart from the double error behavior already present in v1.2.3, was there a difference to v1.2.3 or something to fix?

**Comment by fatcerberus** [comment]
No, not that I could tell.

I did trigger an "uncaught error" error at one point, but that turned out to be because i accidentally compiled Duktape without debugger support and then tried to attach the debugger.

**Comment by svaarala** [comment]
Ok, I'll close this then :)

**Comment by fatcerberus** [comment]
I figured out the cause of the crash by the way, and it was indeed in my code: Throw notify calls duk_safe_to_string(), which ends up trying to grow the callstack, generates a double error as a result, which then calls back into Throw notify... ultimately smashing the stack.
