### ISSUE TITLE
Prefix increment of Proxy'd property doesn't return final value

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#309]
```javascript
function Majin() { this.power = 4499.5; }
buu = new Proxy(new Majin(), {
	get: function(t, prop) { return t[prop]; },
	set: function(t, prop, value) { t[prop] = value * 2; }
});
print(++buu.power);
print(buu.power);
```

Output:
```
4500.5
9001
```

Expected output was 9001 for both prints.

**Comment by svaarala** [comment]
Hmm, I think that's correct behavior?

- Read buu.power: evaluates to 4499.5
- Expression value is 4499.5 + 1 = 4500.5
- Write back 4500.5 which gets stored as 9001 internally

While the stored value is 9001, the expression value is 4499.5 + 1 = 4500.5?

**Comment by fatcerberus** [comment]
Hm, maybe?  I always intuitively viewed prefix increment as "increment then read" as opposed to postfix increment "read then increment"

**Comment by svaarala** [comment]
Firefox agrees with this so I think the current behavior is correct:

```
function Majin() { this.power = 4499.5; }
buu = new Proxy(new Majin(), {
    get: function(t, prop) { return t[prop]; },
    set: function(t, prop, value) { t[prop] = value * 2; }
});
Object { power: 4499.5 }
++buu.power
4500.5
buu.power
9001
```

**Comment by fatcerberus** [comment]
Huh, guess it's not a bug then.  It seemed odd to me, so figured I'd report just in case.

**Comment by svaarala** [comment]
I'll check the semantics and add this as a test case anyway.

**Comment by svaarala** [comment]
The semantics are here: http://www.ecma-international.org/ecma-262/6.0/index.html#sec-prefix-increment-operator

**Comment by fatcerberus** [comment]
Ah, okay, so it indeed evaluates as old + 1.  Not intuitive, but indeed compliant.  Good for me to keep in mind in the future, as this presumably also affects property setters as well.

**Comment by svaarala** [comment]
Yes, the behavior is same for property setters.

The behavior you intuitively expected would mean semantics like this for the Proxy:

- Invoke `get` to read value
- Increment by one
- Invoke `set` to read value
- Invoke `get` again to read expression value

There'd be two `get` calls; same for property setters and getters.
