### ISSUE TITLE
Don't include torture tests in combined source

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#311]
[Don't include torture tests in combined source] ...at least by default.  I realize they can't be easily split out because they are meant to stress-test under-the-hood stuff and thus need access to Duktape internals, but there should at least be a makefile target which excludes them from the distribution.  Unless you're writing code for Duktape itself, they are just bloat.

**Comment by svaarala** [comment]
But that bloat is 100% removed by the preprocessor, so what is the concrete issue with them?

**Comment by fatcerberus** [comment]
By bloat I was more referring to the size of duktape.c, which now stands at nearly 3MB.  This sometimes causes issues, e.g. MSVC locks up if duktape.c is modified when it tries to reload it.

**Comment by svaarala** [comment]
But if this is the issue, torture tests represent quite a small fraction of the source? Assertions are much larger for example. So unless there was a change to remove a lot more, would torture tests really make a meaningful dent in the combined size?

**Comment by fatcerberus** [comment]
Huh. For some reason I thought they were larger than they are, but looking at, e.g. the refzero test it's actually quite compact.

I guess it just didn't make sense to include these since normal users will never use them.  This is different from assertions, which are often useful when diagnosing bugs, etc.  but if it wouldn't make a significant dent in codebase size to exclude the torture tests, I agree it's not worth the trouble.

**Comment by fatcerberus** [comment]
Hm, Duktape source has a LOT of comments, now that I think of it.  Stripping these out would save a lot of space, but that would then mess with the line numbers for assertions, compiler errors/warnings, etc. so that's not really viable either.

Oh well, I guess using the separate source files is always an option if the huge file becomes a problem. :)

**Comment by svaarala** [comment]
They *are* actually used to diagnose corner cases. For example, if a user application is having some problems, enabling assertions and one or more torture options may help pinpointing the cause. But most often they're used only for Duktape development of course.

It would be possible to strip the comments but preserve line numbers though. I wouldn't want to use such a file myself but doing that and shipping a stripped version would be relatively simple.

**Comment by svaarala** [comment]
Here's a branch which adds a stripped source into the dist. The script strips multiline C comments but leaves single-line comments intact because those are often useful and it's safer (the script doesn't handle literals but literals can't be multiline so they won't be processed):

- https://github.com/svaarala/duktape/compare/add-comment-stripped-dist-source

The result is about 550kB smaller:

```
$ ls -l dist/src/
total 5552
-rw-rw-r-- 1 duktape duktape  103311 Aug 30 22:54 duk_config.h
-rw-rw-r-- 1 duktape duktape 3024935 Aug 30 22:55 duktape.c
-rw-rw-r-- 1 duktape duktape   66098 Aug 30 22:54 duktape.h
-rw-rw-r-- 1 duktape duktape 2479742 Aug 30 22:55 duktape_stripped.c
```

Here's a snapshot if you want to see if it makes a difference in your IDE setup: http://duktape.org/snapshots/duktape-1.2.99-20150830200629-v1.2.0-437-g1316910.tar.xz

If it does, I can merge this as a first version of providing a "stripped" source. If not, we can ditch this.

**Comment by fatcerberus** [comment]
Stripping comments cut 550kb, wow.  I knew there were a lot, but that's a way bigger reduction than even I was expecting.

Will have to see if this improves things.  To clarify, MSVC has no problem loading the file and editing it (Intellisense is excruciatingly slow though), but when it is modified outside the IDE, for example when checking out a different branch, the IDE has a tendency to lock up when it goes to reload the modified file.

Normally this isn't a problem because I don't usually keep duktape.c open while working on minisphere code.  But when I'm experimenting with customizations to Duktape itself it can be an issue.  Ironically though, that's the one scenario where having the comments is actually helpful...

The real issue is Intellisense (this is my secret to familiarizing myself with a codebase so quickly, it's a great tool for discovery when you don't know the API).  I'll have to see if stripping the comments improves the parsing speed at all.

**Comment by fatcerberus** [comment]
MSVC seems to have improved and no longer locks up when reloading `duktape.c` after a change.  So the comment-stripped dist isn't necessary anymore.  I'll close the issue.
