### ISSUE TITLE
Avoid including <windows.h> for application build

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#312]
Current `duktape.h` (`duk_config.h` Duktape 1.3) includes `<windows.h>` because it's needed for Duktape Date provider. It is not needed in the application build to provide e.g. types for the Duktape API, so it can be omitted from the application build. This is useful because the header contains a lot of defines which may conflict with user applications.

**Comment by svaarala** [comment]
There's now a guard for the include in master:

```
#if defined(DUK_COMPILING_DUKTAPE)
#include <windows.h>
#endif
```

**Comment by JoshEngebretson** [comment]
Great change, I was undef'ing conflicting symbols as I ran into them :+1:

**Comment by fatcerberus** [comment]
I was wondering how windows.h got mysteriously included in minisphere, I knew I didn't do it. :)
