### ISSUE TITLE
Compilation with IAR compiler fails

### ISSUE THREAD

**Issue by markusl** [svaarala/duktape#318]
Hi.

In our project we integrate Duktape in our build using CMake and use IAR Compiler for building the target binaries. Mostly everything goes just fine but there is one weird compilation error with our compiler. The link to relevant compiler vendor documentation is here: http://supp.iar.com/Support/?Note=99411

Compilation error:
```
[ 70%] Building C object vendor/duktape/CMakeFiles/duktape.dir/src/duktape.c.obj

                lj_ret = duk__handle_longjmp(thr, (duk_hthread *)entry_thread, (duk_size_t)entry_callstack_top);
                ^
"duk_js_executor.c",2053  Error[Pa082]: undefined behavior: the order of
          volatile accesses is undefined in this statement

```

With the following change we have managed to get Duktape working in our project but I'm not 100% sure if this is absolutely correct but at least it seems to work.
```
diff --git a/src-separate/duk_js_executor.c b/src-separate/duk_js_executor.c
index 5eedfb0..d6d6dc4 100644
--- a/src-separate/duk_js_executor.c
+++ b/src-separate/duk_js_executor.c
@@ -2050,7 +2050,9 @@ DUK_INTERNAL void duk_js_execute_bytecode(duk_hthread *exec_thr) {
 		                     (void *) entry_jmpbuf_ptr));
 		thr->heap->lj.jmpbuf_ptr = (duk_jmpbuf *) entry_jmpbuf_ptr;
 
-		lj_ret = duk__handle_longjmp(thr, (duk_hthread *) entry_thread, (duk_size_t) entry_callstack_top);
+ 	duk_hthread *et = entry_thread;
+ 	duk_size_t etop = thr->callstack_top;
+ 	lj_ret = duk__handle_longjmp(thr, et, etop);
 
 		if (lj_ret == DUK__LONGJMP_RESTART) {
 			/*
```

Best Regards,
Markus

**Comment by svaarala** [comment]
The fix is now in master - @markusl if you can verify that master no longer fails that'd be nice. Here's a snapshot distributable with the fix included: http://duktape.org/snapshots/duktape-1.2.99-20150903150407-v1.2.0-514-g838aa13.tar.xz

There's no change in the resulting binary as expected.
