### ISSUE TITLE
duk_config.h and genconfig improvements for 1.4 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#330]
- [x] Genconfig README `--metadata` examples are not relevant in dist
- [x] Review compilers, architectures, platforms, tags metadata
- [x] Solaris endianness fix #453
- [x] Sparc detection

**Comment by fatcerberus** [comment]
Does genconfig have documentation?  I'd like to test it out.

**Comment by svaarala** [comment]
It's here: https://github.com/svaarala/duktape/blob/master/doc/duk-config.rst

It's still "hidden" for 1.3 release, i.e. the default `duk_config.h` works as it does for 1.2 and `DUK_OPT_xxx` flags are supported. But you can already edit it manually when necessary.

Genconfig does work to the extent that you can generate a new autodetect or "barebones" header with overrides given on the command line or from files. However, some of these changes have not yet been merged to master (to become part of 1.3). I'll do that tomorrow, after I've implemented a few more features and rebased the duk_config.h work branch.
