### ISSUE TITLE
Inconsistent Behaviour of duk_is_primitive

### ISSUE THREAD

**Issue by jessedoyle** [svaarala/duktape#337]
Hello,

I'm the author of Crystal bindings to Duktape over at [duktape.cr](https://github.com/jessedoyle/duktape.cr). 

As I was writing (basic) test cases for the public api, I noticed that `duk_is_primitive` does not behave as advertised in the [api documentation](http://duktape.org/api.html#duk_is_primitive) when the index is invalid. The documentation states that the call should return `0` on an invalid index.

Currently, it appears that `duk_is_primitive` returns `1` on an invalid index. You can see my test case [here](https://github.com/jessedoyle/duktape.cr/blob/master/spec/duktape/api/type_spec.cr#L525).

I don't think this is a major issue, but I just wanted to report the inconsistency.

Thanks for making Duktape!

**Comment by svaarala** [comment]
Seems like a clear bug - I'll fix it for 1.3.0, should be easy to fix.

Thanks for reporting! :-)

**Comment by svaarala** [comment]
Ok, the fix is now in master and is going into Duktape 1.3.0 release.

I also extended the testcase for `duk_is_xxx()` calls to cover each for an invalid index. This didn't reveal any similar bugs.

**Comment by svaarala** [comment]
I'll add this to a 1.2.5 maintenance release too.

**Comment by jessedoyle** [comment]
Thanks for getting to this so quickly! Awesome!
