### ISSUE TITLE
Implement safe heap walking into the debugger protocol

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#358]
The debugger protocol supports heap object pointers but lacks the ability to allow the debug client to inspect heap objects, e.g.:

- Check type and internal fields like refcount, flags, internal prototype, etc
- Walk through properties and values (including internal ones)

With this primitive in place the debug protocol would be much more versatile. For example, an Eval resulting in an object value could be inspected, callstack entries could reference the relevant function objects, etc. A debug client could implement a value browser where property chains can be followed, etc.

The main challenge implementing this is that heap objects may be collected while they're being walked. For example, if an Eval result is a temporary object, that object will be unreachable by the time the debug client gets the result -- there are no references to the object once the Eval command handling is done.

The best candidates to avoiding this seems to be either:

- Disable refzero handling and mark-and-sweep when the debugger is paused. Process all refzero entries when the blocking debugger message loop finishes. The downside is that one might run out-of-memory if the blocking message loop takes a long time and e.g. a lot of Evals are executed.

- Add explicit debugger commands to "start walking" and "end walking" which have a similar effect on garbage collection. This approach allows the debug client to "lock" the heap for inspection and then release it.

- A hybrid of the two where garbage collection is disabled during the message loop, but the debug protocol had an explicit "hint" command to indicate that the debug client is not currently walking any values so that running pending garbage collection is safe.

The most important initial step is to identify the best approach and implement a very small prototype for walking so that the approach can be verified in practice.

**Comment by fatcerberus** [comment]
Start/end walking commands are interesting but they seem like they could be confusing, for example it would be natural to issue StartWalking command right before walking an object, but this would actually be incorrect--in the case of a temporary Eval result, it will already have been collected.  You have to actually start walking *before* the Eval, which doesn't seem intuitive.

Another potential snag with this is memory safety.  Duktape would have to be tolerant of already-freed or otherwise invalid heap pointers so that the client can't segfault the target remotely (this would be a very big security issue!)

**Comment by svaarala** [comment]
That memory safety issue is really the only problematic issue - otherwise adding heap walking would just be a matter of figuring out the best command formats etc.

I don't have an idea how to avoid that memory safety issue really. Even with some kind of garbage collect locking the debug client could just make up pointers and ask Duktape to inspect an object behind the made up pointer. Validating such pointers would be quite difficult: Duktape would essentially need to maintain some information about valid pointers or possibly use some running number identifiers instead of pointers to begin with.

Even so, it'd be nice if ensuring memory safety wasn't very tricky for the debug client, so I'm kind of leaning towards the third option: freezing garbage collection when debugger message loop is blocking, and add an optional command to indicate when to garbage collect if the garbage collect freeze becomes an issue. The debug client won't have to use that command, of course, unless it's considered necessary for the specific target.

**Comment by fatcerberus** [comment]
> make up pointers

For some reason I found that hilarious.  "Here, evaluate this object at 0xdeadbeef... It's real, I swear!" *crash*

:)

**Comment by svaarala** [comment]
I don't think there's a portable way of validating pointers or ensuring dereferencing a pointer won't lead to memory safety or security issues - there are simply too many targets with different memory management to do that. On some platforms one can explicitly validate pointers or memory ranges but that'd be quite messy because it'd need to be abstracted etc, and it still wouldn't work everywhere.

This is one reason why I don't think a security relevant target should have debugger support enabled. (Technically debugger support can be enabled as long as there's no way to attach a debug session, at least an untrusted one.)

Even with seemingly innocent operations like resetting a function's PC (which might be useful for some things) it's possible to violate memory safety because of indirectly indexed opcodes where e.g. a constant number is not a static value in the bytecode but an integer in a register (these are needed for handling large functions).

**Comment by fatcerberus** [comment]
Yeah, mainly my concern is that it's not easy to *accidentally* crash the target, start/end walking commands would be too error prone in that regard I think.

**Comment by svaarala** [comment]
I agree, like I said I find the third option most appealing so far.

**Comment by svaarala** [comment]
But note that it's not really a security issue if you can accidentally crash a target if there's an inherent security issue with made up pointers anyway. So I view accidentally crashing the target with heap walking a stability and/or an ease-of-use issue. Providing security guarantees would mean the mechanism would be safe against intentional attacks which would be quite difficult.

Anyway, even with the third option the debug client must be aware that it can't hold pointer references after it resumes execution. If it needs to track an object through a pause-resume-pause cycle, it'd either need some way of looking the object again, or an ability to "pin" an object so that it won't get freed and its pointer would be guaranteed to stay valid (and of course any objects reachable from that object too).

Object pinning would be useful outside of debugging too, so maybe it could be added later to the walking mechanism.

**Comment by svaarala** [comment]
I think I'll finish the longjmp performance fixes and then work a bit on this, it'd be quite useful and I'm itching to prototype it :-)

**Comment by fatcerberus** [comment]
I think that's fine (not holding pointer references after a resume), at least for me I would intuitively *expect* the pointers to be invalidated by the resume, if only because the environment will change very quickly once execution starts up again.  So that's not an issue in my mind.

That said, the pinning _might_ actually be useful for, e.g. a client implementing a "watch" feature, it could pin an object so it doesn't get collected while the debugger examines it for changes.

**Comment by svaarala** [comment]
Agree, watch would probably be the most obvious user for that. I've been doing "watch" using a per-step Eval so far, which is crude but often enough :)

The challenge with pinning is the cleanup: what happens if the debug transport is broken? Or worse, what if the debug client crashes, taking all pinning state with it (so that it can't reconnect and unpin)?

Ideally the pinning state would be automatically undone on a detach - but that'd require state.

And if that's the case, debugger "pinning" could simply be implemented using an array of object references stored in say the heap stash, so that the tracking state also serves to pin the objects.

One could then just delete the whole list on a reconnect. If there were enough write primitives in the debug protocol, all of this could even be done by the debug client with no explicit support from Duktape itself. (Probably not preferable, but just an option.)

**Comment by svaarala** [comment]
The choice for this is becoming nearer :) One more observation on the hybrid approach (= automatic locking during pause, explicit collection hint, automatic unlocking on resume):

- If the debug client wants to Eval and/or inspect stuff while Duktape is *not paused* (which is supported, and which is why `duk_debugger_cooperate()` exists) there'd be no way to lock garbage collection for these operations.

I'm not sure that locking while not paused would necessarily be very wise: when Duktape is running it peeks and executes debugger commands relatively lazily (checking every 200ms or less). So once the debug client locks GC and goes to evaluate and inspect, it could take even seconds before it had the chance to unlock GC again.

So perhaps it's just best to not support that and document that the best approach there is to pause, eval/inspect, and resume.

**Comment by fatcerberus** [comment]
As noted above, the most obvious use case for live Eval would be Watch, a use case which is hindered in any case by the lazy message processing.  In the long term it'd probably be better to include Watch as native functionality (which would also allow, e.g. conditional breakpoints).

**Comment by svaarala** [comment]
Btw, I don't mean "break on watch expression" here but rather just displaying some expression values in a semi realtime fashion. For example, `game.score` or `sensor.value`. Watch expression triggered breakpoints are a different matter and would quite naturally require direct integration into the executor.

As a general design approach I'd prefer making the primitives dumb and the debug client smart: this is mostly motivated by the fact that footprint is a really pressing concern on low memory devices so it's generally preferable to provide a minimum number of non-overlapping building blocks rather than the most optimal front end services. That's why I like object inspection, for example, because a single primitive enables a lot of use cases that don't need to be defined by the target.

But I agree that actual "break on watch expression" support can't be implemented without target support. Or rather, the only current way of doing so is to single step and Eval, which works to a pretty large extent, but is slow and involves protocol messaging for every step.

**Comment by svaarala** [comment]
To clarify a little bit, with current Eval it's quite useful to display e.g. `sensor.value` in a semi realtime fashion as the program executes. But suppose that value was structured, e.g. `game.state`, and one wanted to watch the whole object (its top level keys at least) in a similar manner. That would require object inspection and locking, so one would run into the abovementioned issues.

The only way to do that now would be to Pause, then update the state display by inspecting the state object, and Resume, and to do that e.g. once every second, driven by the debug client.

But this is unrelated to breakpoints as such.

**Comment by svaarala** [comment]
Inspecting objects in general without being paused is a little bit dangerous: the objects can mutate on the fly so that you won't be working with a consistent snapshot. So I guess it'd be quite clear cut that inspection is only really supported when Duktape is paused, and the GC locking would be tied to that paused state.

**Comment by svaarala** [comment]
This has been implemented in master, i.e. GC is disabled during paused state and inspection commands exist.
