### ISSUE TITLE
Move setjmp catchpoints into a separate, minimal outer function

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#369]
Having setjmp() catchpoints in a separate outer function (instead of being integrated with call handling or bytecode executor) compiles into better code because a setjmp() in a function seems to cause compilers to emit less efficient code (perhaps related to variable handling). As a quick measurement, refactoring the bytecode executor setjmp() to be outside of the main executor function was 5-10% faster for native code and ~25% faster for Emscripten-compiled Duktape.

This change will also facilitate using C++ exceptions in place of setjmp/longjmp because the control flow will be easier to tweak to match C++ exceptions in a smaller outer function.

Tasks:

- [x] Rework bytecode executor setjmp to be outside of the main executor
- [x] Rework `duk_handle_call()` setjmp to be outside of the main call setup code - #498
- [x] Rework `duk_handle_safe_call()` setjmp to be outside of the safe call setup - #498

**Comment by fatcerberus** [comment]
I don't understand why this improves performance, but it's hard to argue with 5-10%. :-)

**Comment by AleksiAhtiainen** [comment]
I vote for this also because we have run into compiler issues with setjmp: we have had to disable optimizations completely for some Duktape functions, since the compiler we use incorrectly reuses the stack also on top of variables used within the setjmp block.

**Comment by svaarala** [comment]
@AleksiAhtiainen Yeah, setjmp/longjmp handling is broken on some other toolchains too.

It's also relatively common for compilers to emit incorrect clobber warnings etc when setjmp/longjmp are used in large functions (I've had to diagnose a few of these). So it does help for setjmp to be used in a short wrapper function only.

**Comment by svaarala** [comment]
I have a rough working branch for this now. The change seems to increase footprint a little bit, but improves call performance slightly. With this change all the `DUK_SETJMP()` sites will be in relatively small functions so tweaking them is easier, and the impact of turning off optimization for them should be relatively low.

Also tried a quick test branch to use C++ exceptions instead of setjmp/longjmp (on top of the working branch). The diff is simple and seems to handle C++ cleanup (RAII) correctly. So as soon as this is merged, adding C++ exception support (at least an initial version of that) should be quite easy.

I'm not sure if this change will make 1.4.0 (I'm trying to release it during December) but it should be in master quite soon afterwards in any case.
