### ISSUE TITLE
Warnings in master when compiled with -Wall

### ISSUE THREAD

**Issue by aldialimucaj** [svaarala/duktape#372]
From commit hash: 91d7830

gcc -fomit-frame-pointer -Wall -Wextra   -c -g -Werror -Ilib -std=c99 -fPIC  -MMD -MP -MF "build/Debug/GNU-Linux-x86/lib/duktape.o.d" -o build/Debug/GNU-Linux-x86/lib/duktape.o lib/duktape.c
duk_api_stack.c:2103:27: error: ‘duk_safe_to_hstring’ defined but not used [-Werror=unused-function]
duk_error_misc.c:12:22: error: ‘duk__have_active_catcher’ defined but not used [-Werror=unused-function]

**Comment by svaarala** [comment]
There are a couple of warnings in the master right now - I'll clean these up a bit later.

**Comment by aldialimucaj** [comment]
Confirmed. Thanks.
