### ISSUE TITLE
Store user data in duk_context

### ISSUE THREAD

**Issue by bel2125** [svaarala/duktape#392]
Hello,

I'm maintainer of the [CivetWeb](https://github.com/civetweb/civetweb/) web server.
I am currently trying to add server side JavaScript support by integrating Duktape (https://github.com/civetweb/civetweb/issues/194). CivetWeb already has [Lua](http://www.lua.org/) support, and I want to integrate Duktape in a similar way.

One key feature I used in the Lua integration is upvalues pushed by C functions, but I did not find any equivalent in Duktape yet. I would have multiple instances of the interpreter in the same process and need to attach some user data to C functions to identify the instance.

E.g.: for Lua, I do something like this in C:
```
1) push a function name
2) push values required to identify the instance within the C function (upvalues)
3) push a function pointer
4) bind these things together, so the C function can be called in the scripting language
```
In the implementation of the C function, I can access the values pushed in step 3.
In duktape I found `duk_push_c_function + duk_put_prop_string` - they seems to do 1+2+4, but not 3.

So, is there a way to add upvalues?

Is there a way to add some global user data to the `duk_context` - e.g. `duk_set_user_data(context, void * data)` done after `duk_create_heap_default`, and a corresponding `duk_get_user_data(context)` to call inside a C function called from the script?
If not, I think I could implement such a function on my own. 
Are you interested in patches (pull requests), in case I need to make some?

**Comment by svaarala** [comment]
This guide section may be useful: http://duktape.org/guide.html#programming.9

Once you have pushed the C function on the value stack, you can add ordinary properties to the function object pushed to identify the particular instance. In the C function you can then access the properties like:

```c
duk_push_current_function(ctx);
duk_get_prop_string(ctx, -1, "myFunctionIdentifier");
```

Another much more level mechanism is the "magic" value of a function; it's a plain integer associated with the Ecmascript function instance which you can then access in the C function (`duk_get_current_magic()`).

As for the global user data, Duktape has three different "stashes": heap, global, thread. The stash objects are accessible from C code but not ordinary Ecmascript code, and can be used to store various auxiliary values.

So, you could store a void pointer into the global stash (or heap stash, if that's more appropriate; one heap may have multiple global object environments), e.g. as:

```c
duk_push_global_stash(ctx);
duk_push_pointer(ctx, (void *) myPointer);
duk_put_prop_string(ctx, -2, "myUserData");
```

and then read it back later similarly as a property read.

**Comment by bel2125** [comment]
Thank you for your quick reply.

The function "magic" seems to be only `int16_t`, but I need to store a pointer. I would prefer not to use an extra lookup table if possible.

Now, I used this code:
```
	duk_push_global_stash(ctx);
	duk_push_pointer(ctx, (void *)conn);
	duk_put_prop_string(ctx, -2, civetweb_conn_id);
```
after creating the interpreter state, and to get the value again in a C function
```
	duk_push_global_stash(ctx);
	duk_get_prop_string(ctx, -1, civetweb_conn_id);
	conn = (struct mg_connection *)duk_to_pointer(ctx, -1);
```
This seems to do what I need.
I'm doing this quite often - is it efficient this way?

If possible, I would like to store more C functions together with some values (numbers, strings, ...) in a table. I suppose this can be done with a sequence like `duk_push_global_object`, `duk_push_object`, then `duk_push_c_function + duk_put_prop_string` for all functions, `duk_push_string + duk_put_prop_string` for all strings, and so on, then finally `duk_put_prop_string` to give the global instance of the table/object a name.
Is it possible to add some "hidden" values to a table/object too? (values only accessible in C, not in the scripts). Is pointer added by a `duk_push_pointer + duk_put_prop_string` in the object accessible from the script somehow?

**Comment by fatcerberus** [comment]
If you don't want it accessible to script, you have to use an invalid UTF-8 string for the property name (starting with a \xff byte).  put_prop_string() is the same thing as doing obj[str] in script, so if you start it with a FF byte it won't be accessible through normal means.

**Comment by svaarala** [comment]
A bit more detail on what @fatcerberus said: http://duktape.org/guide.html#internalproperties

These internal properties will merge with ES6 "symbols" down the road. Right now these internal properties cannot be accessed by standard Ecmascript code but it's possible to craft a string using a buffer to gain access - so they're protected from accidental access but not intentional access. This will change later on for better sandboxing.

**Comment by svaarala** [comment]
@bel2125 If you need to store a pointer, then probably easiest is to use an internal property on the Ecmascript function object (pushed by `duk_push_c_function()`) as I described.

As for performance, the cost is the same as a property lookup anywhere else - not terribly fast or terribly slow.

**Comment by bel2125** [comment]
Thanks, it works according to your hints.
