### ISSUE TITLE
Debug macros cannot be overriden

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#402]
Hi,

I want to send debug output to Visual Studio instead of being printed in the console.

The problem is that macros like `DUK_DEBUG_LOG` are defined **after** duk_config.h and cannot be overriden not `DUK_OPT...` is available.

Regards,
Mauro.

**Comment by svaarala** [comment]
This is now fixed in master. All debug logs are written through a user-provided debug write macro which can be freely retargeted.
