### ISSUE TITLE
Patch: Take filename as source for require module path if ID is not present

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#404]
Hi,

When the main javascript code is evaluated and the code uses `require` to load another modules, the resulting id path is not useful if the developer runs code from different paths.

My proposal is to look for the main module's filename as a base for path resolution if module id is empty.

In `duk_bi_global_object_require` function, just below the `str_mod_id = duk_get_string(ctx, 2);` line, I added the following code (based on debugger's one):

```
    if (str_mod_id == NULL || *str_mod_id == 0)
    {
      duk_hthread *curr_thr;
      duk_activation *curr_act;
      duk_size_t i;

      curr_thr = (duk_hthread *)ctx;
      DUK_ASSERT_DISABLE(curr_thr->callstack_top >= 0);
      DUK_ASSERT(curr_thr->callstack_top <= curr_thr->callstack_size);

      while (curr_thr != NULL)
      {
        i = curr_thr->callstack_top;
        while (i > 0)
        {
          i--;
          curr_act = curr_thr->callstack + i;

          duk_push_tval(ctx, &curr_act->tv_func);
          duk_get_prop_stridx(ctx, -1, DUK_STRIDX_FILE_NAME);
          if (duk_is_string(ctx, -1))
          {
            str_mod_id = duk_get_string(ctx, -1);
            if (str_mod_id != NULL && *str_mod_id != 0)
            {
              //got a valid filename!!
              duk_remove(ctx, -2);//remove the function from stack and end loop
              duk_remove(ctx, -2);//remove the undefined id from original function
              break;
            }
          }
          duk_pop_2(ctx);
        }
        if (i > 0)
          break;
        curr_thr = curr_thr->resumer;
      }
    }
```

Sorry for not creating a pull request, I didn't setup tools for building DukTape from Git repository.

Kind regards and excellent work,
Mauro Leggieri

**Comment by svaarala** [comment]
Thanks, I'll see if the change could go to master. Could you provide a few short cut-paste examples to illustrate what the concrete behavior change is (before vs. after)?

**Comment by fatcerberus** [comment]
Just throwing this out there: Doesn't this break the CJS spec?

**Comment by mxmauro** [comment]
Hi Sami, yes.

I'm using DukTape to create a PHP-like engine for an embedded webserver in an app. Webpages are store in a folder tree.

`html/main/index.js` has the following contents:

```
    var ext = require('../js/extension.js');\n"
    ....
```

When my modSearch callback is called, the module ID is correctly resolved to `html/js/extension.js`. Without the modification I get `js/extension.js`.

Regards.

P.D.: The sample is real but I removed all my wrapper stuff to simplify.

**Comment by svaarala** [comment]
Is `html/main/index.js` using the global `require()` function which exists conceptually at the top of the CommonJS hierarchy? I guess it shouldn't be the case because `..` would then cause an error.

**Comment by svaarala** [comment]
I'm not sure if this solves your problem (I don't yet understand it fully), but you can assign an `.id` for the global `require()` if that helps:

```
duk> Duktape.modSearch = function(id) { print(id); throw new Error('not found: ' + id); }
= function anon() {/* ecmascript */}

# Default behavior: invalid ID, can't ascend from top
duk> require('../foo')
TypeError: cannot resolve module id: ../foo
	duk_bi_global.c:926
	require  native strict preventsyield
	global input:1 preventsyield

# Force global require to believe it's running in a/b/c.js
duk> require.id = 'a/b/c.js'
= a/b/c.js
duk> require('../foo')
a/foo
Error: not found: a/foo
	anon input:1 preventsyield
	require  native strict preventsyield
	global input:1 preventsyield
```

**Comment by mxmauro** [comment]
Hi Sami,

Hahaha, what a simple solution. 

To be honest I didn't tested it. I thought `id` field was non-writable because it is configured as `DUK_PROPDESC_FLAGS_C`.

So if `DUK_DEFPROP_HAVE_WRITABLE` flag is missing then the field is writable by default?

On the other hand if your `foo` does an inner `require('bar')` the resulting `id` will be `bar` but if you do `require('./bar')` then the resulting `id` will be `a/bar`. Is the correct behavior to add the `./` prefix?

Thanks,
Mauro.

**Comment by fatcerberus** [comment]
Yes, an unqualified ID ("bar") is absolute under CJS semantics, you have to add `./` for a relative ID.

**Comment by svaarala** [comment]
@mxmauro The global `require()` doesn't have an `id` property at all so you can write it:

```
duk> Object.getOwnPropertyDescriptor(this.require, 'id')
= undefined
```

I'm not sure this is the best behavior but it's the current one anyway. (It might make more sense for the `id` property to exist and be an empty string or `null`, for example.)

If a property is configurable but non-writable, you can't write it using a property assignment (`obj.foo = 123;`) but you can still write it using `Object.defineProperty(obj, 'foo', { value = 123 })`.

Finally, you can always modify a property from C code using `duk_def_prop()` -- even a non-writable and non-configurable property -- using the `DUK_DEFPROP_FORCE` flag.

**Comment by mxmauro** [comment]
Thanks @svaarala and @fatcerberus for clarifying my doubts.

Tested using C functions and worked as you said.

Kind regards,
Mauro.

**Comment by svaarala** [comment]
@mxmauro Good to hear :)
