### ISSUE TITLE
Error in  RegExp 

### ISSUE THREAD

**Issue by stoodx** [svaarala/duktape#410]
Hi All,

When I try to load my js, I always get the following error:

 SyntaxError: invalid regexp quantifier (unknown char) (line 501)

This is 
var sourceRegex = /^function\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/;

I use  duketape 1.3.0

Viktor

**Comment by svaarala** [comment]
Your regexp is missing a backslash escape for braces (`{` and `}` -> `\{` and `\}`) which is required by Ecmascript specification (but often allowed by other engines). See #142 and #74.

**Comment by stoodx** [comment]
Thank you very much,
I have fixed it and my script passed.  But after it I got a new error

TypeError: invalid base value

Can you help me once again?  Node.js ran that js  without error.

https://github.com/stoodx/jssqlapp/blob/master/jsslapp/Files/sql-debug.js

**Comment by svaarala** [comment]
The offending line is:

```
    var parsed = jsfunc.toString().match(sourceRegex).slice(1);
```

What happens is that `match()` returns null (no match) and `null.slice(1)` gets called leading to the error. For some reason sourceRegex is not matching as expected.

**Comment by stoodx** [comment]
thank you for help.

**Comment by svaarala** [comment]
You're welcome - I know that regexp difference is awkward :/

**Comment by fatcerberus** [comment]
@svaraala For what it's worth this is what I meant about "invalid base error" being vague and confusing (I know you're working on a fix :) ), when you have a chain of calls like that match() above it's difficult to tell where the point of failure is.

**Comment by svaarala** [comment]
@fatcerberus I know, I haven't disagreed about the problem with property error messages being vague, but I haven't been sure what the best improvement is. But that's being worked as you say.

**Comment by stoodx** [comment]
Sorry,  I corrected that code on 
  var sourceRegex = /^function\s*\(([^)]*)\)\s*\{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?\}$/;
  function parseJSFunc(jsfunc) {
    // Match the body and the return value of a javascript function source
	var parsed = jsfunc.toString().match(sourceRegex);
	if (!parsed) { return {}; }
	parsed = parsed.slice(1);	
    return {arguments : parsed[0], body : parsed[1], returnValue: parsed[2]}
  }

https://github.com/stoodx/jssqlapp/blob/master/jsslapp/Files/sql-debug.js

But I got the same error.  I tried that fixed piece to insert into another js. The program  passed without errors.

 Is there any way to define a problematic string in js by using Debug mode? 
I use MSVC2012.

**Comment by fatcerberus** [comment]
I see what you're doing - you call toString() on a function to get its source and then try to run a regex match against it.  Duktape doesn't track source code for functions, so that won't work.
