### ISSUE TITLE
Assertion failed: Typed arrays 2 must be run on a little-endian system

### ISSUE THREAD

**Issue by stoodx** [svaarala/duktape#415]
Try to run SQLite (sql-debug.js) from my SyncData.js and get this error:
//////////////
 Assertion failed: Typed arrays 2 must be run on a little-endian system
Error: abort() at Error
        jsStackTrace D:\Work\jssqlapp\trunk\jsslapp\Files\sql-debug.js:987
        stackTrace D:\Work\jssqlapp\trunk\jsslapp\Files\sql-debug.js:1004
        abort D:\Work\jssqlapp\trunk\jsslapp\Files\sql-debug.js:210374
        assert D:\Work\jssqlapp\trunk\jsslapp\Files\sql-debug.js:430
        anon D:\Work\jssqlapp\trunk\jsslapp\Files\sql-debug.js:1062
        anon D:\Work\jssqlapp\trunk\jsslapp\Files\sql-debug.js:211147 preventsyield 
		require  native strict preventsyield
        main .\Files\SyncData.js:29 preventsyield
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more in
formation.
////////////////////

My SyncData.is:
 
///////////////
function getError(fileName)
{
	print("getError: Not init");
    return null;
}

var readFileHelper = (this.readFileNative || getError);

function readFile(fileName)
{
    return readFileHelper(fileName);
}

Duktape.modSearch = function (id) 
{//require
    print('Loading module: ', id);
    // Return source code for module or throw an error.
	var res = readFile(id);
    if (typeof res === 'buffer') 
	{	
		print('require() - ok');
		return res.toString('ascii');
    }
    throw new Error('module not found: ' + id);	
};

//start function
function main(sqlModule, databaseName)
{
    var sql = require(sqlModule);
}
///////////////

Dump of stack:
//////////////////////////////
ctx: top=2, stack=
[
{
	readFileNative:{_func:true},
	getError:{_func:true},
	readFile:{_func:true},
	main:{_func:true},
	readFileHelper:{_func:true},
	Module:{
		print:{_func:true},
		read:{_func:true},
		readBinary:{_func:true},
		arguments:{},
		load:{_func:true},
		printErr:{_func:true},
		thisProgram:"./this.program",
		preRun:[],
		postRun:[],
		Runtime:{
			setTempRet0:{_func:true},
			getTempRet0:{_func:true},
			stackSave:{_func:true},
			stackRestore:{_func:true},
			getNativeTypeSize:{_func:true},
			getNativeFieldSize:{_func:true},
			STACK_ALIGN:16,
			getAlignSize:{_func:true},
			dynCall:{_func:true},
			functionPointers:[],
			addFunction:{_func:true},
			removeFunction:{_func:true},
			getAsmConst:{_func:true},
			warnOnce:{_func:true},
			funcWrappers:{},
			getFuncWrapper:{_func:true},
			UTF8Processor:{_func:true},
			getCompilerSetting:{_func:true},
			stackAlloc:{_func:true},
			staticAlloc:{_func:true},
			dynamicAlloc:{_func:true},
			alignMemory:{_func:true},
			makeBigInt:{_func:true},
			GLOBAL_BASE:8,
			QUANTUM_SIZE:4,
			__dummy__:0
		},
		cwrap:{_func:true},
		ccall:{_func:true},
		setValue:{_func:true},
		getValue:{_func:true},
		ALLOC_NORMAL:0,
		ALLOC_STACK:1,
		ALLOC_STATIC:2,
		ALLOC_DYNAMIC:3,
		ALLOC_NONE:4,
		allocate:{_func:true},
		Pointer_stringify:{_func:true},
		UTF16ToString:{_func:true},
		stringToUTF16:{_func:true},
		UTF32ToString:{_func:true},
		stringToUTF32:{_func:true},
		stackTrace:{_func:true}}},
		"abort() at Error\n\tjsStackTrace D:\\Work\\jssqlapp\\trunk\\jsslapp\\Files\\sql-debug.js:987\n\t
		stackTrace D:\\Work\\jssqlapp\\trunk\\jsslapp\\Files\\sql-debug.js:1004\n\t
		abort D:\\Work\\jssqlapp\\trunk\\jsslapp\\Files\\sql-debug.js:210374
		\n\tassert D:\\Work\\jssqlapp\\trunk\\jsslapp\\Files\\sql-debug.js:430\n\t
		anon D:\\Work\\jssqlapp\\trunk\\jsslapp\\Files\\sql-debug.js:1062\n\t
		anon D:\\Work\\jssqlapp\\trunk\\jsslapp\\Files\\sql-debug.js:211147 
		preventsyield\n\t
		require  native strict preventsyield\n\t
		main .\\Files\\SyncData.js:29 preventsyield\n
		If this abort () is unexpected, build with -s ASSERTIONS=1 which can give more information."]
///////////////////////

Full project is here:
https://github.com/stoodx/jssqlapp
JS and database are here:
https://github.com/stoodx/jssqlapp/tree/master/jsslapp/Files

Any ideas.

**Comment by svaarala** [comment]
You are using a Duktape.Buffer to initialize a typed array view:

```
//var buffer = new ArrayBuffer(TOTAL_MEMORY);
var buffer = new Duktape.Buffer(TOTAL_MEMORY);
```

... which causes issues with the assert:

```
// Endianness check (note: assumes compiler arch was little-endian)
HEAP32[0] = 255;
assert(HEAPU8[0] === 255 && HEAPU8[3] === 0, 'Typed arrays 2 must be run on a little-endian system');
```

See "Typed array constructors interpret other buffer objects as value arrays" in http://wiki.duktape.org/HowtoBuffers.html. In short, a non-ArrayBuffer argument to a typed array constructor gets treated like an array initializer, same as how a typed array argument to a typed array gets treated. So instead of using the buffer as is, a new ArrayBuffer gets created and populated with a copy of the value.

If you use ArrayBuffer:

```
((o) Duktape 1.3.0 (v1.2.0-614-g57bdc8c)
duk> var buffer = new ArrayBuffer(16)
= undefined
duk> var HEAP32 = new Int32Array(buffer)
= undefined
duk> var HEAPU8 = new Uint8Array(buffer)
= undefined
duk> HEAP32[0] = 255
= 255
duk> HEAPU8[0]
= 255
duk> HEAPU8[3]
= 0
```

**Comment by stoodx** [comment]
Thank you for response.

If I replace  Duktape.Buffer on ArrayBuffer. I get the error:

TypeError: invalid base value

The full stack:
////////////////////////////
Stack:
ctx: top=2, 
stack=[
{
	readFileNative:{_func:true},
	getError:{_func:true},
		readFile:{_func:true},
		main:{_func:true},
		readFileHelper:{_func:true},
		Module:{                                            
			print:{_func:true},
			read:{_func:true},
			readBinary:{_func:true},
			arguments:{},
			load:{_func:true},
			printErr:{_func:true},
			thisProgram:"./this.program",
			preRun:[],
			postRun:[],
			Runtime:{
				setTempRet0:{_func:true},
				getTempRet0:{_func:true},
				stackSave:{_func:true},
				stackRestore:{_func:true},
				getNativeTypeSize:{_func:true},
				getNativeFieldSize:{_func:true},
				STACK_ALIGN:16,
				getAlignSize:{_func:true},
				dynCall:{_func:true},
				functionPointers:[],
				addFunction:{_func:true},
				removeFunction:{_func:true},
				getAsmConst:{_func:true},
				warnOnce:{_func:true},
				funcWrappers:{},
				getFuncWrapper:{_func:true},
				UTF8Processor:{_func:true},
				getCompilerSetting:{_func:true},
				stackAlloc:{_func:true},
				staticAlloc:{_func:true},
				dynamicAlloc:{_func:true},
				alignMemory:{_func:true},
				makeBigInt:{_func:true},
				GLOBAL_BASE:8,QUANTUM_SIZE:4,__dummy__:0},
				cwrap:{_func:true},ccall:{_func:true},
				setValue:{_func:true},
				getValue:{_func:true},
				ALLOC_NORMAL:0,
				ALLOC_STACK:1,
				ALLOC_STATIC:2,
				ALLOC_DYNAMIC:3,
				ALLOC_NONE:4,
				allocate:{_func:true},
				Pointer_stringify:{_func:true},
				UTF16ToString:{_func:true},
				stringToUTF16:{_func:true},
				UTF32ToString:{_func:true},
				stringToUTF32:{_func:true},
				stackTrace:{_func:true},
				HEAP:undefined,
buffer:|ff00000000000000332e382e372e340053514c4954455f0000980000109800002
09800003898000048980000000000000000000000000000000000000000000000000000000000000
/////////////////////////////

As you see,  the last normal function is buffer() there. So after its init the stack corrupts.

**Comment by svaarala** [comment]
But where is that TypeError thrown from (which line/statement)?

**Comment by svaarala** [comment]
I'm not sure if this is the same error you get but:

```
TypeError: invalid base value
	duk_hobject_props.c:2250
	cwrap /tmp/sql-debug.js:562
	anon /tmp/sql-debug.js:211018
	global /tmp/sql-debug.js:211147 preventsyield
```

The offending line is:

```
sqlite3_open = Module['cwrap']('sqlite3_open', 'number', ['string', 'number']);
```

Maybe `Module` or `Module['cwrap']` is not defined?

**Comment by stoodx** [comment]
>Maybe Module or Module['cwrap'] is not defined?

But I see them in the stack (see above). Plus, that script works in Node.js

**Comment by svaarala** [comment]
Duktape doesn't provide the same global environment as Node.js. If something works in Node.js it doesn't necessarily mean it works in Duktape.

**Comment by svaarala** [comment]
Ah, `Module['cwrap']` is indeed defined, the stack trace shows this:

```
    cwrap /tmp/sql-debug.js:562
```

That line is:

```
      funcstr += JSsource['stackRestore'].body.replace('()', '(stack)') + ';';
```

Something is probably off there, maybe relying on a `.source` property or something.

**Comment by stoodx** [comment]
1. How did you get this info:
///////////////////////////////////
TypeError: invalid base value
    duk_hobject_props.c:2250
    cwrap /tmp/sql-debug.js:562
    anon /tmp/sql-debug.js:211018
    global /tmp/sql-debug.js:211147 preventsyield
////////////////////////////////////

2.  Why don't I see a normal stack after buffer init:
new ArrayBuffer();
new Duktape.Buffer();

For display I use this fuctions
const char* stoodx::CDukSyncNativeData::ReadFullStack()
{
	if (!m_ctx)
		return NULL;
	duk_push_context_dump(m_ctx);
	return duk_safe_to_string(m_ctx, -1);
}

**Comment by svaarala** [comment]
Errors have a `.stack` property:

- http://duktape.org/guide.html#errorobjects

You can access that from C code e.g. as:

```
/* assuming an error is on the top of the stack (-1) */
duk_get_prop_string(ctx, -1, "stack");
printf("%s\n", duk_safe_to_string(ctx, -1));
duk_pop(ctx);
```

**Comment by stoodx** [comment]
thank for info.

**Comment by svaarala** [comment]
You're welcome, I hope things work out :)

I'm not sure what the goal for your application is, but if it's simply wrapping sqlite, it'd probably be easiest to write Duktape/C bindings for sqlite in C code and then use these bindings from Javascript.

**Comment by stoodx** [comment]
You are right, sqlite  is only a part of the project.  Duktape is used for another things too and I wouldn't  like to  drag an additional C++ interface into the project.

**Comment by fatcerberus** [comment]
@svaarala This is all the more reason I'd say for `Duktape.Buffer` to go the way of the dinosaur in v2.0. ;-)

**Comment by svaarala** [comment]
Yeah, the primary reason Duktape.Buffer exists is that plain buffer values need some object counterpart to be coerced to when coerced using `ToObject`. That coercion could just result in an `ArrayBuffer` IMO.
