### ISSUE TITLE
Interpret parameters as objects

### ISSUE THREAD

**Issue by BorisFaz** [svaarala/duktape#416]
Hello. I'm moving my first steps into duktape. One thing i really don't understand is how to get and interpret a function parameter as object. I mean the right JS-duktape object.
I created the classical Point constructor as done into different code examples. what i need is how to get and interpret a Point object passed as parameter into a function.
Example:
duk_ret_t examinate_point(duk_context *ctx)
{
	// Get arguments
	int res   = duk_is_object(ctx,1);
	int res2 = duk_is_pointer(ctx, 1);
// Here is  something like "duk_to_pointer(ctx, 0)"
// i mean, use a kind of "duk_to_object(ctx, 1)" but getting the object
}

duk_to_pointer, duk_to_number they give back something but duk_to_object not.
Is there sample code, or explanation in how to solve this problem?
Thank you. :-)

**Comment by svaarala** [comment]
The object is already on the value stack - there's no way to "get an object" as such from C code, because there's no easy way to represent an object as a C value.

Instead, you can read and write properties of the object, e.g.:

```
duk_get_prop_string(ctx, 0, "xCoord");
printf("x-coordinate is: %d\n", (int) duk_to_int(ctx, -1));
duk_pop(ctx);
```

**Comment by BorisFaz** [comment]
Ok. I'll try. Thank you!
