### ISSUE TITLE
Question: what is obj_index

### ISSUE THREAD

**Issue by diorahman** [svaarala/duktape#418]
I'm a newbie in this duktape world. Still confused with `obj_index`. What is this `obj_index` and its minus sign?

e.g. 

```
duk_get_prop_string(ctx, -3, "propertyName");
```

Thanks!

**Comment by fatcerberus** [comment]
Duktape's API revolves around a pushdown stack called the "value stack".  `obj_index` is an index into that stack.  It doesn't have to be negative--a positive index is legal and is absolute, starting from the bottom of the stack.  Usually negative indices are more useful--`-1` means "the value on top", `-2` is the value below that, etc.

By way of example:
```c
duk_push_int(ctx, 812);
int x = duk_get_int(ctx, -1);
printf("%d", x);  // 812
```

Incidentally, this is very similar to the way Lua's API is set up.

**Comment by diorahman** [comment]
Thanks!
