### ISSUE TITLE
Add a Detach notify to debugger protocol

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#423]
It is currently impossible to differentiate between a deliberate target-initiated detach, as by closing the application window, versus an unexpected disconnection.  In both cases the client side will only see that the remote socket was closed, with no indication of why.

To solve this, I propose an additional Detach notify, which is sent just prior to detachment, either because the target called `duk_debugger_detach()` or the heap is destroyed.  If the socket is closed without receiving the notify, the client can then safely assume the connection was lost and try to reconnect.

**Comment by svaarala** [comment]
Sounds good to me, it could include a string message to explain the detach too.

**Comment by fatcerberus** [comment]
Unless there will be a hundred different possible detach scenarios, I think it might be simpler to just include an integer constant specifying the reason, like in a Status notify.

**Comment by svaarala** [comment]
That's true. We can add a string message later if that becomes relevant, e.g. if Duktape tries to send a Detach notify on a parse error and could then try to explain the error briefly in the message ("invalid initial byte 0xNN").

**Comment by fatcerberus** [comment]
Hm, you're right that we might want to describe error conditions, so they can be displayed by the client.  Here might be a good format:

`NFY <int: 6> <int: 0/1 iserror> [<str: msg>]`

If the first argument `iserror` is 0, it's a normal, expected detach so no message is needed or present.  Otherwise `iserror` is 1 and `msg` describes the error condition.

**Comment by fatcerberus** [comment]
Just posted a pull for this, #430.
