### ISSUE TITLE
Use type/context specific error throw macros to reduce footprint

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#456]
For example:

```
DUK_ERROR(thr, DUK_ERR_API_ERROR, "api error xyz");
```

Can be converted to:

```
DUK_ERROR_API(thr, "api error xyz");
```

This requires a helper which makes the actual error throw call, but saves one argument from the call site. Because there are a lot of error call sites, this approach can save some footprint quite easily. The call sites will be smaller, which is also good for instruction cache performance as they're mostly cold code.

See discussion in https://github.com/svaarala/duktape/pull/441.

**Comment by fatcerberus** [comment]
This particular issue intrigued me, it's a great example of thinking outside the box I think.  I never would have thought to reduce code size by shaving arguments off of a commonly-called function , but now that I see it it makes a lot of sense.  It's even an optimization that I don't think any compiler is capable of doing automatically.
