### ISSUE TITLE
Misc issues for 1.5.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#481]
- [x] Improve Travis run; assertions enabled? => covered by separate testrunner now
- [x] Build target or script to generate the index page footprint and startup RAM figures based on config YAML files (now done manually which is hard to reproduce and opaque) => covered by testrunner

**Comment by svaarala** [comment]
I'm pruning the in-progress issues for 1.5.0 to ensure the release is done during April.

**Comment by fatcerberus** [comment]
I'm not really sure the checklist above can be completed in 7 days... ;-)

**Comment by svaarala** [comment]
That's why I'm shuffling issues :)

**Comment by svaarala** [comment]
Bullet points not covered in 1.5.0 are now separate issues or pulls.
