### ISSUE TITLE
Simple steps to generate distribution files on Windows

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#488]
Hi, I write this guide to generate distribution files on Windows quickly from Git repository.

1. Install CygWin/CygWin64 from https://cygwin.com/install.html

   *IMPORTANT*: Include BC utility, Python 2.7 and Yaml libraries for Python optional components when installing.

2. Install JAVA 7 or later

3. Download DukTape from GIT repository

4. Download Google's Closure Compiler from https://developers.google.com/closure/compiler/ and copy "compiler.jar" in your local DukTape's folder.

5. Open a command prompt console and go to your local DukTape's folder using:

    `CD your-duktape-git-local-copy-folder`

6. Add CygWin and Git to the PATH environment variable:

   `SET PATH=path-to-cygwin-bin-folder;path-to-git-bin-folder;%PATH%`

   i.e.:  `SET PATH=C:\Dev\CygWin64\bin;C:\Dev\Git\bin;%PATH%`

7. Launch CygWin's Mini TTY by typing:

    `mintty`

8. At last, run the make distributable script in the MiniTTY console:

   `util/make_dist.sh`

Regards,
Mauro.

**Comment by svaarala** [comment]
@mxmauro Master now has a much easier Windows dist process now:

https://github.com/svaarala/duktape#getting-started-modifying-and-rebuilding-the-distributable

So I'll close the issue :) Let me know if there's something you'd like to add to the current README re: distributing on Windows.

**Comment by mxmauro** [comment]
Yes, I saw the new python files. Cool!

**Comment by collvey** [comment]
Is there an updated version to generate distribution files on Windows?

**Comment by mxmauro** [comment]
Hi @collvey, run the python script with desired options and you will get a .c and a header file.

**Comment by svaarala** [comment]
@collvey There's Python2 tooling for disting in master at present. It will be replaced by Node.js based tooling, removing all dependencies on Python2/Python3 for configure/dist (and also for other things).

Some of the Node.js tooling has been merged into master but isn't active yet. It's likely to change in some ways, and may be buggy, but it can be currently tested using for example:
```
$ make -C src-tools
$ nodejs src-tools/index.js dist -o testdist
```

This produces a distributable like util/dist.py does. (I haven't tested it yet on Windows however.)
