### ISSUE TITLE
Check a few NetSurf diffs

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#493]
Volatility of `idx_func`:

- http://source.netsurf-browser.org/netsurf.git/commit/?id=9d097b37f632327cb84d10aee89d9cef390fd37d

Static analysis disabled:

- http://source.netsurf-browser.org/netsurf.git/commit/?id=de637fa571937a5823a8a9c0d07a620d3d5e7820

One approach for static analysis would be to disable static analysis unless that's explicitly requested for Duktape. The best solution would be to fix all static analysis errors, but that's not always possible because the analyzer doesn't always know what internal guarantees are in place.

Tasks:

- [x] Add volatile back to idx_func to fix initial problem - #497
- [x] Figure out why volatile is needed (it shouldn't because idx_func is written before setjmp() and only read after setjmp()) - if it's compiler specific, restrict the fix to a specific compiler
- [x] Static analysis decision

**Comment by fatcerberus** [comment]
That second one (clang static analysis), I'm going to guess Duktape sets off a lot of alarms in the analyzer due to how tight and optimized it is, probably nothing to worry about.  The volatile thing is definitely worth looking into though.

**Comment by svaarala** [comment]
The issue here is more if that disabling should be merged or not - I run scan-build for every release and there are no serious issues.

**Comment by svaarala** [comment]
Disabling compilation to avoid static analysis issues seems awkward to do, so not done here.
