### ISSUE TITLE
Trailing ';' in the duk_push_buffer macro

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#500]
The `duk_push_buffer` has a trailing ';' in its definition:

    #define duk_push_buffer(ctx,size,dynamic) \
    	duk_push_buffer_raw((ctx), (size), (dynamic) ? DUK_BUF_FLAG_DYNAMIC : 0);

causing my automatically instrumented code to fail to compile:

    (s7_Dd.li=s7_DL+31981,duk_push_buffer(s7_v1K2KTC,s7_v1K2KUJ,0))

It should be:

    #define duk_push_buffer(ctx,size,dynamic) \
    	duk_push_buffer_raw((ctx), (size), (dynamic) ? DUK_BUF_FLAG_DYNAMIC : 0)

**Comment by svaarala** [comment]
Good catch, thanks! I checked the public header and this seems to be the only offender.

I'll fix this is also in 1.3.2.

:christmas_tree:

**Comment by svaarala** [comment]
Fixed in master.

**Comment by HouQiming** [comment]
Thanks for the quick fix!

Qiming
