### ISSUE TITLE
Declaration of duk_context : Compiling new version problems 

### ISSUE THREAD

**Issue by BorisFaz** [svaarala/duktape#511]
Hello everybody and happy new year.
I'm trying to use the last version of duktape. I'm using VS2013
I'm having a (stupid) issue and with the duk_context declaration
"typedef struct duk_hthread duk_context"
error C2371: 'duk_context' : redefinition; different basic types

replacing with the old one
"typedef void duk_context;"

Everything works fine. Maybe the issue is not an issue but would like to know more about this.
Thank you

**Comment by fatcerberus** [comment]
This is weird... I'm using VS2015 and have never seen this error.  Are you sure your duktape.h and duktape.c match?  Maybe you have an outdated header, that's the only thing I can think of that would cause this.

**Comment by BorisFaz** [comment]
Yes. Solved. Stupid forward declaration. My fault. Excuse me . Thank you very much 
fatcerberus.
