### ISSUE TITLE
Change duk_(p)eval() .fileName default from __FILE__ to "eval"

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#516]
Using `__FILE__` for the eval source .fileName leads to file/line combinations in stack traces where the filename is from the C file (`__FILE__`) but the line number is from the eval'd Ecmascript code, which is quite misleading.

If this default is not appropriate, calling code can even now use `duk_(p)compile()` + `duk_(p)eval()` to provide an explicit filename.

**Comment by svaarala** [comment]
To elaborate a bit, consider the following call site:

```
/* test.c, eval is on line test.c:123 */
duk_peval_string(ctx, "\n\naiee");  /* ReferenceError on line 3 */
```

As things are now (up to 1.4.0) the temporary function compiled for the eval input has `.fileName` set to `__FILE__` of the call site, i.e. `test.c` here. As a result, the stack trace for the ReferenceError indicates the error occurred on file/line `test.c:3` which is quite misleading.

If the `.fileName` for the eval code were `eval` the error would be blamed on `eval:3` which is correct but doesn't identify the C file with the eval call site.

The `.fileName` could also be set to:

- `test.c/eval` so that stack trace would blame `test.c/eval:3`
- `test.c:123/eval` so that stack trace would blame `test.c:123/eval:3`

**Comment by fatcerberus** [comment]
I'm confused... I know with the changes in 1.4 Duktape walks the callstack looking for an entry with a valid filename, but I was under the impression that it always used the line number from the same stack frame as the filename.  So if the duk_eval() code has no filename, the error should be correctly blamed on `test.c:123` and line 3 should never come into the equation?

**Comment by svaarala** [comment]
`duk_eval()` creates a temporary function whose filename is `__FILE__` of the `duk_eval()` call site.

**Comment by svaarala** [comment]
Also note that `test.c:123`, the call site of `duk_eval()`, is not in the call stack at all so it never directly enters into the file/line decision.

**Comment by svaarala** [comment]
Eval code will now get .fileName "eval" and other function code compiled from a user string gets .fileName "input" so that file/line combinations will now make more sense, see #644.
