### ISSUE TITLE
Problem with function "arguments" array

### ISSUE THREAD

**Issue by JohnMurga** [svaarala/duktape#552]
Can reproduced doing :
```javascript
(function() {
    return JSON.stringify(arguments)
})("a","b");
```
Incorrectly returns : `{"0":"a","1":"b"}` (*Object keyed by strings*)
This might be OK if it was `{0: "a", 1: "b"}`

But ideally it should be that same as :
`JSON.stringify(["a","b"])` which correctly returns `["a","b"]` (Array)

**Comment by svaarala** [comment]
As far as I know that is the correct behavior. The `Arguments` object is not an Ecmascript array:

- http://www.ecma-international.org/ecma-262/5.1/#sec-10.6

**Comment by svaarala** [comment]
V8 behavior is the same:

```
> (function() { return JSON.stringify(arguments); })("a", "b");
'{"0":"a","1":"b"}'
```

**Comment by fatcerberus** [comment]
V8 (Node.js) output:
```
> (function() { return JSON.stringify(arguments)})("a","b");
'{"0":"a","1":"b"}'
>
```

So Duktape's behavior is likely correct.

**Comment by fatcerberus** [comment]
@svaarala Haha, you beat me to it. :)

**Comment by svaarala** [comment]
@JohnMurga `Array.prototype.slice()` is one way to convert the arguments object into an array:

```
duk> (function() { return JSON.stringify(Array.prototype.slice.call(arguments)); })("a", "b");
= ["a","b"]
```

**Comment by JohnMurga** [comment]
Sorry about that, and thanks for the clarification :+1:

**Comment by svaarala** [comment]
No problem, arguments object is indeed a bit mysterious :)
