### ISSUE TITLE
Debugging support

### ISSUE THREAD

**Issue by itay** [svaarala/duktape#56]
We're looking into integration Duktape, and one thing we want to make sure we have is debugging support, at least in the future. 

At a basic level, if there were even just mechanisms to set breakpoints, that would be sufficient. We would just the existing facilities to "inspect" the current stack, etc.

Is this something that is on the roadmap, or that you would be agreeable to if somebody added it?

**Comment by Acconut** [comment]
I will just dive in to show my interest in this feature. As @itay I also prefer the second solution allowing you to write remote debuggers and custom GUI as long as you can expose the protocol over a network. But that's what you meant when speaking about a protocol, didn't you?

Anyway, keep the good work up and thanks for this project. :+1:

**Comment by svaarala** [comment]
Yes, the solution will be protocol oriented. The intent is to include a simple debugger GUI with Duktape so that everyone has access to it out of the box (and it can also be used to debug a custom target). But you can also write your own custom GUI which makes more sense when doing tighter integration. Stay tuned :-)

**Comment by svaarala** [comment]
First merge is now in:

- https://github.com/svaarala/duktape/commit/35a94045436e45fbc9748b2c0581680be82f3159

See the following to get started:

- https://github.com/svaarala/duktape/blob/master/debugger/README.rst
- https://github.com/svaarala/duktape/blob/master/doc/debugger.rst

The functionality in this merge is a baseline which includes all the major pieces of the debugger solution. There are a lot of small issues and bugs to round out before Duktape 1.2 release.

**Comment by Acconut** [comment]
Oh god, that's awesome! I expected this to be released in less than a year and now you push the first pieces a day after I started to look into duktape. I will test this as soon as possible. :)

**Comment by svaarala** [comment]
@Acconut Let me know how it works out :) It's quite barebones still. For instance, the web UI is pretty much a placeholder and will need to be reworked (proper syntax highlighting, etc).

**Comment by JoshEngebretson** [comment]
I am really looking forward to setting aside some time to dig into this, wow, just WOW! 
:+1:  :+1:  :+1:

**Comment by svaarala** [comment]
I'm closing this one now because there's a minimal debugger in master now. Fixes and feature changes in separate issues.
