### ISSUE TITLE
Add ability to send and receive custom debug messages

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#563]
This could be relatively simple, implemented as a custom callback on the target which is called by Duktape when a specific command is received.  Likewise, an API could be added so that the target can send custom messages back to the client.

For example, say the number for the Custom command is 812, the client could send `REQ 812 "foobar"` and whenever Duktape sees a message beginning `REQ 812`, it calls a callback implemented on the target passing the string "foobar" to it.  That callback could then return its own string to be sent back as a reply (REP).

This setup would be very powerful for very little footprint impact.

**Comment by svaarala** [comment]
Some related future work notes: https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#application-specific-messages

The reason I didn't implement this early is that I'd like to avoid adding small features like this incrementally, then realize that plain string messages are not enough after all, and end up supporting overlapping APIs.

So basically the question is: will it be enough to e.g. pass strings back and forth? Technically the answer is "obviously" yes: user code can pack arbitrary values into strings and that would certainly be an easy API to implement. However, it might not be a convenient API if you can't e.g. read/write values on the Duktape stack with typing intact.

**Comment by svaarala** [comment]
I think this feature and the ability to do heap walking for structured values would be a nice "feature pack" for the debugger :)

**Comment by fatcerberus** [comment]
Hm, I feel like I must have read that future work note at some point without realizing it, my idea is almost exactly what is described there.  The only thing different is that you included the concept of named messages, which I didn't think of.

Anyway, I personally don't see a big issue with not being able to pass typed values.  As you note in `debugger.rst`, these messages are usually out of band - not directly related to JavaScript execution.  That said, I'm not shortsighted enough to dismiss the possibility _somebody_ would need this functionality.  So if that were needed, the API could be changed so that you push everything you want to send onto the valstack:

```c
duk_push_int(ctx, 9001);
duk_push_string(ctx, "cats");
duk_debug_oob_send(ctx, /*name*/ "HungryCow", /*n_values*/ 2);
```

Likewise, the callback for out of band messages would get as a parameter the name of the message and the number of values received and would read them from the valstack.  Of course we'd have to make an exception here to the "no calling into Duktape during debug processing" rule. :)

I'm liking this idea now: It exposes the full power of the dvalue protocol to user code for very little increase in complexity.

**Comment by fatcerberus** [comment]
A potential issue is that adding an additional callback is a breaking change with the current API - all the callbacks are provided to `duk_debugger_attach()`.  We could add a function to set the callback after attach, but that would of course be inconsistent with the present design.

**Comment by svaarala** [comment]
I don't think there's a clean compatible way to introduce this; adding a separate "set callback" API call would be awkward and would then be removed later. Still a possibility of course.

One thing I've been thinking earlier is that the detached callback could be generalized to an "incoming event" callback which could handle both internal causes (detach etc) but also actual incoming notify/request messages. I'm not sure if that would be more or less intuitive than having two separate callbacks. In any case, there are other internal causes than detach where some form of "FYI, this happened" might be useful.

**Comment by fatcerberus** [comment]
Appropriating the detach callback could work, of course there's also the issue that the callbacks don't get a `duk_context` pointer, making valstack access awkward.

**Comment by svaarala** [comment]
Yes, and since reattaching from detached callback is now allowed, it should have a "ctx" pointer already. Originally the detached callback was not intended to call into Duktape either which is why it doesn't have that pointer now.

**Comment by fatcerberus** [comment]
If you're curious why I'm asking for this now: In the minisphere GDK, source mapping is handled directly by minisphere (the target).  This is so that whether the game being debugged is a compressed SPK package or a loose collection of files in a directory, that is completely transparent to the client without having to duplicate the SPK unpacking code in the debugger.

The trouble is that the engine has no (easy) way to report the contents of the JSON source map back to the client.  So far I've made do by having minisphere read the source map and pass the source filename to Duktape's compiler instead of the name stored in the game package.  In this way Duktape gives a filename relative to the original source tree and the client is none the wiser.

However, now I need the debugger to access additional information from the source map, specifically the absolute path for the original source tree.  And I have no way to get that information from minisphere to SSJ without, as detailed in `debugger.rst`, either opening a second TCP link or implementing some additional framing to support out-of-band data.  Both of these are possible, but a more elegant solution would be preferable. :)

**Comment by svaarala** [comment]
Sounds reasonable :) What I'd like to use custom messages for is e.g. memory pool statistics snapshots.

If the protocol had a mechanism for string namespaced custom messages for that, a debug client could pick up on those and display the pool statistics graphically. Another debug client which didn't support that custom message could still show the string data of the message which is better than not showing at all - which would be the case if custom messages were sent out of band.

**Comment by fatcerberus** [comment]
By the way here's a picture of my debugger in action.  It's heavily inspired by GDB:

![SSJ](http://i.imgur.com/yku8vRH.png)

**Comment by svaarala** [comment]
Ok if I link to this from the Wiki? Also, are there separate console and GUI debuggers in Minisphere now? :)

**Comment by fatcerberus** [comment]
Sure, go right ahead!

To your question, yes, there is a separate console and GUI debugger.  The GUI debugger is Windows-only though because it's written in .NET and (for whatever reason) Mono won't run it.  That was the impetus for doing this.

In the future I'd like to rewrite the GUI debugger so that it uses SSJ under the hood.  That would allow me to only need to maintain one debug client codebase.  For now I have to do double work...

**Comment by fatcerberus** [comment]
For now I came up with a hacky way to get what I want: minisphere will store the source map and other debugging data so that it's reachable through the global object.  Upon attaching, the client (SSJ) can send Eval commands to pull that data over.  Not a very elegant solution, but should work for now.

**Comment by harold-b** [comment]
I think a reasonable way to add custom commands is simply to add a middle-man at the transport level on the debug target. This proxy could parse dvalues into whole messages and decide if it want's to consume it itself ( i.e. custom message type ), or pass it on to duktape. In this way you keep the debugger API lightweight and we could customize to our heart's content at the transport level. 

Of course, with this approach you could even decide to change the protocol completely if you so desired.

**Comment by fatcerberus** [comment]
That's what I was referring to above with this:

> implementing some additional framing to support out-of-band data

That's even mentioned in the debugger documentation.  However Duktape already has a full dvalue parser built in--why not leverage that rather than adding a whole new protocol layer? :-)

@svaarala I may look into doing something with this after we're finished with the heap walking.  It would be quite useful for my use with minisphere.

**Comment by svaarala** [comment]
I think this is now covered by #596 so closing this one.
