### ISSUE TITLE
Stack dump formatting and enhancements

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#588]
The current stack dump format seems a bit messy for machine consumption, with things like "anon", "eval" sometimes appearing before the file name / line and things like "preventsyield" appearing after.

Is it possible to standardize things a bit so that one can parse the dumps using a simple regexp? A node.js-compatible format would be great :)

Also, is it possible to set a module file name in the dump to something other than the string specified in 'require'?

**Comment by svaarala** [comment]
The current format for actual callstack entries is more or less:

    <func name> <filename | filename:line> [<flag>+]

This should be possible to parse using a regexp if one wanted to, though there are no guarantees of the format not changing without warning. The "eval" and "anon" are function names and always appear in the first position, and "preventsyield" etc are flag names which are appended.

One exception to this format are stack trace lines which are not emitted based on actual callstack entries: if the error has a related native file/line (e.g. a Duktape internal call site) that is simply represented as:

    <file>:<line>

For example:

    duk_api_stack.c:1234

Did you have some specific changes or suggestion in mind?

**Comment by HouQiming** [comment]
This is an example dump right now:

```
Error: test
	anon res/lib/code_editor:4356 preventsyield
	anon  native strict preventsyield
	anon res/lib/code_editor:1341
	anon gui2d/ui:1818
	anon res/main.js:672
	eval res/main.js:674 preventsyield
```

From the point of a text editor, I would prefer something like this:

```
Error: test
	at anon (res/lib/code_editor:4356) preventsyield
	at anon () native strict preventsyield
	at anon (res/lib/code_editor:1341)
	at anon (gui2d/ui:1818)
	at anon (res/main.js:672)
	at eval (res/main.js:674) preventsyield
	at somewhere (duk_api_stack.c:1234) native strict preventyield
```

It should start with some identifiable string ("at ") so that the regexp is less likely to produce bogus matches from ordinary program output. Native errors should have file names in the same place as JS errors.

Thanks!

**Comment by svaarala** [comment]
Something like that is doable and would be more user friendly. The stack trace formatting is very well localized (a single function) so it's easy to change as needed.
