### ISSUE TITLE
Proposal for new require system

### ISSUE THREAD

**Issue by creationix** [svaarala/duktape#60]
I've designed a new require system that duktape could provide that would be flexible for my needs and enough to allow the user to implement a node.js or lua style require system in full.

I don't know enough about duktape performance to know if using prototypes of closures is preferred.  This sample uses prototypes since that's way faster in V8 where most my experience is and I _think_ it would use less ram in duktape which I know is a big goal.

``` js
Module.cache = {};

function Module(id) {
  var cached = Module.cache[id];
  if (cached) { return cached; }
  Module.cache[id] = this;
  this.exports = {};
  this.id = id;
  this.load();
}

Module.prototype.require = function (id) {
  return (new Module(this.resolve(id))).exports;
};

Module.prototype.resolve = function () {
  throw new Error("Please replace Module.prototype.resolve(id) with your own implementation.");
};

Module.prototype.load = function () {
  throw new Error("Please replace Module.prototype.load() with your own implementation.");
};
```

A sample concrete integration with this could be a simple loader that resolves IDs starting with "." as relative to caller's directory and leaves others unchanged.  It's loader simply loads the files from disk and evaluates them using common-js semantics.

``` js
// Sample usage:
// Assume `readFile` and `pathJoin` are provided by user code not shown here`.
// function pathJoin(part1, part2, ...) {} -> path
// function readFile(path) {} -> buffer


// Simple resolve that maps relative requires relative to caller
// and leaves module requires as-is.
Module.prototype.resolve = function resolve(id) {
  if (id[0] === '.') {
    return pathJoin(this.id, '..', id);
  }
  return id;
};

// Simple loader that loads from disk and evals using new Function
Module.prototype.load = function () {
  var code = readFile(this.id);
  // Like `new Function`, but also allows setting filename for stack traces
  var fn = compile(code, this.id, "require", "module", "exports");
  var ret = fn(this.require.bind(this), this, this.exports);
  if (ret !== undefined) { this.exports = ret; }
};
```

The only thing I can't prototype from pure JS is the `compile` function.  The `new Function` builtin is close, but it doesn't provide a way to specify the filename for use in stack traces.  Also some people might prefer modules to each have their own global context so a new API would be required for that as well.  Personally I prefer when each module shares the same global, but has a new unique local scope (which is why I say `new Function` is very close to what I want).

I'm not sure the best way to implement this.  I looked at the source to `new Function` and it uses some APIs not available to me such as `duk_js_push_closure`.

Also if it makes things easier, I don't need a two step process where I create a function with named arguments and then call that function.  Another interface that would work is the ability to eval some code, but inject a few named values into the lexical environment.  Also I prefer the semantics of DUK_COMPILE_FUNCTION.  I don't want auto-return.

**Comment by fatcerberus** [comment]
Any progress on this front?  I wanted to design a package-based CJS system where modules can have different versions of the same dependency and I refer to the package to load the correct version, but since Duktape pre-resolves `require()` paths there's no way to know which package the call came from.  This system would greatly simplify that scenario.

Honestly it might be enough just to add an extra parameter to `Duktape.modSearch` specifying the (pre-resolved) parent ID, splitting the functionality into 2-3 callbacks seems like overengineering to me...

**Comment by svaarala** [comment]
@fatcerberus I'm closing issues for 1.3 release at the moment (though I'm on a summer vacation right now so not very quick :). After that it's time to figure out what backwards incompatible pending changes would be most appropriate for a 2.0 release.

Module loading is one of these issues, and I'd like to ensure that if there's an incompatible change, it's as useful as possible. Access to the requested path is one issue, but there are also others. In particular, I'd like to ensure that the built-in module system in 2.0 would align as well as possible with ES6 modules. (If ES6 didn't have modules, I'd consider making the whole module framework external in 2.0.)

Anyway, it'd certainly be possible to extend modSearch() arguments in a compatible way in 1.3, if there's a clear use case and benefit from doing that before 2.0. I'd just like to avoid fixing one specific issue and creating new ones :-)

**Comment by fatcerberus** [comment]
Passing a second argument to modSearch() containing the resolved ID of the calling module would work for my use case, at least.  Basically I just have to have a way to know which module is making the request so that I can refer back to the right package when resolving the dependency.

I imagine this wouldn't be too difficult, since you already have to track the parent module anyway to resolve relative paths. :wink:

**Comment by svaarala** [comment]
Note that module caching would still happen using the resolved, normalized path. Would this be an issue in your use case, i.e. is it possible two relative paths resolve to a different module but still have the same normalized path?

**Comment by fatcerberus** [comment]
I'm... not sure.  Basically my use case is this:

```javascript
// initial module inclusion, outside of any modules
// require() looks up the package, say cowlib.json, which describes any dependencies and their versions
var cowlib = require("cowlib");
// do stuff with cowlib
```

Now, let's say cowlib.json (the package descriptor) says it required piglib v8.1.2.  Somewhere in cowlib is this require:
```
var piglib = require("piglib");
// do stuff with piglib
```

When piglib is required above, `Duktape.modSearch` hypothetically gets passed two arguments: The first being the resolved ID ("piglib"), and the second being the resolved parent ID "cowlib".  The module search handler can now refer back to cowlib.json, find out that we need piglib v8.1.2 and resolve the ID to, say, `piglib/v8.1.2`.  Or even simpler, just concat the paths and return `cowlib/piglib`.  Either way we get the correct module without having to share potentially conflicting dependencies.

**Comment by fatcerberus** [comment]
Hm, on second thought, the caching may in fact be an issue.  In my case above, Duktape would end up caching the module as "piglib", so even if another module requires a different version later, it'll give me the original one back.

I see why the two functions are necessary here now.  My solution above actually breaks the CommonJS spec and I end up invoking a classic case of undefined behavior. :-)

So I give--I'll wait for 2.0.  I can always write my own `require()` in the meantime.

**Comment by creationix** [comment]
@fatcerberus I have an implementstion of the 2.0 proposal as a polyfill on 1.0 in my dukluv repo.  You're welcome to rip it out and use it in your project.

**Comment by akheron** [comment]
FWIW, here are updated links to the polyfill in the dukluv repo (the ones referring to master above don't point to the correct lines anymore):

https://github.com/creationix/dukluv/blob/638d8fe6/src/main.c#L6-L98
https://github.com/creationix/dukluv/blob/638d8fe6/src/main.c#L146-L151
https://github.com/creationix/dukluv/blob/638d8fe6/test-require.js#L3-L17

**Comment by akheron** [comment]
The polyfill works great for me :+1:

**Comment by svaarala** [comment]
A few features added / discussed before this was opened:

- `module.exports` is supported now, and it allows (1) Ecmascript modules to return e.g. a Function, and (2) also native modules can return a function because `module.exports` can be overwritten in modSearch() directly.
- Under discussion: .fileName property for module function, possibly through `module.fileName` #637

**Comment by svaarala** [comment]
This specific use case would be nice to support (and document the support in Wiki):

- https://github.com/svaarala/duktape/issues/662

It's workable in Duktape 1.x by forcibly overriding `require.id` for the submodule require() function in modSearch().

**Comment by svaarala** [comment]
Another small improvement: Duktape.modLoaded[] could be renamed `require.cache` to match Node.js behavior.

**Comment by svaarala** [comment]
Multiple module loaders per global context; something to consider: https://github.com/svaarala/duktape/issues/696#issuecomment-214069006

**Comment by svaarala** [comment]
Some discussion about adding API support to track "current module" context for easier implementation of `require()` sub-module resolution: https://github.com/svaarala/duktape/issues/696#issuecomment-214075659

**Comment by svaarala** [comment]
There's now a more flexible Node.js loader in master extras. I'm closing this as module loading is now outside Duktape core functionality.
