### ISSUE TITLE
GLFW binding for Duktape

### ISSUE THREAD

**Issue by lzubiaur** [svaarala/duktape#621]
Hi, I made [GLFW](http://www.glfw.org/) bindings for duktape available [here](https://github.com/lzubiaur/duk-glfw).
Regards,
Laurent

**Comment by svaarala** [comment]
I added a pull for duktape-wiki to add your bindings to the project list if you wanted to do that.

- https://github.com/svaarala/duktape-wiki/pull/92

**Comment by lzubiaur** [comment]
Yes sure. Thank you!

**Comment by svaarala** [comment]
Those bindings look like fun to experiment with :)

**Comment by lzubiaur** [comment]
Yes! Duktape is great and really fun when it comes to bind 3rd party libs. A lot easier than Lua (personally).
