### ISSUE TITLE
How to 'name' an object using duktape  

### ISSUE THREAD

**Issue by YukiPaul** [svaarala/duktape#626]
Forgive me if the question is stupid, I am just a beginner to duktape.

I am wondering how to 'name' an object using duktape so I can access this object in duk_eval call.
For example, first I create an object and add some properties to it:

```
duk_idx_t obj_idx;
obj_idx = duk_push_object(ctx);
duk_push_string(ctx,"my_name");
duk_put_prop_string(ctx, obj_idx, "name");
duk_push_string(ctx,"my_val");
duk_put_prop_string(ctx, obj_idx, "value");
```
so now I have an object in the value stack, which has two properties: "name" and "value". 
But then I want to access this object by calling 
duk_eval_string(ctx,"doSomething(this_object);");  
if I can name the object I created in the value stack, I can easily access it in duk_eval_string(). For example, if I can give the object a name "x", then I can call duk_eval_string(ctx,"do something(x)"). I read the document but hardly find a way to do this. Could you please help me with that? Or is there any alternative solution to this problem?

Thanks in advance.

**Comment by svaarala** [comment]
One simple way is to assign the value you created into the global object using `duk_put_global_string()`. It will then be visible to the eval code using that name. This is similar to doing:

    var obj = { name: 'my object', value: 123 };
    eval('print(obj.name)');  // eval sees 'obj'

Values on the value stack are not directly visible to eval code.

If using a global binding for the value is not needed, i.e. you just want to pass a created value to eval code without assigning it anywhere, you can do something like:

    /* Eval a function which is left on the value stack. */
    duk_eval_string(ctx, "(function (val) { /* do something with val */ })");

    /* Create and initialize the object. */
    duk_push_object(ctx);
    /* ... */

    /* At this point value stack has: [ func obj ] */
    duk_call(ctx, 1);  /* call func(obj); */
    duk_pop(ctx);  /* remove result */

I'm not sure from your example whether you really want to do something in the eval code or simply want to call a function with the object as an argument. For the latter case this would simpler than above:

    /* Look up the function from the global object */
    duk_get_global_string(ctx, "doSomething");

    /* Create and initialize the object. */
    duk_push_object(ctx);
    /* ... */

    /* At this point value stack has: [ func obj ] */
    duk_call(ctx, 1);  /* call func(obj); */
    duk_pop(ctx);  /* remove result */

**Comment by YukiPaul** [comment]
Thank you very much for answering my question so quickly. 

Actually my situation is something like this:
First I need to read in a script file by calling:
`duk_eval_file(ctx,"myFile.js");`
Then I want to initialize an object 'f_m' by calling the constructor function 'FiledManager()':
```
/*FieldManager() is defined in myFile.js*/
duk_eval_string(ctx,"var f_m = new FiledManager();");
```
Then I do the followings:
```
duk_idx_t obj_idx;
obj_idx = duk_push_object(ctx);
duk_push_string(ctx,"my_name");
duk_put_prop_string(ctx, obj_idx, "name");
duk_push_string(ctx,"my_val");
duk_put_prop_string(ctx, obj_idx, "value");
```
Finally I want to call:
```
/*addFiled() is a member function defined in FieldManager()*/
duk_eval_string(ctx,"f_m.addField(this_object)");
```

**Comment by svaarala** [comment]
There's no direct way to pass arguments to a plain eval string, but you can use the following pattern if you want to use eval:

```c
/* Create argument object. */
duk_idx_t obj_idx;
duk_push_object(ctx);
/* ... */

/* Create an anonymous function which will accept the object as an argument. */
duk_eval_string(ctx, "(function (obj) { f_m.addField(obj); })");

/* Call the anonymous function. */
duk_dup(ctx, obj_idx);  /* stack here: [ ... obj func obj ] */
duk_call(ctx, 1);       /* stack here: [ ... obj res ] */
duk_pop_2(ctx);         /* ignore call result, pop object too */
```

**Comment by YukiPaul** [comment]
Thanks for your help. This method can definitely solve my problem. I have been using `duk_put_global_string()` that you told me a month ago which also works. I think this question has been solved so feel free to close it.

**Comment by svaarala** [comment]
Good to hear :)
