### ISSUE TITLE
Return a native function as modSearch exports?

### ISSUE THREAD

**Issue by sgmesservey** [svaarala/duktape#628]
I've hit a snag following the conventions for require/modSearch,
in that I can't find a way to return a native function.
Say I want to implement a filesystem wrapper.
It would look like this:
```Javascript
var File = require("File");
var myfile = new File("foo.bar","r");
```
The problem is, I see no easy way to return a native/C function
from Duktape.modSearch.
Perhaps Duktape could detect when returning a function, and have
that function replace *exports*, similar to when it detects a string is
returned.

**Comment by svaarala** [comment]
I added a wiki issue to explain how to do this in detail: you should be able to just replace `module.exports` with a function in modSearch().

As a pure Ecmascript example, here's how you'd return an Ecmascript function from modSearch:

```js
Duktape.modSearch = function (id, require, exports, module) {
    // ignore 'id' in this example
    module.exports = function MyConstructor(name) {
        this.name = name;
    };
    return; // no source
};

var MyFunc = require('dummy');
print(typeof MyFunc);  // prints function
var obj = new MyFunc('myname');
print(obj.name);  // prints myname
```

You can assign a native function to `module.exports` instead. You can also implement the equivalent `modSearch()` function in a Duktape/C function; it also gets the `module` argument and can thus overwrite `module.exports`.

**Comment by svaarala** [comment]
Here's a more detailed explanation (soon to be merged to Wiki master): https://github.com/svaarala/duktape-wiki/blob/1496e67b7546f22e96bb0d3592fd05be59780a81/HowtoModules.md

**Comment by sgmesservey** [comment]
Perfect, thank you!
