### ISSUE TITLE
Having trouble compiling using C++

### ISSUE THREAD

**Issue by mitchblank** [svaarala/duktape#63]
According to the docs, it should be possible to compile duktape.c with a C++ compiler.  I want to do this so that exceptions generated by my callback functions can safely traverse the duktape code.  Maybe I'm doing something wrong, but I'm getting lots of errors trying to build 1.0.1 with g++.

The bulk of the problems have to do with how DUK_LOCAL_DECL causes data types to have extra definitions in the combined C code.  This is because code like the following is legal in C, but not C++:

```C
static const char x[3];
static const char x[3] = { 'a', 'b', 'c' };
```

This trips up dozens of internal statics in duktape.c (duk__date_equivyear just to pick a representative example)  Should I be defining DUK_LOCAL differently when building under C++?

There was one other more straightforward error in duk__to_buffer_raw():

```C
        dst_data = duk_push_buffer(ctx, src_size, buf_dynamic);
```

C++ requires an explicit cast there since duk_push_buffer() returns a void*

(See: #75, #55)

**Comment by svaarala** [comment]
First version of this provided by #499.

In the initial implementation Duktape will use try-catch internally in place of setjmp/longjmp which allows automatic destructors in Duktape/C functions. You can also use C++ exceptions inside your Duktape/C functions but the initial implementation won't support propagating your own exceptions through Duktape (see a lot of discussion about the problems with this above). If you allow an exception to propagate into Duktape code, it will be caught using `catch (...)` and will be converted into a Duktape error (and won't therefore "come out of Duktape" at the other end).
