### ISSUE TITLE
How can I track the line number of the error

### ISSUE THREAD

**Issue by YukiPaul** [svaarala/duktape#645]
I was trying to load some .js files to my program, so I called duk_peval_file() function:

```
 if(duk_peval_file(ctx, "myfile.js") != 0)
 {
 	printf("eval failed: %s\n", duk_safe_to_string(ctx,-1));
 }
```

Since I would like to see the error message if eval failed, I asked the program to print out script errors. Sometimes the error message contains the line number where error occurs, like:

> "eval failed: SyntaxError: parse error (line 42)"

But somethimes the error message just looks like this:

> "eval failed: TypeError: undefined not callable"

Since no line number info is shown, it is difficult for me to figure out where the error occurs. It is possible to use print statements to locate the error but it is very time consuming and inefficient. So I am just wondering if there is way to help me track the line number for any type of error? I appreciate it if you can help me with this. Thank you in advance.

**Comment by svaarala** [comment]
Error objects have a few properties which you can look up:

- `.fileName` and `.lineNumber` will point to a (usually) useful file/line associated with the error cause.
- `.stack` contains a stack trace which provides file/line information for all call stack levels

You can read these properties off the error using `duk_get_prop_string()`:

```c
if (duk_peval_file(ctx, "myfile.js") != 0) {
    duk_get_prop_string(ctx, -1, "stack");
    printf("Eval failed:\n%s\n", duk_safe_to_string(ctx, -1));
    duk_pop(ctx);
}
duk_pop(ctx);
```

In Ecmascript code one would do something like:

```js
try {
    eval("aiee");
} catch (e) {
    print(e.stack);
}
```

**Comment by fatcerberus** [comment]
You need to read the `.fileName` and `.lineNumber` properties of the Error object.  So:

```c
duk_get_prop_string(ctx, -1, "fileName");
duk_get_prop_string(ctx, -2, "lineNumber");
/* ... err fileName lineNumber */
const char* msg = duk_safe_to_string(ctx, -3);
const char* filename = duk_safe_to_string(ctx, -2);
int linenum = duk_to_int(ctx, -1);
/* error handling here */
duk_pop_3(ctx);
```

**Comment by fatcerberus** [comment]
Haha, @svaarala beat me. :)

**Comment by YukiPaul** [comment]
Thanks for your help, @svaarala and @fatcerberus. The problem has been solved, it saves me lots of time.

**Comment by svaarala** [comment]
You're welcome :) I'll add a note to `duk_pcall()` API document because it's quite a basic thing related to protected calls.
