### ISSUE TITLE
Consider removing print() and alert() from core built-ins

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#677]
See comments in: https://github.com/svaarala/duktape/issues/301#issuecomment-209435990

**Comment by fatcerberus** [comment]
I would be fine if these two were removed (or alternatively, hidden behind a config option), FWIW - I have a dedicated `Print()` API in minisphere anyway, and print-to-debug-client can be handled easily with an AppNotify,

**Comment by svaarala** [comment]
That's usually the case: when porting is done, print() and alert() need to be replaced in many cases because writing to stdout/stderr is often the wrong default (and there's no useful default really). They're useful for command line testing - but they can be provided by the command line client in that case.

**Comment by saghul** [comment]
FWIW, I'm building a JS runtime and found these useful... however, adding them myself would be trivial, so I guess I don't care much :-)
