### ISSUE TITLE
Duktape API macro functions should be replaced with (inline) functions 

### ISSUE THREAD

**Issue by jchlapinski** [svaarala/duktape#693]
Let me start by saying this is an awesome project! 
As I am currently embedding it into my project written in Rust, I have encountered a problem that majority of documented API functions are implemented as a macro wrappers. I understand this is done to force inlining for optimal performance, however this makes embedding Duktape trough a FFI calls much more cumbersome. Also there is a possibility clearly stated in the [doc](http://duktape.org/api.html#introduction.5) that all API functions might become macros at some point.

My question is why can those macros be replaced with inline functions written directly in the header files? For example:

In dukconfig.h
```
DUK_EXTERNAL_DECL
duk_context *duk_create_heap(duk_alloc_function alloc_func,
                             duk_realloc_function realloc_func,
                             duk_free_function free_func,
                             void *heap_udata,
                             duk_fatal_function fatal_handler);

#define duk_create_heap_default() \
	duk_create_heap(NULL, NULL, NULL, NULL, NULL)
```
could be written as:
```
DUK_EXTERNAL_DECL
duk_context* duk_create_heap(duk_alloc_function alloc_func,
                             duk_realloc_function realloc_func,
                             duk_free_function free_func,
                             void* heap_udata,
                             duk_fatal_function fatal_handler);

inline
DUK_EXTERNAL_DECL
duk_context* duk_create_heap_default() {
	duk_create_heap(NULL, NULL, NULL, NULL, NULL);
}
```

That way inlining would be left to a compiler discretion, and as far as I know this should work well, and the function "duk_create_heap_default()" would still exist in the lib to be called from some FFI.

Before I do this as PR I would like to ask if there is maybe something I am missing here? Some corner cases where such inlining does not work as expected?

**Comment by fatcerberus** [comment]
It's not just for performance - it's to A) keep footprint down and B) maximize portability.  Duktape is designed to work on all kinds of platforms, including those with as little as 256kb of memory.

That said I don't see how changing all the macros to inline functions buys you anything since they still live in the header.  You wouldn't be able to call them from outside either way.

**Comment by jchlapinski** [comment]
Actually I would. 
If I am not mistaken, a non-inlined version of an "inline" function is still produced by compiler and exist in the library (when compiled as a library), and actual call inlining is decided by the compiler (and/or linker) on case by case basis. 
I have tested my example above and it actually works - I can confirm that I can call duk_create_heap_default() trough FFI from my Rust code.

I understand Your point in A) - however I wonder if the footprint would actually increase. In theory if duktape is used from C/C++ code, compiler would inline most of those functions calls anyway and perhaps eliminate the non-inlined versions from the binary. In case duktape is used trough FFI as in my case, those non-inlined functions need to exist anyway, or there must be some additional proxy API, which is something I am trying to avoid doing.
My understanding of the very reason they introduced the "inline" keyword to the standard at some point was to avoid using macros to achieve almost the same result. From my experience compilers ignore the "inline" keyword MOSTLY in cases where the resulting code would be actually larger.

As for B) - I do not see how macros maximize portability?

**Comment by fatcerberus** [comment]
Regarding portability, `inline` is C99--as mentioned Duktape is designed to work with all kinds of platforms and compilers, even C89 ones!

**Comment by fatcerberus** [comment]
See #87 for some more discussion on this.  Your request is not unprecedented. :)

**Comment by jchlapinski** [comment]
Well then I appologize for creating a new issue. I did search before I added this one, I swear :)

As for C89 conformance - are there actually people still using compilers from those days ;)? But if this is the goal, than I have to respect that.

I am closing this one down, and maybe try to join the other discussion. Thank You!
