### ISSUE TITLE
Is this possible support comment like '#'

### ISSUE THREAD

**Issue by buaabyl** [svaarala/duktape#697]
I wish to embedded duktape as default script engine, work with bash.

Is it possible to support like this:
```javascript
#!/bin/duktape
print("hello world!");
```

I just read file, and strip first line. Maybe it is better to support comment like '#'?

**Comment by svaarala** [comment]
As a first measure you could do that just before loading a source file in the `/bin/duktape` binary.

Adding support for this into Duktape wouldn't be difficult I think. It's somewhat similar to adding HTML comment support in that it's not part of the core standard but still appears quite commonly.

**Comment by svaarala** [comment]
Here's a simple approach using eval:

```c

duk_eval_string(ctx, "(function (src) { return src.replace(/^#.*?$/gm, '// omitted'); })");
duk_push_string(ctx, "...");  /* push source code */
duk_call(ctx, 1 /*nargs*);

/* Source code with hash comments removed now on stack top. */
```

The replacement doesn't disturb line numbers to keep tracebacks useful.

In concrete terms:

```
duk> source = '#!/bin/duktape\nfoo\nbar\n#quux\nbaz\n'
= #!/bin/duktape
foo
bar
#quux
baz

duk> source.replace(/^\#.*?$/gm, '// omitted')
= // omitted
foo
bar
// omitted
baz

```

**Comment by buaabyl** [comment]
Thanks, It is better than strip first line:)
