### ISSUE TITLE
API call to freeze/seal object

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#700]
I would like an API equivalent for `Object.freeze()`.  My use case: I want to freeze the `module.exports` of my native modules but can't do so currently because that value lives only on the valstack.

**Comment by fatcerberus** [comment]
It occurs to me that I can do this as a temporary measure:

```c
/* ... obj */
duk_get_global_string(ctx, "Object");
duk_get_prop_string(ctx, -1, "freeze");
duk_dup(ctx, -3); /* ... 'Object' 'freeze' obj */
duk_call(ctx, 1);  /* ... 'Object' result */
duk_pop_2(ctx);
```

However in light of Duktape supporting native modules perhaps this would still be worth having as a convenience call.

**Comment by svaarala** [comment]
For completeness `Object.seal()` and `Object.freeze()` these related calls are also candidates:

- Object.preventExtensions()
- Object.isSealed()
- Object.isFrozen()
- Object.isExtensible()
