### ISSUE TITLE
Please, add Skookum JS to the list of projects using Duktape

### ISSUE THREAD

**Issue by saghul** [svaarala/duktape#728]
In a happy accident I was planning on releasing a JS runtime I wrote using Duktape today, so I bumped it to 1.5.0 and here it is: https://github.com/saghul/sjs

Can it please get added to the projects list? Thanks a lot!

Btw, Duktape is awesome: easy to use, great design, and fantastic doumentation. I couldn't have done it without Duktape. :heart:

**Comment by svaarala** [comment]
Sure thing :) What would be a good short description for the project?

**Comment by saghul** [comment]
"A *skookum* JavaScript runtime" :-)

**Comment by svaarala** [comment]
Alright, it's there now :)

**Comment by saghul** [comment]
Fantastic, thank you!
