### ISSUE TITLE
Remove file-related API calls

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#734]
File access is a portability issue so the core API shouldn't include calls that deal with files, e.g.:

- `duk_compile_file()`
- `duk_push_string_file()`
- Etc.

Remove these from the public API, but put them into "extras".

All references to `DUK_FPRINTF()` can then be removed and `DUK_FPRINTF`, `DUK_STDOUT`, `DUK_STDERR`, etc can be removed from the config option set.

**Comment by fatcerberus** [comment]
For what it's worth I won't miss these.  minisphere uses a virtualized file system to support transparent packaging so I already need to handle file-related stuff myself anyway.

The file APIs are useful for "getting started" but in any large app I've found them to be inadequate for most use cases.  So extras is definitely the right place for them, I think.

**Comment by svaarala** [comment]
That's my experience too - often file I/O bindings for embedding need some sort of security measures or outright virtualization, or perhaps just logging, so that built-in file I/O is just a risk to be dealt with.

It's useful for getting started, and in fact it'd be useful to have an "extra" providing some very rudimentary getting started style functions like `readFile()` and `writeFile()` in addition to the current file I/O primitives.

**Comment by andoma** [comment]
> minisphere uses a virtualized file system to support transparent packaging so I already need to handle file-related stuff myself anyway.

Exactly the same thing in Movian. Won't miss these either.

**Comment by svaarala** [comment]
Implemented in #788.
