### ISSUE TITLE
Remove Duktape.Buffer, use ArrayBuffer for coercion instead

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#739]
The `Duktape.Buffer` object is unnecessary now that typed array support exists and `ArrayBuffer` can take its place.

Duktape.Buffer has two functions worth keeping:

- A plain buffer coerces to a Duktape.Buffer when coerced using ToObject() coercion. This could be changed to ArrayBuffer. (#864 makes plain buffers behave like (subset) ArrayBuffer instances which may invalidate this issue.)
- You can get the plain buffer from any buffer object using a plain function call to Duktape.Buffer, i.e. `var plain = Duktape.Buffer(bufobj)`. This can be provided using a separate function, e.g. `Duktape.plain(bufobj)` or `bufobj.toPlain()`. (#864 might make this unnecessary; there's also no way of coercing a full Function to a lightfunc.)

**Comment by mamod** [comment]
does this mean ``duk_get_buffer`` will be deprecated too?
To be honest buffer API is a bit confusing

If Duktape.Buffer will be deprecated and ``bufobj.toPlain()`` is introduced then I think ``duk_get_buffer_data`` will be enough, unless I'm missing some use case?

**Comment by svaarala** [comment]
@mamod Plain buffers would remain as they're the most memory efficient alternative and they're used as the backing for buffer objects.

But deprecating `duk_get_buffer()` (or perhaps renaming `duk_get_buffer_data()` to `duk_get_buffer()`) would still be a useful API change because there's generally no need to distinguish between plain buffers and buffer objects when reading/writing them in C.

**Comment by mamod** [comment]
Of course, I was referring to the API call, but after giving it more thoughts I think there is still a use case for pushing and getting plain buffers in C, for example dukluv use them as structure initializes instead of malloc, which more effecient than pushing buffer objects, so instead of deprecating I was thinking of unifying both API calls with type checking if needed as I just saw your v2.0 milestone #741 I think this is the best solution :+1:

**Comment by fatcerberus** [comment]
Yeah, from what @svaarala said above plain buffers will remain, it's just the API that will be simplified.

Part of the reason the 1.x buffer API got to be such a mess is that Duktape didn't originally support typed arrays, so the new stuff had to be bolted on without breaking compatibility.  With 2.x we now have the opportunity to clean it up. :)

**Comment by svaarala** [comment]
There are three functions `Duktape.Buffer` constructor for plain buffers:

- Create a new plain buffer of a specific size, `Duktape.Buffer(4)`.
- Create a new plain buffer with data copied from a string (its internal representation), `Duktape.Buffer('abcd')`.
- Coerce a buffer object into a plain buffer `Duktape.Buffer(bufobj)`. This would get the full underlying plain buffer, ignoring any slice/offset information. No copy is made, the resulting plain buffer is shared with the buffer object.

In addition to this, there's a use case for this (not covered by `Duktape.Buffer`):

- Coerce a buffer object into a plain buffer so that a copy is made; respect slice/offset information. One could emulate this via several calls.

These need some replacement for this pull to be completed, I'll outline a few alternatives below.

**Comment by svaarala** [comment]
The `new ArrayBuffer()` call creates a new ArrayBuffer object while `ArrayBuffer()` is required to be a TypeError. This would allow a plain non-constructor `ArrayBuffer()` call to be used for plain buffer handling (similarly to how a plain `Duktape.Buffer` call and a plain `String` call have different semantics from their constructor call counterparts). This doesn't seem appealing to me because it's too close to the standard constructor whose behavior may change: what if more useful semantics are assigned to a plain `ArrayBuffer(xxx)` call?

Other places where plain buffer functionality could be logically placed:

- The `Duktape` object, e.g. `Duktape.plainBuffer(12)`, etc.
- The `ArrayBuffer` object, e.g. `ArrayBuffer.plain(12)`.

As for the calls themselves:

- Sharing the same method for creating a plain buffer of a certain length and creating a plain buffer from string data makes sense to me. This is *not* the case for an ArrayBuffer though, but Node.js Buffer constructor supports it. Personally I like being able to create a buffer from a string without much extra thought.
- Creating a plain buffer with data copied from any input buffer object could logically be the same method which accepts a length or a string; buffer data would only be treated as another form of initializer input, and it then makes sense to respect the slice/offset data.
- Getting the plain buffer underlying a buffer object is a bit of a different operation because no plain buffer is actually created; rather it's just inspecting a buffer object's internals. It was originally present in `Duktape.Buffer` to match what `String(new String('foo'))` does: it returns the plain string from a boxed String object.

So, if a single method served all these purposes, it'd need some extra information (a flag or similar) to decide what to do with a plain buffer or buffer object input: either create a copy of the slice, or get the underlying buffer.

For clarity it might be better for the "get underlying buffer" operation to be a separate method so that the creation method would always create a new buffer with some initializer.

**Comment by svaarala** [comment]
Concrete suggestion for an `ArrayBuffer.plain()` method (`ArrayBuffer.createPlain()` or `ArrayBuffer.newPlain()`?):

```js
// Create a plain buffer of specified length, initialized with zeroes (unless
// zero init option turned off).
var plain = ArrayBuffer.plain(4);
print(Duktape.enc('jx', plain));  // --> |00000000|

// Create a plain buffer from string data, copying internal string bytes 1:1
// into the buffer.
var plain = ArrayBuffer.plain('abc\xff');
print(Duktape.enc('jx', plain));  // --> |616263c3bf|; U+00FF is in UTF-8 form

// Create a plain buffer, copy data from a plain buffer argument.  Storage
// is not shared between the argument and the result.
var plain1 = ArrayBuffer.plain('abcd');
var plain2 = ArrayBuffer.plain(plain1);  // Create a copy of plain1, storage not shared
print(Duktape.enc('jx', plain2));  // -> |61626364|

// Create a plain buffer, copy data from any buffer object, respect slice
// offset/length.  Storage is not shared between the argument and the result.
var view = new Uint8Array([
    0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68]).subarray(2, 5);  // view sees 'cde' = |636465|
var plain = ArrayBuffer.plain(view);  // Create a copy of visible u8 slice
print(Duktape.enc('jx', plain));  // -> |636465|
```

Separate method for getting the underlying buffer of a buffer object, `ArrayBuffer.getPlain()` (`ArrayBuffer.plainOf()` to mimic `Object.prototype.valueOf()`?):

```js
// Get the plain buffer underlying any buffer object.
// Slice offset/length is not respected, no copy is made.
var view = new Uint8Array([
    0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68]).subarray(2, 5);  // view sees 'cde' = |636465|
var plain = ArrayBuffer.getPlain(view);
print(Duktape.enc('jx', plain));  // -> |636465|

// Underlying buffer is 'plain' (data is 'abcdefgh' from the array initializer).
// View byte offset was view.byteOffset.
// View byte length was view.byteLength.
```

Because this operation is actually related to buffer objects (instances) it could also be in some buffer prototype. The problem with this is that it'd need to be both in the typed array and in the Node.js Buffer inheritance chain, and also in ArrayBuffer.prototype as not all buffer objects are views. So maybe it's better to have it in ArrayBuffer.

**Comment by svaarala** [comment]
One more use case missing above:

- Check whether an argument is a plain buffer or not. In Duktape 1.x this would only be possible indirectly using `Duktape.info()` or `Duktape.Buffer(arg) === arg`.

**Comment by fatcerberus** [comment]
I like `ArrayBuffer.plain()` naming, feels like it fits in with other parts of Ecmascript the best (2+ word method names are rare).

I think I agree that it makes most sense as a method of `ArrayBuffer`, even moreso if Node.js Buffer is updated to inherit from `Uint8Array`.

**Comment by svaarala** [comment]
@fatcerberus Good to hear - I don't see a way around having two methods though, one for plain buffer creation and another for inspecting a buffer object. If the creation method is `ArrayBuffer.plain()` would it then be weird to have `ArrayBuffer.getPlain()` for the buffer object inspection?

If there were no footprint issues, something like `ArrayBuffer.inspect()` which returned an object like the following would be useful:

```js
{
    plainBuffer: buffer,
    byteOffset: 123,
    byteLength: 321,
    elemType: 'uint8'
}
```

However, this "deluxe" primitive would be larger than just "get underlying buffer". On the other hand it'd be more extensible as buffer internals are likely to change. For now just a "get underlying plain buffer" is enough to implement that deluxe inspection call because the other fields are available elsewhere (byteOffset and byteLength is available from the buffer object, and element type is available by checking the inheritance chain).

If there was another field that needed explicit inspection support (= couldn't be implemented another way), it'd probably then be preferable to return an object rather than add a second method to get that field, etc.

Actually, one approach would be to change `Duktape.info()` to return an object (like you asked about earlier), and then add buffer object support into that call, so you could do something like:

```js
var plain = Duktape.info(bufObj).plainBuffer;
```

It might be better to rename that call `Duktape.inspect()`: it'd be more descriptive IMO, and it would then be easy to write a `Duktape.info()` polyfill alongside it.

**Comment by svaarala** [comment]
Then again, using `Duktape.info()` to get the plain buffer (or creating an object to return the plain buffer when requested) would be a relatively heavy hammer *if* the "get plain buffer" operation was part of some hot path handling like managing data buffers in I/O processing. For those paths it'd definitely be preferable if there were no extra allocations when dealing with the buffer values.

**Comment by fatcerberus** [comment]
I guess it would be necessary to consider how common a need "getting the plain buffer" would be to make that decision.  I don't have any insight at present, but I'll think about it.

I tend to agree w.r.t. `Duktape.inspect()` (which could be renamed to the self-explanatory `Object.inspect` if the Duktape object is removed for 2.x).
