### ISSUE TITLE
Ambiguity/error in debugger.rst

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#744]
Under `GetObjPropDesc`, it says this:
> Properties stored in the internal "array part" are indexed using numeric string keys, e.g. "3", not integers, to avoid unnecessary string churn on the target.

This is already confusing (how does using string keys avoid string churn?), but then a few paragraphs down under "Key" it says:
> Number for array index properties of "dense arrays", i.e. arrays which have an internal array part present

Only one of these can be correct.  Which one is it? ;-)

**Comment by fatcerberus** [comment]
Related, under GetObjPropDescRange:
> For both dense and sparse arrays there may be gaps in the array, i.e. elements may be missing. Such elements will not be included in the inspection result at all.

Either this is wrong, or there's a bug in the the heap walking, because I definitely remember writing code to filter out "unused" dvalues.

**Comment by svaarala** [comment]
The index issue is a typo: what was meant is that integer indices are used to avoid string churn. The array gap description is incorrect; I originally thought of implementing it that way but then decided to keep the gaps intact for dense arrays (= array part present).

I'll fix these, thanks for pointing them out :)

**Comment by fatcerberus** [comment]
Another thing you might want to fix/clarify is "number for array index properties..."  "Number" would lead me to believe it expects a Number dvalue (IEEE double) when in reality Duktape expects an integer here (?)

**Comment by fatcerberus** [comment]
@svaarala Bump. :)  This is still not fixed in master.

**Comment by svaarala** [comment]
Looked into this a bit and there are indeed multiple inconsistencies here. There were several iterations of the implementation and documentation is partially out of date. Commenting on the issues:
- Array indices are always sent as strings. The string churn comment was related a previous version but because strings are now used they will be interned and cause string churn.
- Sparse array gaps are visible as missing keys.
- Dense array gaps are visible as "unused" dvalues as you correctly point out.

#744 should fix the text for these issues.

**Comment by fatcerberus** [comment]
_Are_ array indices sent as strings?  I was pretty sure I was receiving integer keys when I set up my debug client.  I'll have to verify that using MSVC debugger now...

**Comment by svaarala** [comment]
> Are array indices sent as strings?

That was related to GetObjPropDesc, i.e. when the array index is an argument in the request.

The results from GetObjPropDescRange can be integers or strings. This is the part which avoids some string churn for the array indices (but the comment was in the wrong place, in GetObjPropDesc).
