### ISSUE TITLE
What 'introduced' version to use in API docs for calls with incompatible changes?

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#749]
For example, `duk_safe_call()` gets a userdata argument in Duktape 2.x which is a source incompatible change. Should the call be listed as "new in 2.0.0" in the API documentation, i.e. it would appear in the "2.0.0" tag list of the api.html page?

One alternative is to keep the original introduced-version for calls where the essential semantics are the same as previously with maybe new arguments or flags, but add some metadata key indicating last incompatible change.

**Comment by svaarala** [comment]
So far "introduced" has been bumped for API calls with incompatible changes but this can be changed before 2.0.0 is released.

**Comment by fatcerberus** [comment]
I think bumping the "introduced" version is misleading, unless the API has changed in some fundamental way.  Adding a separate metadata field seems like a better solution to me.

**Comment by svaarala** [comment]
The issue I'm mostly thinking about is how does one notice that an incompatible change has been made when looking at the API documentation. If "introduced" is bumped, it will be apparent by looking at the list of API calls "introduced" in 2.0.0. If it isn't bumped, the incompatible change won't be apparent at all which would be bad.

**Comment by fatcerberus** [comment]
Hm, maybe the problem isn't with the bumping itself, but the word "introduced".  We could rename the field, but there's another issue: It's a supported and documented scenario that some users may wish to support multiple Duktape versions.  Bumping "introduced" to 2.0.0 gives no indication that the API is actually available (in a slightly different form) in the previous version(s).

**Comment by svaarala** [comment]
True that. Well, I won't touch the introduced versions for now in other pulls.

**Comment by svaarala** [comment]
Related issue: should the YAML metadata files of removed calls be removed from the tree or should there be a "removed" metadata item which would then drop them from the generated API documentation. So far in 2.x changes the YAML metadata files have been removed when a call was removed.

**Comment by fatcerberus** [comment]
Hm, keeping metadata for removed calls around could bloat the repository after a while.  I think removing them is probably for the best.  Of course, if we go that route, then there's really no reason not to go all-in and bump the "introduced" versions as well...

Is there any API documentation included in the dist?  If so it'd probably be okay for the git repo to only reflect the latest API.

**Comment by svaarala** [comment]
Documentation is not currently included in the dist package (though that would be easy to fix and it might be nice to have the static HTML files available for offline viewing etc).

The website has snapshots of documentation for earlier releases, e.g. http://duktape.org/1.0.0/api.html so the old API calls are still viewable there.

I agree it'd be nice to just remove stuff that's no longer part of the API, unless there's some actual use case where that metadata matters. For example, removed calls could be part of the API documentation but labelled as such (or perhaps there could be a button "Show removed calls" in the future). In practical terms there's also going to be a longish period where some people will be developing/maintaining a 1.x code base while others will work with the 2.x API only - and the API documentation may need to support both use cases.
