### ISSUE TITLE
Add duk_get_prop_desc() API call

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#759]
The `duk_def_prop()` API call provides functionality equivalent to `Object.defineProperty()`. Add the equivalent of `Object.getOwnPropertyDescriptor()` as `duk_get_prop_desc()`. The API call could return a descriptor object for the requested property; argument flags could control things like what to do with proxies and internal properties.

The value stack model could match either:
- `duk_def_prop()`, i.e. property descriptor values are pushed on the value stack. This is a bit awkward because the value count may vary which is more difficult to handle for return values than for argument values.
- `Object.getOwnPropertyDescriptor()`, i.e. an object with keys like `value`, `writable`, etc. This is easier from versioning perspective but uses an additional temporary object.

I'd rather go with the latter option because the variable return value count would be awkward to work with and to extend from a versioning perspective.

But if so, maybe `duk_def_prop()` should also follow the same model rather than using a variable value stack input which depends on the flags field? The call could also maybe be renamed `duk_def_prop_desc()`.

**Comment by fatcerberus** [comment]
Not a big fan of renaming `duk_def_prop()` honestly.  The current name makes it obvious that it's an analogue for `Object.defineProperty()`.  `duk_def_prop_desc()` seems awkward because you're not defining the property descriptor (the descriptor format is quite well-defined already :), but rather defining what the property semantics are _with_ a descriptor.

I'm not sure how I feel about needing to pass in an object.  Working with objects on the value stack is awkward.  Each property of the object requires at least 2 lines of code, and heaven help you if any of those property values are also objects:
```c
// bare minimum to set a property on obj at stack top
duk_push_string(ctx, "bar");
duk_put_prop_string(ctx, -2, "foo");
```

Maybe if #575 gets implemented first I'd be more receptive to the idea? ;)

**Comment by svaarala** [comment]
@fatcerberus I have pretty much the same feelings about the naming, just thought that maybe it'd be less confusing to introduce a new call rather than modify an existing one.

Regarding working with an object argument, I think there are pros and cons to each approach. The downside of the current `duk_def_prop()` is that the value stack shape is different depending on flags which can be error prone and not always very modular to extend (as ordering of the arguments plays a role which is non-issue for objects).

For return values the awkwardness of a variable value stack shape are worse IMO because the shape would need to be detected by the call site based on some kind of "return flags" indicating whether a setter/getter is present etc. But then, if the property read call uses an object convention, it's a bit odd and asymmetric if the write call doesn't - especially because the Ecmascript equivalent uses an object argument.

Having the ability to create objects or set multiple properties more conveniently is a separate issue I hope. For example, it might be useful to provide a call to push an object and set its properties at the same time, with the some property values coming from C arguments and some from the value stack. This would be different than `duk_def_prop_list()` if it were inline, using some kind of "format string" approach. Something like:

    duk_push_c_function(ctx, my_getter, 0);
    duk_push_c_function(ctx, my_setter, 0);
    duk_push_object_props(ctx, "enumerable:%b, configurable:%b, getter:%x, setter:%x", 1 /*enumerable*/, 0 /*configurable*/);
