### ISSUE TITLE
Add sub-millisecond resolution to time provider

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#773]
While the `Date` built-in cannot expose sub-millisecond resolution (truncating to even milliseconds is mandated by the specification) the time provider setup for `duk_config.h` should support sub-millisecond resolution. That's more or less already the case, but ensure documentation states this explicitly.

The sub-millisecond resolution will be available through `duk_get_now()` and a possible Ecmascript high resolution time API.

**Comment by svaarala** [comment]
When implementing this it'd also be useful for `Date` to have some way of constructing an instance whose internal time value had more resolution than full milliseconds. The standard methods could then include the additional resolution in their outputs; for example, `d.getUTCMilliseconds()` could return the fractions too.

**Comment by fatcerberus** [comment]
> `d.getUTCMilliseconds()` could return the fractions too

Would that be allowed by the standard?

**Comment by svaarala** [comment]
It wouldn't violate the standard because there's no way to create Date instances with sub-millisecond internal time value. Behavior for such Date instances would thus be undefined. But it's of course a bit of a grey area if such Date instances were then passed around.

**Comment by svaarala** [comment]
But even if the values are passed around I think it'd be OK - the code creating the instances knows it's creating a non-standard Date instance, and can then decide how to use them. If it's not useful to pass them around, it's free not to do so.

The upside of Date supporting these internal time values would be that you could otherwise deal with them normally, only the creation part would be different. If this weren't the case there'd need to be a separate class to provide functions for formatting etc.

But there are also existing specifications for sub-millisecond resolution so I'll have to go through them. One thing quite close is `Performance.now()`, but the time concept used there doesn't match `Date` time value concept unfortunately.

**Comment by svaarala** [comment]
An alternative to letting `d.getUTCMilliseconds()` return fractional millisecond values would be to add a separate getter to get the fractions too, but truncate the output from the standard call. Maybe this would be more predictable, at the cost of a few more methods.

**Comment by fatcerberus** [comment]
As a game developer something like `Performance.now()` sounds really nice.  That looks like it's more of an HTML5 thing though than an Ecmascript thing...

**Comment by svaarala** [comment]
`Performance.now()` is quite useful when you really essentially need something for timing, not really date/time:

> Also unlike Date.now, the values returned by Performance.now() always increase at a constant rate, independent of the system clock (which might be adjusted manually or skewed by software like NTP).

This means that `Date.now()` and `Performance.now()` may differ by an arbitrary amount which changes over time :(

**Comment by svaarala** [comment]
Also in embedded environments a constant rate uptime often makes more sense than a date/time, as an RTC is not always available so that there's no way to know the current time.

**Comment by saghul** [comment]
Is this that useful as a wall clock? If I understood correctly it would be like a Date but with sub-millisecond precision. Another useful thing would be to have a monotonic sub-milisecond time reference, a la process.hrtime() on Node, or uv_hrtime on libuv.

I do have such thing in sjs: http://sjs.readthedocs.io/en/latest/modules/time.html#time.hrtime The problem is that since the value is a uint64_t, it's split into an array of [seconds, nanoseconds], which is not super user friendly...

**Comment by fatcerberus** [comment]
Re: Monotonic time: That's what `Performance.now` discussed above would be for, and yes, speaking as a game developer it would indeed be awesome to have. :-)

**Comment by saghul** [comment]
@fatcerberus we have this in libuv for Linux, OSX, Windows, FreeBSD, SomartOS and AIX, in case you want to *borrow* it. MIT licensed, so no problemo.

**Comment by svaarala** [comment]
@saghul There are several time concepts that would be useful, such as:

- POSIX time, in both time value and broken down representation. This is provided by `Date`, but the milliseconds-only resolution limits some applications.
- Constant rate time, like `Performance.now()`. Provides a useful date/time reference but won't be adjusted if the system does a forced NTP sync or manual time correction. Usefulness depends on the application; if the time adjustment is made for a good reason it won't reflect actual time, so why not use a non-date-bound time reference like uptime?
- Constant rate uptime.

WIthin this issue I'm mainly concerned about `Date` resolution which limits some applications. That time concept must exist within the engine itself to implement `Date`. All the other time concepts are not critical to implement the engine itself so they're more or less optional, and there are various semi-standard APIs for them.

**Comment by svaarala** [comment]
@fatcerberus But what use is a date/time bound monotonous time that might be wrong, compared to a corrected system time? Wouldn't it be simpler to just use uptime, which is constant rate too?

**Comment by svaarala** [comment]
There's actually some demand within Duktape itself to use some constant rate time source (either date/time bound or a plain uptime): all the executor interrupt and other rate limiting checks are now made using the `Date` provider which suffers from potential time jumps (a natural downside of having a correctable time source :).

The controls in place are now to check for negative time differences and treat them as also triggering the periodic condition (e.g. a debug transport poll) so that a time jump can, at worst, trigger more frequent internal checks instead of postponing some checks indefinitely (say, a year :).

So, adding a constant rate source with no specific starting value (up to the application) might be useful internally too.

**Comment by fatcerberus** [comment]
I didn't mean to use monotonic time for the `Date` object, that'd be dumb. :)

With monotonic time you're more concerned with _differences_ between two measurements than an absolute "now".  The use case I was thinking of was e.g. measuring render time in a game loop to keep a constant frame rate.  In that case any kind of NTP correction is undesirable.

I'm a bit surprised that `Performance.now()` apparently measures wall-clock time.  I actually thought it _was_ a measure of uptime.  I need to re-read the MDN page...

**Comment by fatcerberus** [comment]
Anyway I guess we've gotten off the original topic of how to improve the resolution of Date objects specifically.  Sorry for derailing the issue as usual ;)

**Comment by svaarala** [comment]
@fatcerberus I meant wouldn't you rather use an uptime instead of Performance.now() for game timers and such? Or does it matter what the starting point of the time value is (even though it may be off sync with the system time if it has been adjusted)?

**Comment by fatcerberus** [comment]
Yeah, I thought Performance.now() _was_ measuring uptime, hence the confusion.  Rereading the MDN page now I see that isn't actually the case.

Either way the starting time doesn't really matter - the important thing is that 1) it's very precise and 2) it doesn't get adjusted behind your back when you're trying to synchronize things like framerate and such.   And uptime is probably the best metric for that, I agree.

**Comment by svaarala** [comment]
Moved discussion of Date instance millisecond fractions to #1661.
