### ISSUE TITLE
Add minimal time support API calls

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#774]
Add minimal time support API calls to the Duktape C API to allow:
- Getting the current time value.
- Getting the local time offset at a certain time value.
- Converting a time value to broken down UTC components.
- Converting broken down UTC components into a time value.
- Possibly some support for local time and formatting.

Initial draft (needed by logging rework) was implemented in #771:
- [x] Add duk_get_now()
- [x] Add duk_time_to_components()
- [x] Add duk_components_to_time()
- [x] API documentation draft
- [x] Wiki article stub - https://github.com/svaarala/duktape-wiki/pull/112
- [x] Website section on time handling, initial draft
- [x] Initial releases entry

Open issues and tasks:
- [x] Zero vs. one based: Ecmascript API is a mix of these, e.g. `d.getUTCMonth()` is zero-based but `d.getUTCDate()` (day in month) is one-based.
- [x] `duk_time_components` member naming vs. Ecmascript API: `d.getUTCMonth()` is singular but `d.getUTCMinutes()` is plural. Should struct members be named similarly (now there's e.g. `comp.minute`, not `comp.minutes`)?
- [x] Better name for `duk_get_now()`? Maybe `duk_get_time()`?  => Keep, `duk_get_now()` matches `Date.now()`
- [x] Handling of sub-millisecond resolution: while Ecmascript APIs are millisecond limited (explicitly required), there are sub-millisecond APIs and it'd be useful if the C API didn't need two variants
- [x] Because of normalization negative component values are useful, so change components in the struct to be signed (`duk_int_t` or `duk_double_t`)
- [x] Should all `duk_time_components` members be doubles, works best for normalization?
- [x] Releases entry

**Comment by fatcerberus** [comment]
That zero- vs. one-based month discrepancy is really weird.  Ecmascript backward compatibility baggage?

**Comment by fatcerberus** [comment]
I guess the idea is because month names are language-specific so it makes it easier to look them up in an array of it starts at zero...

**Comment by svaarala** [comment]
It probably derives from existing calls like `gmtime()`:

>        tm_mday   The day of the month, in the range 1 to 31.
>        tm_mon    The number of months since January, in the range 0 to 11.

**Comment by svaarala** [comment]
Another thing I really don't like is the special handling for two-digit years, e.g. `Date.UTC(99, 0, 1)` maps to 1999-01-01 but `Date.UTC(100, 0, 1)` maps to 0100-01-01:

```
> new Date(Date.UTC(99, 0, 1)).toISOString()
'1999-01-01T00:00:00.000Z'
> new Date(Date.UTC(100, 0, 1)).toISOString()
'0100-01-01T00:00:00.000Z'
```

The C API draft doesn't have this special casing now so that 99 gets interpreted as the year 99.

**Comment by fatcerberus** [comment]
The two-digit year handling is probably for backward compatibility.  The Ecmascript committee seems very hesitant to deprecate anything (see the way strict mode was implemented).  I guess it's understandable since JS is used on the public web, but it does mean you get really weird semantics at times, like with the `arguments` object.

**Comment by svaarala** [comment]
Yep, it's for backward compatibility. I don't want to carry it over to the C API :)

**Comment by svaarala** [comment]
So it's about time to make final decisions for 2.0.0 release. Having mulled over the zero/one -based issue a bit, I think it's ultimately best if the zero/one-basedness matches the Ecmascript Date getters 1:1.

While having months one-based would make for easier and in some ways less error prone datetime printing, the solution would differ from both `tm_mon` and (more importantly) the Ecmascript API. This would make moving between C and Ecmascript time APIs more error prone, so as a whole this seems more confusing than matching the Ecmascript API.
