### ISSUE TITLE
Is it possible to make a global accessor?

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#784]
I'm looking to implement a system whereby certain subsystems are lazy-loaded the first time they are accessed.  Let's say there's a `graphics` object that you don't want to create a rendering context until it's actually referenced, without resorting to making it a module (`require()` is inconvenient for core functionality--this is one of my gripes with Node).

One way to do this is to do an initialization check in each relevant method, but this could get unwieldy and is prone to bugs due to missed init calls.  A more general solution would be to make the relevant global variable an accessor whose getter performed the initialization.

Is this possible?  Can you have a global accessor, and if so how would I make one in Duktape?

**Comment by saghul** [comment]
How about something like:

~~~~~
Object.defineProperty(global, 'myThing', {
    get: function() {
        if (!global.__myThing) {
           // build and assing myTHing to global.__myThing
        }
        return global.__myThing;
    }
});
~~~~~

**Comment by fatcerberus** [comment]
So in C that would be `duk_def_prop()`.  Will that work even if the property is accessed as a free variable i.e. will `myThing.doStuff()` trigger the getter the same as `global.myThing.doStuff()`?  I guess it would have to, since there's not really anything else sensible it could do...

I guess I'll just have to try it.  Thanks for the tip!

**Comment by svaarala** [comment]
@fatcerberus That should work fine - global variables are looked up through the scope chain, and the global environment is an "object binding" (like `with`) so that variable lookups are ultimately handled as property lookups.

**Comment by megous** [comment]
Maybe you can do something like:

```
Object.defineProperty(global, 'myThing', {
    get: function() {
        if (!global.myThing) {
           // build and assing myTHing to global.myThing
        }
        return global.myThing;
    }
});
```

to avoid getter being called each time you access the property.

**Comment by fatcerberus** [comment]
Forgot about this, I left it open long after the question was solved.  Oops!
