### ISSUE TITLE
Duktape.Buffer(slicedBuffer) returns the whole buffer that's not sliced

### ISSUE THREAD

**Issue by vilic** [svaarala/duktape#792]
```js
var x = new Buffer('abc');

var subX = x.slice(1, 2);

print('subX length ' + subX.length); // 1

var subDX = Duktape.Buffer(subX);

print('subDX length ' + subDX.length); // 3
print('subDX ' + subDX.toString()); // abc
```

**Comment by svaarala** [comment]
That's the current intended behavior: Duktape.Buffer() returns the underlying plain buffer without making a copy. However, because plain buffers don't have slice information (at least currently, being the most memory efficient form of buffers) you'll get the full underlying plain buffer.

**Comment by svaarala** [comment]
If you don't mind making a copy, you can replace `Duktape.Buffer(subX)` with e.g.

```js
var buffer = new Buffer('abc');
var slice = buffer.slice(1, 2);
var copySlice = Duktape.Buffer(new Uint8Array(slice));
print(Duktape.enc('jx', copySlice));  // -> |62| ('b')
```

However, `copySlice` and `slice` won't be backed by the same plain buffer.

**Comment by vilic** [comment]
I see, thanks for clarification.
