### ISSUE TITLE
GCC warning: in 'duk__enc_value': declaration of 'h' shadows ... [-Wshadow] 

### ISSUE THREAD

**Issue by avih** [svaarala/duktape#793]
```
duk_bi_json.c: In function 'duk__enc_value':
duk_bi_json.c:2115:16: warning: declaration of 'h' shadows a previous local [-Wshadow] duk_bi_json.c:1934:15: warning: shadowed declaration is here [-Wshadow]
duk_bi_json.c:2122:16: warning: declaration of 'h' shadows a previous local [-Wshadow] duk_bi_json.c:1934:15: warning: shadowed declaration is here [-Wshadow]
```

This is with version 1.5.0 ( 83d557704ee63f68ab40b6fcb00995c9b3d6777c ). Not sure when it started but IIRC I was not seeing this with earlier versions.

GCC is 4.9.3, cross compiler on host Linux 64, with target Windows 32 (MXE).

I tried looking at `duk_bi_json.c`, but the sources I use are only `duk_config.h`, `duktape.c`, `duktape.h`, `metadata.json`.

**Comment by fatcerberus** [comment]
The offending declarations are here:
https://github.com/svaarala/duktape/blob/v1.5.0/src/duk_bi_json.c#L2115
https://github.com/svaarala/duktape/blob/v1.5.0/src/duk_bi_json.c#L2122

The declaration being shadowed is here:
https://github.com/svaarala/duktape/blob/v1.5.0/src/duk_bi_json.c#L1934

GCC is right to warn: We have a block-scoped variable shadowing one at function scope.  The warning ultimately looks harmless, but of course should still be fixed.

**Comment by svaarala** [comment]
There should be no bug related to this, the shadowing is quite harmless and was introduced when I reworked the two-step JSON encoding into a single step one. I'll issue a pull to fix the warning, thanks!

**Comment by svaarala** [comment]
I'll also add `-Wshadow` to the development builds, it's quite interesting even `-Wall -Wextra` won't enable it by default. While shadowing is a language feature a lot smaller issues are covered by -Wextra IMO.

**Comment by fatcerberus** [comment]
Notably there are some languages, e.g. C#, where it's a hard error to have overlapping scopes for the same identifier.

I guess gcc doesn't enable it by default precisely because a lot of C/C++ programmers take advantage of the feature?  It's more of a "this could be a vector for bugs in future, consider refactoring" type warning than a "if you ship this code it's almost certainly buggy" one. :)
