### ISSUE TITLE
babel-standalone is incredibly slow under Duktape

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#811]
I tried out using babel-standalone in minisphere for ES6 support, but it seems the transpiler runs incredibly slowly under Duktape.  The CoffeeScript and TypeScript transpilers aren't nearly this slow, so it seems like an anomaly specific to Babel.  I wonder where the bottleneck is?

If you want to check it out, babel-standalone is here:
https://github.com/Daniel15/babel-standalone

And the script is here:
https://github.com/Daniel15/babel-standalone/releases/download/release-6.7.7/babel.js

To run the transpiler, just call `Babel.transform("some ES6 code")`

**Comment by svaarala** [comment]
How slow is incredibly slow? 1000x slower?

**Comment by svaarala** [comment]
Case insensitive regexp compilation has known performance issues but it seems `babel.js` compiles in around 0,4 sec so it doesn't seem to be compilation.

**Comment by svaarala** [comment]
@fatcerberus Have you compared the relative performance between Babel and Coffeescript/Typescript on some other engine(s)? This would be nice to know to make sure it's triggering some specific performance issue rather than being generally slower.

**Comment by svaarala** [comment]
This quick test is 8 milliseconds:

```
[babel.js loaded, then interactive mode]
duk> var input = 'const getMessage = () => "Hello World";';
= undefined
duk> var t1 = Date.now(); var output = Babel.transform(input, {presets: ['es2015'] }).code; var t2 = Date.now(); print(t2-t1); print(output);
8
"use strict";

var getMessage = function getMessage() {
  return "Hello World";
};
= undefined
```

Is this roughly the performance you're seeing, or is it much slower?

**Comment by svaarala** [comment]
Seems the the execution time scales directly with input length (i.e. there isn't some large setup cost or something like that): replacing a single const arrow function with three bumps execution from 8ms to 17ms:

```
duk> var input = 'const getMessage = () => "Hello World"; const getMessage2 = () => "Hello World"; const getMessage3 = () => "Hello World"; ' 
= undefined
duk> var t1 = Date.now(); var output = Babel.transform(input, {presets: ['es2015'] }).code; var t2 = Date.now(); print(t2-t1); print(output);
17
"use strict";

var getMessage = function getMessage() {
  return "Hello World";
};var getMessage2 = function getMessage2() {
  return "Hello World";
};var getMessage3 = function getMessage3() {
  return "Hello World";
};
= undefined
```

**Comment by svaarala** [comment]
Minimal interrupt-based profiling would be quite useful for figuring this out :)

**Comment by fatcerberus** [comment]
I'll run some comparisons in a bit but, for a sense of scale here, the CoffeeScript compiler takes nearly a full minute to process through Babel on my AMD A10 desktop.  That seemed rather excessive.

**Comment by svaarala** [comment]
Did you mean vice versa, Babel transpiling the CoffeeScript compiler?

**Comment by fatcerberus** [comment]
Yes, that's what I meant.

**Comment by svaarala** [comment]
Scaling with the typical 30-100x performance difference between Node.js and Duktape, the expected Node.js execution time for that would be around 0,5-2 seconds. If it's much less than 0,5 seconds then Duktape is performing slower (comparatively) than normal.

**Comment by fatcerberus** [comment]
This is the time I wish `duk` had file bindings.  I'm trying to wire up an isolated testcase that I can test using the `time` command, `duk` having file bindings would make that so much easier. ;-)

**Comment by svaarala** [comment]
Depending on compiler options `duk` actually provides `readFile()` and `writeFile()` for testing purposes. The command line option is `DUK_CMDLINE_FILEIO`.

**Comment by fatcerberus** [comment]
Using Node.js on the same machine, using babel-cli with the `es2015` preset on the minified CoffeeScript compiler, takes about 3-4 seconds.  I still need to get an accurate timing for Duktape.

**Comment by svaarala** [comment]
Applying the ~30-100x performance difference the "expected" Duktape timing would be 90-400 seconds. So there might not be anything pathological going on, unfortunately.

**Comment by fatcerberus** [comment]
Duktape took around 30 seconds on the same task before reporting a ReferenceError: `console` is undefined, which makes no sense since CS works fine normally.  No idea what that's all about.

TypeScript, for comparison, takes around 25 seconds to do the same transpile under Duktape.  So it's definitely faster, but not quite as performant as I thought.  I guess on-the-fly transpilation isn't really practical with Duktape.

I am curious what the hot path through Duktape looks like though.  Maybe I'll run it through the profiler. :)

**Comment by svaarala** [comment]
Most likely you'll see that the bytecode dispatch accounts for most of the difference to a JIT engine. The typical performance difference varies a lot but is usually between 10-100x between JIT and interpretation. The more time is spent in built-ins (say, array operations, regexp matching, compilation, etc) the smaller the difference becomes.

**Comment by svaarala** [comment]
Regarding that ReferenceError, if you think something is broken it might be useful to rerun the test with assertions enabled in Duktape build. Maybe you're triggering a compiler / executor bug.

**Comment by fatcerberus** [comment]
So I did an experiment.  I set up minisphere to run all scripts through the TypeScript transpiler, gave it a game with a large number of scripts, and run it under the profiler.  `duk_js_execute_bytecode_inner()` naturally accounts for 96.2% (inclusive, i.e. including callees) of the execution time.  This isn't a surprise: We're running Ecmascript code.  What is interesting is that, within that 96.2%, the top 3 CPU burners are:

```
Functions that were called by duk__js_execute_bytecode_inner 
Function Name	Inclusive Samples	Exclusive Samples	Inclusive Samples %	Exclusive Samples %
duk__handle_call_inner	16,352	117	40.30	0.29
duk_js_push_closure	8,676	426	21.38	1.05
duk__vm_arith_add	6,825	40	16.82	0.10
```

`duk__handle_call_inner` is there of course, that just tells us we're spending 40% of our time running functions.  It's Ecmascript code, not surprising.  More surprising is that 21% is spent pushing closures, and ~17% is spent on... addition?  For some reason?

Looking at _exclusive_ samples, bytecode dispatch accounts for a decent chunk:
```
Function Name	Inclusive Samples	Exclusive Samples	Inclusive Samples %	Exclusive Samples %
[ntdll.dll]	6,266	6,266	15.44	15.44
duk__js_execute_bytecode_inner	39,028	4,967	96.20	12.24
duk_unicode_unvalidated_utf8_length	3,240	3,240	7.99	7.99
memcpy	2,211	2,211	5.45	5.45
```

So around 12% of my execution time is bytecode dispatch, 8% is calculating string length (!), and a whopping 15.5% seems to be system calls (ntdll).

**Comment by svaarala** [comment]
@fatcerberus Should this be closed or is there some concrete action that can be taken?

**Comment by svaarala** [comment]
One documentation related issue, worth nothing in the wiki modules howto, is that if you're transpiling on-the-fly there may be performance issues. One useful mechanism there might be to implement a transpiling cache which associates a transpile result with e.g. a source file hash.

**Comment by fatcerberus** [comment]
I just wondered if you had any insight on my profiling results above.  Bytecode dispatch accounts for a decent amount, but arith_add actually seems more dominant and I have no idea what's up with the 15% in system calls.

**Comment by svaarala** [comment]
Right, it's quite difficult to say if that matches or doesn't match expectations -- what are those expectations? :)

Ultimately the profiling results depend quite heavily on what kind of code is being executed. String heavy code, for example, displays a lot of UTF-8 length computation because a single string intern can take more time than dispatching (say) 10 arithmetic opcodes. Arithmetic addition also covers string concatenation which is often significant, especially if strings are built in the `result += c; result += "foo"; //etc` style as all the intermediate results get interned.

Case insensitive regexp compilation is a current bottleneck for compilation, but not for execution, and isn't an issue in this case.

**Comment by svaarala** [comment]
Oh, one potential issue is that `console.log` issue you encountered. It might be useful to rerun that test with assertions and debug prints enabled to see if anything turns up. (Or if you have a chance, valgrind.)

**Comment by fatcerberus** [comment]
I guess I expected bytecode dispatch to be dominant, but that's not exactly the case here.  It only accounts for 12%, which isn't too bad.  String handling appears to be the bottleneck here.  I just wish I knew what all those ntdll calls were.

I'll do some more tests later on tonight - I have to go to work in a few hours so I don't have the opportunity to do it right now.

**Comment by svaarala** [comment]
It's actually quite easy to dwarf the dispatch, it's not all that heavy per opcode. So for example, if you were to do a loop like:

    for (var i = 0; i < 1e6; i++) { var tmp = String(i); }

string conversion, string freeing, etc, should be much more significant than dispatch. The significance of dispatch ultimately depends on how much work is done per dispatched opcode; string conversion, property lookups, calls, try-catch, are all more significant than the dispatch itself.

Also note that profiling results may be distorted (sometimes quite a lot) because of inlining; and profiling non-inlined code may not be representative.

**Comment by svaarala** [comment]
Ok, sounds good. There's no hurry in closing this issue, I just don't want it to hang open unless there's something to actually do other than stating that more performance would be nice :-)

**Comment by fatcerberus** [comment]
> Also note that profiling results may be distorted (sometimes quite a lot) because of inlining; and profiling non-inlined code may not be representative.

Yes, I'm aware of this - this is why I always profile a fully optimized release build with debugging information enabled in MSVC settings.  I've learned not to profile non-optimized builds with Duktape - the results get very distorted. :)

**Comment by svaarala** [comment]
But then, with optimized builds, the attributions may not be reliable. Schrödinger :-o

**Comment by fatcerberus** [comment]
That's true, although I've found MSVC to be excellent at generating debug info for release builds.  Sometimes line numbers are distorted locally due to optimizations (and local variables get optimized out making it useless for actual debugging) but that's unavoidable.  I don't know that I've ever seen it misattribute things at the function level, but I won't rule out the possibility. :)

**Comment by fatcerberus** [comment]
I'll close this.  If an actionable issue comes up I'll reopen (or open a new issue).

**Comment by fatcerberus** [comment]
Ouch.  TypeScript transpilation speed under Duktape is almost unbearable (= several seconds for ~10kB of code) once I added a `lib.d.ts` to the build.  Good thing I had the foresight to make Cell only compile those source files that changed, or this would be completely unworkable. :)

**Comment by svaarala** [comment]
As discussed above, non-JIT execution is quite a lot slower than JIT execution, so this doesn't really mean anything can or should be changed. In other words, it's not necessarily a relevant issue to be tracked in the repo.

However, if the execution speed difference exceeds the usual 10-100x factor between a JIT and non-JIT executor, then there may be something that performs much worse than expected.

**Comment by fatcerberus** [comment]
Right, which is why I left the issue closed :)

When I get a chance, I'll compare compilation speed in Node.js for the same sources and get back to you on that last point.

**Comment by fatcerberus** [comment]
It seems that type checking in general is the slowest part of the TS compiler:
http://stackoverflow.com/questions/36624273/investigating-long-typescript-compile-times

So partial rebuilds seem to be the best mitigating factor I have without switching engines.  One can disable type checking, but that rather defeats the purpose of using TypeScript. :)
