### ISSUE TITLE
duk_def_prop() doesn't allow index as key

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#836]
At least, the last time I tried to use an index instead of a string for the key, it didn't work.  If it's indeed the case that numeric indices are not allowed as keys for `duk_def_prop()`, would it be difficult to change it so they are?

**Comment by svaarala** [comment]
Should be easy to change if that's the case - ultimately the index is string coerced anyway as there are no numeric properties in Ecmascript.

**Comment by svaarala** [comment]
Yep, the internal implementation uses `duk_require_hstring()` at the moment so it'll reject non-string arguments.

**Comment by fatcerberus** [comment]
Yeah, I just use `duk_to_string()` for now, but it'd be nice for API convenience if the extra step wasn't necessary. :)

**Comment by svaarala** [comment]
Agree: `duk_put_prop()` accepts integers too, and so does `Object.defineProperty()`:

```
((o) Duktape 1.5.0 (v1.4.0-421-g8e90d3d-dirty)
duk> x = {};
= [object Object]
duk> Object.defineProperty(x, 1, {value:'foo'})
= [object Object]
duk> x[1]
= foo
```

**Comment by fatcerberus** [comment]
By the way isn't the string coercion avoided if the object has an array part?

**Comment by svaarala** [comment]
Not for `duk_def_prop()`; it doesn't have the same fast paths as get/put prop.

**Comment by fatcerberus** [comment]
I guess the defprop would discard the array part anyway since the property attributes are being restricted (I think I remember seeing something about that in the internal docs?)

Anyway I'm actually not using this for arrays but instead to make TypeScript-style serializable enums, i.e.

```javascript
MyEnum[MyEnum.MyValue = 1] = "MyValue";
```

I use `duk_def_prop()` for this because I don't want the properties to be writable.

**Comment by svaarala** [comment]
That's the behavior currently; technically it should only discard the array part if the attributes are no longer compatible with the array part assumptions (that is, writable, enumerable, configurable).

**Comment by fatcerberus** [comment]
@svaarala How easy would this be to fix?  I can do it if you want. ;-)

**Comment by svaarala** [comment]
The most trivial fix would be to change `duk_require_hstring()` to `duk_to_hstring()` so should be quite easy. Testcase changes take more time :)
