### ISSUE TITLE
Add ability to create a Proxy from C code

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#837]
For example, `duk_push_proxy()` with value stack behavior:

```
[ ... target handlers ] -> [ ... proxy ]
```

**Comment by fatcerberus** [comment]
I've wanted this API for quite a while, good that you finally thought of it.  Not sure why I never posted an issue...

**Comment by svaarala** [comment]
This came up on IRC again so I opened an issue for it. I'm somewhat hesitant to mirror every Ecmascript constructor and method into the C API for various reasons. So the current situation is somewhat unstable, with APIs added on demand but with no effort to add every Ecmascript bindings as a C binding too.

Footprint is luckily not a practical concern for most platforms with modern compilers when link time optimization can eliminate any unused C API calls during the link phase at the latest.

**Comment by fatcerberus** [comment]
That's understandable.  Proxies would definitely be a candidate for the API though I think: C code may want to act as gatekeeper for the objects it hands out, and Proxy traps are a good way to do that.  So this is good to have for sandboxing if nothing else.

**Comment by fatcerberus** [comment]
By the by, are there any plans in the short-to-mid term to implement the full set of Proxy traps?

**Comment by svaarala** [comment]
Yes, I'm hoping to implement more traps for 2.0.0 release. Not sure if the full set, some of them affect quite many places internally while others are straightforward.

**Comment by svaarala** [comment]
Implemented by #1500.
