### ISSUE TITLE
Show name in "identifier not defined" error

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#839]
Currently an "identifier not defined" error caused by a strict mode reference to an undefined variable doesn't include the identifier that caused the error.  This sometimes makes debugging difficult.  Consider updating the error message to include it, to match the behavior for other, similar errors.

**Comment by svaarala** [comment]
Agreed, the error message gets used when a write to an undeclared variable happens in a strict mode function. Instead of a global property being written an error is thrown:

```
duk> function test() { 'use strict'; notDefined = 1; }
= undefined
duk> test()
ReferenceError: identifier not defined
    at [anon] (duk_js_var.c:1384) internal
    at test (input:1) strict
    at global (input:1) preventsyield
```

**Comment by svaarala** [comment]
Read also throws but that error message already has the identifier name:

```
((o) Duktape 1.5.0 (v1.4.0-421-g8e90d3d-dirty)
duk> function test() { 'use strict'; var x = noSuch; }
= undefined
duk> test()
ReferenceError: identifier 'noSuch' undefined
    at [anon] (duk_js_var.c:1259) internal
    at test (input:1) strict
    at global (input:1) preventsyield
```
