### ISSUE TITLE
Error object not in stack on exception

### ISSUE THREAD

**Issue by mxmauro** [svaarala/duktape#848]
Hi Svaarala,

After some time, updated DukTape and found different things:

I'm using `DUK_USE_CPP_EXCEPTIONS` and use a `try/catch(duk_internal_exception&)` to catch for error thrown by native functions and DukTape functions like push/pop operations (I think DukTape api's might throw, mainly, insufficient memory or range errors).

When the error raises (i.e., bad javascript code), exception is raised, `duk_err_create_and_throw` catches it, pushes the error object and exception and `duk_err_longjmp` is executed again. At this point my handler catches the error but all available stack items are null.

```
try {
    duk_pop(ctx); //some code that will raise an error
}
catch (duk_internal_exception&) {
    //at this point stack has nothing.
}
```

Regards,
Mauro.

**Comment by svaarala** [comment]
When Duktape is using C++ exceptions for long control transfers you're not intended to catch the exceptions yourself. They're just used as a technical means for doing a C++ stack unwind respecting destructors etc. So the protected call sites should just use normal protected calls like `duk_pcall()`, etc.

**Comment by mxmauro** [comment]
Pushing a string, a buffer or growing the stack can lead to memory errors.

Let's say I call `duk_create_heap` and initialize some global vars/functions from C before executing actual Javascript code. If I run out of mem (or trigger another error like out-of-range), I want to catch them. Also to catch errors raised by custom native functions that could be called by this pre-JS code (i.e. creating some object where its constructor is native code too)

And, if possible, I want to differentiate a range error from an alloc error from a custom error (using `duk_error_raw` or similar)

**Comment by svaarala** [comment]
Right, that initialization code would be inside a protected call and any errors thrown would have a message indicating if an out-of-memory happened.

When you say you want to differentiate a range error from an alloc error, what would that mean in practice? Would there be a different code path handling the different error types - and if so, what would they do differently?

The errors are already differentiated by their error messages as far as logging, diagnostics etc are concerned. What I'm trying to understand is why you need to *programmatically* differentiate the errors, and why alloc errors specifically and not a variety of other internal errors.

**Comment by mxmauro** [comment]
Trying to clarify, a sample code:

```
HRESULT RunJsCode(LPCSTR szCodeA)
{
    duk_context *ctx = duk_create_heap(...);
    duk_push_global_object(ctx);
    duk_push_buffer(ctx, 2000, 0);
    duk_push_buffer_object(ctx, -1, 0, 2000, DUK_BUFOBJ_UINT8ARRAY);
    duk_put_prop_string(lpCtx, -2, "\xff""\xff""dummyBuffer");
    duk_eval_string(ctx, szCodeA);
    ....
    return S_OK;
}
```

a) Assume low mem situation and the call to `duk_push_buffer` or `duk_push_buffer_object` fails. How can I catch it? If I'm right the code there is not protected. Or how can I protect it? Tried try/catch your internal exception but for some reason the error object does not appear on stack.

b) Error differentiation is not important. Previously I checked for `DUK_ERR_ALLOC_ERROR` which I turned into `E_OUTOFMEMORY`. I believe it is a fatal error, different, i.e., from a range error because one is raised by the system failing and the other by, i.e., bugs in passes javascript code.

If there is something I can use, the better, may be a string but I cannot get error info because the unprotected code above.

**Comment by fatcerberus** [comment]
You should look into `duk_safe_call()`.  That's how you would protect arbitrary Duktape code.  If an error is thrown during the duration of the safe call, the call will return 1 with the error on the stack.

**Comment by mxmauro** [comment]
Thanks @fatcerberus. I'll see it. A quick view indicates it is the function I need to solve my problems hehe.

**Comment by mxmauro** [comment]
@svaarala If `nrets == 0` in a call to `duk_safe_call` that returns `DUK_EXEC_ERROR`, then the error object is removed from stack too.

**Comment by fatcerberus** [comment]
That's documented behavior and not a bug:
> If an error occurs, the stack will still have `nrets` values at "base index"; the first of such values is the error, and the remaining values are `undefined`. If `nrets` is zero, the error will not be present on the stack (the return stack top will equal the "base index"), so calling this function with `nrets` as 0 is not very useful.

**Comment by mxmauro** [comment]
Thanks again @fatcerberus.

**Comment by fatcerberus** [comment]
@mxmauro No problem, always happy to help.
