### ISSUE TITLE
Projects Using Duktape > please add Freewrl.sf.net

### ISSUE THREAD

**Issue by dug9** [svaarala/duktape#855]
Please add freewrl http://freewrl.sf.net to your list of Project Using Duktape. 
freewrl is a virtual reality browser.
Thanks,
-Doug
more..
a few years ago we adopted duktape for freewrl for platforms where spidermonkey engine isn't available.
- with the help / coaching of Sami Vaarala
- and we changed how we did things -using virtual proxies, an EC6 thing- 
Using lazy virtual proxies the objects have an ID and a few generic parameters. Then our application code does the heavy lifting to figure out what object and function. So A.b[i].c["x"].d goes back to our application code for each step in resolving.
more..
https://sourceforge.net/p/freewrl/git/ci/master/tree/freex3d/src/lib/world_script/
- the _duk modules interface to duktape
- other modules relate no jscript or spidermonkey engine

**Comment by svaarala** [comment]
Ok, added: https://github.com/svaarala/duktape-wiki/pull/129 :)
