### ISSUE TITLE
Used headers/dependencies

### ISSUE THREAD

**Issue by Jan-Kow** [svaarala/duktape#857]
Not really an issue, but in some point pretty interesting. I currently write on my own C library (very small, for my hobby operating system, nothing big (yet!)) and duktape is going to be used in some core parts. When I search around in the ``duk_config.h`` file I find a lot of includes which are (often) platform specific (on Windows, ``windows.h`` etc.). It would be nice if anyone could tell me what is *really* used in order to use/build/compile duktape.

**Comment by svaarala** [comment]
Hmm, you shouldn't be seeing any platform headers in `duktape.h`, they should all be in `duk_config.h` which encapsulates all platform/architecture/compiler detection issues, includes whatever system headers are appropriate etc. You're free to edit `duk_config.h` manually or add explicit support for your platform (the header is autogenerated from various metadata and header snippets).

**Comment by Jan-Kow** [comment]
@svaarala Thanks! I edited my post (have seen that I was in ``duk_config.h`` too late). I'll checkout all the headers tomorrow and will response then.

**Comment by svaarala** [comment]
If you're working on a platform which has minimal standard header support you may need to edit `duk_config.h` manually or add a new platform and recreate a `duk_config.h` file. Some guidance for that is described in: https://github.com/svaarala/duktape/blob/master/doc/duk-config.rst.

**Comment by Jan-Kow** [comment]
So I checked out the config-dir and found out that the only headers I need are:
```
#include <sys/types.h>
#include <sys/endian.h>
#include <sys/param.h>
#include <sys/time.h>
#include <time.h>
```
It looks a little bit confusing because I checked out the ``duk_config.h`` and saw that also stdio etc. is used. Where can I find these includes in the config-dir?

**Comment by Jan-Kow** [comment]
Found it myself in https://github.com/svaarala/duktape/blob/master/config/header-snippets/platform_sharedincludes.h.in

**Comment by svaarala** [comment]
The platforms supported by `duk_config.h` directly assume a minimal set of standard headers (like stdio.h etc). I've worked on some platforms where these are not available at all - for these platforms the only real solution right now is to simply edit `duk_config.h` manually, comment out the unavailable includes, and provide alternatives instead. When doing so it may be easiest to generate a single-platform `duk_config.h` using `genconfig.py` instead of the multi-platform autodetecting default header.

**Comment by Jan-Kow** [comment]
I will use the manual edit for testing and when I get to a release/runnable state I will use ``genconfig.py``. Great to see that Duktape is open for new platforms!

**Comment by svaarala** [comment]
@Jan-Kow Definitely :-) The current genconfig and `duk_config.h` setup is also open to change, especially to support platforms without standard headers. I've worked with a few such platforms and hopefully the process would get easier over time. Let me know what issues you hit so we can see what could be improved.
