### ISSUE TITLE
Regexp parse error - [^[]]

### ISSUE THREAD

**Issue by ghost** [svaarala/duktape#86]
Hey @svaarala,

Found another "real world" regexp parse error that is pretty widely expected.

``` js
[^[]]
```

Not `[`, followed by `]`.

For more context, I was trying to get the CoffeeScript parser itself running in Duktape. It uses a pretty gnarly regexp to parse regexps themselves.

https://github.com/jashkenas/coffeescript/blob/8e4fb1b9378a08cbeafd3659995de178d4c81588/src/lexer.coffee#L816-L829

Related #74.

**Comment by josh** [comment]
Closing out as a "wontfix". It seems like its more likely a configurable regexp backend will be the solution to this.

**Comment by svaarala** [comment]
There are two activities in resolving these issues - one is a replaceable RegExp backend and the other is improving the Duktape built-in regexp engine to support more expressions, so I'll reopen this but unassign it from 1.3.0.

**Comment by svaarala** [comment]
This now works in master so closing:

```
duk> /[^[]]/.test('x]')
= true
duk> /[^[]]/.test('[]')
= false
```
