### ISSUE TITLE
Remove ArrayBuffer number indices

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#870]
Standard ArrayBuffer values don't have virtual index properties like `arrayBuf[3] = 0x98`, but Duktape currently provides them.

For consistency these indices would also need to be removed from plain buffers (which mimic ArrayBuffer instances in 2.x). However, this would make plain buffer handling a little bit awkward: the main goal of using plain buffers over ArrayBuffer and typed arrays (Uint8Array etc) is to save memory; without index properties one is forced to create e.g. a `Uint8Array` over the plain buffer to get access to the bytes. This is counterproductive to saving memory.

Options:
1. Keep virtual number indices for both ArrayBuffers and plain buffers.
2. Keep virtual number indices for plain buffers but not ArrayBuffers. This would be more in line with standard ArrayBuffer behavior but rather confusing if plain buffers had indices and ArrayBuffers didn't.
3. Remove the indices from both plain buffers and ArrayBuffers. Most in line with E6 but basically means memory efficient buffer handling is only possible in C.
4. Change plain buffers to mimic Uint8Arrays but without a `.buffer` property. Remove virtual indices and other non-standard properties from ArrayBuffer.

**Comment by fatcerberus** [comment]
Hm, this is indeed a dilemma.  Maybe making plain buffers act like an ArrayBuffer isn't really such a great idea...

On the other hand, keeping the indices shouldn't really be an issue.  Since E6 doesn't specify that they have to exist at all, providing them shouldn't a compatibility issue for real world code (as long as they are not enumerable).

**Comment by svaarala** [comment]
Right now I'm keeping the indices but making them non-enumerable.

Making plain buffers behave like ArrayBuffers seems otherwise the best candidate to simplify plain buffer behavior for Ecmascript code; I think it's at least better than the current situation. I'm open to better suggestions however :-) The C API is an easier issue because there's no existing code base or compliance to deal with.

**Comment by svaarala** [comment]
To clarify above: there's of course an existing code base for Duktape/C bindings, but it's not as limiting as the existing Ecmascript codebase. In practice code bases that benefit from using plain buffers instead of ArrayBuffers are very memory starved, and trade-offs for compliance are usually not that big of a deal there.

**Comment by svaarala** [comment]
I guess a reasonable compromise might be to have the index (and other non-standard) properties be enabled by default, and add a compliance option for removing all the non-standard properties. Compliance oriented environments (which quite likely won't need plain buffers) could just avoid using plain buffers and disable the extra properties.

**Comment by svaarala** [comment]
Current state is that the indices are present but non-enumerable. I'm leaving this open but unassigning from 2.0.

**Comment by svaarala** [comment]
This has probably been mentioned but one option is for plain buffers to mimic Uint8Array but lack a `.buffer` property. They would then have the number indices etc.

**Comment by fatcerberus** [comment]
That would be in line with Node.js Buffer also being a subclass of Uint8Array.  Conceptually it's a byte array, so that makes a lot of sense.

One thing with that is, if buffer object support is disabled, we now have an "object" which claims to be a Uint8Array without anything that claims to be an ArrayBuffer.  It's maybe a bit weird to have a subtype without the parent type being accounted for.  That's probably not a blocker, but something to think about at least.

**Comment by svaarala** [comment]
Hmm, I'm not sure what you mean: Uint8Arrays don't inherit from ArrayBuffer? The inheritance chain is:

Uint8Array instance -> Uint8Array.prototype -> %TypedArrayPrototype -> Object.prototype

**Comment by fatcerberus** [comment]
Yeah, you're right.  I guess there's a dependency relation still, but it's not a big deal since in standard Ecmascript you can do `new Uint8Array(10)` without having an existing ArrayBuffer.  So maybe not so strange after all. :)

**Comment by svaarala** [comment]
Yeah, that's why I said it would lack a `.buffer` property.

But not sure if it's better to have an ArrayBuffer with non-standard index properties or a non-standard Uint8Array with no `.buffer` property. Plain buffer behavior is non-standard in any case because it doesn't have a property table, so it's just a matter what causes the least surprises *if* you decide to use plain buffers in a way which is visible to script code.

**Comment by fatcerberus** [comment]
For my part, the non-standard Uint8Array seems less surprising.  Standard ArrayBuffer instances don't have index keys, so if you have something that claims to be an ArrayBuffer, I'd find code that indexes it directly to be strange.

**Comment by svaarala** [comment]
I'll make that change - not sure where to put the `.allocPlain()` and `.plainOf()` bindings though. `Uint8Array.prototype` is an odd place at least for '.allocPlain()`. ArrayBuffer would also be odd if plain buffers mimic Uint8Arrays. Uint8Array constructor would be a logical place, but it'd unnecessarily pull in the constructor, the %TypedArray% object etc, just for a few custom calls. Duktape object is a possible place but the methods would then need renaming.

**Comment by fatcerberus** [comment]
Hm, maybe `Buffer.allocPlain()`?  Node.js Buffer is itself a subtype of Uint8Array now, so maybe that could work.

**Comment by svaarala** [comment]
Right, but that'd pull in the Buffer binding which would be equally bad as pulling in the ArrayBuffer binding :-/

Note that I'm mainly concerned about the "stripped" low memory case which should minimize object count. When bufferobject support is enabled, Uint8Array constructor would be as good place as any.

There's still the option of just removing the custom buffer calls. Plain buffers could be created from C code; getting the plain buffer underlying a buffer object would also only be possible from C code. Low memory targets eliminating the buffer objects (or rather minimizing them) would then need to create plain buffers exclusively from C code, adding a custom binding if they needed to be created from Ecmascript code.
