### ISSUE TITLE
Missing stack trace line numbers

### ISSUE THREAD

**Issue by harold-b** [svaarala/duktape#876]
Hello, it's been a while! :) Finally managed to get back to Duktape.

I ran into an issue with the augmented errors... Not sure if I'm missing a config macro or something. But, when executing a simple js file (also tried others):

``` javascript
var foo = "foo";
var bar = "bar";

function throwTest()
{
    throw new Error( "this is an error" );
}

function main()
{
    throwTest();
}

main();
```

I get a stack trace with missing line numbers:

>JS Error ocurred @ fmain.js:0:
Error: this is an error
    at throwTest (fmain.js:0)
    at main (fmain.js:0)
    at [anon] (fmain.js:0)
    at global (fmain.js:0) preventsyield

I'm simply using:
``` c
duk_push_lstring( );
duk_push_string( );
duk_pcompile();
duk_pcall();
```

With no flags, though I've tried all kinds of combinations and API calls ( `duk_compile_file`, `duk_compile_raw`, `duk_eval_string`, ... ) and I get the same result with all of them. I'm using the following config macros:

``` c
#define DUK_USE_FASTINT

#define DUK_USE_DEBUGGER_SUPPORT
#define DUK_USE_DEBUGGER_FWD_LOGGING
#define DUK_USE_DEBUGGER_FWD_PRINTALERT
#define DUK_USE_DEBUGGER_PAUSE_UNCAUGHT
#define DUK_USE_DEBUGGER_INSPECT
#define DUK_USE_DEBUGGER_DUMPHEAP
#define DUK_USE_INTERRUPT_COUNTER
#define DUK_USE_DEBUGGER_THROW_NOTIFY
```
Any idea what I'm missing? I'm running off of the [v1.5.0](https://github.com/svaarala/duktape/tree/v1.5.0) tag.

Checking the error object's lineNumber also always contains a 0. :(

Cheers!

**Comment by svaarala** [comment]
If you're compiling with the default `duk_config.h` line numbers should always appear in stack traces.

Re: the options you're using, how are you actually enabling them? Are you editing the default `duk_config.h` manually or running `genconfig.py` to override specific defaults?

**Comment by harold-b** [comment]
I'm setting them via the duk_custom.h. I read that it's been deprecated, but it's enabling the macros nonetheless. I've also dumped them on top of the duk_config.h as well just in case, but I get the same output...

**Comment by svaarala** [comment]
Hmm, if defaults are used for other defines (than the ones you override) then I don't have an idea why stack trace line numbers would be incorrect :/

**Comment by svaarala** [comment]
This is what I get when running with "duk":

```
$ ./duk.O2.150json _test.js
Error: this is an error
    at throwTest (_test.js:6)
    at main (_test.js:11)
    at global (_test.js:14) preventsyield
error in executing file _test.js
```

**Comment by harold-b** [comment]
Let me try with an official release and see what I get.

**Comment by harold-b** [comment]
Nope, same thing... Wonder what I'm doing wrong...

I dug around a bit earlier and noticed when it gets to the duk_error_augment.c funcs, `thr->compile_ctx` is always NULL. Is it supposed to be a valid pointer at that point?

**Comment by svaarala** [comment]
Only if the error is thrown during compilation (usually a SyntaxError). This shouldn't be the case because we're already running the code.

**Comment by harold-b** [comment]
OK got it, yea it's not during compilation but during execution... I forced it to cause a compilation error and the line numbers are reported there, but not during runtime errors... Hmm what can I have messed up?  =/

**Comment by svaarala** [comment]
I'm not sure if this is the cause, but if the function being executed were missing an internal pc-to-line mapping (internal property `_Pc2line` where `_` is 0xFF) the line numbers would come out as zero.

**Comment by harold-b** [comment]
So once I run `duk_pcompile()`, I can test the func object at the top of the stack for that property to confirm this?

**Comment by svaarala** [comment]
For the stacktrace to come out right all functions in the stacktrace should have that property (those with the property missing would report zero linenumber). But as a quick test you could check that property:

    duk_get_prop_string(ctx, -1, "\xff" "Pc2line");
    ...

**Comment by svaarala** [comment]
(Sorry, off to bed: I'll check this issue in the morning.)

**Comment by harold-b** [comment]
Ok let me give this a go.

The other functions in the example script are stored in the function object returned by pcompile as properties, correcy?

**Comment by harold-b** [comment]
No problem, thanks always for your prompt help Sami :)

**Comment by fatcerberus** [comment]
Nothing to contribute on this, just to say it's good to see someone else is finding Throw notify useful.  I implemented that feature :)

**Comment by harold-b** [comment]
Hey @fatcerberus Bruce, nice to see you again! Thanks for contributing the feature ;)

**Comment by harold-b** [comment]
Well this is embarrassing... :cold_sweat: 

It turned out to be a bug (typo) in my realloc function which is passed to duktape on heap creation. I don't know how the whole system wasn't breaking down, rather than just the line numbers.

I'm getting the correct output now:
>JS Error ocurred @ fmain.js:6:
Error: this is an error
    at throwTest (fmain.js:6)
    at main (fmain.js:11)
    at global (fmain.js:14) preventsyield

Nonetheless, Thanks for taking the time to engage with me, @svaarala  :+1:

**Comment by svaarala** [comment]
@harold-b No worries, very good you found the issue :) It's indeed quite interesting the only thing broke was the line numbers! :game_die:

**Comment by svaarala** [comment]
@harold-b It'd be interesting to know if any reasonable self test would have caught this. Perhaps `DUK_USE_SELF_TESTS` could do a few alloc/realloc/free tests before creating the heap? At least it might trigger a segfault early on if the allocator had some bugs in the required guarantees (happens relatively often especially with more complex custom allocators).

**Comment by harold-b** [comment]
That might be useful, yeah.

In my case, I already had in place some start/end guards to check for overruns/underruns. But my mistake was that I accidentally was copying from the `udata` pointer, instead of the old `ptr`, into the new allocation on my `duk_realloc_function`! Woops!

I suppose to test for that particular case you would have to copy the contents of a `duk_alloc_function` allocated buffer into a temporary stack allocated one, then call `duk_realloc_function` and compare the contents of the stack allocated one with the new one.

**Comment by svaarala** [comment]
Ok, so for example:

- Alloc 16 bytes, fill with marker bytes
- Realloc to, say, 1024 bytes (which probably triggers an actual realloc)
- Compare marker bytes from beginning of reallocated buffer

**Comment by harold-b** [comment]
Exactly that! :+1:

**Comment by svaarala** [comment]
@harold-b If you have energy, it'd be interesting to hear if #877 (with `DUK_USE_SELF_TESTS` enabled) would have caught your issue :-)

**Comment by harold-b** [comment]
OK I can give it a go now, I'll report back in a bit.

**Comment by harold-b** [comment]
Output without the bug enabled: :white_check_mark: 
>JS Error ocurred @ fmain.js:6:
Error: this is an error
    at throwTest (fmain.js:6)
    at main (fmain.js:11)
    at global (fmain.js:14) preventsyield

Output with the bug :beetle:  enabled:
>JS Error ocurred @ fmain.js:0:
Error: this is an error
    at throwTest (fmain.js:0)
    at main (fmain.js:0)
    at global (fmain.js:0) preventsyield

Output with the bug :beetle: and `DUK_USE_SELF_TESTS` enabled:
>self test(s) failed

Well done :+1:

**Comment by svaarala** [comment]
Thanks for testing -- maybe the self test will help someone else later on :)

**Comment by harold-b** [comment]
No problem. Yes indeed these kind are tough to track down.
