### ISSUE TITLE
Incorrect line number in stack trace for thrown error

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#879]
Found another one of these, it's been a while. :)

For the following code:
```javascript
function HPGauge(capacity, sectorSize, color, maxSectors)
{
	if (arguments.length < 1) {
		throw new RangeError("expected 1 or more arguments");
	}

	sectorSize = sectorSize !== undefined ? sectorSize : 100;
	color = color !== undefined ? color.clone() : Color.Lime;
	maxSectors = maxSectors !== undefined ? maxSectors : null;

	this.borderColor = new Color(0, 0, 0, color.alpha);
	// ...
}
```

If the `Color` constructor throws an error, the stack trace will show that HPGauge is executing line 9 (`maxSectors = ...`) instead of line 11 as should be the case.

Duktape version is 1.5.0.

**Comment by fatcerberus** [comment]
I should mention that the stack trace in question was retrieved via the debugger GetCallStack command.  I don't yet know if `Duktape.act()` or the Error object `.stack` property have the same bug or not.

**Comment by svaarala** [comment]
Running in master:

```js
function Color() {
    throw new Error('aiee');
}
Color.Lime = { alpha: 'dummy' };

function HPGauge(capacity, sectorSize, color, maxSectors)
{
    if (arguments.length < 1) {
        throw new RangeError("expected 1 or more arguments");
    }

    sectorSize = sectorSize !== undefined ? sectorSize : 100;
    color = color !== undefined ? color.clone() : Color.Lime;
    maxSectors = maxSectors !== undefined ? maxSectors : null;

    this.borderColor = new Color(0, 0, 0, color.alpha);
    // ...
}

HPGauge(10, 1);
```

Shows:

```
$ ./duk /tmp/foo.js
Error: aiee
    at Color (/tmp/foo.js:2) construct preventsyield
    at HPGauge (/tmp/foo.js:16)
    at global (/tmp/foo.js:20) preventsyield
```

That line (16) seems to match with the `new Color()` call, i.e. this line:

```
    this.borderColor = new Color(0, 0, 0, color.alpha);
```

So maybe this is some debugger related issue.

**Comment by svaarala** [comment]
For me the debugger line number is also correct (16) when the uncaught error causes a pause. I'm running from master though, I'll try 1.5.0 next.

**Comment by svaarala** [comment]
Hmm - it might matter if the `Color` constructor is native or not?

**Comment by svaarala** [comment]
With v1.5.0 the debugger also reports the correct line (16) in the above example.

**Comment by svaarala** [comment]
Ok, so changed `Color` to be native by using `Duktape.Thread` in its place:

```js
Color = Duktape.Thread;
Color.Lime = { alpha: 'dummy' };

function HPGauge(capacity, sectorSize, color, maxSectors)
{
    if (arguments.length < 1) {
        throw new RangeError("expected 1 or more arguments");
    }

    sectorSize = sectorSize !== undefined ? sectorSize : 100;
    color = color !== undefined ? color.clone() : Color.Lime;
    maxSectors = maxSectors !== undefined ? maxSectors : null;

    this.borderColor = new Color(0, 0, 0, color.alpha);
    // ...
}

HPGauge(10, 1);
```

This also reports the correct line (this time 14) for the constructor error in v1.5.0:

```
$ ../../duk foo.js
TypeError: type error (rc -105)
    at Thread () native strict construct preventsyield
    at HPGauge (foo.js:14)
    at global (foo.js:18) preventsyield
error in executing file foo.js
```

And same in v1.5.0 debugger. So unfortunately I cannot reproduce this :(

**Comment by fatcerberus** [comment]
By the way `HPGauge` is a constructor.  Does calling it as such affect anything?  Also yes, in my case `Color` is native.

**Comment by svaarala** [comment]
Calling it as a constructor shouldn't affect stack trace line numbering, at least in any way I can think of.

**Comment by fatcerberus** [comment]
I figured maybe the constructor call would affect it since the generated bytecode would be different for a normal call vs. a constructor call.

Anyway, I'll look at this later and try to come up with an isolated test case.

**Comment by svaarala** [comment]
That's true, but the difference is mostly that instead of a `CALL` a `NEW` is emitted. There are subtle possibilities besides that of course, but at least in my test it didn't matter :/

**Comment by fatcerberus** [comment]
Strange: When I try to reproduce the bug in isolation (as you've been doing), the correct line number is reported.  It seems like maybe it depends on the contents of the callstack?  That'd be weird but it seems to be the case.

**Comment by fatcerberus** [comment]
Okay, now it randomly started working correctly with the same code path and callstack.  Not sure what happened, maybe a bug in my debug client.  I'll keep this issue open for a bit in case I can reproduce it, if not I'll close it.

**Comment by svaarala** [comment]
Ok, sounds good. One thing I remembered is that you experimented with some transpiling; is there any chance the target was running a different (e.g. transpiled) source file than what was visible for the debugger?

**Comment by svaarala** [comment]
The other thing that might happen is that the debug client had, for some reason, not received/processed the latest Status notify. Or Duktape hadn't, for some reason, sent a Status notify with the right PC/line (but then, the fact that we're paused is a Status notify which should also atomatically contain the PC/line).

**Comment by fatcerberus** [comment]
No, the code being executed was JS.  On-the-fly transpilation proved to be too much of a performance issue so I decided to remove it for minisphere 4.0.

The incorrect line number was for the call stack entry below the source of the error (a native constructor), so a lost Status notify seems unlikely.

**Comment by svaarala** [comment]
I agree, that sounds pretty unlikely.

**Comment by fatcerberus** [comment]
I haven't been able to reproduce this.  I suspect now that it might have been user error, i.e. I edited the file while minisphere was running. :P  I'll close the issue.
