### ISSUE TITLE
Add links to external projects using Duktape

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#88]
There's been several requests to add links to external projects using Duktape. The intent would be to point to as many different kinds of projects where Duktape has been used, not to provide an exhaustive listing.

If you're using Duktape in a reasonably sized project and would like to be mentioned, you can either e-mail me directly or comment on this issue.

**Comment by megous** [comment]
Megatools 2.0 uses duktape extensively (in the dev branch): https://github.com/megous/megatools

**Comment by svaarala** [comment]
@megous Added the following to master:

- https://github.com/svaarala/duktape/commit/0fcc4f24434840e3cda1d5d0ec2977887406463a

**Comment by megous** [comment]
Thank you. :+1:

**Comment by farvardin** [comment]
the fantasy console TIC-80 is using Duktape too:

https://github.com/nesbox/TIC-80/search?q=duktape&type=code
