### ISSUE TITLE
Add duktape-android to ProjectsUsingDuktape wiki page

### ISSUE THREAD

**Issue by JakeWharton** [svaarala/duktape#880]
https://github.com/square/duktape-android#readme

We've embedded the sources for compilation out to an Android library, added integrations into the OS, and added support for both binding Java to JS and also JS to Java.

**Comment by svaarala** [comment]
Sounds great, quite nice that JS/Java (and vice versa) bindings work. Looking forward to using this at some point :-) The Wiki edit is tracked by https://github.com/svaarala/duktape-wiki/pull/132 so I'll close this.
