### ISSUE TITLE
After  duk_pcompile_file, How to call the JS function?

### ISSUE THREAD

**Issue by 11nk** [svaarala/duktape#883]
For example, A JS file has three functions like this

```javascript
function func(v)
{
	return 1;
}

function func2(v)
{
	return 2; //
}

function func3(v)
{
	return 3; //
}
```
In C code, I call the function duk_pcomile_file to compile it
Then how to call the JS function in C code

**Comment by fatcerberus** [comment]
Assuming your script isn't strict mode (in which case the functions wouldn't go to global scope), you can just:

```c
duk_get_global_string(ctx, "func");
duk_call(ctx, 0 /*nargs*/);
/* return value of function is now on top of value stack */
```

**Comment by 11nk** [comment]
@fatcerberus  I test it . But failed, here is my code
`
duk_contex * ctx = duk_create_heap_default();
//duk_push_global_object(ctx);
int ret = duk_pcompile_file(ctx, 0, "test.js");
duk_bool_t succ = duk_get_global_string(ctx,"hello");
// succ = 0 . failed here
duk_call(ctx,0);
`

**Comment by fatcerberus** [comment]
I see what's wrong: You only compiled the script, you didn't actually execute it.  `duk_*compile*()` leaves a function on the stack without running any code.  You either have to execute the compiled script using `duk_call()` or for convenience, you can use `duk_peval_file()`:
```c
duk_context * ctx = duk_create_heap_default();
int ret = duk_peval_file(ctx, "test.js");
duk_get_global_string(ctx,"hello");
duk_call(ctx, 0);
```

**Comment by 11nk** [comment]
Thinks.It's okay.
