### ISSUE TITLE
Print flattens arrays

### ISSUE THREAD

**Issue by ocrow** [svaarala/duktape#905]
evaluate (e.g. in the REPL): 

duk> [[1,2],[3,4,[5,6]]];
= 1,2,3,4,5,6

Why does duktape flatten arrays on output? This seems confusing.

**Comment by svaarala** [comment]
It doesn't actually flatten arrays, but string coerces them. String coercion of an array (in any engine) is comma joined list of string coerced elements:

```
duk> a = [1,2,3,[4,5]]; String(a)
= 1,2,3,4,5
```

**Comment by svaarala** [comment]
By the way, there's a "console" provider in the Duktape master (extras/console) which JX-coerces e.g. `console.log()` arguments rather than just string coercing them:

```
$ ./duk.O2
((o) Duktape [linenoise] 1.99.99 (v1.5.0-438-ga35d09e-dirty)
duk> console.log([1,2,3,[4,5]])
[1,2,3,[4,5]]
duk> console.log({foo:[1,2,3,[4,5]]})
{foo:[1,2,3,[4,5]]}
```

While print() just prints strings and string coercion is (at least arguably) appropriate for it, `console.log()` and related calls are intended for debug logging so that using serialization makes maybe more sense for them.

**Comment by fatcerberus** [comment]
To illustrate what @svaarala is saying, output from Node.js when explicitly calling `.toString()` on the array:
```
C:\Users\fatce>node
> [1,2,3,[4,5]].toString()
'1,2,3,4,5'
>
```

Of course Node will show the real structure of the array if you omit the `.toString()` bit as it uses a custom JSON-like provider for that.  Maybe `duk` could do something similar, e.g. JX encoding the result of expressions?

**Comment by svaarala** [comment]
@fatcerberus At least for me a `print()` binding would naturally string encode its arguments. It's also what the `print()` browser bindings do, e.g. on Firefox:

```
print([1,2,3,[4,5]])
"1,2,3,4,5"
```

The `console.log()` and related bindings are intended to dump object structure, and the `extras/console` implementation does that using JX, falling back to string coercion if JX encoding fails (e.g. due to a loop).

**Comment by fatcerberus** [comment]
I agree, string coercion makes the most sense for `print()`.  I was referring specifically to `duk`'s output - it might make more sense for the command-line tool to use a more verbose format for the result of expressions, like Node does.

**Comment by svaarala** [comment]
Ah, I see what you mean now. I agree with that, maybe `duk` could essentially use the same approach as `extras/console`, i.e. attempt JX and fall back to `String(x)` if that fails.

**Comment by ocrow** [comment]
The extras/console approach seems like it would be generally more useful than coercing to string. 

For comparison, it looks like the Node console descends objects and arrays to a depth of three, then prints "[Object]" for any objects at level four. That's true for both expressions evaluated in the repl and console.log().

**Comment by svaarala** [comment]
One simple change would be for `duk` to try `console.log(result)` and if that fails, do string coercion as before. This works if the extras/console support is enabled when compiling `duk` (which is the default in the dist Makefile.cmdline).

**Comment by fatcerberus** [comment]
Maybe have it keep a heap pointer around for `console.log` in case the user does `delete console.log` or something at the command line. :)

**Comment by svaarala** [comment]
True. Well, it'd also be easy to just copy paste the JX formatting from extras/console, it's just:

```c
	duk_eval_string(ctx,
		"(function format(v){"
		    "try{"
		        "return Duktape.enc('jx',v);"
		    "}catch(e){"
		        "return ''+v;"
		    "}"
		"})");
```

**Comment by svaarala** [comment]
That's actually not perfect either because it depends on `Duktape.enc` existing. Another closure wrapper or stash would be needed to secure that.

**Comment by fatcerberus** [comment]
If `Duktape.enc` doesn't exist it will throw and hit the fallback in the catch.  The real problem is if Duktape.enc gets _replaced_, i.e. with another function.

**Comment by svaarala** [comment]
Agree, this applies to the console extra too at present. I don't see that as a really big issue unless one is working with actively hostile code though :)

**Comment by svaarala** [comment]
Ok, #906 has a fix for the console-extra Duktape.dec() runtime lookup. The revised code is:

```
	duk_eval_string(ctx,
		"(function () {"
		    "var E=Duktape.enc;"
		    "return function format(v){"
		        "try{"
		            "return E('jx',v);"
		        "}catch(e){"
		            "return ''+v;"
		        "}"
		    "};"
		"})()");
```

**Comment by fatcerberus** [comment]
That was a quick fix. :)
