### ISSUE TITLE
Rework tooling into a combined config-and-prepare-sources model

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#927]
At the moment there is a `make_dist.py` tool which creates an end user distributable package. The dist tool creates a directory structure and copies over files, config metadata, etc. It also autogenerates some code (like Unicode tables) and creates the separate and combined end user distributable sources, as well as a few `duk_config.h` examples. The end user distributable doesn't include the ability to combine the sources from scratch.

This model doesn't work well for a few cases:

- ROM built-ins involve automatic generation of object initializers, driven by YAML metadata which may also be supplied by the application writer (e.g. to embed custom bindings into ROM).
- Some config options should affect the dist processing. For example, if buffer object support is disabled, the corresponding buffer built-in bindings should be dropped (rather than left in but implemented as error throwing stubs like at present).

Those two cases need a combined step which both prepares a `duk_config.h` header and simultaneously prepares sources for compilation. The inputs to this process include everything genconfig currently accepts (`DUK_USE_xxx` options) but also custom built-in YAML metadata and other miscellaneous options (like whether to use `#line` directives or not). The combined tool could provide shortcut options like `--no-es6` which can be implemented based on YAML metadata tags in `builtins.yaml`.

Tasks:

- [x] Move scripts that should be in the end user distributable into `tools/` and keep scripts not part of the distributable in `util/`.
- [x] Fix `make_dist.py` and other basic build steps for the relocation. At this point builds and disting works as before.
- [x] Split `make_dist.py` into two parts. One part creates the end user distributable directory hierarchy and copies files. Another part is a separate utility for generating Unicode tables, combining sources, etc. This second utility ("prepare source") goes into the distributable, and make_dist.py would run the utility to generate prepared sources with default configuration for convenience (as is the case in the distributable now).
- [x] Merge genconfig with the prepare source utility to form an initial config-and-prepare utility which doesn't yet take advantage of the combined nature of the process.
- [x] Implement initial support for dropping optional bindings entirely rather than having them present with functions that always throw.
- [x] Fix testrunner jobs which run genconfig to use config-and-prepare instead
- [x] Fix example scripts (like util/example_rombuild.sh) also
- [x] Tool naming; `prepare_sources.py` is not an ideal name for "the frontend"
- [x] Fix prepare_sources.py to create either separate or combined sources into the target directory (with no further hierarchy which is confusing); Unicode handling will be slow, figure out if there's any way to speed it up
- [x] Remove dist/config/genconfig.py copy
- [x] Remove make_dist.py support for --rom-support etc
- [x] Documentation updates, dist README updates, etc
- [x] Add an example Makefile / script to illustrate prepare-and-config usage

Later pulls can then implement better combined config-and-prepare processing.

**Comment by fatcerberus** [comment]
What would this mean for someone building Duktape from source?  Does it become a two-step process similar to the venerable `./configure` and `make`?

**Comment by svaarala** [comment]
The distributable would include combined sources and `duk_config.h` for the default configuration as before. If you wanted to create a custom configuration, you'd say something like:

```
$ python tools/prepare.py --no-es6 -UDUK_USE_BUFFEROBJECT_SUPPORT \
      --single-file --rom-builtins --rom-auto-lightfunc --output-directory my-duktape-src
```

For a single file case the result would be `duktape.c`, `duktape.h`, and `duk_config.h` which you would then compile like before. The important change is that preparing `duk_config.h` and the source files happens in the same process, because they are related in some cases (like dropping built-ins).

**Comment by fatcerberus** [comment]
I like that setup then, in some ways it actually seems cleaner than the current method.
