### ISSUE TITLE
Is it possible for supporting SWIG

### ISSUE THREAD

**Issue by aseaday** [svaarala/duktape#930]
I'd love to use SWIG to write a binding. So It is there any suggestion or plan about SWIG extended support.

**Comment by svaarala** [comment]
I looked into SWIG very early on and it seemed to me it'd generate somewhat awkward bindings. But that was just a quick review so I'm not sure if that would actually be the case. What would need to be changed concretely to support SWIG?

**Comment by aseaday** [comment]
The problem is that,  We build a IoT framework both on duktape and V8, I want to give a driver framework for C binding. So I want they can be an same source.

**Comment by svaarala** [comment]
I see, makes sense. SWIG in that use case would then provide good enough bindings more quickly than writing bindings for two engines manually.

SWIG already has Javascript support for a few engines so it should hopefully be quite doable.

**Comment by hypoalex** [comment]
I have a binding largely working at https://github.com/hypoalex/swig/tree/dukswig

The examples are out-of-tree in a workspace at https://github.com/hypoalex/dukswig

In order to get this upstreamed, the duk_shell.cxx test harness needs to be implemented so the tests will run in tree (this requires a small module loader and a console.log implementation).

`NewPointerObj` and `ConvertPtr` are highly suspect, and tricky to get right.

**Comment by denisdemaisbr** [comment]
the C/API of Duktape are too similar* to Lua, sometimes, 'port from lua' will works fine.

**Comment by hypoalex** [comment]
The PR at https://github.com/swig/swig/pull/791 actually works and passes 100% of the test suite.

The APIs are similar, but obviously not the same thing...

**Comment by denisdemaisbr** [comment]
@hypoalex  nice work!
do can share the patch or a version ziped ?

duk_shell -> nice works (dynamic load module)

suggestion: maybe the generated module can 'load' definitions from duktape/build  [ CFLAGS ] easyly!

**Comment by hypoalex** [comment]
You can just build SWIG from https://github.com/hypoalex/swig

The blockers to an upstream merge are essentially just C89 backporting stuff, so if anyone wants to do that it'd be really cool.

**Comment by aseaday** [comment]
what does duk_shell means?

**Comment by hypoalex** [comment]
You can run the SWIG shell from a built copy of SWIG.

`Tools/javascript/javascript -duk`

**Comment by aseaday** [comment]
It throws terminating with uncaught exception of type char const*

**Comment by hypoalex** [comment]
Well, I have no idea what you're talking about without more context... open an issue at `hypoalex/swig` and describe the exact steps to reproduce it and I'll try to get back to you by tomorrow.

**Comment by svaarala** [comment]
There's now SWIG support being worked in another repo, so I'm closing this issue.
