### ISSUE TITLE
Implement TextDecoder/Encoder objects

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#961]
This allows writing and reading strings to/from ArrayBuffers and is implemented by most browsers:
https://encoding.spec.whatwg.org/

Currently manipulating strings embedded in a buffer requires using the Node.js Buffer object or `String.fromBuffer()` (Duktape 2.0+), both of which are nonstandard and not likely to exist outside of Duktape (and Node.js of course).  TextDecoder seems to be the standard way to do it with ArrayBuffers, since `ArrayBuffer#toString()` just gives "[object ArrayBuffer]".

It would be nice to have this standard implemented in Duktape, even if it only provides UTF-8 support without all the other encodings.

**Comment by svaarala** [comment]
Related: https://github.com/svaarala/duktape/pull/864#issuecomment-233082556

**Comment by svaarala** [comment]
`String.fromBuffer()` provides a different primitive because it's a 1:1 byte-for-byte conversion with no encoding. That's useful in some situations and is necessarily Duktape custom because it deals with how strings are represented internally in Duktape.

**Comment by fatcerberus** [comment]
Would it be possible to reuse the code for Buffer#toString() to implement `TextDecoder`?  That might help to not increase the footprint too much.  `TextEncoder` probably can't reuse anything though.

**Comment by fatcerberus** [comment]
Actually `Buffer.write()` takes a string and encoding argument, so yeah, if we only support UTF-8 it should be possible to reuse all the string encoding/decoding code for Node.js buffer for `TextEncoder` and `TextDecoder`.  I'll look into this either later today or tomorrow.

The feature should be optional, placed behind a configuration option, since not all applications will need the functionality.  It also depends on bufferobject support.

**Comment by svaarala** [comment]
Hmm, I should prototype how the configure.py-driven truly optional built-ins work. With that in place it should be straightforward to add stuff without impacting low memory targets. Of course, there's still the question of what functionality belongs in the core and what doesn't. There are clear cases but also some grey area cases.

**Comment by fatcerberus** [comment]
Hm, I could have sworn there was an issue in github to track a proposed feature for pluggable text encodings, but apparently not.

**Comment by fatcerberus** [comment]
Another option would be to provide `TextEncoder` and `TextDecoder` as an extra in the dist; since they're not part of the Ecmascript specification, they don't technically belong in the core.

**Comment by fatcerberus** [comment]
Just implemented basic Encoding support in minisphere.  I posted an issue on the minisphere repo since the initial implementation is hopelessly non-compliant and needs to be fixed before minisphere 5.0:

* https://github.com/fatcerberus/minisphere/issues/73

`TextDecoder#decode()` just does the equivalent of `String.fromBuffer()`!

As I work towards improving the implementation, maybe I'll open a Duktape pull to add a new extra. :)

**Comment by svaarala** [comment]
Yeah, I'm not sure if this is better as an extra or not. There are many factors involved, but it makes for something to be in the core at least when most (not necessarily all) of these are true:

- It's a standard or de facto standard feature and/or generally expected
- It's useful to a large variety of applications, i.e. generic in nature
- There's some benefit in implementing it as an internal rather than external feature; e.g. some operations are not otherwise possible (weak references for example) or maybe the internal implementation can share the code

Now with the capability to make built-ins truly optional (and thus free of footprint impact) adding bindings to the core implementation has less conflict with low memory targets.

String encodings seem like a pretty core feature. I'm not sure how to handle the encodings though - supporting a very large number of encodings means using an external library (or a lot of work ... :) and Duktape is generally UTF-8 (CESU-8) only now. Making it pluggable might be useful, but that's not necessarily that different to implementing it as an external module.

**Comment by fatcerberus** [comment]
For TextEncoder, the spec requires only UTF-8 and UTF-16.  TextDecoder supports a whole bunch of legacy encodings, but I'm not sure if they're all required.  I'll have to give it a closer look.

**Comment by fatcerberus** [comment]
Am I technically out of compliance if the utf-8 encoder actually encodes to CESU-8 rather than "proper" UTF-8?  I think so, but I'm not actually sure.

**Comment by fatcerberus** [comment]
Incidentally while I'm thinking about it, why _does_ Duktape uses CESU-8 internally instead of plain UTF-8?

**Comment by svaarala** [comment]
Ecmascript requires that strings be capable of representing all 16-bit codepoints, even invalid surrogate pairs. UTF-8 doesn't allow that.

Duktape doesn't actually use CESU-8 but rather extended UTF-8 which has a larger range (to cover all 32-bit codepoints) and CESU-8 for surrogate codepoints. So it's possible to use UTF-8 strings too and codepoints beyond BMP, but such strings are non-standard.

**Comment by fatcerberus** [comment]
Good to know, that means that what I'm doing right now:
https://github.com/fatcerberus/minisphere/blob/master/src/engine/pegasus.c#L3483-L3500

...is almost certainly not a compliant utf-8 encoder. :)

**Comment by fatcerberus** [comment]
With regard to this:
> It's useful to a large variety of applications, i.e. generic in nature

This definitely fits under that heading.  It compliments buffer object support nicely since there's no built-in facility in DataView for working with strings.  And it's standardized, so that's another one of your bullet points. :)

Honestly this would be a no-brainer to be in the core, except for the issue of all the encodings that it seems need to be supported.  That's why I suggested it to be an extra.

**Comment by svaarala** [comment]
Would you propose implementing those encodings from scratch or using an external encoding library?

**Comment by fatcerberus** [comment]
iconv seems to be the standard for UNIX based systems, so we could use that.  The situation on Windows is more complicated; I don't think there's any real standard, not even a de facto one.

For footprint reasons I think I would prefer implementing encodings from scratch over relying on external libraries.  8-bit encodings are easy enough to deal with using lookup tables (and these only need to go one way); dealing with Unicode encodings is a bit more involved but should be doable without too much fuss.

**Comment by fatcerberus** [comment]
Looking over the algorithms for decoding starting here:

* https://encoding.spec.whatwg.org/#the-encoding

The specification is very specific about how the handlers for each encoding must work.  Further, there are a few different "error modes" that affect what happens when invalid input is encountered.  I'd imagine most external libraries would be optimized for real-world use and probably too lenient for this purpose.

**Comment by fatcerberus** [comment]
@svaarala Where does Duktape look for the list of files when combining sources?  I'm experimenting with this but `configure.py` doesn't pick up the new .c file I added to `src-input/`, so I end up with a broken build.

**Comment by svaarala** [comment]
It's an explicit list in configure.py: https://github.com/svaarala/duktape/blob/master/tools/configure.py#L393-L512.

**Comment by fatcerberus** [comment]
Hmm, I thought I found that list and added the file but it still didn't make it into the combined source.I'll double check it later.

**Comment by fatcerberus** [comment]
Nevermind, turns out I didn't add the new file to `configure.py` after all.  I did so, and now everything's working as expected.

**Comment by fatcerberus** [comment]
Interestingly, Node.js 6.7.0 doesn't have the Encoding API, but Chrome does.  So it doesn't seem to be implemented in core V8--or if it is, Node is using an older V8 version without the feature.

**Comment by svaarala** [comment]
Did you check out alternatives to the WHATWG specification BTW?

**Comment by svaarala** [comment]
Spent some time looking at what people do and there doesn't seem to a real alternative besides Node.js Buffer, and the encoding API seems cleanest. So looks like we're on the right path indeed :)

Loosely related, there's also `atob()` and `btoa()` which could replace the custom base-64 bindings. Those functions operate on string data identifying Unicode codepoints U+00 to U+FF as "bytes" which is not 1:1 with current functionality though (which is buffer oriented) and that seems quite awkward. There've been suggestions to add buffer support to atob()/btoa() but not sure of that status; also some suggestions to shoehorn base-64 into the encoding API but that was abandoned too as far as I can tell :-/.

**Comment by fatcerberus** [comment]
> Did you check out alternatives to the WHATWG specification BTW?

I did but I don't remember finding anything as useful.  When I searched for how to do this about a year ago (around the time you first implemented buffer object support), `TextEncoder` was also what I found, so it seems like the WHATWG API is pretty much the de facto standard.

Somewhat related, `TextEncoder` according to the current spec only supports UTF-8.  Earlier versions supported UTF-16 as well; Chrome claims to have removed support in v53:
https://www.chromestatus.com/feature/5630760492990464

However I am still able to create a UTF-16 encoder in Chrome 53:
```js
> var te = new TextEncoder('utf-16');
undefined
> te.encode("foobar")
[102, 0, 111, 0, 111, 0, 98, 0, 97, 0, 114, 0]
```

**Comment by fatcerberus** [comment]
The encoding API is exposed also to web workers so it seems like a good fit for Duktape :)

**Comment by svaarala** [comment]
It seems like the best choice I agree. I'd prefer something simple like Python does:

```py
bytes = u'foo\ucafebar'.encode('utf-8');
```

Ideally there would just be a couple of methods in `String.prototype` with no further ceremony. Actually `Duktape.enc()` and `Duktape.dec()` were pretty much intended to be those two functions where the codec naming would be extended going forward. But it's a custom binding of course.

So overall even though the interface is maybe heavier than I personally prefer, and it doesn't provide base64, the encoding API seems like the best approach overall. A more standard base64 interface then remains an open issue.

**Comment by svaarala** [comment]
Just glancing through the wording in the Encoding specification, it's not very clearly specified where the attributes should reside (instance or prototype). At least in Firefox `.encoding` is an inherited getter. Maybe I'm just not used to it, but IDL in web specifications feels a bit roundabout at least when talking about concrete Javascript APIs. Just reading the IDL one might expect the property to be an ordinary "own property":

```
[Constructor(optional DOMString label = "utf-8", optional TextDecoderOptions options),
 Exposed=(Window,Worker)]
interface TextDecoder {
  readonly attribute DOMString encoding;
  readonly attribute boolean fatal;
  readonly attribute boolean ignoreBOM;
  USVString decode(optional BufferSource input, optional TextDecodeOptions options);
};
```

But the text talks about "encoding attribute's getter" etc.

I think I'll need to give WebIDL a readthrough and get better acquainted with it - it's used to describe many of the non-core APIs so it'd be a good idea to know it better :)

**Comment by fatcerberus** [comment]
FWIW: Chrome puts the properties and methods on the prototype as well.

**Comment by fatcerberus** [comment]
As for vagueness, this is just a guess but maybe that's the intent - it gives implementors more flexibility to implement the interface in whatever way is most comfortable.

**Comment by svaarala** [comment]
WebIDL is also technically somewhat language unaware and has a separate "mapping" for Javascript so there is some indirection by design.

**Comment by fatcerberus** [comment]
This what the WebIDL spec says about attributes:
https://www.w3.org/TR/WebIDL/#idl-attributes

I don't have time to read through it now but I'll give it a good look too when I get home.

**Comment by fatcerberus** [comment]
I read over some relevant sections of WebIDL's Ecmascript mapping and it seems that in most cases values are mapped by coercion - `undefined` by default coerces to a DOMString as the string "undefined", for example.  This goes against my intuition but I guess makes sense when mapping an interface to a duck-typed language.

I don't see anything in the WebIDL spec that indicates whether attributes must be accessors or not, though.  I'll keep digging.

**Comment by svaarala** [comment]
I'll try to take a look as soon as I can too. Comparing to Firefox and Chrome (and Node.js) gives some confirmation of interpreting the requirements right. Or at least to avoid surprising user code :)

**Comment by fatcerberus** [comment]
Here's something interesting: The latest draft of WebIDL (2016) requires that passing a RegExp where a dictionary (i.e. POJO) is expected throws a TypeError:
https://heycam.github.io/webidl/#es-dictionary

Behavior in the current W3C recommendation (2012) differs: `undefined` and `null` are not valid values at all, and there's no special handling for regexps:
https://www.w3.org/TR/WebIDL/#es-dictionary

The W3C recommendation is old enough that it makes no mention of buffer objects at all, so I'm thinking it's better to follow the 2016 draft.

**Comment by fatcerberus** [comment]
Read some more of WebIDL before.  Here's what I found:
* Interfaces map to global constructors without namespacing (e.g. `new TextDecoder()`)
* Attributes map to properties on the prototype
* Operators map to methods on the prototype
* What happens when attempting to modify a `readonly` attribute is implementation-defined
* Description of attributes alludes to getters/setters, which implies they map to accessors.  This matches the behavior of at least e.g. Chrome so seems to be the correct interpretation.

The current implementation of the Encoding API in minisphere (which will be obsolete soon ;-) matches these requirements so it seems I'm on the right track.

**Comment by svaarala** [comment]
Sounds good, it's great to get this feature into master. Adding a few text encoding primitives into the C API would then also make sense but let's look at that separately :)

**Comment by fatcerberus** [comment]
Huh, this didn't close when #975 got merged.  I'll do that now :)
