### ISSUE TITLE
How to bind class duktape to c++ 

### ISSUE THREAD

**Issue by zero-ui** [svaarala/duktape#964]
c++ code:
class object{
public:
object(char *a);
~object();
void add(){
k=i+j;
}
void sub(){
k=i-j;
}
private:
int i;
int j;
int k;
}

js:
var o = new object("test");
o.i=1;
o.j=2;
o.add();
priant(o.k);
o.sub();
priant(o.k);

I would like to ask how such a realization 
What we call the destructor

**Comment by svaarala** [comment]
This is more of a documentation issue and tracked by https://github.com/svaarala/duktape-wiki/issues/50, so closing.
