### ISSUE TITLE
Enumerating codepoints in a string?

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#967]
Is there any way to enumerate codepoints in a Duktape string?  To decode strings passed in from JS, e.g. for text rendering, so far I've been using Bjoern Hoehrmann's UTF-8 decoder:

* https://github.com/fatcerberus/minisphere/blob/master/src/shared/unicode.c#L9-L42

But this fails in case of non-BMP ("astral") codepoints: They are decoded to their individual surrogates because of the CESU-8 encoding.  It's possible to do the decoding in two passes to recombine the surrogates, but it would of course be easier if I could just enumerate codepoints directly. :)

Whose dumb idea was it to specify UTF-16 semantics for Ecmascript strings anyway?

(I suspect Duktape using "extended" UTF-8 might pose an issue for the above decoder too...)

**Comment by fatcerberus** [comment]
Hm, it seems the problem is worse than I initially thought.  Upon attempting to render the following string:

```
"🐽 PIG NOSE"
```

My text renderer first decodes the string using the above mentioned UTF-8 decoder, then converts it to Windows-1252.  The pig nose character is made up of two surrogate codepoints (`U+D83D` and `U+DC3D`); since I have no special handling for surrogates, these should be replaced with two "substitute" (0x1A) characters.  However what I actually get is **FOUR** 0x1A characters.  This behavior makes no sense to me, but since you know more about Duktape's internal string encoding, maybe you can enlighten me. :)

**Comment by svaarala** [comment]
You can do:

```
duk> x = 'foo\ucafebar'
= "foo\ucafebar"
duk> Array.prototype.forEach.call(x, function (cp) { print(cp.charCodeAt(cp)); })
102
111
111
51966
98
97
114
= undefined
```

This may be worth reading if you haven't: http://wiki.duktape.org/HowtoNonBmpCharacters.html.

**Comment by svaarala** [comment]
Note that the "extended" UTF-8 is never used by standard Ecmascript strings. All standard Ecmascript strings are 16-bit codepoint sequences encoded in CESU-8. They only come into play if you intentionally create them from C code or via buffer coercions.

**Comment by svaarala** [comment]
Allowing non-BMP is more of a convenience for C code which already deals with UTF-8. Having to convert to CESU-8 and back would be awkward *if* you don't care about your strings being outside of Ecmascript string space which is often the case for e.g. UI applications.

**Comment by fatcerberus** [comment]
I'm actually trying to enumerate codepoints from C.  While it's possible to set up a `forEach` call with the callback being a Duktape/C function, that's really awkward.

To clarify a bit: I'm trying to implement `TextEncoder` for #961.  According to the Encoding standard, this should encode the string in pure UTF-8--1-4 bytes per character, no surrogate pairs, no codepoints beyond 0x10FFFF.  In order to do that, the string must be decoded into its constituent codepoints first, which means relying on the internal representation of strings in Duktape not changing.  That's probably a safe bet, but still feels awkward.

**Comment by svaarala** [comment]
The closest thing might be: http://duktape.org/api.html#duk_decode_string.

**Comment by svaarala** [comment]
For implementing encoding/decoding I don't think there's a reasonable alternative to working with the byte representation directly. Making a function call per codepoint is quite slow compared to doing the necessary conversions on-the-fly.

While there's some potential for the internal representation to change, it must essentially be ASCII comaptible for the API to be convenient to use. UTF-8 is the logical API choice for international strings, and CESU-8 encodings for surrogate pairs to achieve the Ecmascript 16-bit-pure requirement. So, I don't see the internal representation changing quite easily unless some requirement changes.

**Comment by svaarala** [comment]
That said, Duktape does do case conversion etc with a function which does an internal (inlined) function call per codepoint. It's not ideal but the goal for the Unicode internals is to be as small as possible. That will likely change going forward to improve Unicode performance.

**Comment by fatcerberus** [comment]
...how did I never notice that function? :)

I agree with you though that dealing with the bytes of the string directly is more efficient.  I'll probably end up doing that, but it's good to know that a built-in facility exists in the API to do this.  Out of curiosity does `duk_decode_string()` process surrogates (combining them into a single codepoint), or leave them as-is?  I'm assuming the latter since that matches how Ecmascript code sees the string.

You can close the issue now if you want, I don't think there's anything else that needs to be solved here.

**Comment by svaarala** [comment]
Nothing in Duktape processes surrogate pairs as present, because there's no guarantee that the pairs are valid (which comes from the Ecmscript "any 16-bit codepoint sequence" string model).

**Comment by svaarala** [comment]
Ok, I'll close this :)

**Comment by fatcerberus** [comment]
Regarding that pig nose bug: I think it might just a double-encoding bug on my end.  Input source files are re-encoded as UTF-8 before passing to Duktape (to handle ANSI files with extended characters), and I suspect that might be what's expanding the pig nose character into 4 chars.

**Comment by fatcerberus** [comment]
Hm, apparently my UTF-8 decode function returns a "reject" status on encountering surrogate codepoints.  This throws the decode out of sync and it continues to reject the remaining bytes (replacing them with 0x1A) until it gets to the space.  I'll have to fix that :)
