### ISSUE TITLE
Support for typed arrays?

### ISSUE THREAD

**Issue by amerkoleci** [svaarala/duktape#99]
Any plans to add support for typed arrays?
I'm porting WebGL engine and thus would like to use them?

**Comment by svaarala** [comment]
Yes, there are plans to add bindings for both Node.js like Arrays and TypedArrays, both implemented using the same underlying mechanism. They should make Duktape 1.2 release in 2-3 months.

**Comment by svaarala** [comment]
This will be covered by #153 so closing.
