### ISSUE TITLE
Duktape sometimes uses CESU-8 for Ecmascript strings, sometimes not

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#996]
I found a weird encoding bug that sometimes causes the test below to fail in minisphere.  At first I thought the bug was in minisphere, but on investigating it actually looks like it's a Duktape bug (see below).

The original source text is UTF-8.

```js
	const assert = require('assert');
	var input = "Oh no, PIG! 🐽 *MUNCH*";  // contains pignose emoji
	var enc = new TextEncoder();
	var dec = new TextDecoder('utf-8');
	var buffer = enc.encode(input);  // returns Uint8Array
	var output = "";
	for (var i = 0; i < buffer.length; ++i) {
		var slice = buffer.subarray(i, i + 1);
		output += dec.decode(slice, { stream: true });
	}
	output += dec.decode();
	assert.ok(output === input, "UTF-8 roundtrip failed");
```

There's about a 1 in 4 chance for the code above to throw an AssertionError.  I thought the bug might be in `TextDecoder`, but that doesn't appear to be the case - it always outputs Ecmascript-compliant strings (i.e. the pignose is encoded as a surrogate pair).  What actually seems to be happening is that Duktape fails to normalize the string literal to CESU-8 as required by Ecmascript.  The input string is then not Ecmascript compliant and the roundtrip test fails.

If I change the input string to be ONLY a pignose emoji, then the test succeeds every time.  It only seems to blow up when plain text is mixed with supplemental characters.

**Comment by fatcerberus** [comment]
In case that wasn't clear since I have a tendency to over-explain :)

When the test code above fails, it's because `input` is improperly encoded.  Since that's assigned from a string literal, this suggests Duktape is at fault.

**Comment by svaarala** [comment]
That would be easy to demonstrate using:

    print(Duktape.enc('jx', ArrayBuffer.allocPlain(input)))

If the encoding is not CESU-8, it'd show up there.

**Comment by svaarala** [comment]
I think there are test cases to cover some of the non-BMP decoding and it isn't obviously broken:

```
duk> x = Duktape.dec('jx', '"\\U0001F4A9"')
= "\U0001f4a9"
duk> z = eval('"' + x + '"')
= "\ud83d\udca9"
```

The surrogate pairs are correct and match http://www.fileformat.info/info/unicode/char/1f4a9/index.htm.

Not to say there can't be some off-chance bug. But "1 in 4" sounds like memory corruption somewhere - any chance you could run under valgrind? It could also be some sort of lexer window issue, i.e. accessing beyond guaranteed window length or something.

**Comment by svaarala** [comment]
Hmm - actually no, the lexer window is for a lookahead of already decoded codepoints and that decoding process has access to the entire input string at the moment.

**Comment by svaarala** [comment]
```
((o) Duktape [linenoise] 1.99.99 (v1.5.0-675-g026080b)
duk> var input = "Oh no, PIG! 🐽 *MUNCH*";
= undefined
duk> input
= "Oh no, PIG! \ud83d\udc3d *MUNCH*"
```

That seems to match http://www.fileformat.info/info/unicode/char/1f43d/index.htm and I can't reproduce any issues.

Could you exclude TextEncoder/TextDecoder from the equation by e.g. printing a binary representation of `input` a bunch of times *before* TextEncoder/TextDecoder runs? With the theory that source code lexing is the problem, it would have to happen even without that step?

**Comment by fatcerberus** [comment]
I'll try that later.  A lexer/parser issue would make sense, as the occurrence used to be about 50/50 before I started adding more instrumentation (like the assert).  Even so, shouldn't it be deterministic?

**Comment by svaarala** [comment]
If you can reproduce it reliably, it would be easiest if you could add that string-to-buffer-to-JX dump for:
- "input" just after assigning it (before textencoder/textdecoder)
- "input" after the encode/decode process
- "output" after the encode/decode process

If you can catch the error in action, those three dumps would then show precisely where/what had changed.

As for determinism, if it's an outright bug it should be deterministic. So I'm suspecting more memory corruption, or maybe overwriting (read only) string data, or the like.

**Comment by fatcerberus** [comment]
I notice you added out of spec support for Unicode escapes to allow any codepoint to be escaped.  Now might be a good time to mention that ES6 has a standard format for that, see this article:
http://www.2ality.com/2015/01/es6-strings.html?m=1

**Comment by fatcerberus** [comment]
Huh, maybe the bug is on my end after all, though I can't imagine why it only fails sometimes...

```js
	const assert = require('assert');
	var input = "Oh no, PIG! 🐽 *MUNCH*";
	console.log("input:before", Duktape.enc('jx', ArrayBuffer.allocPlain(input)));
	var enc = new TextEncoder();
	var dec = new TextDecoder('utf-8');
	var buffer = enc.encode(input);  // returns Uint8Array
	var output = "";
	for (var i = 0; i < buffer.length; ++i) {
		var slice = buffer.subarray(i, i + 1);
		output += dec.decode(slice, { stream: true });
	}
	output += dec.decode();
	console.log("input:after ", Duktape.enc('jx', ArrayBuffer.allocPlain(input)));
	console.log("output      ", Duktape.enc('jx', ArrayBuffer.allocPlain(output)));
	assert.ok(output === input, "UTF-8 roundtrip");
```

On a successful run, all values match (naturally):
```
log: input:before |4f68206e6f2c205049472120eda0bdedb0bd202a4d554e43482a|
log: input:after  |4f68206e6f2c205049472120eda0bdedb0bd202a4d554e43482a|
log: output       |4f68206e6f2c205049472120eda0bdedb0bd202a4d554e43482a|
```

On a failing run (which seems to get harder and harder to trigger as I add more instrumentation):
```
log: input:before |4f68206e6f2c205049472120eda0bdedb0bd202a4d554e43482a|
log: input:after  |4f68206e6f2c205049472120eda0bdedb0bd202a4d554e43482a|
log: output       |4f68206e6f2c205049472120c3adc2a0c2bdc3adc2b0c2bd202a4d554e43482a|
```

`input.length` is always 22.  `output.length` is 26 on a failing run.

Clearly my UTF-8 decoder is emitting too many bytes, but I have no idea why.  Here's the contents of `buffer`:
```
= "|4f68206e6f2c205049472120f09f90bd202a4d554e43482a|"
```

Pasting that into an online UTF-8 decoder reveals a 4-byte sequence for the emoji character, which is correct.  So the encoder at least is not at fault.

**Comment by fatcerberus** [comment]
Here's the decoding breakdown for the corrupted output above.
```
U+004F LATIN CAPITAL LETTER O character
U+0068 LATIN SMALL LETTER H character
U+0020 SPACE character
U+006E LATIN SMALL LETTER N character
U+006F LATIN SMALL LETTER O character
U+002C COMMA character (,)
U+0020 SPACE character
U+0050 LATIN CAPITAL LETTER P character
U+0049 LATIN CAPITAL LETTER I character
U+0047 LATIN CAPITAL LETTER G character
U+0021 EXCLAMATION MARK character (!)
U+0020 SPACE character

--- corrupted UTF-8 codepoint starts here ---
U+00ED LATIN SMALL LETTER I WITH ACUTE character (&#x00ED;)
U+00A0 NO-BREAK SPACE character (&#x00A0;)
U+00BD VULGAR FRACTION ONE HALF character (&#x00BD;)
U+00ED LATIN SMALL LETTER I WITH ACUTE character (&#x00ED;)
U+00B0 DEGREE SIGN character (&#x00B0;)
U+00BD VULGAR FRACTION ONE HALF character (&#x00BD;)
--- end of corrupted UTF-8 codepoint ---

U+0020 SPACE character
U+002A ASTERISK character (*)
U+004D LATIN CAPITAL LETTER M character
U+0055 LATIN CAPITAL LETTER U character
U+004E LATIN CAPITAL LETTER N character
U+0043 LATIN CAPITAL LETTER C character
U+0048 LATIN CAPITAL LETTER H character
U+002A ASTERISK character (*)
```

Which renders as:
```
Oh no, PIG! í ½í°½ *MUNCH*
```

Source:
https://software.hixie.ch/utilities/cgi/unicode-decoder/utf8-decoder

I think I see what happened: The individual bytes of the surrogates were encoded as though they were Windows-1252.  I have no idea why that would have happened though...

**Comment by fatcerberus** [comment]
In any case, there doesn't appear to be a Duktape bug, but I'm not going to rule it out just yet.  I need to look into this a bit closer to get to the bottom of it.

**Comment by fatcerberus** [comment]
Well this is embarassing. :)

The bug is actually not in TextDecoder but instead there's some memory unsafe behavior in my string handling code:
https://github.com/fatcerberus/minisphere/blob/e5fafe2f8854b99a0db707d9f602789914fee566/src/shared/lstring.c#L338

The string passed in is checked to see if it's already UTF-8/CESU-8 encoded before interpreting it as CP-1252.  Validation goes until it sees a nul, except that there might not actually be one - the function takes a `length` parameter for that reason.  Why this didn't blow up on me more often, I don't know.

I'll close the issue, Duktape is not at fault.

**Comment by fatcerberus** [comment]
The bug above also explains the occasional corruption of the input string - if the string handler concludes "not UTF-8" for the original source code, it ends up being sent to Duktape double-encoded.

**Comment by svaarala** [comment]
> I notice you added out of spec support for Unicode escapes to allow any codepoint to be escaped. Now might be a good time to mention that ES6 has a standard format for that, see this article:
http://www.2ality.com/2015/01/es6-strings.html?m=1

There's actually no out-of-spec support now - but JX has a `\U` escape which supports up to 32 bits.

Adding that `\u{codepoint}` escape would make sense, and JX could also use it.

**Comment by svaarala** [comment]
> The bug is actually not in TextDecoder but instead there's some memory unsafe behavior in my string handling code [...]

Memory unsafe behavior sounded the most likely explanation. The results can often be subtle and they may appear in an unrelated location which is very annoying. Valgrind! :)

**Comment by fatcerberus** [comment]
Running minisphere under valgrind is extremely painful - it takes about 5 minutes just to get going, and then games run at around 1fps, making it very difficult to get it in position to trigger a bug.  That was my last resort if I couldn't find the issue, but I wanted to try more efficient means first.

Ironically though if I had thought to run the engine in the MSVC debugger I would have triggered the bug every time - since MSVC fills guard areas with I think 0xCC which is an invalid initial byte.

**Comment by svaarala** [comment]
I meant more Duktape testcases under valgrind. But now your pushes should trigger those runs, it just takes a lot of time for them to complete. But at least you don't need to do it manually :-)
